### ISSUE TITLE
考虑使用tokio runtime

### ISSUE THREAD

**Issue by xxfye** [shadowsocks/shadowsocks-rust#100]
https://github.com/tokio-rs/tokio

**Comment by zonyitoo** [comment]
现在不就是用的tokio么？

**Comment by zonyitoo** [comment]
噢，这是搞了一套新的Server框架啊……可以研究一下

**Comment by zonyitoo** [comment]
大部分迁移了。tokio-signal目前依然支持新的tokio接口，无法完全迁移。

**Comment by xxfye** [comment]
非常棒👍

**Comment by xxfye** [comment]
已经尝试`v1.7.0-alpha`，希望能代替几天一崩的Py版本，非常感谢。
不过临近高考，问题不一定会及时反馈。

**Comment by zonyitoo** [comment]
已经更新到alpha.4
