### ISSUE TITLE
Can SNI-based TCP tunnels be implemented?

### ISSUE THREAD

**Issue by jan-bar** [shadowsocks/shadowsocks-rust#1004]
I configure the tcp tunnel as follows
```json
{
    "protocol": "tunnel",
    "local_address": "127.0.0.1",
    "local_port": 443,
    "forward_address": "google.com",
    "forward_port": 443,
    "mode": "tcp_only"
}
```
Then configure the following host rules
```sh
127.0.0.1 translate.googleapis.com
127.0.0.1 github.com
127.0.0.1 google.com
```
But according to the tcp tunnel configuration, I can only access `curl https://google.com`

I want to automatically forward to the corresponding server according to my request, like below
```sh
curl https://translate.googleapis.com
curl https://github.com
curl https://google.com
```
I found a solution, you can use the `SNI` mechanism of `tls`

Here is an implementation: https://www.agwa.name/blog/post/writing_an_sni_proxy_in_go

I have done this functionality in my `SIP003` plugin (i use golang). But I'm not very good at rust, I hope this project can also support this feature

This feature can proxy all the addresses configured by the host on port 443 of the machine, and any client software can directly access it without configuring socks or http proxy

**Comment by database64128** [comment]
This usage pattern is quite unusual and I think it is also out of scope for a Shadowsocks implementation.

**Comment by jan-bar** [comment]
> This usage pattern is quite unusual and I think it is also out of scope for a Shadowsocks implementation.

Well, I don't like global proxies very much, this way is a good choice for me. I'm just proposing a solution, and I've realized it myself and benefited from it.

**Comment by database64128** [comment]
You can use ACL rules to achieve the same outcome.

> nginx also supports `SNI` to proxy different domain names, I think `SNI` can also be used in proxy.

That would require the program to understand HTTP/TLS/QUIC semantics. There are other proxy tools that have this feature, and their implementations are quite messy IMO. This approach also won't work in the future when the websites you visit start to support ECH. The author of this project wants to K.I.S.S. (keep it simple & stupid). So it's very unlikely for this to be implemented.
