### ISSUE TITLE
Allow 0 for local_port in sslocal

### ISSUE THREAD

**Issue by oscar-c** [shadowsocks/shadowsocks-rust#1008]
Right now `sslocal` does not allow `0` for `local_port` in config file.

bind to port 0 asks the kernel to allocate a port for the process.

Sometimes I don't want to specify a local_port nubmer when running `sslocal`. I just want it to run and am happy with whatever port it binds to.

**Comment by zonyitoo** [comment]
Then how can you know exactly which port it was binded to? How to use it without a known port?

**Comment by oscar-c** [comment]
> Then how can you know exactly which port it was binded to? How to use it without a known port?
In the log output, through looking up the process.

**Comment by zonyitoo** [comment]
Then you have to manually set the port in client by `grep`ing from `sslocal`'s log. Everything will be broken if `sslocal` restarts.

**Comment by oscar-c** [comment]
> `grep`ing from `sslocal`'s log. Everything will be broken if `sslocal` restarts.

I run `sslocal` periodically to check for the connection speed to my servers. I start a `sslocal`, get its port, run `curl` with proxy, then terminate `sslocal`. It's only going to be alive for less than 2 min each time. I don't need to worry about it restarts.

**Comment by zonyitoo** [comment]
I am not convinced. I don't think this is the expected usage of this project.

You can always run a `sslocal` instance listening to a fixed port and perform your test.

**Comment by oscar-c** [comment]
K
