### ISSUE TITLE
webpage github.com/shadowsocks/shadowsocks-rust isn't loading

### ISSUE THREAD

**Issue by A2Sumie** [shadowsocks/shadowsocks-rust#1015]
I don't understand. It keeps giving me an unicorn.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/89308692/204007083-6e5c3639-5f84-447a-b09e-d4becff98643.png">
I'm in Japan so nothing to do with censorship or network.
issues and release page can be properly opened by manually entering the address.
Other shadowsocks repos are also fine.
Changed browsers and flushed cache and tried my cellular network but none would work.

**Comment by zonyitoo** [comment]
Well then, maybe the GitHub server that serving this repo/page to you was down somehow. Since you can actually saw GitHub‘s error page, your network connection was Ok.
