### ISSUE TITLE
sslocal 只发送 target address 不发送 payload

### ISSUE THREAD

**Issue by totravel** [shadowsocks/shadowsocks-rust#1023]
sslocal 和服务器建立连接后，只发送了 target address。服务器可以得到 target 的地址并与之建立连接，之后就一直在等待 sslocal 发送 payload。根据 [文档](https://github.com/shadowsocks/shadowsocks-org/wiki/Protocol)，sslocal 不是应该在发送 target address 之后接着发送 payload 吗？

**Comment by zonyitoo** [comment]
If the answer is No, then this project is completely broken.

You should take a deeper look to your client whether it actually sent payload to `sslocal` after connected.

**Comment by totravel** [comment]
好吧，我确实有点仓促了，不好意思，但我确实通过实验观察到这一现象，下面是详细信息，麻烦你帮忙看一下：

sslocal 和 ssserver 都工作在本地，ssserver 监听在 8787 端口。这是我使用的配置：

```json
{
    "server": "127.0.0.1",
    "server_port": 8787,
    "password": "123456",
    "method": "aes-256-gcm",
    // ONLY FOR `sslocal`
    // Delete these lines if you are running `ssserver` or `ssmanager`
    "local_address": "127.0.0.1",
    "local_port": 1080
}
```

这是启动 sslocal 用的命令和输出：

```bash
$ ./sslocal -c config.json -v
2022-11-29T16:39:52.343904900+08:00 INFO  [17216:9540] [shadowsocks_rust::service::local] shadowsocks local 1.14.3 build 2022-04-04T17:19:11.998958100+00:00
2022-11-29T16:39:52.347103800+08:00 INFO  [17216:2096] [shadowsocks_service::local::socks::server] shadowsocks socks TCP listening on 127.0.0.1:1080
2022-11-29T16:40:03.018313800+08:00 DEBUG [17216:5104] [shadowsocks_service::local::socks::server::socks5::tcprelay] CONNECT www.baidu.com:80
2022-11-29T16:40:03.019489200+08:00 DEBUG [17216:5104] [shadowsocks_service::local::utils] established tcp tunnel 127.0.0.1:59531 <-> www.baidu.com:80 through sever 127.0.0.1:8787 (outbound: 127.0.0.1:8787)
```

客户端是 curl。这是我使用的 curl 命令：

```bash
$ curl www.baidu.com -x socks5h://127.0.0.1:1080 -v
*   Trying 127.0.0.1:1080...
* SOCKS5 connect to www.baidu.com:80 (remotely resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)
> GET / HTTP/1.1
> Host: www.baidu.com
> User-Agent: curl/7.83.1
> Accept: */*
>
```

可以看到 curl 已经把 payload 发给 sslocal：

![from client to sslocal](https://user-images.githubusercontent.com/22211266/204482082-ed4b171b-4536-48da-b08d-eaaf173c3b39.png)

但是 sslocal 全程只发给服务器 160 字节：

![from sslocal to ssserver](https://user-images.githubusercontent.com/22211266/204483192-e4120511-aba2-4ad8-829c-88b75dc75c57.png)

**Comment by zonyitoo** [comment]
Did you remove these two lines for `ssserver`?

```
    "local_address": "127.0.0.1",
    "local_port": 1080
```

**Comment by totravel** [comment]
不好意思，是我错怪 shadowsocks-rust 了。shadowsocks-rust 的 sslocal 没有问题，它向 ssserver 发送的 160 字节已经包含 payload 了。

令我感到意外的是，shadowsocks-rust 的 sslocal 的行为确实和其他 sslocal 有所不同。具体来说，shadowsocks-rust 把 target address 和 payload 合在一起进行加密和解密，最终只会形成一个 encrypted chunks，而其他 sslocal 则对它们分别进行加密和解密，最终会形成两个 encrypted chunks。

**Comment by zonyitoo** [comment]
> 而其他 sslocal 则对它们分别进行加密和解密，最终会形成两个 encrypted chunks。

This is wrong. It will generate an obvious pattern in data flow, which will make your servers easily detectable.
