### ISSUE TITLE
请教大佬：华硕ax88u梅林固件应该用哪个平台的编译好的程序？

### ISSUE THREAD

**Issue by hedsbj** [shadowsocks/shadowsocks-rust#1024]
想手动更新一下科学插件

**Comment by zonyitoo** [comment]
https://www.broadcom.com/products/wireless/wireless-lan-infrastructure/bcm49408

ARMv8, aarch64

**Comment by hedsbj** [comment]
多谢您的回复,找了一下,预编译好的二进制程序 中似乎没有针对 这个平台的?
