### ISSUE TITLE
Passing server traffic to multiple network interface

### ISSUE THREAD

**Issue by bart3nder** [shadowsocks/shadowsocks-rust#1027]
Hello y'all!
I'm running `ssserver` like `ssserver -c config.json --outbound-bind-interface eth1` to pass all traffic to `eth1` interface, Using  this config:

```
{
    "servers": [
        {
            "address": "0.0.0.0",
            "mode":"tcp_and_udp",
            "port":80,
            "password":"Password",
            "timeout":60,
            "method":"chacha20-ietf-poly1305"

        },
        {
            "address": "0.0.0.0",
            "mode":"tcp_and_udp",
            "port":443,
            "password":"Password",
            "timeout":60,
            "method":"chacha20-ietf-poly1305"

        },
      
    ],
}
```
And it works just fine. The question is, Is there any option / solution or plans to add a feature that user can pass traffic from one port to interface X and another port to interface Y? In the above config I want to pass server traffic on port 80 to `eth1` and the server on port 443 to `eth2`

**Comment by zonyitoo** [comment]
Well, why not just launch 2 different `ssserver` instances which listens to specific ports and bind to their corrsponding interfaces?

**Comment by bart3nder** [comment]
Actually I was doing the exact same thing while using ss-libev and ss-rust, But since I recently found extended configuration format and gotta say I really liked it (both ease of use and performance aspect), I was looking for achieving that point in one config and without getting back to my previous setup. Anyway, If there is a chance to add this little feature, I would appreciate it. Thanks!

**Comment by zonyitoo** [comment]
I wouldn’t say that it is impossible to implement. It is quite easy to make each server instances to use different outbound configurations. But how about the DNS resolver? (Currently the DNS resolver doesn’t use the outbound configurations, but may be in the future it can actually do.)

If anyone who interested in making this work, feel free to open a PR.

**Comment by bart3nder** [comment]
Great!
