### ISSUE TITLE
help: use vps in vultr.com to build ssserver, but blocked after 4days

### ISSUE THREAD

**Issue by caoweiju** [shadowsocks/shadowsocks-rust#1028]
## build ssserver
build step:
1. vps: normal vps in vultr.com
2. build config: only port 22 is ok(other port was blocked by gfw),use chacha20-ietf-poly1305;
3. plugin: no plugin

everything work ok, my phone connect ssserver, but after 3days, connect was blocked, 
i have tried many times, three vps has the same sutiation, after few days, port was blocked;

what is the problem.

**Comment by zonyitoo** [comment]
I don't think this is a technical issue about shadowsocks-rust.
