### ISSUE TITLE
"aes-256-cfb" Method Not Supported

### ISSUE THREAD

**Issue by GoldenLighter** [shadowsocks/shadowsocks-rust#1041]
```
{
    "server": "0.0.0.0",
    "server_port": 45623,
    "password": "xxx",
    "method": "aes-256-cfb"
}

```
Hi dear manager,
Why "aes-256-cfb" method is not supported on windows?
Command is :
`ssserver -c config.json`
I put libsodium dll on windows System32 & SysWow64 folders.
But still does not work.
Please give a solution about methods using with this package on windows os.

References : 
[https://py-ipv8.readthedocs.io/en/latest/preliminaries/install_libsodium.html](https://py-ipv8.readthedocs.io/en/latest/preliminaries/install_libsodium.html)

[https://download.libsodium.org/libsodium/releases/](https://download.libsodium.org/libsodium/releases/)

[https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip](https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-msvc.zip)

**Comment by zonyitoo** [comment]
stream ciphers are deprecated and disabled by default. If you know the risk and insist to use these vulnerable ciphers, compile it yourself.

**Comment by GoldenLighter** [comment]
Please list supported methods here.

Your app is working very well on windows.
But i am looking for a app to connect shadowsocks on server and show a port to connect it on local.
SSCap.exe was ok for this purpose.
But it does not support any of your methods.
Any idea?

**Comment by zonyitoo** [comment]
Read the doc before asking questions: https://github.com/shadowsocks/shadowsocks-rust#supported-ciphers

Your question could be easily searched in Google: https://github.com/net4people/bbs/issues/24

**Comment by zonyitoo** [comment]
What is SSCap? What feature does it provides

**Comment by GoldenLighter** [comment]
v2rayN can do this job and SSCap has depricated now.
But sometimes depricated softs are better than chinese softs :)

**Comment by zonyitoo** [comment]
https://github.com/tarolabs/sscap

It is a Windows client created by Chinese. There are various clients work like it, such as shadowsocks-windows.
