### ISSUE TITLE
How run ssstart.exe at boot

### ISSUE THREAD

**Issue by GoldenLighter** [shadowsocks/shadowsocks-rust#1043]
How to run ssserver.exe at reboot?
By running ssservice.exe nothing happens!!!

**Comment by zonyitoo** [comment]
Use Google instead of opening an issue right here.

**Comment by GoldenLighter** [comment]
I know about other ways using with google.
I want to know what is the job ssservice.exe file and after running what will happen on server!
Does it install a service on services area to run ssserver.exe auto?
If yes after running it i could n't find related service.

**Comment by zonyitoo** [comment]
ssserver is just a program that runs a shadowsocks server, which receives requests from sslocal and forwards it to remote target servers.

**Comment by ahmeaqas** [comment]
you can find a step by step guide for installing and configuring the shadowsocks server and client i.e. [Unlocking the Internet: A Step-by-Step Guide to Setting Up Your Own Shadowsocks-Rust Proxy Server on Linux](https://hobbytronics.pk/unlocking-the-internet-a-step-by-step-guide-to-setting-up-your-own-shadowsocks-rust-proxy-server-on-linux/). Just visit Step 5: Create a Systemd Service.
