### ISSUE TITLE
aes-pmac-siv 错误

### ISSUE THREAD

**Issue by e2ge** [shadowsocks/shadowsocks-rust#105]
版本1.6.12
cargo build --release --features miscreant

客户端win7，nightly-msvc ABI，以下错误提示后客户端中止退出：
Illegal instruction

服务端Centos，nightly-gnu ABI，错误提示：
[ERROR] AEAD decrypt failed, nonce=b"\x00\x00\x00\x00\x00\x00\x00\x00", input=b"$R", tag=b"\x15Yx5\x15\x0ce\t\xf9\x1b\xc1\xa4\x06\x93\x8e\xa2", err: decrypt failure
[ERROR] Failed to handle client (...): failed to decode Address, may be wrong method or key, peer: ...
[ERROR] Failed to handle client (...): failed to decode Address, may be wrong method or key, peer: ...

**Comment by zonyitoo** [comment]
1. 请clone [此repo](https://github.com/miscreant/miscreant/tree/master/rust) 然后执行 `cargo test` 及 `cargo test --release`，测试是否会报 `Illegal instruction`，若会，说明此crate编译有问题（大概率怀疑是你所运行的CPU不支持AES指令），把相关信息提Issue给miscreant。

2. 此错误提示就是服务端无法正常解码，一般来讲就是加密方式不匹配，或纯粹就是密码写错了。请先检查Client及Server端加密方式是否一样，且Password是否一样。

若确认配置没有问题，请提供Client版本及你使用的配置（Client端及Server端配置），我要重现。

**Comment by e2ge** [comment]
client是我自己在本机上编译的，版本1.6.12，编译过程没有报错。
OPENSSL_DIR=C:\\\OpenSSL-Win64 OPENSSL_STATIC=yes SODIUM_BUILD_STATIC=yes cargo build --release --features miscreant

配置文件：
{
    "servers": [
        {
            "address": "xxx.com", "port": 8338,
            "password": "xxx", "method": "aes-256-gcm", "timeout": 300
        }
    ],
    "local_port": 1080,
    "local_address": "127.0.0.1"
}

**Comment by zonyitoo** [comment]
Client也是`shadowsocks-rust`吗？我现在就在用`aes-pmac-siv`，使用非常正常啊……

**Comment by e2ge** [comment]
是的，client也是rust版本的ss，可能是不支持aes的缘故？等我换个电脑试试再来报告。

**Comment by zonyitoo** [comment]
Segmentation fault就是Illegal instruction，差不多的。
实际上不支持AES指令的话，应当使用代码模拟版本的AES加密的，这个库没有做好，强行用AESNI

**Comment by e2ge** [comment]
ok，谢谢，期待进一步的升级，辛苦。

**Comment by zonyitoo** [comment]
你这个问题应该向`miscreant`提issue，让他们看看针对你的CPU应该要怎么判断

**Comment by quininer** [comment]
更新到 0.4-beta 可解決 https://github.com/miscreant/miscreant/pull/177

**Comment by zonyitoo** [comment]
@e2ge 是否已经Fix？
