### ISSUE TITLE
I believe sslocal running in redir mode lacks v4v6 dual stack support?

### ISSUE THREAD

**Issue by Originalimoc** [shadowsocks/shadowsocks-rust#1052]
Configured  and confirmed from netstat to listen on [::]:1080. But then IPv4 won't work. libev ver ss-redir can. Or I configured it wrong?

**Comment by zonyitoo** [comment]
dual-stack on Linux/FreeBSD is only supported since [v1.15.0-alpha.9](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.15.0-alpha.9) .

**Comment by Originalimoc** [comment]
Huh I'm on alpha 8. It said TProxy I thought it wasn't what I'm using XD. I'll test it later.
