### ISSUE TITLE
segfault after update from 1.14.3 to 1.15.0

### ISSUE THREAD

**Issue by abubaca4** [shadowsocks/shadowsocks-rust#1053]
Starting without error, crashes when try to connect
error in dmesg
`[1349465.234644] tokio-runtime-w[51940]: segfault at 29 ip 0000563c44f39c6e sp 00007f1ca555b490 error 4 in ssserver[563c44c00000+4a2000]

[1349465.234687] Code: 66 66 66 2e 0f 1f 84 00 00 00 00 00 48 8b 8c 24 00 02 00 00 48 83 f9 20 0f 83 de 00 00 00 48 85 c0 0f 84 6c 01 00 00 48 89 c1 <48> 8b 40 08 0f b6 51 20 89 d6 83 e6 01 8d 34 b6 89 f7 83 cf 0a f6`

running in VPS with two core of AMD EPYC 7551 and one Gb of Ram

config
`{
    "server": "::",
    "server_port": cleaned,
    "password": "cleaned",
    "method": "aes-128-gcm",
    "mode": "tcp_only",
    "fast_open": true,
    "reuse_port": true,
    "no_delay": true,
    "plugin": "xray-plugin_linux_amd64",
    "ipv6_first": true,
    "plugin_opts": "server"
}`

**Comment by zonyitoo** [comment]
Which `rustc` version are you using?

**Comment by abubaca4** [comment]
> Which `rustc` version are you using?

Just archive from release page
https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.15.0/shadowsocks-v1.15.0.x86_64-unknown-linux-gnu.tar.xz

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.15.1

Please upgrade to v1.15.1 and see if it fixes.

**Comment by abubaca4** [comment]
1.15.1 work without errors
