### ISSUE TITLE
NatTypeTester shows UdpBlocked

### ISSUE THREAD

**Issue by quanljh** [shadowsocks/shadowsocks-rust#1055]
I'm using v1.15.1 and v2ray plugin 5.1.0.
Server config:
```json
{
    "server":"0.0.0.0",
    "server_port":17892,
    "password":"password",
    "timeout":300,
    "method":"aes-128-gcm",
    "ipv6_first": false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"v2ray-plugin",
    "plugin_opts":"mux=0;server;path=/aaa"
}
```
Client config
```json
{
    "server": "server host",
    "server_port": 17892,
    "password": "password",
    "method": "aes-128-gcm",
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "mode": "tcp_and_udp",
    "plugin": "v2ray-plugin",
    "plugin_opts": "mux=0;host=serverhost;path=/aaa",
    "log": {
        "level": 1,
        "format": {
            "without_time": false
        }
    }
}
```
I tried to use NatTypeTester to check my NAT type but I got "UdpBlocked" with the correct socks5 setting
Log:
![image](https://user-images.githubusercontent.com/38105306/208296228-5aebee98-96c0-4c55-9099-75502f8ff72e.png)

I tried Xray, V2ray vlite protocol and can get "FullCone" results.

I'm not sure what I'm doing wrong.

**Comment by zonyitoo** [comment]
You could try it locally (run both `sslocal` and `ssserver` in the same local network) and see if it can still reproduce.

**Comment by zonyitoo** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/1067951/208308886-e73ea2e3-2a30-4766-bf84-072e0549b79e.png">

It worked as expected in my VM. And I have also asked the author of NatTypeTester, and he couldn't reproduce this issue, too.

**Comment by quanljh** [comment]
Thanks for your reply.

Weird, If it works on your machine, then it should be no issue with shadowsocks proxy. 

> You could try it locally (run both `sslocal` and `ssserver` in the same local network) and see if it can still reproduce.

I'll check tonight.

> BTW, how is your network configuration? 

What kind of network configuration I should provide? I'm using Win11. I suppose it's some settings related to SS specifically because I don't have issues when using V2rayN with Xray or V2ray-vlite.

**Comment by zonyitoo** [comment]
Someone couldn't reproduce with exactly the same configuration as yours.

**Comment by quanljh** [comment]
I'll try to debug NatTypeTester to see if I can get any useful exceptions/info

**Comment by quanljh** [comment]
Sorry, I made a big mistake, my ss server is using shadowsocks+ws+tls but I haven't setup the udp port-forwarding which caused the issue. 
Thanks for the help. Closing this issue.
