### ISSUE TITLE
source port can‘t sync forward

### ISSUE THREAD

**Issue by ziojacky** [shadowsocks/shadowsocks-rust#1064]
i use redir protocol in local, server forward will made new connect and new random source port to destination address and port, have any way to keep local source port sync server forward?

**Comment by zonyitoo** [comment]
I couldn't get what you mean. What is "keep local source port sync server forward"?

**Comment by ziojacky** [comment]
> I couldn't get what you mean. What is "keep local source port sync server forward"?

look this: https://github.com/xtaci/kcptun/issues/897

**Comment by ziojacky** [comment]
for example:

ss normal proxy process 
10.0.0.1:1001 -> 1.1.1.1:443 -> 10.0.0.1:1234 (local ss-redir) -> 1.2.3.4:1234 (ss server) -> 1.2.3.4:random port -> 1.1.1.1:443

expected function
10.0.0.1:1001 -> 1.1.1.1:443 -> 10.0.0.1:1234 (local ss-redir) -> 1.2.3.4:1234 (ss server) -> 1.2.3.4:1001 -> 1.1.1.1:443

not use random port proxy, use same client source port to proxy.

**Comment by zonyitoo** [comment]
This is impossible. If the outbound port keep exactly the same as the client's, then how to handle different clients with the same port?

The shadowsocks works just like a symmetric NAT service, which will make a 1-to-1 mapping for a local port and outbound port. There is no NAT service that could guarantee that the outbound port can be exactly the same as the local source port.

On the other hand, why would you require this feature? What kind of service would require the clients' port to be fixed?

**Comment by ziojacky** [comment]
> This is impossible. If the outbound port keep exactly the same as the client's, then how to handle different clients with the same port?
> 
> The shadowsocks works just like a symmetric NAT service, which will make a 1-to-1 mapping for a local port and outbound port. There is no NAT service that could guarantee the outbound port can be exactly the same as the local source port.
> 
> On the other hand, why would you require this feature? What kind of service would require the clients' port to be fixed?

fixed same port mainly used for some p2p services, these services need specified port, so proxy server need keep same local soruce port to get return date.

**Comment by zonyitoo** [comment]
To achieve you goal, the proxy service will become some kind of tunnel that directly maps the client local port in the server, which in the end the server can only serve one client. If you have multiple clients, or machines, you will have to use different servers, or simply different network interfaces with different outbound IPs.

I don't think this is a general service, so it wouldn't be implemented in shadowsocks-rust.

Further more, for P2P services, normally they will first use UDP punching a hole on NAT, and then connect each others with the punched port.
