### ISSUE TITLE
Add support for reloading acl at runtime

### ISSUE THREAD

**Issue by ArchGuyWu** [shadowsocks/shadowsocks-rust#1065]
For those who are using a dynamic ip adress, they can not determine their ip address/ip range, and need to modify their acl list more often. Allowing modify acl list at runtime maybe a good feature for them.

**Comment by zonyitoo** [comment]
What do you mean dynamic ip address?

**Comment by ArchGuyWu** [comment]
An IP address that an ISP lets you use temporarily.

**Comment by zonyitoo** [comment]
Why is that going into the ACL file?

**Comment by ArchGuyWu** [comment]
Because I don't want others to connect my shadowsocks server, and this can also help to defend against GFW.

**Comment by ArchGuyWu** [comment]
Or can only add support for reloading acl list at time.

**Comment by dev4u** [comment]
> Because I don't want others to connect my shadowsocks server, and this can also help to defend against GFW.

ipset+iptables效果可达

**Comment by ArchGuyWu** [comment]
> > Because I don't want others to connect my shadowsocks server, and this can also help to defend against GFW.
> 
> ipset+iptables效果可达

确实如此，但还是希望能支持acl运行时重载

**Comment by zonyitoo** [comment]
It doesn't need lots of work to make ACL auto-reloadable. But it will make the `AccessControl` structure become a wrapper wrapped a 2 levels `Arc`, which will controlled by a notify task monitoring the file events.
