### ISSUE TITLE
udp failed to send back 1402 bytes to client, error: Message too long

### ISSUE THREAD

**Issue by ArchGuyWu** [shadowsocks/shadowsocks-rust#1066]
`udp failed to send back 1402 bytes to client [::ffff:a.b.c.x]:4860, from target 178.63.98.68:443, control: UdpSocketControlData { client_session_id: 8402938654779882522, server_session_id: 5391500292745882023, packet_id: 16, user: None }, error: Message too long (os error 90)`

**Comment by zonyitoo** [comment]
Yes, it is too long for a UDP packet.

**Comment by ArchGuyWu** [comment]
> Yes, it is too long for a UDP packet.

So I should just modify sysctl conf?

**Comment by zonyitoo** [comment]
How did you fix?
