### ISSUE TITLE
failed to compile `shadowsocks-rust v1.6.12`

### ISSUE THREAD

**Issue by windmonk** [shadowsocks/shadowsocks-rust#107]
# cargo install shadowsocks-rust

when i use cargo to install ss , the bug appeared. 
how can i fix it ,thx!

   ...
   Compiling openssl-sys v0.9.30
   Compiling unicode-bidi v0.3.4
   Compiling unreachable v1.0.0
   Compiling regex-syntax v0.6.0
   Compiling humantime v1.1.1
   Compiling foreign-types v0.3.2
   Compiling block-buffer v0.3.3
   Compiling textwrap v0.9.0
   Compiling qrcode v0.5.0
   Compiling base64 v0.9.1
   Compiling serde_json v1.0.17
   Compiling crossbeam-epoch v0.3.1
   Compiling crossbeam-epoch v0.4.1
   Compiling bytes v0.4.7
   Compiling mio v0.6.14
   Compiling msdos_time v0.1.6
   Compiling futures-cpupool v0.1.8
   Compiling tar v0.4.15
   Compiling aho-corasick v0.6.4
   Compiling tokio-timer v0.2.3

error: failed to compile `shadowsocks-rust v1.6.12`, intermediate artifacts can be found at `/tmp/cargo-install9MxSMO`

Caused by:
  failed to run custom build command for `openssl-sys v0.9.30`
process didn't exit successfully: `/tmp/cargo-install9MxSMO/release/build/openssl-sys-3d3d8372bfca9942/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.30

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.30/build.rs:212:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by windmonk** [comment]
囧  看了之前的提问 是路径原因编译失败?

**Comment by zonyitoo** [comment]
You can download prebuilt binaries for Linux from here: https://github.com/shadowsocks/shadowsocks-rust/releases .

**Comment by windmonk** [comment]
thx !! I get the binaries edition.
