### ISSUE TITLE
使用AES系列密码套件会导致UDP被封

### ISSUE THREAD

**Issue by ArchGuyWu** [shadowsocks/shadowsocks-rust#1077]
所使用的密码套件为2022-blake3-aes-256-gcm，所使用的端口为[此处](https://it-tools.tech/random-port-generator)获取的随机端口
起初只开启了一个使用2022-blake3-chacha20-poly1305密码套件的SS端口(简称**ChaCha20端口**)并一直使用到现在，几天前增加了一个使用2022-blake3-aes-256-gcm密码套件的SS端口(简称**AES端口**)，但今早AES端口的UDP被封锁了，更换AES端口的端口号后在今天下午又遭封锁，但ChaCha20端口的UDP仍然正常

**Comment by database64128** [comment]
This couldn't even be called an experiment. Your setup is flawed and cannot lead to the conclusion in your title.

**Comment by ArchGuyWu** [comment]
好的，那我先关掉这个issue，然后发个新issue统计一下遇到这种情况的案例，如果报告的多了麻烦看一下
