### ISSUE TITLE
AEAD具体加密流程？

### ISSUE THREAD

**Issue by xxfye** [shadowsocks/shadowsocks-rust#110]
最近在翻阅SS文档，对AEAD有些疑惑，故来请教，问题如下：
1. sub-key有什么用？一定要实现吗？
1. nonce递增如何解决sslocal和ssserver同时向对方发送chunk导致两边都无法解密问题？
1. 对于udp代理，ssserver和sslocal间也是udp吗，丢包怎么办😱？

**Comment by zonyitoo** [comment]
1. 请阅读SIP-007 
> AEAD ciphers require a per-session subkey derived from the pre-shared master key using HKDF, and use the subkey
> to encrypt/decrypt. Essentially it means we are moving from (M+N)-bit (PSK, nonce) pair to
> (M+N)-bit (HKDF(PSK, salt), nonce) pair. Because HKDF is a PRF, the new construction significantly expands the
> amount of randomness (from N to at least M where M is much greater than N), thus correcting the previously
> mentioned design flaw.
2. 不理解你的问题，为什么会出现两边都无法解密
3. udp本身就会丢包，该怎么办就怎么办

**Comment by zonyitoo** [comment]
Close for inactive.
