### ISSUE TITLE
Multiuser on single port

### ISSUE THREAD

**Issue by miladrahimi** [shadowsocks/shadowsocks-rust#1100]
I've used the following config to setup multiple user on single port.
```json
{
  "servers": [
    {
      "address": "0.0.0.0",
      "port": 8388,
      "method": "chacha20-ietf-poly1305",
      "password": "secret",
      "timeout": 7200,
      "mode": "tcp_only",
      "users": [
        {
          "name": "someone",
          "password": "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE="
        }
      ]
    }
  ]
}
```
Clients can connect using "secret" password but "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" (the user password) doesn't work.
Where is my mistake?

**Comment by zonyitoo** [comment]
https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-2-shadowsocks-2022-extensible-identity-headers.md

Read the doc. You must use a client that supports AEAD-2022 Extensible Identity Headers. The password in client should be: `secret:YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=` some how.
