### ISSUE TITLE
ssmanager with ipv6_first option doesn't work as expected

### ISSUE THREAD

**Issue by ntzyz** [shadowsocks/shadowsocks-rust#1101]
For example, with the following configuration:

```json
{
  "servers": [{
    "address": "::",
    "port": 34156,
    "password": "redacted",
    "method": "aes-256-gcm"
  }],
  "dns": "2001:4860:4860::8888",
  "mode": "tcp_and_udp",
  "manager_address": "127.0.0.1",
  "manager_port": 55001,
  "ipv6_first": true
}
```

The server will always establish connections using IPv4 unless the website is IPv6 only:

```
$ all_proxy=127.0.0.1:6152 curl -s cloudflare.com/cdn-cgi/trace | grep ip
ip=103.152.<redacted>.<redacted>
$ all_proxy=127.0.0.1:6152 curl -s ipv6.ip.sb
2406:4440:<redacted>::<redacted>
```

However, there is no such issue when using this same configuration with `ssserver`.

```
$ all_proxy=127.0.0.1:6152 curl -s cloudflare.com/cdn-cgi/trace | grep ip
ip=2406:4440:<redacted>::<redacted>
```

An attempt to fix the issue was made in this commit: https://github.com/ntzyz/shadowsocks-rust/commit/f51769caba69d012251e2eaf6e6ac3cdaf2f68c9. Please let me know if the patch is acceptable, I'd like to create a pull request if it's okay.

**Comment by zonyitoo** [comment]
You don't need to put `ipv6_first` in `ManagerConfig`. The only thing you should do is to add `manager.set_ipv6_first(config.ipv6_first)` right after:
https://github.com/shadowsocks/shadowsocks-rust/blob/1c9bac427ed3effac9cfe60b40482ef4085471d2/crates/shadowsocks-service/src/manager/mod.rs#L67

Everything should work as expected.
