### ISSUE TITLE
mulitple users on single port

### ISSUE THREAD

**Issue by miladrahimi** [shadowsocks/shadowsocks-rust#1102]
I want to set up Shadowsocks on multiple servers behind a load balancer (HA Proxy), but since Shadowsocks create users with different ports, it's hard to manage.
Is there any way to define users with single port?

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/master/README.md#configuration

AEAD-2022 Extensible Identity Headers
