### ISSUE TITLE
插件是否也会遵循 `--user` 选项所指定的用户？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-rust#1105]
当我使用 [qtun](https://github.com/shadowsocks/qtun) 插件时：
```sh
# 日志显示的证书目录 /root/.acme.sh/example.com
ssservice local --config ./local.json

# 日志显示的证书目录 /root/.acme.sh/example.com
ssservice local --user nobody --config ./local.json
```

当我使用 [xray-plugin](https://github.com/teddysun/xray-plugin) 插件时：
```sh
# 日志显示的证书目录 /root/.acme.sh/example.com
ssservice local --config ./local.json

# 日志显示的证书目录 //.acme.sh/example.com
ssservice local --user nobody --config ./local.json
```

请问为什么在使用 qtun 插件的时候，即使我指定了 `--user nobody`, 它读取到的证书目录也是在 `/root` 下？

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/92c218d828bc9eef6734c7c5c0b0493e8d26f7c1/crates/shadowsocks/src/plugin/ss_plugin.rs#L17-L23

Plugin starts without changing the uid, so the process should run with the user specified by `--user`.

As for the problem about the path of cert, you should open an issue to qtun, there is nothing related to shadowsocks-rust.
