### ISSUE TITLE
UPX compression issue in current(v1.15.2) release.

### ISSUE THREAD

**Issue by riKirsti** [shadowsocks/shadowsocks-rust#1120]
I noticed that the UPX has a compression issue in the release github action [logs](https://github.com/shadowsocks/shadowsocks-rust/actions/runs/3770207229/jobs/6409902514#logs). Probably also in the former release.
![UPX Compression Issue](https://user-images.githubusercontent.com/81143735/219926438-b311af86-6f08-4b8f-b2bb-5975168d3303.png)
It was a known [bug](https://github.com/upx/upx/issues/476) and had already been fixed in [upx v4.02](https://github.com/upx/upx/commit/78f48d65d578765726d4c061ad8bc0d1b423811e). But the main Linux distributions still only use upx 3.96, so does the github action [ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md).
I have a temporary workaround for this. Download and use the precompiled version of UPX in [build-release.yml](https://github.com/shadowsocks/shadowsocks-rust/blob/master/.github/workflows/build-release.yml#L59) instead of apt-get install -y upx.
`wget -q https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz -O /tmp/upx-4.0.2.tar.xz&&mkdir -p /tmp/upx&&xz -d -c /tmp/upx-4.0.2.tar.xz | tar -x -C /tmp/upx;
chmod +x /tmp/upx/upx-4.0.2-amd64_linux/upx&&export PATH=/tmp/upx/upx-4.0.2-amd64_linux:$PATH;` 
I got compression success and they are function well on my OpenWrt router for a month. Also tested on the lasted shadowsocks-rust [commit](https://github.com/shadowsocks/shadowsocks-rust/commit/49df0ebbedef68874aac6b984e9c5b1762783691).
![UPX Success](https://user-images.githubusercontent.com/81143735/219931569-8794b46f-4bc7-4a29-970b-bdc88d05eadd.png)
![compare](https://user-images.githubusercontent.com/81143735/219932013-a9ad3fb1-b5ec-44fc-ac86-ddaf9fb6e213.png)
 
BTW, based on the UPX [doc](https://github.com/upx/upx/blob/devel/doc/upx.pod#compression-levels--tuning), I recommend use `upx --lzma --best` instead of `upx -9` in [build-release](https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/build-release#L41) to get better compression ratio and I can confirm this will not break shadowsocks-rust's functions.

Thank you for your remarkable efforts on this great project.

**Comment by zonyitoo** [comment]
I am Ok for these changes. Please make a PR.

**Comment by riKirsti** [comment]
PR for this. https://github.com/shadowsocks/shadowsocks-rust/pull/1123
