### ISSUE TITLE
`xchacha20-ietf-poly1305` is not a supported method

### ISSUE THREAD

**Issue by kojirou1994** [shadowsocks/shadowsocks-rust#113]

**Comment by zonyitoo** [comment]
Yes. We didn't support this method. And it is not a "required" method in shadowsocks.

**Comment by zonyitoo** [comment]
Ref: https://github.com/briansmith/ring/issues/411

**Comment by zonyitoo** [comment]
Uses `xchacha20-ietf-poly1305` provided by `libsodium`. Switch to `ring` if it is ready in the future.

**Comment by zonyitoo** [comment]
@kojirou1994 Changes are already included in `v1.7.0-alpha.8`: https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.7.0-alpha.8
