### ISSUE TITLE
failed to run custom build command for `bzip2-sys v0.1.6`

### ISSUE THREAD

**Issue by zqxvip** [shadowsocks/shadowsocks-rust#114]
error: failed to compile `shadowsocks-rust v1.6.12`, intermediate artifacts can be found at `/tmp/cargo-installpfvb2Q`

Caused by:
  failed to run custom build command for `bzip2-sys v0.1.6`
process didn't exit successfully: `/tmp/cargo-installpfvb2Q/release/build/bzip2-sys-b0f4fe5adefc1486/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("...")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "..." "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "bzip2-1.0.6" "-DBZ_NO_STDIO" "-o" "/tmp/cargo-installpfvb2Q/release/build/bzip2-sys-83a80d9e9ade075f/out/bzip2-1.0.6/blocksort.o" "-c" "bzip2-1.0.6/blocksort.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `...` installed?

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by zonyitoo** [comment]
Please open an issue in https://github.com/alexcrichton/bzip2-rs .
