### ISSUE TITLE
No idea why can not connect to remote by sslocal

### ISSUE THREAD

**Issue by arayus** [shadowsocks/shadowsocks-rust#1143]
1.  I test ssserver and sslocal in internal net work, the proxy seems ok. (socket 5, or http , black or aes)
2.  When I try to connect to my remote server, it not ok.
3.  I try tcpdump in remote, it looks like no request come in. 
4.  The server is already using by my android client and windows client (use chacha20 with v2ray quic)

Is there any idea to debug ?

**Comment by zonyitoo** [comment]
1. Run `sslocal` with `-vvv` and see if it actually receives request from your clients and which server does it want to connect.
2. Make sure that your system is able to connect to your server's specific port. Try to use `telnet` for testing.
