### ISSUE TITLE
MIPS cross compilation works for GitHub Workflow but not locally...?

### ISSUE THREAD

**Issue by KaraRyougi** [shadowsocks/shadowsocks-rust#1144]
I got the following error using the instructions in `.github/workflowsbuild-release.yml`:
```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/target/release/build/ring-ef45c452e46e5833/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
```
which seems to be a common one (see https://github.com/briansmith/ring/issues/562). However it seems the GitHub workflow is perfectly fine with compiling it... What am I missing?

**Comment by KaraRyougi** [comment]
`rustc 1.68.0 (2c8cc3432 2023-03-06)`
`cargo 1.68.0 (115f34552 2023-02-26)`

**Comment by zonyitoo** [comment]
Try to run `rustup upgrade` for all your local tool chain, and then removes those existed containers and images let `cross` download the latest images.

**Comment by KaraRyougi** [comment]
It might be related to my Debian 12 Bookworm environment. I tried again on another Debian 11 machine and everything works fine.
