### ISSUE TITLE
Is there a guide on how to start and configure the config.json when installed via snap?

### ISSUE THREAD

**Issue by cizz0r** [shadowsocks/shadowsocks-rust#1146]
I just can't get it to working using this .service file I created.
```
[Unit]
Description=Shadowsocks-Libev Custom Server Service for %I
Documentation=manss-server(1)
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/snap run shadowsocks-rust.ss-server -c /var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json

[Install]
WantedBy=multi-user.target
```

**Comment by cizz0r** [comment]
<img width="968" alt="Screenshot 2023-03-14 at 23 03 54" src="https://user-images.githubusercontent.com/111606933/225152327-e5f6826b-9c5f-43cb-a0ad-2b33f92ae071.png">



And where can I modify the normal systemd file so that it doesn't overwrite? I'd like to add my config parameter permanently.

**Comment by zonyitoo** [comment]
Not sure. If you finally find the answer, please help to improve the README.md.
