### ISSUE TITLE
Best bypass for GFW?

### ISSUE THREAD

**Issue by cizz0r** [shadowsocks/shadowsocks-rust#1147]
Hello, I installed Shadowsocks Rust now correctly (just missing autostart), what are the best settings for China?

My current ones are:
{
    "server": "0.0.0.0",
    "server_port": 5460,
    "password": "************************************",
    "method": "chacha20-ietf-poly1305",
    "mode":"tcp_and_udp",
    "fast_open":false
}

**Comment by zonyitoo** [comment]
Not sure what you are asking for. Closing.
