### ISSUE TITLE
How to config to add a layer of socks5 proxy between ss-server and target?

### ISSUE THREAD

**Issue by Nathaniel100** [shadowsocks/shadowsocks-rust#1151]
Is it possible to add a layer of socks5 proxy between ss-server and target to hide the information of ss-server?
client <---> ss-local <---> ss-server  <---> socks5 proxy <--->  target

Please let me know if there is an existing solution, thanks.

**Comment by dev4u** [comment]
对于ss的使用场景来说，多级代理的需求或许不是太强烈。

你可以试试gost，看看能不能满足你的需求？

**Comment by zonyitoo** [comment]
ssserver will use standard sockets to connect remote targets. So your issue could be converted to: how to redirect socket requests to a SOCKS5 server.

There are many solutions out there could fulfill this requirement. For example, gost that suggested by dev4u.

I would give you another solution: Hook socket APIs like https://github.com/rofl0r/proxychains-ng .

BTW, this is not a technical issue about shadowsocks-rust, closing.

**Comment by database64128** [comment]
Shameless plug: https://github.com/database64128/shadowsocks-go should be able to fulfill your use case.

**Comment by Nathaniel100** [comment]
Thanks, it works via https://github.com/rofl0r/proxychains-ng
