### ISSUE TITLE
MPTCP support

### ISSUE THREAD

**Issue by skeggse** [shadowsocks/shadowsocks-rust#1156]
It looks like `shadowsocks-libev` supports a `--mptcp` flag on supported Kernels, and it'd be neat to have feature parity with that flag in `shadowsocks-rust`!

**Comment by zonyitoo** [comment]
Well, I didn’t realize that it was actually useful.

**Comment by xinlake** [comment]
- Windows 11
- stable-x86_64-pc-windows-msvc unchanged - rustc 1.68.2 (9eb3afe9e 2023-03-27)

v1.15.2 compiles successfully and works fine, v1.15.3 compiles with errors
```
   Compiling clap v4.2.1
   Compiling xdg v2.4.1
   Compiling daemonize v0.5.0
   Compiling sysexits v0.5.0
   Compiling trust-dns-resolver v0.22.0
   Compiling shadowsocks v1.15.3 (E:\OSS\SourceCode\Client-Android-Optimize\core\src\main\rust\shadowsocks-rust\crates\shadowsocks)
error[E0425]: cannot find value `IPPROTO_MPTCP` in crate `libc`
   --> crates\shadowsocks\src\net\sys\unix\linux\mod.rs:224:64
    |
224 |         let fd = libc::socket(family, libc::SOCK_STREAM, libc::IPPROTO_MPTCP);
    |                                                                ^^^^^^^^^^^^^ help: a constant with a similar name exists: `IPPROTO_MTP`
    |
   ::: D:\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.141\src\unix\linux_like\mod.rs:885:1
    |
885 | pub const IPPROTO_MTP: ::c_int = 92;
    | ------------------------------ similarly named constant `IPPROTO_MTP` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `shadowsocks` due to previous error
warning: build failed, waiting for other jobs to finish...
````

**Comment by zonyitoo** [comment]
Why your rustc with windows target compiled the code only for Linux?

**Comment by xinlake** [comment]
> Why your rustc with windows target compiled the code only for Linux?

I'm compiling Shadowsocks Rust for [Android app](https://github.com/xinlake/privch-client-flutter/tree/main/xinlake-tunnel/plugin/android) on Windows PC.
- Rust Toolchain: stable-x86_64-pc-windows-msvc
- Rust Target: aarch64-linux-android, armv7-linux-androideabi

**Comment by zonyitoo** [comment]
Will be in next release v1.16
