### ISSUE TITLE
Why sslocal redirect mode you set ipv6 only to drop dual stack support but ss-libev hasn't?

### ISSUE THREAD

**Issue by Originalimoc** [shadowsocks/shadowsocks-rust#1159]
[crates/shadowsocks-service/src/local/redir/tcprelay/sys/unix/linux.rs](https://github.com/shadowsocks/shadowsocks-rust/commit/8817e04de2aa1aab28948ba1b3e73dc56ff1adf8#diff-4c85340326ce6f34d70cdb4fd32a6e910060399e7cd44a12350edcf3248c907c)

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/91028db4a327c9b0b7fa3e64412377b645ce9266/crates/shadowsocks-service/src/local/redir/tcprelay/sys/unix/linux.rs#L44-L50

I think the comment is very clear: "Redirect doesn't support dual-stack".

dual-stack is only supported in tproxy.

**Comment by Originalimoc** [comment]
Intentional? But why?

**Comment by database64128** [comment]
> Intentional? But why? I guess it's not implemented?

I think it's probably because redirect predates `IPV6_V6ONLY`, and no one bothered to implement dual-stack support for it in the kernel, because tproxy is the new way.

**Comment by Originalimoc** [comment]
> > Intentional? But why? I guess it's not implemented?
> 
> I think it's probably because redirect predates `IPV6_V6ONLY`, and no one bothered to implement dual-stack support for it in the kernel, because tproxy is the new way.

ss-redir(shadowsocks-libev) supports it.

**Comment by zonyitoo** [comment]
Did you actually try to run it in dual-stack mode and `REDIRECT` both IPv4 and IPv6 traffic to this process and it can get the original destination of IPv4 connections successfully?

**Comment by Originalimoc** [comment]
I don't know if internally "it can get the original destination of IPv4 connections".

But set listen to "::" I can use both v4 and v6.

(Not sure if it opens both v4 and v6 socket internally.)

**Comment by zonyitoo** [comment]
Please delete these lines:

https://github.com/shadowsocks/shadowsocks-rust/blob/498e6a2446c5f81498182a4244ad2fd037f10f02/crates/shadowsocks-service/src/local/redir/tcprelay/sys/unix/linux.rs#L44-L50

then compile a `sslocal` and test it in your environment.

**Comment by zonyitoo** [comment]
Confirmed Linux 5.4 REDIRECT supports dual-stack.

**Comment by zxlhhyccc** [comment]
> 确认 Linux 5.4 REDIRECT 支持双栈。

Linux 5.15 VPS node cannot be connected

**Comment by zonyitoo** [comment]
It is a sslocal feature, shouldn’t have anything related to the server.
