### ISSUE TITLE
A long standing bug, create thousands of connections in seconds, wasting around 1GB per hour bw

### ISSUE THREAD

**Issue by Originalimoc** [shadowsocks/shadowsocks-rust#1160]
This bug is at least from 1.9.x as I regressed to libev client which never happens.
Seems like this bug is not solved by this issue #1138 as I initially thought.

After running for a while(within 24h). Loads of TCP packets with payload length 0(didn't save capture, details later if reoccured) will be passed between ssserver add sslocal(redir mode). And with this conntrack: (see attached log, all these created within seconds after conntrack -D). Which 10800 is ssserver listen port and 1082 is sslocal listen redir port. After restarting sslocal it gets back to normal.

Also, not saved which process on ssserver side(????? I sense some loop storm, but why didn't happen on libev ss and I've filtered(RETURN in iptables) LAN IP ranges) is connecting 1082, also details later if reoccured

[orged1.log](https://github.com/shadowsocks/shadowsocks-rust/files/11098443/orged1.log)

**Comment by Originalimoc** [comment]
But this can't explain why a sslocal restart solves the problem. And sslocal side iptables nat already RETURN LAN IP 192.168/16, so it SHOULD not hit 1082.

**Comment by zonyitoo** [comment]
Restart will break the loop immediately.

> Loads of TCP packets with payload length 0.

They should be  created by `connect()`?

**Comment by Originalimoc** [comment]
No plugin.
Is it possible that somewhat sslocal generated request "connect to $(sslocal.listen_addr: sslocal.listen_port)" and sends it to ssserver to create this loop?

**Comment by zonyitoo** [comment]
Impossible.

**Comment by Originalimoc** [comment]
reopen if reoccured
