### ISSUE TITLE
Invalid Socks5 version

### ISSUE THREAD

**Issue by JanBoshoff** [shadowsocks/shadowsocks-rust#117]
I'm running a shadowsocks-rust server with the following commands (passwords & ip's omitted):

Ubuntu 16.04 server:
``./ssserver -uv -s "[::]:8388" -m "aes-256-cfb" -k "password"

Arch linux desktop:
``./sslocal -uv -b "127.0.0.1:1080" -s "11.22.33.44:8388" -m "aes-256-cfb" -k "password"

When setting my browser's proxy settings to ``127.0.0.1:1080`` and trying to navigate to www.google.com I get a page that says "The connection was reset".

In the sslocal logs I get the following error:
``[2018-07-08][15:37:12.826901715][ERROR] [shadowsocks::relay::tcprelay::socks5_local] Failed to handle client: Invalid Socks5 version``

I have tried with and without the obfs simple pluging and always get the same result. The server does not get any errors as nothing even reaches it. I have also tried with v1.6.12 and the latest alpha 1.7.0-alpha.9.

I found only one reference in issue #61 which seemed to be about the encryption method. I couldn't understand it though as it was in Chinese. I am a bit limited to where I can search at the moment. Any help will be much appreciated.

**Comment by JanBoshoff** [comment]
Thanks for the reply. 

I was thinking it might be something like that, but I'm using Firefox (61) and the settings look fine. Unless there is somewhere to change it except the normal proxy settings dialog I'm still stuck with this problem. I also tried setting Chromium's proxy setting when launching it from the cli, but I get the same error.

**Comment by zonyitoo** [comment]
For Firefox, make sure you are using `SOCKS Host` with `SOCKS v5` selected. It works perfectly in my Firefox(61).
![image](https://user-images.githubusercontent.com/1067951/42517872-4fa7287a-8493-11e8-99b3-4b8de20b001b.png)
For chrome, I uses the `SwitchyOmega` plugin for managing my proxy setting, and it works fine, too.

Maybe you can try it with `curl`

```
curl --socks5-hostname "127.0.0.1:4080" "https://www.google.com"
```

Replace `127.0.0.1:4080` with your local client's address.

**Comment by Kabie** [comment]
I encountered this too. The `shadowsocks-libev` works fine. I think problem is not about config or client.

**Comment by zonyitoo** [comment]
How can I reproduce it.

**Comment by Kabie** [comment]
I just upgrade kernel to `4.17.5-1-ARCH` (was 4.17.4-2-ARCH I believe) and the problem is gone. @JanBoshoff you should also try it.

**Comment by JanBoshoff** [comment]
Great! Thanks. I've been a bit busy, but I'll try tonight and see if it works.

**Comment by JanBoshoff** [comment]
I upgraded Arch and now have the 4.17.5-1 kernel. Then I tried to run everything as before, but got the same error (Invalid socks5 version). So I tried with the SwitchyOmega plugin for firefox, but it only resulted in a new error `Connection reset by peer (os error 104)`.

In the end I switched my server to Shadowsocks Go + Simple Obfs and using Shadowsocks-libev + Simple Obfs on the client side. 

Note: Using the Go server with libev client still didn't work through Firefox's own proxy dialog. I could only get it to work with the plugin. I was also unable to get the exact same setup working before upgrading Arch to the new kernel.

Thanks a lot for the help.

**Comment by zonyitoo** [comment]
```
Connection reset by peer (os error 104)
```

That's because the server side have closed the connection. You can check the log on the server side.

But at least, after upgrading to 4.17.5-1 kernel, you can successfully connect to the client side!

Could you try again with the Rust version in your server side? With the libev version on the client side, or any versions you want. It should work. If it doesn't work, please give me the logs on the server side.

**Comment by JanBoshoff** [comment]
Hi @zonyitoo. Sure I will. Will see if I can find some time over the next few days to try it out. Then I'll let you know.

**Comment by JanBoshoff** [comment]
Hi @zonyitoo. Sorry for the loooong wait. I finally got around to testing it all out again. So I set up a server using Shadowsocks Rust that behind an OBFS simple server. I am connecting to the server using the Android, Windows and libev clients without any issues. Great job!
