### ISSUE TITLE
HTTP wont transit IPV6 - Unsure how to proceed

### ISSUE THREAD

**Issue by camsoftworks2018** [shadowsocks/shadowsocks-rust#1173]
local config
```json
{
        "locals": [
                {
                        "local_address": "127.0.0.1",
                        "local_port": 1080,
                        "protocol": "http"
                },
                {
                        "local_address": "::",
                        "local_port": 1080,
                        "protocol": "http"
                }
        ],

        "servers": [
                {
                        "server": "9018138.proxy.###.###",
                        "server_port": 8080,
                        "password": ####,
                        "method": "chacha20-ietf-poly1305",
                        "timeout": 5
                }
        ]
}
```

server config
```json
{
        "server": "::",
        "server_port": 8080,
        "password": ###,
        "timeout": 5,
        "method": "chacha20-ietf-poly1305",

        "mode": "tcp_only",

        "dns": "1.1.1.1:53,1.0.0.1:53",
        "ipv6_first": true
}
```

I have been experiencing a problem with DNS Resolution of IPV6 Addresses, domain not found when attempting to connect to domains linked by only a AAAA record, Furthermore there is a problem where IPv6 addresses which are pinged result in general failure from windows.

I am not sure which configurations allow IPv6 and IPv4 transit however the only constraint is that it has to operate over shadowsocks http via tcp.

this is a rather big problem for me as i host a range of IPv6 only Services, inaccessible from my current site, as well as other endpoints now operating exclusively over IPv6 are virtually inaccessible from inside the restricted network.

Any help for this would be amazing and i will take any advice given.

**Comment by camsoftworks2018** [comment]
Refinement,

I have discovered that using a windows compiled shadowsocks-rust local, DNS IPv4 and IPv6 are transmitted to the server.
Using lookups it appears outbound :53 is invocated when i make requests for known IPv6 only domains.

However this is when shadowsocks is supplied the dns argument "[2606:4700::1111]:53".
Which then floods the console for timeout/no data recieved.

Im currently installing the dns utils resolver to test whether it may be the core issue in relation to my host, and hopefully its logging will direct me to the core error.

This doesnt still explain why IPv6 doesnt transit when used directly, but moves closer to fixing the issue of nxdomain on IPv6 only domains/subdomains.

**Comment by zonyitoo** [comment]
HTTP Proxy Protocol is an Application level protocol. Clients will normally send proxy requests with domain names directly. So the domain names should be resolved remotely. In other words, there should be nothing related to your clients' configuration.

Does your server has IPv6 outbound address? Or does it supports AAAA record resolution?

**Comment by camsoftworks2018** [comment]
Ive tested sslocal with the -vvv argument.
Looks like IPv6 records are sending the domains through the tunnel, However on further inspection it appears the server is receiving requests to resolve.
`2023-04-17T08:41:22.064445746+00:00 DEBUG [20348:140223627056896] [trust_dns_resolver::lookup_ip] one of ipv4 or ipv6 lookup failed in ipv4_and_ipv6 strategy: no record found for Query { name: Name("dns01.v6.aws.csw.cam."), query_type: A, query_class: IN }`, 
If you look at dns01.v6.aws.csw.cam youll find it points to cloudflare's ipv6 dns server.

I did the same test for the dns01.v4.aws.csw.cam and it worked.

Ive just learned my ISP doesnt support IPv6 however because of http i dont think this would be an issue, correct?

**Comment by camsoftworks2018** [comment]
Actually, ive just looked and it appears all my command line testing effectively avoids the proxy entirely, I am unsure why this is happening - Likely an issue with windows proxy not proxying all interface traffic.

I will try find a solution to first capture all traffic and send it through the proxy before i proceed.

**Comment by camsoftworks2018** [comment]
I have a feeling shadowsocks local-tun may fix this issue however i am not sure as its not supported on windows and i dont really know how to bridge it from WSL2 which also doesnt appear to support IPv6

**Comment by camsoftworks2018** [comment]
Well ill mark this as closed due to shadowsocks not being a part of the problem, thanks for the support.

**Comment by camsoftworks2018** [comment]
Closed because shadowsocks wasnt the problem, just the windows networking system ignoring applications etc.

Thanks for the support

**Comment by camsoftworks2018** [comment]
Fixed, IPv6 Resolution now works fully and IPv6 is resolved over an IPv4 Only connection.

For any future references this was done with [ProxyCap](https://www.proxycap.com/) which supports a direct Shadowsocks Connection.

**Comment by camsoftworks2018** [comment]
Fixed, IPv6 Resolution now works fully and IPv6 is resolved over an IPv4 Only connection.

For any future references this was done with [ProxyCap](https://www.proxycap.com/) which supports a direct Shadowsocks Connection.
