### ISSUE TITLE
macos  sslocal --protocol tun   无流量进出

### ISSUE THREAD

**Issue by oujl** [shadowsocks/shadowsocks-rust#1176]
我在macos上运行sslocal ，如下是我的config.json 内容：
{
    "locals": [
        {
            "protocol": "tun",
            "tun_interface_name": "utun88",
            "tun_interface_address": "10.255.0.1/24"
        },
    ],
    "servers": [
        {
            "address": "XXX.XXX.XXX.XXX",
            "port": 8388,
            "password": "123456",
            "method": "aes-256-gcm",
            "timeout": 7200
        },
    ],
}

启动命令  ： sudo sslocal -c  config.json 
无流量流入流出tun device .
mac 上的tun device 是要配置 route , 我翻了代码发现   
crates/shadowsocks-service/src/local/tun/sys/unix/apple/macos.rs的这个 set_route_configuration方法有相关实现 ，但是没有看到被调用的地方。

另外发现从设置里配置的 tun_interface_name 字段，到真实创建的tun设备名字不一样 ，总是减1 ，如name : utun8 , 真实创建的却是utun7  , 自己使用[rust-tun]这个demo没发现有这个问题 。

希望能支持macos tun , 方便以macos为开发环境的同学。

**Comment by zonyitoo** [comment]
If `sockaddr_ctl.sc_unit` set to `0`, it means to let kernel dynamically allocate an id for this `utun` device.

So the `utun0` should have `sc_unit = 1`. Which is why it was always -1.

**Comment by oujl** [comment]
终于跑起来了 
关键点：
1 config文件内，添加 ："outbound_bind_interface": "en0"   ， en0 是mac wifi的设备名。

2 设置Mac的系统路由：
  sudo route delete -inet default                 #删除系统默认路由
  sudo route add -inet default 10.10.0.1      #添加 sslocal创建的tun 的网关为系统默认网关，这样流量才会进出
  sudo route add -inet default 192.168.2.1 -ifscope en0


完整的config.json 

{
    "locals": [
        {
            "protocol": "tun",
            "tun_interface_name": "utun88",
            "tun_interface_address": "10.10.0.2/24",
            "tun_interface_destination":"10.10.0.1"
        }
    ],
    "servers": [
        {
            "address": "XXX.XXX.XXX.XXX",
            "port": 8388,
            "password": "password",
            "method": "aes-256-gcm",
            "timeout": 7200
        }
    ],
    
    "outbound_bind_interface": "en0"
}
