### ISSUE TITLE
Failed to connect remote server

### ISSUE THREAD

**Issue by e2ge** [shadowsocks/shadowsocks-rust#118]
[2018-07-14][20:53:14.591223300][ERROR] Failed to connect remote server, err: resolved xx.xxx.com to empty address, all IPs are filtered
[2018-07-14][20:53:14.592222200][ERROR] Failed to handle client: resolved xx.xxx.com to empty address, all IPs are filtered

一直在等新的版本，alpha9和alpha10终于能在windows上的mingw环境编译过了，用的gnu abi编译，电脑原因没有试msvc abi。
因为新的版本和旧的版本变动有点大，增加了ssdns.exe，看log貌似是dns没有响应，无法返回server的ip。
会不会需要在config.json里面设置fallback的dns呢？

**Comment by zonyitoo** [comment]
日志的意思是DNS解析`xx.xxx.com`的时候，返回的是空值，或者是有返回，但是被过滤掉了。
具体你的怎么做的？
`ssdns`是一个新的工具，是用来把DNS请求放到远端去解析。可以不使用它的。

**Comment by e2ge** [comment]
没有进行什么特殊的操作。在win10下，mingw更新到最新的版本，rustup update更新到最新的版本。
编译命令：OPENSSL_DIR=C:\\OpenSSL-Win64 OPENSSL_STATIC=yes SODIUM_BUILD_STATIC=yes cargo build --release --features miscreant
在mingw下执行./sslocal.exe -c ./config.json
正常出现启动log，出现提示监听端口，在firefox自带option中更改到socks5，会出现一段时间的等待状态，然后log蹦出来Failed to connect remote server
试着用-v开启debug日志，并没有过多的信息。

**Comment by zonyitoo** [comment]
说明是解析不了这个 `xx.xxx.com` 地址

```
nslookup xx.xxx.com
```

有返回吗？

配置里不要写域名，直接用IP呢？

**Comment by e2ge** [comment]
地址是肯定可以解析的，因为有其他的连接存在，我需要等一会试一下直接用ip。
有一个提示是我系统中有dnscrypt-proxy，所以系统的dns设置为127.0.0.1，不知道是否会影响ss-rust的dns解析，我也会试一下。

**Comment by zonyitoo** [comment]
不会。因为我的Linux服务器上也用了dnsmasq，OS X本地本身也有dsutils，我还试过用`ssdns`来代理本地所有DNS请求，然后再启动`sslocal`，解析也是没有问题。

**Comment by zonyitoo** [comment]
也许Windows下有什么特殊的设置有影响，我没有测试过，没有Windows可测。

**Comment by e2ge** [comment]
把server换成ip就可以了，奇怪的问题。

**Comment by zonyitoo** [comment]
说明是Windows下解析不了，跟[trust-dns](https://github.com/bluejekyll/trust-dns)有关了……

**Comment by e2ge** [comment]
问一个题外的问题，ssdns是基于trust-dns的，而trust-dns是支持dns over tls，不知道ssdns是否支持dns-over-tls设置成上有dns，例如9.9.9.9就支持dns-over-tls

**Comment by zonyitoo** [comment]
`ssdns`是在本地监听端口，把DNS请求封装成ShadowSocks UDP包，发到`ssserver`去访问DNS服务器。

`ssserver`用的是`trust-dns`，应该是支持。我个人没有试过。
在服务端改一下`/etc/resolv.conf`试试？

**Comment by zonyitoo** [comment]
貌似是需要在代码里改一下DNS resolver的配置，指定protocol才行。这个可以另提一个issue吧，可以做一下。

**Comment by zonyitoo** [comment]
Should be fixed in #122 .
