### ISSUE TITLE
Ability to log full url path

### ISSUE THREAD

**Issue by laspera** [shadowsocks/shadowsocks-rust#1188]
I see that there already was asked about this https://github.com/shadowsocks/shadowsocks-rust/issues/681

But it that would be a really nice feature for metrics or something like these, I'm not seeing this thing in other shadowsocks server impls and would like to see it here

**Comment by zonyitoo** [comment]
It won't be possible for TLS or QUIC connections to see the full url path. This feature will only works in HTTP/1.1 and HTTP/1.0.

I still don't think this is worth to do. Or do you have any good suggestions about how to implement it?

**Comment by laspera** [comment]
Nah I don't really have any suggestions, but does https also encode url path?

**Comment by zonyitoo** [comment]
Yes, of course. Since there is no possible way, closing.

**Comment by laspera** [comment]
Is there any other alternative proxy that will achieve this? I mean maybe wireguard or squid3 etc.

**Comment by zonyitoo** [comment]
No. It is possible only if you can decrypt TLS data chunks. One of the design goal of TLS is to protect data from any third-party, your proxy server is the third-party middleman between you and the destination target server.
