### ISSUE TITLE
Properly handle TCP CLOSE-WAIT state

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#1195]
Discussion continue from #1190 .

The original issue author doesn't want to have any effective discussion any further.

**Comment by zonyitoo** [comment]
For reference, in `go-shadowsocks2`:

https://github.com/shadowsocks/go-shadowsocks2/blob/828576df0a9415d1f49e9433577389821e862f3c/tcp.go#L145-L166

It calls `io.Copy` on both direction. Set a Read timeout when one of them ends.

**Comment by database64128** [comment]
I posted a lengthy analysis yesterday at https://github.com/zhboner/realm/issues/87#issuecomment-1548133861.

There's no need for a read timeout. TCP keepalive will terminate the connection when `TCP_KEEPCNT` is reached. The default is 9 on my system. You can add an option for it if you want.

**Comment by zonyitoo** [comment]
Because it is already in `CLOST-WAIT` state, I don't think `TCP_KEEPCNT` could solve the problem.

**Comment by zonyitoo** [comment]
```
CLIENT -> LOCAL -> SERVER -> REMOTE
```

Base on the original discussion, sockets that are in `CLOSE-WAIT` states are `LOCAL -> SERVER`.

Sockets must be held in here:

https://github.com/shadowsocks/shadowsocks-rust/blob/bf5d9a909acc04c93405729542f5f0c9de31121f/crates/shadowsocks/src/relay/tcprelay/utils.rs#L193-L217

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/bf5d9a909acc04c93405729542f5f0c9de31121f/crates/shadowsocks/src/relay/tcprelay/utils.rs#L49-L87

1. `poll_read` never return EOF?

Since the socket is already in `CLOSE-WAIT` state, `poll_read` should return EOF.

2. `poll_write` always returns `Polling`?

It should return `EPIPE`.

3. Blocking on `poll_flush`?

Really?

**Comment by zonyitoo** [comment]
I found a scenario:

1. Server closes by killing the whole process directly. So all the existing connections should send `RST` to `LOCAL`. (One way to trigger `CLOST-WAIT` in the original issue.)
    - Maybe `FIN`? It depends on whether the server close sockets gracefully when exiting.
3. `LOCAL` receives `FIN`, `poll_read` returns `EOF`, otherwise if it is `RST`, it [should return `ConnectReset`](https://github.com/rust-lang/rust/blob/9239760da89cd8e9a51536beeb0a23762064037d/library/std/src/sys/unix/mod.rs#LL246C45-L246C45).
    - `FIN`: If `CLIENT` is still running properly, there should be nothing left in the read buffer. So it would continue to call [`shutdown(SHUT_WR)`](https://github.com/tokio-rs/tokio/blob/c84d0a14b189c45da8f5e963fd3a83790ec92f8e/tokio/src/net/tcp/stream.rs#L1358-L1361) on the `CLIENT -> LOCAL` socket. The `LOCAL` should send `FIN` to `CLIENT` [(reference)](https://stackoverflow.com/questions/4160347/close-vs-shutdown-socket/23483487#23483487).
    - `RST`: Exit the whole copy process directly, which will eventually `close()` both sockets immediately, no orphan `CLOSE-WAIT` sockets should be left in this situation.
4. `CLIENT`'s `recv()` should return EOF. But if it doesn't `shutdown` or `close` its socket, then the sockets in `CLIENT` and `LOCAL` will never reach its destruction process, which will eventually stay in `CLOSE-WAIT` state forever.

**Comment by database64128** [comment]
>     3. `CLIENT`'s `recv()` should return EOF. But if it doesn't `shutdown` or `close` its socket, then the sockets in `CLIENT` and `LOCAL` will never reach its destruction process, which will eventually stay in `CLOSE-WAIT` state forever?

Not for `LOCAL`. `LOCAL` has sent FIN and from its perspective the accepted connection is in `FIN_WAIT2` and thus is subject to `tcp_fin_timeout`.

**Comment by database64128** [comment]
> So if sockets are forcibly closed if `CLIENT` doesn't respond with `FIN` or `RST`, then another call of `transfer_one_direction` which manages `CLIENT -> LOCAL` should ends as expected.
> 
> If so, why did those `CLOSE-WAIT` sockets exist?

Because `transfer_one_direction` is still waiting to read from `CLIENT`, and it won't call `shutdown(SHUT_WR)` on `LOCAL -> SERVER` socket until the `CLIENT -> LOCAL` socket receives a FIN or runs out of `tcp_fin_timeout`.

**Comment by zonyitoo** [comment]
Since sockets are in `CLOSE-WAIT` state, the `copy` function should have already ended (the `shutdown(SHUT_WR)` must be called on both writer stream).

If these sockets are somehow still holding by some structs in the program, then it will stay in `CLOSE-WAIT` indefinitely.

> Because `transfer_one_direction` is still waiting to read from `CLIENT`, and it won't call `shutdown(SHUT_WR)` on `LOCAL -> SERVER` socket until the `CLIENT -> LOCAL` socket receives a FIN or runs out of `tcp_fin_timeout`.

Yes. And it is `60` seconds by default.

But still, it should stay in `FIN-WAIT*` state for `60` seconds but not `CLOSE-WAIT`.

**Comment by database64128** [comment]
> But still, it should stay in `FIN-WAIT*` state for `60` seconds but not `CLOSE-WAIT`.

FIN_WAIT1/2 is when our side has sent FIN and is waiting for more data or a FIN from the remote side.

From `LOCAL`'s perspective, on `LOCAL -> SERVER`, we have already received a FIN, and we haven't called `shutdown(SHUT_WR)` yet, so it's in `CLOSE_WAIT`.

**Comment by zonyitoo** [comment]
So if a `LOCAL -> SERVER` socket stays in `CLOSE-WAIT` indefinitely, then the connection of `CLIENT -> LOCAL` must not exit properly. `FIN` haven't sent to `CLIENT`, otherwise the kernel behavior of `tcp_fin_timeout` will forcibly close the `CLIENT -> LOCAL` connection, which will eventually close the `LOCAL -> SERVER` socket in the current implementation.

In current implementation, it only happens if there are still data in the read buffer, but couldn't `write()` for some unknown reasons.

**Comment by zonyitoo** [comment]
It is still a black box for us. Let me add a timer in `copy`.

When the timeout is reached, it prints a `warn` log about how many data was still in the buffer.

**Comment by zonyitoo** [comment]
Focus on the problem, no personal attack.

**Comment by f4nff** [comment]
I encountered the same scene in another project, only to initiate issues, and this situation existed before realm.

**Comment by zonyitoo** [comment]
I added a 5 seconds (read+write) timeout on the other copy direction when the current one ends with EOF and found some connections have ended unexpectly by the timeout:

```
2023-05-17T10:29:17.051639299+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(747517), b_to_a: Running(CopyBuffer { read_done: false, pos: 346, cap: 346, amt: 2749, .. })
2023-05-17T10:51:43.288722428+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5277), b_to_a: Running(CopyBuffer { read_done: false, pos: 406, cap: 406, amt: 532, .. })
2023-05-17T10:52:19.447472007+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5277), b_to_a: Running(CopyBuffer { read_done: false, pos: 401, cap: 401, amt: 527, .. })
2023-05-17T11:05:49.529981300+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(0), b_to_a: Running(CopyBuffer { read_done: false, pos: 0, cap: 0, amt: 0, .. })
2023-05-17T11:06:16.838874543+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5555), b_to_a: Running(CopyBuffer { read_done: false, pos: 39, cap: 39, amt: 712, .. })
2023-05-17T11:06:21.456252128+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(6318), b_to_a: Running(CopyBuffer { read_done: false, pos: 334, cap: 334, amt: 398, .. })
2023-05-17T11:21:45.173411464+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(6371), b_to_a: Running(CopyBuffer { read_done: false, pos: 406, cap: 406, amt: 532, .. })
2023-05-17T11:22:19.110805979+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(6382), b_to_a: Running(CopyBuffer { read_done: false, pos: 401, cap: 401, amt: 527, .. })
2023-05-17T11:51:46.156522083+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5314), b_to_a: Running(CopyBuffer { read_done: false, pos: 406, cap: 406, amt: 532, .. })
2023-05-17T12:10:29.666227552+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5301), b_to_a: Running(CopyBuffer { read_done: false, pos: 38, cap: 38, amt: 994, .. })
2023-05-17T12:51:49.600502093+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(5230), b_to_a: Running(CopyBuffer { read_done: false, pos: 406, cap: 406, amt: 532, .. })
2023-05-17T13:05:23.755865075+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(60627), b_to_a: Running(CopyBuffer { read_done: false, pos: 779, cap: 779, amt: 843, .. })
```

In these logs, `a` is the "Encrypted" stream, which is `LOCAL <-> SERVER` and `b` is the "Plain" stream, which is `CLIENT <-> LOCAL`.

In all the cases, `a_to_b` ended with EOF. But `b_to_a` remained running but buffers were all empty (`pos == cap`).

When `a_to_b` ends, it will set both read timeouts (5 seconds) on `b` and write timeouts on `a`, then call `shutdown(SHUT_WR)` on `b`. So the `"read timeout"` in logs were generated by `b`'s `recv()`, which is the `CLIENT -> LOCAL` socket.

Normally, after calling `shutdown(SHUT_WR)` on `b`, it will send a `FIN` to `CLIENT`. For a normal `CLIENT`, it should ends its `recv()` process and then `close()` or `shutdown()` the socket after `send()`ing the other data. In this case, `b` didn't `recv()` from `CLIENT` for at least 5 seconds.

If the `5` seconds read timeout doesn't exist, the `b_to_a` may continue hanging for a long time, which is why the `a` socket stayed in `CLOSE-WAIT`.

**Comment by zonyitoo** [comment]
Make a commit to let users test in their own environment.

**Comment by f4nff** [comment]
```
root@yy:/home# git clone https://github.com/shadowsocks/shadowsocks-rust.git
Cloning into 'shadowsocks-rust'...
remote: Enumerating objects: 18362, done.
remote: Counting objects: 100% (18362/18362), done.
remote: Compressing objects: 100% (5511/5511), done.
remote: Total 18362 (delta 12555), reused 18298 (delta 12518), pack-reused 0
Receiving objects: 100% (18362/18362), 5.77 MiB | 8.68 MiB/s, done.
Resolving deltas: 100% (12555/12555), done.
root@yy:/home# cd shadowsocks-rust/
root@yy:/home/shadowsocks-rust# ls
acl           build             Cargo.toml  Cross.toml  Dockerfile  k8s       README.md     src
appveyor.yml  Cargo.lock        configs     debian      examples    LICENSE   rustfmt.toml  tests
bin           cargo-publish.sh  crates      docker      homebrew    Makefile  snap
root@yy:/home/shadowsocks-rust# cargo build --release --target x86_64-unknown-linux-musl
    Updating crates.io index
  Downloaded thread-id v4.1.0
  Downloaded notify v5.2.0
  Downloaded proc-macro2 v1.0.58
  Downloaded trust-dns-resolver v0.23.0-alpha.2
  Downloaded h2 v0.3.19
  Downloaded trust-dns-proto v0.23.0-alpha.2
  Downloaded 6 crates (708.3 KB) in 1.91s
   Compiling libc v0.2.144
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.58
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.27
   Compiling autocfg v1.1.0
   Compiling typenum v1.16.0
   Compiling version_check v0.9.4
   Compiling serde v1.0.163
   Compiling subtle v2.4.1
   Compiling zeroize v1.6.0
   Compiling log v0.4.17
   Compiling generic-array v0.14.7
   Compiling pin-project-lite v0.2.9
   Compiling lock_api v0.4.9
   Compiling thiserror v1.0.40
   Compiling futures-core v0.3.28
   Compiling parking_lot_core v0.9.7
   Compiling memchr v2.5.0
   Compiling scopeguard v1.1.0
   Compiling bytes v1.4.0
   Compiling smallvec v1.10.0
   Compiling syn v2.0.16
   Compiling slab v0.4.8
   Compiling futures-sink v0.3.28
   Compiling const-oid v0.9.2
   Compiling futures-channel v0.3.28
   Compiling futures-task v0.3.28
   Compiling der v0.6.1
   Compiling tokio v1.28.1
   Compiling cpufeatures v0.2.7
   Compiling futures-util v0.3.28
   Compiling getrandom v0.2.9
   Compiling signal-hook-registry v1.4.1
   Compiling rand_core v0.6.4
   Compiling block-buffer v0.10.4
   Compiling socket2 v0.4.9
   Compiling parking_lot v0.12.1
   Compiling crypto-common v0.1.6
   Compiling num_cpus v1.15.0
   Compiling digest v0.10.6
   Compiling bitflags v1.3.2
   Compiling futures-io v0.3.28
   Compiling once_cell v1.17.1
   Compiling cc v1.0.79
   Compiling pin-utils v0.1.0
   Compiling inout v0.1.3
   Compiling base16ct v0.1.1
   Compiling tracing-core v0.1.31
   Compiling opaque-debug v0.3.0
   Compiling itoa v1.0.6
   Compiling syn v1.0.109
   Compiling sec1 v0.3.0
   Compiling cipher v0.4.4
   Compiling universal-hash v0.5.0
   Compiling crypto-bigint v0.4.9
   Compiling signature v1.6.4
   Compiling num-integer v0.1.45
   Compiling io-lifetimes v1.0.10
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling indexmap v1.9.3
   Compiling num-traits v0.2.15
   Compiling rustix v0.37.19
   Compiling linked-hash-map v0.5.6
   Compiling ppv-lite86 v0.2.17
   Compiling percent-encoding v2.2.0
   Compiling elliptic-curve v0.12.3
   Compiling form_urlencoded v1.1.0
   Compiling ecdsa v0.14.8
   Compiling rand_chacha v0.3.1
   Compiling ring v0.16.20
   Compiling aead v0.5.2
   Compiling unicode-bidi v0.3.13
   Compiling fnv v1.0.7
   Compiling unicode-normalization v0.1.22
   Compiling hashbrown v0.12.3
   Compiling linux-raw-sys v0.3.7
   Compiling ucd-trie v0.1.5
   Compiling base64ct v1.6.0
   Compiling async-trait v0.1.68
   Compiling ryu v1.0.13
   Compiling crossbeam-utils v0.8.15
   Compiling spki v0.6.0
   Compiling idna v0.3.0
   Compiling rand v0.8.5
   Compiling blake3 v1.3.3
   Compiling polyval v0.6.0
   Compiling match_cfg v0.1.0
   Compiling serde_json v1.0.96
   Compiling untrusted v0.7.1
   Compiling heck v0.4.1
   Compiling spin v0.5.2
   Compiling ipnet v2.7.2
   Compiling hostname v0.3.1
   Compiling ghash v0.5.0
   Compiling pkcs8 v0.9.0
   Compiling http v0.2.9
   Compiling p384 v0.11.2
   Compiling enum-as-inner v0.5.1
   Compiling p256 v0.11.1
   Compiling ed25519 v1.5.3
   Compiling poly1305 v0.8.0
   Compiling serde_derive v1.0.163
   Compiling thiserror-impl v1.0.40
   Compiling tokio-macros v2.1.0
   Compiling futures-macro v0.3.28
   Compiling tracing-attributes v0.1.24
   Compiling pin-project-internal v1.1.0
   Compiling aes v0.8.2
   Compiling ctr v0.9.2
   Compiling pest v2.6.0
   Compiling chacha20 v0.9.1
   Compiling hmac v0.12.1
   Compiling inotify-sys v0.1.5
   Compiling constant_time_eq v0.2.5
   Compiling lazy_static v1.4.0
   Compiling httparse v1.8.0
   Compiling arrayvec v0.7.2
   Compiling same-file v1.0.6
   Compiling data-encoding v2.3.3
   Compiling quick-error v1.2.3
   Compiling utf8parse v0.2.1
   Compiling arrayref v0.3.7
   Compiling anstyle-parse v0.2.0
   Compiling ring-compat v0.5.1
   Compiling pin-project v1.1.0
   Compiling resolv-conf v0.7.0
   Compiling walkdir v2.3.3
   Compiling pest_meta v2.6.0
   Compiling inotify v0.9.6
   Compiling hkdf v0.12.3
   Compiling chacha20poly1305 v0.10.1
   Compiling aes-gcm v0.10.1
   Compiling crossbeam-channel v0.5.8
   Compiling is-terminal v0.4.7
   Compiling lru-cache v0.1.2
   Compiling sha1 v0.10.5
   Compiling md-5 v0.10.5
   Compiling pest_generator v2.6.0
   Compiling filetime v0.2.21
   Compiling tower-service v0.3.2
   Compiling anstyle-query v1.0.0
   Compiling destructure_traitobject v0.2.0
   Compiling colorchoice v1.0.0
   Compiling arc-swap v1.6.0
   Compiling anstyle v1.0.0
   Compiling anyhow v1.0.71
   Compiling try-lock v0.2.4
   Compiling anstream v0.3.2
   Compiling unsafe-any-ors v1.0.0
   Compiling futures-executor v0.3.28
   Compiling futures v0.3.28
   Compiling shadowsocks-crypto v0.5.1
   Compiling http-body v0.4.5
   Compiling terminal_size v0.2.6
   Compiling ordered-float v2.10.0
   Compiling yaml-rust v0.4.5
   Compiling socket2 v0.5.3
   Compiling time v0.1.45
   Compiling pest_derive v2.6.0
   Compiling aho-corasick v1.0.1
   Compiling spin v0.9.8
   Compiling regex-syntax v0.7.1
   Compiling iana-time-zone v0.1.56
   Compiling clap_lex v0.4.1
   Compiling option-ext v0.2.0
   Compiling byte_string v1.0.0
   Compiling httpdate v1.0.2
   Compiling strsim v0.10.0
   Compiling tower-layer v0.3.2
   Compiling base64 v0.21.0
   Compiling lru_time_cache v0.11.11
   Compiling chrono v0.4.24
   Compiling clap_builder v4.2.7
   Compiling dirs-sys v0.4.1
   Compiling typemap-ors v1.0.0
   Compiling url v2.3.1
   Compiling mio v0.8.6
   Compiling tracing v0.1.37
   Compiling notify v5.2.0
   Compiling want v0.3.0
   Compiling serde_urlencoded v0.7.1
   Compiling tower v0.4.13
   Compiling regex v1.8.1
   Compiling json5 v0.4.1
   Compiling serde-value v0.7.0
   Compiling serde_yaml v0.8.26
   Compiling derivative v2.2.0
   Compiling iprange v0.6.7
   Compiling thread-id v4.1.0
   Compiling rtoolbox v0.0.1
   Compiling byteorder v1.4.3
   Compiling humantime v2.1.0
   Compiling home v0.5.5
   Compiling log-mdc v0.1.0
   Compiling checked_int_cast v1.0.0
   Compiling qrcode v0.12.0
   Compiling xdg v2.5.0
   Compiling rpassword v7.2.0
   Compiling clap v4.2.7
   Compiling build-time v0.1.3
   Compiling log4rs v1.2.0
   Compiling directories v5.0.1
   Compiling daemonize v0.5.0
   Compiling sysexits v0.5.0
   Compiling tokio-util v0.7.8
   Compiling trust-dns-proto v0.23.0-alpha.2
   Compiling tokio-tfo v0.2.1
   Compiling sendfd v0.4.3
   Compiling h2 v0.3.19
   Compiling trust-dns-resolver v0.23.0-alpha.2
   Compiling hyper v0.14.26
   Compiling shadowsocks v1.16.0 (/home/shadowsocks-rust/crates/shadowsocks)
   Compiling shadowsocks-service v1.16.0 (/home/shadowsocks-rust/crates/shadowsocks-service)
   Compiling shadowsocks-rust v1.16.0 (/home/shadowsocks-rust)
    Finished release [optimized] target(s) in 1m 24s
root@yy:/home/shadowsocks-rust#
```

```
root@OpenWrt:~/ss# ./sslocal --protocol tun -s "[2a01:1700:2::7:18b]:1" -m "2022-blake3-aes-128-gcm"
 -k "RPNvHZ+QYIc9bdBBpwZKaQ==" --outbound-bind-interface pppoe-wan --tun-interface-name tun0 -U --tc
p-no-delay --tcp-keep-alive 120 --udp-timeout 60
error: invalid value 'tun' for '--protocol <PROTOCOL>'
  [possible values: socks, http, tunnel]

  tip: a similar value exists: 'tunnel'

For more information, try '--help'.
```



???

**Comment by f4nff** [comment]
thank you.

**Comment by f4nff** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/19538878/459a8c75-47d2-4d7f-91f9-cd5265a15c2f)

Sorry, still not resolved

**Comment by zonyitoo** [comment]
This commit is not aim to "resolve", but to help identifying what exactly happening in the underlying connections.

**Comment by f4nff** [comment]
`        const TIMEOUT_AFTER_EOF: Duration = Duration::from_secs(60);`


`        const TIMEOUT_AFTER_EOF: Duration = Duration::from_secs(3);`


This seems to be an improvement.

**Comment by zonyitoo** [comment]
This will make `sslocal` lose data definitely, no improvement at all.

**Comment by zonyitoo** [comment]
Timeout only happens when `LOCAL` receives `FIN` from `SERVER`, and then it sends `FIN` to `CLIENT`. But the `CLIENT` still keep the half connection alive for some reason. It may still want to transmit data to `SERVER`. So If `LOCAL` closes the connection forcibly, those data will lose definitely, which is not the goal as a "proxy".

In this situation, `CLOSE-WAIT` remains because `CLIENT`s are still keeping the connections alive, which is definitely not a BUG. Proxy only close the connection when `CLIENT` or `SERVER` ask him to do so.

I will run the local and server a day and see of we could catch other situations that causes long living `CLOSE-WAIT`.

**Comment by f4nff** [comment]
The client is doing concurrency testing, and the client has closed concurrent requests, and the server should also release the connection soon.

**Comment by zonyitoo** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/1067951/0c2a3da2-995c-4c26-bb2f-f60b11163b08)

Here is a TCP state machine for reference.

If you see `LAST_ACK`, then Application have already closed the socket. You should find your answer in Linux Kernel.

**Comment by zonyitoo** [comment]
After a day of running, I have collected 159 samples that timeout 60s were reached after one transmission have already seen EOF. There is no surprise that 100% of them are look exactly like this:

```
05-18T14:42:39.341585394+00:00 WARN  copy bidirection ends with error: read timeout, a_to_b: Done(28444), b_to_a: Running(CopyBuffer { read_done: false, pos: 248, cap: 248, amt: 2680, .. })
```

`CLIENT` still keep the connection alive even `LOCAL` have already sent `FIN` to it.

The TCP sockets in this project are enabled `SO_KEEPALIVE` with `TCP_KEEPIDLE = TCP_KEEPINTVL = 15s`, just like what Go's did in the standard library. So in these cases, `CLIENT`s can still respond `LOCAL`'s keep alive probing packets at least 60 seconds. Or maybe the `CLIENT`s couldn't repond to keep alive anymore, but the default setting in Linux `tcp_keepalive_probes` is `9`. So the server will forcibly close the socket after `9 * 15 = 135s` if `CLIENT`s didn't respond to its keep alive probing.

One possible test remaining:

1. Set `tcp_keepalive_probes` to `3`, then sockets will be forcibly closed after `3 * 15 = 45s < 60s`.
2. Check if we can still see `"read timeout"` in logs.

But we can still make a conclusion here:

```
CLIENT -> LOCAL -> SERVER -> TARGET
```

1. When `SERVER` sends `FIN` to `LOCAL`, the connection (`LOCAL -> SERVER`) will then go into `CLOSE_WAIT` state.
2. `LOCAL`'s `a_to_b` copy will end with `EOF`, and then sends `FIN` to `CLIENT`, the connection (`CLIENT -> LOCAL`) will then go into `FIN_WAIT_1` state.
3. `CLIENT`'s `recv()` will see `EOF`. But if:
    - `CLIENT` doesn't close the socket as expected, which is normal, many languages like Java, Python that have GC will close the socket only when GC release the underlying object.
    - `CLIENT` closes the socket, but the `FIN` sent to `LOCAL` was somehow lost.
    - `CLEINT` can still respond to `LOCAL`'s keep-alive probing.
    - `CLIENT` cannot respond to `LOCAL`'s keep-alive probing less than 9
4. `LOCAL`'s `a_to_b` couldn't receive `EOF` in at least `9 * 15 = 135s` seconds.
5. After keep-alive probes 9 times, Linux will forcibly close the socket in `LOCAL`. `a_to_b` will receive `EOF`.
6. All sockets are closed. `CLOSE_WAIT` state will last at least 135 seconds.

> 如果close-wait一闪即逝是正常的

No, you are wrong.

There are multiple **correct** ways to make these `CLOSE_WAIT` to have less life time:

1. Set `tcp_keepalive_probes` to a smaller value, if `CLIENT`s are actually gone.
2. Set `"keep_alive"` to a smaller value in `sslocal`'s configuration:
    ```json
    {
        // Enables `SO_KEEPALIVE` and set `TCP_KEEPIDLE`, `TCP_KEEPINTVL` to the specified seconds
        "keep_alive": 15,
    }
    ```
    Which will also help to identify disconnected `CLIENT`s faster.

**Comment by f4nff** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/19538878/8257e196-11cd-42f7-9bbd-86ccdf8c3282)
The server has not been released, and it is strange to use, so it is temporarily abandoned.

**Comment by f4nff** [comment]
It has not been released, and it has been waiting for a few minutes.
If I have less concurrency, nothing, but high concurrency,
never released ^

**Comment by f4nff** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/19538878/f63e0cc6-980b-48b9-90c6-4a41682784e4)

**Comment by f4nff** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/19538878/addc1f38-5a06-4617-9685-b9afe04b5f61)
