### ISSUE TITLE
docker ssserver-rust  failed to start plugin "v2ray-plugin"

### ISSUE THREAD

**Issue by yuwade** [shadowsocks/shadowsocks-rust#1197]
{
    "server":"0.0.0.0",
    "server_port":8388,
    "password":"password0",
    "timeout":300,
    "method":"aes-256-gcm",
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
    "plugin":"v2ray-plugin",
    "plugin_opts":"server"
}

docker run --name ssserver-rust \
  --restart always \
  -p 8388:8388/tcp \
  -p 8388:8388/udp \
  -v /root/ssserver/config.json:/etc/shadowsocks-rust/config.json \
  -dit ghcr.io/shadowsocks/ssserver-rust:latest

ERROR 
/usr/local/bin/docker-entrypoint.sh: Configuration complete; ready for start up
[0;32mINFO[0m  shadowsocks server 1.15.3 build 2023-03-12T16:50:50.362433959+00:00
[0;31;1mERROR[0m failed to start plugin "v2ray-plugin" for server 0.0.0.0:8388, err: No such file or directory (os error 2)

**Comment by zonyitoo** [comment]
There is no `v2ray-plugin` in the image, you should either build your own image or pint a volume inside the container.
