### ISSUE TITLE
cargo install shadowsocks-rust error

### ISSUE THREAD

**Issue by 1stdropshipping** [shadowsocks/shadowsocks-rust#120]
os: win7 amd64
error:
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading shadowsocks-rust v1.6.12
error: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) -

**Comment by zonyitoo** [comment]
This is a network issue. You are blocked by GFW, so you saw this error message.
