### ISSUE TITLE
请问 怎么构建生成ios平台静态库

### ISSUE THREAD

**Issue by vandykeWei** [shadowsocks/shadowsocks-rust#1222]
你好，请问怎么配置才能构建ios平台的静态库.a ？需要怎么修改cargo.toml?

**Comment by zonyitoo** [comment]
You can make a new project, and set `crate-type` to `staticlib`, and then exposes APIs in C style name mangling.

**Comment by vandykeWei** [comment]
> You can make a new project, and set `crate-type` to `staticlib`, and then exposes APIs in C style name mangling.

thank you for your reply. Excuse me, how to build a project that can build ios static library, and exposes APIs in C style? My knowledge on these is lacking.

**Comment by database64128** [comment]
This is not a Q&A forum. Do your own research instead of asking these questions and wasting everyone else's time.

**Comment by vandykeWei** [comment]
> This is not a Q&A forum. Do your own research instead of asking these questions and wasting everyone else's time.

thank you for your reply. I feel very sorry.

**Comment by zonyitoo** [comment]
https://www.greyblake.com/blog/exposing-rust-library-to-c/
