### ISSUE TITLE
Cut a new release with the iOS support?

### ISSUE THREAD

**Issue by faern** [shadowsocks/shadowsocks-rust#1235]
Hi,

I do not know if you have any current release plans or what's on the roadmap. Would it be possible to make a release with the merged support for iOS (#1194)? That would allow us to depend on a crates.io version of this app instead of from git.

Thank you.

**Comment by zonyitoo** [comment]
I am still waiting for trust-dns to make their final release.

**Comment by zonyitoo** [comment]
Released v1.16.0.
