### ISSUE TITLE
Segfault of stable crate with current stable compiler.

### ISSUE THREAD

**Issue by pinkisemils** [shadowsocks/shadowsocks-rust#1239]
Whilst the current `master` branch already has a [fix](https://github.com/shadowsocks/shadowsocks-rust/commit/c2877c10b589f8123840741c6ce1d553b33892ae) for this, I was wondering if you could backport this to `1.15` or not. The stable version still segfaults when built with a compiler newer than 1.68.

We've also opened up a rustsec [advisory](https://github.com/rustsec/advisory-db/pull/1726) just in case, but they want some input from you, the maintainers, of the crate to decide if it's a real security issue or not.

**Comment by zonyitoo** [comment]
1.16 will be released when trust-dns publish their final release.

Let's wait until the end of July, if trust-dns still didn't make their final release, I will backport this fix to 1.15.
