### ISSUE TITLE
Running the ssserver binary does not work, but ss-rust docker image works partially

### ISSUE THREAD

**Issue by ShrirajHegde** [shadowsocks/shadowsocks-rust#1240]
On one of the servers, Running the `ssserver` binary does not work (tested working in a different server)

So I decided to use the docker image, but it works partially. Some connections fail with `error: Address not available (os error 99) ` in both servers (even the server where directly running `ssserver` binary works fine)

Here is the log:

```
/usr/local/bin/docker-entrypoint.sh: Configuration complete; ready for start up                                                                               
INFO  shadowsocks server 1.15.4 build 2023-07-06T16:44:41.659763496+00:00                                                                                     
INFO  shadowsocks tcp server listening on 0.0.0.0:9000, inbound address 0.0.0.0:9000                                                                          
ERROR tcp tunnel [my_ip_address]:45906 -> [2404:6800:4009:812::2004]:443 connect failed, error: Address not available (os error 99)                           
ERROR tcp tunnel [my_ip_address]:41988 -> [2404:6800:4009:812::2004]:443 connect failed, error: Address not available (os error 99)                           
ERROR tcp tunnel [my_ip_address]:42012 -> [2404:6800:4009:812::2004]:443 connect failed, error: Address not available (os error 99)                           
ERROR tcp tunnel [my_ip_address]:42020 -> [2404:6800:4009:812::2004]:443 connect failed, error: Address not available (os error 99)                           
ERROR tcp tunnel [my_ip_address]:42034 -> [2a03:2880:f20c:1c6:face:b00c:0:7260]:443 connect failed, error: Address not available (os error 99)                
ERROR tcp tunnel [my_ip_address]:42044 -> [2a03:2880:f20c:1c6:face:b00c:0:7260]:80 connect failed, error: Address not available (os error 99)                 
ERROR tcp tunnel [my_ip_address]:42060 -> [2a03:2880:f231:c7:face:b00c:0:7260]:5222 connect failed, error: Address not available (os error 99)                
ERROR tcp tunnel [my_ip_address]:42062 -> [2a03:2880:f211:1ca:face:b00c:0:7260]:80 connect failed, error: Address not available (os error 99)  
```

**Comment by zonyitoo** [comment]
Please rerun `ssserver` with `strace` and see which exactly syscall returns `EADDRNOTAVAIL`.

**Comment by zonyitoo** [comment]
> On one of the servers, Running the ssserver binary does not work (tested working in a different server)

Please give more details about "does not work".

**Comment by ShrirajHegde** [comment]
> > On one of the servers, Running the ssserver binary does not work (tested working in a different server)
> 
> Please give more details about "does not work".

I mean, binary runs without any errors in the log (just shadowsocks listening). But connection doesn't work. I would like to know any known firewall or some other problem.

> Please rerun ssserver with strace and see which exactly syscall returns EADDRNOTAVAIL.

Regarding the OS error, it is unavailability of IPv6. So no need of strace I assume. I faced the exact difficulty with shadowsocks-libev.
I was able to solve the docker problem by disabling the "Route IPv6 traffic" since the docker container was not being able to access IPv6. Furthermore, I looked up and this is an issue with docker, so would be good to mention in the docker section. 

https://docs.docker.com/config/daemon/ipv6/#use-ipv6-for-the-default-bridge-network

This section gives instructions for enabling IPv6. 

With this, even IPv6 traffic works as intended.

**Comment by zonyitoo** [comment]
> I mean, binary runs without any errors in the log (just shadowsocks listening). But connection doesn't work. I would like to know any known firewall or some other problem.

I couldn't help about this :(

**Comment by ShrirajHegde** [comment]
Anyway, thanks.

It works on docker without IPv6.

**Comment by zonyitoo** [comment]
You should forbid your clients to send IPv6 targets to servers.

**Comment by ShrirajHegde** [comment]
Added a pull request with warning in README.md https://github.com/shadowsocks/shadowsocks-rust/pull/1241
