### ISSUE TITLE
shadowsocks-rust支持前置代理吗？

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-rust#1242]
shadowsocks-windows是支持正向代理（前置代理的）。但是没有看到shadowsocks-rust的相关配置，请问支持吗？如果支持，如何配置？谢谢！

**Comment by tianlichunhong** [comment]
> What exactly is the "forward proxy" in shadowsocks-windows? Or in other word, what do you want to achieve?

Thank you for your reply!
In my company, to get on the internet, I need to set up  http proxy. How do I use shadowsocks-rust in this case? 
 shadowsocks-windows has this function as below:

![image](https://github.com/shadowsocks/shadowsocks-rust/assets/13270039/03ee04f4-d2d1-4443-b829-c8f0f39c25c0)

**Comment by zonyitoo** [comment]
So this forward proxy works between `sslocal` and `ssserver`, like this:

```
sslocal -> "forward proxy" -> ssserver
```

If I understand it correctly, `sslocal` in this project doesn't support it internally.

You could make a "plugin" to work as a "forward proxy".

**Comment by tianlichunhong** [comment]
> 

but I didn't found any forward proxy plugin for shadowsovks-rust. If you know, can you share the link. Thank uou!

**Comment by zonyitoo** [comment]
I don't know, either.

**Comment by fernvenue** [comment]
That's actually an useful feature, is it possible that make ssserver go out through another socks service?

**Comment by zonyitoo** [comment]
Any PRs are welcome, I don't need this feature in real life, so I currently have no motivation to implement this feature.

**Comment by HTensor** [comment]
> That's actually an useful feature, is it possible that make ssserver go out through another socks service?

Maybe you can use gost
