### ISSUE TITLE
为什么我在windows下跑不起来

### ISSUE THREAD

**Issue by unknownUser99999** [shadowsocks/shadowsocks-rust#1251]

**Comment by unknownUser99999** [comment]
我说的是windows作为客户端，不是服务器

**Comment by unknownUser99999** [comment]
我说的是windows作为客户端，不是服务器 。是需要用v2rayN代替吗

**Comment by zonyitoo** [comment]
You should at lease provide details about: how to reproduce? What did you see? Did you see any logs?

**Comment by unknownUser99999** [comment]
> 您至少应该提供以下详细信息：如何重现？ 你看见什么了？ 你看到任何日志了吗？

直接闪退啊

**Comment by unknownUser99999** [comment]
> 您至少应该提供以下详细信息：如何重现？ 你看见什么了？ 你看到任何日志了吗？

missing `local_address`, consider specifying it by --local-addr command line option, or "local_address" and "local_port" in configuration file

**Comment by unknownUser99999** [comment]
> 您至少应该提供以下详细信息：如何重现？ 你看见什么了？ 你看到任何日志了吗？

是需要配置文件吗

**Comment by zonyitoo** [comment]
Yes. You should at least read the README document. If you are seeking for a client with UI, this project couldn't help.

**Comment by unknownUser99999** [comment]
> 是的。 您至少应该阅读 README 文档。 如果您正在寻找具有 UI 的客户，这个项目将帮不上忙。

我想问下，确定这个是可以作为客户端的，我感觉你写的这个是用作服务端的。

**Comment by zonyitoo** [comment]
Of course not. Who said that a client should have a graphic UI.

**Comment by unknownUser99999** [comment]
> 当然不是。 谁说客户端应该有图形用户界面。

好吧，但是当我以配置文件运行，他依然报错
2023-07-18T12:34:24.452408700+08:00 ERROR unsupported socks version 43
2023-07-18T12:34:24.452659500+08:00 ERROR socks5 tcp client handler error: unsupported socks version

**Comment by zonyitoo** [comment]
Read the doc please.
