### ISSUE TITLE
UDP overhead when using "none" encryption method?

### ISSUE THREAD

**Issue by LindaFerum** [shadowsocks/shadowsocks-rust#1260]
Hi! Basically familiarized myself with this https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md

And came to ask / clarify, what's the overhead on UDP packets when method "plain/none" is used?

is it 16B header + "payload" 
or 
16B header + 16B tag + payload ? (I am under impression that the "tag" may mean AEAD tag which obviously should not be there for "plain/none")

Also do I understand correctly that the "payload" here fully encapsulates the original UDP packet so I should keep extra 28 bytes (IPv4+UDP) in mind?

**Comment by database64128** [comment]
> And came to ask / clarify, what's the overhead on UDP packets when method "plain/none" is used?

Under the plain/none method, each packet is just SOCKS address + payload.

> Also do I understand correctly that the "payload" here fully encapsulates the original UDP packet so I should keep extra 28 bytes (IPv4+UDP) in mind?

No, the payload is just the original UDP payload (without the 8-byte UDP header or 20/40-byte IP header).

**Comment by LindaFerum** [comment]
The SOCKS address means RFC [1928](https://www.rfc-editor.org/rfc/rfc1928) UDP request header?

**Comment by database64128** [comment]
No, just ATYP + address + port.

**Comment by LindaFerum** [comment]
Thanks!
