### ISSUE TITLE
Make it build on stable Rust

### ISSUE THREAD

**Issue by asypost** [shadowsocks/shadowsocks-rust#129]
It seems the use of spin-rs make it can't build with stable Rust compiler,beacause spin-rs use the const-fn feature by default.But there's a way to disable this by adding `default-features = false` to the dependencies.spin section.details on bellow:
`[dependencies.spin]`
`version = "0.4"`
` default-features = false`

**Comment by zonyitoo** [comment]
Ah. Sorry. I have already done it in my local branch. Committing right now.
