### ISSUE TITLE
Command line parameters to register ssserver.exe or sslocal.exe as Windows Service

### ISSUE THREAD

**Issue by SignFinder** [shadowsocks/shadowsocks-rust#1292]
Might it is a good idea to add command line parameters like --service-install --service-uninstall to able register sslocal.exe or ssserver.exe as Windows Service using windows sc command and send to the command all necessary variables.
Fox example - like zabbix agent for Windows works https://www.zabbix.com/documentation/current/en/manual/appendix/install/windows_agent

**Comment by zonyitoo** [comment]
https://stackoverflow.com/questions/3582108/create-windows-service-from-executable

Is that `sc` command works as you expected?

**Comment by SignFinder** [comment]
> https://stackoverflow.com/questions/3582108/create-windows-service-from-executable
> 
> Is that `sc` command works as you expected?

Unfortunately no, service creating correct, but it is not started as I expected :-( with error 1053 (Windows 11 22H2 x64)
![Screenshot 2023-09-11 214951](https://github.com/shadowsocks/shadowsocks-rust/assets/299814/57f3c7e3-6a4d-4748-a8d9-b5529866730a)

**Comment by zonyitoo** [comment]
Just walk through an example code of a Windows Service: https://learn.microsoft.com/en-us/windows/win32/services/svc-cpp . If you want to run `sslocal` as a Windows Service, you will have to make a runnable binary that register system callbacks with Windows' APIs.

It may be hard to integrated those into `sslocal`. I would suggest to make a new runnable to run as a service, and then start `sslocal` via new processes.

**Comment by zonyitoo** [comment]
Complile a Windows Service adapter:

```
cargo build --release --bin "sswinservice" --features "winservice"
```

Register it as a Windows Service, for example with Powershell:

```powershell
New-Service -Name "shadowsocks-local-service" -DisplayName "Shadowsocks Local Service" -BinaryPathName "<path_to>\sswinservice.exe local -c <path_to_config>.json"
```

Start the service from the Service application.
