### ISSUE TITLE
No voice call via WhatsApp or Telegram

### ISSUE THREAD

**Issue by navhawk80** [shadowsocks/shadowsocks-rust#1293]
Hello, I'm using teddysun/shadowsocks-rust docker container latest at the moment version v1.16.1. Since vervion 1.15.0 voice calls via WhatsApp or Telegram do not work (I did not try any other messengers). When call is coming the phone is rinning , pick up the phone and it always trying to reconnect than after some time connection resets itself with No connection message.
Just find out by trying one by one previous version that last one where calls work is v1.14.3.
In docker container there are a lot of errors:

<details><summary>Container log</summary>
<p>

ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:3446 -> 91.108.9.88:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:24284 -> 91.108.13.55:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:18506 -> 91.108.17.51:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:3446 -> 91.108.9.88:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:24284 -> 91.108.13.55:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:18506 -> 91.108.17.51:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:3446 -> 91.108.9.88:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:24284 -> 91.108.13.55:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:18506 -> 91.108.17.51:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:18506 -> 91.108.17.51:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:3446 -> 91.108.9.88:599 with 40 bytes, error: Address family not supported by protocol (os error 97)
ERROR udp relay 178.176.77.241:24284 -> 91.108.13.55:599 with 40 bytes, error: Address family not supported by protocol (os error 97)

</p>
</details> 

<details><summary>my config.json</summary>
<p>

{
"servers": [
{
"address": "0.0.0.0",
"port": 77777,
"password": "password",
"method": "chacha20-ietf-poly1305",
"nameserver": "10.0.1.1",
"plugin": "v2ray-plugin",
"plugin_opts": "server;loglevel=none",
"mode": "tcp_only"
},
{
"address": "0.0.0.0",
"port": 88888,
"password": "password",
"method": "chacha20-ietf-poly1305",
"nameserver": "10.0.1.1",
"mode": "tcp_and_udp"
}
],

"timeout": 300,
"no_delay": true,
"fast_open": true,
"reuse_port": true,
"workers": 1,
// "log": {
// "level": 1,
// "format": {"without_time": false,},
// },
}

</p>
</details> 

When using v1.14.3 logs is clear and all is working with the same configuration.

Can you look at the issue?
Thank you.

**Comment by zonyitoo** [comment]
> ERROR udp relay 178.176.77.241:2776 -> 91.108.17.9:47539 with 96 bytes, error: Address family not supported by protocol (os error 97)

Could you run it again with `strace` and see which exactly syscall returns `EAFNOSUPPORT`?

I thought it was because your system doesn't support IPv6.

**Comment by zonyitoo** [comment]
Outbound UDP sockets were created in dual-stack mode:

https://github.com/shadowsocks/shadowsocks-rust/blob/a47fc19e08747269307379d1a311454fc48bed84/crates/shadowsocks-service/src/server/udprelay.rs#L672-L738

So if your system was too old, or had IPv6 dual-stack mode disabled, you should see `EAFNOSUPPORT`.

**Comment by navhawk80** [comment]
> I thought it was because your system doesn't support IPv6

You are right. IPv6 was disabled. Just enabled it and now voice calls are working again.
Thank you.

**Comment by ahmeaqas** [comment]
Visit troubleshooting section of [Unlocking the Internet: A Step-by-Step Guide to Setting Up Your Own Shadowsocks-Rust Proxy Server on Linux](https://hobbytronics.pk/unlocking-the-internet-a-step-by-step-guide-to-setting-up-your-own-shadowsocks-rust-proxy-server-on-linux/#google_vignette).
