### ISSUE TITLE
Improving shadowsocks-rust Performance with Kernel TLS

### ISSUE THREAD

**Issue by Alion548** [shadowsocks/shadowsocks-rust#1301]
Transport Layer Security (TLS) is an extremely popular cryptography protocol. Implementing TLS in the kernel (kTLS) improves performance by significantly reducing the need for copying operations between user space and the kernel.

https://docs.kernel.org/networking/tls.html
https://www.nginx.com/blog/improving-nginx-performance-with-kernel-tls/

**Comment by zonyitoo** [comment]
There is no TLS operations in shadowsocks-rust.
