### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by bzmjcster** [shadowsocks/shadowsocks-rust#1310]
2023-09-23 20:30:21.3876|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by zonyitoo** [comment]
What is that?

**Comment by bzmjcster** [comment]
无法链接呢

**Comment by zonyitoo** [comment]
I don't think it was reported from this project.

**Comment by bzmjcster** [comment]
我在看看是什么原因呢
