### ISSUE TITLE
Error when launching shadowsocks in Docker on port 443 and network_mode: "host"

### ISSUE THREAD

**Issue by nix155** [shadowsocks/shadowsocks-rust#1323]
When launching shadowsocks in Docker on port 443 with the network_mode set to "host", I get the error:
shadowsocks | INFO shadowsocks server 1.16.2 build 2023-09-23T06:54:41.971144846+00:00
shadowsocks | /usr/bin/docker-entrypoint.sh: Configuration complete; ready for start up
shadowsocks | server aborted with Permission denied (os error 13)
Changing the port or the network_mode from "host" resolves the error.
Here are my docker-compose.yml
`version: '3.9'
services:
  shadowsocks:
    container_name: shadowsocks
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    restart: always
    volumes:
      - ./config.json:/etc/shadowsocks-rust/config.json
    network_mode: "host"
`
and json.config.
`{
    "server": "0.0.0.0",
    "server_port": 443,
    "password": "password",
    "timeout": 300,
    "method":"chacha20-ietf-poly1305",
    "fast_open" :true,
}`

**Comment by zonyitoo** [comment]
You may have to start with root, or other users that have proper privileges to listen port 443.

**Comment by zonyitoo** [comment]
Interesting. Could you run the binary with strace and see which exactly syscall returns EPERM?

**Comment by nix155** [comment]
I entered the container, added strace, started debugging - and there is no error. Then I replaced the entrypoint - entrypoint: ssserver -c /etc/shadowsocks-rust/config.json - and there is also no error. It means that something is wrong with docker-entrypoint.sh.

**Comment by zonyitoo** [comment]
`-a nobody`

**Comment by zonyitoo** [comment]
Actually, you may add a port forwarding configuration when starting with docker:

https://docs.docker.com/network/

then the server in container doesn't need those priviledges.
