### ISSUE TITLE
[Feature Request] Support socks/http mix protocol in sslocal

### ISSUE THREAD

**Issue by hronro** [shadowsocks/shadowsocks-rust#1324]
It would be great if `sslocal` could serve as both an HTTP/SOCKS proxy using only one port.

**Comment by zonyitoo** [comment]
There is no easy way to implement this feature. Feel free to open a PR if you find a proper way.

**Comment by zonyitoo** [comment]
Here is one obstacle that blocking this issue:

- SOCKS5 is implemented via pure `TcpListener`, but HTTP is with [`hyper`](https://crates.io/crates/hyper).

How to hijack the `accept()` result and check the first byte of the TCP stream? How to divert the handling routine from HTTP to SOCKS?

**Comment by zonyitoo** [comment]
Supported on master branch.
