### ISSUE TITLE
`run_as_user()` should abort execution on error conditions

### ISSUE THREAD

**Issue by mgerstner** [shadowsocks/shadowsocks-rust#1328]
Currently [run_as_user()](https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/sys.rs#L80) only prints out warnings if dropping privileges to a configured user accounts fails or is incomplete.

Since lowered privileges are a major security property I believe the execution of the daemon should stop if the desired privileges cannot be successfully established.

**Comment by zonyitoo** [comment]
Reasonable. Could you open a PR for this?
