### ISSUE TITLE
feature request: support macOS's launch_activate_socket

### ISSUE THREAD

**Issue by liudongmiao** [shadowsocks/shadowsocks-rust#1330]
In shadowsocks-libev, there is `launch_activate_socket` in https://github.com/shadowsocks/shadowsocks-libev/pull/1003.
In shadowsocks-rust, there is no such feature.

So, it's possible for shadowsocks-rust to support this feature?

There is another rust project https://github.com/LinkTed/doh-client ships with `launch_activate_socket`.

**Comment by zonyitoo** [comment]
It seems that you only create the TCP socket via `launch_activate_socket`, how about the UDP socket?

**Comment by zonyitoo** [comment]
https://github.com/LinkTed/doh-client/blob/master/src/listen/activation_socket.rs#L32

It has memory leaks if `launch_activate_socket` returns `cnt > 1`.

**Comment by liudongmiao** [comment]
@zonyitoo I will try to implement and make a PR.
