### ISSUE TITLE
Protocol "tun" not working

### ISSUE THREAD

**Issue by oxoWrk** [shadowsocks/shadowsocks-rust#1337]
I'm using the latest release  v1.17.0
In server logs:
[shadowsocks_service::server::tcprelay] tcp handshake failed, received EOF before a complete target Address, peer: X.X.X.X:12345

**Comment by zonyitoo** [comment]
tun is for local server, not remote server.

**Comment by oxoWrk** [comment]
Then I don't understand how it can be used...
Can you show an example of usage?

**Comment by zonyitoo** [comment]
Please read `README.md`, there is an example in there.
