### ISSUE TITLE
Custom TLS, HTTPS, HTTP/3 DNS.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-rust#1339]
Since shadowsocks-rust now has `cloudflare_tls`, `cloudflare_https` and `google_h3`, is it possible that shadowsocks-rust supports custom DNS-over-TLS, DNS-over-HTTPS and DNS-over-HTTP/3 as DNS?

**Comment by zonyitoo** [comment]
There is a hidden feature, that you can specify a JSON Object as a `ResolverConfig`, https://docs.rs/hickory-resolver/0.24.0/hickory_resolver/config/struct.ResolverConfig.html .

```json
{
    "dns": {
        "name_servers": [
            {  ... }
        ]
    }
```

But it is unstable, because the format will change if the definition of `ResolverConfig` changes.

**Comment by fernvenue** [comment]
Hi @zonyitoo, thanks for your reply, could you please give me an example? What if I wanna add `tls://203.0.113.1:8853`, `https://[2001:db8::1]:443/dns-query` and `h3://[2001:db8::1]:8443/dns-query`?

**Comment by zonyitoo** [comment]
You may try to open a PR for it. BTW, I think the `/dns-query` path is not necessary.

**Comment by zonyitoo** [comment]
On the other hand, is `h3` is the standard scheme of h3?

**Comment by fernvenue** [comment]
> On the other hand, is `h3` is the standard scheme of h3?

It's another application's behavior I think, details [here](https://github.com/AdguardTeam/AdGuardHome/blob/62ec0d5adc1f5c0281de2299b1c501b1d0393f1f/CHANGELOG.md?plain=1#L1305).

**Comment by fernvenue** [comment]
Seems work fine in these days, I'm gonna close this issue for now :)
