### ISSUE TITLE
持续增加udp监听端口

### ISSUE THREAD

**Issue by foxconndmd** [shadowsocks/shadowsocks-rust#134]
未开启udp转发，浏览器使用远程dns通过socks5，udp监听端口持续增加，后来就算没使用也一直保持监听几百个udp端口。
不知这种情况正常不？
昨晚300多，今天早上1000多了。
netstat -ulnp|grep ssserver|wc -l
1132
1.6.12和最新版本都是这样。

**Comment by zonyitoo** [comment]
`ssserver`的udp确认关闭了么？重启时有日志可以看到有没有listening UDP

**Comment by foxconndmd** [comment]
@zonyitoo 确定关闭了，同时我还使用iptables禁止了所有udp流量进入。

**Comment by zonyitoo** [comment]
我想可能跟这个有关 https://github.com/bluejekyll/trust-dns/issues/633

**Comment by zonyitoo** [comment]
trust-dns的修复已经发布，相信已经修复，可以测试一下

**Comment by foxconndmd** [comment]
好的，我试试再来回复。

**Comment by foxconndmd** [comment]
正常了。
