### ISSUE TITLE
配置文件中无法使用注释

### ISSUE THREAD

**Issue by e2ge** [shadowsocks/shadowsocks-rust#135]
非常喜欢rust版本中的负载均衡功能，虽然比较基础，但是提供了一个可能。
有个问题就是服务器多了之后希望能加个注释注明以下，但是貌似加了注释就无法启动了。
是否的确不支持注释的功能，还是win下的问题？谢谢。

win10下，v1.6.12

**Comment by zonyitoo** [comment]
标准的JSON格式本身就不支持注释。要支持的话要看看serde-json能不能支持，mark下先

**Comment by e2ge** [comment]
谢谢。

**Comment by zonyitoo** [comment]
hjson正在试，但是有一个BUG。它解析时，Number类型的全都解析为`F64`，所以切换之后出了问题。

**Comment by zonyitoo** [comment]
在最新的Commit中已支持。
