### ISSUE TITLE
ssurl added escape character in password

### ISSUE THREAD

**Issue by brianwoo** [shadowsocks/shadowsocks-rust#1355]
It seems that ssurl is adding an escape character in the password:

```bash
cat ~/Downloads/client.json 
{
  "server": "1.2.3.4",
  "server_port": 8400,
  "password": "F6BY4IwbXB5Juobo2aofoJ6P86G/yBYJO3pJzcMIUOU=",
  "method": "2022-blake3-chacha20-poly1305"
}
```
Encoding:
```bash
/opt/shadowsocks/ssurl --encode ~/Downloads/client.json
ss://2022-blake3-chacha20-poly1305:F6BY4IwbXB5Juobo2aofoJ6P86G%2FyBYJO3pJzcMIUOU%3D@1.2.3.4:8400
```

Decoding (notice the password has a backslash for escaping the forward slash):
```bash
/opt/shadowsocks/ssurl --decode ss://2022-blake3-chacha20-poly1305:F6BY4IwbXB5Juobo2aofoJ6P86G%2FyBYJO3pJzcMIUOU%3D@1.2.3.4:8400
{"server":"1.2.3.4","server_port":8400,"password":"F6BY4IwbXB5Juobo2aofoJ6P86G\/yBYJO3pJzcMIUOU=","method":"2022-blake3-chacha20-poly1305","mode":"tcp_and_udp"}
```

**Comment by zonyitoo** [comment]
https://www.json.org/json-en.html

Yes, `/` should be escaped.

**Comment by brianwoo** [comment]
@zonyitoo when that happens, I can no longer load the ss:// string into the Android app.  Are you saying that that's a bug on the Android side?

**Comment by zonyitoo** [comment]
I suppose so.

**Comment by zonyitoo** [comment]
```
ss://2022-blake3-chacha20-poly1305:F6BY4IwbXB5Juobo2aofoJ6P86G%2FyBYJO3pJzcMIUOU%3D@1.2.3.4:8400
```

The `ss://` in your example, password is: `F6BY4IwbXB5Juobo2aofoJ6P86G/yBYJO3pJzcMIUOU=`.

So what do you mean:

> can no longer load the ss:// string into the Android app

**Comment by brianwoo** [comment]
> ```
> ss://2022-blake3-chacha20-poly1305:F6BY4IwbXB5Juobo2aofoJ6P86G%2FyBYJO3pJzcMIUOU%3D@1.2.3.4:8400
> ```
> 
> The `ss://` in your example, password is: `F6BY4IwbXB5Juobo2aofoJ6P86G/yBYJO3pJzcMIUOU=`.
> 
> So what do you mean:
> 
> > can no longer load the ss:// string into the Android app

Yeah, if you copy that ss:// string, from the Android app, you import that string, it will say "Failed to Import."  Is the Android app at fault here?

**Comment by brianwoo** [comment]
Just to clarify, from the Android App, there are 2 ways to import the configuration (by ss:// string or by file).  There is no problem with importing by the json file.  However, loading the equivalent ss:// string I get the "Failed to Import".  I am not sure if it's the ssurl's fault or the Android app's.

**Comment by zonyitoo** [comment]
You should open an issue to the Android project instead.
