### ISSUE TITLE
插件启动参数失效

### ISSUE THREAD

**Issue by baijunty** [shadowsocks/shadowsocks-rust#136]
服务器部署的时候一直没成功，本地编译试了下也是这样。
插件：tcptun
{
	"server": "127.0.0.1",
	"server_port": 8500,
	"local_address": "127.0.0.1",
	"local_port": 8600,
	"password": "12345678",
	"timeout": 600,
	"method": "aes-256-gcm",
	"plugin": "server_windows_amd64",
	"plugin_opts": "-t \"127.0.0.1: 8500\" -l \": 10010\" -mode fast -key \"12345678\" -crypt aes-192",
	"enable_udp": true,
	"udp_timeout": 300
}
启动后变成了。
![image](https://user-images.githubusercontent.com/8980568/50044470-bf03e300-00be-11e9-92e2-430cc550cbc7.png)
插件运行参数没修改成功，还是默认参数。

**Comment by zonyitoo** [comment]
给你的配置加上语法高亮：

```json
{
"server": "127.0.0.1",
"server_port": 8500,
"local_address": "127.0.0.1",
"local_port": 8600,
"password": "12345678",
"timeout": 600,
"method": "aes-256-gcm",
"plugin": "server_windows_amd64",
"plugin_opts": "-t "127.0.0.1: 8500" -l ": 10010" -mode fast -key "12345678" -crypt aes-192",
"enable_udp": true,
"udp_timeout": 300
}
```

**Comment by zonyitoo** [comment]
另外，我猜你是不是对shadowsocks插件的运行方式有误解？`plugin_opts`不是命令`plugin`的命令行参数，而是通过`SS_PLUGIN_OPTIONS`这个环境变量传过去的。

**Comment by baijunty** [comment]
好吧，是我搞错了。
大概试了下Windows客户端的参数确实生效正确启动起来了。
![image](https://user-images.githubusercontent.com/8980568/50044957-15c0eb00-00c6-11e9-8441-fae09115afb0.png)
我再看看服务器怎么弄。
打扰了，关了吧。

**Comment by zonyitoo** [comment]
```json
{
"server": "127.0.0.1",
"server_port": 8500,
"local_address": "127.0.0.1",
"local_port": 8600,
"password": "12345678",
"timeout": 600,
"method": "aes-256-gcm",
"plugin": "server_windows_amd64",
"plugin_opts": "-t \"127.0.0.1: 8500\" -l \": 10010\" -mode fast -key \"12345678\" -crypt aes-192",
"enable_udp": true,
"udp_timeout": 300
}
```

这样试一下？Windows版是指这个版本吗？https://github.com/shadowsocks/shadowsocks-windows

**Comment by baijunty** [comment]
> 看了一下代码，一样是实现的SIP003，https://github.com/shadowsocks/shadowsocks-windows/blob/14559b5ef60d2e580e90adea33c26c15ca61c0cb/shadowsocks-csharp/Controller/Service/Sip003Plugin.cs#L69
> 
> 你用的tcptun是哪个版本？我重现一下？
就是官方原版最新的，是我的理解问题，现在不用SIP003规范只按流程自己手动启动tcptun绑定端口转发shadowsocks流量也能正常使用了，还有就是昨天跑着跑着服务器端shadowsocks文件打开数量超句柄限制跑飞了，不知道是不是tcptun的原因

**Comment by zonyitoo** [comment]
server fd limit的问题看这个 #127
