### ISSUE TITLE
编译target aarch64-pc-windows-msvc 报错failed to run custom build command for `ring v0.16.20`

### ISSUE THREAD

**Issue by vandykeWei** [shadowsocks/shadowsocks-rust#1360]
请问，编译目标版本是aarch64-pc-windows-msvc 时，报错error: failed to run custom build command for `ring v0.16.20`。 是本地配置不完善还是其他问题？ 请教各位大佬.

**Comment by zonyitoo** [comment]
Please give more details about what exactly the error with extra outputs.

**Comment by vandykeWei** [comment]
下面是编译输出
PS E:\wgfWork\shadowsocks-rust\shadowsocks-rust-1.17.1> cargo build --target aarch64-pc-windows-msvc --release
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling autocfg v1.1.0
   Compiling typenum v1.17.0
   Compiling windows_aarch64_msvc v0.48.5
   Compiling version_check v0.9.4
   Compiling subtle v2.5.0
   Compiling zeroize v1.6.0
   Compiling winapi v0.3.9
   Compiling memchr v2.6.4
   Compiling serde v1.0.188
   Compiling thiserror v1.0.50
   Compiling futures-core v0.3.29
   Compiling pin-project-lite v0.2.13
   Compiling parking_lot_core v0.9.8
   Compiling futures-sink v0.3.29
   Compiling futures-channel v0.3.29
   Compiling scopeguard v1.2.0
   Compiling futures-task v0.3.29
   Compiling bytes v1.5.0
   Compiling futures-util v0.3.29
   Compiling smallvec v1.11.1
   Compiling const-oid v0.9.5
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.29
   Compiling itoa v1.0.9
   Compiling once_cell v1.18.0
   Compiling cc v1.0.83
   Compiling opaque-debug v0.3.0
   Compiling num_cpus v1.16.0
   Compiling base16ct v0.1.1
   Compiling cpufeatures v0.2.9
   Compiling tinyvec_macros v0.1.1
   Compiling percent-encoding v2.3.0
   Compiling linked-hash-map v0.5.6
   Compiling ppv-lite86 v0.2.17
   Compiling fnv v1.0.7
   Compiling ucd-trie v0.1.6
   Compiling crossbeam-utils v0.8.16
   Compiling async-trait v0.1.74
   Compiling base64ct v1.6.0
   Compiling unicode-bidi v0.3.13
   Compiling windows_aarch64_msvc v0.52.0
   Compiling libc v0.2.149
   Compiling ryu v1.0.15
   Compiling getrandom v0.2.10
   Compiling ipnet v2.9.0
   Compiling match_cfg v0.1.0
   Compiling serde_json v1.0.108
   Compiling ipconfig v0.3.2
   Compiling untrusted v0.7.1
   Compiling heck v0.4.1
   Compiling windows_x86_64_msvc v0.48.5
   Compiling der v0.6.1
   Compiling tinyvec v1.6.0
   Compiling arrayvec v0.7.4
   Compiling hashbrown v0.14.2
   Compiling equivalent v1.0.1
   Compiling tracing-core v0.1.31
   Compiling generic-array v0.14.7
   Compiling form_urlencoded v1.2.0
   Compiling lock_api v0.4.10
   Compiling slab v0.4.9
   Compiling num-traits v0.2.17
   Compiling indexmap v1.9.3
   Compiling rand_core v0.6.4
   Compiling httparse v1.8.0
   Compiling widestring v1.0.2
   Compiling data-encoding v2.4.0
   Compiling http v1.0.0
   Compiling arrayref v0.3.7
   Compiling constant_time_eq v0.3.0
   Compiling quick-error v1.2.3
   Compiling syn v1.0.109
   Compiling anstyle v1.0.4
   Compiling utf8parse v0.2.1
   Compiling lru-cache v0.1.2
   Compiling aho-corasick v1.1.2
   Compiling destructure_traitobject v0.2.0
   Compiling arc-swap v1.6.0
   Compiling colorchoice v1.0.0
   Compiling indexmap v2.1.0
   Compiling try-lock v0.2.4
   Compiling hashbrown v0.12.3
   Compiling unicode-normalization v0.1.22
   Compiling spki v0.6.0
   Compiling regex-syntax v0.8.0
   Compiling anyhow v1.0.75
   Compiling yaml-rust v0.4.5
   Compiling lru_time_cache v0.11.11
   Compiling signature v1.6.4
   Compiling rand_chacha v0.3.1
   Compiling ring v0.16.20
   Compiling blake3 v1.5.0
   Compiling windows-targets v0.48.5
   Compiling http-body v1.0.0
   Compiling base64 v0.21.5
   Compiling clap_lex v0.6.0
   Compiling byte_string v1.0.0
   Compiling unsafe-any-ors v1.0.0
   Compiling option-ext v0.2.0
   Compiling want v0.3.1
   Compiling iprange v0.6.7
   Compiling log-mdc v0.1.0
   Compiling pkcs8 v0.9.0
   Compiling byteorder v1.5.0
   Compiling quote v1.0.33
   Compiling humantime v2.1.0
   Compiling ed25519 v1.5.3
   Compiling idna v0.4.0
   Compiling checked_int_cast v1.0.0
   Compiling sysexits v0.7.5
   Compiling xdg v2.5.2
   Compiling rand v0.8.5
   Compiling crossbeam-channel v0.5.8
   Compiling windows-sys v0.48.0
   Compiling windows-targets v0.52.0
   Compiling typemap-ors v1.0.0
   Compiling syn v2.0.38
   Compiling qrcode v0.12.0
   Compiling regex-automata v0.4.1
   Compiling spin v0.9.8
   Compiling windows-sys v0.52.0
   Compiling parking_lot v0.12.1
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `E:\wgfWork\shadowsocks-rust\shadowsocks-rust-1.17.1\target\release\build\ring-e15e403c9ad795bd\build-script-build` (exit code: 101)
  --- stderr
  running "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\arm64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "include" "-W4" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Ox" "-DNDEBUG" "-c" "/FoE:\\wgfWork\\shadowsocks-rust\\shadowsocks-rust-1.17.1\\target\\aarch64-pc-windows-msvc\\release\\build\\ring-159338429db30282\\out\\aes_nohw.obj" "crypto/fipsmodule/aes/aes_nohw.c"
  running "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\arm64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "include" "-W4" "/GS" "/Gy" "/EHsc" "/GR-" "/Zc:wchar_t" "/Zc:forScope" "/Zc:inline" "/Zc:rvalueCast" "/sdl" "/Wall" "/wd4127" "/wd4464" "/wd4514" "/wd4710" "/wd4711" "/wd4820" "/wd5045" "/Ox" "-DNDEBUG" "-c" "/FoE:\\wgfWork\\shadowsocks-rust\\shadowsocks-rust-1.17.1\\target\\aarch64-pc-windows-msvc\\release\\build\\ring-159338429db30282\\out\\montgomery.obj" "crypto/fipsmodule/bn/montgomery.c"
  thread 'main' panicked at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.16.20\build.rs:656:9:
  execution failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by AaronChen0** [comment]
Quote from the ring build page (https://github.com/briansmith/ring/blob/main/BUILDING.md) :

> For Windows ARM64 targets (aarch64-pc-windows-msvc), the Visual Studio Build Tools “VS 2022 C++ ARM64 build tools” and "clang" components must be installed. 

You are using `Microsoft Visual Studio\2019\Community`. Do you meet that requirement?

**Comment by zonyitoo** [comment]
ref https://github.com/briansmith/ring/issues/1167

**Comment by zonyitoo** [comment]
Upgrade shadowsocks-crypto's dependency should be able to fix this issue.
