### ISSUE TITLE
How to prevent user share their account?

### ISSUE THREAD

**Issue by nickcartery** [shadowsocks/shadowsocks-rust#1368]
I want to prevent user from sharing their account publicly, It will make my server stressed. Is there any way to limit 1 IP source to 1 port?
Currently, I can limit user quota bandwidth.
I also noticed that the TCP keep-alive will keep the previous connections, so I don't know how to reject the previous IP source and accept the new IP source, so this rule does not work:

```
sudo iptables -A INPUT -p tcp --syn --dport 8080 -m recent --name port8080 --set
sudo iptables -A INPUT -p tcp --syn --dport 8080 -m recent --name port8080 --update --seconds 60 --hitcount 2 -j REJECT

```

**Comment by zonyitoo** [comment]
You can limits every users to have only N active Client IPs by adding a proxy server.
