### ISSUE TITLE
最近的更新导致内存占用的增加

### ISSUE THREAD

**Issue by asypost** [shadowsocks/shadowsocks-rust#137]
最近的更新(92c4058)会导致内存占用的增加，而且据观察会随着时间慢慢增长。
我的使用环境是Ubuntu 14.04，1G内存。两天的使用内存占用达到了4.1%，之前的版本内存占用一般稳定在1.8%左右。

**Comment by zonyitoo** [comment]
这……不可能吧。这个commit理应不可能产生这样的效果

**Comment by zonyitoo** [comment]
是否有cargo update？

**Comment by asypost** [comment]
有 @zonyitoo

**Comment by zonyitoo** [comment]
可能是某个依赖库的更新导致的。试下不`cargo update`，用我提交的`Cargo.lock`里固定下来的依赖版本

**Comment by asypost** [comment]
好的，明天有时间我测试下

**Comment by zonyitoo** [comment]
你可以再执行一次`cargo update`，然后会输出更新的依赖。把输出的数据贴一下？

**Comment by asypost** [comment]
cargo update
    Updating crates.io index
    Updating arrayvec v0.4.7 -> v0.4.9                                                                                                                                                                         
      Adding autocfg v0.1.1
    Updating backtrace v0.3.9 -> v0.3.13
    Updating backtrace-sys v0.1.24 -> v0.1.26
    Updating bzip2-sys v0.1.6 -> v0.1.7
    Updating cc v1.0.25 -> v1.0.27
      Adding crc32fast v1.1.2
    Updating crossbeam-deque v0.6.2 -> v0.6.3
    Updating crossbeam-epoch v0.6.1 -> v0.7.0
    Updating crossbeam-utils v0.6.1 -> v0.6.3
    Updating flate2 v1.0.5 -> v1.0.6
    Removing flate2-crc v0.1.0
    Updating h2 v0.1.13 -> v0.1.14
    Updating http v0.1.13 -> v0.1.14
    Updating humantime v1.1.1 -> v1.2.0
    Updating ipconfig v0.1.7 -> v0.1.9
    Updating lazycell v1.2.0 -> v1.2.1
    Updating libc v0.2.43 -> v0.2.45
    Updating memchr v2.1.1 -> v2.1.2
    Updating num_cpus v1.8.0 -> v1.9.0
    Updating openssl v0.10.15 -> v0.10.16
    Updating openssl-sys v0.9.39 -> v0.9.40
      Adding rand v0.6.1
      Adding rand_chacha v0.1.0
      Adding rand_hc v0.1.0
      Adding rand_isaac v0.1.1
      Adding rand_pcg v0.1.1
      Adding rand_xorshift v0.1.0
    Updating redox_syscall v0.1.42 -> v0.1.44
    Updating regex v1.0.6 -> v1.1.0
    Updating regex-syntax v0.6.3 -> v0.6.4
    Updating rustc-demangle v0.1.9 -> v0.1.11
    Updating serde v1.0.80 -> v1.0.82
    Updating smallvec v0.6.6 -> v0.6.7
    Updating string v0.1.1 -> v0.1.2
    Updating subprocess v0.1.17 -> v0.1.18
    Updating syn v0.15.21 -> v0.15.23
    Updating time v0.1.40 -> v0.1.41
    Updating tokio v0.1.11 -> v0.1.13
    Updating tokio-current-thread v0.1.3 -> v0.1.4
    Updating tokio-reactor v0.1.6 -> v0.1.7
    Updating tokio-signal v0.2.6 -> v0.2.7
    Updating tokio-threadpool v0.1.8 -> v0.1.9
    Updating tokio-timer v0.2.7 -> v0.2.8
    Updating tokio-udp v0.1.2 -> v0.1.3
    Updating tokio-uds v0.2.3 -> v0.2.4
      Adding trust-dns-proto v0.6.1
    Updating trust-dns-resolver v0.10.0 -> v0.10.1

**Comment by asypost** [comment]
crossbeam 的 这个bug https://github.com/crossbeam-rs/crossbeam/issues/273 会有影响吗

**Comment by zonyitoo** [comment]
不太清楚，要研究一下。这是间接引用了。。

**Comment by asypost** [comment]
测试了下最新的版本，发现内存使用比较稳定了。我觉得这个issue可以关闭了。
