### ISSUE TITLE
多配置文件

### ISSUE THREAD

**Issue by yiguihai11** [shadowsocks/shadowsocks-rust#1371]
发现了一个影响使用体验的问题：单配置文件的使用方式不够灵活。每次使用优选IP的时候都得去进行繁琐的修改 "servers": [ ...........] 块内的数据而且像这些配置数据又更新的比较频繁，能不能用单独的配置文件来配置 "locals": [] 和 "servers": [ ...........] 块内的信息或者多配置文件导入，像现在所有的配置都在一个文件内配置数据一多查阅体验差和不够优雅灵活

**Comment by zonyitoo** [comment]
If many files works, then you can always merge them into one. Because there is always exactly one set of `locals` and `servers` in one `sslocal` process.

**Comment by yiguihai11** [comment]
> If many files works, then you can always merge them into one. Because there is always exactly one set of `locals` and `servers` in one `sslocal` process.

linux中并没有很好的工具操作json

**Comment by zonyitoo** [comment]
Python is a good choice.

**Comment by yiguihai11** [comment]
> Python is a good choice.

路由器装个py环境不合适吧

**Comment by zonyitoo** [comment]
Well, my OpenWRT was built with a Python, which actually solved my problem.
