### ISSUE TITLE
Latency, Throughput, and Scalibility

### ISSUE THREAD

**Issue by lonnietc** [shadowsocks/shadowsocks-rust#1398]
Hello,

I am working in a new Rust project that is related to ultra-high performance P2P networking and came across shadowsocks.

Was going to use Wireguard-rs but wanted to see if there was any type of information on the latency, throughput, and scalibity of shadowsocks as I also need to be able to quickly create/delete encrypted tunnels that can pass packets to computers that are behind a NAT.

Any thoughts?

Thanks

**Comment by zonyitoo** [comment]
There is nothing new in Rust,

1. Encryption operations are CPU bound, so you will have to make fully usage of enough CPU resources for processing packets.
2. Avoid memory copies.
3. Avoid locks.

Since this is not a technically issue of this project, I am going to close this issue.
