### ISSUE TITLE
UDP package failed to send back from the ssserver

### ISSUE THREAD

**Issue by jackli0127** [shadowsocks/shadowsocks-rust#1408]
<img width="1387" alt="image" src="https://github.com/shadowsocks/shadowsocks-rust/assets/102128343/b515efe5-178d-436d-8c81-4e9f62a2e03b">

shadowsocks-rust verison: v.1.17.1
OS version: Centos 9 Stream or Ubuntu 20.4

We upgraded our Shadowsocks from shadowsocks-libev 3.3.4 on CentOS 7 to shadowsocks-rust 1.17.1 on CentOS Stream 9 and Ubuntu 20.4, and then I found a large number of errors in the ssserver log as attached, which resulted in the loss of video during our users' Zoom meeting.

If I deploy shadowsocks-libev 3.3.5 on CentOS Stream 9 or Ubuntu 20.04, the same error messages are found. However, if I deploy shadowsocks-libev 3.3.4, both the log messages and our meeting video return to normal.

Any ideas on how to resolve the problem? Thanks!

**Comment by database64128** [comment]
It seems like an MTU misconfiguration somewhere in your network. You didn't discover the issue with shadowsocks-libev because it didn't bother with disabling IP fragmentation.

**Comment by jackli0127** [comment]
However, even when I configure a smaller MTU value on the network interface or in the ss-server parameters (shadowsocks-libev 3.3.5), I still encounter this error message.

The error only occurs when using the UDP protocol, and even UDP packets of 500 bytes fail to send

**Comment by zonyitoo** [comment]
`EMSGSIZE` should only occurs when packet size is greater than MTU. But interestingly that those ~500 bytes packets still fails.

The error was reported here:

https://github.com/shadowsocks/shadowsocks-rust/blob/1789dfad781966464fc7b4aef9ca470128f1526b/crates/shadowsocks-service/src/server/udprelay.rs#L791-L797

And you may also try to comment these lines and see if `EMSGSIZE` goes away:

https://github.com/shadowsocks/shadowsocks-rust/blob/1789dfad781966464fc7b4aef9ca470128f1526b/crates/shadowsocks/src/net/sys/unix/mod.rs#L55-L57
