### ISSUE TITLE
RST may occur on local TCP in TUN mode

### ISSUE THREAD

**Issue by Skyxim** [shadowsocks/shadowsocks-rust#1412]
Recently I was curious about the performance of smoltcp, and shadowsocks happened to use it, so I gave it a try. In the iperf3 parallel test, there is a high probability that the connection will fail.

Since this is sending, it is non-blocking, The data packet will quickly enter the virtual device and be used by Smoltcp
https://github.com/shadowsocks/shadowsocks-rust/blob/7f0779a81ed601a2827eb08040934ead97b79002/crates/shadowsocks-service/src/local/tun/tcp.rs#L133

If you happen to be currently running here
https://github.com/shadowsocks/shadowsocks-rust/blob/7f0779a81ed601a2827eb08040934ead97b79002/crates/shadowsocks-service/src/local/tun/tcp.rs#L312

An RST response will be generated in `Interface::poll` because there is no corresponding listening TCP

Maybe we can create a `oneshot` and wait in `TcpConnection::new` for the created Socket to be consumed. My try did solve the problem. But I'm not sure if this is the best way

**Comment by zonyitoo** [comment]
Hmm, you are right. Please help to make a PR.
