### ISSUE TITLE
`forward_addr` is specified but Shadowsocks says it is not

### ISSUE THREAD

**Issue by jpmvferreira** [shadowsocks/shadowsocks-rust#1420]
Hi there, maybe I'm missing something very obvious, but trying to create a tunnel in Shadowsocks with a config that looks like
```
{
  "protocol": "tunnel",
  "forward_address": "192.168.1.69",
  "forward_port": "8096",
  "server": "XXX",
  "server_port": 443,
  "password": "YYY",
  "method": "chacha20-ietf-poly1305",
  "local_address": "127.0.0.1",
  "local_port": 1080
}
```
Returns an error from Shadowsocks saying that `forward_addr` was not specified
```console
$ sslocal -v -c tunnel.json 
2024-01-23T22:38:15.701511748+00:00 DEBUG [114632:139918889978624] [shadowsocks_rust::sys] rlimit NOFILE adjusted rlimit { rlim_cur: 524288, rlim_max: 524288 }
config integrity check failed, missing `forward_addr` in configuration
```
Clearly, the value for `forward_address` is present in the config file, and replacing it with `forward_addr` doesn't work either.

What is curious is that running this directly in the command line, bypassing the config file, I get no errors
```console
$ sslocal --protocol tunnel -f 192.168.1.69:8096 -s XXX:443 -m chacha20-ietf-poly1305 -k YYY -b 127.0.0.1:1080
2024-01-23T22:39:59.825112454+00:00 INFO  shadowsocks local 1.17.1 build 2023-11-26T16:00:22.060213964+00:00
2024-01-23T22:39:59.830397305+00:00 INFO  shadowsocks TCP tunnel listening on 127.0.0.1:1080
```

System information:
- Installation Source: AUR (shadowsocks-rust-bin)
- Version: 1.17.1-1
- OS: Manjaro
- Kernel: 5.10.206
- System is up to date with the AUR and the official repositories

This error also takes place in another machine, this one running Arch, with Shadowsocks rust from the official repositories, which the exact same version.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust#configuration

It is only supported in extended `locals`.
