### ISSUE TITLE
Build from source failure (on VPS)

### ISSUE THREAD

**Issue by LindaFerum** [shadowsocks/shadowsocks-rust#1429]
Hello! 
Basically, build from source fails on a VPS where I really really want custom-built Shadowsocks server with stream ciphers re-enabled 

Error looks like

 warning: build failed, waiting for other jobs to finish...
 error: could not compile `shadowsocks-rust` (bin "ssserver")
 
 Caused by:
  process didn't exit successfully: `/home/admin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name ssserver --edition=2021 bin/ssserver.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=211 --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 --cfg 'feature="aead-cipher-2022"' --cfg 'feature="default"' --cfg 'feature="hickory-dns"' --cfg 'feature="ipnet"' --cfg 'feature="local"' --cfg 'feature="local-http"' --cfg 'feature="local-socks4"' --cfg 'feature="local-tun"' --cfg 'feature="local-tunnel"' --cfg 'feature="log4rs"' --cfg 'feature="logging"' --cfg 'feature="manager"' --cfg 'feature="multi-threaded"' --cfg 'feature="qrcode"' --cfg 'feature="server"' --cfg 'feature="service"' --cfg 'feature="stream-cipher"' --cfg 'feature="utility"' -C metadata=cd869cbe8147ab0d -C extra-filename=-cd869cbe8147ab0d --out-dir /home/admin/shadowsocks-rust/target/release/deps -C strip=symbols -L dependency=/home/admin/shadowsocks-rust/target/release/deps --extern base64=/home/admin/shadowsocks-rust/target/release/deps/libbase64-a49ee0088ca890e7.rlib --extern build_time=/home/admin/shadowsocks-rust/target/release/deps/libbuild_time-b076a7adefcaf042.so --extern cfg_if=/home/admin/shadowsocks-rust/target/release/deps/libcfg_if-0493d2d4edee34f5.rlib --extern clap=/home/admin/shadowsocks-rust/target/release/deps/libclap-8545dd6ca727f401.rlib --extern daemonize=/home/admin/shadowsocks-rust/target/release/deps/libdaemonize-405b5cdc91b8d8a8.rlib --extern directories=/home/admin/shadowsocks-rust/target/release/deps/libdirectories-e1bc318f31deb61a.rlib --extern futures=/home/admin/shadowsocks-rust/target/release/deps/libfutures-bb1b5a6cb704ac43.rlib --extern ipnet=/home/admin/shadowsocks-rust/target/release/deps/libipnet-8cee8b02ccfacaa0.rlib --extern json5=/home/admin/shadowsocks-rust/target/release/deps/libjson5-b24f4d909068757f.rlib --extern libc=/home/admin/shadowsocks-rust/target/release/deps/liblibc-2e90f703c2ef3dcb.rlib --extern log=/home/admin/shadowsocks-rust/target/release/deps/liblog-31b88aef43c6829e.rlib --extern log4rs=/home/admin/shadowsocks-rust/target/release/deps/liblog4rs-500d6ebb91af5407.rlib --extern num_cpus=/home/admin/shadowsocks-rust/target/release/deps/libnum_cpus-c8a61fa39bc8da7a.rlib --extern qrcode=/home/admin/shadowsocks-rust/target/release/deps/libqrcode-32d8c2eabbbe85f5.rlib --extern rand=/home/admin/shadowsocks-rust/target/release/deps/librand-62f10768261783f8.rlib --extern rpassword=/home/admin/shadowsocks-rust/target/release/deps/librpassword-cac9e9e1c052aba7.rlib --extern serde=/home/admin/shadowsocks-rust/target/release/deps/libserde-0e77ffcc123272c3.rlib --extern shadowsocks_rust=/home/admin/shadowsocks-rust/target/release/deps/libshadowsocks_rust-231742f5227305f4.rlib --extern shadowsocks_service=/home/admin/shadowsocks-rust/target/release/deps/libshadowsocks_service-df20ae1bedf30383.rlib --extern sysexits=/home/admin/shadowsocks-rust/target/release/deps/libsysexits-e6cf178ee82b22a9.rlib --extern thiserror=/home/admin/shadowsocks-rust/target/release/deps/libthiserror-efa58b657c2dac0f.rlib --extern tokio=/home/admin/shadowsocks-rust/target/release/deps/libtokio-63dfd5823325508d.rlib --extern xdg=/home/admin/shadowsocks-rust/target/release/deps/libxdg-b08ed9bc0ee8f30a.rlib -C target-cpu=native -L native=/home/admin/shadowsocks-rust/target/release/build/blake3-06cbd5c28e6f9991/out -L native=/home/admin/shadowsocks-rust/target/release/build/blake3-06cbd5c28e6f9991/out -L native=/home/admin/shadowsocks-rust/target/release/build/ring-9c71dac61a2a2b5e/out` (signal: 9, SIGKILL: kill)

**Comment by dev4u** [comment]
请先确认你的vps运行在2GB或以上。

**Comment by LindaFerum** [comment]
increased to 6 GB Ram, problem persists.

 Also, cross-compiling to VPS's detected architecture (skylake-avx512) on my baremetal 32 GB ram machine results in a bunch of failures (failed to run custom build command for `ring v0.17.7`)

Currently partially solved the problem by cross-compiling with export RUSTFLAGS="-C target-cpu=x86-64" on bare metal machine, then pushing result to VPS. Seems to build okay and work so far (albeit I guess not quite so fast as it could be lol)

**Comment by zonyitoo** [comment]
If the error was always `(signal: 9, SIGKILL: kill)`, then there was most likely that the build process was killed by OOM.

> (failed to run custom build command for ring v0.17.7)

Well, you should double check the error log about what exactly the error reported from the compiler.

**Comment by devdotnetorg** [comment]
@LindaFerum you can build executables using buildx and Dockerfile, it's very simple. The file is based on https://github.com/shadowsocks/shadowsocks-rust/blob/master/Dockerfile. For example, I compiled **sswinservice** in Ubuntu Ubuntu 22.04.2 LTS, 2 Gb RAM, in cross-compilation mode. Assembly process, post (Russian language) [Cross-compilation of a project in Docker using Buildx using the example of building shadowsocks-rust and the Libgpiod library](https://devdotnet.org/post/cross-compilation-project-v-docker-ispolzuya-buildx-na-primere-shadowsocks-rust-i-libgpiod/).
This is how I build sswinservice.exe, file [Dockerfile.alpine.sswinservice](https://github.com/devdotnetorg/shadowsocks-rust/blob/master/Dockerfile.alpine.sswinservice), builder [buildx-out.sh](https://github.com/devdotnetorg/shadowsocks-rust/blob/master/buildx-out.sh).
```bash
SS_VER=1.18.0
sudo apt-get update
sudo apt-get install -y curl unzip
curl -SL --output shadowsocks-rust.zip https://github.com/shadowsocks/shadowsocks-rust/archive/refs/tags/v${SS_VER}.zip
unzip shadowsocks-rust.zip
cd shadowsocks-rust-${SS_VER}
curl -SL --output Dockerfile.alpine.sswinservice https://raw.githubusercontent.com/devdotnetorg/shadowsocks-rust/master/Dockerfile.alpine.sswinservice
curl -SL --output buildx-out.sh https://raw.githubusercontent.com/devdotnetorg/shadowsocks-rust/master/buildx-out.sh
chmod +x buildx-out.sh
./buildx-out.sh
```

**Comment by zonyitoo** [comment]
For cross compiling, you can try [cross](https://github.com/cross-rs/cross).
