### ISSUE TITLE
Questions about plugins, auto-switching and DNS.

### ISSUE THREAD

**Issue by paolosezart** [shadowsocks/shadowsocks-rust#1430]
I am using the shadowsocks-rust client on my Raspberry pi4 with the Raspbian Bookworm operating system. I tested a few proxy programs, for this OS and shadowsocks-rust turned out to be the most convenient, stable and resource-free. I'm running shadowsocks-rust in local proxy mode, because it's not a good idea to let all traffic through a proxy.

I studied the documentation, but could not find information about which plugins are already built into the program, and which ones need to be downloaded separately. In particular, does shadowsocks-rust have the ability to connect to servers with "hysteria", "vmess", "vless", "trojan". And what is the syntax for writing a configuration file to connect these protocols? Please write detailed examples of writing configuration files with different protocols.

The second question is about auto-switching. As it is written in the help, the shadowsocks-rust client tests all connections at startup and selects the fastest one. And what happens if the remote server shuts down, will shadowsocks-rust switch to another server registered in config.json?

And the third question is, how do I configure shadowsocks-rust to listen to local UDP port 53, to proxy DNS queries?
Thank you so much for your project!

**Comment by zonyitoo** [comment]
> I studied the documentation, but could not find information about which plugins are already built into the program, and which ones need to be downloaded separately.

"Plugin" is a standard protocol, which was defined in [SIP003](https://github.com/shadowsocks/shadowsocks-org/issues/28) and [SIP003u](https://github.com/shadowsocks/shadowsocks-org/issues/180). So there is no "builtin" plugin in this project.

> In particular, does shadowsocks-rust have the ability to connect to servers with "hysteria", "vmess", "vless", "trojan".

No. This is a Project in the "shadowsocks" organization.

While you are talking about Plugin, you may build a shadowsocks Plugin with any other existed program, for example, [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin).

> And what happens if the remote server shuts down, will shadowsocks-rust switch to another server registered in config.json?

Yes, it will switch to the server that have the highest "score". If a server was down, it won't get high enough "score", in most cases.

> how do I configure shadowsocks-rust to listen to local UDP port 53, to proxy DNS queries?

You may try to start a "tunnel" local instance, which listen to port 53 and forward all the queries to a specific destination set by "forward_addr".
