### ISSUE TITLE
How to configure sslocal-tun?

### ISSUE THREAD

**Issue by pronebird** [shadowsocks/shadowsocks-rust#1432]
Hi,

I have been playing around tun support on macOS today. I can't really make it work and I'd appreciate some pointers.

In my simple test I figured that I'd create a configuration where I take all traffic from utun and then forward it into local SS server, so for the server setup it's easy:

```
ssserver --encrypt-method none --server-addr "127.0.0.1:8388" --password ""
```

Then sslocal with utun is configured as such:

```
sudo sslocal --server-addr "127.0.0.1:8388" \
    --password "" \
    --encrypt-method "none" \
    --protocol tun \
    --tun-interface-address "10.0.0.1/24"
```

Somehow I had impression that it should just work out of box without changing a routing table (which could be a dead wrong assumption), but curl can't really send anything over utun:

```
curl --interface utun4 https://1.1.1.1
```

I'd appreciate some pointer if you have any idea what's going on there.

**Comment by hainesc** [comment]
@pronebird AFAIK, the current implementation is `just a tun device`, when you run the command, you get a virtual device `utun4`, and any packets send to the device go shadowsocks server as the command configs.

For further, 
1. making the device as the default route table
2. handling routing loop

are not implemented. 

I think it is a good suggestion to make the tun device working as default route. maybe we can add some option, such as
sslocal --protocol tun **--default-route true**

**Comment by zonyitoo** [comment]
> I think it is a good suggestion to make the tun device working as default route. maybe we can add some option, such as
sslocal --protocol tun --default-route true

Actually it was implemented in older releases, but some experts wanted them to be removed since it would messup their own route tables.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/65eb758ad426250f358a647ec99baab8fea722d8/crates/shadowsocks-service/src/local/tun/sys/unix/apple/macos.rs#L60-L177

This is how to set default route table for the tun device on macOS, if anyone interested.

**Comment by zonyitoo** [comment]
> Somehow I had impression that it should just work out of box without changing a routing table (which could be a dead wrong assumption), but curl can't really send anything over utun:
>
> ```
> curl --interface utun4 https://1.1.1.1
> ```
>
> I'd appreciate some pointer if you have any idea what's going on there.

Well yes, because on macOS, you have to set the route table, otherwise `--interface utun4` won't work.

**Comment by hainesc** [comment]
@zonyitoo Wow, perfect information, thanks. 
I 'd like make a proposal to bring it back, we can add a flag to decide whether make a default route.

**Comment by zonyitoo** [comment]
But actually it was quite easy to use the `route` command to set the default route. All these settings could be done in shell.

**Comment by hainesc** [comment]
> But actually it was quite easy to use the `route` command to set the default route. All these settings could be done in shell.

I don't think it is that easy.
1. What about route looping? I mean, if you set the utun device as the default route, as you curl 
`curl --interface utun4 https://1.1.1.1`, packets go to the utun device, and encrypted by shadowsocks client, and then go shadowsosks server, so the server's IP address should have a route record, to let packets go to physical device, not route to default, here is utun again.
2. How to handle the direct visit? If I visit some website that I don't like to be proxy by shadowsocks server, eg, the server in the local network which can be reach by gateway of the default physical device, the utun device should have the ability to work with the PAC config.

**Comment by zonyitoo** [comment]
The PAC you mentioned could be replaced by ACL config, which could work mostly the same.

Back to the original problem, could `—outbound-bind-interface` works in this case? Emm.. maybe not. Things get quite easier on Linux.

**Comment by zonyitoo** [comment]
I changed my mind, since Linux adds default route by default, macOS could also follow this default behavior.
