### ISSUE TITLE
Invalid error logging when using `local-tun` on Windows

### ISSUE THREAD

**Issue by Sricor** [shadowsocks/shadowsocks-rust#1469]
I've encountered a problem with local-tun on Windows where I receive an invalid error log message. 

![Screenshot (1)](https://github.com/shadowsocks/shadowsocks-rust/assets/78024433/2434f156-e213-4e47-8cbc-90ac490b63c6)
`ERROR WinTun: Failed to find matching adapter name: Element not found. (Code 0x00000490)`

The problem seems to appear on the following line of code:
https://github.com/meh/rust-tun/blob/e762c419d71438e67379f9b2fed89b5cb835cc6a/src/platform/windows/device.rs#L41

It seems to be an invalid error message? Could be improved to provide more clarity on what is causing the issue or to confirm that the current behavior is expected under certain conditions.

**Comment by zonyitoo** [comment]
It was reported from the `wintun` library. I think this line of error could be ignored, because as you can see in `windows/device.rs`, it was trying to `open` a WinTun with a provided `tun_name` as adapter name, if it fails, create a new adapter.
