### ISSUE TITLE
Compile to WATER?

### ISSUE THREAD

**Issue by myleshorton** [shadowsocks/shadowsocks-rust#1486]
Would be very cool if this could be made compatible with WATER -- https://github.com/refraction-networking/water

**Comment by zonyitoo** [comment]
What we need to do for making this project compatible with “water”?

**Comment by zonyitoo** [comment]
https://github.com/refraction-networking/water-rs/tree/main/examples/water_bins/ss_client_wasm_v1/src

It seems that they have already made a simple version of ss clients.
