### ISSUE TITLE
Not possible to specify connection timeout as argument to `sslocal`

### ISSUE THREAD

**Issue by mvd-ows** [shadowsocks/shadowsocks-rust#149]
As above.

I believe the timeout defaults to 300 seconds.

**Comment by zonyitoo** [comment]
Should it be the same as `timeout` ?

**Comment by mvd-ows** [comment]
I suppose that's the timeout, yes, but I will admit that I'm a little confused. There seems to be different timeouts used throughout the code and there's only ever one timeout value being specified as input.

However, the reason I opened this issue is because it's possible to specify a timeout if you're using a config file. But there is no way to put the timeout directly as an argument to `sslocal`.

**Comment by zonyitoo** [comment]
Hmm, yes. Because the original version of `sslocal` in `shadowsocks` doesn't have that command line argument.

**Comment by mvd-ows** [comment]
I see. Yes, we've stumbled upon a few limitations in `shadowsocks-libev` before. This isn't a huge deal but it seems somewhat asymmetrical.

**Comment by zonyitoo** [comment]
Yes, I was confused, too. Not all configurations can be overwritten by command line arguments.

**Comment by zonyitoo** [comment]
Sorry for supporting this after a year. :(
