### ISSUE TITLE
question: ERROR udp relay {local} -> {remote} with {length} bytes, error: Message too large (os error 90)  

### ISSUE THREAD

**Issue by liudongmiao** [shadowsocks/shadowsocks-rust#1494]
https://github.com/shadowsocks/shadowsocks-rust/blob/dcdeca032cad409d1ad133abeafa0270bb32a945/crates/shadowsocks-service/src/server/udprelay.rs#L654-L662

Could anyone tell me the meaning and how to avoid? Is it related with mtu?

client: shadowsocks-libev ss-redir 3.3.5 with udprelay patch from master
server: shadowsocks-rust ssserver 1.18.2

|size|count|
|----|------|
|1396|8|
|1412|17|
|1428|15|
|1444|10|
|1460|15|
|1476|344|
|1492|287|
|1508|292|
|1524|291|
|1540|52|

**Comment by zonyitoo** [comment]
The encrypted packet was larger than your MTU, so UDP socket's `sendmsg` rejected with `EMSGSIZE`.

**Comment by liudongmiao** [comment]
Thanks. After check, it's sent by an app to detect MTU.
