### ISSUE TITLE
feature request: specify plugin-mode in command line

### ISSUE THREAD

**Issue by liudongmiao** [shadowsocks/shadowsocks-rust#1495]
For `mode`, there is `-U` for `TCP_AND_UDP`. (The meaning of `-u` / `-U` is different with shadowsocks-libev.)

For `plugin-mode`, it seems there is no such option.

Two options:
1. a new argument like `-P` or so.
2. if `-U` is specified, change plugin-mode to `TCP_AND_UDP`.

**Comment by zonyitoo** [comment]
There are `--plugin`, `--plugin-opts` options. So there should be a `--plugin-mode` for consistency.

**Comment by liudongmiao** [comment]
Thanks. Use `--plugin-mode` would be better.
