### ISSUE TITLE
feature request: specify launchd_tcp_socket_name / launchd_udp_socket_name in outer config

### ISSUE THREAD

**Issue by liudongmiao** [shadowsocks/shadowsocks-rust#1498]
work: 
```jsonc
{
  "locals": [
    {
      "launchd_tcp_socket_name": "TCPListener",
      "launchd_udp_socket_name": "UDPListener",
      "local_address": "127.0.0.1",
      "local_port": 1080
    }
  ],
  "method": "xxx",
  "mode": "tcp_and_udp",
  // other option
}
```

don't work:
```jsonc
{
  "launchd_tcp_socket_name": "TCPListener",
  "launchd_udp_socket_name": "UDPListener",
  "local_address": "127.0.0.1",
  "local_port": 1080,
  "method": "xxx",
  "mode": "tcp_and_udp",
  // other option
}
```

expect `launchd_tcp_socket_name` / `launchd_udp_socket_name` can work in outer, like `locals[0]`.

and, could `launchd_tcp_socket_name` / `launchd_udp_socket_name` be an option in command line?

**Comment by zonyitoo** [comment]
You could add a PR for this. Actually I don’t recommend to add too many extended fields in the “basic format”, which is used frequently in cross-implementation configuration.
