### ISSUE TITLE
Cannot use TUN protocol on Windows 10

### ISSUE THREAD

**Issue by bryanc12** [shadowsocks/shadowsocks-rust#1501]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/34401335/0f873f8b-8391-4460-adcf-16d34ec1ec55)

Not sure why, the error is showing TUN is not a valid protocol. I'm using the version "v1.18.2". I have downloaded the wintun.dll.

Trying with the command .\sslocal.exe --protocol tun

**Comment by zonyitoo** [comment]
`tun` is not enabled for Windows in default build, you could build it from source by enabling `--features local-tun`.
