### ISSUE TITLE
does the cargo package lack some options and commands?

### ISSUE THREAD

**Issue by zaknenou** [shadowsocks/shadowsocks-rust#1519]
Thanks for this implementation, it is great that yet another optimization was possible
  
  I installed shadowsocks-rust using `cargo install shadowsocks-rust`. The commands that were added to my terminal are: `sslocal`, `ssmanager`, `ssserver`, `ssservice`, `ssurl`. But I notice a command `ssredir` was mentioned once on the README, yet not included in my installation. Additionally, when I try to pass either of the options: `--protocol redir` or `--protocol tun` I get the errors respectively:
```
error: invalid value 'redir' for '--protocol <PROTOCOL>'
  [possible values: socks, http, tunnel]

For more information, try '--help'.
```
or 
```
error: invalid value 'tun' for '--protocol <PROTOCOL>'
  [possible values: socks, http, tunnel]

  tip: a similar value exists: 'tunnel'

For more information, try '--help'.
```
  Is it because I installed from Cargo instead of compiling from source ? Also `--tcp-redir` and `--udp-redir` are absent from my --help.

**Comment by AaronChen0** [comment]
1. ssredir was merged into sslocal.
2. To enable redir and tun protocal, you should add them as features during install. Try this:
```
cargo install shadowsocks-rust --features "local-redir,local-tun"
```

**Comment by zonyitoo** [comment]
Yes, `redir` must be enabled by `local-redir`, and `tun` must be enabled by `local-tun`.

**Comment by zaknenou** [comment]
> 1. ssredir was merged into sslocal.
> 
>     2. To enable redir and tun protocal, you should add them as features during install. Try this:
> 
> 
> ```
> cargo install shadowsocks-rust --features "local-redir,local-tun"
> ```

Thank you, TIL about the --features flag for cargo install
