### ISSUE TITLE
Better server management strategy in sslocal

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#152]
As asked in #151 , currently our load balancing algorithm is simply Round Robin, which is good if all your servers have good qualities, otherwise, when any of your servers down, `sslocal` will still try to connect that broken server.

So I think we need a better server choosing algorithm.

One simple strategy came out of my mind is:

- Ping servers periodically, record their delay
- Choose the server that has the lowest delay

Strictly this is not a Load Balancing algorithm anymore. But .. it is always the best to use the fastest server.

**Comment by zonyitoo** [comment]
@raintean I have implemented a simple version in the master branch, please test it, if you are interested.

**Comment by raintean** [comment]
ok, thanks for what you do. When I'm free, I'll try this new feature!
感谢你, 我有空试试...

**Comment by e2ge** [comment]
我有个建议，在nginx的lb里面有个策略叫做least_time，是属于收费版里面的功能，具体如何实现我也不太清楚，具体可以指定first_byte或者last_byte的时间。我觉得这样的策略可能是最有意义的，简单的ping还是有点简陋了，特别对于中间有relay服务器来说只代表relay服务器的延迟，对整个连接和传输意义不是很大。
http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html#least_time

**Comment by e2ge** [comment]
还有就是在ss-c#客户端上是有几个策略的，里面有个high availability和by statistic，by statistic据说已经放弃了。高可用策略应该是基于一个打分策略。
https://github.com/shadowsocks/shadowsocks-windows/issues/1792

**Comment by zonyitoo** [comment]
嗯，可以参考一下。目前基于Ping平均耗时波动非常大
