### ISSUE TITLE
Here are some feature suggestions for Shadowsocks-Rust.

### ISSUE THREAD

**Issue by maojianyou** [shadowsocks/shadowsocks-rust#1522]
1、Can Shadowsocks-Rust support MPQUIC?
2、Can the --protocol tun interface be made persistent? Currently, when the client sslocal is closed, the tun interface automatically exits.
3、The transparent proxy mode TPROXY with --on-port 6000 --on-ip 0.0.0.0 --tproxy-mark 1 seems to not work well. Can it be optimized to simplify deployment, with a more user-friendly tunnel interface?
4、Can the NAT address of the ssserver be changed? I noticed that when the client sslocal reaches the server through the tun tunnel, it automatically NATs to the gateway IP. Is it possible to customize and modify this?
5、sslocal ------> ssserver currently only supports one-way communication. Can it support bi-directional communication?

**Comment by zonyitoo** [comment]
> Can Shadowsocks-Rust support MPQUIC?

What do you mean "support"?

> Can the --protocol tun interface be made persistent? Currently, when the client sslocal is closed, the tun interface automatically exits.

The tun device on Linux could be created from command lines. You can create one and let `sslocal` binds to it. (not sure, but you can give a try).

> The transparent proxy mode TPROXY with --on-port 6000 --on-ip 0.0.0.0 --tproxy-mark 1 seems to not work well. Can it be optimized to simplify deployment, with a more user-friendly tunnel interface?

What do you mean "more user-friendly"?

> Can the NAT address of the ssserver be changed? I noticed that when the client sslocal reaches the server through the tun tunnel, it automatically NATs to the gateway IP. Is it possible to customize and modify this?

Not sure what you are talking about.

> sslocal ------> ssserver currently only supports one-way communication. Can it support bi-directional communication?

Why would a connection starts from `ssserver` then connects to `local`? This is a client-server architecture, so it won't be possible.

**Comment by maojianyou** [comment]
> > Can Shadowsocks-Rust support MPQUIC?
> 
> What do you mean "support"?
> Does your software have this feature, can it support MPQUIC? Similar to how you support MPTCP, MPQUIC supports multi-path over UDP.
>
> > Can the --protocol tun interface be made persistent? Currently, when the client sslocal is closed, the tun interface automatically exits.
> 
> The tun device on Linux could be created from command lines. You can create one and let `sslocal` binds to it. (not sure, but you can give a try).

> So you mean using system commands such as ip tuntap and others, right? Normally, it makes more sense for your program to directly invoke ip without integrating it into the software.


> > The transparent proxy mode TPROXY with --on-port 6000 --on-ip 0.0.0.0 --tproxy-mark 1 seems to not work well. Can it be optimized to simplify deployment, with a more user-friendly tunnel interface?
> 
> What do you mean "more user-friendly"?
>The configuration is too complex, and the tests have never been successful. 

> > Can the NAT address of the ssserver be changed? I noticed that when the client sslocal reaches the server through the tun tunnel, it automatically NATs to the gateway IP. Is it possible to customize and modify this?
> 
> Not sure what you are talking about.
> For instance, in the case of ssserver when there are multiple public IPs, does it default to only NAT to the public address that sslocal actively connects to for NAT?

> > sslocal ------> ssserver currently only supports one-way communication. Can it support bi-directional communication?
> 
> Why would a connection starts from `ssserver` then connects to `local`? This is a client-server architecture, so it won't be possible.
Since I've seen that VPN can achieve bidirectional communication, I'll leave this issue aside.
