### ISSUE TITLE
How to set up multiple SIP002 URLs for sslocal

### ISSUE THREAD

**Issue by gocpicnic** [shadowsocks/shadowsocks-rust#1527]
Set one SIP002 URL,the example for help doc like this:

sslocal -b "127.0.0.1:1080" --server-url "ss://YWVzLTI1Ni1nY206cGFzc3dvcmQ@127.0.0.1:8388/?plugin=v2ray-plugin%3Bserver%3Btls%3Bhost%3Dgithub.com"

Now I have many SIP002 URLs,how to set up?

**Comment by zonyitoo** [comment]
It only supports one server instance from command line. You could parse SIP002 URLs into a configuration file.
