### ISSUE TITLE
v2ray-plugin No such file or directory even abs path

### ISSUE THREAD

**Issue by hxzhao527** [shadowsocks/shadowsocks-rust#1531]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/8402502/bf6184ee-3529-4331-8dda-49de74535ea1)

# infos
- version: shadowsocks 1.18.4
- how install: installed by snap

**Comment by zonyitoo** [comment]
Application running in `snap` is wrapped in a separated environment. So the path `/usr` is not the one you are expected.

**Comment by hxzhao527** [comment]
Got it. Thanks.

**Comment by zonyitoo** [comment]
If you are interested, you may try to add a "system-files" interface to it and see if it could allow `sslocal` in `snap` reads `/usr/bin`.

**Comment by zonyitoo** [comment]
BTW, these snap apps can access to your "home" directory, consider put them into your "home".

**Comment by zonyitoo** [comment]
https://askubuntu.com/a/1139166/100031

Here is another possible solution.
