### ISSUE TITLE
Error 101

### ISSUE THREAD

**Issue by egasvegas1109** [shadowsocks/shadowsocks-rust#1536]
Hello, I deployed shadowsocks-rust on a VPS and use the address 0.0.0.0 in the server config to interact only with IPv4, but for some reason it wants to connect to IPv6 and gives an error.
The VPS does not have an IPv6 address, only IPv4. 
I don't use docker
 ERROR tcp tunnel "my ip" -> ipv6.2ip.io:443 connect failed, error: Network is unreachable (os error 101)

{
    "server": "0.0.0.0",
    "server_port": 8388,
    "password": "kfsjJ2Jqofias@Flf",
    "timeout": 300,
    "method": "chacha20-ietf-poly1305"
}

**Comment by zonyitoo** [comment]
Your client wanted to connect "ipv6.2ip.io:443", so `ssserver` made connection to that address, which only have AAAA records.
