### ISSUE TITLE
Using multiple servers and traffic control

### ISSUE THREAD

**Issue by egasvegas1109** [shadowsocks/shadowsocks-rust#1538]
Hello, I want to generate unique keys (ss) for different users and control the traffic of these keys. Therefore, do I need to use multiple servers (one server = one user)? 
```json
    "server": "::",
    "server_port": 8388,
    "method": "aes-256-gcm",
    "password": "your-password1",
    "timeout": 7200,
    "servers": [
        {
            "address": "0.0.0.0",
            "port": 8389,
            "method": "aes-256-gcm",
            "password": "your-password2",
            "timeout": 7200,
        },
        {
            "address": "0.0.0.0",
            "port": 8390,
            "method": "aes-256-gcm",
            "password": "your-password3",
            "timeout": 7200,
        }
    ]
```
If so, is it OK to use a separate server for each user, let's say if there are 100 such users? Wouldn't this increase the load on the server many times if I used one server instead of 100? And how can traffic be controlled, for example, the number of connected devices to a particular server? I understand that you can use "AEAD" to generate different keys, but this approach does not suit me due to the fact that the user can find out "iPSK", therefore it makes no sense to use the user's password. And most importantly, "AEAD" does not allow you to control traffic (for example, the number of connected devices), and this is the most important thing in my task. Can I use Nginx to limit the number of connections?

**Comment by egasvegas1109** [comment]
> For your case, you may try AEAD-2022's EIH (Extendsible Identity Header).

AEAD-2022 does not suit me, is it possible to use some solution to send a combination of "port+ password" to open a new server from Python code? Something like: https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users but as I understand it, this is not supported in ss-rust?

**Comment by egasvegas1109** [comment]
I thought it would be possible to use ssmanager to create multiple servers, but it does not know how to create servers from different configs. I don't want to store one big config with multiple servers.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users

This is supported by `ssmanager`.

**Comment by egasvegas1109** [comment]
Hello again, please excuse me for writing here again. Is it possible, using "a", to send not only the port and password, but also the IP? The fact is that I have ssmanager on one VPS, which serves to control traffic and other work, and I want to add other VPS to this ssmanager. They have different IP addresses, will it work out that way? Or does ssmanager manage servers only those that are on the same VPS?

**Comment by zonyitoo** [comment]
Each ssmanager controls its own set of ssservers. They should be on the same machine. But technically you can implement a ssmanager that can manage ssserver instances across multiple machines. In that case, you can use whatever protocol you want, not only the one that was defined in Manage-Multiple-User.
