### ISSUE TITLE
Fake DNS Configuration 

### ISSUE THREAD

**Issue by wyzdot** [shadowsocks/shadowsocks-rust#1539]
Hi @zonyitoo  thank you for implementing Fake DNS, great job! Could you please  provide us with some examples of configurations and rules? I've read some of the source code, and honestly, I have no clue about it.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust#configuration

Read the doc. And it is unstable, please use it and see if there are any problems.

**Comment by wyzdot** [comment]
> https://github.com/shadowsocks/shadowsocks-rust#configuration
> 
> Read the doc. And it is unstable, please use it and see if there are any problems.

Thanks.  As of now, it seems that we cannot use Fake DNS as an upstream server for other servers due to compatibility issues. Is it designed to be this way, or is there another reason? I'm not sure if my use case is correct, but when we use Fake DNS as an upstream, the downstream cannot correctly process the response data from Fake DNS.

**Comment by zonyitoo** [comment]
Well, clients are now get your "fake" IPs from the FakeDNS, and then they try to connect to those "fake" IPs. You will have to ensure those connections that are destinated to those IPs could be redirected to sslocal.

For example:

```bash
# First of all, send a DNS request to FakeDNS
$ dig www.twitter.com @127.0.0.1 -p 10053
   # Got a fake IP "1.2.3.4"

# Let the client sends request to 1.2.3.4, like this
$ curl "https://www.twitter.com" --resolve "www.twitter.com:443:1.2.3.4" --socks5 "127.0.0.1:1080"
```

If your `curl` compiled with `c-ares`, you may also specify the FakeDNS with `--dns-server`.

**Comment by wyzdot** [comment]
The dig query works very well, but if you use some dnsproxy tools and forward the query to  Fake DNS, it seems that they 
 cannot understand the response message from Fake DNS. I tried several different ones to forward the query, and none of them worked properly. 

Did some research:

normal local dns response:
```
ANSWER Message { header: Header { id: 14606, message_type: Response, op_code: Query, authoritative: false, truncation: false, recursion_desired: true, recursion_available: true, authentic_data: false, checking_disabled: false, response_code: NoError, query_count: 1, answer_count: 1, name_server_count: 0, additional_count: 0 }, queries: [Query { name: Name("g.cn."), query_type: A, query_class: IN }], answers: [Record { name_labels: Name("g.cn."), rr_type: A, dns_class: IN, ttl: 300, rdata: Some(A(A(142.251.2.94))) }], name_servers: [], additionals: [], signature: [], edns: None }
```
Fake DNS response:
```
ANSWER Message { header: Header { id: 27648, message_type: Response, op_code: Query, authoritative: false, truncation: false, recursion_desired: false, recursion_available: false, authentic_data: false, checking_disabled: false, response_code: NoError, query_count: 0, answer_count: 0, name_server_count: 0, additional_count: 0 }, queries: [], answers: [Record { name_labels: Name("x.com."), rr_type: A, dns_class: IN, ttl: 10, rdata: Some(A(A(10.255.0.2))) }], name_servers: [], additionals: [], signature: [], edns: None }
```
It seems that the Queries section is not included in the response and wireshark also confirmed this. 
Anyway, I don't know if this is the real issue.

**Comment by zonyitoo** [comment]
Hmm interesting, I tried it with smartdns and it can process these response messages. I don’t know much about the RFC, does the Query must be included in the response message?

**Comment by wyzdot** [comment]
I am not a cs pro, just did some searching... The Queries section should not be necessary, at least that's what ChatGPT said. If you want to reproduce the problem, you can try use dnsmasq coredns or chinadns-ng to forwarding. I have tested these tools.

**Comment by zonyitoo** [comment]
I see a difference in your example:

Normal DNS response message has: `query_count: 1, answer_count: 1`, but FakeDNS response came with `query_count: 0, answer_count: 0`.

Let me make them right.

**Comment by zonyitoo** [comment]
I was wrong. The `Header` in log was not the final header that was going to be serialized into the packet. They are all correct.

I have added the Query Section, please compile with the latest commit and see if it actually help:

```
; <<>> DiG 9.10.6 <<>> AAAA www.pinterest.com @127.0.0.1 -p 10053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61845
;; flags: qr; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.pinterest.com.		IN	AAAA

;; ANSWER SECTION:
www.pinterest.com.	60	IN	AAAA	fd00::

;; Query time: 0 msec
;; SERVER: 127.0.0.1#10053(127.0.0.1)
;; WHEN: Mon May 27 23:41:38 CST 2024
;; MSG SIZE  rcvd: 63
```

**Comment by wyzdot** [comment]
Fixed. cheers!
