### ISSUE TITLE
How can I get approved IP addresses?

### ISSUE THREAD

**Issue by egasvegas1109** [shadowsocks/shadowsocks-rust#1544]
How can I get the IP addresses of clients who have successfully connected to the ssserver? (who entered the password correctly)

**Comment by zonyitoo** [comment]
What do you mean "get"? From log? From code?

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/7de93f78d6a01a80e5a0bd98929161005abac1d9/crates/shadowsocks-service/src/server/tcprelay.rs#L71-L82

You can print the `peer_addr` after `accept`.

It should also works for UDP server:

https://github.com/shadowsocks/shadowsocks-rust/blob/7de93f78d6a01a80e5a0bd98929161005abac1d9/crates/shadowsocks-service/src/server/udprelay.rs#L257-L285

**Comment by egasvegas1109** [comment]
Thanks for the answer, but how can I modify the ssserver so that it displays a list of connected users using the command?

**Comment by zonyitoo** [comment]
You may try to use `-v`, `-vv`, `-vvv` first. If it doesn't fulfull your goal, add your own customized log in code.

**Comment by egasvegas1109** [comment]
I made the code, but it outputs all users, even those who have not connected, but simply send the "ping" command over the server IP:
`            let (local_stream, peer_addr) = match self
                .listener
                .accept_map(|s| MonProxyStream::from_stream(s, flow_stat))
                .await
            {
                Ok(s) => s,
                Err(err) => {
                    error!("tcp server accept failed with error: {}", err);
                    time::sleep(Duration::from_secs(1)).await;
                    continue;
                }
            };

            println!("Client connected: {}", peer_addr);
            
            if self.context.check_client_blocked(&peer_addr) {
                warn!("access denied from {} by ACL rules", peer_addr);
                continue;
            }`
And I would like to make sure that only those who have access to the server are displayed based on the password.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/94c097196e5586760a42f7ed722a70651ff07f9e/crates/shadowsocks-service/src/server/tcprelay.rs#L191-L195

This `trace` log is what you want, I suppose.
