### ISSUE TITLE
macOS 10.14.5 build failed

### ISSUE THREAD

**Issue by ulongx** [shadowsocks/shadowsocks-rust#155]
Compiling tokio-rustls v0.9.3
error: failed to run custom build command for `libsodium-ffi v0.1.17`
process didn't exit successfully: `/Users/ulongx/RustP/github/shadowsocks-rust/target/release/build/libsodium-ffi-276e9dde1bb41757/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rerun-if-env-changed=SODIUM_BUILD_STATIC

--- stderr
thread 'main' panicked at 'Missing libsodium library in your system, try to use SODIUM_BUILD_STATIC=yes to build it from source', /Users/ulongx/.cargo/registry/src/github.com-1ecc6299db9ec823/libsodium-ffi-0.1.17/build.rs:50:24
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by zonyitoo** [comment]
> Missing libsodium library in your system

Please install `libsodium`. (For example: `brew install libsodium`).

> try to use SODIUM_BUILD_STATIC=yes to build it from source

Or you can build it from source by `SODIUM_BUILD_STATIC=yes cargo build`.
