### ISSUE TITLE
Using the subdomain for the server

### ISSUE THREAD

**Issue by egasvegas1109** [shadowsocks/shadowsocks-rust#1551]
How can I make the shadowsocks rust server available by subdomain? My subdomain uses dns and Cloudflare proxy. I use the IP address in the server settings, because SSR does not start if you enter a subdomain instead of an ip. I tried to do forwarding in Nginx to the ip:port of the SSR server, but it also didn't work. I also installed SSL Cloudflare on the VPS.
I use the following Nginx configuration to proxy subdomain requests to the Flask web server, but I don't understand how to make the shadowsocks rust server accessible by subdomain.

```
server {
	listen 443 ssl http2;
	server_name subdomain.domain.com;

	ssl_certificate			/etc/ssl/origin_swifty.pem;
	ssl_certificate_key		/etc/ssl/private_swifty.pem;

	location /generate {
        	proxy_pass https://127.0.0.1:5000;
        	proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
    }

	location /get_traffic_info {
        	proxy_pass https://127.0.0.1:5000;
        	proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
    }

	location /deactivated_key {
        	proxy_pass https://127.0.0.1:5000;
        	proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```

**Comment by zonyitoo** [comment]
If your subdomain.domain.com couldn’t be resolved by your default DNS server, try to put it in `/etc/hosts`, then ssserver will be able to start.

**Comment by egasvegas1109** [comment]
> If your subdomain.domain.com couldn’t be resolved by your default DNS server, try to put it in `/etc/hosts`, then ssserver will be able to start.

Yes, thanks, SSR is now running on my subdomain. But it is still unavailable by subdomain. I found out that the reason is the enabled proxying via Cloudflare, as it hides the real IP address and therefore the server becomes unavailable. Is there any way to solve this problem without disabling proxying via Cloudflare?

**Comment by egasvegas1109** [comment]
I have another question: I use https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users and is it possible to run the server on a subdomain, and not on 0.0.0.0?

**Comment by egasvegas1109** [comment]
I searched the Internet and it seems that only disabling proxying on Cloudflare will help solve this problem, since IP addresses are being substituted during proxying and Nginx does not seem to be able to help with this.

**Comment by zonyitoo** [comment]
I am not familiar with Cloudflare proxy, unfortunately.
