### ISSUE TITLE
Does shadowsocks-rust support relay (i.e. chain proxy)?

### ISSUE THREAD

**Issue by zwl1619** [shadowsocks/shadowsocks-rust#1554]
Does shadowsocks-rust support relay (i.e. chain proxy)?

**Comment by zonyitoo** [comment]
What has to be done for supporting "relay"?

**Comment by zwl1619** [comment]
Hi @zonyitoo, I'm not sure how to express it. 
What I want to do is:
I created a client and a server with shadowsocks, it works successfully. 
Now I have another socks5 ip proxy, it has name&password&ip address&port.
I want to connect the shadowsocks server to the socks5 ip proxy, then access Internet from the socks5 ip proxy, instead of  from the shadowsocks server.
What should I do?

**Comment by zonyitoo** [comment]
So you have 2 socks5 proxy in the middle:

```
sslocal -> socks5proxy -> ssserver -> socks5proxy -> target
```

Consider do it via tools like: https://github.com/rofl0r/proxychains-ng .

**Comment by zwl1619** [comment]
@zonyitoo only one socks5 proxy, like this:
```
sslocal -> ssserver -> socks5proxy -> target
```

**Comment by zonyitoo** [comment]
It should work by applying proxychains-ng on `ssserver`.

**Comment by zwl1619** [comment]
OK, thanks a lot.
