### ISSUE TITLE
Error:Android:Build Failed

### ISSUE THREAD

**Issue by CyberJet-Project** [shadowsocks/shadowsocks-rust#1557]
Hi, Dev
Android build failed.
Commit 94115393df628c8ef9adc319474bec469e9afe47 will cause build fail due to tun2 module can't compile correctly in Gradle.

**Comment by zonyitoo** [comment]
What errors did you see? Paste your error log at least.

**Comment by CyberJet-Project** [comment]
I am sorry..

error log attached here:

`cargo ndk --platform 24 --target=armv7-linux-androideabi  build --release --features=local-fake-dns`

`error[E0432]: unresolved import `ipnet`
   --> src/service/local.rs:816:21
    |
816 |                 use ipnet::{Ipv4Net, Ipv6Net};
    |                     ^^^^^ use of undeclared crate or module `ipnet`

error[E0425]: cannot find value `parse_ipnet` in module `vparser`
   --> src/service/local.rs:478:44
    |
478 |                     .value_parser(vparser::parse_ipnet)
    |                                            ^^^^^^^^^^^ not found in `vparser`
    |
note: found an item that was configured out
   --> src/vparser/mod.rs:60:8
    |
60  | pub fn parse_ipnet(v: &str) -> Result<IpNet, String> {
    |        ^^^^^^^^^^^
    = note: the item is gated behind the `local-tun` feature

error[E0425]: cannot find value `parse_ipnet` in module `vparser`
   --> src/service/local.rs:486:44
    |
486 |                     .value_parser(vparser::parse_ipnet)
    |                                            ^^^^^^^^^^^ not found in `vparser`
    |
note: found an item that was configured out
   --> src/vparser/mod.rs:60:8
    |
60  | pub fn parse_ipnet(v: &str) -> Result<IpNet, String> {
    |        ^^^^^^^^^^^
    = note: the item is gated behind the `local-tun` feature

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `shadowsocks-rust` (lib) due to 3 previous errors`
