### ISSUE TITLE
Cannot use cargo install v1.20.1

### ISSUE THREAD

**Issue by AquaSimulacra** [shadowsocks/shadowsocks-rust#1561]
When I use cargo to install ss-rust, it will install 1.20.0 but not the latest version.
![IMG_5036](https://github.com/shadowsocks/shadowsocks-rust/assets/98635189/a77ac5fa-061f-4d4e-84b3-2ea012941b29)

**Comment by zonyitoo** [comment]
Didn’t publish yet.

**Comment by AquaSimulacra** [comment]
But why I can see it in the release page? Is it because you have not published it in cargo?

**Comment by zonyitoo** [comment]
Yes it is. It will be published tonight.

**Comment by AquaSimulacra** [comment]
Thank you!

**Comment by zonyitoo** [comment]
Published.

**Comment by AquaSimulacra** [comment]
Got it, thank you.

**Comment by ahmeaqas** [comment]
you can find a step by step guide for installing and configuring the shadowsocks server and client i.e. [Unlocking the Internet: A Step-by-Step Guide to Setting Up Your Own Shadowsocks-Rust Proxy Server on Linux](https://hobbytronics.pk/unlocking-the-internet-a-step-by-step-guide-to-setting-up-your-own-shadowsocks-rust-proxy-server-on-linux/).
