### ISSUE TITLE
What is the difference between Shadowsocks and my simple proxy, and can someone tell me the reason?

### ISSUE THREAD

**Issue by xsstc** [shadowsocks/shadowsocks-rust#1562]
I would like to ask a question. I co-wrote a tunnel proxy using the Rust tokio library, which utilizes tokio's TcpStream. It has a client and a server, similar to the principle of Shadowsocks, and the server is located in Hong Kong. My program code is quite simple: the server receives the client's forwarding request, establishes a TCP connection with the target server, and then performs the forwarding. I can connect to websites in mainland China through the proxy I wrote, but I cannot connect to Google. 

However, when I deploy Shadowsocks on the same server, I can connect to Google. I want to know the reason. Can someone help me?

Here is my server code:
```
async fn handle_client(mut client_socket: TcpStream, pool: Arc<Mutex<HashMap<String, TcpStream>>>,client_addr: std::net::SocketAddr) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let key = "hahahah";  
    let mut buffer = Vec::new();
    loop {
        let mut temp_buffer = vec![0; 2048];
        let bytes_read = client_socket.read(&mut temp_buffer).await?;
        if bytes_read == 0 {
            break;
        }
        buffer.extend_from_slice(&temp_buffer[..bytes_read]);
    }
    let request = String::from_utf8(decrypt(key, &buffer)?)?;
    if request.starts_with("CONNECT") {
        if let Some(addr) = parse_connect_request(&request) {
            return handle_connect(client_socket, &request).await;
        } else {
            eprintln!("Invalid CONNECT request");
            return Ok(());
        }
    } else {
        return handle_http(client_socket, &request, pool).await;
    }
}

fn parse_connect_request(request: &str) -> Option<String> {
    let connect_str = "CONNECT ";
    if let Some(pos) = request[connect_str.len()..].find(" HTTP/") {
        let addr = &request[connect_str.len()..connect_str.len() + pos];
        return Some(addr.to_string());
    }
    None
}

async fn handle_connect(mut client_socket: TcpStream, request: &str) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let mut lines = request.lines();
    let request_line = lines.next().ok_or("Invalid HTTP request")?;
    let mut parts = request_line.split_whitespace();
    let _method = parts.next().ok_or("Invalid HTTP request")?;
    let url = parts.next().ok_or("Invalid HTTP request")?;    
    
    let host_port: Vec<&str> = url.split(':').collect();
    if host_port.len() != 2 {
        eprintln!("Invalid address in CONNECT request: {}", request);
        return Ok(());
    }

    let remote_host = host_port[0];
    let remote_port: u16 = host_port[1].parse()?;
    let remote_addr = resolve_address(remote_host, remote_port).await?;

    println!("https--Connecting to server ==> {}", remote_addr);
    let key = "hahahah";
    let estalish_request = b"HTTP/1.1 200 Connection Established\r\n\r\n";
    let mut remote_socket = TcpStream::connect(&remote_addr).await?;
    client_socket.write_all(encrypt(key, estalish_request).as_slice()).await?;

    let (mut ri, mut wi) = remote_socket.into_split();
    let (mut ro, mut wo) = client_socket.into_split();

    let client_to_server = tokio::spawn(forward_decrypted(ro, wi, key));
    let server_to_client = tokio::spawn(forward_encrypted(ri, wo, key));

    tokio::try_join!(client_to_server, server_to_client)?;

    Ok(())
}
```

**Comment by xsstc** [comment]
Does my code use HTTP proxy instead of SOCKS proxy?

**Comment by zonyitoo** [comment]
Well, you didn't provide enough detail about you implementation, I am going to fill the detail with my guess.

1. Your clients are using HTTP Proxy Client protocol, which specifically only the `CONNECT` method to establish a TCP tunnel.
2. There is an "local agent" in your local enviromnet that will "encrypt" your TCP payloads and then send to your remote server (at HK).
3. Remote server accepts clients from the "local agent", and then "decrypt" your TCP payloads, which are in HTTP Proxy Protocol, connects the target servesr and establishes TCP tunnels.

If all the above are the actual implementation, there won't be any errors when accessing Google with a proper implemented client that supports HTTP Proxy Protocol (for example, `curl`).

Here are some tips for you to debug:

1. Checkout the "local agent" detailed log, ensure Client have actually sent HTTP Proxy requests to your "local agent", and your "local agent" can successfully bypasses all the payloads to the proper server.
2. Clients didn't perform DNS resolution but send domain in HTTP Requests.
3. Checkout server's detailed log and see if it can actually receive requests from "local agent".
4. Checkout if server could decrypt the correct HTTP Proxy request from "local agent".
5. Checkout if server sent requests to the remote target.
6. Checkout if server could receive requests from the remote target.
7. ...

**Comment by xsstc** [comment]
> Well, you didn't provide enough detail about you implementation, I am going to fill the detail with my guess.
> 
> 1. Your clients are using HTTP Proxy Client protocol, which specifically only the `CONNECT` method to establish a TCP tunnel.
> 2. There is an "local agent" in your local enviromnet that will "encrypt" your TCP payloads and then send to your remote server (at HK).
> 3. Remote server accepts clients from the "local agent", and then "decrypt" your TCP payloads, which are in HTTP Proxy Protocol, connects the target servesr and establishes TCP tunnels.
> 
> If all the above are the actual implementation, there won't be any errors when accessing Google with a proper implemented client that supports HTTP Proxy Protocol (for example, `curl`).
> 
> Here are some tips for you to debug:
> 
> 1. Checkout the "local agent" detailed log, ensure Client have actually sent HTTP Proxy requests to your "local agent", and your "local agent" can successfully bypasses all the payloads to the proper server.
> 2. Clients didn't perform DNS resolution but send domain in HTTP Requests.
> 3. Checkout server's detailed log and see if it can actually receive requests from "local agent".
> 4. Checkout if server could decrypt the correct HTTP Proxy request from "local agent".
> 5. Checkout if server sent requests to the remote target.
> 6. Checkout if server could receive requests from the remote target.
> 7. ...

I have reexamined my understanding of the SOCKS proxy and then wrote a client and server. However, it still doesn’t work. I think my understanding might be flawed. I have placed the new, simple code at https://github.com/xsstc/rust-socks-proxy.git. If you have time, could you help me take a look? I hope you can point out where my understanding is wrong. This issue has been troubling me for two months.

I am running the client on Windows. Since it’s difficult to set up a SOCKS proxy on Windows (I found some tutorials on Google, but they didn’t work), I am converting HTTP to SOCKS5 in the client, then encrypting it and sending it to the server. The server receives the TCP stream, decrypts it, and then forwards it to the destination server.

Additionally, if I need to set up an HTTPS proxy, do I need to configure a TLS certificate on the cloud server myself?

The shadowsocks-rust project is quite complex for me, and I can only understand it bit by bit. I couldn't find any complete tutorials on proxy servers online. If it's not trouble, could you recommend some tutorials for me? Thank you very much.

**Comment by zonyitoo** [comment]
To be honest, there are lots of "stupid mistakes" in your code, I changed a little bit and they are now nearly working:

1. In `client_socks5.rs`, [these lines](https://github.com/xsstc/rust-socks-proxy/blob/0fa0437c7967bbba9d7639a9d8b92e0bee43f226/src/client_socks5.rs#L74-L84) are completely useless, your server won't send a response to client with these data.

2. You should read [SOCKS5 RFC](https://datatracker.ietf.org/doc/html/rfc1928) before writing your code.

3. You should read [HTTP Proxy RPC](https://www.ietf.org/rfc/rfc2068.txt) and [CONNECT](https://www.rfc-editor.org/rfc/rfc9110#CONNECT).
    Specifically, you should at least send a response to your client `HTTP/1.1 200 OK\r\n\r\n` to let it know TCP tunnel have already been established.

4. Your `encrypt` and `decrypt` are completely wrong, you seems like have no knowledge about how these crypto algorithms working. Specifically:

    - You `encrypt` the data everytime when `read()` from the `client_stream`, which is not fixed-length, so your encrypted result will not be fixed-length.
    - Then your server receives this encrypted data by `read()`, which couldn't be sure that you could get the exact length of data that you just `write()` from your `client_socks5.rs`.
    - You generate and prepend an IV everytime when calling `encrypt()`, which is a completely wrong design.

5. Delete those `encrypt()` and `decrypt()` call in code, with all the fixed I have applied, the proxy is working well.

Since your program are building on a wrong protocol design, so I stopped right here. Your should first design a proper client-server protocol.

You are missing too many background knowledge about network protocol design, cryptographic algorithm basic principle, TCP server design. So I suggest you should learn background knowledge before getting your hand on the actual proxy implementation.

**Comment by xsstc** [comment]
> To be honest, there are lots of "stupid mistakes" in your code, I changed a little bit and they are now nearly working:
> 
> 1. In `client_socks5.rs`, [these lines](https://github.com/xsstc/rust-socks-proxy/blob/0fa0437c7967bbba9d7639a9d8b92e0bee43f226/src/client_socks5.rs#L74-L84) are completely useless, your server won't send a response to client with these data.
> 2. You should read [SOCKS5 RFC](https://datatracker.ietf.org/doc/html/rfc1928) before writing your code.
> 3. You should read [HTTP Proxy RPC](https://www.ietf.org/rfc/rfc2068.txt) and [CONNECT](https://www.rfc-editor.org/rfc/rfc9110#CONNECT).
>    Specifically, you should at least send a response to your client `HTTP/1.1 200 OK\r\n\r\n` to let it know TCP tunnel have already been established.
> 4. Your `encrypt` and `decrypt` are completely wrong, you seem like have no knowledge about how these crypto algorithms working. Specifically:
>    
>    * You `encrypt` the data everytime when `read()` from the `client_stream`, which is not fixed-length, so your encrypted result will not be fixed-length.
>    * Then your server receives this encrypted data by `read()`, which couldn't be sure that you could get the exact length of data that you just `write()` from your `client_socks5.rs`.
>    * You generate and prepend an IV everytime when calling `encrypt()`, which is a completely wrong design.
> 5. Delete those `encrypt()` and `decrypt()` call in code, with all the fixed I have applied, the proxy is working well.
> 
> Since your program are building on a wrong protocol design, so I stopped right here. Your should first design a proper client-server protocol.
> 
> You are missing too many background knowledge about network protocol design, cryptographic algorithm basic principle, TCP server design. So I suggest you should learn background knowledge before getting your hand on the actual proxy implementation.

"Thank you very much for your suggestions. I will follow your advice to study and make changes.

**Comment by xsstc** [comment]
> To be honest, there are lots of "stupid mistakes" in your code, I changed a little bit and they are now nearly working:
> 
> 1. In `client_socks5.rs`, [these lines](https://github.com/xsstc/rust-socks-proxy/blob/0fa0437c7967bbba9d7639a9d8b92e0bee43f226/src/client_socks5.rs#L74-L84) are completely useless, your server won't send a response to client with these data.
> 2. You should read [SOCKS5 RFC](https://datatracker.ietf.org/doc/html/rfc1928) before writing your code.
> 3. You should read [HTTP Proxy RPC](https://www.ietf.org/rfc/rfc2068.txt) and [CONNECT](https://www.rfc-editor.org/rfc/rfc9110#CONNECT).
>    Specifically, you should at least send a response to your client `HTTP/1.1 200 OK\r\n\r\n` to let it know TCP tunnel have already been established.
> 4. Your `encrypt` and `decrypt` are completely wrong, you seem like have no knowledge about how these crypto algorithms working. Specifically:
>    
>    * You `encrypt` the data everytime when `read()` from the `client_stream`, which is not fixed-length, so your encrypted result will not be fixed-length.
>    * Then your server receives this encrypted data by `read()`, which couldn't be sure that you could get the exact length of data that you just `write()` from your `client_socks5.rs`.
>    * You generate and prepend an IV everytime when calling `encrypt()`, which is a completely wrong design.
> 5. Delete those `encrypt()` and `decrypt()` call in code, with all the fixed I have applied, the proxy is working well.
> 
> Since your program are building on a wrong protocol design, so I stopped right here. Your should first design a proper client-server protocol.
> 
> You are missing too many background knowledge about network protocol design, cryptographic algorithm basic principle, TCP server design. So I suggest you should learn background knowledge before getting your hand on the actual proxy implementation.

I followed your advice to read the SOCKS5 RFC and the HTTP Proxy RFC and CONNECT. (I have roughly gone through them because there were some parts I didn’t understand; I will continue to read them later.) I added new code files clientV2.rs and serverV2.rs. Now, I can connect to Google, but it only works once. After that, when I try to access other websites, it gets stuck. I’m using Windows’ built-in proxy feature to construct SOCKS5 based on the HTTP CONNECT request in the client. If you have time, could you help me review the new code? I’d like to check if my logic is correct and also understand how to connect to multiple websites normally. Additionally, you mentioned before that "Since your program is building on a wrong protocol design," what does "protocol design" mean? Does Shadowsocks-rust have a protocol design?  I can continually enhance my understanding by reading code. I've asked many people, but no one has responded, so I'm truly grateful for your help.

**Comment by zonyitoo** [comment]
> what does "protocol design" mean

A protocol how your data was transferred through network. You can send and recv data properly with a proper protocol design, otherwise you will have the problem like you do.

> Does Shadowsocks-rust have a protocol design?

Of course. They are in:

https://shadowsocks.org/doc/aead.html
https://shadowsocks.org/doc/stream.html
https://shadowsocks.org/doc/sip022.html
https://shadowsocks.org/doc/sip023.html

**Comment by xsstc** [comment]
> > what does "protocol design" mean
> 
> A protocol how your data was transferred through network. You can send and recv data properly with a proper protocol design, otherwise you will have the problem like you do.
> 
> > Does Shadowsocks-rust have a protocol design?
> 
> Of course. They are in:
> 
> https://shadowsocks.org/doc/aead.html https://shadowsocks.org/doc/stream.html https://shadowsocks.org/doc/sip022.html https://shadowsocks.org/doc/sip023.html

I checked the link you gave me. From my understanding, protocol design involves encrypting and decrypting the HTTP stream that is forwarded after SOCKS authentication is completed and a tunnel is established, similar to AEAD. If I split a piece of information into three chunks, I can design my own rules, such as setting a marker in each chunk so that after they are parsed, the three chunks can be reassembled in order. Additionally, I can mark the last chunk to indicate that the entire message has been sent, and then let the server forward it.

I forgot to mention above that I rewrote clientV2 and serverV2, which you can find here: https://github.com/xsstc/rust-socks-proxy/tree/main/src. Could you please help me check it ? Currently, it can connect to Google, but only once, and then it can't connect to any website. The server's screenshot below shows that it seems to be blocked. What's the meaning of the "Connection reset by peer
![guzhang](https://github.com/shadowsocks/shadowsocks-rust/assets/37971233/b33c8b9b-0283-4309-a3f3-67cb1a8f972d)
"

 I suspect the reason might be that the tunnel is not being pinned after being established, causing the program to lose track of the tunnel's address in memory. Alternatively, each request might be establishing a tunnel to the target server, causing the program to become blocked. Should I store the tunnels established between the client and the target server in a hashmap and reuse the tunnel for subsequent requests to the same server? Do I need to design a ping function like in the shadowsocks-rust project to keep the tunnel connection alive?

**Comment by xsstc** [comment]
> > I checked the link you gave me. From my understanding, protocol design involves encrypting and decrypting the HTTP stream that is forwarded after SOCKS authentication is completed and a tunnel is established, similar to AEAD. If I split a piece of information into three chunks, I can design my own rules, such as setting a marker in each chunk so that after they are parsed, the three chunks can be reassembled in order. Additionally, I can mark the last chunk to indicate that the entire message has been sent, and then let the server forward it.
> 
> Well, a very simple and common protocol design is TLV (Type-Length-Value). The design you mentioned is like `startmarker-value-endmarker`. Of course it should work, but if your value contains something like your endmarker, then receiver will get confused. Anyway this is not something I want to discuss, you can choose any designs that are proper and complete.
> 
> > I suspect the reason might be that the tunnel is not being pinned after being established, causing the program to lose track of the tunnel's address in memory.
> 
> No. Connection reset by peer, means that when you want to `write()` data to a TCP socket, the socket have already been closed by remote. So if you know that is the cause of ECONNRESET, then you should findout why the remote socket is closed before receiving your data, that is very obvious:
> 
> https://github.com/xsstc/rust-socks-proxy/blob/bbebb6d4639fc853df0ec0cfd81bf7202bec3a91/src/clientV2.rs#L82-L93
> 
> You are using `select!`, please read the document about what `select!` was doing. In this piece of code, any of these two futures `client_to_socks` and `socks_to_client` ends will then let the control flow going to the end of `handle_connection`, which eventually causing the other future getting aborted.
> 
> You should use `join` or anything similiar.

I changed select! to try_join!, but I still can only connect to the website once. Trying to connect again results in an error. For example, the webpage shows the error:
The webpage cannot function properly www.google.com.hk did not send any data.
ERR_EMPTY_RESPONSE/

The server console output is as follows:
![zzz](https://github.com/shadowsocks/shadowsocks-rust/assets/37971233/82b9cac0-5fa9-41ea-bed0-f2338cdfd45f)

as shown in the image, indicates that it gets stuck at the cursor. No matter what my client sends, it no longer shows anything. 'Domain ===>' shows the target server domain . The client console output is as follows:
```
Received request ===> "CONNECT cm.mgid.com:443 HTTP/1.1\r\nHost: cm.mgid.com:443\r\nProxy-Connection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0\r\n\r\n"

Received request ===> "CONNECT pr-bh.ybp.yahoo.com:443 HTTP/1.1\r\nHost: pr-bh.ybp.yahoo.com:443\r\nProxy-Connection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0\r\n\r\n"

Target address: cm.mgid.com, target port: 443

Target address: pr-bh.ybp.yahoo.com, target port: 443

Error handling connection: Os { code: 10060, kind: TimedOut, message: "The connection attempt failed because the connected party did not properly respond after a period of time or the connected host did not respond." }

Received request ===> "CONNECT assets.msn.cn:443 HTTP/1.1\r\nHost: assets.msn.cn:443\r\nProxy-Connection: keep-alive\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0\r\n\r\n"

Target address: assets.msn.cn, target port: 443

Error handling connection: Os { code: 10060, kind: TimedOut, message: "The connection attempt failed because the connected party did not properly respond after a period of time or the connected host did not respond." }

Error handling connection: Os { code: 10060, kind: TimedOut, message: "The connection attempt failed because the connected party did not properly respond after a period of time or the connected host did not respond." }

Error handling connection: Os { code: 10060, kind: TimedOut, message: "The connection attempt failed because the connected party did not properly respond after a period of time or the connected host did not respond." }
```
But after a while, when the server console again displays 'Domain ===> xxxx', I can connect to the websites again. Then the server blocks again, with the cursor blinking in place. Once blocked, the server stops receiving information from the client. What I don't understand now is why the server is blocking. Each connection is handled as a new asynchronous task, and the asynchronous scheduler should continue to schedule tasks. When the server is blocked, the CPU and memory usage on the cloud server are relatively low, so this might not be an issue with the cloud server itself.

I would like to ask what the reason for this issue is and how I can resolve it. The knowledge I've gained in these few days surpasses that of the past two months. I feel like I'm close to implementing a simple tunnel proxy server. Thank you again for your help！

**Comment by zonyitoo** [comment]
Actually it works quite well with `curl`, I cannot reproduce your error cases.

You should test on the same machine to exclude any external factors that affect your test results. I suspects that your connection or remote port was somehow being blocked by a middleman.

**Comment by xsstc** [comment]
> Actually it works quite well with `curl`, I cannot reproduce your error cases.
> 
> You should test on the same machine to exclude any external factors that affect your test results. I suspects that your connection or remote port was somehow being blocked by a middleman.

Thank you for your patient help. I am in China, and the server is in Hong Kong. I suspect it's the Great Firewall (GFW) causing the issue, so I will try encrypting the data to bypass the GFW. Should I keep the created tunnels in a hashmap for reuse? In the future, there will be multiple clients connecting to the server, and I want the program to run more efficiently. By the way, in shadowsocks-rust, there is a ping function and a struct called PingBalancer. Is the ping function used to maintain the long-term connection of the tunnel?

**Comment by zonyitoo** [comment]
The answer is in the code, read the code.
