### ISSUE TITLE
ss-rust is not on the big comparison table

### ISSUE THREAD

**Issue by Artoria2e5** [shadowsocks/shadowsocks-rust#157]
https://github.com/shadowsocks/shadowsocks/wiki/Feature-Comparison-across-Different-Versions

**Comment by zonyitoo** [comment]
Most of the implementations are not in the table.

**Comment by Artoria2e5** [comment]
... and I guess it won't be a bad idea to do an update and put all official ones on there?

**Comment by zonyitoo** [comment]
Move this issue to https://github.com/shadowsocks/shadowsocks-org .

**Comment by zonyitoo** [comment]
It is already in the table on shadowsocks.org: http://shadowsocks.org/en/spec/Implementations.html .

**Comment by zonyitoo** [comment]
Could be replaced by: https://github.com/shadowsocks/shadowsocks-org/wiki/Implementations
Which is showing in https://shadowsocks.org/en/spec/Implementations.html
