### ISSUE TITLE
"Tunnel protocol" configuration and protocol overhead (the local-tunnel thing), lots of questions

### ISSUE THREAD

**Issue by tonsimple** [shadowsocks/shadowsocks-rust#1570]
Okay, so basically the readme has two examples - the "Tunnel Local client" section 
`sslocal --protocol tunnel -b "127.0.0.1:3128" -f "127.0.0.1:8080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty"` 

and the server section with a fairly large config that I won't quote (starts "// Tunnel local server (feature = "local-tunnel")) but that server example seems entirely "unmarried" from the local example ...

Questions: 

1) Do I understand correctly that in the "Tunnel Local client" the "127.0.0.1:8080" is localhost port 8080 on **server machine** ?

2) if it is, then does server need any additional configuration (beyond being built with "tunnel" protocol support) to allow for tunneling as specified in example above, or will a "well behaved" shadowsocks-rust server built with tunnel support get all the necessary data from the clientside? 

3) How much overhead is added by "tunnel local" feature operation assuming no encryption (encryption:none), by which I mean: 

I presume at minimum (with no encryption) there needs to be ATYP + address + port to reach the remote shadowsocks server and at least one more ATYP + address + port to specify "where to forward to"...

 would that be correct? Anything extra added there that I'm missing? 

4) bonus question about encryption:none :-) 
it seems to still demand a password when starting up a client, is that used somewhere for something, or is it just a quirk of the rarely used "no encryption" feature ? 

P.S.: 
in case someone wonders, what I'm trying to do is to leverage shadowsocks into using [Mullvad's udp2tcp<>tcp2udp](https://github.com/mullvad/udp-over-tcp) solution to traverse a naughty network that just won't let udp packets be  

The scheme goes something like 

shadowsocks client 1 [SC1] - actually receives UDP traffic from app using SOCKS5 udp features, "targets" a udp2tcp port

shadowsocks client 2 [SC2] - sends TCP from udp2TCP to SS1, presumably the place where "local-tunnel" has to be done
 
shadowsocks server 1 [SS1] - receives the "tunnel" traffic and forwards it to TCP2udp binary 

shadowsocks server 2 [SS2] - receives udp traffic from TCP2udp and sends back replies 

like
`SC1<->udp2TCP<->SC2<-local-tunnel->SS1<->TCP2udp<->SS2<->destination`

**Comment by zonyitoo** [comment]
Shadowsocks service will always has a "local client" and "remote server", so there will be no ambiguity about "Tunnel Local Client":

For the example: `sslocal --protocol tunnel -b "127.0.0.1:3128" -f "127.0.0.1:8080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty"`

```
(Client) --> Tunnel Local Client (listening 127.0.0.1:3128) --> Remote Server (listening [::1]:8388) --> Target Server (127.0.0.1:8080)
```

`local-tunnel` client for establishing a tunnel in shadowsocks protocol to a fixed "forward address" destination target server.
 So in the example, everything that sends to 127.0.0.1:3128, will always be sent to 127.0.0.1:8080 via [::1]:8388 in shadowsocks protocol.

> it seems to still demand a password when starting up a client, is that used somewhere for something, or is it just a quirk of the rarely used "no encryption" feature ?

I cannot reproduce.
