### ISSUE TITLE
请教下rust版本加盐的流程

### ISSUE THREAD

**Issue by 13437543491** [shadowsocks/shadowsocks-rust#1575]
void aead_ctx_init(cipher_t *cipher, cipher_ctx_t *cipher_ctx, int enc)
由于之前使用了libev版本的，在这个方法里面，做了自己的逻辑处理，rust版本有相对应处理加盐的方法吗？可以给一下代码路径吗

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/tree/master/crates/shadowsocks/src/relay

All shadowsocks protocol implementation codes are in this directory.
