### ISSUE TITLE
Customize Shadowsocks server DNS

### ISSUE THREAD

**Issue by AquaSimulacra** [shadowsocks/shadowsocks-rust#1576]
The default DNS server for ssserver is 8.8.8.8. I want to change this to cloudflare. However, when I try to run this command ssserver --dns cloudflare, it tells me "missing proxy servers, consider specifying it by --server-addr, --encrypt-method, --password command line option, or configuration file, check more details in https://shadowsocks.org/guide/configs.html". This URL "https://shadowsocks.org/guide/configs.html" doesn't work. Moreover, I don't understand what does  --server-addr mean in this command. I am totally disoriented. Can anyone help me out?

**Comment by zonyitoo** [comment]
> The default DNS server for ssserver is 8.8.8.8.

No. There is no "default DNS server". You must have set `nameserver 8.8.8.8` in your `/etc/resolv.conf`.

> However, when I try to run this command ssserver --dns cloudflare, it tells me "missing proxy servers, consider specifying it by --server-addr, --encrypt-method, --password command line option, or configuration file, check more details in [shadowsocks.org/guide/configs.html](https://shadowsocks.org/guide/configs.html)".

The console prompt was very clear, you have to provide at least one server instance parameter either from command line (`--server-addr xxxx:xxx --encrypt-method mmm --password ppp`) or from configuration file (`-c`).

**Comment by AquaSimulacra** [comment]
So you mean that ss will just use the nameserver specified in resolv.conf?

**Comment by zonyitoo** [comment]
By default, yes.

**Comment by AquaSimulacra** [comment]
> So you mean that ss will just use the nameserver specified in resolv.conf? But when I check ssservice status it gives me this. ![image](https://private-user-images.githubusercontent.com/98635189/346248894-af109207-63f5-46cd-9319-b3a43cc3c9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzY1NjIsIm5iZiI6MTcyMDIzNjI2MiwicGF0aCI6Ii85ODYzNTE4OS8zNDYyNDg4OTQtYWYxMDkyMDctNjNmNS00NmNkLTkzMTktYjNhNDNjYzNjOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjkwMzcyYmI3OTBlMzUwYTBkNzc5ZWE4MDE1ZTVmNGY0MjZkNmZkMjBiM2YyOWY2MDRjNTI2MzYyZTU1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJv3A3y1qain-xDI73dBJVDa6wmJRdwo437aF8BTgBs)

It tells me that it starts with dns 8.8.8.8

**Comment by AquaSimulacra** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/98635189/b380c396-4111-4bc0-8088-4d0e98f84bf3)
And this is my config

**Comment by zonyitoo** [comment]
Your `/system.slice/ss-rust.service` starts `ssservice` with that command line.

**Comment by AquaSimulacra** [comment]
Then how should I change this command line?

**Comment by zonyitoo** [comment]
`vim /system.slice/ss-rust.service`.

**Comment by AquaSimulacra** [comment]
![image](https://github.com/shadowsocks/shadowsocks-rust/assets/98635189/56a8d9a8-bbea-4152-b00c-553d32ae25e5)
But there is nothing in this file

**Comment by zonyitoo** [comment]
Then you will have to find the exact service file yourself.

**Comment by AquaSimulacra** [comment]
Thank you for helping!

**Comment by zonyitoo** [comment]
`cloudflare_https` is supported by features "dns-over-https", which is not enabled by default.
