### ISSUE TITLE
How to also block the error information prompted and block all log information

### ISSUE THREAD

**Issue by Chichifn** [shadowsocks/shadowsocks-rust#1588]

**Comment by Chichifn** [comment]
It is on the Shadowsocks v1.20.1. x86_64 pc windows msmc

**Comment by zonyitoo** [comment]
What do you want to achieve? Logging output can be filtered by setting the `RUST_LOG` variable. `RUST_LOG=off`

**Comment by Chichifn** [comment]
> What do you want to achieve? Logging output can be filtered by setting the `RUST_LOG` variable. `RUST_LOG=off`

ssserver -c config.json RUST_LOG=off
error: unexpected argument 'RUST_LOG=off' found

What I want to achieve is not to need all logs, including logs for errors

**Comment by zonyitoo** [comment]
If you are running in CMD, use `set RUST_LOG=off` before running `ssserver`.
