### ISSUE TITLE
1.20.x ssservice.exe and sswinservice.exe can not run on windows server 2016

### ISSUE THREAD

**Issue by peng5545** [shadowsocks/shadowsocks-rust#1589]
run ssservice or sswinservice from cmd, nothing output but ssserver run just fine.
downgrade to 1.19.4 then everything is ok.
os:Server 2016 Datacenter 1607 14393.7070

**Comment by zonyitoo** [comment]
You must provide more detail about the key issue, what did you see, what do you think that is the cause of the current issue.

**Comment by peng5545** [comment]
> You must provide more detail about the key issue, what did you see, what do you think that is the cause of the current issue.

key issue is ....i saw nothing, neither cmd window nor windows Event Viewer.
![2016](https://github.com/user-attachments/assets/da37dbda-78ad-4ba4-b88c-6cf3306dc501)
![2022](https://github.com/user-attachments/assets/33147700-e646-4836-acaa-7e3b6e04a288)

**Comment by zonyitoo** [comment]
Interesting. There must be something wrong working with `stdout` or `stderr` in the latest version.

Could you dig more deeper about what exactly it was happening?

**Comment by peng5545** [comment]
ok, maybe try do something this weekend.

**Comment by peng5545** [comment]
> Interesting. There must be something wrong working with `stdout` or `stderr` in the latest version.
> 
> Could you dig more deeper about what exactly it was happening?

The procedure entry point SetInterfaceDnsSettings could not be located in the dynamic link library C:\Users\Administrator\Desktop\shadowsocks-rust-master\target\release\full\sslocal.exe. 


On fresh install OS show this error message, and maybe cause by this change,I try change version to 1, no error.
#https://github.com/shadowsocks/shadowsocks-rust/commit/b5f3065f3df875a2450629e475d462ce4cdfec30#r144199956

**Comment by database64128** [comment]
Makes sense. The [documentation](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-setinterfacednssettings) for `SetInterfaceDnsSettings` says the minimum supported server is Windows 10 Build 19041, which is higher than your OS build number.

**Comment by zonyitoo** [comment]
I suspect this is the root cause. https://github.com/tun2proxy/rust-tun/pull/74/files

**Comment by peng5545** [comment]
Download new build,problem was solved,THX!
