### ISSUE TITLE
Feature Request: Support ROUTE_TABLE for tproxy ip rule add fwmark $ROUTE_FWMARK table $ROUTE_TABLE

### ISSUE THREAD

**Issue by peterwillcn** [shadowsocks/shadowsocks-rust#1593]
Feature Request: Support ROUTE_TABLE for tproxy:
  ip rule add fwmark $ROUTE_FWMARK table $ROUTE_TABLE

**Comment by zonyitoo** [comment]
What do we need to do for supporting it?

**Comment by peterwillcn** [comment]
> What do we need to do for supporting it?
```
ip rule add fwmark $ROUTE_FWMARK table $ROUTE_TABLE
iptables -w -t mangle -A ss -s $subnet -j MARK --set-mark $ROUTE_FWMARK
iptables -w -t mangle -A ss -m mark --mark $ROUTE_FWMARK -j ACCEPT
iptables -w -t mangle -I PREROUTING -j ss
iptables -w -t mangle -I OUTPUT -p udp --dport 53 -j ss 
```

**Comment by zonyitoo** [comment]
These are all done via command line. So what do we need to do in code for supporting it?

**Comment by peterwillcn** [comment]
> These are all done via command line. So what do we need to do in code for supporting it?

May I ask how to implement it via command line? Please advise，Thanks!

**Comment by zonyitoo** [comment]
The `$ROUTE_TABLE` is a shell variable. You may just assign a number to it.

**Comment by peterwillcn** [comment]
> The `$ROUTE_TABLE` is a shell variable. You may just assign a number to it.

What I mean is that the default traffic for starting sslocal is stored in - T $ROUTE_TABLE

**Comment by zonyitoo** [comment]
So how to implement `-T`, what’s the actual syscall to set with the provided argument?

**Comment by peterwillcn** [comment]
> So how to implement `-T`, what’s the actual syscall to set with the provided argument?

ref: https://github.com/rssnsj/network-feeds/blob/master/minivtun-tools/files/etc/init.d/minivtun.sh

> So how to implement `-T`, what’s the actual syscall to set with the provided argument?

```
		/usr/sbin/minivtun -r [$server_addr]:$server_port -n $ifname \
			-a $local_ipaddr/`netmask_to_pfxlen $local_netmask` \
			-e "$password" -t "$algorithm" -w -m $mtu \
			-D -v 0.0.0.0/0 -T $VPN_ROUTE_TABLE -M $metric_base++$nr_tunnels \
			-p /var/run/$ifname.pid -H /var/run/$ifname.health \
			$cmd_opts -d || continue
```
Can you refer to this: https://github.com/rssnsj/minivtun/blob/d7007bd8a79eadcd38d8e652dffaca93c2580cd2/src/minivtun.c#L172

**Comment by zonyitoo** [comment]
https://github.com/rssnsj/minivtun/blob/d7007bd8a79eadcd38d8e652dffaca93c2580cd2/src/library.c#L439-L509

On macOS and FreeBSD, it actually calls `route` command directly. For others, Linux I suppose, set with `ip` commands.

So you can always do it via command line.

**Comment by peterwillcn** [comment]
@zonyitoo I have found your script and am currently learning it https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/iptables_tproxy.sh 
Thanks.
