### ISSUE TITLE
~~~~

### ISSUE THREAD

**Issue by Su-Du** [shadowsocks/shadowsocks-rust#1596]

**Comment by zonyitoo** [comment]
I couldn't understand what you are talking about. Let me guess: You want to put shadowsocks' traffic into a wireguard tunnel?

**Comment by Su-Du** [comment]
I want my outbound ip to be a wireguard ip, because I often access content that has a territorial jurisdiction, which requires a different IP.

**Comment by Su-Du** [comment]
> I couldn't understand what you are talking about. Let me guess: You want to put shadowsocks' traffic into a wireguard tunnel?

I want my outbound ip to be a wireguard ip, because I often access content that has a territorial jurisdiction, which requires a different IP.

**Comment by Su-Du** [comment]
> I couldn't understand what you are talking about. Let me guess: You want to put shadowsocks' traffic into a wireguard tunnel?

Yes

**Comment by zonyitoo** [comment]
I have no idea what was blocking you from making shadowsocks' ssserver's outbound traffic to be relayed by wireguard.

**Comment by Su-Du** [comment]
> I have no idea what was blocking you from making shadowsocks' ssserver's outbound traffic to be relayed by wireguard.

I may not express it clearly. My client and server have established a connection through shadowsocks-rust and there is no problem. However, my server is in Germany and the content I access is in the United States. It has IP jurisdiction, so I need to give SS the outbound IP. Become the wireguard connection I established on the server.

**Comment by Su-Du** [comment]
> 我不知道是什么阻止你让 shadowsocks 的 ssserver 的出站流量通过 wireguard 中继。

client=ss  to server=ss to wireguard(US)=OK

**Comment by zonyitoo** [comment]
> > I have no idea what was blocking you from making shadowsocks' ssserver's outbound traffic to be relayed by wireguard.
> 
> I may not express it clearly. My client and server have established a connection through shadowsocks-rust and there is no problem. However, my server is in Germany and the content I access is in the United States. It has IP jurisdiction, so I need to give SS the outbound IP. Become the wireguard connection I established on the server.

Just simply starts wireguard on server serving on an interface, for example `wg0`. And then set `outbound-bind-interface wg0` for ssserver.

**Comment by Su-Du** [comment]
What about binding? My configuration is as follows, can you write it down for me? Thanks for your help and great project

**Comment by Su-Du** [comment]
> > > I have no idea what was blocking you from making shadowsocks' ssserver's outbound traffic to be relayed by wireguard.
> > 
> > I may not express it clearly. My client and server have established a connection through shadowsocks-rust and there is no problem. However, my server is in Germany and the content I access is in the United States. It has IP jurisdiction, so I need to give SS the outbound IP. Become the wireguard connection I established on the server.
> 
> Just simply starts wireguard on server serving on an interface, for example `wg0`. And then set `outbound-bind-interface wg0` for ssserver.

cat /etc/shadowsocks/config.json
{
"server": "::",
"server_port": 14324,
"password": "XXXXXXXXXXXXXXXXXXXXXX",
"method": "aes-256-gcm",
"fast_open": true,
"mode": "tcp_and_udp",
"user":"nobody",
"timeout":300,
"nameserver":"127.0.0.1"
}

**Comment by zonyitoo** [comment]
```json
{
    "outbound_bind_interface": "wg0"
}
```
