### ISSUE TITLE
Publish on macports

### ISSUE THREAD

**Issue by talentlessguy** [shadowsocks/shadowsocks-rust#1607]
So that it can be installed via `sudo port install shadowsocks-rust`. MacPorts only have libev C implementation at the moment.

**Comment by zonyitoo** [comment]
I thought macOS users should prefer HomeBrew than MacPorts.

**Comment by talentlessguy** [comment]
@zonyitoo homebrew installs from git repos and to a home dir instead of system wide. homebrew pulls a bunch of uneeded crap unfortunately.

**Comment by zonyitoo** [comment]
Do you know how to make a Portfile for this project and update it automatically (maybe with github action)?

**Comment by zonyitoo** [comment]
https://guide.macports.org/#development.buildbot

Emm, MacPorts has a buildbot.

**Comment by talentlessguy** [comment]
yes, and the portfile needs to be added to this GitHub repo:

https://github.com/macports/macports-ports

**Comment by talentlessguy** [comment]
thank you for publishing it!
