### ISSUE TITLE
Visibility of methods in shadowsocks 

### ISSUE THREAD

**Issue by botylev** [shadowsocks/shadowsocks-rust#1613]
Hello,

I'm building my own personal proxy tool and would like to use the existing shadowsocks-rust project as a library.
I faced a small problem with a function in [ProxyServerStream::from_stream](https://github.com/shadowsocks/shadowsocks-rust/blob/4c2bdaeabb0c78da12541fdaebcac929ad2719a6/crates/shadowsocks/src/relay/tcprelay/proxy_stream/server.rs#L45C7-L45C16) - it is marked as pub(crate) and therefore I cannot reuse it in my code. I know about ProxyListener built in shadowsocks crate but I would really prefer to use ProxyServerStream with already accepted TcpStream from Tokio because it is more convenient to work with in my application context.

Can you please elaborate on `pub(crate)` visibility on this method? Can it be done just like `pub`?

Also I would like to mention [CryptoStream::set_request_nonce_with_received](https://github.com/shadowsocks/shadowsocks-rust/blob/4c2bdaeabb0c78da12541fdaebcac929ad2719a6/crates/shadowsocks/src/relay/tcprelay/crypto_io.rs#L440C6-L440C15) and [CryptoStream::current_data_chunk_remaining](https://github.com/shadowsocks/shadowsocks-rust/blob/4c2bdaeabb0c78da12541fdaebcac929ad2719a6/crates/shadowsocks/src/relay/tcprelay/crypto_io.rs#L454) because they are also marked as `pub(crate)` and I think they can be just `pub`.

Thanks

**Comment by zonyitoo** [comment]
Make them public means that I have to maintain API compatibility in the future upgrades, but they are really should not being considered as "stable" APIs.

**Comment by zonyitoo** [comment]
Well, because the Server stream can only be built by Listener, so it doesn't need to be public. The Client stream's `from_stream` was used in the service crate so it has to be public.

I am Ok to make Server stream's `from_stream` public, but the `user_manager` shouldn't be there because it is not a required attribute, which should be set with a setter.
