### ISSUE TITLE
How to configure hickory-dns

### ISSUE THREAD

**Issue by smithe-ma** [shadowsocks/shadowsocks-rust#1617]
Add to config.json
 {
"hickory-dns":true, 
 "dns": "google",
 "dns_cache_size": 100,
 "keep_alive": 20,
 "nofile": 10240,

}

I don't know if this configuration has been successfully enabled hickory-dns and dns_cache_size.
How to check it  work or not?
Still need cp hickory-dns to the same dir with ssserver or not?

Please give me some advice, thanks

**Comment by zonyitoo** [comment]
Did you invent those configuration fields yourself? The only configuration key is `"dns"`, hickory-dns is enabled by feature `hickory-dns`, which is enabled by default.

**Comment by smithe-ma** [comment]
thanks. I wrote it myself according to the instructions, but I didn't
understand.
which ways can I check the dns_cache?

May I ask again, v2Plugin Settings
{
    "plugin_opts": "mode=quic;host=github.com",
    "plugin_args": [
        // Each line is an argument passed to "plugin"
        "--verbose"
    ],
    "plugin_mode": "tcp_and_udp", // SIP003u, default is "tcp_only"
}

host mut be  myself website?

Directly using this configuration (mode=quic;host=github.com) can not
connect

ty ***@***.***> 於 2024年8月18日週日 下午10:48寫道：

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust#configuration

Here is the reference of configuration keys.

For issues related to v2ray-plugin, you should open them in v2ray-plugin's repository.
