### ISSUE TITLE
What is the official directory for plugins when installed using `snap install shadowsocks-rust`?

### ISSUE THREAD

**Issue by http600** [shadowsocks/shadowsocks-rust#1618]
I executed the following commands:

```bash
mkdir -p /var/snap/shadowsocks-rust/common/bin/
install /usr/bin/ss-v2ray-plugin /var/snap/shadowsocks-rust/common/bin/
```
This was necessary because the Snap service could not access `/usr/bin/ss-v2ray-plugin`.

It seems:

1. I spent several hours before finally getting it to work. It would be nice to have it in `README`
2. I chose the directory `/var/snap/shadowsocks-rust/common/bin/`, and it works, but is this officially accepted?

**Comment by zonyitoo** [comment]
Snap created a closed environment for an application. I don't know what is the "officially accepted" way to let a snap application access binaries outside the snap controlled environment, so I cannot answer this question.

**Comment by ahmeaqas** [comment]
you can find a step by step guide for installing and configuring the shadowsocks server and client i.e. [Unlocking the Internet: A Step-by-Step Guide to Setting Up Your Own Shadowsocks-Rust Proxy Server on Linux](https://hobbytronics.pk/unlocking-the-internet-a-step-by-step-guide-to-setting-up-your-own-shadowsocks-rust-proxy-server-on-linux/).
