### ISSUE TITLE
Disable tunnel features on server side?

### ISSUE THREAD

**Issue by mklnz** [shadowsocks/shadowsocks-rust#1633]
Just wondering if it's possible to disable tunnel features on the server side so users cannot forward ports bound to 127.0.0.1 on the server side?

**Comment by zonyitoo** [comment]
What do you mean about "tunnel features"? There is not such thing in the server. Or I can say that the server itself is a TCP/UDP tunnel, so disabling the "tunnel" is just kill the server itself.

> so users cannot forward ports bound to 127.0.0.1 on the server side

It could be solved with ACL rules, read the doc:
https://github.com/shadowsocks/shadowsocks-rust#acl
