### ISSUE TITLE
是否有计划迁移到 async/await ？

### ISSUE THREAD

**Issue by gfreezy** [shadowsocks/shadowsocks-rust#164]
async/await 1.39 就会 stable

**Comment by zonyitoo** [comment]
正在做。目前主要依赖到 https://github.com/bluejekyll/trust-dns/pull/849 。

修改特别的多，进度

- [ ] TCP Relay
- [ ] UDP Relay
- [ ] DNS Proxy

**Comment by zonyitoo** [comment]
Discussion moved to #165 .
