### ISSUE TITLE
Regarding issues encountered during the experimental verification of the MPTCP functionality on shadowsocks-rust.

### ISSUE THREAD

**Issue by maojianyou** [shadowsocks/shadowsocks-rust#1642]
Client A and Server B are connected through two lines. On A, there are interfaces em2: 10.10.73.2 and em3: 10.10.74.2. On Server B, the interfaces are em2: 10.10.73.1 and em3: 10.10.74.1. Then, I created a virtual IP on Server B, for example, tun1 with IP 6.6.6.6. I set up two static routes on A for load balancing. However, I found that after enabling MPTCP in the kernel, only one connection was made, for example, using em3 with IP 10.10.74.1.

I suspect the reason is that on Client A, the command sslocal -s 6.6.6.6:6666 is used, while on Server B, the command ./ssserver -m none -s 6.6.6.6:6666 is used, as part of the Shadowsocks configuration. It seems that only one TCP connection is selected each time, which means the same TCP connection is always used. Although MPTCP is supported, it doesn’t actually split into multiple subflows. I have configured MPTCP in the kernel to create two subflows, so I wanted to ask if there are any similar MPTCP-related cases, as this feature currently seems impossible to achieve.

![image](https://github.com/user-attachments/assets/2aaad884-8f09-4a42-990a-02055841fd22)

**Comment by zonyitoo** [comment]
sslocal establish new TCP connections to ssserver for every connections from clients. Each TCP sockets enables mptcp when created.

Did you enables `mptcp` in configuration or command line arguments?

**Comment by maojianyou** [comment]
> sslocal establish new TCP connections to ssserver for every connections from clients. Each TCP sockets enables mptcp when created.
> 
> Did you enable `mptcp` in configuration or command line arguments?

The parameters must have been added, otherwise there wouldn't be any stream information when using ip mptcp monitor. If MPTCP isn't enabled, there won't be any TCP stream information

```
Client A
./sslocal -s 6.6.6.6:12809 -k  -U -m none --protocol tun --tun-interface-name tun12 --tun-interface-address 172.16.67.1/24 -d --tcp-multipath --tcp-no-delay --tcp-fast-open

Server B
./ssserver -m none -s 6.6.6.6:12809 -k  -b 6.6.6.6 -U -d --tcp-multipath --tcp-no-delay --tcp-fast-open
```

![image](https://github.com/user-attachments/assets/baffb9d1-abcd-4e92-a0bd-cdfc251275cb)
![image](https://github.com/user-attachments/assets/36a45499-cf73-4831-b57c-67a8a3ddfe89)

Normally, there should be two TCP subflows, but currently, there is only one at 10.10.74.2. There should be another at 10.10.73.2, but it doesn't exist. So, it's unclear whether shadowsocks-rust is not invoking the subflow feature of the kernel's MPTCP.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/a4919d01cc86c9befe1e9cb915eb95239be5ffba/crates/shadowsocks/src/net/sys/unix/linux/mod.rs#L215-L226

What have to be done for client sockets for MPTCP for using the same TCP connection?

As far as I know, MPTCP on Linux only needs to set the proto parameter in the `socket` call to `IPPROTO_MPTCP`.

**Comment by maojianyou** [comment]
> https://github.com/shadowsocks/shadowsocks-rust/blob/a4919d01cc86c9befe1e9cb915eb95239be5ffba/crates/shadowsocks/src/net/sys/unix/linux/mod.rs#L215-L226
> 
> What have to be done for client sockets for MPTCP for using the same TCP connection?
> 
> As far as I know, MPTCP on Linux only needs to set the proto parameter in the `socket` call to `IPPROTO_MPTCP`.

I am testing the following setup:

A is the client, simulating a Windows user access scenario.
B is the sslocal (Shadowsocks local),
C is the ssserver (Shadowsocks server), meaning B and C together are like a client-server pair.
D is a website, which can be understood as an Nginx site.
In this setup, A and D do not support MPTCP, while B and C have kernel-level MPTCP support, allowing for multiple paths. The TCP flow from A goes to B through the shadowsocks-rust TUN tunnel, which is also configured to use MPTCP. In theory, the TCP flow from A to B should split into two subflows and reach C, where it should merge back into a single flow to D, achieving an MPTCP proxy.

I understand that shadowsocks-rust with MPTCP should work like this, but in my current tests, it's not functioning as expected. It might be that shadowsocks-rust is not fully compatible with MPTCP, causing this issue. I haven’t been able to verify it successfully. My requirement is to have B and C support MPTCP, so even if A and D don't, multiple subflows can still be used between B and C.

**Comment by zonyitoo** [comment]
The B -> C is achieved by the code piece I sent from the last comment, the key parameter is the protocol: `IPPROTO_MPTCP`.

I don't know what have to be done in code level to "fully compatible with MPTCP".

**Comment by zonyitoo** [comment]
There are some options like `ip mptcp limits set subflows 3` to control how many subflows that Path Manager could create. For many system the default subflows limit is `2`.

I think it should be an expected behavior in your case.

**Comment by maojianyou** [comment]
> There are some options like `ip mptcp limits set subflows 3` to control how many subflows that Path Manager could create. For many systems the default subflows limit is `2`.
> 
> I think it should be an expected behavior in your case.

I found the reason. It was because when I configured MPTCP, add_addr_accepted was set to 0 or 1, which actually refers to the number of interfaces. Thank you very much.
![image](https://github.com/user-attachments/assets/f4c1d548-a3ba-4303-880f-cabccd235111)
