### ISSUE TITLE
Implement `Debug` trait for `ProxyClientStream`

### ISSUE THREAD

**Issue by link2xt** [shadowsocks/shadowsocks-rust#1647]
`ProxyClientStream` does not implement `Debug` so I have to wrap it into another type here and pass `AsyncRead` and `AsyncWrite` through: https://github.com/deltachat/deltachat-core-rust/pull/5955

Generally I would prefer `missing_debug_implementations` lint to be enabled so all public APIs have `Debug` as dealing with missing `Debug` is usually difficult when someone wants to embed the type into a struct that derives `Debug`.

**Comment by zonyitoo** [comment]
Please consider submit a PR for this.
