### ISSUE TITLE
Can domain names in ACL work in local-tun mode?

### ISSUE THREAD

**Issue by mklnz** [shadowsocks/shadowsocks-rust#1648]
From what I understand when a route is added to be forwarded through the TUN device, the DNS resolution is separate so the TUN interface only gets src/dst IP addresses.

Does local-dns integrate with local TUN to provide some sort of DNS resolve cache?

**Comment by zonyitoo** [comment]
local-tun is just a tunnel that bypasses all received TCP/UDP packets to the remote target servers.

To achieve your requirements, possible solutions are:

1. local-tun handles DNS requests, for example, hijacks all packets destinated to port 53.
2. Create a fake DNS server listening on a specific IP, DNS requests send to this IP will be bypassed to a specific DNS resolver, and remember the resolved results. When packets were received from tun, check if it is in the previous DNS results.

A simple implementation of fake-dns was in the source tree: https://github.com/shadowsocks/shadowsocks-rust/tree/master/crates/shadowsocks-service/src/local/fake_dns , but I don't think it is production ready.

If you have any better idea, please submit a PR.

**Comment by mklnz** [comment]
Hmm yeah that's what I thought you'd have to do. Then there is also the problem of cache time etc. I'll have a think about it and see what the best way to implement it...

I feel this is better suited for local-dns? Since it already reads ACL rules correct?

**Comment by zonyitoo** [comment]
local-dns is a DNS server, which provide a service just like china-dns, choosing result by ACL rules from a local DNS and remote DNS.

**Comment by mklnz** [comment]
Actually does bypass ACLs work with local-tun mode even with IPs?
I just noticed bypassed connections do work and gives error spam (macOS):

Steps to reproduce:
```
./sslocal --version
shadowsocks 1.20.4

sudo ./sslocal -c config.json // configs below
sudo route add 1.1.1.1 10.255.0.1
sudo route add 8.8.8.8 10.255.0.1

dig +tcp google.com @8.8.8.8 // Going through proxy - no issue
;; ANSWER SECTION:
google.com.		37	IN	A	172.217.31.14

dig +tcp google.com @1.1.1.1 // Bypass
ERROR TCP tunnel failure, 10.255.0.1:58683 <-> 1.1.1.1:53, error: Connection refused (os error 61)
ERROR TCP tunnel failure, 10.255.0.1:58457 <-> 1.1.1.1:53, error: Can't assign requested address (os error 49)
ERROR TCP tunnel failure, 10.255.0.1:58461 <-> 1.1.1.1:53, error: Can't assign requested address (os error 49)
ERROR TCP tunnel failure, 10.255.0.1:58460 <-> 1.1.1.1:53, error: Can't assign requested address (os error 49)
ERROR TCP tunnel failure, 10.255.0.1:58352 <-> 1.1.1.1:53, error: Can't assign requested address (os error 49)
ERROR TCP tunnel failure, 10.255.0.1:58310 <-> 1.1.1.1:53, error: Can't assign requested address (os error 49)
```

I added some breakpoints in `shadowsocks_service/src/local/net/tcp/auto_proxy_stream.rs`
It seems to hit the correct functions
`AutoProxyClientStream::connect_proxied_with_opts` for 8.8.8.8
`AutoProxyClientStream::connect_bypassed_with_opts` -> for 1.1.1.1

So the ACL match is working, but any bypassed connections seem to get stuck in an error loop.

Configs:
`hosts.acl`
```
[bypass_all]

[proxy_list]
8.8.8.8
```

config.json
```
{
  "locals": [
    {
      "protocol": "tun",
      "mode": "tcp_and_udp",
      "tun_interface_address": "10.255.0.1/24",
      "outbound_bind_interface": "lo0", // Tried en0 (ethernet) too
      "acl": "./hosts.acl"
    }
  ],
  "servers": [
    {
      "server": "XXXXX",
      "server_port": 10000,
      "method": "2022-blake3-aes-128-gcm",
      "password": "XXXXX",
      "mode": "tcp_and_udp"
    }
  ]
}
```

**Comment by zonyitoo** [comment]
`outbound_bind_interface` is in the root level of the configuration JSON.

**Comment by mklnz** [comment]
Ah I see, that was a silly mistake. It seems what I'm looking for in terms of DNS is already working with local-dns.  After looking through the source code I can see `check_target_bypassed` already integrates with local-dns to use the cache for reverse IP lookup.

I can see after the first resolve of a hostname it adds to the cache and the next connection will be proxied so this issue can be closed.
Thanks for the help!
