### ISSUE TITLE
Multiple outbound interfaces support.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-rust#1657]
Hi, this is a feature request :)

Currently we can specify the outbound interface using `--outbound-bind-interface` or `outbound_bind_interface` in configuration, is that possible to specify multiple interfaces here? I have `enp3s0` and `wl0` on my device, and I use wired network but sometimes I use wireless also, I have to change the configuration to make it work, so I think support multiple interfaces here will be so great.

And yea, you may wanna say why just leave it empty to follow the route table, because I also have WireGuard on my device, and UDP connection sometimes may poor, and shadowsocks-rust have better performance for some applications that follow the system proxy settings, I don't want my shadowsocks-rust use WireGuard so.

Any help would be greatly appreciated!

**Comment by fernvenue** [comment]
By the way, I found out that gost-v3 have Multi-homed feature here: https://gost.run/en/tutorials/multi-homed, may can be an example? But it is writen by Golang.

**Comment by zonyitoo** [comment]
`SO_BINDTODEVICE` can only support 1 exactly interface name.

> I have `enp3s0` and `wl0` on my device, and I use wired network but sometimes I use wireless also, I have to change the configuration to make it work, so I think support multiple interfaces here will be so great.

It is hard to be done in the application level to know when you want to use another device.

You can make a script to generate a new configuration file and then restart the shadowsocks process.

**Comment by zonyitoo** [comment]
> By the way, I found out that gost-v3 have Multi-homed feature here: [gost.run/en/tutorials/multi-homed](https://gost.run/en/tutorials/multi-homed), may can be an example? But it is writen by Golang.

Well, from the document we can know how it was implemented:

> When a host is multi-homed host, different network exits can be specified for routes of different services as required.

It requires a "route" configuration. So there should be no differences if you can control your system's route table.

**Comment by fernvenue** [comment]
Hi @zonyitoo! Thanks for your reply and super clear explain!

> You can make a script to generate a new configuration file and then restart the shadowsocks process.

That's actually a great idea, I will give it a try.

> It requires a "route" configuration. So there should be no difference if you can control your system's route table.

Got it, thanks for the explain :)

**Comment by fernvenue** [comment]
I just closed this issue as not planned for now, and I will put any updates here such as the script or systemd example here when I finished tests.

**Comment by fernvenue** [comment]
In the end, I excluded server addresses using [WireGuard AllowedIPs Calculator](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/), problem solved :)
