### ISSUE TITLE
Does shadowsocks-rust support reuse_port as shadowsocks-libev?

### ISSUE THREAD

**Issue by ljw20180420** [shadowsocks/shadowsocks-rust#1667]
I find that sslocal --help does not have reuse-port option. Does shadowsocks-rust support reuse_port as shadowsocks-libev?

How can I use it in config file? Should I use "tcp_no_delay": true or "no-delay: true" in the config file?

Should I use "tcp_fast_open: true" or "fast_open: true" in config file?

Is it possible to set multiple server-urls in SIP002 (https://shadowsocks.org/doc/sip002.html) in config file?

Thanks.

**Comment by zonyitoo** [comment]
Why is that useful if sslocal in this project already support running on multi-core systems.

**Comment by ljw20180420** [comment]
Thank you. I will close this issue.
