### ISSUE TITLE
Mipsel is not working?

### ISSUE THREAD

**Issue by Naerotg3t** [shadowsocks/shadowsocks-rust#1671]
Can't install mipsel version, not have ipk and opkg install not working, please help, thx)

**Comment by zonyitoo** [comment]
You could cross compile one by yourself.

MIPS architecture is in Tier 3 of Rust's platform support. https://doc.rust-lang.org/beta/rustc/platform-support.html . So I removed it from the default release build this year.

> not have ipk and opkg install not working

You could build one with OpenWRT's SDK.
