### ISSUE TITLE
Fedora 40 Libsodium.20.23 not found but it's installed.

### ISSUE THREAD

**Issue by Wiserrhino** [shadowsocks/shadowsocks-rust#1676]
On a new install of Fedora 40 executing ss-server returns this error:
ss-server: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory

It is clearly installed here:
/usr/lib64/libsodium.so.23

But I have no idea how to tell ss-server it's location and I've scoured the internet for hours trying to find a fix that works for Fedora.

I'm in China, so I would really appreciate some help with this. I've successfully installed shadowsocks-electron through snap as a temporary fix, but the connection is intermittent. It craps out frequently and I'd like to get rid of it.

Thanks!

**Comment by AaronChen0** [comment]
You are using shadowsocks-libev. You should download executable [here](https://github.com/shadowsocks/shadowsocks-rust/releases/) for shadowsocks-rust.

**Comment by zonyitoo** [comment]
shadowsocks-rust doesn't need libsodium. And its binary name is not `ss-server`. What you are running is shadowsocks-libev, which is https://github.com/shadowsocks/shadowsocks-libev .

**Comment by Wiserrhino** [comment]
Thank you.
