### ISSUE TITLE
UDP relay 每次都会重新绑定一个新端口

### ISSUE THREAD

**Issue by gfreezy** [shadowsocks/shadowsocks-rust#168]
https://github.com/shadowsocks/shadowsocks-rust/blob/6f4f75466d7ed7ee4af5cec4246f2b552c44d42b/src/relay/udprelay/server.rs#L78

这里的代码写的，每次有一个 UDP 包，都会重新创建一个新 Socket，即使源端是同一个端口发送过来的包，经过代理，在目标服务器上不是一个来源端口。
这样会导致导致所有需要传输多个UDP包的协议都无效。

**Comment by zonyitoo** [comment]
嗯。以前写法上是使用同一个端口，但后来发现go版是这样子做的，就保持一致了。

**Comment by gfreezy** [comment]
这个有规范吗？ss server端这么处理，udp代理实际上并起不了啥作用？

**Comment by zonyitoo** [comment]
按我对SS的理解，UDP方面并没有规范。如果以最初的Python版为准的话，确实应该是使用单独一个端口来实现收/发包。

http://shadowsocks.org/en/spec/Protocol.html

这里并没有提到这块的实现规范。

**Comment by zonyitoo** [comment]
如果都用同一个端口进出，这样也会导致远端无法识别不同的情况，都混在一起？

**Comment by zonyitoo** [comment]
@gfreezy 可以试一下master分支，这个实现应该可以解决你的问题

**Comment by zonyitoo** [comment]
Already fixed in master branch. Will be released in `v1.8.0`.
