### ISSUE TITLE
How to proxy ssh connection

### ISSUE THREAD

**Issue by kigawas** [shadowsocks/shadowsocks-rust#169]
Cannot use `ProxyCommand` in ssh config
```
 Host *
   ProxyCommand connect-proxy -S 127.0.0.1:1080 %h %p
```

**Comment by zonyitoo** [comment]
https://superuser.com/questions/454210/how-can-i-use-ssh-with-a-socks-5-proxy

**Comment by kigawas** [comment]
I tried, but the connection cannot be established. It just stuck there

**Comment by kigawas** [comment]
Neither connect-proxy nor nc worked

**Comment by zonyitoo** [comment]
Have you confirmed that your proxy works?

```
curl --socks5-hostname 127.0.0.1:1080 http;//www.example.com -v
```

**Comment by kigawas** [comment]
Absolutely works. You can try connecting ssh via the socks5 proxy

**Comment by kigawas** [comment]
I'll close this since cannot reproduce it stably

**Comment by zonyitoo** [comment]
Hmm? It wasn't stably reproducible? I will try it tonight.
