### ISSUE TITLE
error: could not compile `shadowsocks-rust` (bin "ssservice")

### ISSUE THREAD

**Issue by MMHackMM** [shadowsocks/shadowsocks-rust#1705]
Ubuntu24.04 and Ubuntu22.04
RAM：2G
CPU：2c  

 Compiling xdg v2.5.2
   Compiling qrcode v0.14.1
   Compiling shadowsocks-rust v1.21.0
    Building [=======================> ] 305/310: ssservice(bin), sslocal(bin)                                                          

error: could not compile `shadowsocks-rust` (bin "ssservice")

Caused by:
  process didn't exit successfully: `/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name ssservice --edition=2021 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/shadowsocks-rust-1.21.0/bin/ssservice.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=138 --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 --cfg 'feature="aead-cipher-2022"' --cfg 'feature="default"' --cfg 'feature="hickory-dns"' --cfg 'feature="local"' --cfg 'feature="local-http"' --cfg 'feature="local-socks4"' --cfg 'feature="local-tunnel"' --cfg 'feature="log4rs"' --cfg 'feature="logging"' --cfg 'feature="manager"' --cfg 'feature="multi-threaded"' --cfg 'feature="qrcode"' --cfg 'feature="server"' --cfg 'feature="service"' --cfg 'feature="time"' --cfg 'feature="tracing"' --cfg 'feature="tracing-subscriber"' --cfg 'feature="utility"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("aead-cipher-2022", "aead-cipher-2022-extra", "aead-cipher-extra", "basic", "default", "dns-over-h3", "dns-over-https", "dns-over-native-tls", "dns-over-native-tls-vendored", "dns-over-tls", "full", "full-extra", "hickory-dns", "ipnet", "jemalloc", "jemallocator", "local", "local-dns", "local-fake-dns", "local-flow-stat", "local-http", "local-http-native-tls", "local-http-native-tls-vendored", "local-http-rustls", "local-online-config", "local-redir", "local-socks4", "local-tun", "local-tunnel", "log4rs", "logging", "manager", "mimalloc", "mime", "multi-threaded", "qrcode", "replay-attack-detect", "reqwest", "rpmalloc", "security-replay-attack-detect", "server", "service", "snmalloc", "snmalloc-rs", "stream-cipher", "tcmalloc", "tcmalloc-vendored", "time", "tracing", "tracing-subscriber", "trust-dns", "utility", "utility-url-outline", "windows-service", "winservice"))' -C metadata=b8228d6c7ca4f272 -C extra-filename=-b8228d6c7ca4f272 --out-dir /tmp/cargo-installDW65Kx/release/deps -C strip=symbols -L dependency=/tmp/cargo-installDW65Kx/release/deps --extern base64=/tmp/cargo-installDW65Kx/release/deps/libbase64-c63472cdfad0affb.rlib --extern build_time=/tmp/cargo-installDW65Kx/release/deps/libbuild_time-074971020f20a22b.so --extern cfg_if=/tmp/cargo-installDW65Kx/release/deps/libcfg_if-55f97daabd256f61.rlib --extern clap=/tmp/cargo-installDW65Kx/release/deps/libclap-d79e49e980777416.rlib --extern daemonize=/tmp/cargo-installDW65Kx/release/deps/libdaemonize-747eb71cbc03aaf1.rlib --extern directories=/tmp/cargo-installDW65Kx/release/deps/libdirectories-a54a06c9cefed40f.rlib --extern futures=/tmp/cargo-installDW65Kx/release/deps/libfutures-f37050135a2d3708.rlib --extern json5=/tmp/cargo-installDW65Kx/release/deps/libjson5-3a6755a68b3923c4.rlib --extern libc=/tmp/cargo-installDW65Kx/release/deps/liblibc-266350ee2b65c32d.rlib --extern log=/tmp/cargo-installDW65Kx/release/deps/liblog-e75f4412884ba21b.rlib --extern log4rs=/tmp/cargo-installDW65Kx/release/deps/liblog4rs-e535891aba62c0ea.rlib --extern qrcode=/tmp/cargo-installDW65Kx/release/deps/libqrcode-2145cce8c542a4fa.rlib --extern rand=/tmp/cargo-installDW65Kx/release/deps/librand-cd2c83089cb7bba6.rlib --extern rpassword=/tmp/cargo-installDW65Kx/release/deps/librpassword-6a8750100da968da.rlib --extern serde=/tmp/cargo-installDW65Kx/release/deps/libserde-84f524451a1fbb7e.rlib --extern shadowsocks_rust=/tmp/cargo-installDW65Kx/release/deps/libshadowsocks_rust-167589d05cb8508e.rlib --extern shadowsocks_service=/tmp/cargo-installDW65Kx/release/deps/libshadowsocks_service-6b11b0fdd64d1164.rlib --extern sysexits=/tmp/cargo-installDW65Kx/release/deps/libsysexits-56fec4157e9f44b4.rlib --extern thiserror=/tmp/cargo-installDW65Kx/release/deps/libthiserror-e780b83db77dcd6a.rlib --extern time=/tmp/cargo-installDW65Kx/release/deps/libtime-23cd9e0736f6a8e5.rlib --extern tokio=/tmp/cargo-installDW65Kx/release/deps/libtokio-d9cde03178bd8da7.rlib --extern tracing=/tmp/cargo-installDW65Kx/release/deps/libtracing-847132ffbd1d14fe.rlib --extern tracing_subscriber=/tmp/cargo-installDW65Kx/release/deps/libtracing_subscriber-a9b6d52a9a6295a2.rlib --extern xdg=/tmp/cargo-installDW65Kx/release/deps/libxdg-bd4b85cb78efb17e.rlib --cap-lints allow -L native=/tmp/cargo-installDW65Kx/release/build/blake3-9c9e32799b2f9cbf/out -L native=/tmp/cargo-installDW65Kx/release/build/blake3-9c9e32799b2f9cbf/out -L native=/tmp/cargo-installDW65Kx/release/build/ring-1c0e4f6e306e847f/out` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
    Building [=======================> ] 306/310: sslocal(bin)                                                                          

error: failed to compile `shadowsocks-rust v1.21.0`, intermediate artifacts can be found at `/tmp/cargo-installDW65Kx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by MMHackMM** [comment]
MiB Mem :   1966.8 total
Is it because the memory is too small?

**Comment by zonyitoo** [comment]
Probably yes.
