### ISSUE TITLE
shadowsock client does not update the server ip after connection

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [shadowsocks/shadowsocks-rust#1709]
Hi! I have a dynamic white address using the name no-ip.com 
I noticed that after changing the ip address, the connection does not resume. 
The IP address may not be being updated / resolving of host name.

**Comment by zonyitoo** [comment]
What do you mean "white address"? Could you give me an example about your configuration.

**Comment by Yrij-Zhavoronkov** [comment]
> What do you mean "white address"? Could you give me an example about your configuration.

white IP == public IP (not for NAT)

```
{
    "server":"myhost.ddns.net",
    "server_port": 8388,
    "password":"myPassword",
    "mode": "udp_only",
    "method":"chacha20-ietf-poly1305",
    "locals": [
        {
        "local_address": "127.0.0.1",
        "local_port": 1080,
        "forward_address": "127.0.0.1",
        "forward_port": 51820,
        "protocol": "tunnel"
        }
    ]
}
```

**Comment by zonyitoo** [comment]
If I understand correctly, when the IP of `myhost.ddns.net` changed, `sslocal`:

1. Current active connections were still holding, so it remain connected to the original IP of `myhost.ddns.net`
2. New connections were trying to connect to the original IP of `myhost.ddns.net`

The 1. is an expected behavior, the `"server"`'s domain name is resolved when tunnel is establishing, but the 2. is not. You could first verify if your local DNS server have already updated the correct IP of `myhost.ddns.net`, for example, `dig myhost.ddns.net`.

**Comment by Yrij-Zhavoronkov** [comment]
Understood you. Then it turns out that in its current form it will not be possible to use it in the script: started, left the remote PC, connected when needed (possibly after a long period of time)

**Comment by zonyitoo** [comment]
It should work. Because if your IP was actually changed, the current active connections will be aborted, because the destination server have already gone. So there should be no problem.

**Comment by Yrij-Zhavoronkov** [comment]
The question is not about the topic of the problem, but about the project. Given that you understand it, you will be able to answer for sure.
Is it possible to organize a tunnel using the library alone so that, say, an RDP session to the client can be established from the server?

**Comment by zonyitoo** [comment]
Establish a RDP session to the client from server? So what you want is:

```
RDPClient -> sssserver -> sslocal -> RDPServer
```

No. As you can see the name of `ssserver` and `sslocal`, they are components of a CLIENT-SERVER architecture, which means that connections must be created from `sslocal` to `ssserver`, but not the opposite.

But I do think there are another solution, for example:

1. Launch a `ssserver` with `RDPServer`, `RDPClient` connects to a `sslocal`.
2. Create a connection from the machine running `sslocal` and `RDPServer` to the one running `ssserver` and `RDPClient`, and then open RDP session through the connected session.

**Comment by Yrij-Zhavoronkov** [comment]
Maybe I don't understand English well.

I didn't quite understand the first scheme / I'm not sure what will happen since the RDP Server does not have a public ip that could be accessed via the Internet.

The second scheme will look approximately the way I wanted, I will ask you to visualize it.

PC (RDP-server with gray IP / NAT, ss local) -> PC (RDP-client, server, public dynamic IP)
right? In this case I still don't understand how I can access the RDP server from the ssserver, because I need an ip/port, and I do not know what it will be

**Comment by Yrij-Zhavoronkov** [comment]
> I renamed your PC to PC1 and PC2. So let me clearify your issue: What you want is to RDC access from PC2 to PC1, right? Because PC1 is the RDP-server, and PC2 is the RDP-client.

Yes. 

> Do you have control of the NAT network?

No, I don't have access to the PC1 network settings.

If we go back to the configuration of the original question, then this is the configuration for Wireguard
So the current solution looks something like this:

PC1 (RDP-server with grey IP / NET, ss local, wireguard) ->   local.tunnel 1080:51820 -> PC2 (RDP-client, server, wireguard, public dynamic IP)

The reason why I asked about the possibilities was that I hoped that it was possible to get a direct tunnel with some specific port from both PC1 and PC2 server sides, so that without additional funds (Mr. wireguard) I could establish an RDP session.

I'm sorry if I just wasted your time.

**Comment by zonyitoo** [comment]
Hmm, may be your setting is the best already.
