### ISSUE TITLE
Connection Throw error: copy bidirection ends with error: unexpected end of file

### ISSUE THREAD

**Issue by liangpure** [shadowsocks/shadowsocks-rust#1711]
Client Version: 1.21.0
Server: Ubuntu 20.0.4

Recently, I have been experiencing a connection error. The error message is as follows: **"tokio-runtime-worker ThreadId(21) shadowsocks::relay::tcprelay::utils: copy bidirection ends with error: unexpected end of file, a_to_b: Running(CopyBuffer { read_done: false, pos: 0, cap: 0, amt: 0, .. }), b_to_a: Done(0)"**

My service was working fine from April to September this year, but it is not working now. I suspect that the GFW may have interfered with the SS TCP stream.

What's strange is that I can use SS connection with a 4G phone network, but not with Ethernet, and I can access my server normally via both of them.

Is there anyone else experiencing this similar issue, maybe we can discuss it here

**Comment by zonyitoo** [comment]
The error indicated that a TCP connection was ended with EOF before the server received a full shadowsocks packet. You may have to make more tests for evidences.
