### ISSUE TITLE
UDP traffic not flowing

### ISSUE THREAD

**Issue by sgp729** [shadowsocks/shadowsocks-rust#1712]
I launch local proxy server with:
```bash
$ sslocal -U -b 127.0.0.1:9050 --server-url "ss://.../?outline=1"
INFO shadowsocks local 1.21.0 build 2024-09-22T18:06:17.170776391+00:00
INFO shadowsocks socks TCP listening on 127.0.0.1:9050  
INFO shadowsocks socks5 UDP listening on 127.0.0.1:9050
```
and configure firefox to use the proxy server, it fails to send UDP packets at all.
[Livekit WebRTC test](https://livekit.io/webrtc/browser-test) reports that there are no UDP ICE candidates:
```
Error: No public UDP candidates were found. This likely means your network is blocking STUN lookups.
```
However I'm sure that the proxy server allows UDP traffic and STUN lookup.

Examining traffic with wireshark shows that there are 0 UDP packets sent to proxy and only TCP are being sent:
```
ip.dst == proxy_ip:port and udp
    Displayed: 0
```
I wonder if this is even a proxy issue, maybe I'm missing something completely unrelated to shadowsocks...
Additional info, if it can be useful:
```bash
$ uname -omr
6.11.2-arch1-1 x86_64 GNU/Linux
```
```bash
$ doas iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

**Comment by AaronChen0** [comment]
SOCKS5 proxies can theoretically handle both TCP and UDP, but Firefox only supports TCP connections over SOCKS. And the same for chromium browsers.
