### ISSUE TITLE
Docker version is not working for me

### ISSUE THREAD

**Issue by Comandante1977** [shadowsocks/shadowsocks-rust#1723]
Hi!
My configs:

Server's config.json
{
    "server": "0.0.0.0",
    "server_port":8388,
    "password":"pass",
    "timeout":300,
    "method":"aes-256-gcm",
    "ipv6_first":false,
    "mode":"tcp_and_udp"
}

Servers docker-compose.yml
version: "3.7"

networks:
  ss:
    enable_ipv6: false
    ipam:
     driver: default

services:
  shadowsocks:
     image: ghcr.io/shadowsocks/ssserver-rust:latest
     container_name: shadowsocks
     networks:
      - ss
     cap_add:
      - NET_ADMIN
      - SYS_MODULE

     volumes:
        - /root/shadowsocks/conf/config.json:/etc/shadowsocks-rust/config.json
     ports:
        - 12005:8388/tcp
        - 12005:8388/udp
     restart: unless-stopped

Client's config.json 
{
    "server": "ip",
    "mode":"tcp_and_udp",
    "server_port":12005,
    "local_port":1080,
    "password":"pass",
    "timeout":60,
    "method":"aes-256-gcm"
}

Error on client
2024-10-20T19:02:01.673113663+03:00 ERROR socks5 tcp client handler error: connect ip:12005 timeout

Firewall rules are good on server.

Where is the problem?

IPv6 enabled on server and docker, but there is no IPv6 on client.

**Comment by Comandante1977** [comment]
UPD. tried on other servers with fresh docker installation and everything works fine there. It seems that smth went wrong on my test server with docker routing etc. Dont know what at this moment )))

**Comment by zonyitoo** [comment]
> 2024-10-20T19:02:01.673113663+03:00 ERROR socks5 tcp client handler error: connect ip:12005 timeout

There must be a route problem in the docker for `ip`. You could try with `telnet ip 12005` inside your container to verify if it actually works.
