### ISSUE TITLE
sswindows failed to start

### ISSUE THREAD

**Issue by bthulu** [shadowsocks/shadowsocks-rust#1736]
![image](https://github.com/user-attachments/assets/ad4489f4-4166-46cc-b1c8-665cc9b86b20)

**Comment by zonyitoo** [comment]
`sswinservice` is for running as a [Windows Service](https://learn.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications), which is not for launching directly. If you want to launch it directly from console, use the `ssservice` binary instead.
