### ISSUE TITLE
Performance regression after switching to tokio-0.2

### ISSUE THREAD

**Issue by cg31** [shadowsocks/shadowsocks-rust#174]
I tried to use go-shadowsocks2 as tunnel to have a test, the result doesn't look great...

It was shadowsocks-rust-async branch release build I was using in this test.

This is what I did:
1. start shadowsocks-rust server:
ssserver -s 127.0.0.1:8488 -m chacha20-ietf -k password

2. start go-shadowsocks2 as tunnel:
go-shadowsocks2 -verbose -c ss://chacha20-ietf:password@localhost:8488 -tcptun :1090=127.0.0.1:5201

3. start iperf server:
iperf -s -p 5201

4. run iperf as client:
iperf -c localhost -p 1090 -n 10G

The result was:
[388]  0.0-130.7 sec  10.0 GBytes   657 Mbits/sec

If I replaced step 1 with go-shadowsocks2 as server:
go-shadowsocks2 -verbose -s ss://chacha20-ietf:password@:8488

The result was:
[384]  0.0-27.4 sec  10.0 GBytes  3.13 Gbits/sec

**Comment by zonyitoo** [comment]
I have seen many complains about performance regression after migrating to tokio v0.2.

Let's findout if there are any things could be optimized in this project first.

**Comment by cg31** [comment]
I just tried the master branch, it looks like also needed some optimization
[384]  0.0-89.2 sec  10.0 GBytes   963 Mbits/sec

This is where a tunnel is useful.

For the record, I am using stable-x86_64-pc-windows-msvc,  rustc 1.39.0.

**Comment by zonyitoo** [comment]
`master` branch is using future v0.1, which requires lots of `Future`s' transformation, that should be slower.

**Comment by zonyitoo** [comment]
I didn't see any obvious performance problem on the `feature-migrate-async-await` branch. Any idea?

**Comment by cg31** [comment]
It is hard to spot the bottleneck just by looking at the code. Profiling tools are needed to find the hot spots.

**Comment by zonyitoo** [comment]
My test with the lastest commit (with tokio v0.2.2)

System
```
Darwin 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

TEST-1:

```
iperf -> sstunnel (rust) -> go-shadowsocks2 -> iperf

------------------------------------------------------------
Client connecting to localhost, TCP port 1300
TCP window size:  344 KByte (default)
------------------------------------------------------------
[  5] local 127.0.0.1 port 56597 connected with 127.0.0.1 port 1300
write failed: Broken pipe
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-10.0 sec  2.92 GBytes  2.50 Gbits/sec
```

TEST-2

```
iperf -> sstunnel (rust) -> ssserver (rust) -> iperf

------------------------------------------------------------
Client connecting to localhost, TCP port 1300
TCP window size:  400 KByte (default)
------------------------------------------------------------
[  5] local 127.0.0.1 port 56763 connected with 127.0.0.1 port 1300
write failed: Broken pipe
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-10.0 sec  3.60 GBytes  3.09 Gbits/sec
```

Well, it is actually a lot faster than Go's version.

**Comment by cg31** [comment]
Maybe it is related to OS?

Could you use "-n 10G" to iperf? So we can compare to the result with the result on Windows?

**Comment by zonyitoo** [comment]
I have already use `-n 10G` on `iperf`.

**Comment by zonyitoo** [comment]
TEST-1:

```
iperf -> sstunnel (rust) -> go-shadowsocks2 -> iperf

[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-11.6 sec  10.0 GBytes  7.39 Gbits/sec
```

TEST-2:

```
iperf -> sstunnel (rust) -> ssserver (rust) -> iperf

[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-12.6 sec  10.0 GBytes  6.80 Gbits/sec
```

**Comment by zonyitoo** [comment]
Another test pairs:

TEST-1:

```
iperf -> sstunnel (rust) -> go-shadowsocks2 -> iperf

[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-37.5 sec  10.0 GBytes  2.29 Gbits/sec
```

TEST-2:

```
iperf -> sstunnel (rust) -> ssserver (rust) -> iperf

[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-29.2 sec  10.0 GBytes  2.95 Gbits/sec
```

Result is not stable.

**Comment by cg31** [comment]
It could be a Windows specific issue, maybe in rust compiler or in  libraries, if we can get a good performance on Linux as well.

**Comment by cg31** [comment]
I just tried rust and go version on my Linux box, it is a ThinkStation with 56 cores.

Rust version uses plain method, and go version uses dummy method.

Rust version gets:
[  3]  0.0-14.3 sec  10.0 GBytes  6.01 Gbits/sec

Go version is incredible:
[  3]  0.0- 3.9 sec  10.0 GBytes  22.1 Gbits/sec

**Comment by zonyitoo** [comment]
Hmm.. nearly 4 times.

In this test, I don't think the number of cores of CPU is important, because it has only one connection. So I think the key is task scheduler's performance.

**Comment by cg31** [comment]
When I test the proxy sample: https://github.com/tokio-rs/tokio/blob/master/examples/proxy.rs

in these steps:
./proxy 127.0.0.1:1090 127.0.0.1:5201 &
iperf -s -p 5201 &
iperf -c 127.0.0.1 -p 1090 -n 10G

I got:
[  3]  0.0-13.4 sec  10.0 GBytes  6.40 Gbits/sec

it is similar to ss-rust. It means the bottleneck is not in ss-rust itself, but in tokio.

**Comment by cg31** [comment]
I created a repo with go and rust tests to benchmark the relay speeds
https://github.com/cg31/PerfectRelay

**Comment by cg31** [comment]
I tried to use std::net to relay the data, it looks just faster:
https://github.com/cg31/PerfectRelay/tree/master/rust_std

**Comment by zonyitoo** [comment]
> I tried to use std::net to relay the data, it looks just faster:
> https://github.com/cg31/PerfectRelay/tree/master/rust_std

That means the problem is in tokio's scheduler.

**Comment by cg31** [comment]
async-std is faster than tokio, but still a lot slower than std:
https://github.com/cg31/PerfectRelay/tree/master/rust_async_std

On Windows 10, i7 machine:

tokio:
[264]  0.0-78.5 sec  10.0 GBytes  1.09 Gbits/sec

async-std:
[268]  0.0-29.9 sec  10.0 GBytes  2.87 Gbits/se

std:
[272]  0.0- 9.3 sec  10.0 GBytes  9.24 Gbits/sec

**Comment by zyctree** [comment]
add `BufReader` and `BufWriter` will help
`BufReader` can be added directly
```rust
let mut ri = tokio::io::BufReader::new(ri);
let mut ro = tokio::io::BufReader::new(ro);
```
`BufWriter` need to work with `poll_flush`

**Comment by zyctree** [comment]
here is my result of https://github.com/cg31/PerfectRelay/tree/master/rust_async_std

```txt
# without BufReader
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-11.8 sec  10.0 GBytes  7.26 Gbits/sec

# with BufReader
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 9.2 sec  10.0 GBytes  9.34 Gbits/sec
```

**Comment by zonyitoo** [comment]
Readers are already built with a buffer (for instance, [`aead.rs`](https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/relay/tcprelay/aead.rs#L63-L71)).

**Comment by cg31** [comment]
A BufReader and also a BufWriter did the trick.

# without BufReader and BufWriter https://github.com/cg31/PerfectRelay/tree/master/rust_tokio
[384]  0.0-101.1 sec  10.0 GBytes   850 Mbits/sec

# only using BufReader 
[384]  0.0-93.3 sec  10.0 GBytes   921 Mbits/sec

# using both  BufReader and also a BufWriter https://github.com/cg31/PerfectRelay/tree/master/rust_tokio_buf
[384]  0.0-30.5 sec  10.0 GBytes  2.82 Gbits/sec

**Comment by clementhk** [comment]
I ran this test with latest release vs go-shadowsocks2 under Debian stable, here's the result.

shadowsocks-rust
```
[  3]  0.0-21.3 sec  10.0 GBytes  4.04 Gbits/sec
[  3]  0.0-20.9 sec  10.0 GBytes  4.12 Gbits/sec
[  3]  0.0-21.0 sec  10.0 GBytes  4.09 Gbits/sec
```

go-shadowsocks2
```
[  3]  0.0-12.4 sec  10.0 GBytes  6.92 Gbits/sec
[  3]  0.0-14.0 sec  10.0 GBytes  6.14 Gbits/sec
[  3]  0.0-13.6 sec  10.0 GBytes  6.29 Gbits/sec
```

**Comment by clementhk** [comment]
Here's something interesting for RPi users.

shadowsocks-rust server + go-shadowsocks2 client
```
[  3]  0.0-283.5 sec  5.60 GBytes   170 Mbits/sec
[  3]  0.0-50.5 sec  1.00 GBytes   170 Mbits/sec
```

go-shadowsocks2 server + go-shadowsocks2 client
```
[  3]  0.0-52.0 sec  1.00 GBytes   165 Mbits/sec
[  3]  0.0-51.8 sec  1.00 GBytes   166 Mbits/sec
```

shadowsocks-rust server + shadowsocks-rust client
```
[  3]  0.0-13.4 sec  1.00 GBytes   641 Mbits/sec
[  3]  0.0-13.8 sec  1.00 GBytes   625 Mbits/sec
[  3]  0.0-13.5 sec  1.00 GBytes   635 Mbits/sec
```

**Comment by clementhk** [comment]
@zonyitoo shall we keep this issue open and pin it for discussing performance and for people to post benchmark results?

**Comment by zonyitoo** [comment]
Sure.

**Comment by zonyitoo** [comment]
So your data result is: on x86_64 platform, ss-rust 4GiB/sec slower than ss-go2 6GiB/sec, but on RPi (ARM), ss-rust is faster.

**Comment by quininer** [comment]
We can first enable some general optimization options, such as using [`jemallocator`](https://docs.rs/jemallocator/0.3.2/jemallocator/) and [tokio's `parking_lot` feature](https://docs.rs/tokio/0.2.21/tokio/#internal-features).

**Comment by zonyitoo** [comment]
jemalloc may increase binary size, which is not good for embedded environments.

**Comment by quininer** [comment]
we don't need to enable it by default, and at least on desktop and server we don't need to worry about binary size.

**Comment by clementhk** [comment]
> jemalloc may increase binary size, which is not good for embedded environments.

Do you know what size and performance difference?

**Comment by zonyitoo** [comment]
Rust is currently uses system's memory allocator by default, which may not be optimized for concurrent programs. jemalloc or tcmalloc will perform better in multithread programs.

As for `parking_lot` feature, I don't know much about it.

**Comment by clementhk** [comment]
jemalloc test result on RPi4 (not overclocked)

system memory allocator
```
-rwxr-xr-x 1 root root 7.5M Jun  9 13:10 sslocal
-rwxr-xr-x 1 root root 5.3M Jun  9 13:10 ssserver
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24846
[  4]  0.0-13.7 sec  1.00 GBytes   627 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24852
[  4]  0.0-13.7 sec  1.00 GBytes   626 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24858
[  4]  0.0-13.6 sec  1.00 GBytes   632 Mbits/sec
```


jemalloc
```
-rwxr-xr-x 1 root root  12M Jun  9 12:59 sslocal
-rwxr-xr-x 1 root root 9.1M Jun  9 12:45 ssserver
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24828
[  4]  0.0-12.8 sec  1.00 GBytes   669 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24834
[  4]  0.0-12.7 sec  1.00 GBytes   677 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 24840
[  4]  0.0-12.8 sec  1.00 GBytes   670 Mbits/sec
```

It's about 10% improvement

**Comment by clementhk** [comment]
Under Debian stable x86_64 there's no performance improvement.

system
```
-rwxr-xr-x  1 root root 5.6M Jun  9 08:39 ssserver
-rwxr-xr-x  1 root root 7.7M Jun  9 08:39 sslocal
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33278
[  4]  0.0-25.9 sec  10.0 GBytes  3.32 Gbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33290
[  4]  0.0-26.1 sec  10.0 GBytes  3.29 Gbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33308
[  4]  0.0-25.3 sec  10.0 GBytes  3.40 Gbits/sec
```


jemalloc
```
-rwxr-xr-x  1 root root  11M Jun  9 08:45 ssserver
-rwxr-xr-x  1 root root  13M Jun  9 08:45 sslocal
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33324
[  4]  0.0-26.3 sec  10.0 GBytes  3.27 Gbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33366
[  4]  0.0-26.2 sec  10.0 GBytes  3.28 Gbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 33384
[  4]  0.0-25.9 sec  10.0 GBytes  3.32 Gbits/sec
```

**Comment by clementhk** [comment]
jemalloc test result on RPi4 (overclocked)

system memory allocator
??

jemalloc
```
-rwxr-xr-x 1 root root  12M Jun  9 12:59 sslocal
-rwxr-xr-x 1 root root 9.1M Jun  9 12:45 ssserver
[  4]  0.0- 9.3 sec  1.00 GBytes   928 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 22660
[  4]  0.0- 9.0 sec  1.00 GBytes   950 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 22666
[  4]  0.0- 9.4 sec  1.00 GBytes   915 Mbits/sec
[  4] local 127.0.0.1 port 5201 connected with 127.0.0.1 port 22672
[  4]  0.0- 9.1 sec  1.00 GBytes   948 Mbits/sec
```

**Comment by zonyitoo** [comment]
Why not try again with aes-gcm with hardware accleration?

**Comment by clementhk** [comment]
@zonyitoo let me know when parking_lot is ready, I'll do a benchmark.

**Comment by zonyitoo** [comment]
It is already enabled by default in master branch.

I don't think it can improve performance significantly.

**Comment by quininer** [comment]
@clementhk  Can you record flamegraph? It can be done easily using the [flamegraph](https://github.com/flamegraph-rs/flamegraph) tool.

**Comment by clementhk** [comment]
> It is already enabled by default in master branch.
> 
> I don't think it can improve performance significantly.

You're right, it's ~10% improvement with 32 bit arm, but ~1% with arm64 and amd64.
I've migrated my shadowsocks server to arm64.



> @clementhk Can you record flamegraph? It can be done easily using the [flamegraph](https://github.com/flamegraph-rs/flamegraph) and [not-perf](https://github.com/koute/not-perf) tool.

I can do it this weekend.
