### ISSUE TITLE
`sslocal` does not respect `locals[].protocol`

### ISSUE THREAD

**Issue by alaz** [shadowsocks/shadowsocks-rust#1764]
Hi,

Regardless of the `protocol` field set in the `locals` section and `socks5_auth_config_path` being present, `shadowsocks-rust` accepts HTTP proxy connections without authentication:

`config.json`:

```json
{
    "locals": [
        {
            "protocol": "socks",
            "local_address": "127.0.0.1",
            "local_port": 9090,
            "socks5_auth_config_path": "auth.json"
        }
    ],

    "servers": [
        {...}
    ],
}
```

`auth.json`:

```json
{
    "password": {
        "users": [
            {
                "user_name": "user",
                "password": "password"
            }
        ]
    }
}
```

Tests:

```sh
$ curl -si --proxy socks5://127.0.0.1:9090 -U user:password https://api.seeip.org | head
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 10 Nov 2024 10:21:39 GMT
Content-Type: text/plain
Content-Length: 14
Connection: keep-alive
Cache-Control: no-cache
```

```sh
$ curl -i --proxy socks5://127.0.0.1:9090 -U user:pass https://api.seeip.org 
curl: (97) User was rejected by the SOCKS5 server (1 255).
```

```sh
$ curl -si --proxy http://127.0.0.1:9090 -U us:pass https://api.seeip.org | head
HTTP/1.1 200 OK
Date: Sun, 10 Nov 2024 10:22:43 GMT

HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 10 Nov 2024 10:22:43 GMT
Content-Type: text/plain
Content-Length: 14
Connection: keep-alive
Cache-Control: no-cache
```

**Comment by zonyitoo** [comment]
This is because the `socks` protocol also supports `http` proxy protocol implicitly. It also supports socks4/4a, too.

Protocol http and socks4/4a didn’t implement authentication right now.

It is a problem that would allow user to bypass socks5 authentication by using http or socks4/4a.

Maybe we should disable http, socks4/4a on `socks` protocol when socks5 authentication is enabled?

**Comment by alaz** [comment]
Hi, thank you for the details. Yes, I agree that this implicit behaviour is a security problem.

I think the easiest and most backward compatible solution would be to introduce `socks5` variant for `protocol`, that does not support `http` or `socks4` implicitly.

**Comment by alaz** [comment]
Looking at the code,

> Maybe we should disable http, socks4/4a on socks protocol when socks5 authentication is enabled?

This approach looks more straightforward to implement.

I do not have a strong opinion. Anything will do, as SOCKS5 authentication makes little sense at the moment.
