### ISSUE TITLE
sstunnel 的使用场景

### ISSUE THREAD

**Issue by bukede** [shadowsocks/shadowsocks-rust#177]
如题，什么情况下会用到 sstunnel 呢 ?

**Comment by cg31** [comment]
开发时用作性能测试是最重要的应用。

实际使用时，如果你有多个server也可以做接力，比如这个  https://www.m690.com/archives/1000/

**Comment by zonyitoo** [comment]
看了一下文章，讲的方法是

```
sslocal -> (sstunnel -> ssserver) -> ssserver
```

其中`sstunnel`跑在`GATE_CHINA`上，两个`ssserver`是同一个进程。

主要的优势是可以在国内搭一个节点，避免直连国外的`ssserver`。文中提到的提供给多人使用在本项目中并不需要，直接同一个`ssserver`就可以同时监听多个端口。

**Comment by cg31** [comment]
还有个优势是tunnel很“干净”，在接力过程中

sslocal <=> sstunnel1 <=> ... <=> sstunnelN  <=> sstserver

tunnel不需要访问sslocal要访问的目标网站。

**Comment by bukede** [comment]
sslocal -> (sstunnel -> ssserver) -> ssserver
