### ISSUE TITLE
Panic on parsing server config URLs

### ISSUE THREAD

**Issue by link2xt** [shadowsocks/shadowsocks-rust#1770]
There are multiple places where parsing server config from URL or just trying to parse a password panics and crashes the whole application using the library.

https://github.com/shadowsocks/shadowsocks-rust/blob/c52b77d1123a55cf8f60842ea92a156cda57ce34/crates/shadowsocks/src/config.rs#L436-L442

https://github.com/shadowsocks/shadowsocks-rust/blob/c52b77d1123a55cf8f60842ea92a156cda57ce34/crates/shadowsocks/src/config.rs#L447
(triggered by `ServerConfig::from_url("ss://2022-blake3-aes-128-gcm:XYZ@127.0.0.1:9999")`)

https://github.com/shadowsocks/shadowsocks-rust/blob/c52b77d1123a55cf8f60842ea92a156cda57ce34/crates/shadowsocks/src/config.rs#L518

https://github.com/shadowsocks/shadowsocks-rust/blob/c52b77d1123a55cf8f60842ea92a156cda57ce34/crates/shadowsocks/src/config.rs#L529

One of the cases was fixed in https://github.com/shadowsocks/shadowsocks-rust/pull/1762

**Comment by zonyitoo** [comment]
It shouldn't fail. It would always be `Some(..)`.
