### ISSUE TITLE
build/build-release 脚本的兼容性

### ISSUE THREAD

**Issue by bukede** [shadowsocks/shadowsocks-rust#178]
在 ubuntu 18.04 下运行 build/build-release 提示
./build/build-release: 9: ./build/build-release: Syntax error: "(" unexpected

该脚本只适用于 macOS 吗？

**Comment by zonyitoo** [comment]
我试了一下用`zsh`, `bash`跑都没问题呀

**Comment by bukede** [comment]
之前还会报
