### ISSUE TITLE
Configuration option to allow IP fragmentation on outbound UDP sockets in ssserver

### ISSUE THREAD

**Issue by tom-ryan** [shadowsocks/shadowsocks-rust#1780]
Hello! I have a use case where outbound UDP traffic from ssserver sometimes needs to traverse a network with a smaller MTU. Unfortunately I don't have control over the network or the application sending the traffic.

I saw that per previous issues on this project, IP fragmentation was disabled to improve performance. For my use case, it's preferable to allow IP fragmentation / accept the performance overhead.

I tested that by commenting out the following lines, UDP traffic was fragmented as expected: 
https://github.com/shadowsocks/shadowsocks-rust/blob/e791f233f7848d6c9f2a99b0794986d0cddb6c79/crates/shadowsocks/src/net/sys/unix/linux/mod.rs#L313-L315

What do you think about adding a new configuration option in ssserver like `allow_outbound_udp_fragmentation` ? The default will be false, keeping the current behavior. When `allow_outbound_udp_fragmentation = true`, `set_disable_ip_fragmentation` will be skipped. If that sounds OK, I'll be happy to submit a patch.

**Comment by zonyitoo** [comment]
It is Ok. I would prefer `outbound_udp_allow_fragmentation`. Just put it in `ConnectOpts` and supported it both globally and per-servers.

**Comment by Venkatesh1505** [comment]
Hey @zonyitoo !
When is the related PR planned to be released? I see [here](https://github.com/shadowsocks/shadowsocks-rust/pull/1790#issuecomment-2513744333) that it was planned in early december. Any tentative dates planned for the same? TIA

**Comment by zonyitoo** [comment]
Waiting for hickory-dns' new release.

**Comment by venkateshravichandran01** [comment]
Thanks @zonyitoo ! I could see that there is a release by hickory-dns recently - https://crates.io/crates/hickory-resolver 
v0.24.2. Am I looking at the wrong place?
Asking since we are waiting for next release of shadowsocks-rust incorporating the changes to allow IP fragmentation.

**Comment by zonyitoo** [comment]
We are waiting for its v0.25 release.
