### ISSUE TITLE
负载均衡算法中域名的选取问题

### ISSUE THREAD

**Issue by skynocloud** [shadowsocks/shadowsocks-rust#180]
您好, 代码中采用 dl.google.com 这个域名来测试访问速度其实是不可行的, 因为 dl.google.com 在中国并没有被屏蔽, 这就直接导致负载均衡算法从整体上效果不怎么样.

所以选择一个好的稳定的被屏蔽的域名是比较重要的, 建议使用 google.com 这个域名或者 youtube.com 等. 但是从一方面来讲, 把域名写死到里面并不太优雅, 可以考虑将其放到配置文件中, 这样可以方便不同地区的人定制使用. 我把代码中的 dl.google.com 更换后, 重新编译后负载均衡算法工作良好, 体验很不错.

**Comment by zonyitoo** [comment]
但我的想法就是应该选择一个都没有被屏蔽的域名才对？因为这里只是用于测耗时。

**Comment by skynocloud** [comment]
> 但我的想法就是应该选择一个都没有被屏蔽的域名才对？因为这里只是用于测耗时。

在能保证所有服务器都一直可用的状态下, 这样来处理是可以的, 但是网络状况并不会总是那么稳定, 也就是说总有些代理服务器会偶尔掉线(这里指代理服务器可以访问没有被屏蔽的网站, 但是访问不了被屏蔽的站点), 这一因素也比较影响体验. Anyway, 这只是个建议 :)

**Comment by cg31** [comment]
关于负载均衡，我觉的它应该作为一个在编译时能enable/disbale的feature。

**Comment by zonyitoo** [comment]
> 关于负载均衡，我觉的它应该作为一个在编译时能enable/disbale的feature。

disable掉的话，多server该如何选取？Round Robin？

**Comment by cg31** [comment]
disable 就是local不做选择，由用户指定server。就像是运行 sslocal -s server-addr。

这样的好处是，在ss-rust上面可能做一个GUI，选择server在GUI做。

**Comment by zonyitoo** [comment]
指定单个server的时候，balancer不会启动的。

参考ss-libev版本的ssmgr实现，每一个单独的用户都启动一个单独的ssserver进程，只传入单个配置。

**Comment by zonyitoo** [comment]
Now it is using http://detectportal.firefox.com/success.txt for TCP connectivility checking.
