### ISSUE TITLE
does it run in openwrt?

### ISSUE THREAD

**Issue by youxiaojie** [shadowsocks/shadowsocks-rust#1809]
pkgs, or static binary of two architecture, mipsel for qualcomm, ramips for mediatek?

**Comment by zonyitoo** [comment]
You could cross compile one by yourself.

**Comment by youxiaojie** [comment]
> You could cross compile one by yourself.

could you please write an reference on how to cross compile for other platform? thanks!!

**Comment by zonyitoo** [comment]
https://github.com/cross-rs/cross
