### ISSUE TITLE
关于dns泄露的问题

### ISSUE THREAD

**Issue by fyhong** [shadowsocks/shadowsocks-rust#1812]
如果我用命令行直接运行
./ssrust --dns 210.220.163.82 --outbound-bind-interface ppp0 -k test -m chacha20-ietf-poly1305 -s 0.0.0.0:40001
我到https://surfshark.com/zh/dns-leak-test检测dns，
![QQ截图20241212131945](https://github.com/user-attachments/assets/f2a6471b-6f10-4cfd-aeb7-8559298e259b)
是上面的结果

但如果我用以下的配置文件，再用./ssrust -c test.json 来运行,再检测dns,就会跳回vps原来的dns.这是什么原因
{
"servers": [
{"server": "0.0.0.0", "server_port": 40001, "dns_cache_size": 0, "mode": "tcp_and_udp", "password": "test", "method": "chacha20-ietf-poly1305", "dns": "210.220.163.82", "outbound_bind_interface": "ppp0" }
]
}
![222222](https://github.com/user-attachments/assets/f67ead26-0c44-4f97-a4aa-7b12af92d4d9)

**Comment by zonyitoo** [comment]
There is no `dns` configuration key for `server`.

**Comment by fyhong** [comment]
那为什么我直接用命令行它是生效的？

**Comment by zonyitoo** [comment]
Because there is a `--dns` command line option, but no `dns` in configuration for `server`.

**Comment by fyhong** [comment]
但是我这份配置里面是有配置dns的
{
"servers": [
{"server": "0.0.0.0", "server_port": 40001, "dns_cache_size": 0, "mode": "tcp_and_udp", "password": "test", "method": "chacha20-ietf-poly1305", "dns": "210.220.163.82", "outbound_bind_interface": "ppp0" }
]
}
