### ISSUE TITLE
[FEATURE] Address whitelist for sslocal

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#183]
`sslocal` could support a proxy white list, only proxy those requests that target addresses are in the list.

- `sslocal` supports white list (including TCP, UDP)
- Support loading from URLs, such as [gfwlist](https://github.com/gfwlist/gfwlist)

Open for contribution.

**Comment by bigtan** [comment]
负载均衡 + http + 规则分流  基本上就是一个rust重写版的clash了

**Comment by e2ge** [comment]
这个有点像v2ray的路由功能呀。
v2其实做了一个domain的库，可以用类似geosite的方式自定义list，你也可以考虑。
https://github.com/v2ray/domain-list-community

总觉得gfwlist太大了，我还是比较喜欢自定义。

**Comment by zonyitoo** [comment]
> 负载均衡 + http + 规则分流 基本上就是一个rust重写版的clash了

哈哈，不过这只是我自己脑洞想做的。需求上并不明确，我在ss前面套了一个privoxy来配置各种规则，走不同的网络（公司内网等）

**Comment by zonyitoo** [comment]
> 这个有点像v2ray的路由功能呀。
> v2其实做了一个domain的库，可以用类似geosite的方式自定义list，你也可以考虑。
> https://github.com/v2ray/domain-list-community
> 
> 总觉得gfwlist太大了，我还是比较喜欢自定义。

Thanks for your advice.

**Comment by e2ge** [comment]
@bigtan clash应该不是自己实现的这些功能吧，用的是v2ray的代码

**Comment by e2ge** [comment]
@zonyitoo 我之前也用privoxy，后来换成v2ray来分流了，但是v2的配置文件太不友好了。

**Comment by zonyitoo** [comment]
ACL is already supported in master.
