### ISSUE TITLE
被block问题

### ISSUE THREAD

**Issue by vincascm** [shadowsocks/shadowsocks-rust#187]
2019年有SS的VPS大量被封，有一个对此进行技术分析的文章： <https://gfw.report/blog/gfw_shadowsocks/>。
在此期间注意到有 <https://github.com/trojan-gfw/trojan>，及[proxy over websocket](https://github.com/vi/websocat)的程序，均选择了使用常见协议来降低被检测的概率，不知作者对此有如何看法，是否有新版或全新工具的开发计划。
目前在用[kcptun](https://github.com/xtaci/kcptun)，期待一个用rust开发的，无特征的，能充分利用带宽且低延迟的，少量或无配置的下一代工具。

**Comment by zonyitoo** [comment]
Shadowsocks现在支持Plugin，比如现在推荐的`v2ray-plugin`，用的是websocket, websocket+tls和quic协议。

`sslocal` -> `plugin-local` -> `plugin-server` -> `ssserver`

因此用SS并不妨碍自定义你想要用的协议，利用kcptun协议来传输ss流量也是完全Ok的

**Comment by vincascm** [comment]
thx
