### ISSUE TITLE
Server Manager是否应该支持流量加密。

### ISSUE THREAD

**Issue by baijunty** [shadowsocks/shadowsocks-rust#192]
虽然是15年的标准了
看了下基本就是明文，而且list命令太危险了。直接把所有关键配置信息都返回回来。
简直太危险了，根本不敢开
只需要简单的扫描下端口就能扫出来。

**Comment by zonyitoo** [comment]
所以协议上建议的是开 unix socket 。

而且一般是借助一个前端软件来使用的，`ssmanager`是作为它的后端，如 [shadowsocks-manager](https://github.com/shadowsocks/shadowsocks-manager)

**Comment by baijunty** [comment]
好吧，我研究一下
