### ISSUE TITLE
DNS WARN when accessing china website in acl mode

### ISSUE THREAD

**Issue by bigtan** [shadowsocks/shadowsocks-rust#196]
`ss-local.exe -c config.json --acl chn.acl --protocol=http`

[2020-02-26T12:10:27Z WARN  trust_dns_proto::udp::udp_client_stream] dropped malformed message waiting for id: 48309 err: buffer exhausted

china ip list https://github.com/17mon/china_ip_list

**Comment by zonyitoo** [comment]
This is a new WARN log from trust-dns-resolver 0.19.3 . Maybe it is because DNS resolve has timeout.

**Comment by zonyitoo** [comment]
It should be releated to `timeout`. Future will be dropped if DNS resolve time excceeded `timeout`.

**Comment by zonyitoo** [comment]
You may also see warning like this: https://github.com/bluejekyll/trust-dns/issues/355

**Comment by zonyitoo** [comment]
You could ignore it if every other things works fine.
