### ISSUE TITLE
method aes-256-gcm not supported

### ISSUE THREAD

**Issue by wan9wu** [shadowsocks/shadowsocks-rust#197]
直接下载了：
 shadowsocks-v1.8.9-stable.x86_64-unknown-linux-musl.tar.xz

直接运行：
 sslocal -b "127.0.0.1:1080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty"

提示：
method aes-256-gcm not supported

请问如何排查此问题。

**Comment by zonyitoo** [comment]
下载地址是？

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/releases
我刚验证了没有任何问题

**Comment by zonyitoo** [comment]
Close for inactivity.
