### ISSUE TITLE
relay 是如何实现的？

### ISSUE THREAD

**Issue by Ryan-Git** [shadowsocks/shadowsocks-rust#200]
@zonyitoo 
你好，冒昧请教一个跟项目不是特别有关的问题。

为了更好地理解 ss 和学一下 rust，我参考这个项目尝试做了一个简单的代理（[这里](https://github.com/Ryan-Git/sagittarius)），握手等阶段没什么问题，但最后 relay 就是没反应（卡住或发送几百字节就断开）。看了几遍这里的实现还是不知道哪里有问题，方便的话不知能否指点一下，非常感谢！

主要代码如下

服务端：
```rust
let (mut ri, mut wi) = self.inbound.split();
let (mut ro, mut wo) = self.outbound.as_mut().unwrap().split();

use tokio::io::copy;
let i2o = copy(&mut ri, &mut wo);
let o2i = copy(&mut ro, &mut wi);

match future::select(i2o, o2i).await .....
```

客户端(async-std)：
```rust
let mut ri = BufReader::with_capacity(2048, self.inbound.clone());
let mut wi = BufWriter::with_capacity(2048, self.inbound.clone());
let mut ro = BufReader::with_capacity(2048, self.outbound.as_ref().unwrap().clone());
let mut wo = BufWriter::with_capacity(2048, self.outbound.as_ref().unwrap().clone());

use async_std::io::copy;
let i2o = copy(&mut ri, &mut wo);
let o2i = copy(&mut ro, &mut wi);

match i2o.race(o2i).await ...
```

**Comment by zonyitoo** [comment]
应该是因为用了`BufWriter`。它要达到一定的数量才会实际调用`write()`，所以如果你读到的数据本身就很小的话（比如HTTP的`GET`），写到`BufWriter`并不会触发到写，导致请求实际上一直没有发出去，自然目标服务器也不会有东西返回来

**Comment by Ryan-Git** [comment]
> 应该是因为用了`BufWriter`。它要达到一定的数量才会实际调用`write()`，所以如果你读到的数据本身就很小的话（比如HTTP的`GET`），写到`BufWriter`并不会触发到写，导致请求实际上一直没有发出去，自然目标服务器也不会有东西返回来

感谢！

试了没有 buf 不行，后来看 tokio 的 copy 有个 2k 的 buf 就没动脑子全加了。。确实应该是只有 reader 加 buf 才行。

**Comment by Ryan-Git** [comment]
回去以后发现还是不行。这种构造方式（读加 buf，写不加）应该是尝试过的。最后觉得可能还是长城宽带的问题。。。

不过 ssh tunnel 会相对稳定一些，不知道是不是用了什么特别的方法。

**Comment by zonyitoo** [comment]
本地loopback先测试一下看看能不能复现问题

**Comment by Ryan-Git** [comment]
> 本地loopback先测试一下看看能不能复现问题

不行，本地肯定都测过的。就是本地能用，服务器上（azure 日本西）部分网络可以用，家里还是不行。

**Comment by zonyitoo** [comment]
那就不要用`copy`，自己写一个`loop`，每收到一次数据打出来看看是否读到了东西

**Comment by Ryan-Git** [comment]
恩，试了一下。3k 的东西服务端发完1分多钟客户端才读到。。。

**Comment by zonyitoo** [comment]
Interesting. 是在linux跑吗？用`strace`看一下系统调用

**Comment by Ryan-Git** [comment]
![image](https://user-images.githubusercontent.com/5906907/76165564-07f7f980-6193-11ea-95eb-cc26001482fc.png)

**Comment by zonyitoo** [comment]
你要看`write()`调用的时候，以及另外一边收到`read()`的时间

**Comment by Ryan-Git** [comment]
很神奇的是没有。。我研究一下

**Comment by Ryan-Git** [comment]
ssh 上去都卡死。。。白天再试试
