### ISSUE TITLE
tokio_dns_resolver is actually blocking

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#208]
https://github.com/tokio-rs/tokio/blob/826fc21abfd04779cde92e4cc33de2adb42cf327/tokio/src/net/addr.rs#L147-L148

I rest my case.

**Comment by Mygod** [comment]
Disappointingly, so does async-std: https://github.com/async-rs/async-std/blob/46cafffc31711d5df1b267dc38d191463ac10bda/src/net/addr.rs#L214-L218

**Comment by madeye** [comment]
I think that's why trust-dns-resolver is also used here?

**Comment by Mygod** [comment]
I don't see `trust-dns` enabled in shadowsocks-android? Also maybe tokio dns should be avoided in general. I am still reading trust-dns-resolver though.

**Comment by madeye** [comment]
No, I didn't enable that for Android.

To improve the perf, we can re-enable it later.

**Comment by Mygod** [comment]
This will be resolved via https://github.com/shadowsocks/shadowsocks-rust/pull/242/commits/9712a97cb6503ed98626c60391f3e8f982e5dc85, though only for `local-dns-relay` feature.

**Comment by Mygod** [comment]
It seems like server also does dns resolving. I looked into it and there is this `from_system_conf` API in trust-dns that we can use to replace `tokio_dns_resolver`. Also opened https://github.com/bluejekyll/trust-dns/issues/1099 upstream to refine the feature.

**Comment by zonyitoo** [comment]
`tokio` and `async-std` will always want to keep consistent with `libstd`. So it won't be possible for them to add asynchronous DNS resolution, unless `libstd` supports it. And I don't think `libstd` is going to reimplement full DNS resolution.

**Comment by zonyitoo** [comment]
`trust-dns` is quite a large library,  enabling it will significantly increase binary size.

Also, I am highly suggest that `src/relay/dnsrelay` could reuse the client implementation in `trust-dns-client` instead of reimplementing client resolution logics with `trust-dns-proto`.

**Comment by Mygod** [comment]
I think the binary size is still reasonable. Let's just use `trust-dns` then.
