### ISSUE TITLE
UnixStream is blocking

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#209]
Please use the one in `tokio` or `async-std`. While it seems like they implemented it using polling instead of signals (`<aio.h>`), it is better than blocking operations.

**Comment by Mygod** [comment]
Okay it seems like both of these two use mio, which uses `<sys/select.h>` underthehood, so I guess that is fine too.

**Comment by zonyitoo** [comment]
Which `UnixStream`? The one in `src/relay/sys/unix/mod.rs:protect`?

**Comment by Mygod** [comment]
I saw you are using `tokio::net::UnixStream` in `stat_path`... This is the correct one.

**Comment by zonyitoo** [comment]
Yup. @madeye said `protect` doesn't need to be nonblocked.

**Comment by Mygod** [comment]
While `protect` is basically a series of RPCs, why not just use nonblocking variant everywhere?

**Comment by zonyitoo** [comment]
It's true. I am going to add it for you. @madeye

**Comment by madeye** [comment]
Awesome 👍

**Comment by zonyitoo** [comment]
BIG PROBLEM: `sendfd` crate doesn't support async i/o

**Comment by zonyitoo** [comment]
I chose 2. :P

**Comment by madeye** [comment]
Sure.

**Comment by Mygod** [comment]
I see. Technically `SendWithFd` is implemented by [`sendfd`](https://github.com/Standard-Cognition/sendfd) and not supported by stdlib. 6373040 seems like a good solution. 👍

**Comment by madeye** [comment]
6373040 works well. I think we can close this now.
