### ISSUE TITLE
Use features to enable currently Android only features

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#210]
Currently we have `cfg(target_os = "android")`, maybe it's better to define them as features, e.g.

1. `socksifier` feature, which is used for creating a VPN over Shadowsocks, consists of `protect_path`;
2. `stats` feature, which reports stats using `stats_path`; (could be extended in the future if needed)
3. `uds` feature, which enables various `UnixStream`-related features that are only available on Unix (Mac, Linux, Android, ...).
4. `dns-relay` feature, which is self-explanatory.

This is probably very low priority, just want to mention it to make code more readable and extendable. :)

**Comment by zonyitoo** [comment]
I agree. Another refactor is now on the schedule.

**Comment by Mygod** [comment]
Made some progress at #242.

**Comment by zonyitoo** [comment]
I am expecting a `#[cfg(feature = "android-application")]`.

```toml
[features]
android-application = ["socksifier", ...]
```

Or, maybe, create a folder inside `src/relay` and then puts all Android related code in it.

**Comment by Mygod** [comment]
Why treat Android specially? I think the feature split makes more sense.
