### ISSUE TITLE
Always failed with config file

### ISSUE THREAD

**Issue by HsuJv** [shadowsocks/shadowsocks-rust#212]
Here're my two configuration files:
```json
{
	"server": "::",
	"server_port": 443,
	"local_address": "127.0.0.1",
	"local_port": 4433,
	"password": "xxxx",
	"timeout": 20,
	"method": "aes-256-gcm"
}
```
```json
{
	"servers": [
		{
			"address": "::",
			"port": 443,
			"password": "xxxx",
			"method": "aes-256-gcm"
		},
		{
			"address": "::",
			"port": 80,
			"password": "xxxx",
			"method": "aes-256-gcm"
		}
	],
	"local_port": 4433,
	"local_address": "127.0.0.1",
	"dns": "8.8.8.8"
}
```

Then I use `ssserver -c config.json` to start the ss server.
However, when the ss local connecting, the log always shows
```bash
root@instance-20200213-0412:~/ss-rs# /root/.cargo/bin/ssserver -c /etc/ss.json 
[2020-03-15T11:54:04Z INFO  ssserver] ShadowSocks 1.8.9
[2020-03-15T11:54:04Z INFO  shadowsocks::relay::tcprelay::server] ShadowSocks TCP Listening on [::]:443
[2020-03-15T11:54:07Z ERROR shadowsocks::relay::tcprelay::server] Failed to connect remote www.google.com:443, Invalid argument (os error 22)
```

But when I run the ss server with CLI `/root/.cargo/bin/ssserver -s "[::]:443" -m "aes-256-gcm" -k "xxx"`, it succeed.

Please take a look at to see what's wrong with my configure file.

Thanks in advance for kindly advise.

**Comment by zonyitoo** [comment]
Remove `local_address` and `local_port`. For `ssserver`, these two options are for setting outbound sockets' `bind()` address, which is commonly used for choosing network interface.

**Comment by HsuJv** [comment]
Awesome! It works.
I simply copy your example and modify some server settings which made this stupid mistake.

Thanks again for your help.

Close the issue
