### ISSUE TITLE
Time formatted output should not use UTC time

### ISSUE THREAD

**Issue by Stzx** [shadowsocks/shadowsocks-rust#217]
UTC time should not be used:

> [2020-03-24T03:02:08Z INFO  sslocal] ShadowSocks 1.8.9
> [2020-03-24T03:02:08Z INFO  shadowsocks::relay::tcprelay::http_local] ShadowSocks HTTP Listening on x.x.x.x:x

`version` : shadowsocks-v1.8.9-stable.x86_64-pc-windows-gnu.zip

**Comment by zonyitoo** [comment]
This is the default format of [env_logger](https://crates.io/crates/env_logger).

**Comment by Stzx** [comment]
> This is the default format of [env_logger](https://crates.io/crates/env_logger).

Yes.

But I think using local time format is more intuitive than using UTC format. What do you think?

**Comment by zonyitoo** [comment]
Yup. That's because `env_logger` uses `humantime`, which prints timestamp in RFC3339 format (always a UTC time).

Let's see what I can do for it.

**Comment by zonyitoo** [comment]
`master` branch is now using local time instead of UTC time. Will be released in the next version.
