### ISSUE TITLE
有无可能使用纯rust的加密实现,替换现有的openssl依赖?

### ISSUE THREAD

**Issue by raintean** [shadowsocks/shadowsocks-rust#218]
依赖系统的openssl, 对于跨平台编译会带来不方便的地方, 尤其是移动平台. 是否有可能使用纯rust的加密实现(ring等)?

**Comment by zonyitoo** [comment]
已经在用`ring`，但部分`shadowsocks.org`上定义的加密方式，没有完全支持。
如果不需要使用需要OpenSSL的加密方式，可以去掉相关的`feature`，这样就不会依赖到了

**Comment by raintean** [comment]
好的, 非常感谢回答. 其实您的回答其实在我预料之中, 我其实想要的是能否使用ring或者其他的来完全替代openssl, 目前看来整个rust生态圈好像还不太可能. 哈哈....

**Comment by zonyitoo** [comment]
嗯。这个本身一直在我的TODO List里，`ring`出来之后已经用它来支持了一部分了。但`ring`本身并没有考虑支持一些比较老的算法，但这些算法在ss圈里应用还是比较广泛的。

针对这个问题刚也简单搜索了一下，光`aes-***-***`这些算法，貌似都没有一个靠谱的Rust实现（其中RustCrypto项目已废弃、`aes`项目的具体实现有点不明）

**Comment by raintean** [comment]
跨平台的交叉编译, 其实我很早以前已经找到很好的方法了. openssl 是可以直接包含在rust里面源码编译的.

**Comment by zonyitoo** [comment]
这个项目就挺好 https://github.com/rust-embedded/cross 我用着感觉不错

**Comment by raintean** [comment]
我也在用这个, 只不过没有darwin平台的cross, darwin平台是基于真机的. 但是其实是有cross方案的. golang世界里面的xgo就能. 回头我得好好研究一下他的docker image

**Comment by LuoZijun** [comment]
已经在路上了：https://github.com/shadowsocks/crypto

**Comment by LuoZijun** [comment]
OpenSSL 已经去掉了。

See PR #319
