### ISSUE TITLE
在UDP转发中,local->remote和remote->local的地址匹配

### ISSUE THREAD

**Issue by raintean** [shadowsocks/shadowsocks-rust#225]
```rust
        debug!(
            "UDP ASSOCIATE {} <- {}, payload length {} bytes",
            src_addr, remote_addr, remote_recv_len
        );

        // FIXME: The Address should be the Address that client sent
        let addr = Address::SocketAddress(remote_addr);

        // CLIENT <- SERVER protocol: ADDRESS + PAYLOAD
        let mut send_buf = Vec::new();
        addr.write_to_buf(&mut send_buf);
        send_buf.extend_from_slice(&remote_buf[..remote_recv_len]);
```
中间的
```rust
// FIXME: The Address should be the Address that client sent
```
是不是指在域名为目标地址的情况下, 如果接受到需要转发给local的数据包,在转发前,需要把ip转换成对应的域名?   
我看了很多的ss/socks5的实现,在这个一块都是不规范的. 特地来看一下作者的实现.

**Comment by madeye** [comment]
`FIXME: The Address should be the Address that client sent`

Actually we should not fix anything here, the implementation is correct.

As shadowsocks provided a `(address) restricted-cone NAT`, it's possible that the source address where the UDP packet comes from is some address other than the client sent. https://en.wikipedia.org/wiki/Network_address_translation#Methods_of_translation

This technique is widely used in P2P applications, like IP phones and P2P gaming: https://en.wikipedia.org/wiki/UDP_hole_punching

**Comment by raintean** [comment]
> `FIXME: The Address should be the Address that client sent`
> 
> Actually we should not fix anything here, the implementation is correct.
> 
> As shadowsocks provided a `(address) restricted-cone NAT`, it's possible that the source address where the UDP packet comes from is some address other than the client sent. https://en.wikipedia.org/wiki/Network_address_translation#Methods_of_translation
> 
> This technique is widely used in P2P applications, like IP phones and P2P gaming: https://en.wikipedia.org/wiki/UDP_hole_punching

我关注的并不是remote包应不应该转发回local的问题.  
我的意思是, 如果local发送一个域名为目标地址的udp包, 经过remote转发到目标服务器, 然后目标服务器回复了udp包到remote, 这个时候remote再把udp回给local的时候, 是不是应该转换成peer_addr为域名?

**Comment by zonyitoo** [comment]
是的，这块协议没有规范，因此我这里实现时就只返回了IP，避免一次Address结构的拷贝。不过这里的开销实际微乎其微，感觉是可以变回来

**Comment by raintean** [comment]
> 是的，这块协议没有规范，并没有要求把local->remote时使用的`Address`原样返回。目前这里的实现是类似一个NAT，要实现成这样的话就需要有一个`Address`与`ip:port`的反查Map

是的, 大部分的ss(或者socks5)服务器都没有实现该规范, 包括shadowsocks的协议草案上也是只是使用`target address`一词代替.  
再次感谢作者回答.
