### ISSUE TITLE
无法在ssserver中使用acl规则

### ISSUE THREAD

**Issue by MeteorsLiu** [shadowsocks/shadowsocks-rust#226]
你好。

我想在ssserver中使用acl规则，但是我发现--acl这个参数根本不存在，但我看到了本项目的介绍说，rust版本也支持acl规则，请问下如何才能使用呢。

ss-rust version:1.8.9
cargo: 1.42.0

**Comment by MeteorsLiu** [comment]
error: Found argument '--acl' which wasn't expected, or isn't valid in this context

**Comment by Stzx** [comment]
嘿，抱歉。 `--acl` 参数在 `v1.8.9` 版本后添加，现在还未发布!

**Comment by zonyitoo** [comment]
ACL是在1.8.10才有的，还未发布。可使用circle-ci中的nightly build

**Comment by zonyitoo** [comment]
https://circleci.com/gh/shadowsocks/shadowsocks-rust
