### ISSUE TITLE
Run server in background

### ISSUE THREAD

**Issue by stringer44** [shadowsocks/shadowsocks-rust#228]
Hello devs
Thanks for all your hard work
have a question
how to run ssserver in background if it possible?
tried systemd but it didn't work for me. i use ubuntu server 18.04

**Comment by zonyitoo** [comment]
Why `systemd` didn't work? Processes that managed by `systemd` are already **run in background**.

**Comment by stringer44** [comment]
> Why `systemd` didn't work? Processes that managed by `systemd` are already **run in background**.

i don't know. in my case server is running only if i starting it in terminal.
btw sorry my english, i'm russian.

**Comment by zonyitoo** [comment]
Please check your service definition. `ssserver` may be failed to start.

**Comment by zonyitoo** [comment]
Close for inactivity.
