### ISSUE TITLE
The remote address of UDP relay is not handled properly

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-rust#230]
In  https://github.com/shadowsocks/shadowsocks-android/pull/2454, we found shadowsocks-rust handles the UDP relay incorrectly, which cause STUN and DNS (with checking the source address) tests failed.

The bug is related to these lines:

https://github.com/shadowsocks/shadowsocks-rust/blob/f1bb7c5341f40a4c815a66295a2721f338cb6b4a/src/relay/udprelay/association.rs#L411

Shadowsocks-rust ignores the "real" source address returned from remote, and didn't construct the relay packet with this address.

https://github.com/shadowsocks/shadowsocks-rust/blob/f1bb7c5341f40a4c815a66295a2721f338cb6b4a/src/relay/udprelay/socks5_local.rs#L127

To fix this issue in socks5-local, we should assemble the packet with the source address from shadowsocks remote.

In other implementations, we simply returns the plain packet (SOCKS5 address + payload) back to the socks5 client:

https://github.com/shadowsocks/shadowsocks-libev/blob/401d32348024f7a0871aef76d436a5a847ef3b5a/src/udprelay.c#L881

In the NAT redir mode, we need to rebind the UDP socket to the the "real" address to let the client think the packet is actually sent from that address.

https://github.com/shadowsocks/shadowsocks-libev/blob/401d32348024f7a0871aef76d436a5a847ef3b5a/src/udprelay.c#L875

**Comment by madeye** [comment]
I tried to fix this via deff21. I only tested it with ss-local and socksfy (https://www.inet.no/dante/doc/1.3.x/socksify.1.html)

**Comment by zonyitoo** [comment]
That's a huge bug!

**Comment by zonyitoo** [comment]
@madeye Could you make a PR for this?

**Comment by Mygod** [comment]
The commit is already in #211 right?

**Comment by madeye** [comment]
Yes, it's already in that PR.
