### ISSUE TITLE
Shadowsocks should send data along with header

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#232]
Currently, this implementation does handshake first, which is problematic for obfuscation, e.g.

https://github.com/shadowsocks/shadowsocks-rust/blob/1204d581610c5c6bcb24aab40e1d4fa52c18aa29/src/relay/tcprelay/socks5_local.rs#L40

**Comment by zonyitoo** [comment]
Hmm, IV is already sent with the first packet:

1. Client -> Server: target's `Address`
2. Server -> Client: the first response packet.

**Comment by Mygod** [comment]
Two connections should use independent IVs.

**Comment by zonyitoo** [comment]
Yes, they are.

**Comment by Mygod** [comment]
The first packet should contain the header/handshake as well as actual payload.

**Comment by zonyitoo** [comment]
Hmm, then the `ProxyStream` should store the `Address` and sent it with the first `write` call.

**Comment by Mygod** [comment]
CC @madeye to double check on this.

**Comment by zonyitoo** [comment]
Made a simple but a little bit ugly solution.

**Comment by Mygod** [comment]
This should also be done at the server side as well -- https://github.com/shadowsocks/shadowsocks-rust/blob/806f44244af1366323d69a2abed3a530838ab264/src/relay/tcprelay/aead.rs

**Comment by zonyitoo** [comment]
Server side doesn't have a handshake packet.

**Comment by Mygod** [comment]
Cool just double checked via `tcpdump` and can confirm that both sides are doing it correctly with https://github.com/shadowsocks/shadowsocks-rust/commit/45a3469840fa423cecec90de5cc03ed5003c1a92.

**Comment by Mygod** [comment]
@madeye Maybe we should include this in official doc as well?

**Comment by madeye** [comment]
Yeah, we should do that.

**Comment by Mygod** [comment]
@madeye Updated at https://github.com/shadowsocks/shadowsocks-org/wiki/Protocol

**Comment by madeye** [comment]
Hmm, this fix caused another problem: https://github.com/shadowsocks/shadowsocks-android/issues/2621.

We'd better have a delay to send out the header, even if there's no data. Some underlying protocol requires this behavior like TCP.

**Comment by zonyitoo** [comment]
Well, it would be quite tricky to do that in a `Future` based server... But it should be able to do.

**Comment by madeye** [comment]
Yes, I tried to implement this myself at first, but found it's not easy.

**Comment by zonyitoo** [comment]
I am currently working on #326 . This issue will probably have to be fixed after #326 being done.

**Comment by Mygod** [comment]
Considering this only covers a few use cases like FTP, maybe it is better to have a timeout of maybe 500ms, and an option to turn off this behavior (default on).

**Comment by madeye** [comment]
A fixed 500ms timeout looks good enough.

Given most of protocols today let client send the request first, I don't think we would see header only handshakes often.

**Comment by zonyitoo** [comment]
This 500ms is only applied on the client side: `client -> remote`. The other side of the tunnel on servers can still wait for the first response from the target remote servers.
