### ISSUE TITLE
TCP socks5 client exited with error: unsupported socks version 0x4

### ISSUE THREAD

**Issue by qwelias** [shadowsocks/shadowsocks-rust#233]
I'm trying to use it on Windows, and I'm not sure if:
- Windows does not support SOCKS5
- I configured Windows incorrectly
- I configured ss-rust incorrectly

Running as Admin:
`& "D:\stuff\ss\ssserver.exe" -U -v -c "D:\stuff\ss\config.json"`
`& "D:\stuff\ss\sslocal.exe" -U -v -c "D:\stuff\ss\config.json"`

Configs:
```json
{
    "server": "127.0.0.1",
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "",
    "timeout": 300,
    "method": "plain"
}
```
![Windows config](https://i.imgur.com/ac8Tenq.png)

**Comment by studentmain** [comment]
windows system proxy use only socks4

**Comment by zonyitoo** [comment]
Yes, Windows' builtin proxy setting is only support socks4/4a.

**Comment by zonyitoo** [comment]
BTW, @qwelias you can try to use `--protocol http`.

**Comment by qwelias** [comment]
@zenytoo, thanks, but I need to proxy tcp and udp, looks like there's no way via windows system proxy
