### ISSUE TITLE
Cargo.lock is missing?

### ISSUE THREAD

**Issue by netvl** [shadowsocks/shadowsocks-rust#236]
Missing `Cargo.lock` makes this project unbuildable using standard tools on NixOS, because they require presence of the `Cargo.lock` file by default. Also, I believe it is idiomatic to have `Cargo.lock` committed to the project if it is an application.

**Comment by zonyitoo** [comment]
It could be a library as well.

**Comment by Mygod** [comment]
It's probably a good practice to check-in the lock file as it would be useful for reproducible builds. See also: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

**Comment by zonyitoo** [comment]
Ok, for following official's suggestion.
