### ISSUE TITLE
regex error: Compiled regex exceeds size limit of 10485760 bytes.', src/bin/local.rs:245:17

### ISSUE THREAD

**Issue by Yesionio** [shadowsocks/shadowsocks-rust#237]
![2020-05-05 17-48-55 的屏幕截图](https://user-images.githubusercontent.com/34182932/81054479-81913700-8ef9-11ea-95bb-8df25bfacbce.jpg)

**Comment by zonyitoo** [comment]
What... Could you provide your `nobanAD.acl`?

**Comment by zonyitoo** [comment]
Please check if this commit works for you.

**Comment by Yesionio** [comment]
OK, thinks
