### ISSUE TITLE
Plugin may need more than 2 seconds to start

### ISSUE THREAD

**Issue by madeye** [shadowsocks/shadowsocks-rust#240]
On some old Android device, we expect plugins like v2ray would have a very slow startup, which will break the assumption below:

https://github.com/shadowsocks/shadowsocks-rust/blob/ea24418ffcbb01ebb88fd3af9e161a5f93fe0a27/src/plugin/mod.rs#L215

Here's the bug report for shadowsocks-android:

https://github.com/shadowsocks/shadowsocks-android/issues/2515#issuecomment-625366119

We may wait longer enough, say 10 seconds, or just remove this connection test in shadowsocks-rust.

BTW, I expect even slower startup on some embedded devices like routers.

**Comment by zonyitoo** [comment]
That's bad. :(

Those code were added for ensuring that when server's port is listening, server is ready for accepting requests.

Also, the LoadBalancer requires initialization for choosing the best server. If removing this, LoadBalancer's constructor won't be able to know which servers are dead.

Both of them will eventually cause failures just after launches of `sslocal`.

**Comment by zonyitoo** [comment]
> We may wait longer enough, say 10 seconds.

I would prefer that.

And don't crash if any plugins don't response in time.
