### ISSUE TITLE
rlim_cur: nofile expected `u32`, found `u64`

### ISSUE THREAD

**Issue by clementhk** [shadowsocks/shadowsocks-rust#243]
```
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/shadowsocks-rust-1.8.10/src/relay/utils.rs:26:23
   |
26 |             rlim_cur: nofile,
   |                       ^^^^^^ expected `u32`, found `u64`

error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/shadowsocks-rust-1.8.10/src/relay/utils.rs:27:23
   |
27 |             rlim_max: nofile,
   |                       ^^^^^^ expected `u32`, found `u64`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `shadowsocks-rust`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `shadowsocks-rust v1.8.10`, intermediate artifacts can be found at `/tmp/cargo-installbj1lDi`
```

root@kardiapi:\~# rustc -V
rustc 1.43.1 (8d69840ab 2020-05-04)
root@kardiapi:\~# cargo -V
cargo 1.43.0 (2cbe9048e 2020-05-03)

**Comment by zonyitoo** [comment]
What's your platform?

**Comment by clementhk** [comment]
Linux 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

**Comment by clementhk** [comment]
Any chance you could release it with `arm-unknown-linux-gnueabihf` so I don't have to compile it myself? 😅
I might upgrade it to `aarch64` later but for now it doesn't work very well with Raspberry Pi.

**Comment by zonyitoo** [comment]
> Any chance you could release it with arm-unknown-linux-gnueabihf so I don't have to compile it myself? 😅

It seems that [`cross`](https://github.com/rust-embedded/cross) supports that platform. I can add it into Circle-CI's build script.

**Comment by clementhk** [comment]
Testing your fix

**Comment by clementhk** [comment]
Confirm that it's fixed.

**Comment by zonyitoo** [comment]
@clementhk https://circleci.com/gh/shadowsocks/shadowsocks-rust/771#artifacts/containers/0 Prebuilt binaries for arm-unknown-linux-gnueabihf.

**Comment by clementhk** [comment]
> @clementhk https://circleci.com/gh/shadowsocks/shadowsocks-rust/771#artifacts/containers/0 Prebuilt binaries for arm-unknown-linux-gnueabihf.

Thanks!
The build works!
```
root@kardiapi:~# ./ssserver -V
shadowsocks 1.8.11
```

**Comment by zonyitoo** [comment]
Nightly builds could be found in circle-ci. It will rebuild for every commits.
