### ISSUE TITLE
"no-openssl" feature

### ISSUE THREAD

**Issue by clementhk** [shadowsocks/shadowsocks-rust#244]
Right now I'm building with `--no-default-features --features "sodium trust-dns local-http local-http-native-tls"`, because cargo doesn't support disabling a single default feature.
But I need to copy default features into features and take the features with openssl out, and that makes it a bit complicated as default features changes.

Another issue is that even after taking openssl features out, `openssl-sys` was still compiled, but this could be fixed by having "no-openssl" feature.

**Comment by clementhk** [comment]
I just noticed that `openssl-sys` was built because of `local-http-native-tls` feature.

**Comment by zonyitoo** [comment]
OpenSSL is depended by many crates. I don't think that is a good solution.

**Comment by clementhk** [comment]
I don't think OpenSSL can be trusted so hopefully one day we can be free from it.
What is the downside of disabling `local-http-native-tls` btw?
This is the only thing that is depending on `openssl` on my side.

**Comment by zonyitoo** [comment]
You can replace it by `local-http-rustls`.
The only problem is that `ring` doesn't support those old crypto algorithm, so `rustls` can only support those modern tls algorithms. You won't be able to connect to those targets that doesn't support modern algorthms (like microsoft's servers).
Many client implementations uses `CONNECT` for `https` requests, so the problem mentions above will only affect those clients that sends `https` requests without `CONNECT` (like microsoft's softwares, Visual Studio Code, Outlooks).

**Comment by zonyitoo** [comment]
Oh, btw, `native-tls` uses system's APIs, which will be able to reuse system's builtin cert library.

**Comment by clementhk** [comment]
Ok thanks!
I don't use Windows so hopefully it'll work out for me.

**Comment by zonyitoo** [comment]
> I don't use Windows so hopefully it'll work out for me.

Nope. Those features are in Microsoft's product, for example, Visual Studio Code.

**Comment by clementhk** [comment]
> > I don't use Windows so hopefully it'll work out for me.
> 
> Nope. Those features are in Microsoft's product, for example, Visual Studio Code.

Grrr... That's annoying...
