### ISSUE TITLE
How to get the latest build from CircleCI?

### ISSUE THREAD

**Issue by cyber386** [shadowsocks/shadowsocks-rust#251]
I don't know how to download a new version on CircleCI, maybe we should release a new version for this issue ? https://github.com/shadowsocks/shadowsocks-rust/issues/234

**Comment by clementhk** [comment]
They don't show the Artifacts tab for guests, so you'll have to login to see that tab, or add `#artifacts/containers/0` to the end of the job url.
Like this https://circleci.com/gh/shadowsocks/shadowsocks-rust/814#artifacts/containers/0

**Comment by cyber386** [comment]
Thanks, let's keep this issue open may help the other people.

**Comment by zonyitoo** [comment]
> They don't show the Artifacts tab for guests, so you'll have to login to see that tab

That's a problem, I am going to fix this.

**Comment by zonyitoo** [comment]
@cyber386 @clementhk Can you open this link? https://circleci.com/gh/shadowsocks/shadowsocks-rust

If you can, click into one of the builds. Can you see the **Artifacts** tab?

![image](https://user-images.githubusercontent.com/1067951/81937830-b0f52180-9626-11ea-8fd7-630d7b374ed0.png)

**Comment by cyber386** [comment]
> @cyber386 @clementhk Can you open this link? https://app.circleci.com/pipelines/github/shadowsocks/shadowsocks-rust
> 
> If you can, click into one of the builds. Can you see the **Artifacts** tab?
> 
> ![image](https://user-images.githubusercontent.com/1067951/81937830-b0f52180-9626-11ea-8fd7-630d7b374ed0.png)

No, the URL will be redirected to the authentication page.

**Comment by zonyitoo** [comment]
Which one? pipelines URL or the Artifacts tab?

**Comment by cyber386** [comment]
> Which one? pipelines URL or the Artifacts tab?

https://app.circleci.com/pipelines/github/shadowsocks/shadowsocks-rust
This one.

**Comment by zonyitoo** [comment]
Can you access after authentication?

**Comment by cyber386** [comment]
> Can you access after authentication?
Yes

**Comment by zonyitoo** [comment]
Ok then.. I can't fix that because it's CircleCI's strategy.

**Comment by cyber386** [comment]
> Ok then.. I can't fix that because it's CircleCI's strategy.
Update README.md that can be a good solution ^_^

**Comment by zonyitoo** [comment]
## Get nightly builds from CircleCI

1. Visit https://app.circleci.com/pipelines/github/shadowsocks/shadowsocks-rust
    - Login with your account
2. Click one of the latest build pipelines
    ![image](https://user-images.githubusercontent.com/1067951/81950380-70050900-9636-11ea-9164-06921474c2ad.png)
3. Click the **ARTIFACTS** tab and download prebuilt binaries
    ![image](https://user-images.githubusercontent.com/1067951/81950522-9e82e400-9636-11ea-858e-53190260f2a4.png)

**Comment by clementhk** [comment]
Docker builds is no longer on CircleCI, hope it won't affect docker releases.

**Comment by zonyitoo** [comment]
Docker build is only for tags.

**Comment by yangmingxuan** [comment]
> ## Get nightly builds from CircleCI
> 1. Visit https://app.circleci.com/pipelines/github/shadowsocks/shadowsocks-rust
>    
>    * Login with your account
> 2. Click one of the latest build pipelines
>    ![image](https://user-images.githubusercontent.com/1067951/81950380-70050900-9636-11ea-9164-06921474c2ad.png)
> 3. Click the **ARTIFACTS** tab and download prebuilt binaries
>    ![image](https://user-images.githubusercontent.com/1067951/81950522-9e82e400-9636-11ea-858e-53190260f2a4.png)

But there it says:"There are no artifacts to show here.
After 30 days, all artifacts associated with a build automatically expire. Since this run is over 30 days old, the artifacts may have been deleted."

**Comment by zonyitoo** [comment]
This project is currently uses Github Actions to build releases.
