### ISSUE TITLE
Too many open files strikes back

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#262]
Similar to #106, I am seeing a lot of errors related to too many open files in shadowsocks-android, more frequently in Xiaomi phones. Probably have to do with UDP association.

**Comment by zonyitoo** [comment]
Related to #252 .

```jsonc
{
    "udp_timeout": 5,  // Idling UDP associations will be kept only 5 seconds
    "udp_max_associations": 512,  // Maximum UDP associations to be kept, unlimited by default
}
```

**Comment by Mygod** [comment]
Yes. Using max associations sounds like a hack instead of a proper fix though.

**Comment by zonyitoo** [comment]
Maybe we can set `udp_max_associations`' default value to be 1/3 of rlimit.

**Comment by Mygod** [comment]
I think there is something else wrong. Do we handle closing udp sockets correctly? (I haven't checked but it might be the case)

**Comment by zonyitoo** [comment]
It's a problem. But it should be handled correctly. UDP's sockets are actually stored inside a tokio's task, which will be killed when `ProxyAssociation` is dropped.

BTW, #259 is probably not a good idea, which is causing timed out associations couldn't be released in time.

**Comment by zonyitoo** [comment]
For reference, you should see `DEBUG` logs like:

```
UDP association xxx <- ... task is closing
```

when associations are dropped.

**Comment by Mygod** [comment]
Connections should be dropped when new connection comes in. I don't think that is an issue. Also it is only a server side change.

**Comment by zonyitoo** [comment]
It seems that `getrlimit` won't work on Android after doing some searching on Google.

**Comment by Mygod** [comment]
Where did you find that `getrlimit` does not work?

Either way, maybe there are two things we can do:

1. Drop associations when we get `EMFILE` (however, this error can arise anywhere in the code).
2. (Unix specific?) If UDP request originates from localhost (or in Android's VPN mode, a local client connects to the tun interface), we can determine when the UDP connection has gone away by reading `/proc/net/udp` (or [`ConnectivityManager.getConnectionOwnerUid` for Android 10+](https://developer.android.com/reference/android/net/ConnectivityManager.html#getConnectionOwnerUid(int,%20java.net.InetSocketAddress,%20java.net.InetSocketAddress))).
3. Drop UDP sockets actively when we receive ICMP unreachable messages. However, this would require a `recvmsg` syscall which is neither supported by std nor tokio. https://github.com/rust-lang/rfcs/issues/2931

**Comment by zonyitoo** [comment]
Drops association when `UDP ASSOCIATE`'s TCP connection is closed?

**Comment by Mygod** [comment]
Yes but it requires the application to support this `UDP ASSOCIATE` command as well, in particular, tun interfaces operates on IP level so it will not know when UDP socket is closed either. An alternative is to use other kernel API like `/proc/net/udp`.

On the other hand, maybe if we use `UdpSocket::connect` it will properly return `ECONNREFUSED` when we `send`/`recv`? That would be useful too.

**Comment by zonyitoo** [comment]
> On the other hand, maybe if we use `UdpSocket::connect` it will properly return `ECONNREFUSED` when we `send`/`recv`? That would be useful too.

This is the prefered solution.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/3b47fa67fac6c2bded73616a284f26c6159cbe9a/src/relay/sys/windows/mod.rs#L38-L48

ICMP port unreachable errors are closed on purpose.

**Comment by Mygod** [comment]
However, we only use `UdpSocket::connect` for sslocal to ssserver connections. Every other UDP socket needs to communicate with multiple clients so it will not help much, i.e. we can only use it to close connections when ssserver is unreachable (e.g. due to connectivity change).

**Comment by zonyitoo** [comment]
It is ok to add a customized function to call `recvmsg`, as I have already done for `*-redir` implementations.

**Comment by Mygod** [comment]
We need to integrate it with mio too to make it async.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/3b47fa67fac6c2bded73616a284f26c6159cbe9a/src/relay/udprelay/redir/sys/unix/linux.rs#L56-L70

No you don't need mio.

BTW, please fix #265 first. @Mygod

**Comment by zonyitoo** [comment]
Tests on macOS:

nc -> sslocal -> ssserver -> nc

Settings: `udp_timeout: 5`, `udp_max_associations: 10`.

After the first packet, both `sslocal` and `ssserver` have created new fds:

`lsof -p ${sslocal_pid}`:

```
sslocal 46977 zonyitoo   13u    IPv4 0xe8869e9b57cb177b       0t0                 UDP localhost:61627->localhost:8288
sslocal 46977 zonyitoo   14u    IPv4 0xe8869e9b57cb0bdb       0t0                 UDP *:52299
```

`lsof -p ${ssserver_pid}`:

```
ssserver 46453 zonyitoo   13u    IPv4 0xe8869e9b6368131b      0t0                 UDP *:49907
```

After 5 seconds, all of these newly created fds are released.

So I think there is no fd leaks in UDP association implementation.

**Comment by zonyitoo** [comment]
Maybe default timeout of udp associations shouldn't be 5 minutes, which is too long.

UDP associations are used mostly for sending one packet.

**Comment by Mygod** [comment]
UDP sockets can usually send more than one packets... Our implementation of UDP DNS is pretty wasteful. On the other hand, I suspect the issue on those phones are erroneous implementations of UPnP (or something similar) creating a lot of short-lived sessions.

**Comment by zonyitoo** [comment]
I have tested with v2ray-plugin's QUIC mode:

```
CLIENT -> sslocal1(v2ray-plugin) -> sslocal2(tunnel) -> ssserver2(tunnel)  -> ssserver1(v2ray-plugin) -> REMOTE
```

And I saw both `sslocal2` and `ssserver2` kept only 1 association all the time.

**Comment by zonyitoo** [comment]
Reverted.
