### ISSUE TITLE
Domain name is re-resolved for every UDP packet

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#263]
This is *very* wasteful. Consider using `UdpSocket::connect` instead.

See also this for unexpected benefits: https://stackoverflow.com/a/51296247/2245107

**Comment by zonyitoo** [comment]
Use `UdpSocket::connect` for sockets local <-> server?

**Comment by Mygod** [comment]
I have a WIP. Let me finish it sometime.

**Comment by zonyitoo** [comment]
You should merge master before doing any modification. I have done some refactor.

**Comment by Mygod** [comment]
Cool!

**Comment by zonyitoo** [comment]
What you are going to optimize are blocks like:

https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/relay/udprelay/association.rs#L292-L296

but remote servers' addresses may change if they are domain name addresses.

**Comment by Mygod** [comment]
Yes and even so the same IP should be used for the same connection.
