### ISSUE TITLE
cargo install shadowsocks-rust failed in centos 7

### ISSUE THREAD

**Issue by djjowfy** [shadowsocks/shadowsocks-rust#266]
error: failed to compile `shadowsocks-rust v1.8.11`, intermediate artifacts can be found at `/tmp/cargo-install79EkdC`

Caused by:
  could not compile `regex-syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name regex_syntax /root/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.18/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="unicode"' --cfg 'feature="unicode-age"' --cfg 'feature="unicode-bool"' --cfg 'feature="unicode-case"' --cfg 'feature="unicode-gencat"' --cfg 'feature="unicode-perl"' --cfg 'feature="unicode-script"' --cfg 'feature="unicode-segment"' -C metadata=7953866535f48214 -C extra-filename=-7953866535f48214 --out-dir /tmp/cargo-install79EkdC/release/deps -L dependency=/tmp/cargo-install79EkdC/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)

**Comment by zonyitoo** [comment]
It is probably that you don't have enough memory for compiling.

**Comment by zonyitoo** [comment]
Close for inactivity.
