### ISSUE TITLE
latest master branch compilation failed

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#269]
error[E0308]: mismatched types
   --> src/relay/dnsrelay/mod.rs:225:43
    |
225 |             if should_forward_by_response(acl, &local_response, query) {
    |                                                                    ^^^ expected reference, found enum `std::option::Option`
    |
    = note: expected reference `&std::option::Option<acl::AccessControl>`
                    found enum `std::option::Option<&acl::AccessControl>`

51d21c4aab81dc97b2449df8c6a704c85abc59fc

**Comment by zonyitoo** [comment]
This is a problem, I can't verify it on my local environment.
