### ISSUE TITLE
more config file flag support

### ISSUE THREAD

**Issue by kuyagic** [shadowsocks/shadowsocks-rust#270]
I found some cli flag are not supported by a config file which will be very useful in systemd model like 
`--protocol` , `--tcp-redir` and `--udp-redir`

**Comment by zonyitoo** [comment]
I am very caution about adding non-standard fields into configure json definitions. Maybe some day it will conflict with other projects.

**Comment by Mygod** [comment]
A good option could be to prefix it with `rust-` or `shadowsocks-rust-`.

**Comment by zonyitoo** [comment]
ref shadowsocks-org#143

**Comment by zonyitoo** [comment]
Supported in v1.10.
