### ISSUE TITLE
Openwrt port

### ISSUE THREAD

**Issue by ghost** [shadowsocks/shadowsocks-rust#273]
It would be awesome to have an Openwrt port!

**Comment by zonyitoo** [comment]
I am not accessible to any routes running OpenWRT. Any PRs are welcome.

Just start with running the following command:

```bash
rustup target add mips-unknown-linux-musl
```

**Comment by cyber386** [comment]
> I am not accessible to any routes running OpenWRT. Any PRs are welcome.
> 
> Just start with running the following command:
> 
> ```shell
> rustup target add mips-unknown-linux-musl
> ```

Nope, that's not gonna work because ring doesn’t support MIPS, they don't even have a plan...

**Comment by zonyitoo** [comment]
Maybe we could disable any ciphers that depending on `ring`.

**Comment by cyber386** [comment]
Got some new problem:
```
   Compiling shadowsocks-rust v1.8.14 (/project)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> src/relay/flow.rs:6:18
  |
6 |         atomic::{AtomicU64, Ordering},
  |                  ^^^^^^^^^
  |                  |
  |                  no `AtomicU64` in `sync::atomic`
  |                  help: a similar name exists in the module: `AtomicU8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `shadowsocks-rust`.

To learn more, run the command again with --verbose.
```

https://doc.rust-lang.org/std/sync/atomic/#portability

- PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types.
- ARM platforms like armv5te that aren't for Linux do not have any atomics at all.
- ARM targets with thumbv6m do not have atomic operations at all.

**Comment by cyber386** [comment]
![image](https://user-images.githubusercontent.com/62885475/89520155-026d1100-d810-11ea-82e4-48d2a420a283.png)

**Comment by zonyitoo** [comment]
Tracking issue about MIPS support for `ring`: https://github.com/briansmith/ring/issues/562

**Comment by LuoZijun** [comment]
@zonyitoo PR #319  应该解决了这个问题？

**Comment by zonyitoo** [comment]
Yup. It is fixed already.
