### ISSUE TITLE
Release asserts cannot run under CentOS 7

### ISSUE THREAD

**Issue by abcfy2** [shadowsocks/shadowsocks-rust#275]
I just download https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.8.12/shadowsocks-v1.8.12.x86_64-unknown-linux-gnu.tar.xz. But running failed.

```
./ssserver -h
./ssserver: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./ssserver)
```

**Comment by zonyitoo** [comment]
Your system has an old glibc, which means that you have to use a musl version: shadowsocks-v1.8.12.x86_64-unknown-linux-musl.tar.xz

**Comment by abcfy2** [comment]
Oh thank you. The musl version could work both on CentOS 6 and CentOS 7.

By the way, for Linux, which version is better or prefer, musl or glibc ?

**Comment by zonyitoo** [comment]
http://www.etalabs.net/compare_libcs.html

**Comment by abcfy2** [comment]
Thank you.
