### ISSUE TITLE
compilation failed with latest code in ss-android module

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#277]
toolchain: nightly-x86_64-apple-darwin (default)
ss-android: https://github.com/shadowsocks/shadowsocks-android/commit/208d5369684efdbf0b38005c6a6078b8b37314b8
ss-rust: 1ae41274ade2a9ee5fa66d0cb5c04187b6052067

compilation's issue:
> Task :core:cargoBuildArm64
   Compiling shadowsocks-rust v1.8.13 (/develop/workspaces/shadowsocks-android/core/src/main/rust/shadowsocks-rust)
error[E0433]: failed to resolve: use of undeclared type or module `AsyncMutex`
   --> src/context.rs:319:35
    |
319 |             reverse_lookup_cache: AsyncMutex::new(LruCache::with_expiry_duration(Duration::from_secs(
    |                                   ^^^^^^^^^^ use of undeclared type or module `AsyncMutex`
error[E0412]: cannot find type `AsyncMutex` in this scope
   --> src/context.rs:258:27
    |
258 |     reverse_lookup_cache: AsyncMutex<LruCache<IpAddr, bool>>,
    |                           ^^^^^^^^^^ not found in this scope
error: aborting due to 2 previous errors

**Comment by zonyitoo** [comment]
Sorry for the mess.
