### ISSUE TITLE
移除 CFB128 分组工作模式

### ISSUE THREAD

**Issue by LuoZijun** [shadowsocks/shadowsocks-rust#287]
CFB 工作模式有 4 个子版本：

1. CFB1
2. CFB8
3. CFB64
4. CFB128

对称分组密码 和 CFB128 分组工作模式结合产生的 Cipher 并不能处理不定长的数据输入（明文和密文）,它要求输入数据的长度必须为 16 Bytes 的倍数。

CFB64 分组工作模式则要求输入数据的长度为 8 Bytes 的倍数。

CFB1 和 CFB8 要求输入数据是 1-bit 和 8-bit 的倍数，所以在以 byte 序列为输入的情况下，它总是处于已经对齐的状态。所以 CFB1 和 CFB8 可以作为流密码使用。

目前，SS 里面支持了 CFB128分组模式，这应该是一个错误。

Spec:

[6.3 The Cipher Feedback Mode, (Page-18)](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf)

**Comment by LuoZijun** [comment]
涉及的 Cipher:

*   aes-128-cfb
*   aes-128-cfb128
*   aes-192-cfb
*   aes-192-cfb128
*   aes-256-cfb
*   aes-256-cfb128
*   camellia-128-cfb
*   camellia-128-cfb128
*   camellia-192-cfb
*   camellia-192-cfb128
*   camellia-256-cfb
*   camellia-256-cfb128

**Comment by studentmain** [comment]
是的，教科书上是这样说的。不过不妨考虑考虑CFB操作模式是上一块密文的块加密结果与明文异或形成本段密文。通过对这一特性的利用，可以实现CFB128作流密码使用。

**Comment by LuoZijun** [comment]
@studentmain 当然有很多种方式可以让它变成一个流密码。但是规范在哪？

**Comment by studentmain** [comment]
不妨问问openssl enc

**Comment by studentmain** [comment]
若是想看看里面的代码，可以参考 https://www.github.com/shadowsocks/shadowsocks-windows/tree/v5/master/shadowsocks-csharp/Encryption/Stream/ExtendedCfbBlockCipher.cs 

对于CFB模式的一个块，明文与密文的bit一一对应，因此明文 1000000000000000 和 1234567890abcdef 的第一个密文字节是一样的

**Comment by studentmain** [comment]
进一步，对于任意的拥有 n bit 相同前缀的块，它们的密文的前 n bit 也一样。

更进一步，对于不完整的有 n bit 长的块，再其后填充任何数据都不影响密文的前 n bit。

反之，对于 n bit 长的不完整密文块，再其后填充任何数据都不影响明文的前 n bit。

**Comment by LuoZijun** [comment]
我明白你的意思了，就跟 OFB 一样。这样子的话，那就只有 CFB64 没法转换为 流密码了。

**Comment by LuoZijun** [comment]
https://github.com/LuoZijun/crypto/commit/4a98965bd66f812cb363d67c5602ff8ee76702b5

**Comment by studentmain** [comment]
CFB64需搭配使用64位块的块加密算法（Blowfish）以实现流加密。

**Comment by LuoZijun** [comment]
@studentmain 有相关 Spec 吗？如果只是某个库这样做的话，那就没必要了。

**Comment by studentmain** [comment]
操作方法和CFB128使用128位块加密（AES）时一致。此方法实际上被包括OpenSSL以及Golang密码库在内的众多密码学库广泛使用，至少是事实标准。Shadowsocks在早期添加rc4和rc4-md5时引入了OpenSSL依赖，进而引入了OpenSSL实现的一系列其他的流加密。

**Comment by LuoZijun** [comment]
喔，这个嘛。我并不看重 OpenSSL 的事实标准。

**Comment by LuoZijun** [comment]
另外，那些也已极度过时了，安全性方面，完整性方面、性能方面都没有优势。实际应用当中也没用广泛的应用。对实现它实在没兴趣。

**Comment by studentmain** [comment]
> 
> 
> 另外，那些也已极度过时了，安全性方面，完整性方面、性能方面都没有优势。实际应用当中也没用广泛的应用。对实现它实在没兴趣。

Shadowsocks 的所有流加密模式都已弃用了。在此保留的流加密实现的意义和提供 IE11 一样：除非万不得已不得用的兼容性工具。
