### ISSUE TITLE
Could not find OpenSSL in x86_64-pc-windows-msvc build

### ISSUE THREAD

**Issue by bdbai** [shadowsocks/shadowsocks-rust#288]
Executing binaries inside `shadowsocks-v1.8.15.x86_64-pc-windows-msvc.zip` gives

(libssl-1_1-x64.dll not found)
![image](https://user-images.githubusercontent.com/5270106/90617772-aeb3ec00-e241-11ea-83b3-6bbb57712f79.png)

(libcrypto-1_1-x64.dll not found)
![image](https://user-images.githubusercontent.com/5270106/90617795-b5dafa00-e241-11ea-9aa4-3cfe83015ca9.png)

Since these dependencies are supposed to be statically linked, I assume there is misconfiguration in the build process. `shadowsocks-v1.8.15.x86_64-pc-windows-gnu.zip` just works fine.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/ed0ca0dd4aa99c94693b39f47eb171021d9f3f6b/.github/workflows/build-release.yml#L74

`OPENSSL_STATIC` is already set to `"1"`.. Hmm..

**Comment by bdbai** [comment]
@zonyitoo is it reproducible on your side?

**Comment by zonyitoo** [comment]
I don't have any Windows devices. Could you reproduce it by running this script with environment variable set `OPENSSL_STATIC`?

https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/build-host-release.ps1

**Comment by zonyitoo** [comment]
Oh. I have specified `openssl-vendored` feature in this build script. Hmm, it should be linked statically.

**Comment by bdbai** [comment]
> I don't have any Windows devices. Could you reproduce it by running this script with environment variable set to `OPENSSL_STATIC=1`?
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/build-host-release.ps1

Still reproducible using this script. Detailed raw console log:

<details><pre><code>
PS D:\proj\ytflow> git clone -b master https://github.com/shadowsocks/shadowsocks-rust
Cloning into 'shadowsocks-rust'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9377 (delta 0), reused 0 (delta 0), pack-reused 9370
Receiving objects: 100% (9377/9377), 2.79 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (6698/6698), done.
PS D:\proj\ytflow> cd .\shadowsocks-rust\
PS D:\proj\ytflow\shadowsocks-rust> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\bdbai\.rustup

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc
stage1

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.45.2 (d3fb005a3 2020-07-31)

PS D:\proj\ytflow\shadowsocks-rust> rustup update
info: syncing channel updates for 'stable-i686-pc-windows-msvc'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2020-08-20, rust version 1.47.0-nightly (32c654a97 2020-08-19)
info: downloading component 'rustfmt'
info: downloading component 'rls'
info: downloading component 'rust-analysis'
info: downloading component 'rust-src'
info: downloading component 'cargo'
info: downloading component 'rust-std'
 17.4 MiB /  17.4 MiB (100 %)  11.2 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 11.2 MiB /  40.6 MiB ( 28 %)   0 B/s in  1s ETA: Unknown
PS D:\proj\ytflow\shadowsocks-rust> $env:OPENSSL_STATIC=1
PS D:\proj\ytflow\shadowsocks-rust> .\build\build-host-release.ps1
Started building release for x86_64-pc-windows-msvc ...
  Downloaded aead v0.2.0
  Downloaded block-cipher-trait v0.6.2
  Downloaded aes-siv v0.2.0
  Downloaded crypto-mac v0.7.0
  Downloaded enum-as-inner v0.3.3
  Downloaded hostname v0.3.1
  Downloaded ipnet v2.3.0
  Downloaded checked_int_cast v1.0.0
  Downloaded lru_time_cache v0.10.0
  Downloaded miow v0.3.5
  Downloaded resolv-conf v0.6.3
  Downloaded strum v0.18.0
  Downloaded tower v0.3.1
  Downloaded tower-limit v0.3.1
  Downloaded tower-timeout v0.3.0
  Downloaded tracing-core v0.1.13
  Downloaded aes v0.3.2
  Downloaded async-trait v0.1.36
  Downloaded untrusted v0.7.1
  Downloaded byte_string v1.0.0
  Downloaded ctr v0.3.2
  Downloaded hmac v0.7.1
  Downloaded iprange v0.6.3
  Downloaded mio-named-pipes v0.1.7
  Downloaded pmac v0.2.0
  Downloaded strum_macros v0.18.0
  Downloaded tower-buffer v0.3.0
  Downloaded tower-load-shed v0.3.0
  Downloaded webpki v0.21.3
  Downloaded zeroize v1.1.0
  Downloaded base64 v0.12.3
  Downloaded tracing v0.1.18
  Downloaded match_cfg v0.1.0
  Downloaded dbl v0.2.1
  Downloaded tokio-rustls v0.13.1
  Downloaded tower-load v0.3.0
  Downloaded openssl-src v111.10.2+1.1.1g
  Downloaded tracing-attributes v0.1.9
  Downloaded webpki-roots v0.19.0
  Downloaded chrono v0.4.13
  Downloaded h2 v0.2.6
  Downloaded indexmap v1.5.1
  Downloaded stream-cipher v0.3.2
  Downloaded json5 v0.2.8
  Downloaded tower-util v0.3.1
  Downloaded bloomfilter v1.0.3
  Downloaded tower-retry v0.3.0
  Downloaded hyper v0.13.7
  Downloaded subtle v1.0.0
  Downloaded qrcode v0.12.0
  Downloaded tower-layer v0.3.0
  Downloaded aes-soft v0.3.3
  Downloaded widestring v0.4.2
  Downloaded trust-dns-proto v0.19.5
  Downloaded mio-uds v0.6.8
  Downloaded ring v0.16.15
  Downloaded tower-discover v0.3.0
  Downloaded clap v2.33.2
  Downloaded trust-dns-resolver v0.19.5
  Downloaded ipconfig v0.2.2
  Downloaded try-lock v0.2.3
  Downloaded cmac v0.2.0
  Downloaded hkdf v0.8.0
  Downloaded libsodium-sys v0.2.6
  Downloaded term_size v0.3.2
  Downloaded miscreant v0.5.2
  Downloaded 66 crates (17.2 MB) in 1m 03s (largest was `ring` at 5.3 MB)
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.74
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling memchr v2.3.3
   Compiling winapi-build v0.1.1
   Compiling typenum v1.12.0
   Compiling autocfg v1.0.0
   Compiling futures-core v0.3.5
   Compiling slab v0.4.2
   Compiling pin-project-internal v0.4.23
   Compiling winapi v0.2.8
   Compiling fnv v1.0.7
   Compiling iovec v0.1.4
   Compiling cc v1.0.58
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.4.1
   Compiling bytes v0.5.6
   Compiling pin-project-lite v0.1.7
   Compiling proc-macro-nested v0.1.6
   Compiling futures-sink v0.3.5
   Compiling tower-service v0.3.0
   Compiling once_cell v1.4.0
   Compiling proc-macro-hack v0.5.18
   Compiling byteorder v1.3.4
   Compiling futures-io v0.3.5
   Compiling pin-utils v0.1.0
   Compiling getrandom v0.1.14
   Compiling pkg-config v0.3.18
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling subtle v1.0.0
   Compiling tinyvec v0.3.3
   Compiling serde_derive v1.0.114
   Compiling tower-layer v0.3.0
   Compiling matches v0.1.8
   Compiling opaque-debug v0.2.3
   Compiling itoa v0.4.6
   Compiling vcpkg v0.2.10
   Compiling unicode-segmentation v1.6.0
   Compiling ucd-trie v0.1.3
   Compiling ppv-lite86 v0.2.8
   Compiling serde v1.0.114
   Compiling gimli v0.22.0
   Compiling adler v0.2.3
   Compiling byte-tools v0.3.1
   Compiling bitflags v1.2.1
   Compiling percent-encoding v2.1.0
   Compiling maplit v1.0.2
   Compiling httparse v1.3.4
   Compiling ryu v1.0.5
   Compiling match_cfg v0.1.0
   Compiling base64 v0.11.0
   Compiling ipconfig v0.2.2
   Compiling object v0.20.0
   Compiling rustc-demangle v0.1.16
   Compiling quick-error v1.2.3
   Compiling regex-syntax v0.6.18
   Compiling zeroize v1.1.0
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.30
   Compiling linked-hash-map v0.5.3
   Compiling unicode-width v0.1.8
   Compiling serde_json v1.0.57
   Compiling widestring v0.4.2
   Compiling native-tls v0.2.4
   Compiling try-lock v0.2.3
   Compiling fake-simd v0.1.2
   Compiling siphasher v0.3.3
   Compiling ipnet v2.3.0
   Compiling dtoa v0.4.6
   Compiling vec_map v0.8.2
   Compiling bit-vec v0.6.2
   Compiling checked_int_cast v1.0.0
   Compiling strsim v0.8.0
   Compiling strum v0.18.0
   Compiling lru_time_cache v0.10.0
   Compiling byte_string v1.0.0
   Compiling mio-uds v0.6.8
   Compiling base64 v0.12.3
   Compiling tracing-core v0.1.13
   Compiling thread_local v1.0.1
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling lock_api v0.3.4
   Compiling futures-channel v0.3.5
   Compiling openssl-src v111.10.2+1.1.1g
   Compiling hashbrown v0.8.2
   Compiling indexmap v1.5.1
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling futures-task v0.3.5
   Compiling unicode-bidi v0.3.4
   Compiling http v0.2.1
   Compiling unicode-normalization v0.1.13
   Compiling pest v2.1.3
   Compiling heck v0.3.1
   Compiling miniz_oxide v0.4.0
   Compiling block-padding v0.1.5
   Compiling foreign-types v0.3.2
   Compiling lru-cache v0.1.2
   Compiling addr2line v0.13.0
   Compiling iprange v0.6.3
   Compiling qrcode v0.12.0
   Compiling ring v0.16.15
   Compiling openssl-sys v0.9.58
   Compiling idna v0.2.0
   Compiling pest_meta v2.1.3
   Compiling http-body v0.3.1
   Compiling want v0.3.0
   Compiling aho-corasick v0.7.13
   Compiling num_cpus v1.13.0
   Compiling backtrace v0.3.50
   Compiling libsodium-sys v0.2.6
   Compiling quote v1.0.7
   Compiling rand_core v0.5.1
   Compiling generic-array v0.12.3
   Compiling url v2.1.1
   Compiling regex v1.3.9
   Compiling rand_chacha v0.2.2
   Compiling block-cipher-trait v0.6.2
   Compiling crypto-mac v0.7.0
   Compiling dbl v0.2.1
   Compiling digest v0.8.1
   Compiling stream-cipher v0.3.2
   Compiling block-buffer v0.7.3
   Compiling aead v0.2.0
   Compiling socket2 v0.3.12
   Compiling net2 v0.2.34
   Compiling parking_lot_core v0.7.2
   Compiling atty v0.2.14
   Compiling winreg v0.6.2
   Compiling time v0.1.43
   Compiling term_size v0.3.2
   Compiling schannel v0.1.19
   Compiling hostname v0.3.1
   Compiling winapi-util v0.1.5
   Compiling rand v0.7.3
   Compiling aes-soft v0.3.3
   Compiling pmac v0.2.0
   Compiling cmac v0.2.0
   Compiling hmac v0.7.1
   Compiling ctr v0.3.2
   Compiling md-5 v0.8.0
   Compiling sha-1 v0.8.2
   Compiling miow v0.3.5
   Compiling miow v0.2.1
   Compiling parking_lot v0.10.2
   Compiling textwrap v0.11.0
   Compiling chrono v0.4.13
   Compiling resolv-conf v0.6.3
   Compiling webpki v0.21.3
   Compiling sct v0.6.0
   Compiling termcolor v1.1.0
   Compiling pest_generator v2.1.3
   Compiling aes v0.3.2
   Compiling hkdf v0.8.0                                                                                                error[E0463]: can't find crate for `aesni`                                                                                --> C:\Users\bdbai\.cargo\registry\src\github.com-1ecc6299db9ec823\aes-0.3.2\src\lib.rs:61:1                             |                                                                                                                    61 | extern crate aesni;                                                                                                   | ^^^^^^^^^^^^^^^^^^^ can't find crate                                                                               
   Compiling bloomfilter v1.0.3
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `aes`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
1.8.16
D:\proj\ytflow\shadowsocks-rust\build\release
shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip


    Directory: D:\proj\ytflow\shadowsocks-rust\build

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2020/8/20    14:09                release
Compress-Archive: D:\proj\ytflow\shadowsocks-rust\build\build-host-release.ps1:35
Line |
  35 |  Compress-Archive @CompressParam
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The path 'sslocal.exe' either does not exist or is not a valid file system path.

PS D:\proj\ytflow\shadowsocks-rust\target\release> cd ../..
PS D:\proj\ytflow\shadowsocks-rust> $env:RUSTFLAGS="-C target-cpu=native"
PS D:\proj\ytflow\shadowsocks-rust> .\build\build-host-release.ps1
Started building release for x86_64-pc-windows-msvc ...
  Downloaded aesni v0.6.0
  Downloaded 1 crate (100.7 KB) in 5.40s
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.74
   Compiling memchr v2.3.3
   Compiling log v0.4.11
   Compiling winapi-build v0.1.1
   Compiling lazy_static v1.4.0
   Compiling typenum v1.12.0
   Compiling futures-core v0.3.5
   Compiling autocfg v1.0.0
   Compiling slab v0.4.2
   Compiling pin-project-internal v0.4.23
   Compiling winapi v0.2.8
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.4.1
   Compiling iovec v0.1.4
   Compiling fnv v1.0.7
   Compiling cc v1.0.58
   Compiling bytes v0.5.6
   Compiling pin-project-lite v0.1.7
   Compiling futures-sink v0.3.5
   Compiling proc-macro-nested v0.1.6
   Compiling tower-service v0.3.0
   Compiling once_cell v1.4.0
   Compiling proc-macro-hack v0.5.18
   Compiling futures-io v0.3.5
   Compiling pin-utils v0.1.0
   Compiling pkg-config v0.3.18
   Compiling getrandom v0.1.14
   Compiling untrusted v0.7.1
   Compiling subtle v1.0.0
   Compiling spin v0.5.2
   Compiling tower-layer v0.3.0
   Compiling matches v0.1.8
   Compiling tinyvec v0.3.3
   Compiling serde_derive v1.0.114
   Compiling itoa v0.4.6
   Compiling opaque-debug v0.2.3
   Compiling byteorder v1.3.4
   Compiling vcpkg v0.2.10
   Compiling unicode-segmentation v1.6.0
   Compiling ucd-trie v0.1.3
   Compiling serde v1.0.114
   Compiling ppv-lite86 v0.2.8
   Compiling maplit v1.0.2
   Compiling percent-encoding v2.1.0
   Compiling bitflags v1.2.1
   Compiling byte-tools v0.3.1
   Compiling adler v0.2.3
   Compiling gimli v0.22.0
   Compiling ipconfig v0.2.2
   Compiling match_cfg v0.1.0
   Compiling object v0.20.0
   Compiling rustc-demangle v0.1.16
   Compiling ryu v1.0.5
   Compiling httparse v1.3.4
   Compiling base64 v0.11.0
   Compiling unicode-width v0.1.8
   Compiling serde_json v1.0.57
   Compiling openssl v0.10.30
   Compiling quick-error v1.2.3
   Compiling widestring v0.4.2
   Compiling zeroize v1.1.0
   Compiling regex-syntax v0.6.18
   Compiling linked-hash-map v0.5.3
   Compiling native-tls v0.2.4
   Compiling foreign-types-shared v0.1.1
   Compiling try-lock v0.2.3
   Compiling bit-vec v0.6.2
   Compiling fake-simd v0.1.2
   Compiling vec_map v0.8.2
   Compiling siphasher v0.3.3
   Compiling strsim v0.8.0
   Compiling ipnet v2.3.0
   Compiling dtoa v0.4.6
   Compiling checked_int_cast v1.0.0
   Compiling strum v0.18.0
   Compiling mio-uds v0.6.8
   Compiling lru_time_cache v0.10.0
   Compiling base64 v0.12.3
   Compiling byte_string v1.0.0
   Compiling tracing-core v0.1.13
   Compiling thread_local v1.0.1
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling lock_api v0.3.4
   Compiling futures-channel v0.3.5
   Compiling futures-task v0.3.5
   Compiling openssl-src v111.10.2+1.1.1g
   Compiling hashbrown v0.8.2
   Compiling num-traits v0.2.12
   Compiling indexmap v1.5.1
   Compiling num-integer v0.1.43
   Compiling unicode-bidi v0.3.4
   Compiling http v0.2.1
   Compiling unicode-normalization v0.1.13
   Compiling pest v2.1.3
   Compiling heck v0.3.1
   Compiling block-padding v0.1.5
   Compiling miniz_oxide v0.4.0
   Compiling lru-cache v0.1.2
   Compiling foreign-types v0.3.2
   Compiling addr2line v0.13.0
   Compiling iprange v0.6.3
   Compiling qrcode v0.12.0
   Compiling ring v0.16.15
   Compiling openssl-sys v0.9.58
   Compiling idna v0.2.0
   Compiling pest_meta v2.1.3
   Compiling http-body v0.3.1
   Compiling want v0.3.0
   Compiling aho-corasick v0.7.13
   Compiling num_cpus v1.13.0
   Compiling backtrace v0.3.50
   Compiling libsodium-sys v0.2.6
   Compiling quote v1.0.7
   Compiling rand_core v0.5.1
   Compiling generic-array v0.12.3
   Compiling url v2.1.1
   Compiling regex v1.3.9
   Compiling rand_chacha v0.2.2
   Compiling block-cipher-trait v0.6.2
   Compiling crypto-mac v0.7.0
   Compiling dbl v0.2.1
   Compiling digest v0.8.1
   Compiling stream-cipher v0.3.2
   Compiling aead v0.2.0
   Compiling block-buffer v0.7.3
   Compiling socket2 v0.3.12
   Compiling net2 v0.2.34
   Compiling parking_lot_core v0.7.2
   Compiling winapi-util v0.1.5
   Compiling winreg v0.6.2
error: failed to run custom build command for `openssl-sys v0.9.58`                                                                                                                                                                             Caused by:                                                                                                                process didn't exit successfully: `D:\proj\ytflow\shadowsocks-rust\target\release\build\openssl-sys-7f26fa8aa9f24890\build-script-main` (exit code: 101)                                                                                      --- stdout                                                                                                              cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
running "perl" "./Configure" "--prefix=D:\\proj\\ytflow\\shadowsocks-rust\\target\\release\\build\\openssl-sys-689fc360101c3a8c\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', C:\Users\bdbai\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.10.2+1.1.1g\src\lib.rs:408:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
1.8.16
D:\proj\ytflow\shadowsocks-rust\build\release
shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
Compress-Archive: D:\proj\ytflow\shadowsocks-rust\build\build-host-release.ps1:35
Line |
  35 |  Compress-Archive @CompressParam
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The path 'sslocal.exe' either does not exist or is not a valid file system path.

PS D:\proj\ytflow\shadowsocks-rust\target\release> .\build\build-host-release.ps1
.\build\build-host-release.ps1: The term '.\build\build-host-release.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS D:\proj\ytflow\shadowsocks-rust\target\release> cd ../..
PS D:\proj\ytflow\shadowsocks-rust> .\build\build-host-release.ps1
Started building release for x86_64-pc-windows-msvc ...
   Compiling hostname v0.3.1
   Compiling schannel v0.1.19
   Compiling atty v0.2.14
   Compiling term_size v0.3.2
   Compiling time v0.1.43
   Compiling openssl-sys v0.9.58
   Compiling miow v0.3.5
   Compiling parking_lot v0.10.2
   Compiling termcolor v1.1.0
   Compiling ipconfig v0.2.2
   Compiling miow v0.2.1
   Compiling webpki v0.21.3
   Compiling sct v0.6.0
   Compiling textwrap v0.11.0
   Compiling resolv-conf v0.6.3
   Compiling native-tls v0.2.4
   Compiling libsodium-sys v0.2.6
   Compiling pest_generator v2.1.3
   Compiling pin-project-internal v0.4.23
   Compiling tokio-macros v0.2.5
   Compiling futures-macro v0.3.5
   Compiling tracing-attributes v0.1.9
   Compiling serde_derive v1.0.114
   Compiling thiserror-impl v1.0.20
error: failed to run custom build command for `openssl-sys v0.9.58`                                                                                                                                                                             Caused by:                                                                                                                process didn't exit successfully: `D:\proj\ytflow\shadowsocks-rust\target\release\build\openssl-sys-7f26fa8aa9f24890\build-script-main` (exit code: 101)                                                                                      --- stdout                                                                                                              cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset
running "perl" "./Configure" "--prefix=D:\\proj\\ytflow\\shadowsocks-rust\\target\\release\\build\\openssl-sys-689fc360101c3a8c\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', C:\Users\bdbai\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.10.2+1.1.1g\src\lib.rs:408:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
1.8.16
D:\proj\ytflow\shadowsocks-rust\build\release
shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
Compress-Archive: D:\proj\ytflow\shadowsocks-rust\build\build-host-release.ps1:35
Line |
  35 |  Compress-Archive @CompressParam
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The path 'sslocal.exe' either does not exist or is not a valid file system path.

PS D:\proj\ytflow\shadowsocks-rust\target\release> $env:PATH+=";D:\soft\Strawberry\perl\bin;"
PS D:\proj\ytflow\shadowsocks-rust\target\release> cd ../..
PS D:\proj\ytflow\shadowsocks-rust> .\build\build-host-release.ps1
Started building release for x86_64-pc-windows-msvc ...
   Compiling openssl-sys v0.9.58
   Compiling async-trait v0.1.36
   Compiling enum-as-inner v0.3.3
   Compiling strum_macros v0.18.0
   Compiling clap v2.33.2
   Compiling aesni v0.6.0
   Compiling pmac v0.2.0
   Compiling ctr v0.3.2
   Compiling cmac v0.2.0
   Compiling hmac v0.7.1
   Compiling md-5 v0.8.0
   Compiling sha-1 v0.8.2
   Compiling mio v0.6.22
   Compiling rand v0.7.3
   Compiling rustls v0.17.0
   Compiling env_logger v0.7.1
   Compiling webpki-roots v0.19.0
   Compiling chrono v0.4.13
   Compiling pin-project v0.4.23
   Compiling tracing v0.1.18
   Compiling serde v1.0.114
   Compiling pest_derive v2.1.0
   Compiling thiserror v1.0.20
   Compiling hkdf v0.8.0
   Compiling aes v0.3.2
   Compiling mio-named-pipes v0.1.7
   Compiling bloomfilter v1.0.3
   Compiling rustls-native-certs v0.3.0
   Compiling futures-util v0.3.5
   Compiling tower-discover v0.3.0
   Compiling tower-load-shed v0.3.0
   Compiling aes-siv v0.2.0
   Compiling tokio v0.2.22                                                                                                 Compiling miscreant v0.5.2                                                                                              Compiling serde_json v1.0.57                                                                                            Compiling json5 v0.2.8                                                                                                  Compiling serde_urlencoded v0.6.1                                                                                       Compiling tower-load v0.3.0                                                                                             Compiling tokio-util v0.3.1
   Compiling tower-timeout v0.3.0
   Compiling tower-buffer v0.3.0
   Compiling tower-retry v0.3.0
   Compiling tokio-rustls v0.13.1
   Compiling futures-executor v0.3.5
   Compiling tower-util v0.3.1
   Compiling tower-limit v0.3.1
   Compiling h2 v0.2.6
   Compiling futures v0.3.5
   Compiling tower v0.3.1
   Compiling trust-dns-proto v0.19.5
   Compiling trust-dns-resolver v0.19.5
   Compiling hyper v0.13.7
   Compiling openssl v0.10.30
   Compiling shadowsocks-rust v1.8.16 (D:\proj\ytflow\shadowsocks-rust)
    Finished release [optimized] target(s) in 7m 48s
1.8.16
D:\proj\ytflow\shadowsocks-rust\build\release
shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
Created release packet D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip
Created release packet checksum D:\proj\ytflow\shadowsocks-rust\build\release\shadowsocks-v1.8.16.x86_64-pc-windows-msvc.zip.sha256
PS D:\proj\ytflow\shadowsocks-rust\target\release>
</code></pre></details>

**Comment by zonyitoo** [comment]
Please try with this release: https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.8.16

**Comment by bdbai** [comment]
> Please try with this release: https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.8.16

![image](https://user-images.githubusercontent.com/5270106/90739639-4a586180-e301-11ea-9d67-cee612e74f54.png)
![image](https://user-images.githubusercontent.com/5270106/90739734-517f6f80-e301-11ea-9112-956054df9aab.png)

**Comment by zonyitoo** [comment]
I have no idea why this happen.

https://github.com/shadowsocks/shadowsocks-rust/blob/4fd4ac5bbe29d9294b15abb422d82108e8a3a2fc/build/build-host-release.ps1#L13

I have already set `openssl-vendored`, which will eventually set `vendored` feature to the `openssl` crate.

Could you help figuring out why openssl-sys didn't link openssl-src's output statically? :(

**Comment by bdbai** [comment]
Appending `-C target-feature=+crt-static` to `RUSTFLAGS` works like a charm, see https://github.com/sfackler/rust-openssl/issues/1063#issuecomment-466821257.

**Comment by zonyitoo** [comment]
Please try again with this release: https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.8.16

**Comment by bdbai** [comment]
There seems no difference in this release? Kinda weird...

**Comment by zonyitoo** [comment]
@bdbai Please download it again.

**Comment by studentmain** [comment]
![图片](https://user-images.githubusercontent.com/17123090/90757078-ae146780-e2cc-11ea-8e27-9546906035b6.png)

Seems it has no libssl dependency now

> 
> 
> @bdbai Please download it again.

**Comment by bdbai** [comment]
@zonyitoo The latest release works on my machine, with a couple of megabytes increased in size for each binary. Good work!
