### ISSUE TITLE
Panick in UDP assoc

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#293]
```
ERROR failed to create UDP association, Address family not supported by protocol (os error 97)
ERROR one of servers exited unexpectly, result: Err(Os { code: 97, kind: Other, message: "Address family not supported by protocol" })
thread 'main' panicked at 'aborted with server exited unexpectly', src/bin/local.rs:382:45
```

**Comment by Mygod** [comment]
To reproduce: send a UDP packet with domain name as remote.

So something wrong here? https://github.com/shadowsocks/shadowsocks-rust/blob/36a14836e08e5b3c327198e52d6cb86b4bcdf95b/src/relay/udprelay/association.rs#L209

**Comment by zonyitoo** [comment]
`EAFNOSUPPORT` error is probably being returned from `bind()`, which is called in `UdpSocket::connect`.

```
The specified address is not a valid address for the address family of the specified socket.
```

Interesting. I am curious about the value of `addr`.

**Comment by Mygod** [comment]
It should be an IPv4 address. I don't think I have set up an AAAA record for it.

**Comment by zonyitoo** [comment]
It shouldn't crash anyway. Please test again with this commit.

**Comment by Mygod** [comment]
Sorry I've been busy. Let me test it later.

**Comment by Mygod** [comment]
Hmm I was running 74688d8a97f4e67132272ebc78d5e242bf269c68 (on shadowsocks-android) but I can no longer reproduce this on latest master now. I will assume it is fixed for now. :rofl:
