### ISSUE TITLE
Running in single-threaded mode, there is a high chance of bad performance

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#300]
https://github.com/shadowsocks/shadowsocks-rust/blob/8eeda75a7206924260c7a7e20b24635d545ea8ac/Cargo.toml#L57

我的服务器用haproxy用负载均衡，他的后端运行的是ssserver。
手机端用ss，在youtube视频结尾加载出广告前，点击下个视频，有很大几率被卡死。
我分析原因是这样的。
有可能上段视频的结尾广告虽然未加载出来，但请求已经发出，服务端准备、或正在返回数据。这时我点击另一段视频的请求，虽然请求被发送上服务端，但也要等上一个请求处理完毕后，才会切换处理新的请求。
为了验证我的猜测，我把android、服务端的程序，屏蔽单线程模式后重新编译并安装，发现卡死的现象确实有减少了。

不知我的猜测、验证是否正确？

附haproxy主要运行配置：
client timeout 3m
server timeout 10m
connect 2s
client-fin 5s
server-fin 5s
nbthread 4
tcp mode

**Comment by zonyitoo** [comment]
> 有可能上段视频的结尾广告虽然未加载出来，但请求已经发出，服务端准备、或正在返回数据。这时我点击另一段视频的请求，虽然请求被发送上服务端，但也要等上一个请求处理完毕后，才会切换处理新的请求。

If that is true, there are several possibilities:

1. Some tasks were always "Ready", so it always kept running and didn't have a chance to let scheduler to switch between tasks, in other word, starvation.
2. There were some long blocking calls makes it impossible for a single thread scheduler to switch between tasks.

**Comment by zonyitoo** [comment]
@dev4u Did you see the same problem on the libev version?

**Comment by dev4u** [comment]
没有，回去我试试这种组合。估计需要测试2、3天才能有结果反馈给你。

**Comment by dev4u** [comment]
> @dev4u Did you see the same problem on the libev version?

在libev下，上面的现象没有发生。希望之前的是网络不稳定导致。

**Comment by zonyitoo** [comment]
In the same time, could you test with Rust's `ssserver` or `sslocal` that you were using previously.
