### ISSUE TITLE
Support [SIP008] Online Config

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#302]
https://github.com/shadowsocks/shadowsocks-org/issues/89

This feature allows `sslocal` to update configurations dynamically from a config that hosts on a HTTPS server.

**Comment by DuckSoft** [comment]
did you mean something like this?

```ss-local --sip008 '{"server":"xxxxxx","port":12345,"password":"somerandomnode","method":"aes-128-gcm"}' ....```

**Comment by zonyitoo** [comment]
```
$ sslocal --sip008 "https://URL-TO-SSCONF"
```

Maybe something like this.

**Comment by fernvenue** [comment]
This is gonna be a great feature.

**Comment by zonyitoo** [comment]
Because in practice, the SIP008 configuration file get from an URL usually require some modification. So what I was doing is:

1. Add a crontab script to download the SIP008 configuration file from an URL
2. Do my modifications, produce a new configuration file
3. Send a signal to `sslocal` process, and let it reload the configuration file

**Comment by fernvenue** [comment]
What if make it work as an alternative of `"servers": []` part for `sslocal` and `ssservice local`? We can still do our modifications locally.

**Comment by zonyitoo** [comment]
There may be quite a lot of works to do:

1. Run a background task for pulling SIP008 configurations in a fix interval. (EASY)
2. `PingBalancer` supports updating servers separately from different sources (command line, configuration file, SIP008).
3. Make HTTPS requests to SIP008 URL:
    - Which HTTP library? `reqwest` should be a choice.
    - Which TLS library? `rust-tls` for using system provided TLS framework, or `rustls`. 
    - HTTP's outbound sockets should follow the `outbound-*` configurations. (HARD)

Still wondering how to customize the sockets with `reqwest`'s API.

**Comment by fernvenue** [comment]
Glad to see shadowsocks-rust supports SIP008 since [v1.16.2](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.16.2).
