### ISSUE TITLE
Need I use the server_block_local.acl to enhance security？

### ISSUE THREAD

**Issue by mxdh** [shadowsocks/shadowsocks-rust#304]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/server_block_local.acl

Or just like https://github.com/shadowsocks/shadowsocks/wiki/Block-Connection-to-localhost, localhost is blocked by default?

**Comment by zonyitoo** [comment]
You should use `server_block_local.acl`, localhost is not blocked by default.
