### ISSUE TITLE
failed to connect remote, Invalid argument (os error 22)

### ISSUE THREAD

**Issue by we1559** [shadowsocks/shadowsocks-rust#306]
error log

> 2020-10-28T15:03:42.862+00:00 INFO  shadowsocks 1.8.20
> 2020-10-28T15:03:42.865+00:00 INFO  shadowsocks TCP listening on *.*.*.*:*
> 2020-10-28T15:03:55.276+00:00 ERROR failed to connect remote github.com:443 via 127.0.0.1:0, Invalid argument (os error 22)
> 2020-10-28T15:03:55.518+00:00 ERROR failed to connect remote github.com:443 via 127.0.0.1:0, Invalid argument (os error 22)

The python server runs well, but the rust server report fail

the config is
> {
>    "server": "*.*.*.*",
>    "server_port": *,
>    "local_address": "127.0.0.1",
>    "local_port": 1080,
>    "password":"*",
>    "timeout":300,
>    "method":"xchacha20-ietf-poly1305",
>    "fast_open": true
> }

the python sserver runs with method: aes-256-gcm as it doesn't support xchacha20-ietf-poly1305

**Comment by mxdh** [comment]
You should remove the `local_address` and the `local_port`. In this way I successfully solved the same problem.
https://github.com/shadowsocks/shadowsocks-rust/issues/205#issuecomment-599203334

**Comment by we1559** [comment]
> You should remove the `local_address` and the `local_port`. In this way I successfully solved the same problem.
> [#205 (comment)](https://github.com/shadowsocks/shadowsocks-rust/issues/205#issuecomment-599203334)

thanks for your reply, it works.
