### ISSUE TITLE
没有后台运行的吗？

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#308]
libev版本添加-f参数就后台运行了rust版本没有找到，没有这个功能的话会很不方便。

**Comment by zonyitoo** [comment]
I believe all modern systems have all very easy-to-use process managers, like systemd, launchd, supervisor, ...

**Comment by zonyitoo** [comment]
This commit should resolve this issue.

**Comment by triaqu** [comment]
如果IPv6用公网IPv4用内网该怎么写呢？
