### ISSUE TITLE
tunnel无法正常使用的问题

### ISSUE THREAD

**Issue by xnyjdegh** [shadowsocks/shadowsocks-rust#310]
首先感谢各位作者的辛苦付出，产出了如此好用的工具。
因为英语不好，担心描述不准确，所以使用中文请教。

### 碰到的问题：

想在透明代理网关使用tunnel作为dns代理，但提示：

ERROR [shadowsocks::relay::udprelay::association] UDP association recv 127.0.0.1:39498 <- .., error: Connection refused (os error 111)

### 使用的部件：

rust版shadowsocks v1.8.20 amd64 + v2ray-plugin-linux-amd64-v1.3.1 + caddy  2.2.1 amd64（服务端）
下载地址：
shadowsocks-rust : https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.8.20/shadowsocks-v1.8.20.x86_64-unknown-linux-gnu.tar.xz
v2ray-plugin : https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz

### 服务端配置形如：

```
{
    "server":"0.0.0.0",
    "server_port": 10000,
    "password":"passwordpassword",
    "timeout":5,
    "method":"aes-256-gcm",
    "plugin": "v2ray-plugin",
    "plugin_opts": "server;path=/pathpath",
    "dns":"google",
    "mode":"tcp_and_udp"
}
```

### 客户端配置形如：

```
{
    "server": "xx.xx.xx",
    "server_port": 443,
    "password": "passwordpassword",
    "method": "aes-256-gcm",
    "timeout": 5,
    "local_port": 10053,
    "local_address": "0.0.0.0",
    "mode": "tcp_and_udp",
    "plugin": "v2ray-plugin",
    "plugin_opts": "tls;host=xx.xx.xx;path=/pathpath"
}
```

### Caddy配置形如：

```
xx.xx.xx {
        encode gzip
        reverse_proxy /pathpath 127.0.0.1:10000 {
                header_up -Origin
        }
	log {
        	output file /var/log/caddy/access.log
	}
}
```

### 现象：

```
窗口1启动tunnel：
/usr/local/bin/sslocal -c /usr/local/etc/ss-rust/config-tunnel.json -f 8.8.8.8:53 --protocol tunnel -v

服务端处窗口3作为服务器：
/usr/local/bin/ssserver -c /usr/local/etc/ss-rust/config.json -v

此时在
窗口2测试做dns请求：
dig @127.0.0.1 -p 10053 google.com

窗口1提示：
2020-11-02T13:50:24.286+08:00 DEBUG [shadowsocks::relay::udprelay::association] UDP association 127.0.0.1:56201 -> 8.8.8.8:53 (proxied) sent 51 bytes
2020-11-02T13:50:24.442+08:00 ERROR [shadowsocks::relay::udprelay::association] UDP association recv 127.0.0.1:56201 <- .., error: Connection refused (os error 111)
2020-11-02T13:50:29.286+08:00 DEBUG [shadowsocks::relay::udprelay::association] UDP association 127.0.0.1:56201 -> 8.8.8.8:53 (proxied) sent 51 bytes
2020-11-02T13:50:29.438+08:00 ERROR [shadowsocks::relay::udprelay::association] UDP association recv 127.0.0.1:56201 <- .., error: Connection refused (os error 111)
2020-11-02T13:50:34.286+08:00 DEBUG [shadowsocks::relay::udprelay::association] UDP association 127.0.0.1:56201 -> 8.8.8.8:53 (proxied) sent 51 bytes
2020-11-02T13:50:34.438+08:00 ERROR [shadowsocks::relay::udprelay::association] UDP association recv 127.0.0.1:56201 <- .., error: Connection refused (os error 111)

服务器处窗口3没有任何日志。
甚至caddy的log也没有任何日志。

在此前和此提示后我都有尝试启用socks5 启动：
/usr/local/bin/sslocal -c /usr/local/etc/ss-rust/config-tunnel.json 
可以正常代理访问，证明配置链应该是没有错的。
```

我原意是想单纯使用ss-redir来实现tcp和udp的透明代理，为了解决dns污染和避免中国内地网站也走远程dns解析，所以引入了smartdns配合https://github.com/felixonmars/dnsmasq-china-list.git 来做分流，非此列表的dns请求走redir，不无法正常工作（应该是因为只能接受iptables过来的流量而不能是应用层面的dns请求），所以启用tunnel启动于127.0.0.1:10053，但发现也无法解析国外域名，所以用dig测试。

**我有点怀疑是因为-f 参数我用错了，但是没有查到相关文档，只查到了libev版有-L的相关教程，应该是属于同一个作用，还请指教**

另附应该与此问题无关的iptables配置：

```
##################### SSREDIR #####################
iptables -t mangle -N SSREDIR

# connection-mark -> packet-mark
# restore-mark是把连接中的 mark 设置到数据包中
# 下面的--save-mark是把数据包的 mark 打到连接中
iptables -t mangle -A SSREDIR -j CONNMARK --restore-mark
# 如果包里的 mark 是 0x2333 就不处理它
iptables -t mangle -A SSREDIR -m mark --mark 0x2333 -j RETURN

# please modify MyIP, MyPort, etc.
# ignore traffic sent to ss-server
iptables -t mangle -A SSREDIR -d xx.xx.xx -j RETURN

# ignore traffic sent to reserved addresses
# 忽略传输到保留地址的流量
iptables -t mangle -A SSREDIR -d 0.0.0.0/8          -j RETURN
iptables -t mangle -A SSREDIR -d 10.0.0.0/8         -j RETURN
iptables -t mangle -A SSREDIR -d 100.64.0.0/10      -j RETURN
iptables -t mangle -A SSREDIR -d 127.0.0.0/8        -j RETURN
iptables -t mangle -A SSREDIR -d 169.254.0.0/16     -j RETURN
iptables -t mangle -A SSREDIR -d 172.16.0.0/12      -j RETURN
iptables -t mangle -A SSREDIR -d 192.0.0.0/24       -j RETURN
iptables -t mangle -A SSREDIR -d 192.0.2.0/24       -j RETURN
iptables -t mangle -A SSREDIR -d 192.88.99.0/24     -j RETURN
iptables -t mangle -A SSREDIR -d 192.168.0.0/16     -j RETURN
iptables -t mangle -A SSREDIR -d 198.18.0.0/15      -j RETURN
iptables -t mangle -A SSREDIR -d 198.51.100.0/24    -j RETURN
iptables -t mangle -A SSREDIR -d 203.0.113.0/24     -j RETURN
iptables -t mangle -A SSREDIR -d 224.0.0.0/4        -j RETURN
iptables -t mangle -A SSREDIR -d 240.0.0.0/4        -j RETURN
iptables -t mangle -A SSREDIR -d 255.255.255.255/32 -j RETURN

# 中国的IP忽略
iptables -t mangle -A SSREDIR -m set --match-set cidr_cn dst -j RETURN

# mark the first packet of the connection
# 标注 0x2333 到第一个数据包
iptables -t mangle -A SSREDIR -p tcp --syn                      -j MARK --set-mark 0x2333
iptables -t mangle -A SSREDIR -p udp -m conntrack --ctstate NEW -j MARK --set-mark 0x2333

# packet-mark -> connection-mark
# 把数据包里的 mark 打到连接中
iptables -t mangle -A SSREDIR -j CONNMARK --save-mark

##################### OUTPUT #####################
# proxy the outgoing traffic from this machine
# 代理从本机发出的流量
iptables -t mangle -A OUTPUT -p tcp -m addrtype --src-type LOCAL ! --dst-type LOCAL -j SSREDIR
iptables -t mangle -A OUTPUT -p udp -m addrtype --src-type LOCAL ! --dst-type LOCAL -j SSREDIR

##################### PREROUTING #####################
# proxy traffic passing through this machine (other->other)
# 流经本机的代理流量(其他机->其他机)
iptables -t mangle -A PREROUTING -p tcp -m addrtype ! --src-type LOCAL ! --dst-type LOCAL -j SSREDIR
iptables -t mangle -A PREROUTING -p udp -m addrtype ! --src-type LOCAL ! --dst-type LOCAL -j SSREDIR

# hand over the marked package to TPROXY for processing
# 将标记好的包装交给TPROXY处理。
iptables -t mangle -A PREROUTING -p tcp -m mark --mark 0x2333 -j TPROXY --on-ip 127.0.0.1 --on-port 60080
iptables -t mangle -A PREROUTING -p udp -m mark --mark 0x2333 -j TPROXY --on-ip 127.0.0.1 --on-port 60080
```

net.ipv4.ip_forward 开启了。

使用的ipset也已经正常处理了的。

**Comment by zonyitoo** [comment]
I believe your configuration is wrong.

Your `ssserver` is listening on `0.0.0.0:10000` based on your configuration, but your `sslocal` wants to connect to `xx.xx.xx:443`.

I couldn't reproduce on my laptop. You can verify it with by testcase:

```bash
# Start sslocal
$ sslocal -s 127.0.0.1:9300 -b 127.0.0.1:1081 -m rc4-md5 -k 1 -U -vv -f 114.114.114.114:53 --protocol tunnel

# Start ssserver
$ ssserver -s 127.0.0.1:9300 -m rc4-md5 -k 1 -U -vv

# Query baidu.com
$ dig @127.0.0.1 -p 1081 baidu.com

; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 1081 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42702
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;baidu.com.			IN	A

;; ANSWER SECTION:
baidu.com.		348	IN	A	220.181.38.148
baidu.com.		348	IN	A	39.156.69.79

;; Query time: 89 msec
;; SERVER: 127.0.0.1#1081(127.0.0.1)
;; WHEN: Mon Nov 02 15:51:46 CST 2020
;; MSG SIZE  rcvd: 70
```

**Comment by xnyjdegh** [comment]
> I believe your configuration is wrong.
> 
> Your `ssserver` is listening on `0.0.0.0:10000` based on your configuration, but your `sslocal` wants to connect to `xx.xx.xx:443`.
> 
> I couldn't reproduce on my laptop. You can verify it with by testcase:
> 
> ```shell
> # Start sslocal
> $ sslocal -s 127.0.0.1:9300 -b 127.0.0.1:1081 -m rc4-md5 -k 1 -U -vv -f 114.114.114.114:53 --protocol tunnel
> 
> # Start ssserver
> $ ssserver -s 127.0.0.1:9300 -m rc4-md5 -k 1 -U -vv
> 
> # Query baidu.com
> $ dig @127.0.0.1 -p 1081 baidu.com
> 
> ; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 1081 baidu.com
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42702
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 512
> ;; QUESTION SECTION:
> ;baidu.com.			IN	A
> 
> ;; ANSWER SECTION:
> baidu.com.		348	IN	A	220.181.38.148
> baidu.com.		348	IN	A	39.156.69.79
> 
> ;; Query time: 89 msec
> ;; SERVER: 127.0.0.1#1081(127.0.0.1)
> ;; WHEN: Mon Nov 02 15:51:46 CST 2020
> ;; MSG SIZE  rcvd: 70
> ```

感谢您的回复。
我因为使用了caddy，所以是监听在443，然后caddy从443转给10000处理。

**Comment by zonyitoo** [comment]
Then you are wrong. `dig` is sending request via UDP, so it is not sent through your `v2ray-plugin` in TLS protocol.

So your Caddy won't receive that request.

```
dig -> sslocal (127.0.0.1:10053) -> ssserver (127.0.0.1:443) -> 8.8.8.8:53
```

Plugins are only for TCP connections.

**Comment by zonyitoo** [comment]
You may try to let `dig` send its query via TCP like this:

```bash
$ dig @127.0.0.1 -p 1081 baidu.com +tcp
```

Then your Caddy should receive the data query request.

**Comment by xnyjdegh** [comment]
> Then you are wrong. `dig` is sending request via UDP, so data won't be sent through your `v2ray-plugin` in TLS protocol.
> 
> So your Caddy won't receive that request.
> 
> ```
> dig -> sslocal (127.0.0.1:10053) -> ssserver (127.0.0.1:443) -> 8.8.8.8:53
> ```
> 
> Plugins are only for TCP connections.

感谢指教。
我使用dig @127.0.0.1 -p 10053 google.com +tcp   可以正常使用了。

**Comment by zonyitoo** [comment]
Great.

**Comment by xnyjdegh** [comment]
> Great.



> You may try to let `dig` send its query via TCP like this:
> 
> ```shell
> $ dig @127.0.0.1 -p 10053 baidu.com +tcp
> ```
> 
> Then your Caddy should receive the data query request.
> 
> ```
> dig -> sslocal (TCP 127.0.0.1:10053) -> Caddy (TCP xx.xx:443) -> ssserver (TCP xx.xx:10000) -> TCP 8.8.8.8:53
> ```

另外还想请教一下，有没有任何办法可以让我只启用redir进程就解决我想把dns请求转交给redir的需求呢？不是很想开多一个tunnel。

**Comment by zonyitoo** [comment]
> > Great.
> 
> > You may try to let `dig` send its query via TCP like this:
> > ```shell
> > $ dig @127.0.0.1 -p 10053 baidu.com +tcp
> > ```
> > 
> > 
> > Then your Caddy should receive the data query request.
> > ```
> > dig -> sslocal (TCP 127.0.0.1:10053) -> Caddy (TCP xx.xx:443) -> ssserver (TCP xx.xx:10000) -> TCP 8.8.8.8:53
> > ```
> 
> 另外还想请教一下，有没有任何办法可以让我只启用redir进程就解决我想把dns请求转交给redir的需求呢？不是很想开多一个tunnel。

Could you please clearify your question?

```
clients -> iptables -> sslocal (REDIR ...:60080) -> Caddy (TCP :443) ->  ssserver (TCP :10000) -> remote
```

Is that correct?

**Comment by xnyjdegh** [comment]
> > > 大。
> > 
> > 
> > > 您可以尝试`dig`通过TCP这样发送其查询：
> > > ```shell
> > > $挖@ 127.0.0.1 -p 10053 baidu.com + tcp
> > > ```
> > > 
> > > 
> > > 然后，您的Caddy应该会收到数据查询请求。
> > > ```
> > > dig -> sslocal (TCP 127.0.0.1:10053) -> Caddy (TCP xx.xx:443) -> ssserver (TCP xx.xx:10000) -> TCP 8.8.8.8:53
> > > ```
> > 
> > 
> > 另外还想请教一下，有没有任何办法可以让我只启用redir进程就解决我想把dns请求转交给redir的需求呢？不是很想开多一个隧道。
> 
> 您能澄清您的问题吗？
> 
> ```
> clients -> iptables -> sslocal (REDIR ...:60080) -> Caddy (TCP :443) ->  ssserver (TCP :10000) -> remote
> ```
> 
> 那是对的吗？

嗯，想必你建议的这种做法是对的。
原提问里也有提到我的猜想，
“dns请求走redir，不能够正常工作（应该是因为只能接受iptables过来的流量，而不能是dns程序的dns请求）”
我应该是缺了clients -> iptables  的步骤，直接
```
clients -> iptables -> sslocal (REDIR ...:60080) -> Caddy (TCP :443) ->  ssserver (TCP :10000) -> remote
```
我以为ss-redir可以直接识别dig的tcp或udp的dns请求（也许dig发出的数据跟iptables数据不是同一类？我不是很明白这两者的区别）

**Comment by zonyitoo** [comment]
`dig` is one of the `clients`.

Have you tried digging directly with `dig baidu.com` or `dig google.com`?

**Comment by xnyjdegh** [comment]
> `dig`是其中之一`clients`。
> 
> 您是否尝试过直接使用`dig baidu.com`或进行挖掘`dig google.com`？



> `dig`是其中之一`clients`。
> 
> 您是否尝试过直接使用`dig baidu.com`或进行挖掘`dig google.com`？

我是clients -> sslocal (REDIR ...:60080) ，少了iptables那次转发。这应该是不行的。
这个是我的知识盲区，想知道在哪可以了解到client发出的udp或tcp的dns请求和转交给iptables后回来的udp或tcp请求的区别，以此来判断有没有更省一次iptables转发的方法
因为在我理解从Application Layer这一层流到Network Layer，在TPROXY的情况下，需要走OUTPUT链mark后到PREROUTING链才能回位于Application Layer的redir，而dig本身就在Application Layer，类似tunnel在Application Layer就很便利，不用绕一圈

**Comment by zonyitoo** [comment]
If `sslocal` is running in REDIR mode, it is required that all data is transferred by `iptables`. `sslocal` reads SRC ADDR and DST ADDR from operating system (Linux in this case), and relay this data packet to remote servers.

iptables is required if you want `sslocal` in REDIR mode, or you shouldn't use REDIR.

**Comment by xnyjdegh** [comment]
> If `sslocal` is running in REDIR mode, it is required that all data is transferred by `iptables`. `sslocal` reads SRC ADDR and DST ADDR from operating system (Linux in this case), and relays this data packet to remote servers.
> 
> iptables is mandatory if you want `sslocal` in REDIR mode, or you shouldn't use REDIR.

感谢。那我只好还是用tunnel配合redir来使用了。
我原来想用iptables+ipt2sock+shadowsocks的socks5来做这一套（那便可以换成任何支持socks5的代理），然后dns请求由某smartdns分流，但是终究还是找不到一个比较好用的（且近一年还有维护的）能把dns请求转成socks5的工具，找到最终最独立的还是只有shadowsocks-tunnel可以做这件事。
占用了你很多时间解答，再次感谢

**Comment by zonyitoo** [comment]
Why don't you let DNS requests send through iptables? You can simply modify `/etc/resolv.conf` to set your remote DNS servers, such as `8.8.8.8`.

**Comment by xnyjdegh** [comment]
> 为什么不让DNS请求通过iptables发送？您只需修改`/etc/resolv.conf`即可设置您的远程DNS服务器，例如`8.8.8.8`。

原提问中有提到，

> 为了解决dns污染和避免中国内地网站也走远程dns解析，所以引入了smartdns配合https://github.com/felixonmars/dnsmasq- china-list.git来做分流
这样来达到中国内地网站走运营商dns，其他的走经过代理的无污染的dns的目的
另外上面也有提到，让 dns client 发送的流量（不管是直接请求 8.8.8.8:53 还是 /etc/resolv.conf 配 8.8.8.8 ）流往iptables我理解是这样：
```
Application Layer (dns client) -> iptables(Network Layer TPROXY OUTPUT  mark) -> iptables(Network Layer TPROXY PREROUTING )  ->Application Layer  ( redir） ->  shadowsocks server
```
而tunnel的流向是
```
Application Layer (dns client) ->Application Layer  ( tunnel）  ->  shadowsocks server
```
少了很多步骤
