### ISSUE TITLE
MT7621 get "Error relocating" when running binaries in shadowsocks-v1.8.23.mipsel-unknown-linux-musl.tar.xz release

### ISSUE THREAD

**Issue by freakinyy** [shadowsocks/shadowsocks-rust#311]
root@xxxx:\~/bin# cat /proc/cpuinfo | grep "system type"
system type             : MediaTek MT7621 ver:1 eco:3
root@xxxx:\~/bin# uname -a
Linux xxxx 4.14.171 #0 SMP Thu Feb 27 21:05:12 2020 mips GNU/Linux
root@xxxx:~/bin# ./sslocal
Error relocating ./sslocal: __select_time64: symbol not found
Error relocating ./sslocal: __gettimeofday_time64: symbol not found
Error relocating ./sslocal: __fstat_time64: symbol not found
Error relocating ./sslocal: __time64: symbol not found
Error relocating ./sslocal: __stat_time64: symbol not found
Error relocating ./sslocal: __clock_gettime64: symbol not found
Error relocating ./sslocal: __gmtime64_r: symbol not found

Running other binaries from the package get the same errors.
If I downloaded the release for wrong target? Or must I build binaries from source for this cpu?

**Comment by zonyitoo** [comment]
> Or must I build binaries from source for this cpu?

It seems so. You may try to compile one by yourself.

**Comment by abcfy2** [comment]
Know issue: https://github.com/rust-lang/libc/issues/1848

So a quick fix is just downgrade cross toolchain which using musl 1.1.x. Like: 

https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/Dockerfile.arm-unknown-linux-musleabi

**Comment by freakinyy** [comment]
> Known issue: [rust-lang/libc#1848](https://github.com/rust-lang/libc/issues/1848)
> 
> So a quick fix is just downgrade cross toolchain which using musl 1.1.x. Like:
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/Dockerfile.arm-unknown-linux-musleabi
> 
> Also, you may try this build. Is this working for you ?
> [shadowsocks-v1.8.24.mips-unknown-linux-musl.zip](https://github.com/shadowsocks/shadowsocks-rust/files/5482732/shadowsocks-v1.8.24.mips-unknown-linux-musl.zip)

Nope. This one is for mips. I'm sure mt7621 is mipsel. But I still tried. 

root@xxxx:~/bin# ./sslocal
./sslocal: line 1: syntax error: unexpected "("

**Comment by abcfy2** [comment]
How about this one ?

[shadowsocks-v1.8.24.mipsel-unknown-linux-musl.zip](https://github.com/shadowsocks/shadowsocks-rust/files/5482983/shadowsocks-v1.8.24.mipsel-unknown-linux-musl.zip)

**Comment by freakinyy** [comment]
> How about this one ?
> 
> [shadowsocks-v1.8.24.mipsel-unknown-linux-musl.zip](https://github.com/shadowsocks/shadowsocks-rust/files/5482983/shadowsocks-v1.8.24.mipsel-unknown-linux-musl.zip)

Yes this works.

**Comment by abcfy2** [comment]
OK. I'll make a PR to fix this issue.
