### ISSUE TITLE
shadowsocks-android编译出现OpenSSL及Libsodium链接错误

### ISSUE THREAD

**Issue by janus-xiao** [shadowsocks/shadowsocks-rust#320]
下载了shadowsocks-v1.8.0-alpha.2-stable.x86_64-pc-windows-gnu.zip
在shadowsocks-android要怎么使用？

**Comment by janus-xiao** [comment]
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `G:\GithubSoftware\ShadowsocksAndroid\core\src\main\rust\shadowsocks-rust\target\debug\build\openssl-sys-32b61c86cea72137\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_armv7-linux-androideabi = Some("F:\\Android\\sdk\\ndk\\21.3.6528147\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi23-clang.cmd")
  CFLAGS_armv7-linux-androideabi = None
  CFLAGS_armv7_linux_androideabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running "perl" "./Configure" "--prefix=G:\\GithubSoftware\\ShadowsocksAndroid\\core\\src\\main\\rust\\shadowsocks-rust\\target\\armv7-linux-androideabi\\debug\\build\\openssl-sys-432535d979e8c747\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "no-shared" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer"
  Configuring OpenSSL version 1.1.1h (0x1010108fL) for linux-armv4
  Using os-specific seed configuration

  It looks like you don't have either nmake.exe or dmake.exe on your PATH,
  so you will not be able to execute the commands from a Makefile.  You can
  install dmake.exe with the Perl Package Manager by running:

      ppm install dmake


  --- stderr
  perl: warning: Setting locale failed.
  perl: warning: Please check that your locale settings:
  	LC_ALL = "C.UTF-8",
  	LANG = (unset)
      are supported and installed on your system.
  perl: warning: Falling back to the system default locale ("Chinese (Simplified)_China.936").

  ******************************************************************************
  This perl implementation doesn't produce Unix like paths (with forward slash
  directory separators).  Please use an implementation that matches your
  building platform.

  This Perl version: 5.26.3 for MSWin32-x64-multi-thread
  ******************************************************************************
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=G:\\GithubSoftware\\ShadowsocksAndroid\\core\\src\\main\\rust\\shadowsocks-rust\\target\\armv7-linux-androideabi\\debug\\build\\openssl-sys-432535d979e8c747\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "no-shared" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer"
      Exit status: exit code: 255

**Comment by janus-xiao** [comment]
@zonyitoo 请问shadowsocks-android 可以不便宜rust直接使用shadowsocks-v1.8.0-alpha.2-stable.x86_64-pc-windows-gnu.zip吗？

**Comment by zonyitoo** [comment]
为什么要在Android上使用Windows版本的程序？

**Comment by janus-xiao** [comment]
> 为什么要在Android上使用Windows版本的程序？

shadowsocks-android也有rust库，我以为是编译用的。。。
我在编译shadowsocks-android项目openssl-sys v0.9.58  libsodium-sys v0.2.6这两个库编译不过，您可以帮我看看吗？

1. error: failed to run custom build command for `openssl-sys v0.9.58`

2. error: could not find native static library `libsodium`, perhaps an -L flag is missing?

error: aborting due to previous error

The following warnings were emitted during compilation:

warning: Using unknown libsodium version.  This crate is tested against 1.0.18 and may not be fully compatible with other versions.

could not find native static library `libsodium`, perhaps an -L flag is missing?

aborting due to previous error

Using unknown libsodium version.  This crate is tested against 1.0.18 and may not be fully compatible with other versions.

**Comment by zonyitoo** [comment]
这个看起来你是在尝试使用预编译好的`libcrypto`和`libsodium`，但是在搜索路径里并没有找到。这个可能跟编译时使用的参数有关，具体要看shadowsocks-android编译时传入的参数。

cc @Mygod

**Comment by dev4u** [comment]
android版的前3、4个rust依赖的版本是有这个问题。
确认当前编译的版本是最新的，编译前执行clean任务

**Comment by janus-xiao** [comment]
> android版的前3、4个rust依赖的版本是有这个问题。
> 确认当前编译的版本是最新的，编译前执行clean任务

我直接下载shadowsocks-rust的当前版本，我shadowsocks-Android是应用了这个库

**Comment by janus-xiao** [comment]
> android版的前3、4个rust依赖的版本是有这个问题。
> 确认当前编译的版本是最新的，编译前执行clean任务

shadowsocks本身应该就是依赖了这个库

**Comment by dev4u** [comment]
https://github.com/shadowsocks/shadowsocks-rust/commit/2b55f9c0fadbc1551e695928dc5337881ac73c8b
在这个版本之后，就已经修复openssl的依赖问题。

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/36576a6113d69dc91875441dc115fb34da003313/core/build.gradle.kts#L47

shadowsocks-android 传入的编译参数里也有 `openssl-vendored` ，我想应该是你的代码是旧的或环境有问题。

**Comment by janus-xiao** [comment]
应该是环境问题，我暂时使用了libsslocal.so，没有去编译rust了，后面有时间再看了；
