### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#321]
编译加上local-redir功能老是报错，不加上就通过
```
   Compiling hyper v0.14.0-dev (https://github.com/hyperium/hyper.git#121c3313)
   Compiling shadowsocks-rust v1.9.0 (/home/runner/work/shadowsocks_install/shadowsocks_install/shadowsocks-rust)
error[E0599]: no function or associated item named `from_std` found for struct `mio::net::UdpSocket` in the current scope
  --> src/relay/udprelay/redir/sys/unix/linux.rs:50:42
   |
50 |         let msock = mio::net::UdpSocket::from_std(socket.into_udp_socket());
   |                                          ^^^^^^^^ function or associated item not found in `mio::net::UdpSocket`

error[E0308]: mismatched types
  --> src/relay/udprelay/redir/sys/unix/linux.rs:63:46
   |
63 |         match self.io.get_ref().send_to(buf, target) {
   |                                              ^^^^^^
   |                                              |
   |                                              expected `&std::net::SocketAddr`, found enum `std::net::SocketAddr`
   |                                              help: consider borrowing here: `&target`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `shadowsocks-rust`

To learn more, run the command again with --verbose.
Error: Process completed with exit code 101.
```  

编译参数
```
cargo +nightly build --release --target x86_64-unknown-linux-gnu --features "local-socks4 local-http local-tunnel local-dns trust-dns local-flow-stat local-redir"
```

**Comment by zonyitoo** [comment]
This is due to API changes in tokio v0.3.

**Comment by zonyitoo** [comment]
It doesn't make any sense, `mio::net::UdpSocket::from_std` should exist:  https://docs.rs/mio/0.7.6/mio/net/struct.UdpSocket.html#method.from_std

Please check your `Cargo.lock` and see what version of mio did you use.

**Comment by zgzh** [comment]
同样不通过。``├── async-trait v0.1.41 (proc-macro)
│   ├── proc-macro2 v1.0.24
│   │   └── unicode-xid v0.2.1
│   ├── quote v1.0.7
│   │   └── proc-macro2 v1.0.24 (*)
│   └── syn v1.0.48
│       ├── proc-macro2 v1.0.24 (*)
│       ├── quote v1.0.7 (*)
│       └── unicode-xid v0.2.1
├── base64 v0.13.0
├── bloomfilter v1.0.3
│   ├── bit-vec v0.6.2
│   ├── rand v0.7.3
│   │   ├── getrandom v0.1.15
│   │   │   ├── cfg-if v0.1.10
│   │   │   └── libc v0.2.80
│   │   ├── libc v0.2.80
│   │   ├── rand_chacha v0.2.2
│   │   │   ├── ppv-lite86 v0.2.10
│   │   │   └── rand_core v0.5.1
│   │   │       └── getrandom v0.1.15 (*)
│   │   └── rand_core v0.5.1 (*)
│   └── siphasher v0.3.3
├── byte_string v1.0.0
├── byteorder v1.3.4
├── bytes v0.5.6
├── cfg-if v1.0.0
├── clap v2.33.3
│   ├── ansi_term v0.11.0
│   ├── atty v0.2.14
│   │   └── libc v0.2.80
│   ├── bitflags v1.2.1
│   ├── strsim v0.8.0
│   ├── term_size v0.3.2
│   │   └── libc v0.2.80
│   ├── textwrap v0.11.0
│   │   ├── term_size v0.3.2 (*)
│   │   └── unicode-width v0.1.8
│   ├── unicode-width v0.1.8
│   └── vec_map v0.8.2
├── daemonize v0.4.1
│   ├── boxfnonce v0.1.1
│   └── libc v0.2.80
├── futures v0.3.8
│   ├── futures-channel v0.3.8
│   │   ├── futures-core v0.3.8
│   │   └── futures-sink v0.3.8
│   ├── futures-core v0.3.8
│   ├── futures-executor v0.3.8
│   │   ├── futures-core v0.3.8
│   │   ├── futures-task v0.3.8
│   │   │   └── once_cell v1.5.2
│   │   └── futures-util v0.3.8
│   │       ├── futures-channel v0.3.8 (*)
│   │       ├── futures-core v0.3.8
│   │       ├── futures-io v0.3.8
│   │       ├── futures-macro v0.3.8 (proc-macro)
│   │       │   ├── proc-macro-hack v0.5.19 (proc-macro)
│   │       │   ├── proc-macro2 v1.0.24 (*)
│   │       │   ├── quote v1.0.7 (*)
│   │       │   └── syn v1.0.48 (*)
│   │       ├── futures-sink v0.3.8
│   │       ├── futures-task v0.3.8 (*)
│   │       ├── memchr v2.3.4
│   │       ├── pin-project v1.0.2
│   │       │   └── pin-project-internal v1.0.2 (proc-macro)
│   │       │       ├── proc-macro2 v1.0.24 (*)
│   │       │       ├── quote v1.0.7 (*)
│   │       │       └── syn v1.0.48 (*)
│   │       ├── pin-utils v0.1.0
│   │       ├── proc-macro-hack v0.5.19 (proc-macro)
│   │       ├── proc-macro-nested v0.1.6
│   │       └── slab v0.4.2
│   ├── futures-io v0.3.8
│   ├── futures-sink v0.3.8
│   ├── futures-task v0.3.8 (*)
│   └── futures-util v0.3.8 (*)
├── http v0.2.1
│   ├── bytes v0.5.6
│   ├── fnv v1.0.7
│   └── itoa v0.4.6
├── hyper v0.14.0-dev (https://github.com/hyperium/hyper.git#121c3313)
│   ├── bytes v0.6.0
│   ├── futures-channel v0.3.8 (*)
│   ├── futures-core v0.3.8
│   ├── futures-util v0.3.8 (*)
│   ├── h2 v0.3.0 (https://github.com/hyperium/h2.git#5a92f256)
│   │   ├── bytes v0.6.0
│   │   ├── fnv v1.0.7
│   │   ├── futures-core v0.3.8
│   │   ├── futures-sink v0.3.8
│   │   ├── futures-util v0.3.8 (*)
│   │   ├── http v0.2.1 (*)
│   │   ├── indexmap v1.6.0
│   │   │   └── hashbrown v0.9.1
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.0.1
│   │   ├── slab v0.4.2
│   │   ├── tokio v0.3.4
│   │   │   ├── bytes v0.6.0
│   │   │   ├── futures-core v0.3.8
│   │   │   ├── lazy_static v1.4.0
│   │   │   ├── libc v0.2.80
│   │   │   ├── memchr v2.3.4
│   │   │   ├── mio v0.7.6
│   │   │   │   ├── libc v0.2.80
│   │   │   │   └── log v0.4.11
│   │   │   │       ├── cfg-if v0.1.10
│   │   │   │       └── serde v1.0.117
│   │   │   │           └── serde_derive v1.0.117 (proc-macro)
│   │   │   │               ├── proc-macro2 v1.0.24 (*)
│   │   │   │               ├── quote v1.0.7 (*)
│   │   │   │               └── syn v1.0.48 (*)
│   │   │   ├── num_cpus v1.13.0
│   │   │   │   └── libc v0.2.80
│   │   │   ├── parking_lot v0.11.1
│   │   │   │   ├── instant v0.1.9
│   │   │   │   │   └── cfg-if v1.0.0
│   │   │   │   ├── lock_api v0.4.2
│   │   │   │   │   └── scopeguard v1.1.0
│   │   │   │   └── parking_lot_core v0.8.0
│   │   │   │       ├── cfg-if v0.1.10
│   │   │   │       ├── instant v0.1.9 (*)
│   │   │   │       ├── libc v0.2.80
│   │   │   │       └── smallvec v1.5.0
│   │   │   ├── pin-project-lite v0.2.0
│   │   │   ├── signal-hook-registry v1.2.2
│   │   │   │   └── libc v0.2.80
│   │   │   ├── slab v0.4.2
│   │   │   └── tokio-macros v0.3.1 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.24 (*)
│   │   │       ├── quote v1.0.7 (*)
│   │   │       └── syn v1.0.48 (*)
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.0.1
│   │   ├── tokio-util v0.5.0
│   │   │   ├── bytes v0.6.0
│   │   │   ├── futures-core v0.3.8
│   │   │   ├── futures-sink v0.3.8
│   │   │   ├── log v0.4.11 (*)
│   │   │   ├── pin-project-lite v0.1.11
│   │   │   └── tokio v0.3.4 (*)
│   │   ├── tracing v0.1.21
│   │   │   ├── cfg-if v0.1.10
│   │   │   ├── log v0.4.11 (*)
│   │   │   ├── pin-project-lite v0.1.11
│   │   │   ├── tracing-attributes v0.1.11 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.24 (*)
│   │   │   │   ├── quote v1.0.7 (*)
│   │   │   │   └── syn v1.0.48 (*)
│   │   │   └── tracing-core v0.1.17
│   │   │       └── lazy_static v1.4.0
│   │   └── tracing-futures v0.2.4
│   │       ├── pin-project v0.4.27
│   │       │   └── pin-project-internal v0.4.27 (proc-macro)
│   │       │       ├── proc-macro2 v1.0.24 (*)
│   │       │       ├── quote v1.0.7 (*)
│   │       │       └── syn v1.0.48 (*)
│   │       └── tracing v0.1.21 (*)
│   ├── http v0.2.1 (*)
│   ├── http-body v0.4.0 (https://github.com/hyperium/http-body#5e434739)
│   │   ├── bytes v0.6.0
│   │   └── http v0.2.1 (*)
│   ├── httparse v1.3.4
│   ├── httpdate v0.3.2
│   ├── itoa v0.4.6
│   ├── pin-project v1.0.2 (*)
│   ├── socket2 v0.3.16
│   │   ├── cfg-if v0.1.10
│   │   └── libc v0.2.80
│   ├── tokio v0.3.4 (*)
│   ├── tower-service v0.3.0
│   ├── tracing v0.1.21 (*)
│   └── want v0.3.0
│       ├── log v0.4.11 (*)
│       └── try-lock v0.2.3
├── ipnet v2.3.0
├── iprange v0.6.3
│   └── ipnet v2.3.0
├── json5 v0.2.8
│   ├── pest v2.1.3
│   │   └── ucd-trie v0.1.3
│   ├── pest_derive v2.1.0 (proc-macro)
│   │   ├── pest v2.1.3 (*)
│   │   └── pest_generator v2.1.3
│   │       ├── pest v2.1.3 (*)
│   │       ├── pest_meta v2.1.3
│   │       │   ├── maplit v1.0.2
│   │       │   └── pest v2.1.3 (*)
│   │       │   [build-dependencies]
│   │       │   └── sha-1 v0.8.2
│   │       │       ├── block-buffer v0.7.3
│   │       │       │   ├── block-padding v0.1.5
│   │       │       │   │   └── byte-tools v0.3.1
│   │       │       │   ├── byte-tools v0.3.1
│   │       │       │   ├── byteorder v1.3.4
│   │       │       │   └── generic-array v0.12.3
│   │       │       │       └── typenum v1.12.0
│   │       │       ├── digest v0.8.1
│   │       │       │   └── generic-array v0.12.3 (*)
│   │       │       ├── fake-simd v0.1.2
│   │       │       └── opaque-debug v0.2.3
│   │       ├── proc-macro2 v1.0.24 (*)
│   │       ├── quote v1.0.7 (*)
│   │       └── syn v1.0.48 (*)
│   └── serde v1.0.117 (*)
├── lazy_static v1.4.0
├── libc v0.2.80
├── log v0.4.11 (*)
├── log4rs v0.13.0
│   ├── arc-swap v0.4.7
│   ├── chrono v0.4.19
│   │   ├── libc v0.2.80
│   │   ├── num-integer v0.1.44
│   │   │   └── num-traits v0.2.14
│   │   │       [build-dependencies]
│   │   │       └── autocfg v1.0.1
│   │   │   [build-dependencies]
│   │   │   └── autocfg v1.0.1
│   │   ├── num-traits v0.2.14 (*)
│   │   └── time v0.1.44
│   │       └── libc v0.2.80
│   ├── flate2 v1.0.19
│   │   ├── cfg-if v1.0.0
│   │   ├── crc32fast v1.2.1
│   │   │   └── cfg-if v1.0.0
│   │   ├── libc v0.2.80
│   │   └── miniz_oxide v0.4.3
│   │       └── adler v0.2.3
│   │       [build-dependencies]
│   │       └── autocfg v1.0.1
│   ├── fnv v1.0.7
│   ├── humantime v1.3.0
│   │   └── quick-error v1.2.3
│   ├── libc v0.2.80
│   ├── log v0.4.11 (*)
│   ├── log-mdc v0.1.0
│   ├── parking_lot v0.11.1 (*)
│   ├── serde v1.0.117 (*)
│   ├── serde-value v0.6.0
│   │   ├── ordered-float v1.1.0
│   │   │   └── num-traits v0.2.14 (*)
│   │   └── serde v1.0.117 (*)
│   ├── serde_derive v1.0.117 (proc-macro) (*)
│   ├── serde_json v1.0.59
│   │   ├── itoa v0.4.6
│   │   ├── ryu v1.0.5
│   │   └── serde v1.0.117 (*)
│   ├── serde_yaml v0.8.14
│   │   ├── dtoa v0.4.6
│   │   ├── linked-hash-map v0.5.3
│   │   ├── serde v1.0.117 (*)
│   │   └── yaml-rust v0.4.4
│   │       └── linked-hash-map v0.5.3
│   ├── thread-id v3.3.0
│   │   └── libc v0.2.80
│   └── typemap v0.3.3
│       └── unsafe-any v0.4.2
│           └── traitobject v0.1.0
├── lru_time_cache v0.11.2
├── mio v0.6.22
│   ├── cfg-if v0.1.10
│   ├── iovec v0.1.4
│   │   └── libc v0.2.80
│   ├── libc v0.2.80
│   ├── log v0.4.11 (*)
│   ├── net2 v0.2.35
│   │   ├── cfg-if v0.1.10
│   │   └── libc v0.2.80
│   └── slab v0.4.2
├── mio-uds v0.6.8
│   ├── iovec v0.1.4 (*)
│   ├── libc v0.2.80
│   └── mio v0.6.22 (*)
├── pin-project v1.0.2 (*)
├── qrcode v0.12.0
│   └── checked_int_cast v1.0.0
├── rand v0.7.3 (*)
├── regex v1.4.2
│   ├── aho-corasick v0.7.15
│   │   └── memchr v2.3.4
│   ├── memchr v2.3.4
│   ├── regex-syntax v0.6.21
│   └── thread_local v1.0.1
│       └── lazy_static v1.4.0
├── ring v0.16.16
│   ├── libc v0.2.80
│   ├── once_cell v1.5.2
│   ├── spin v0.5.2
│   └── untrusted v0.7.1
│   [build-dependencies]
│   └── cc v1.0.65
├── rustls-native-certs v0.4.0
│   ├── openssl-probe v0.1.2
│   └── rustls v0.18.1
│       ├── base64 v0.12.3
│       ├── log v0.4.11 (*)
│       ├── ring v0.16.16 (*)
│       ├── sct v0.6.0
│       │   ├── ring v0.16.16 (*)
│       │   └── untrusted v0.7.1
│       └── webpki v0.21.3
│           ├── ring v0.16.16 (*)
│           └── untrusted v0.7.1
├── serde v1.0.117 (*)
├── serde_json v1.0.59 (*)
├── serde_urlencoded v0.7.0
│   ├── form_urlencoded v1.0.0
│   │   ├── matches v0.1.8
│   │   └── percent-encoding v2.1.0
│   ├── itoa v0.4.6
│   ├── ryu v1.0.5
│   └── serde v1.0.117 (*)
├── shadowsocks-crypto v0.1.0
│   ├── crypto2 v0.1.1
│   ├── rand v0.7.3 (*)
│   └── ring v0.16.16 (*)
├── socket2 v0.3.16 (*)
├── spin v0.7.0
├── strum v0.19.5
├── strum_macros v0.19.4 (proc-macro)
│   ├── heck v0.3.1
│   │   └── unicode-segmentation v1.7.0
│   ├── proc-macro2 v1.0.24 (*)
│   ├── quote v1.0.7 (*)
│   └── syn v1.0.48 (*)
├── tokio v0.3.4 (*)
├── tokio-rustls v0.20.0
│   ├── rustls v0.18.1 (*)
│   ├── tokio v0.3.4 (*)
│   └── webpki v0.21.3 (*)
├── tower v0.4.0 (https://github.com/tower-rs/tower.git#d4d1c67c)
│   ├── futures-core v0.3.8
│   ├── pin-project v1.0.2 (*)
│   ├── tower-layer v0.3.0 (https://github.com/tower-rs/tower.git#d4d1c67c)
│   ├── tower-service v0.3.0
│   └── tracing v0.1.21 (*)
├── trust-dns-resolver v0.20.0-alpha.3 (https://github.com/bluejekyll/trust-dns.git?branch=upgrade-to-tokio-0.3#a931624c)
│   ├── cfg-if v1.0.0
│   ├── futures-util v0.3.8 (*)
│   ├── lazy_static v1.4.0
│   ├── log v0.4.11 (*)
│   ├── lru-cache v0.1.2
│   │   └── linked-hash-map v0.5.3
│   ├── parking_lot v0.11.1 (*)
│   ├── resolv-conf v0.7.0
│   │   ├── hostname v0.3.1
│   │   │   ├── libc v0.2.80
│   │   │   └── match_cfg v0.1.0
│   │   └── quick-error v1.2.3
│   ├── serde v1.0.117 (*)
│   ├── smallvec v1.5.0
│   ├── thiserror v1.0.22
│   │   └── thiserror-impl v1.0.22 (proc-macro)
│   │       ├── proc-macro2 v1.0.24 (*)
│   │       ├── quote v1.0.7 (*)
│   │       └── syn v1.0.48 (*)
│   ├── tokio v0.3.4 (*)
│   └── trust-dns-proto v0.20.0-alpha.3 (https://github.com/bluejekyll/trust-dns.git?branch=upgrade-to-tokio-0.3#a931624c)
│       ├── async-trait v0.1.41 (proc-macro) (*)
│       ├── cfg-if v1.0.0
│       ├── data-encoding v2.3.1
│       ├── enum-as-inner v0.3.3 (proc-macro)
│       │   ├── heck v0.3.1 (*)
│       │   ├── proc-macro2 v1.0.24 (*)
│       │   ├── quote v1.0.7 (*)
│       │   └── syn v1.0.48 (*)
│       ├── futures-channel v0.3.8 (*)
│       ├── futures-io v0.3.8
│       ├── futures-util v0.3.8 (*)
│       ├── idna v0.2.0
│       │   ├── matches v0.1.8
│       │   ├── unicode-bidi v0.3.4
│       │   │   └── matches v0.1.8
│       │   └── unicode-normalization v0.1.16
│       │       └── tinyvec v1.1.0
│       │           └── tinyvec_macros v0.1.0
│       ├── ipnet v2.3.0
│       ├── lazy_static v1.4.0
│       ├── log v0.4.11 (*)
│       ├── rand v0.7.3 (*)
│       ├── serde v1.0.117 (*)
│       ├── smallvec v1.5.0
│       ├── thiserror v1.0.22 (*)
│       ├── tokio v0.3.4 (*)
│       └── url v2.2.0
│           ├── form_urlencoded v1.0.0 (*)
│           ├── idna v0.2.0 (*)
│           ├── matches v0.1.8
│           └── percent-encoding v2.1.0
├── url v2.2.0 (*)
└── webpki-roots v0.20.0
    └── webpki v0.21.3 (*)
[dev-dependencies]
└── env_logger v0.8.2
    ├── atty v0.2.14 (*)
    ├── humantime v2.0.1
    ├── log v0.4.11 (*)
    ├── regex v1.4.2 (*)
    └── termcolor v1.1.2

**Comment by zonyitoo** [comment]
```
├── mio v0.6.22
│   ├── cfg-if v0.1.10
│   ├── iovec v0.1.4
│   │   └── libc v0.2.80
│   ├── libc v0.2.80
│   ├── log v0.4.11 (*)
│   ├── net2 v0.2.35
│   │   ├── cfg-if v0.1.10
│   │   └── libc v0.2.80
│   └── slab v0.4.2
├── mio-uds v0.6.8
│   ├── iovec v0.1.4 (*)
│   ├── libc v0.2.80
│   └── mio v0.6.22 (*)
```

**Comment by yiguihai** [comment]
编译通过了，我试错了好久才有勇气开Issues在此之前没有一个反馈这个问题的搞的我都怀疑自己了。享受别人成果而不去帮助奉献的人真是无耻。
