### ISSUE TITLE
[Feature Req] Support verbose logging

### ISSUE THREAD

**Issue by cyqsimon** [shadowsocks/shadowsocks-rust#322]
For network diagnostic purposes, it would be nice to have a verbose logging mode.

In SS-libev, this feature is offered with the `-v` flag.

**Comment by zonyitoo** [comment]
Have you tried to pass `-v`?

**Comment by cyqsimon** [comment]
Ah sorry. I somehow missed the `-v Set the level of debug` in `help`. I guess I was looking for the word "verbose" too much 😅

**Comment by zonyitoo** [comment]
`-v` is a repeated parameter, you can set verbose level by `-v`, `-vv`, `-vvv`, `-vvvv`
