### ISSUE TITLE
这会导致shadowsocks-android在启动服务时失败

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#323]
https://github.com/shadowsocks/shadowsocks-rust/blob/71b98f74d412b286c0fecc7a4a4c4c0af80122be/src/bin/local.rs#L154

在android下，sslocal启动的时候，会检查dns-addr、local-dns-addr、remote-dns-addr三个参数，必须成对指定。而ss android项目中，只指定了dns-relay、remote-dns，缺少了local-dns-addr参数，这会导致app不能正常启动服务。[相关代码](https://github.com/shadowsocks/shadowsocks-android/blob/36576a6113d69dc91875441dc115fb34da003313/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L127-L129)

**Comment by dev4u** [comment]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/1210047/99896525-64bd2500-2ccc-11eb-80ee-c03a5d9fef39.png">

**Comment by dev4u** [comment]
CC @madeye

**Comment by zonyitoo** [comment]
Hmm, Android is expecting `--local-dns-addr` to have a default value.
