### ISSUE TITLE
`cargo install shadowsocks-rust` fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by oebrab** [shadowsocks/shadowsocks-rust#324]
The error message is:

```
error: failed to compile `shadowsocks-rust v1.8.23`, intermediate artifacts can be found at `/tmp/cargo-installA1weRC`

Caused by:
  could not compile `shadowsocks-rust`

Caused by:
  process didn't exit successfully: `rustc --crate-name sslocal --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/shadowsocks-rust-1.8.23/src/bin/local.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 --cfg 'feature="aes-cfb"' --cfg 'feature="aes-ctr"' --cfg 'feature="default"' --cfg 'feature="http"' --cfg 'feature="hyper"' --cfg 'feature="libsodium-sys"' --cfg 'feature="local-http"' --cfg 'feature="local-http-rustls"' --cfg 'feature="local-socks4"' --cfg 'feature="local-tunnel"' --cfg 'feature="openssl"' --cfg 'feature="rc4"' --cfg 'feature="ring"' --cfg 'feature="ring-aead-ciphers"' --cfg 'feature="rustls-native-certs"' --cfg 'feature="sodium"' --cfg 'feature="tokio-rustls"' --cfg 'feature="tower"' --cfg 'feature="trust-dns"' --cfg 'feature="trust-dns-resolver"' --cfg 'feature="webpki-roots"' -C metadata=c974932a8cd56394 -C extra-filename=-c974932a8cd56394 --out-dir /tmp/cargo-installA1weRC/release/deps -L dependency=/tmp/cargo-installA1weRC/release/deps --extern async_trait=/tmp/cargo-installA1weRC/release/deps/libasync_trait-a51e753a81fd672c.so --extern base64=/tmp/cargo-installA1weRC/release/deps/libbase64-82804e685eeeafab.rlib --extern bloomfilter=/tmp/cargo-installA1weRC/release/deps/libbloomfilter-04ea3769105d05a3.rlib --extern byte_string=/tmp/cargo-installA1weRC/release/deps/libbyte_string-623c2f30293b828b.rlib --extern byteorder=/tmp/cargo-installA1weRC/release/deps/libbyteorder-d9f395551737a72f.rlib --extern bytes=/tmp/cargo-installA1weRC/release/deps/libbytes-eaef4d60c65ed744.rlib --extern cfg_if=/tmp/cargo-installA1weRC/release/deps/libcfg_if-d20067d3f06b054e.rlib --extern clap=/tmp/cargo-installA1weRC/release/deps/libclap-0f8f97b460716d88.rlib --extern daemonize=/tmp/cargo-installA1weRC/release/deps/libdaemonize-ac395f401ed8355d.rlib --extern digest=/tmp/cargo-installA1weRC/release/deps/libdigest-76b1432f41c5d65c.rlib --extern futures=/tmp/cargo-installA1weRC/release/deps/libfutures-3578709eeb39e9c8.rlib --extern hkdf=/tmp/cargo-installA1weRC/release/deps/libhkdf-d96f7db18e4f4e07.rlib --extern hmac=/tmp/cargo-installA1weRC/release/deps/libhmac-31e835199a214cf2.rlib --extern http=/tmp/cargo-installA1weRC/release/deps/libhttp-90b421d0ee83da49.rlib --extern hyper=/tmp/cargo-installA1weRC/release/deps/libhyper-e43217c44b5194e7.rlib --extern ipnet=/tmp/cargo-installA1weRC/release/deps/libipnet-e9c058f522d33ba0.rlib --extern iprange=/tmp/cargo-installA1weRC/release/deps/libiprange-5946e85a3bb6c49b.rlib --extern json5=/tmp/cargo-installA1weRC/release/deps/libjson5-4fc3190d8588337c.rlib --extern lazy_static=/tmp/cargo-installA1weRC/release/deps/liblazy_static-30322ec29723ea95.rlib --extern libc=/tmp/cargo-installA1weRC/release/deps/liblibc-200eb869faf743a8.rlib --extern libsodium_sys=/tmp/cargo-installA1weRC/release/deps/liblibsodium_sys-25e001549855bf10.rlib --extern log=/tmp/cargo-installA1weRC/release/deps/liblog-c35c00cfd4f91448.rlib --extern log4rs=/tmp/cargo-installA1weRC/release/deps/liblog4rs-f9d75573541b6ce7.rlib --extern lru_time_cache=/tmp/cargo-installA1weRC/release/deps/liblru_time_cache-09346186772b02c4.rlib --extern md5=/tmp/cargo-installA1weRC/release/deps/libmd5-782255dddb3efddd.rlib --extern mio=/tmp/cargo-installA1weRC/release/deps/libmio-da89baa447670fc0.rlib --extern mio_uds=/tmp/cargo-installA1weRC/release/deps/libmio_uds-47dc080add79c09d.rlib --extern openssl=/tmp/cargo-installA1weRC/release/deps/libopenssl-425ae915e56e2eb3.rlib --extern pin_project=/tmp/cargo-installA1weRC/release/deps/libpin_project-8978c9ce33be7e87.rlib --extern qrcode=/tmp/cargo-installA1weRC/release/deps/libqrcode-ad6f8f02162e704d.rlib --extern rand=/tmp/cargo-installA1weRC/release/deps/librand-a7b17b8044cf326c.rlib --extern regex=/tmp/cargo-installA1weRC/release/deps/libregex-28518e8a28150413.rlib --extern ring=/tmp/cargo-installA1weRC/release/deps/libring-e800b92c0800c7e6.rlib --extern rustls_native_certs=/tmp/cargo-installA1weRC/release/deps/librustls_native_certs-4cfcc1e4b3b695fe.rlib --extern serde=/tmp/cargo-installA1weRC/release/deps/libserde-bea299885728ce15.rlib --extern serde_json=/tmp/cargo-installA1weRC/release/deps/libserde_json-76c6db395c079342.rlib --extern serde_urlencoded=/tmp/cargo-installA1weRC/release/deps/libserde_urlencoded-c6fdc8cce98fbe02.rlib --extern sha1=/tmp/cargo-installA1weRC/release/deps/libsha1-6e8d230363f95d77.rlib --extern shadowsocks=/tmp/cargo-installA1weRC/release/deps/libshadowsocks-7ccadcac018b6826.rlib --extern socket2=/tmp/cargo-installA1weRC/release/deps/libsocket2-d75cbdfff8ddf1a8.rlib --extern spin=/tmp/cargo-installA1weRC/release/deps/libspin-8b8a43919173625a.rlib --extern strum=/tmp/cargo-installA1weRC/release/deps/libstrum-ddb089c89b2fc7ed.rlib --extern strum_macros=/tmp/cargo-installA1weRC/release/deps/libstrum_macros-6861548804f898ac.so --extern tokio=/tmp/cargo-installA1weRC/release/deps/libtokio-3f2d8e19257e4715.rlib --extern tokio_rustls=/tmp/cargo-installA1weRC/release/deps/libtokio_rustls-14db321e5ff3e8d1.rlib --extern tower=/tmp/cargo-installA1weRC/release/deps/libtower-c7cd443e7c1f5fa1.rlib --extern trust_dns_proto=/tmp/cargo-installA1weRC/release/deps/libtrust_dns_proto-37d82d057737d8d5.rlib --extern trust_dns_resolver=/tmp/cargo-installA1weRC/release/deps/libtrust_dns_resolver-47d23089756a2d5a.rlib --extern typenum=/tmp/cargo-installA1weRC/release/deps/libtypenum-ff7145ced451eef0.rlib --extern url=/tmp/cargo-installA1weRC/release/deps/liburl-dd07ae9e4f6fcc5c.rlib --extern webpki_roots=/tmp/cargo-installA1weRC/release/deps/libwebpki_roots-d35f2424f7504ce0.rlib --cap-lints allow -L native=/tmp/cargo-installA1weRC/release/build/libsodium-sys-a7dc266567440e1c/out/installed/lib -L native=/tmp/cargo-installA1weRC/release/build/ring-78875f43760f35e8/out` (signal: 9, SIGKILL: kill)
```

**Comment by zonyitoo** [comment]
Please provide full output.

**Comment by oebrab** [comment]
Updating crates.io index
  Installing shadowsocks-rust v1.8.23
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling libc v0.2.80
   Compiling syn v1.0.50
   Compiling cfg-if v0.1.10
   Compiling serde_derive v1.0.117
   Compiling serde v1.0.117
   Compiling autocfg v1.0.1
   Compiling log v0.4.11
   Compiling cfg-if v1.0.0
   Compiling memchr v2.3.4
   Compiling futures-core v0.3.8
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling cc v1.0.65
   Compiling once_cell v1.5.2
   Compiling fnv v1.0.7
   Compiling smallvec v1.5.0
   Compiling scopeguard v1.1.0
   Compiling bytes v0.5.6
   Compiling pin-project-lite v0.1.11
   Compiling pin-project-internal v0.4.27
   Compiling proc-macro-hack v0.5.19
   Compiling proc-macro-nested v0.1.6
   Compiling futures-sink v0.3.8
   Compiling tower-service v0.3.0
   Compiling typenum v1.12.0
   Compiling version_check v0.9.2
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.8
   Compiling getrandom v0.1.15
   Compiling pkg-config v0.3.19
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling matches v0.1.8
   Compiling itoa v0.4.6
   Compiling tower-layer v0.3.0
   Compiling tinyvec_macros v0.1.0
   Compiling adler v0.2.3
   Compiling percent-encoding v2.1.0
   Compiling ryu v1.0.5
   Compiling linked-hash-map v0.5.3
   Compiling ppv-lite86 v0.2.10
   Compiling ucd-trie v0.1.3
   Compiling unicode-segmentation v1.7.0
   Compiling crc32fast v1.2.1
   Compiling gimli v0.23.0
   Compiling bitflags v1.2.1
   Compiling maplit v1.0.2
   Compiling quick-error v1.2.3
   Compiling traitobject v0.1.0
   Compiling base64 v0.12.3
   Compiling httparse v1.3.4
   Compiling subtle v2.3.0
   Compiling serde_json v1.0.59
   Compiling rustc-demangle v0.1.18
   Compiling hashbrown v0.9.1
   Compiling object v0.22.0
   Compiling match_cfg v0.1.0
   Compiling byteorder v1.3.4
   Compiling dtoa v0.4.6
   Compiling opaque-debug v0.3.0
   Compiling try-lock v0.2.3
   Compiling openssl v0.10.30
   Compiling foreign-types-shared v0.1.1
   Compiling unicode-width v0.1.8
   Compiling arc-swap v0.4.7
   Compiling regex-syntax v0.6.21
   Compiling boxfnonce v0.1.1
   Compiling cpuid-bool v0.1.2
   Compiling ipnet v2.3.0
   Compiling bit-vec v0.6.2
   Compiling openssl-probe v0.1.2
   Compiling ansi_term v0.11.0
   Compiling checked_int_cast v1.0.0
   Compiling siphasher v0.3.3
   Compiling log-mdc v0.1.0
   Compiling vec_map v0.8.2
   Compiling httpdate v0.3.2
   Compiling strsim v0.8.0
   Compiling base64 v0.13.0
   Compiling lru_time_cache v0.11.2
   Compiling byte_string v1.0.0
   Compiling strum v0.19.5
   Compiling spin v0.7.0
   Compiling miniz_oxide v0.4.3
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling indexmap v1.6.0
   Compiling instant v0.1.9
   Compiling tracing-core v0.1.17
   Compiling thread_local v1.0.1
   Compiling ring v0.16.16
   Compiling futures-task v0.3.8
   Compiling lock_api v0.4.2
   Compiling futures-channel v0.3.8
   Compiling generic-array v0.14.4
   Compiling openssl-sys v0.9.58
   Compiling libsodium-sys v0.2.6
   Compiling unicode-bidi v0.3.4
   Compiling http v0.2.1
   Compiling tinyvec v1.1.0
   Compiling form_urlencoded v1.0.0
   Compiling yaml-rust v0.4.4
   Compiling lru-cache v0.1.2
   Compiling pest v2.1.3
   Compiling heck v0.3.1
   Compiling addr2line v0.14.0
   Compiling humantime v1.3.0
   Compiling unsafe-any v0.4.2
   Compiling foreign-types v0.3.2
   Compiling iprange v0.6.3
   Compiling qrcode v0.12.0
   Compiling http-body v0.3.1
   Compiling unicode-normalization v0.1.16
   Compiling pest_meta v2.1.3
   Compiling typemap v0.3.3
   Compiling quote v1.0.7
   Compiling net2 v0.2.35
   Compiling parking_lot_core v0.8.0
   Compiling iovec v0.1.4
   Compiling num_cpus v1.13.0
   Compiling signal-hook-registry v1.2.2
   Compiling hostname v0.3.1
   Compiling term_size v0.3.2
   Compiling time v0.1.44
   Compiling socket2 v0.3.17
   Compiling atty v0.2.14
   Compiling thread-id v3.3.0
   Compiling daemonize v0.4.1
   Compiling aho-corasick v0.7.15
   Compiling idna v0.2.0
   Compiling parking_lot v0.11.1
   Compiling rand_core v0.5.1
   Compiling resolv-conf v0.7.0
   Compiling textwrap v0.11.0
   Compiling backtrace v0.3.55
   Compiling flate2 v1.0.19
   Compiling ordered-float v1.1.0
   Compiling regex v1.4.2
   Compiling webpki v0.21.3
   Compiling sct v0.6.0
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling crypto-mac v0.10.0
   Compiling url v2.2.0
   Compiling pest_generator v2.1.3
   Compiling tokio-macros v0.2.6
   Compiling pin-project-internal v1.0.2
   Compiling futures-macro v0.3.8
   Compiling tracing-attributes v0.1.11
   Compiling thiserror-impl v1.0.22
   Compiling async-trait v0.1.42
   Compiling enum-as-inner v0.3.3
   Compiling strum_macros v0.19.4
   Compiling rand_chacha v0.2.2
   Compiling clap v2.33.3
   Compiling chrono v0.4.19
   Compiling webpki-roots v0.20.0
   Compiling md-5 v0.9.1
   Compiling sha-1 v0.9.2
   Compiling hmac v0.10.1
   Compiling pest_derive v2.1.0
   Compiling pin-project v0.4.27
   Compiling pin-project v1.0.2
   Compiling thiserror v1.0.22
   Compiling rand v0.7.3
   Compiling hkdf v0.10.0
   Compiling serde_yaml v0.8.14
   Compiling serde-value v0.6.0
   Compiling serde_urlencoded v0.7.0
   Compiling json5 v0.2.8
   Compiling tower-discover v0.3.0
   Compiling tower-load-shed v0.3.0
   Compiling futures-util v0.3.8
   Compiling bloomfilter v1.0.3
   Compiling mio v0.6.22
   Compiling tracing v0.1.21
   Compiling rustls v0.18.1
   Compiling want v0.3.0
   Compiling log4rs v0.13.0
   Compiling futures-executor v0.3.8
   Compiling tower-util v0.3.1
   Compiling mio-uds v0.6.8
   Compiling tracing-futures v0.2.4
   Compiling rustls-native-certs v0.4.0
   Compiling futures v0.3.8
   Compiling tokio v0.2.23
   Compiling tokio-util v0.3.1
   Compiling tower-load v0.3.0
   Compiling trust-dns-proto v0.19.6
   Compiling tower-timeout v0.3.0
   Compiling tower-buffer v0.3.0
   Compiling tower-retry v0.3.0
   Compiling tokio-rustls v0.14.1
   Compiling h2 v0.2.7
   Compiling tower-limit v0.3.1
   Compiling trust-dns-resolver v0.19.6
   Compiling hyper v0.13.9
   Compiling tower v0.3.1
   Compiling shadowsocks-rust v1.8.23
error: failed to compile `shadowsocks-rust v1.8.23`, intermediate artifacts can be found at `/tmp/cargo-installA1weRC`

Caused by:
  could not compile `shadowsocks-rust`

Caused by:
  process didn't exit successfully: `rustc --crate-name sslocal --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/shadowsocks-rust-1.8.23/src/bin/local.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto=fat -C codegen-units=1 --cfg 'feature="aes-cfb"' --cfg 'feature="aes-ctr"' --cfg 'feature="default"' --cfg 'feature="http"' --cfg 'feature="hyper"' --cfg 'feature="libsodium-sys"' --cfg 'feature="local-http"' --cfg 'feature="local-http-rustls"' --cfg 'feature="local-socks4"' --cfg 'feature="local-tunnel"' --cfg 'feature="openssl"' --cfg 'feature="rc4"' --cfg 'feature="ring"' --cfg 'feature="ring-aead-ciphers"' --cfg 'feature="rustls-native-certs"' --cfg 'feature="sodium"' --cfg 'feature="tokio-rustls"' --cfg 'feature="tower"' --cfg 'feature="trust-dns"' --cfg 'feature="trust-dns-resolver"' --cfg 'feature="webpki-roots"' -C metadata=c974932a8cd56394 -C extra-filename=-c974932a8cd56394 --out-dir /tmp/cargo-installA1weRC/release/deps -L dependency=/tmp/cargo-installA1weRC/release/deps --extern async_trait=/tmp/cargo-installA1weRC/release/deps/libasync_trait-a51e753a81fd672c.so --extern base64=/tmp/cargo-installA1weRC/release/deps/libbase64-82804e685eeeafab.rlib --extern bloomfilter=/tmp/cargo-installA1weRC/release/deps/libbloomfilter-04ea3769105d05a3.rlib --extern byte_string=/tmp/cargo-installA1weRC/release/deps/libbyte_string-623c2f30293b828b.rlib --extern byteorder=/tmp/cargo-installA1weRC/release/deps/libbyteorder-d9f395551737a72f.rlib --extern bytes=/tmp/cargo-installA1weRC/release/deps/libbytes-eaef4d60c65ed744.rlib --extern cfg_if=/tmp/cargo-installA1weRC/release/deps/libcfg_if-d20067d3f06b054e.rlib --extern clap=/tmp/cargo-installA1weRC/release/deps/libclap-0f8f97b460716d88.rlib --extern daemonize=/tmp/cargo-installA1weRC/release/deps/libdaemonize-ac395f401ed8355d.rlib --extern digest=/tmp/cargo-installA1weRC/release/deps/libdigest-76b1432f41c5d65c.rlib --extern futures=/tmp/cargo-installA1weRC/release/deps/libfutures-3578709eeb39e9c8.rlib --extern hkdf=/tmp/cargo-installA1weRC/release/deps/libhkdf-d96f7db18e4f4e07.rlib --extern hmac=/tmp/cargo-installA1weRC/release/deps/libhmac-31e835199a214cf2.rlib --extern http=/tmp/cargo-installA1weRC/release/deps/libhttp-90b421d0ee83da49.rlib --extern hyper=/tmp/cargo-installA1weRC/release/deps/libhyper-e43217c44b5194e7.rlib --extern ipnet=/tmp/cargo-installA1weRC/release/deps/libipnet-e9c058f522d33ba0.rlib --extern iprange=/tmp/cargo-installA1weRC/release/deps/libiprange-5946e85a3bb6c49b.rlib --extern json5=/tmp/cargo-installA1weRC/release/deps/libjson5-4fc3190d8588337c.rlib --extern lazy_static=/tmp/cargo-installA1weRC/release/deps/liblazy_static-30322ec29723ea95.rlib --extern libc=/tmp/cargo-installA1weRC/release/deps/liblibc-200eb869faf743a8.rlib --extern libsodium_sys=/tmp/cargo-installA1weRC/release/deps/liblibsodium_sys-25e001549855bf10.rlib --extern log=/tmp/cargo-installA1weRC/release/deps/liblog-c35c00cfd4f91448.rlib --extern log4rs=/tmp/cargo-installA1weRC/release/deps/liblog4rs-f9d75573541b6ce7.rlib --extern lru_time_cache=/tmp/cargo-installA1weRC/release/deps/liblru_time_cache-09346186772b02c4.rlib --extern md5=/tmp/cargo-installA1weRC/release/deps/libmd5-782255dddb3efddd.rlib --extern mio=/tmp/cargo-installA1weRC/release/deps/libmio-da89baa447670fc0.rlib --extern mio_uds=/tmp/cargo-installA1weRC/release/deps/libmio_uds-47dc080add79c09d.rlib --extern openssl=/tmp/cargo-installA1weRC/release/deps/libopenssl-425ae915e56e2eb3.rlib --extern pin_project=/tmp/cargo-installA1weRC/release/deps/libpin_project-8978c9ce33be7e87.rlib --extern qrcode=/tmp/cargo-installA1weRC/release/deps/libqrcode-ad6f8f02162e704d.rlib --extern rand=/tmp/cargo-installA1weRC/release/deps/librand-a7b17b8044cf326c.rlib --extern regex=/tmp/cargo-installA1weRC/release/deps/libregex-28518e8a28150413.rlib --extern ring=/tmp/cargo-installA1weRC/release/deps/libring-e800b92c0800c7e6.rlib --extern rustls_native_certs=/tmp/cargo-installA1weRC/release/deps/librustls_native_certs-4cfcc1e4b3b695fe.rlib --extern serde=/tmp/cargo-installA1weRC/release/deps/libserde-bea299885728ce15.rlib --extern serde_json=/tmp/cargo-installA1weRC/release/deps/libserde_json-76c6db395c079342.rlib --extern serde_urlencoded=/tmp/cargo-installA1weRC/release/deps/libserde_urlencoded-c6fdc8cce98fbe02.rlib --extern sha1=/tmp/cargo-installA1weRC/release/deps/libsha1-6e8d230363f95d77.rlib --extern shadowsocks=/tmp/cargo-installA1weRC/release/deps/libshadowsocks-7ccadcac018b6826.rlib --extern socket2=/tmp/cargo-installA1weRC/release/deps/libsocket2-d75cbdfff8ddf1a8.rlib --extern spin=/tmp/cargo-installA1weRC/release/deps/libspin-8b8a43919173625a.rlib --extern strum=/tmp/cargo-installA1weRC/release/deps/libstrum-ddb089c89b2fc7ed.rlib --extern strum_macros=/tmp/cargo-installA1weRC/release/deps/libstrum_macros-6861548804f898ac.so --extern tokio=/tmp/cargo-installA1weRC/release/deps/libtokio-3f2d8e19257e4715.rlib --extern tokio_rustls=/tmp/cargo-installA1weRC/release/deps/libtokio_rustls-14db321e5ff3e8d1.rlib --extern tower=/tmp/cargo-installA1weRC/release/deps/libtower-c7cd443e7c1f5fa1.rlib --extern trust_dns_proto=/tmp/cargo-installA1weRC/release/deps/libtrust_dns_proto-37d82d057737d8d5.rlib --extern trust_dns_resolver=/tmp/cargo-installA1weRC/release/deps/libtrust_dns_resolver-47d23089756a2d5a.rlib --extern typenum=/tmp/cargo-installA1weRC/release/deps/libtypenum-ff7145ced451eef0.rlib --extern url=/tmp/cargo-installA1weRC/release/deps/liburl-dd07ae9e4f6fcc5c.rlib --extern webpki_roots=/tmp/cargo-installA1weRC/release/deps/libwebpki_roots-d35f2424f7504ce0.rlib --cap-lints allow -L native=/tmp/cargo-installA1weRC/release/build/libsodium-sys-a7dc266567440e1c/out/installed/lib -L native=/tmp/cargo-installA1weRC/release/build/ring-78875f43760f35e8/out` (signal: 9, SIGKILL: kill)

**Comment by zonyitoo** [comment]
It doesn't make any sense. It that `rustc` was killed by OOM-killer?

**Comment by oebrab** [comment]
The error occured after:

```
Compiling ...
Compiling shadowsocks-rust v1.8.23
  Building [===> ] 260/261: sslocal(bin)
```

**Comment by zonyitoo** [comment]
Does your build environment have enough free memory? 2G is recommend.

**Comment by oebrab** [comment]
1GB.

**Comment by zonyitoo** [comment]
```
dmesg | grep OOM
```

You should see `rustc` was killed by OOM killer.

**Comment by zonyitoo** [comment]
Is your problem resolved? @oebrab
