### ISSUE TITLE
server 端能支持 DoT、DoH吗？

### ISSUE THREAD

**Issue by josh-chan** [shadowsocks/shadowsocks-rust#330]
RT，主要是避免vps提供商记录dns请求。

**Comment by dev4u** [comment]
通过第三方软件可以实现

**Comment by dev4u** [comment]
​// DNS server's address for resolving domain names​
    ​// For *NIX and Windows, it uses system's configuration by default​
    ​//​
    ​// Value could be IP address of DNS server, for example, "8.8.8.8".​
    ​// DNS client will automatically request port 53 with both TCP and UDP protocol.​
    ​//​
    ​// It also allows some pre-defined well-known public DNS servers:​
    ​// - google (TCP, UDP)​
    ​// - cloudflare (TCP, UDP)​
    ​// - cloudflare_tls (TLS), enable by feature "dns-over-tls"​
    ​// - cloudflare_https (HTTPS), enable by feature "dns-over-https"​
    ​// - quad9 (TCP, UDP)​
    ​// - quad9_tls (TLS), enable by feature "dns-over-tls"​
    ​//​
    ​// The field is only effective if feature "trust-dns" is enabled.​
    ​"dns"​: ​"google"​,​

**Comment by zonyitoo** [comment]
It already supported right now.

**Comment by 70599** [comment]
Is this working correctly?

After I put `cloudflare_tls` into my server config,
Got this error message: `ERROR Failed to parse DNS "cloudflare_https" in config to IpAddr, fallback to system config`.

My server config:
```json
{
	"server": "0.0.0.0",
	"server_port": 6888,
	"password": "password",
	"timeout": 300,
	"method": "chacha20-ietf-poly1305",
	"dns": "cloudflare_https",
	"mode": "tcp_and_udp"
}
```

**Comment by 70599** [comment]
The binary file `ssserver` is extracted from https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.8.23/shadowsocks-v1.8.23.x86_64-unknown-linux-musl.tar.xz

**Comment by zonyitoo** [comment]
The pre-built releases doesn't have this feature enabled, consider build it by yourself.

```
cargo build --release --features "dns-over-tls dns-over-https local-redir"
```

**Comment by 70599** [comment]
Do I have to set `cloudflare_https` in config on client, or server, or both, to make sure all dns requests will through https?

**Comment by zonyitoo** [comment]
Clients only need DNS resolver for resolving servers' address, or checking if domain name should be proxied or bypassed when ACL is enabled. For most cases, clients doesn't need that `dns` setting.

`dns` have to be set for `ssserver` in your case.

BTW, you could use Docker to build MUSL release by yourself:

```bash
$ cd build
$ EXTRA_FEATURES="dns-over-https dns-over-tls" ./build-release -t x86_64-unknown-linux-musl
```

**Comment by zgzh** [comment]
cargo test --features "dns-over-https"     出错
cargo test --features "dns-over-tls"   ok

**Comment by zonyitoo** [comment]
You could build only with old source code. Current version in master is still depending on trust-dns's unfinished branch.

**Comment by zonyitoo** [comment]
Closing, problem solved.

**Comment by zgzh** [comment]
最新仓库   cargo test --features "dns-over-https"   已经 ok了，谢谢。
