### ISSUE TITLE
Abysmal performance on Windows, UDP6 sockets?

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-rust#331]
Trying to replace shadowsocks-libev (compiled through Cygwin) with shadowsocks-rust results in abysmal performance.

With shadowsocks-libev, opening my browser and loading a page takes roughly 2-3 seconds.
With shadowsocks-rust, the same takes over 40s.

With shadowsocks-libev the browser just creates a bunch of TCP connections from to ss-local and ss-local creates the same number of connections to ss-server that quickly transfer all data.

sslocal however spams UDP6 sockets. After a few seconds it starts creating connections to the ss-server, at which point some data is transferred. Then it starts creating more UDP6 sockets, again. It takes a few more seconds until more connections are created...
This repeats for over 40s until the website is loaded.

Where do these UDP6 sockets come from? I'm not using IPv6 anywhere, neither UDP, the server name resolves to an IPv4 address and the local_address is "127.0.0.1".

**Comment by zonyitoo** [comment]
Did you run `sslocal` in `tcp_and_udp` mode?

**Comment by xnoreq** [comment]
No, I'm running `sslocal.exe -c config.json`.
The config is the same as with ss-local, except I had to add local_address.

Here's the config:
```
{
    "server":"some hostname",
    "server_port":8088,
	"local_port":8088,
	"local_address": "127.0.0.1",
    "password":"some password",
    "timeout":60,
    "method":"aes-128-gcm",
    "fast_open": false,
    "reuse_port": true,
    "no_delay": true
}
```

**Comment by zonyitoo** [comment]
You could start it with `-vvv` again,

```
sslocal.exe -c config.json -vvv
```

and see what it was doing at that time.

I suspect that there was something related to the DNS resolver.

**Comment by xnoreq** [comment]
-vvv prints `initializing local server with Config  ... dns: None, mode: TcpOnly` and all the other properties are also mostly None.

`initializing DNS resolver` shows that it uses my router's IPv6 UDP, IPv6 TCP and IPv4 UDP, then there are 12 more entries which are duplicates and it seems to have grabbed from a VirtualBox host-only network adapter (which makes no sense if it used them over the Ethernet interface, the addresses start with fec0:0:0:ffff::).

Let's ignore that this smells like reinventing the wheel when a simple request could be made to the OS' DNS resolver or to a configured trusted resolver...
sslocal only has to do a single DNS request, namely to resolve the ss-server hostname to figure out which IP to connect to. That's it.

From sslocal receiving the first request to resolving the ss-server hostname it takes 40 ms (!), which is pretty bad considering this is a host on the LAN, the DNS resolver is on the LAN and the name has already been resolved and is in cache.

Worse, it seems to spam DNS requests to all those UDP entries out of the 16 total IPs that it found, some of which are invalid and result in timeouts.

Then it just repeats creating sockets for those fec0:0:0:ffff:: addresses.

**Comment by xnoreq** [comment]
Btw, setting `"dns": "some DNS server IP"` in config manually does result in a considerable speedup, because it doesn't run into these timeout anymore.

**Comment by xnoreq** [comment]
Compiled my own version without trust-dns.
Now it works also without manually and statically specifying a DNS server, resolves extremely fast (log said 3ms), and the resulting binary is 3.3 MB instead of the ~9 MB of the release version.

**Comment by zonyitoo** [comment]
> Btw, setting `"dns": "some DNS server IP"` in config manually does result in a considerable speedup, because it doesn't run into these timeout anymore.

Maybe this could be a temporary solution.

> `initializing DNS resolver` shows that it uses my router's IPv6 UDP, IPv6 TCP and IPv4 UDP, then there are 12 more entries which are duplicates and it seems to have grabbed from a VirtualBox host-only network adapter (which makes no sense if it used them over the Ethernet interface, the addresses start with fec0:0:0:ffff::).

Yes, on Windows, it reads DNS configurations from all your network adapters. Resolver will try to send TCP & UDP requestes to all your configured DNS addresses, so that's why you saw those UDP6 sockets.

**Comment by zonyitoo** [comment]
> Compiled my own version without trust-dns.
> Now it works also without manually and statically specifying a DNS server, resolves extremely fast (log said 3ms), and the resulting binary is 3.3 MB instead of the ~9 MB of the release version.

Yes, that's a good solution thought.

But the default resolver (tokio's default) resolves addresses by calling `getaddrinfo` in a thread pool, so that should result in significant performance lost.

**Comment by zonyitoo** [comment]
Latest master branch won't enable trust-dns by default on Windows. So this problem is solved.

https://github.com/shadowsocks/shadowsocks-rust/blob/56b943501ab3a650881860d164021a1fe9295f2e/crates/shadowsocks-service/src/lib.rs#L76-L85
