### ISSUE TITLE
Valid configuration invalid with shadowsocks-rust and incompatibilities with shadowsocks-libev

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-rust#332]
The binaries link to [quick guide](https://shadowsocks.org/en/config/quick-guide.html).

But there are several issues with shadowsocks-rust when using this configuration:
1) ss-local (from shadowsocks-libev) vs sslocal
ss-local starts just fine. Starting sslocal with that configuration leads to an error, because it additionally needs local_address.

2) ss-server (from shadowsocks-libev) vs ssserver
ss-server reads "server" and "server_port" to listen on that IP:port. No local_* config entries are needed.
ssserver on the other hand does not start without local_* entries which shouldn't even be used. It also does not start without the server_* entries, but incorrectly seems to be using the local_ config entries to bind.

Can you please fix this, especially ssserver (which doesn't even need the local_port entry), to work with the configuration as shown in the quick guide?

**Comment by xnoreq** [comment]
Is the server/server_port configuration from the config file never added to the server config?
The only place where a server config is added is here, and it only happens if SERVER_ADDR was specified on the command line:
https://github.com/shadowsocks/shadowsocks-rust/blob/22c018023298cde2b2a8e1b2d3eb33d16769ad03/bin/server.rs#L145

**Comment by zonyitoo** [comment]
> ss-local starts just fine. Starting sslocal with that configuration leads to an error, because it additionally needs local_address.

It sounds ok. After a glance on the libev version, `ss-local` sets `local_address` to `::1` or `127.0.0.1` depending on `ipv6_first` and all your remote servers whether all of them could be resolved to IPv6 addresses.

> ssserver on the other hand does not start without local_* entries which shouldn't even be used. 

That's not true. `ssserver` could start without `local_*`.

Could you provide an example configuration that could illustrate your problem?

**Comment by zonyitoo** [comment]
> Is the server/server_port configuration from the config file never added to the server config?

That's not true. Reading from configuration is the fundamental feature of `ssserver`.

**Comment by xnoreq** [comment]
I'm sorry, there was an error in the service file I used which started up sslocal instead of ssserver.
I think you also fixed the local_address missing with the latest commit, so I will close this issue.
