### ISSUE TITLE
Windows 下无窗口运行

### ISSUE THREAD

**Issue by YogiLiu** [shadowsocks/shadowsocks-rust#333]
目前在 Windows 下把 sslocal.exe 直接放到任务计划里执行，会导致在执行时跳出 cmd 窗口，能否提供无窗口的可执行文件。

**Comment by dev4u** [comment]
这个锅，sslocal可不背。

**Comment by zonyitoo** [comment]
I am not familiar with Windows, according to [this answer in Stackoverflow](https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window), it seems that what I have to do is to specify

```rust
#![windows_subsystem = "windows"]
```

in all binaries' crate root.

But what would happen if you run this program (`sslocal.exe` in your case) directly in GUI? For example, double click it. If it runs without console prompt, then how can you know it is running?

**Comment by zonyitoo** [comment]
Another side effect is that if using `windows` subsystem, no console output will be made even if you run this program from CMD.

**Comment by zonyitoo** [comment]
You could check this out: https://pureinfotech.com/prevent-command-window-appearing-scheduled-tasks-windows-10/

Create schtasks with "Run whether user is logged on or not" checked.

**Comment by YogiLiu** [comment]
> Create schtasks with "Run whether user is logged on or not" checked.

感谢回复，目前我是用的也是这个方法。

> For example, double click it. If it runs without console prompt, then how can you know it is running?

这个功能主要用于一些特殊场景，譬如把程序放在任务计划里启动。至于如何判断它是否正常运行，可以通过任务管理器查看，也可以通过 curl 发起一次测试请求。

**Comment by YogiLiu** [comment]
V2Ray-core 的 Windows 版本会提供一个名为 wv2ray.exe 的可执行文件，这个可执行文件在运行时不会弹出 CMD 窗口，直接进入后台运行，不知对您是否有参考价值。

**Comment by zonyitoo** [comment]
> V2Ray-core 的 Windows 版本会提供一个名为 wv2ray.exe 的可执行文件，这个可执行文件在运行时不会弹出 CMD 窗口，直接进入后台运行，不知对您是否有参考价值。

Well, that is an easy task. I may add this after I finished #326 .

**Comment by database64128** [comment]
As a Windows user, I'm against implementing this feature. In my opinion, `wv2ray.exe` shouldn't have existed in the first place. This is a typical example of overengineering.

**Comment by zonyitoo** [comment]
I personally don't possess any Windows devices, so I don't know whether setting a binary to Windows Subsystem is required for all Windows users or not.

**Comment by database64128** [comment]
After raising the issue at V2Fly and some discussions, we have reached an agreement to drop `wv2ray.exe` in the upcoming V2Ray version 5. See https://github.com/v2fly/v2ray-core/commit/fe60260d48a2ce482268239cb56b99ba15bb2633.

> Is it mandatory for all release binaries?
> Is it a common case for all Windows users?

The user should be running ss-rust as a service instead of using the task scheduler to start ss-rust. Expecting the service itself to behave in a certain way is just as ridiculous as expecting it to have a full-blown GUI. It makes no sense at all because it's not designed and never intended to be that way.

**Comment by database64128** [comment]
v2fly/v2ray-core#488

**Comment by zonyitoo** [comment]
Then I think this issue could be closed.

**Comment by YogiLiu** [comment]
赞同 @database64128 的意见。
经过查阅资料，Windows 用户可以通过 [nssm](https://nssm.cc/) 将 shadowsocks-rust 注册成为服务，使用方法类似于 Linux 下的 systemctl 命令。
