### ISSUE TITLE
ERROR Failed to get TcpRequestHeader

### ISSUE THREAD

**Issue by alienzj** [shadowsocks/shadowsocks-rust#336]
Hi, How to avoid this error ?

```
Dec 01 13:55:57 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: Connection reset by peer (os error 104)
Dec 01 13:57:45 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: Connection reset by peer (os error 104)
Dec 01 13:57:45 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: Connection reset by peer (os error 104)
Dec 01 14:05:12 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: early eof
Dec 01 15:37:23 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: early eof
Dec 01 15:37:27 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: Connection reset by peer (os error 104)
Dec 01 15:53:18 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: early eof
Dec 01 15:53:26 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: early eof
Dec 01 15:54:13 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: Connection reset by peer (os error 104)
Dec 01 16:09:05 supermeta sslocal-rust[2979629]: ERROR Failed to get TcpRequestHeader: early eof
```

**Comment by zonyitoo** [comment]
It seems that connection is lost before getting the full SOCKS5 TCP request header. Check your configuration first.

**Comment by alienzj** [comment]
Hi, this is my configuration:
```
{
    "server":"xx.xx.xx.xx",
    "server_port":8888,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"***********",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "plugin": "v2ray-plugin",
    "fast_open": false,
    "workers": 1,
    "prefer_ipv6": false
}

```

Thanks.

**Comment by zonyitoo** [comment]
```
curl "https://www.baidu.com" --socks5-hostname "127.0.0.1:1080"
```

Could you test if it is work with your configuration?

**Comment by alienzj** [comment]
Yes, STATUS OK.

**Comment by zonyitoo** [comment]
That indicates that there was at least one client trying to connect to your port in an unrecognized protocol, your `sslocal` itself runs pretty well.

**Comment by klaaktu** [comment]
Hi, I also see some of this error message in the log, along with
> Thu Jul  8 17:49:49 2021 daemon.err sslocal[12129]: 2021-07-08T17:49:49.243585795+00:00 ERROR failed to get TcpRequestHeader: Connection reset by peer (os error 131)

Is this because I exposed my sslocal to the WAN (listening on [::])? Is it a bad idea?
Can I find out more about the bad peer? Recently my Firebox is stuttering frequently with Google websites, not sure if it's related...

**Comment by zonyitoo** [comment]
Clients already sent SOCKS5 handshakes but didn't send any `TcpRequestHeader` to `sslocal`. I could add some logs for you.

**Comment by klaaktu** [comment]
Thanks. I `tcpdump`'d those packets, turns out they _are_ from me. Indeed after receiving socks authentication message, they just closed the connection without asking to connect to anything. Maybe it _is_ because of the ad blocker.
