### ISSUE TITLE
thread 'main' panicked at 'logging: Errors

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#337]
编译x86_64-unknown-linux-gnu的最新版，直接复制官方文档的也不行
```
root@BoringClever-VM:~# ./ssmanager --manager-address "127.0.0.1:6100" -vvv
thread 'main' panicked at 'logging: Errors { errors: [DuplicateLoggerName("shadowsocks")] }', bin/logging/mod.rs:67:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
root@BoringClever-VM:~#
```
![IMG_20201202_103958](https://user-images.githubusercontent.com/22967964/100821311-1279c200-348b-11eb-9fec-a9493b8975b0.jpg)

这是我编译的文件  https://github.com/yiguihai/shadowsocks_install/blob/master/bin/ssserver

**Comment by zonyitoo** [comment]
Couldn't reproduce on my laptop. Did you compile directly from master?

**Comment by yiguihai** [comment]
> Couldn't reproduce on my laptop. Did you compile directly from master?

是的我用master分支
我的编译脚本https://github.com/yiguihai/shadowsocks_install/raw/master/.github/workflows/bin.yml
编译也没有报错
https://github.com/yiguihai/shadowsocks_install/runs/1483785221?check_suite_focus=true#step:20:409

**Comment by zgzh** [comment]
master分支同样复现，编译成功运行同样报错
`./ssserver -s "[::]:8388" -m "aes-256-gcm" -k "hello-kitty" -vvv
thread 'main' panicked at 'logging: Errors { errors: [DuplicateLoggerName("shadowsocks")] }', bin/logging/mod.rs:67:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by zonyitoo** [comment]
Oh I see. Bug confirmed.

**Comment by zgzh** [comment]
谢谢你的迅速修复，问题已经解决~
