### ISSUE TITLE
Binary release is not statically linked?

### ISSUE THREAD

**Issue by KaraRyougi** [shadowsocks/shadowsocks-rust#338]
The README says `Download static-linked build here.` and directs me to the release page. I downloaded `shadowsocks-v1.8.23.mips-unknown-linux-musl.tar.xz`. 

However, I'm unable to run it on my EdgeRouter. I got this error: `-bash: ./sslocal: No such file or directory`. Checking the binaries, I find that they seem to be dynamically linked:
`sslocal: ELF 32-bit MSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-mips-sf.so.1, not stripped`

**Comment by zonyitoo** [comment]
To check if a binary is dynamic linked or not, you can use the `ldd` command:

```
ldd sslocal
```

**Comment by zonyitoo** [comment]
>  I got this error: `-bash: ./sslocal: No such file or directory. `

This error shows that this binary is not runnable on your system. Maybe it is because the binary is 32-bit but your are running a 64-bit system.

**Comment by KaraRyougi** [comment]
> > I got this error: `-bash: ./sslocal: No such file or directory. `
> 
> This error shows that this binary is not compatible on your system. Maybe it is because the binary is 32-bit but your are running a 64-bit system.

Thanks for pointing this out! Turns out you are correct. My kernel info shows mips64.

`ldd sslocal` gives me:
`./sslocal: error while loading shared libraries: /usr/lib/mips-linux-gnu/libc.so: invalid ELF header`

**Comment by zonyitoo** [comment]
https://github.com/rust-embedded/cross

You could build one by yourself.

```
cross build --release --target "mips64-unknown-linux-gnuabi64"
```

But `cross` doesn't provide a MIPS64 image with MUSL, so you may have to make a cross build in your own environment.
