### ISSUE TITLE
'called `Result::unwrap()` on an `Err` value: InvalidUserInfo',

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#341]
ssurl无法解析ss://链接  
1.9.0版本  
测试的链接  
```
ss://bm9uZTpZMlJtWkdJMlpqY3RNako=@23.95.220.139:10665/?plugin=v2ray-plugin%3bpath%3d15cf38018c6334c7a28243ffd6b76b50%3bhost%3dmikutap.ml#%e7%be%8e%e5%9b%bd%20%e7%ba%bd%e7%ba%a6%e5%b7%9e%20%e5%b8%83%e6%b3%95%e7%bd%97%20colocrossing.com
```
出错信息
![IMG_20201211_084922](https://user-images.githubusercontent.com/22967964/101847271-d2eb5e00-3b8d-11eb-9b0f-3ee9c5dcd645.jpg)  
```Shell
root@BoringClever-VM:/etc/ssmanager/bin# ./ssurl -d "ss://bm9uZTpZMlJtWkdJMlpqY3RNako=@23.95.220.139:10665/?plugin=v2ray-plugin%3bpath%3d15cf38018c6334c7a28243ffd6b76b50%3bhost%3dmikutap.ml#%e7%be%8e%e5%9b%bd%20%e7%ba%bd%e7%ba%a6%e5%b7%9e%20%e5%b8%83%e6%b3%95%e7%bd%97%20colocrossing.com"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUserInfo', bin/ssurl.rs:60:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```
链接可以正常导入安卓客户端但ssurl就是解析出错

**Comment by zonyitoo** [comment]
This is not a SIP002 URL. https://github.com/shadowsocks/shadowsocks-org/issues/27

We could see in SIP002:

```
userinfo = websafe-base64-encode-utf8(method  ":" password)
```

And your UserInfo is `bm9uZTpZMlJtWkdJMlpqY3RNako=`, which obviously is not a *Websafe Base64* encode.

**Comment by yiguihai** [comment]
> This is not a SIP002 URL. [shadowsocks/shadowsocks-org#27](https://github.com/shadowsocks/shadowsocks-org/issues/27)
> 
> We could see in SIP002:
> 
> ```
> userinfo = websafe-base64-encode-utf8(method  ":" password)
> ```
> 
> And your UserInfo is `bm9uZTpZMlJtWkdJMlpqY3RNako=`, which obviously is not a _Websafe Base64_ encode.

还是希望兼容一下

**Comment by zonyitoo** [comment]
Where did you get these non-standard URLs?

**Comment by yiguihai** [comment]
> Where did you get these non-standard URLs?

这是我的脚本处理后输出的😓现在已经搞定了
