### ISSUE TITLE
timeout handling is completely broken

### ISSUE THREAD

**Issue by notsure2** [shadowsocks/shadowsocks-rust#343]
Hello,
Shadowsocks applies the timeout not on receiving first data from the client, but on any traffic activity in the entire connection. This is completely wrong and has been fixed before in shadowsocks-libev a very long time ago (years). Even Cloak had this problem and I had to fix it myself.

Why this is wrong ?
Because shadowsocks is not a sockets application, it is just a proxy. A proxy should not assume ownership and enforce its own timeouts. It should be completely transparent and not alter the characteristics of the connection. It is up to the Layer 8 (?) application that's running on TOP of shadowsocks to implement its own timeouts or keepalives in the application layer (eg: SSH sending of null packets, HTTP keep alives, HTTP timeouts), and not the job of a proxy application.

The only kind of timeout that's permissible for a "proxy" kind of application to enforce is a timeout for the **initial** data reception from the local application, or from the client (in the server's point of view) and ONLY as a kind of defense from resource exhaustion attacks.

Otherwise, many kinds of problems will happen to proxied applications (eg: killing of Idle SSH sessions) or termination of long idle connections that are supposed to be completely valid.

I keep seeing this mistake being repeated in application after application. Please fix this. I don't know rust to fix this myself and now shadowsocks-libev project is directing users to use this one instead which has this serious regression of behavior.

Thank you for understanding.

**Comment by zonyitoo** [comment]
I have to check out how libev handles the `timeout` setting. Could you provide a hint for me?

**Comment by madeye** [comment]
As mentioned by @Mygod before, maybe we should remove timeout logic from shadowsocks entirely.

At least, sslocal doesn't need a timeout setting, browsers and apps can handle timeout for us.

**Comment by zonyitoo** [comment]
Great. I am totally agree with that.

**Comment by notsure2** [comment]
@zonyitoo 

How libev handles timeout now (and this is the correct behavior):

- For shadowsocks client: The timeout is applied on receiving a full SOCKS5 request header from the application. Once the application sent the SOCKS5 header and it is valid, there is no more timeout, even if the application doesn't send anymore data (ie: it handshakes with ss-local and then sends nothing). This way it protects from bad apps that open lot of connections and don't send any data.

- For shadowsocks server: The timeout is applied on receiving an encrypted shadowsocks request header from the incoming connecting client. Once the header is read there is no more timeout, even if the shadowsocks client didn't send anymore bytes. This way it protects from attackers establishing TCP connections and then holding the connection open without sending any proper shadowsocks handshake.
