### ISSUE TITLE
DNS relay LocalStream could use the global DNS resolver

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#346]
I found that there is a hijack in `Context::dns_resolve`:

https://github.com/shadowsocks/shadowsocks-rust/blob/d0fc26317d5ce26de9dafe4dd1c241a9f23b1cfc/shadowsocks/src/context.rs#L313-L320

which will try to send DNS queries to `local-dns-addr` instead of the builtin DNS resolver.

If the `trust-dns` feature is enabled, `TokioAsyncResolver`'s nameserver is configurable via the `dns` key in the configuration. So is it possible to remove these lines?

@madeye @Mygod

**Comment by madeye** [comment]
I provided the DNS address directly to the built-resolver:

https://github.com/shadowsocks/shadowsocks-android/blob/2bb9a6da7d07b5f47e624e242aae634c8354302d/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L90

So, I think it's fine to remove `local-dns-addr` here now.

**Comment by zonyitoo** [comment]
The only problem is that `TokioAsyncResolver`'s outbound socket is not protected by `VpnService`.

**Comment by madeye** [comment]
@Mygod If I understand correctly, the local DNS provided by shadowsocks-android is the same as the system resolver?

**Comment by Mygod** [comment]
> I provided the DNS address directly to the built-resolver:
> 
> https://github.com/shadowsocks/shadowsocks-android/blob/2bb9a6da7d07b5f47e624e242aae634c8354302d/core/src/main/java/com/github/shadowsocks/bg/ProxyInstance.kt#L90
> 
> So, I think it's fine to remove `local-dns-addr` here now.

Isn't that the address that shadowsocks-rust is supposed to listen on?

The local DNS is supposed to be Android's resolver for underlying network interface in Android, through a uds.

**Comment by madeye** [comment]
Okay, I forgot we have a default local DNS address `local_dns_path`...

So, actually, unless shadowsocks-rust finds a way to use the Android's resolver for underlying network, I don't think we can remove the local-dns feature here.

**Comment by zonyitoo** [comment]
ok.
