### ISSUE TITLE
Use same port for SOCKS5/HTTP proxy

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-rust#349]
https://github.com/shadowsocks/shadowsocks-android/issues/2577

**Comment by zonyitoo** [comment]
Accepts a `TcpStream` and then choose protocol automatically by the first byte?

```rust
match first_byte {
    0x05 => handle_socks5_stream
    0x04 => handle_socks4_stream
    'H' | 'h' => handle_http_stream
}
```

**Comment by dev4u** [comment]
> Accepts a `TcpStream` and then choose protocol automatically by the first byte?
> 
> ```rust
> match first_byte {
>     0x05 => handle_socks5_stream
>     0x04 => handle_socks4_stream
>     'H' | 'h' => handle_http_stream
> }
> ```
> 
> That is quite hard to implement that with hyper. There is no API for this = =..

或许可以参考一下，clash是怎么实现？他们家好像见到能支持类似的功能

**Comment by zonyitoo** [comment]
I know hot to implement that, the only problem is [hyper](https://crates.io/crates/hyper) doesn't provide a API for me to customize `Server`'s accept process.

**Comment by madeye** [comment]
@zonyitoo IIRC, some similar apps use pipes / channels to redirect the traffic to their HTTP modules.

BTW, I think it's a low priority request.

**Comment by LuoZijun** [comment]
> I know how to implement that, the only problem is [hyper](https://crates.io/crates/hyper) doesn't provide a API for me to customize `Server`'s accept process.

`first_byte` 使用 `.peek(...)` ？

**Comment by zonyitoo** [comment]
I don't think the problem is how to guess which protocol going to be used,

https://github.com/shadowsocks/shadowsocks-rust/blob/1d11fba996c3a62333da511354cc21315b0af552/crates/shadowsocks-service/src/local/socks/server/mod.rs#L171-L177

the key issue is that there is no API to feed an accepted `TcpStream` into a hyper `Server` instance.

**Comment by 18o** [comment]
I think it could be all local services use one common port, or loop all ports set in local configure file, start tcp/udp services for each port and dispatch to different workers by checking the inbound package.In this way local dns can be  mixed as well.

**Comment by database64128** [comment]
I don't see how one could run out of ports for local services. Having multiple services over the same port adds unnecessary complexity and overhead.

**Comment by zonyitoo** [comment]
Supported on master branch.

**Comment by ljw20180420** [comment]
How to use SOCKS5/HTTP at the same port? I cannot find a guide on this.
