### ISSUE TITLE
ssserver绑定的udp端口不过期

### ISSUE THREAD

**Issue by kckm** [shadowsocks/shadowsocks-rust#351]
用最新的master线的代码编译，cargo +nightly build --release， 运行ssserver，配置文件udp_timeout:120，使用netstat -tulnp 命令查看，udp端口一直存在，使用release里的1.8.23则无此问题。

**Comment by zonyitoo** [comment]
You can trigger a cleanup by sending a packet to it.

**Comment by zonyitoo** [comment]
Or I could add back active cleanup logics in 1.8.23.

**Comment by zonyitoo** [comment]
It should be related to another bug, which was fixed with the latest commit.
