### ISSUE TITLE
Upgrade to tokio v1.0

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#354]
- HTTP
  - [x] Hyper v0.14
  - [x] tokio-rustls v0.22
  - [x] tokio-native-tls
  - [x] tower
- DNS
  - [x] trust-dns (trust-dns-resolver, trust-dns-proto, trust-dns-client) https://github.com/bluejekyll/trust-dns/issues/1329

**Comment by IceCodeNew** [comment]
剩下的两个应该都在上游解决了～

**Comment by zonyitoo** [comment]
https://github.com/bluejekyll/trust-dns/blob/main/crates/resolver/Cargo.toml#L80

trust-dns didn't update yet.

**Comment by mqy** [comment]
1.0.0 was replaced with 1.0.1 which fixed a soundness hole https://github.com/tokio-rs/tokio/releases/tag/tokio-1.0.1

**Comment by zonyitoo** [comment]
It doesn't matter, we don't need this `RwLock`
