### ISSUE TITLE
自动退出

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#357]
打扰了  😊
编译的最新版，问题应该出在这一两天的改动。
服务端运行一切正常，客户端连接后就报错自动退出了。
```
INFO  [26424:140387844658752] [ssserver] shadowsocks 1.9.0  
INFO  [26424:140387844658752] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 0.0.0.0:1234, inbound address 0.0.0.0:1234  
INFO  [26424:140387844658752] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 0.0.0.0:1234  
thread 'tokio-runtime-worker' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /home/runner/.cargo/git/checkouts/trust-dns-97a7602ad159d348/0662ab6/crates/resolver/src/name_server/connection_provider.rs:343:25                                                                                               note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                   
/tmp/tmp.tm4j4K4rQZ/ss-main: line 1267:
```  
![IMG_20201225_004250](https://user-images.githubusercontent.com/22967964/103099678-6c187b00-464a-11eb-97ce-5eef1b6f8f2f.jpg)

希望作者能完善编译后的自动化功能测试，我还是改成几个月编译一次吧。

**Comment by zonyitoo** [comment]
Well, I know this issue, https://github.com/shadowsocks/shadowsocks-rust/actions

**Comment by zgzh** [comment]
服务端也会退出，重启还不会自启，很诡异，启动脚本都是一样，之前的版本没这个状况~

**Comment by zgzh** [comment]
还是下载发行包算了

**Comment by yiguihai** [comment]
> 还是下载发行包算了

.你是用我的脚本的吗？

**Comment by zgzh** [comment]
没有，我本机构建，用的这个启动[脚本](https://github.com/shadowsocks/shadowsocks-rust/blob/master/debian/shadowsocks-rust-server%40.service)

**Comment by zgzh** [comment]
报错日志``thread 'tokio-runtime-worker' panicked at 'must be called from the context of Tokio runtime con
12月 25 13:25:32 pi ssserver[603]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
