### ISSUE TITLE
Failed to build from git using rustup nightly

### ISSUE THREAD

**Issue by chromer030** [shadowsocks/shadowsocks-rust#365]
$ cargo build --release   
error: failed to run custom build command for `proc-macro2 v1.0.24`

Caused by:
  process didn't exit successfully: `/shadowsocks-rust/target/debug/build/proc-macro2-a5a5780f735c08f5/build-script-build` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  cargo:rerun-if-changed=build.rs
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by database64128** [comment]
The error message is quite clear. You should probably google it and investigate before creating an issue here without much useful information.

**Comment by DuckSoft** [comment]
SIGILL: illegal instruction

Usually caused by:
```
using a toooooooooooooooooooooooooooooooooooooooooooooooo oooooooooooooooooooooooold cpu
```

**Comment by chromer030** [comment]
My CPU is Kaby Lake and i think it's not old.
Just i forgot to add `rustflags = ["-Ctarget-feature=+aes,+sse2,+ssse3"]` to cargo's config file.

**Comment by zonyitoo** [comment]
> error: failed to run custom build command for proc-macro2 v1.0.24

I suspected that you have been trying to making a cross build. The *build script* is running on your host machine.

Otherwise, you could try to delete the `.cargo` folder in the root directory. If it works, it means that you are using a very old CPU.

**Comment by zonyitoo** [comment]
I have removed some modern CPU features from `config.toml`, which should be able to be compatible with some old CPUs.

**Comment by chromer030** [comment]
@zonyitoo 
Hi , Thank you so much , you are great.
I have multiple Haswell , Skylake and Kabylake CPUs and days ago, by removing non-essential Instruction Sets from `config.toml` i was able to compile and use the tool successfully on all mentioned platforms.
Thank you again
