### ISSUE TITLE
请问rust支持加速aes-128-gcm吗？

### ISSUE THREAD

**Issue by Meilinhost** [shadowsocks/shadowsocks-rust#368]
请问rust支持加速aes-128-gcm吗？
我看到libev默认只能加速aes-256-gcm，

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L169

https://github.com/shadowsocks/shadowsocks-libev/issues/2243#issuecomment-471446803

不知道rust有没有支持到128

现在运行库是mbedTLS还是openssl

**Comment by zonyitoo** [comment]
We use https://github.com/shadowsocks/crypto2 . And yes, on x86_64, aes is hardware acclerated.

**Comment by Meilinhost** [comment]
> 我们使用https://github.com/shadowsocks/crypto2。是的，在x86_64上，es是硬件兼容的。

也就是说它是支持128gcm硬解的吗，不需要为此改成256gcm来参与硬解是吧

**Comment by DuckSoft** [comment]
✅

**Comment by zonyitoo** [comment]
> > 我们使用[https://github.com/shadowsocks/crypto2。是的，在x86_64上，es是硬件兼容的。](https://github.com/shadowsocks/crypto2%E3%80%82%E6%98%AF%E7%9A%84%EF%BC%8C%E5%9C%A8x86_64%E4%B8%8A%EF%BC%8Ces%E6%98%AF%E7%A1%AC%E4%BB%B6%E5%85%BC%E5%AE%B9%E7%9A%84%E3%80%82)
> 
> 也就是说它是支持128gcm硬解的吗，不需要为此改成256gcm来参与硬解是吧

It depends on your platform. If you are using x86, armv6, mips, ... , then there is no hardware accleration.
