### ISSUE TITLE
Can we have mips64 build for the release?

### ISSUE THREAD

**Issue by KaraRyougi** [shadowsocks/shadowsocks-rust#370]
I use a mips64 device as my router. Thanks!

**Comment by zonyitoo** [comment]
`mips64-unknown-linux-gnuabi64` or `mips64el-unknown-linux-gnuabi64`?

**Comment by KaraRyougi** [comment]
`mips64-unknown-linux-gnuabi64`. The device is EdgeRouter 4 by the way.

**Comment by zonyitoo** [comment]
Could you verify if the build output works for your router?

```bash
cd build
./build-release -t mips64-unknown-linux-gnuabi64
```

**Comment by abcfy2** [comment]
> Could you verify if the build output works for your router?
> 
> ```shell
> cd build
> ./build-release -t mips64-unknown-linux-gnuabi64
> ```

Maybe `mips64-unknown-linux-muslabi64` is better ? Because it has no relation with kernel version.

**Comment by zonyitoo** [comment]
https://github.com/rust-embedded/cross

Unfortunately, `cross` doesn't support that.

**Comment by KaraRyougi** [comment]
> Could you verify if the build output works for your router?
> 
> ```shell
> cd build
> ./build-release -t mips64-unknown-linux-gnuabi64
> ```

I build the binary by `cross build --target mips64-unknown-linux-gnuabi64 --release`.
When it runs on my EdgeRouter 4, the following error occurred: `Accessing a corrupted shared library`. I also see files like `sslocal.d` under the release folder.

```
file sslocal

sslocal: ELF 64-bit MSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, interpreter /lib64/ld.so.1, BuildID[sha1]=eaf9d2afd82bb742f76069c39b664ae9fa5f9b3c, for GNU/Linux 3.2.0, not stripped
```

Also, I'm not sure how to enable the `local-redir` option.

**Comment by zonyitoo** [comment]
> Also, I'm not sure how to enable the local-redir option.

```
cross build --target mips64-unknown-linux-gnuabi64 --release --features "local-redir"
```

> I also see files like `sslocal.d` under the release folder.

It doesn't matter.

> When it runs on my EdgeRouter 4, the following error occurred: `Accessing a corrupted shared library`

I am not familiar with this error. You may need to find out the reason by yourself.

**Comment by abcfy2** [comment]
> > Could you verify if the build output works for your router?
> > ```shell
> > cd build
> > ./build-release -t mips64-unknown-linux-gnuabi64
> > ```
> 
> I build the binary by `cross build --target mips64-unknown-linux-gnuabi64 --release`.
> When it runs on my EdgeRouter 4, the following error occurred: `Accessing a corrupted shared library`. I also see files like `sslocal.d` under the release folder.
> 
> ```
> file sslocal
> 
> sslocal: ELF 64-bit MSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, interpreter /lib64/ld.so.1, BuildID[sha1]=eaf9d2afd82bb742f76069c39b664ae9fa5f9b3c, for GNU/Linux 3.2.0, not stripped
> ```
> 
> Also, I'm not sure how to enable the `local-redir` option.

Seems that your shared library is broken ? Maybe you can check with:

```sh
ldd sslocal
```

Then you can find the linked shared libraries and check which library is broken.

**Comment by KaraRyougi** [comment]
```
ldd sslocal
	not a dynamic executable
```

Oops. Sorry for wasting you guys time. EdgeRouter 4 is actually not MIPS64.

```
/bin/bash: ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 3.2.0, BuildID[sha1]=cf04fe027c6d0ffdc84ca97b264d0c67f0132c15, stripped
```

However the `mips-unknown-linux-musl` version doesn't work on the system...

**Comment by abcfy2** [comment]
> ```
> ldd sslocal
> 	not a dynamic executable
> ```
> 
> Oops. Sorry for wasting you guys time. EdgeRouter 4 is actually not MIPS64.
> 
> ```
> /bin/bash: ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 3.2.0, BuildID[sha1]=cf04fe027c6d0ffdc84ca97b264d0c67f0132c15, stripped
> ```
> 
> However the `mips-unknown-linux-musl` version doesn't work on the system... I'll try to compile for `mips-unknown-linux-gnu`.

Please show the output:

```sh
uname -a
```

and

```sh
cat /proc/cpuinfo
```

**Comment by KaraRyougi** [comment]
I failed building the project with `cross build --target mips64-unknown-linux-gnu --release --features "local-redir"`.

```  
Compiling shadowsocks-service v1.9.0 (/project/crates/shadowsocks-service)
error[E0308]: mismatched types
  --> crates/shadowsocks-service/src/net/flow.rs:58:9
   |
57 |     pub fn rx(&self) -> u64 {
   |                         --- expected `u64` because of return type
58 |         self.rx.load(Ordering::Relaxed) as u32
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         expected `u64`, found `u32`
   |         help: you can convert a `u32` to a `u64`: `(self.rx.load(Ordering::Relaxed) as u32).into()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `shadowsocks-service`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

System information:

```
~$ uname -a
Linux router-home 4.9.79-UBNT #1 SMP Thu Mar 5 16:49:39 UTC 2020 mips64 GNU/Linux
~$ cat /proc/cpuinfo
system type		: UBNT_E300
machine			: Unknown
processor		: 0
cpu model		: Cavium Octeon III V0.2  FPU V0.0
BogoMIPS		: 2000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 256
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	: vz
shadow register sets	: 1
kscratch registers	: 4
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 1
cpu model		: Cavium Octeon III V0.2  FPU V0.0
BogoMIPS		: 2000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 256
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	: vz
shadow register sets	: 1
kscratch registers	: 4
package			: 0
core			: 1
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 2
cpu model		: Cavium Octeon III V0.2  FPU V0.0
BogoMIPS		: 2000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 256
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	: vz
shadow register sets	: 1
kscratch registers	: 4
package			: 0
core			: 2
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 3
cpu model		: Cavium Octeon III V0.2  FPU V0.0
BogoMIPS		: 2000.00
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 256
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa			: mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented	: vz
shadow register sets	: 1
kscratch registers	: 4
package			: 0
core			: 3
VCED exceptions		: not available
VCEI exceptions		: not available
```

Wait... so MIPS64 is compatible with MIPS32? I guess I got confused since aarch64 is not compatible with 32-bit ARM...

**Comment by zonyitoo** [comment]
That's strange. The `musl` version is not a dynamic linked binary.

**Comment by abcfy2** [comment]
Seems that there is something wrong with `mips-unknown-linux-musl` building.

```sh
$ qemu-mips ./sslocal --version
qemu-mips: Could not open '/lib/ld-musl-mips-sf.so.1': No such file or directory
```

The `musl` version should be staticlly linked in fact.

**Comment by KaraRyougi** [comment]
After applying the patch to fix the build error, `cross build --target mips-unknown-linux-gnu --release --features "local-redir"` successfully builds the binaries that can run on my EdgeRouter 4. Thanks everyone for helping me!
