### ISSUE TITLE
Using special character in key causes decryption failure.

### ISSUE THREAD

**Issue by colin0154** [shadowsocks/shadowsocks-rust#372]
I change to shadowsocks-rust from libev today, and not able to make it run. It prompts that AEAD decryption failed whatever method I use (I tried chacha20, xchacha20 and AES, all of them are AEAD varients). I find out it was the special character '$' I used in my key that cause the problem. 

Maybe it's a bug?  By the way it failed to parse my config json, while it's the same one used by libev-port.

Version: v1.8.23 (locally build)
OS: Fedora 32

**Comment by zonyitoo** [comment]
Please provide your configuration. I cannot help you if I cannot reproduce your problem.

**Comment by zonyitoo** [comment]
I tested `sslocal` with libev's `ss-server` with the following configuration:

```json
{
    "method": "aes-128-gcm",
    "password": "abc$abc"
}
```

Everything works fine.

**Comment by colin0154** [comment]
I directly run this line in CLI with minimal configuration, then connect to it using shadowsocks-windows client.

`/usr/local/bin/ssserver -s [::]:8838 -m chacha20-ietf-poly1305 -k itsmyspecial$fakekey`

```
INFO shadowsocks TCP listening on [::]:8838

2021-01-04T04:34:40.616122387+00:00 ERROR AEAD decrypt failed, input=b"\x15\xa3", tag=b"\xd5\x8d(=dw\x1a181\xde[\xa6TvX", opening: OpeningKey { algorithm: CHACHA20_POLY1305 }
2021-01-04T04:34:40.617181379+00:00 ERROR failed to decode Address, may be wrong method or key, from client [::ffff:*.*.*.*]:60653, error: AEAD decrypt error
```

But with the same key without $, it works.

**Comment by colin0154** [comment]
If I choose to use config (the same one used by libev, and it's working), it would encounter some parse error.

```
{
        "server":"0.0.0.0",
        "server_port":****,
        "password":"*******with$inside*******",
        "timeout":"600",
        "method":"chacha20-ietf-poly1305",
        "fast_open":true,
        "mode":"tcp_only"
}
```
```
# ssserver -c /snap/shadowsocks-libev/config.json
thread 'main' panicked at 'loading config "/snap/shadowsocks-libev/config.json", json parse error, Message("error parsing number")', src/bin/server.rs:107:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

# ssserver --version
shadowsocks 1.8.23
```

**Comment by DuckSoft** [comment]
timeout is number not string

**Comment by DuckSoft** [comment]
> I directly run this line in CLI with minimal configuration, then connect to it using shadowsocks-windows client.
> 
> 
> 
> `/usr/local/bin/ssserver -s [::]:8838 -m chacha20-ietf-poly1305 -k itsmyspecial$fakekey`
> 
> 
> 
> ```
> 
> INFO shadowsocks TCP listening on [::]:8838
> 
> 2021-01-04T04:34:40.616122387+00:00 ERROR AEAD decrypt failed, input=b"\x15\xa3", tag=b"\xd5\x8d(=dw\x1a181\xde[\xa6TvX", opening: OpeningKey { algorithm: CHACHA20_POLY1305 }
> 
> 2021-01-04T04:34:40.617181379+00:00 ERROR failed to decode Address, may be wrong method or key, from client [::ffff:*.*.*.*]:60653, error: AEAD decrypt error
> 
> ```
> 
> 
> 
> But with the same key without $, it works.

wrap your password with single quote `'`. shell basic.

**Comment by zonyitoo** [comment]
> I directly run this line in CLI with minimal configuration, then connect to it using shadowsocks-windows client.
> 
> `/usr/local/bin/ssserver -s [::]:8838 -m chacha20-ietf-poly1305 -k itsmyspecial$fakekey`
> 
> ```
> INFO shadowsocks TCP listening on [::]:8838
> 2021-01-04T04:34:40.616122387+00:00 ERROR AEAD decrypt failed, input=b"\x15\xa3", tag=b"\xd5\x8d(=dw\x1a181\xde[\xa6TvX", opening: OpeningKey { algorithm: CHACHA20_POLY1305 }
> 2021-01-04T04:34:40.617181379+00:00 ERROR failed to decode Address, may be wrong method or key, from client [::ffff:*.*.*.*]:60653, error: AEAD decrypt error
> ```
> 
> But with the same key without $, it works.

Hah... You are running the command in shell, which `$` is the prefix of shell's variable.

Specifically, `itsmyspecial$fakekey` is equivalent to a string concatenation: `"itsmyspecial" + "$fakekey"`. The second part of substring reads from a variable called `fakekey`, which doesn't exists in your context.

So your password becomes `itsmyspecial`.

Solution is quite simple, `-k 'itsmyspecial$fakekey'`.

It shouldn't work in libev, because `$` is processed by shell.

**Comment by zonyitoo** [comment]
> If I choose to use config (the same one used by libev, and it's working), it would encounter some parse error.
> 
> ```
> {
>         "server":"0.0.0.0",
>         "server_port":****,
>         "password":"*******with$inside*******",
>         "timeout":"600",
>         "method":"chacha20-ietf-poly1305",
>         "fast_open":true,
>         "mode":"tcp_only"
> }
> ```
> 
> ```
> # ssserver -c /snap/shadowsocks-libev/config.json
> thread 'main' panicked at 'loading config "/snap/shadowsocks-libev/config.json", json parse error, Message("error parsing number")', src/bin/server.rs:107:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Aborted (core dumped)
> 
> # ssserver --version
> shadowsocks 1.8.23
> ```

Interestingly, [libev accepts your wrong json](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/jconf.h#L69). @madeye Why libev reads `timeout` as a string?

**Comment by madeye** [comment]
I handled the conversion here: 

1. https://github.com/shadowsocks/shadowsocks-libev/blob/b68157e6f72ed10c91c82554cdb82785295370fc/src/jconf.c#L43
2. https://github.com/shadowsocks/shadowsocks-libev/blob/b68157e6f72ed10c91c82554cdb82785295370fc/src/jconf.c#L258

But yes, it is unnecessary.

**Comment by colin0154** [comment]
> Hah... You are running the command in shell, which `$` is the prefix of shell's variable.
> 
> Specifically, `itsmyspecial$fakekey` is equivalent to a string concatenation: `"itsmyspecial" + "$fakekey"`. The second part of substring reads from a variable called `fakekey`, which doesn't exists in your context.
> 
> So your password becomes `itsmyspecial`.
> 
> Solution is quite simple, `-k 'itsmyspecial$fakekey'`.
> 
> It shouldn't work in libev, too, because `$` is processed by shell.

Thanks for your explaination. I don't have much experience with shell, actually I had tried wrapping it with double quote before commiting the issue but had no success. Didn't think of single quote though.

**Comment by zonyitoo** [comment]
Yes, double quote will result the same.
