### ISSUE TITLE
ss-tunnel available in ss-rust

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-rust#374]
Hi
I need this feature to prevent dns pollution. Is this available in new sslocal ?

**Comment by zonyitoo** [comment]
```
sslocal --protocol tunnel
```

**Comment by debiansid** [comment]
in shadowsocks-libev I achieved this by
`/usr/bin/ss-tunnel -c /etc/shadowsocks-libev/%i.json -b 127.0.0.1 -l 40 -L 8.8.8.8:53 -u`
new sslocal only has --forward-addr <FORWARD_ADDR>

how can I run it for dns forwarding?

thanks

**Comment by zonyitoo** [comment]
It works exactly the same.

**Comment by debiansid** [comment]
> It works exactly the same.
> 
> ```
> /usr/bin/sslocal -c /etc/shadowsocks-libev/%i.json -b 127.0.0.1:53 --forward-addr 8.8.8.8:53 -u --protocol tunnel
> ```

thank you Sir!
