### ISSUE TITLE
simple-obfs in rust

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-rust#377]
Is there any plan for this?

**Comment by zonyitoo** [comment]
Nope. simple-obfs is already replaced by v2ray-plugin. I don't see a reason to rewrite it in Rust.

**Comment by DuckSoft** [comment]
Just a hint, it's officially deprecated by upstream. See https://github.com/shadowsocks/simple-obfs.

**Comment by debiansid** [comment]
I knew that, but v2ray plugin is too big

**Comment by DuckSoft** [comment]
That's a pity. I do not have the interest to rewrite it either.
Maybe you can wait for some generous pull request.

**Comment by zonyitoo** [comment]
Yup. Since it is already marked as deprecated, it is unwise to pay any efforts to rewrite it in Rust.
