### ISSUE TITLE
希望通过传递参数方式，指定多线程模式下tokio启动的线程数

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#379]
https://github.com/shadowsocks/shadowsocks-rust/blob/9000b31ffb9805324719ff5ba57c9338e357d1f0/bin/ssserver.rs#L282

如题，tokio在多线程模式下，默认开启与系统核心数匹配的线程数量。
大多数小伙伴买的机器都是单核心，当然也包括我在内。而我们用的手机，大多都已经6核、8核或更多。
这在现有的代码逻辑上，会发生服务器上的[单]线程要为连接终端的多线程服务。虽然我暂时未能证实这会带来什么影响，不过从道理上说，势必会产生响应的阻塞。
我为例，服务器虽是单核，但也[超频]一下，开5个处理线程，用得也挺好的。

**Comment by database64128** [comment]
I'm still convinced we should revert 7bf6d32. And 04791a5.

**Comment by zonyitoo** [comment]
Well, it won't, technically.

It is quite unnecessary to run servers with threads more than your cores, that will eventually results in more context switches (switches between threads). For tokio based program, all I/O are non-blocking I/O, so there is quite unnecessray to open more threads.

BTW, tokio will spawn more threads if some of them are blocked (just like Go's runtime, BTW). So I don't think you should intervene that.

> 我为例，服务器虽是单核，但也[超频]一下，开5个处理线程，用得也挺好的。

Well, in my daily working environment, opening more threads than CPU cores will significantly increase CPU usage and memory consumption, but gain no performance benefits.

> 这在现有的代码逻辑上，会发生服务器上的[单]线程要为连接终端的多线程服务。

Well, I will give you another examples, like nginx, 4 process could handle tons of thousands of connections; like redis, 1 process could handle millions of requests.

Reactor based server can easily handles C10K. For modern servers with modern CPUs, handling C100K is an easy job.

#### So why would we still want to use multi-threaded scheduler?

shadowsocks service is not only a I/O bound service, but also CPU consuming. Cryptography operations are CPU bound. So running services (for both `sslocal` and `ssserver`) could use all compute resources of the current machines (CPU cores). In this perspective, running server with threads that slightly bigger than the number of cores may have the best performance (which is the default).

BTW, if you insist adding two parameters for customizing threads count, well, that is quite easy for me.

**Comment by dev4u** [comment]
@zonyitoo 看得出你很用心地在回复，谢谢！

你举的例子很清楚，同时你的观点我也很认同。但sslocal、ssserver和nginx、redis的工作环境，还是存在差异。毕竟前者要更多的算力在加解密上。

我清楚加这个控制的参数，就是[一小块蛋糕]的事情。像我这个没怎么学rust，也能看着你的代码加上这个参数。虽然是简单的事，但是我还是希望专业的事，留给专业的人来做会比较好。还是由专业的人来决策要不要加吧。

**Comment by zonyitoo** [comment]
> 毕竟前者要更多的算力在加解密上。

Yes, you are correct, and CPU bound programs shouldn't set number of threads more than CPU cores' count.

I recently busy at work. I will add them sometime later. But still, personally, I won't recommend you to change these numbers.

**Comment by zonyitoo** [comment]
> I'm still convinced we should revert [7bf6d32](https://github.com/shadowsocks/shadowsocks-rust/commit/7bf6d320a743147d165c3ff1a8d5d1992db3e970). And [04791a5](https://github.com/shadowsocks/shadowsocks-rust/commit/04791a5d85301cc5694925232ed3e77a10f10841).

Well, these are not related to this issue. But, hmm, yeah.
