### ISSUE TITLE
是否支持日志里面记录访问的域名和url功能？

### ISSUE THREAD

**Issue by denwork** [shadowsocks/shadowsocks-rust#380]
1、不知道这个版本ssserver或sslocal能不能支持日志中输出访问的域名和url的功能？有域名和url日志就可以分析数据了。
2、另外如果有cache的能力就更完美了！毕竟在家里或者公司使用的时候，如果能缓存内存这样别人访问了一次我就能更快打开了。而且很多时候网络链路也不怎么稳定，或者按量付费每次去拉取资源会浪费很多带宽。
如果可以提供这两个特性，支持透明代理的方式。我愿意付费购买技术支持！

**Comment by zonyitoo** [comment]
1. `-v` will print domains. Fullurl will not be printed, only domain name is known in proxy.
2. What kind of cache? Could you elaborate it?

**Comment by denwork** [comment]
@zonyitoo  1. Can you add fullurl in to log message?Can you pick it in tcp packages for https protocol.
2.The cache like such as squid. Save static files,forward dynamic resource.

**Comment by dev4u** [comment]
> @zonyitoo  1. Can you add fullurl in to log message?Can you pick it in tcp packages for https protocol.
> 2.The cache like such as squid. Save static files,forward dynamic resource.

实现不了你这两个功能。以https请求为例，ss没办法在中间环节“看到”请求的内容。包括请求的路径、header……

**Comment by denwork** [comment]
@dev4u   谢谢！！
