### ISSUE TITLE
Some unsafe code may be wrong.

### ISSUE THREAD

**Issue by chongxu1980** [shadowsocks/shadowsocks-rust#384]
In "shadowsocks-rust/crates/shadowsocks-service/src/local/mod.rs" line 368 and 369:
```rust
    let buf: [u64; 2] = [tx as u64, rx as u64];
    let buf = unsafe { slice::from_raw_parts(buf.as_ptr() as *const _, 16) };
```
after the unsafe code the buf size is 128 bytes. I tested it by this:
```rust
use std::mem::size_of;
use std::mem::size_of_val;
use std::slice;

fn main() {
    let a = 1u64;
    let b = 2u64;
    let buf: [u64; 2] = [a, b];
    let buf = unsafe { slice::from_raw_parts(buf.as_ptr() as *const _, 16) };
    println!("{}", size_of_val(buf));
    println!("{}", size_of::<[u64; 2]>());
}

```
I think it should be like this:
```rust
    let buf: [u64; 2] = [tx as u64, rx as u64];
    let buf: &[u8] = unsafe { slice::from_raw_parts(buf.as_ptr() as *const _, 16) };
```
or:
```rust
    let buf: [u64; 2] = [tx as u64, rx as u64];
    let buf = unsafe { slice::from_raw_parts(buf.as_ptr() as *const u8, 16) };
```

**Comment by zonyitoo** [comment]
`stream.write_all(buf)` will ensure that `buf` has type `&[u8]`.

You should test it like this:

```rust
use std::mem::size_of;
use std::mem::size_of_val;
use std::slice;

fn write_all(buf: &[u8]) {}

fn main() {
    let a = 1u64;
    let b = 2u64;
    let buf: [u64; 2] = [a, b];
    let buf = unsafe { slice::from_raw_parts(buf.as_ptr() as *const _, 16) };
    write_all(buf);
    println!("{}", size_of_val(buf));
    println!("{}", size_of::<[u64; 2]>());
}
```

**Comment by chongxu1980** [comment]
> `stream.write_all(buf)` will ensure that `buf` has type `&[u8]`.
> 
> https://github.com/shadowsocks/shadowsocks-rust/blob/6c7c5fec1ae512cd95bccec2475024490d78a822/crates/shadowsocks-service/src/local/mod.rs#L371
> 
> You should test it like this:
> 
> ```rust
> use std::mem::size_of;
> use std::mem::size_of_val;
> use std::slice;
> 
> fn write_all(buf: &[u8]) {}
> 
> fn main() {
>     let a = 1u64;
>     let b = 2u64;
>     let buf: [u64; 2] = [a, b];
>     let buf = unsafe { slice::from_raw_parts(buf.as_ptr() as *const _, 16) };
>     write_all(buf);
>     println!("{}", size_of_val(buf));
>     println!("{}", size_of::<[u64; 2]>());
> }
> ```

Yes, I'm wrong. Thank you for your reply.
