### ISSUE TITLE
Easiest Solution for Running on GCP/AWS?

### ISSUE THREAD

**Issue by lhy-loveworld** [shadowsocks/shadowsocks-rust#391]
Hi,

I'm trying to find the easiest solution to deploy a ssserver on a cloud instance. I used to directly use `shadowsocks-python` but it looks like the encryption methods it supports are all gone in the Windows shadowsocks client. So I'm trying to use `shadowsocks-rust` instead, the problem I'm running into is that it seems the cheapest GCP/AWS instance is not able to build the code. So I have the following questions:
1. Is shadowsocks the easiest solution to start a VPN/proxy server on cloud?
2. For using `shadowsocks-rust`, it seems I can directly download the release [here](https://github.com/shadowsocks/shadowsocks-rust#download-release). Does it mean I don't need to build? What's the next step after downloading the release?

大家好，
我想在GCP/AWS上快速deploy一个VPN，之前一直用的 `shadowsocks-python`似乎停止support了很多加密算法。我现在在尝试使用`shadowsocks-rust`，但是最便宜的cloud instance由于性能太差不能成功build。所以我有了以下两个疑问：
1. shadowsocks是最简单的在cloud instance上面搭梯子的方法吗？
2. 直接下载`shadowsocks-rust`的release是不是就不用build了，我不熟悉rust，请问下载以后接下来的步骤是什么？

Thanks!

**Comment by zonyitoo** [comment]
1. Maybe.
2. Yes, it should work on modern servers.

**Comment by lhy-loveworld** [comment]
Thanks. I somehow downloaded the source code. And it worked now.
