### ISSUE TITLE
[Feature proposal] Server disable in Extended multiple server configuration

### ISSUE THREAD

**Issue by spyophobia** [shadowsocks/shadowsocks-rust#394]
## Rationale
`shadowsocks-rust` supports creating and/or connecting to multiple servers within one configuration file, which is great.

However, sometimes there arises the need, whether during testing or deployment, for us to temporarily disable one or more servers. Example scenarios include:
- Several conflicting server profiles during testing
- Isolating the issue during network diagnosis
- Server temporarily unavailable

Ideally, the user should be able to simply block-comment out a profile to disable it. Unfortunately, JSON format does not have support for comments, which means the user would need to:
1. either joggle several configuration files
2. or copying & pasting the profile around in the JSON file

... Neither of which is convenient.

## What I am envisioning
Wouldn't it be nice, if you can simply add `"disable": true` to a server profile and turn it off?

Something like this:
```json
{
    "servers": [
        {
            "address": "127.0.0.1",
            "port": 1080,
            "password": "hello-world",
            "method": "aes-256-gcm",
            "timeout": 300
        },
        {
            "disable": true,
            "address": "127.0.0.1",
            "port": 1081,
            "password": "hello-kitty",
            "method": "chacha20-ietf-poly1305"
        }
    ],
    "local_port": 8388,
    "local_address": "127.0.0.1"
}
```

I think it would be a good "quality of life" improvement while being not too complicated to implement.

**Comment by spyophobia** [comment]
Also, I personally know some Rust so I'm happy to contribute via a PR.

**Comment by spyophobia** [comment]
Also, I personally know some Rust so I'm happy to contribute via a PR.

**Comment by database64128** [comment]
+1. The feature would be helpful for me as well.

**Comment by zgzh** [comment]
If possible, set the specified server as the default, and use other servers when it fails. This scenario is that the network speed is fast, but the speed is low, so it can’t be optimized. You can only delete the server.

**Comment by spyophobia** [comment]
> If possible, set the specified server as the default, and use other servers when it fails. This scenario is that the network speed is fast, but the speed is low, so it can’t be optimized. You can only delete the server.

Don't worry I got you covered. I actually intend to submit another feature proposal about customisation options for the load balancer, which will be a superset of the feature you are describing.

**Comment by spyophobia** [comment]
@zgzh See https://github.com/shadowsocks/shadowsocks-rust/issues/395

**Comment by zonyitoo** [comment]
> Ideally, the user should be able to simply block-comment out a profile to disable it. Unfortunately, JSON format does not have support for comments,

I am using json5 in this project. :P . So yeah, you can use comments.

BTW, I personally agree with the optional `disable` field. Feel free to open a PR for this. Should it be included in SIP008? @database64128

**Comment by zonyitoo** [comment]
Technically, yeah. But that is not a standard basic format of shadowsocks, so I am not guranteed that it will not be changed in the future.

**Comment by zonyitoo** [comment]
Merged.

**Comment by dev4u** [comment]
可以设置1、0来代表true、false吗？

**Comment by zonyitoo** [comment]
Why.

**Comment by dev4u** [comment]
> Why.

因为有些三方库，如果设置一个属性为true，他会用1来表示，反之亦然。
