### ISSUE TITLE
The crate domain does not support local hosts file

### ISSUE THREAD

**Issue by Matrix-Zhang** [shadowsocks/shadowsocks-rust#40]
may be change to crate tokio-dns-unofficial?

**Comment by zonyitoo** [comment]
`ssserver` or `sslocal`?

**Comment by Matrix-Zhang** [comment]
both of them

**Comment by zonyitoo** [comment]
Why would you need that?

1. If your servers' domain cannot be resolved in `sslocal`, write IP addresses in configuration files.
2. If your servers' domain cannot be resolved in `ssserver` side... is that possible?

**Comment by Matrix-Zhang** [comment]
the server is my vps host which i write local hostname in /etc/hosts

**Comment by zonyitoo** [comment]
Ref to https://github.com/partim/domain/issues/12 .

**Comment by Matrix-Zhang** [comment]
https://github.com/partim/nsswitch

**Comment by zonyitoo** [comment]
This crate is still in a very early stage.

**Comment by zonyitoo** [comment]
It should supports now. But it still requires more works on Windows.

**Comment by zonyitoo** [comment]
Already deprecated `domain` crate and replaced it with standard name resolving provided by libc.
