### ISSUE TITLE
Where is ssserver log file?

### ISSUE THREAD

**Issue by hunbssfy** [shadowsocks/shadowsocks-rust#403]
I put ssserver binary in a dir and started it with `./ssserver -d -c config.json`, then where should the log file be generated?
I can't find it in `/var/log/`

**Comment by dev4u** [comment]
指定你的log4rs.yaml，然后在里面配置。

**Comment by zonyitoo** [comment]
Logs are written to `stdout` by default. If you want to write to a file, use `--log-config`. Here is an example:

https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/log4rs.yaml
