### ISSUE TITLE
Debian 10服务端报错：Illegal instruction

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-rust#404]
内核：`4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`
服务端版本：`v1.9.0-alpha.1~v1.9.0-alpha.5`，gnu与musl均报错

**Comment by zonyitoo** [comment]
Your must be running on a very old CPU. Consider compile it by your self, especially:

1. Delete those features that your CPU doesn't support in [`config.toml`](https://github.com/shadowsocks/shadowsocks-rust/blob/master/.cargo/config.toml), or you can just delete it completely.
2. Compile it on your server directly with environemnt variable `RUSTFLAGS=-Ctarget-cpu=native` set.
