### ISSUE TITLE
using crate spin without feature "std" causes performance problem

### ISSUE THREAD

**Issue by asypost** [shadowsocks/shadowsocks-rust#408]
According to the describtion of [spin](https://crates.io/crates/spin),using spin without "std" feature enabled the synchronization is done through spinning,which may cause high cpu usage.

**Comment by zonyitoo** [comment]
Interesting throught. Busy spinning in multi-core system will actually have benefits, for example, caching. So if critical section is small, busy spinning may be a good option.

https://github.com/mvdnes/spin-rs/blob/3f5b82ad7ae296610b4d7d54be1b15fe6d37fa6d/src/lib.rs#L58-L62

I don't know if `std::thread::yield_now` have any optimization about this, or it is just a call to `pthread_yield`?

**Comment by zonyitoo** [comment]
It seems that it is just a `pthread_yield`.

**Comment by zonyitoo** [comment]
It won't have any observable difference in shadowsocks' use case. :P For TCP connections, checking IV is only happened for new connections. For UDP associations, IV will be checked for every packets, that should become a hot spot, but most users only uses TCP. :)

BTW, do you want to make a PR for this? Or I just add it directly.

How about the feature `ticket_lock`, which is also a useful feature, I think.

**Comment by asypost** [comment]
Ticket lock doesn't yield to the system's scheduler either.I think using std feature is a better choice in an userspace application with OS environment.BTW it's OK if you add this directly.

**Comment by asypost** [comment]
Maybe use std along with ticket lock is OK, I don't look the detail of the implement for now,sorry.
