### ISSUE TITLE
failed to initialize DNS resolver with system-config

### ISSUE THREAD

**Issue by tjc0726** [shadowsocks/shadowsocks-rust#411]
2021-02-09T12:04:32.424775065+08:00 ERROR failed to initialize DNS resolver with system-config, error: Error parsing resolv.conf: InvalidOption(17)
2021-02-09T12:04:32.425038602+08:00 INFO  shadowsocks TCP listening on 0.0.0.0:53236

ConfigFile:
{
  "server":"0.0.0.0",
  "server_port":53236,
  "password":"hello-ss",
  "timeout":300,
  "method":"xchacha20-ietf-poly1305",
  "fast_open": false
}

resolv.conf:
![image](https://user-images.githubusercontent.com/49085201/107314429-8c53aa80-6acf-11eb-8176-e4f52f5b8ae7.png)

**Comment by dev4u** [comment]
这很明显是你的resolv.conf文件配置出问题。出门左转google解决一下。

**Comment by zonyitoo** [comment]
Your vim already shows your errors.

**Comment by tjc0726** [comment]
> Your vim already shows your errors.

It can be solved by clear all content and just set nameserver to 8.8.8.8,but the previous setting also works fine except on ss-rust

Although vi shows the error,Google told me its correct to configure it in this way(I'll be thankful if you tell me what error is),BTW its tricky to change the file since it will be recovered after reboot

**Comment by zonyitoo** [comment]
`/etc/resolv.conf` is parsed by this crate: https://github.com/tailhook/resolv-conf .

For `options` key, it only supports the following values: https://github.com/tailhook/resolv-conf/blob/e6f4ff12ea9f163ff9580489ed0f527b2a73e484/src/grammar.rs#L172-L207

**Comment by zonyitoo** [comment]
I tried your configuration locally in macOS, everything works fine.

**Comment by tjc0726** [comment]
> I tried your configuration locally in macOS, everything works fine.

Is there anything I can do to help you locate this bug?

**Comment by dev4u** [comment]
```
options edns0
options trust-ad
```

**Comment by tjc0726** [comment]
> ```
> options edns0
> options trust-ad
> ```

doesnt work,but instead of InvalidOption(17),its now InvalidOption(18) in the error message,It seems related to the trust-ad part

**Comment by zonyitoo** [comment]
`InvalidOption(17)` means the line number is 17.

Which version were you using? Could you test with the master branch?

**Comment by tjc0726** [comment]
> `InvalidOption(17)` means the line number is 17.
> 
> Which version were you using? Could you test with the master branch?

Sry,My bad,I'm still using 1.8.23,and I found out it seems to be fixed in the v1.9.0-alpha.5.
BTW,when I switch to v1.9.0-alpha.5, it shows that `xchacha20-ietf-poly1305` is not a supported method'
`chacha20-ietf-poly1305` was fine,Is this a feature or something?

**Comment by zonyitoo** [comment]
Yes, `xchacha20-ietf-poly1305` is not a standard method, just use `chacha20-ietf-poly1305`.
