### ISSUE TITLE
ERROR failed to send packet into response channel, error: channel closed

### ISSUE THREAD

**Issue by xsy2004** [shadowsocks/shadowsocks-rust#414]
###  Question：
shadowsocos-rust大量报错，并且无法通过UDP转发测试。
shadowsocos-rust reports a lot of errors and cannot pass the UDP forwarding test。
### Log：
```
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
Feb 14 15:09:15 ecs-gVG5z ssserver[24279]: ERROR failed to send packet into response channel, error: channel closed
```
### config.json

```
{
    "server": "0.0.0.0",
    "server_port": myport,
    "password": "mypassword",
    "timeout": 300,
    "method": "aes-128-gcm",
    "mode": "tcp_and_udp",
    "no_delay": true,
    "ipv6_first": false,
    "dns": "mydns"
}
```

### Solution
restart the server can solve the udp forwarding.

And why is there such an error result reported, and how can it be rooted out?

**Comment by xsy2004** [comment]
and this error
`Feb 15 07:25:32 debian-s-1vcpu-1gb-sgp1-01 ssserver[6139]: ERROR AEAD decrypt failed, input=b"\xc3\x0f", tag=b"\xa7\xdf\xb2\xc9\xb1-\xdf\x07\xef\xe1pd\x83\xe7\x8f\x84", opening: OpeningKey { algorithm: AES_128_GCM }`

**Comment by zonyitoo** [comment]
Which version are you using? Could you try with the latest master's version?

> ERROR AEAD decrypt failed, input=b"\xc3\x0f", tag=b"\xa7\xdf\xb2\xc9\xb1-\xdf\x07\xef\xe1pd\x83\xe7\x8f\x84", opening: OpeningKey { algorithm: AES_128_GCM }

Failed to decrypt your packet, you should verify your password.

I suspected you are using 1.8.23. Try with the latest code, which will help a lot for me to address the key issue.

**Comment by xsy2004** [comment]
> Which version are you using? Could you try with the latest master's version?
> 
> 
> 
> > ERROR AEAD decrypt failed, input=b"\xc3\x0f", tag=b"\xa7\xdf\xb2\xc9\xb1-\xdf\x07\xef\xe1pd\x83\xe7\x8f\x84", opening: OpeningKey { algorithm: AES_128_GCM }
> 
> 
> 
> Failed to decrypt your packet, you should verify your password.
> 
> 
> 
> I suspected you are using 1.8.23. Try with the latest code, which will help a lot for me to address the key issue.

yes, my version is 1.8.23, maybe my friend password is wrong, thank you!!!

**Comment by zonyitoo** [comment]
Consider using the latest v1.9.0.
