### ISSUE TITLE
[FR] Read password from an environment variable

### ISSUE THREAD

**Issue by NightMachinary** [shadowsocks/shadowsocks-rust#419]
I want to read all the config from my config file, but read just the password from an environment variable. This way I can put the config file in my public dotfile git repo and share it between my servers.

```
SHADOWSOCKS_PASSWORD='...' ss-server -c config.json
```

`config.json`:
```
{
"server":["::0","0.0.0.0"],
"server_port":8512,
"local_port":1080,
"timeout":300,
"nameserver": "8.8.8.8",
"mode": "tcp_only",
"fast_open":false,
"method":"chacha20-ietf-poly1305"
}
```

**Comment by zonyitoo** [comment]
This is a very customized feature. I would personally recommend you to add it yourself.

Or maybe, maybe it can be supported by a special variable syntax:

```json
{
    "password": "$SHADOWSOCKS_PASSWORD"
}
```
