### ISSUE TITLE
ssmanager dose not support args like “--plugin --plugin-opts”

### ISSUE THREAD

**Issue by shminer** [shadowsocks/shadowsocks-rust#421]
Now we use plugins a lot to avoid detection.

Please add ssmanager plugin args support like ss-manager.

So that we can use plugins when using shadowsocks-manager.

**Comment by dev4u** [comment]
为啥manager需要支持加载插件呢，能说说是怎么样的使用场景吗？

**Comment by shminer** [comment]
> 为啥manager需要支持加载插件呢，能说说是怎么样的使用场景吗？

因为目前shadowsocks-manager使用api管理时是不可以附带参数的，在web管理ss的时候是无法添加带插件的端口的。

目前应用场景是这样shadowsocks-manager用来管理服务，使用rust或者libve作为服务。在web界面添加端口时，可以添加带插件的服务。

目前我看到libve版本可以使用ss-manager添加插件。一旦ss-manager添加了--plugin参数，他启动的ss-server可以自动带上--plugin参数。

**Comment by shminer** [comment]
具体类似这样 https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L211

**Comment by dev4u** [comment]
明白，谢谢指教。

**Comment by zonyitoo** [comment]
Hmm, have you tried to send `plugin` and `plugin_opts` in the `add` command? It is always supports in this project.

**Comment by zonyitoo** [comment]
Oh, maybe what you want is to pass `--plugin` and `--plugin-opts` directly from command line arguments to `ssmanager` and applies to all servers?

Is that really a good design?

**Comment by shminer** [comment]
> Oh, maybe what you want is to pass `--plugin` and `--plugin-opts` directly from command line arguments to `ssmanager` which applies to all servers?
> 
> Is that really a good design?

Yes, that is not a good design, shadowsocks-manager not support this function yet, use api is not convenient.
Maybe I should request a issue to shadowsocks-manager repo.

**Comment by zonyitoo** [comment]
Good point, and I recommended shadowsocks-manager's maintainer can standardize the manager protocol. @gyteng

**Comment by gyteng** [comment]
try 0.38.x
https://github.com/shadowsocks/shadowsocks-manager/pull/668

**Comment by zonyitoo** [comment]
@gyteng I don't think `ssmanager` supports `--plugin` and `--plugin-opts` from command line options. You should send plugin options from `add` command like `add: {"plugin":"xx", "plugin_opts": "xxx"}`

**Comment by gyteng** [comment]
I will fix it later

**Comment by ylfzq** [comment]
> @gyteng I don't think `ssmanager` supports `--plugin` and `--plugin-opts` from command line options. You should send plugin options from `add` command like `add: {"plugin":"xx", "plugin_opts": "xxx"}`

This solution is perfect, but it is not supported by other implementations yet. How can we sync this solution to other implementations and come to an agreement.

**Comment by ylfzq** [comment]
> Oh, maybe what you want is to pass `--plugin` and `--plugin-opts` directly from command line arguments to `ssmanager` which applies to all servers?
> 
> Is that really a good design?

It's not a good design, but it seems not so bad if you consider them as default parameters.

**Comment by zonyitoo** [comment]
The only other implementation is shadowsocks-libev.

I am Ok to add it as a default parameter, but since every server instances are independent, and the plugin configurations are bounded to a specific one instance, why would you need a default parameter?

If plugin has a default parameter, why won't the others parameters has defaults?

**Comment by ylfzq** [comment]
> The only other implementation is shadowsocks-libev.
> 
> I am Ok to add it as a default parameter, but since every server instances are independent, and the plugin configurations are bounded to a specific one instance, why would you need a default parameter?
> 
> If plugin has a default parameter, why won't the others parameters has defaults?

Yes, it does have a default value for all parameters. You can see the document [here](https://github.com/shadowsocks/shadowsocks-libev#usage) and the code [here](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L891).
