### ISSUE TITLE
1.9.0 无法在Greencloud正常运行

### ISSUE THREAD

**Issue by windstander** [shadowsocks/shadowsocks-rust#426]
我使用这个脚本安装并升级：
https://github.com/loyess/Shell

上一个版本一切正常，升级到1.9.0后，运行启动文件：

```bash
#!/usr/bin/env bash
# chkconfig: 2345 90 10
# description: A secure socks5 proxy, designed to protect your Internet traffic.

### BEGIN INIT INFO
# Provides:          Shadowsocks-rust
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fast tunnel proxy that helps you bypass firewalls
# Description:       Start or stop the Shadowsocks-rust server
### END INIT INFO


if [ -f /usr/local/bin/ssserver ]; then
    DAEMON=/usr/local/bin/ssserver
elif [ -f /usr/bin/ssserver ]; then
    DAEMON=/usr/bin/ssserver
fi
NAME=Shadowsocks-rust
CONF=/etc/shadowsocks/config.json
LOG=/var/log/shadowsocks-rust.log
PID_DIR=/var/run
PID_FILE=$PID_DIR/shadowsocks-rust.pid
RET_VAL=0

[ -x $DAEMON ] || exit 0

if [ ! -d "$(dirname ${LOG})" ]; then
    mkdir -p $(dirname ${LOG})
fi

check_pid(){
	get_pid=`ps -ef |grep -v grep | grep ssserver |awk '{print $2}'`
}

check_pid
if [ -z $get_pid ]; then
    if [ -e $PID_FILE ]; then
        rm -f $PID_FILE
    fi
fi

if [ ! -d $PID_DIR ]; then
    mkdir -p $PID_DIR
    if [ $? -ne 0 ]; then
        echo "Creating PID directory $PID_DIR failed"
        exit 1
    fi
fi

if [ ! -f $CONF ]; then
    echo "$NAME config file $CONF not found"
     exit 1
fi

check_running() {
    if [ -e $PID_FILE ]; then
        if [ -r $PID_FILE ]; then
            read PID < $PID_FILE
            if [ -d "/proc/$PID" ]; then
                return 0
            else
                rm -f $PID_FILE
                return 1
            fi
        fi
    else
        return 2
    fi
}

do_status() {
    check_running
    case $? in
        0)
        echo "$NAME (pid $PID) is running."
        ;;
        1|2)
        echo "$NAME is stopped"
        RET_VAL=1
        ;;
    esac
}

do_start() {
    if check_running; then
        echo "$NAME (pid $PID) is already running."
        return 0
    fi
    ulimit -n 51200
    nohup $DAEMON -c $CONF -v > $LOG 2>&1 &
    check_pid
    echo $get_pid > $PID_FILE
    if check_running; then
        echo "Starting $NAME success"
    else
        echo "Starting $NAME failed"
        RET_VAL=1
    fi
}

do_stop() {
    if check_running; then
        kill -9 $PID
        rm -f $PID_FILE
        echo "Stopping $NAME success"
    else
        echo "$NAME is stopped"
        RET_VAL=1
    fi
}

do_restart() {
    do_stop
    sleep 0.5
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RET_VAL=1
    ;;
esac

exit $RET_VAL
```

会提示错误：

/etc/init.d/shadowsocks-rust: line 130: 1374 Illegal instruction nohup $DAEMON -c $CONF -v > $LOG 2>&1

但是这个语句本身没有问题，运行上一个版本一切正常。系统是Debian并升级到最新版本。

**Comment by dev4u** [comment]
这不是应该找提供脚本的兄弟来处理比较对口？

**Comment by zonyitoo** [comment]
> 1374 Illegal instruction

Well, your machine is running on a very old CPU, which doesn't support some of the SIMD instruction sets.

Solution:

1. Compile a `ssserver` by yourself.
2. Get a new server.

**Comment by windstander** [comment]
> 
> 
> 这不是应该找提供脚本的兄弟来处理比较对口？

跟脚本无关，用旧版没有问题。

**Comment by windstander** [comment]
> 
> 
> > 1374 Illegal instruction
> 
> Well, your machine is running on a very old CPU, which doesn't support some of the SIMD instruction sets.
> 
> Solution:
> 
>     1. Compile a `ssserver` by yourself without the `.cargo/config.toml`, or compile it with environment variable `RUSTFLAGS="-C target-cpu=native"` for optimizations for your local CPU.
> 
>     2. Get a new server.

How to compile it?
I can not do it.

**Comment by zonyitoo** [comment]
1. Install Docker
2. Remove this file: `.cargo/config.toml`
3. Run:
  ```bash
  cd build
  ./build-release -t "x86_64-unknown-linux-gnu"
  ```
  Replace the `-t` target with your platform's specific value.

**Comment by windstander** [comment]
> 
> 
>     1. Install Docker
> 
>     2. Remove this file: `.cargo/config.toml`, or just remove the instruction sets that your CPU doesn't support, maybe `sse4.*`, `avx`, ...
> 
>     3. Install Rust's toolchain: https://rustup.rs/
> 
>     4. Install Cross: `cargo install cross`
> 
>     5. Run:
>        ```shell
>        cd build
>        ./build-release -t "x86_64-unknown-linux-gnu"
>        ```
>        
>        
>        Replace the `-t` target with your platform's specific value.
> 
>     6. You will see release packages in `build/release`

Thanks. I am learning.
Now I have installed all the binaries.
Should I download all the source cold and then unpack the zip to the root folder of my server and run build command?

**Comment by windstander** [comment]
> 
> 
>     1. Install Docker
> 
>     2. Remove this file: `.cargo/config.toml`, or just remove the instruction sets that your CPU doesn't support, maybe `sse4.*`, `avx`, ...
> 
>     3. Install Rust's toolchain: https://rustup.rs/
> 
>     4. Install Cross: `cargo install cross`
> 
>     5. Run:
>        ```shell
>        cd build
>        ./build-release -t "x86_64-unknown-linux-gnu"
>        ```
>        
>        
>        Replace the `-t` target with your platform's specific value.
> 
>     6. You will see release packages in `build/release`

I made it!

**Comment by freakinyy** [comment]
> > 1374 Illegal instruction
> 
> Well, your machine is running on a very old CPU, which doesn't support some of the SIMD instruction sets.
> 
> Solution:
> 
> 1. Compile a `ssserver` by yourself without the `.cargo/config.toml`, or compile it with environment variable `RUSTFLAGS="-C target-cpu=native"` for optimizations for your local CPU.
> 2. Get a new server.

Same issue when use "x86_64-unknown-linux-musl" on openwrt resolved by remove avx in ".cargo/config.toml". Thank you for your build guide.
But I don't think it is only a "very old CPU" problem. Some not very old but low-end CPUs like almost all Celeron and Pentium (up to G6600, if i'm not mistaken) has no avx instructions. These CPUs are unlikely used on servers, but probably used on some routers.  So I hope there are additional x86_64 release versions without avx.

**Comment by zonyitoo** [comment]
Sounds reasonable.

@LuoZijun How would performance be affected if AVX is not enabled by default?

**Comment by LuoZijun** [comment]
@zonyitoo `AVX` 的加速指令预计将来会用在 `Chacha20` 算法上面，目前并没有使用。

**Comment by database64128** [comment]
- CPU: i5-7400
- OS: Arch Linux 5.11.1-arch1-1
- Protocol: Shadowsocks AEAD ChaCha20Poly1305
- Setup: loopback proxychains-ng single connection
    - shadowsocks/shadowsocks-rust@7f86e36
    - shadowsocks/go-shadowsocks2@75d4327 CGO_ENABLED=1 go1.16
    - v2fly/v2ray-core 4.34.0-1 from https://archlinux.org/packages/community/x86_64/v2ray/
    - XTLS/Xray-core@48fab4d CGO_ENABLED=1 go1.16

| | ss-rust native cpu client | ss-rust no avx no avx2 client | go-ss2 client | v2ray client | Xray client |
| --- | ---: | ---: | ---: | ---: | ---: |
| ss-rust native cpu server | 6.43Gbps | | 6.36Gbps | 2.72Gbps | 5.16Gbps |
| ss-rust no avx no avx2 server | | 6.37Gbps | 6.45Gbps | | |
| go-ss2 server | 6.17Gbps | | 6.19Gbps | 2.30Gbps | 4.78Gbps |
| v2ray server | 6.00Gbps | | 5.88Gbps | 4.72Gbps | 5.50Gbps |
| Xray server | 6.39Gbps | | 6.60Gbps | 2.32Gbps | 6.27Gbps |

- Conclusions
    - `avx`, `avx2`, and `-Ctarget-cpu=native` has negligible impact on the performance of single-connection C20P1305.
    - shadowsocks-rust is the fastest implementation of both server and client.

**Comment by IceCodeNew** [comment]
> * CPU: i5-7400
> * OS: Arch Linux 5.11.1-arch1-1
> * Protocol: Shadowsocks AEAD ChaCha20Poly1305 & AES-256-GCM
> * Setup: loopback proxychains-ng single connection
>   
>   * [7f86e36](https://github.com/shadowsocks/shadowsocks-rust/commit/7f86e36)
>   * [shadowsocks/go-shadowsocks2@75d4327](https://github.com/shadowsocks/go-shadowsocks2/commit/75d4327) CGO_ENABLED=1 go1.16
>   * v2fly/v2ray-core 4.34.0-1 from [archlinux.org/packages/community/x86_64/v2ray](https://archlinux.org/packages/community/x86_64/v2ray/)
>   * [XTLS/Xray-core@48fab4d](https://github.com/XTLS/Xray-core/commit/48fab4d) CGO_ENABLED=1 go1.16
> 
> chacha20-poly1305	ss-rust native cpu client	ss-rust no avx no avx2 client	go-ss2 client	v2ray client	Xray client
> ss-rust native cpu server	6.43Gbps		6.36Gbps	2.72Gbps	5.16Gbps
> ss-rust no avx no avx2 server		6.37Gbps	6.45Gbps		
> go-ss2 server	6.17Gbps		6.19Gbps	2.30Gbps	4.78Gbps
> v2ray server	6.00Gbps		5.88Gbps	4.72Gbps	5.50Gbps
> Xray server	6.39Gbps		6.60Gbps	2.32Gbps	6.27Gbps
> aes-256-gcm	ss-rust native cpu client	ss-rust no avx no avx2 client	go-ss2 client	v2ray client	Xray client
> ss-rust native cpu server	8.02Gbps		8.07Gbps	3.10Gbps	6.23Gbps
> ss-rust no avx no avx2 server		8.04Gbps			
> go-ss2 server	8.35Gbps		8.04Gbps	2.65Gbps	5.95Gbps
> v2ray server	7.38Gbps		7.37Gbps	5.85Gbps	6.76Gbps
> Xray server	8.52Gbps		8.56Gbps	6.24Gbps	8.34Gbps
> * Conclusions
>   
>   * `avx`, `avx2`, and `-Ctarget-cpu=native` have negligible impact on the performance of single-connection C20P1305 and AES-256-GCM.
>   * shadowsocks-rust and go-shadowsocks2 are the fastest client implementations.

Thanks for the benchmark.
