### ISSUE TITLE
I need ss-redir

### ISSUE THREAD

**Issue by juhuaguai** [shadowsocks/shadowsocks-rust#437]
I download the release package,but without ss-redir.
I rebuild source,but ss-redir wasn't created.
What I can do for it?
Thanks!

**Comment by dev4u** [comment]
rust版没有ss-redir的。

**Comment by juhuaguai** [comment]
This is frustrating. I need it on the router.

**Comment by zonyitoo** [comment]
`sslocal --protocol redir`
