### ISSUE TITLE
配置文件方式运行时 无法同时监听IPv4和IPv6

### ISSUE THREAD

**Issue by jxcn** [shadowsocks/shadowsocks-rust#438]
```
$ ssserver -c rust.json -v
thread 'main' panicked at 'loading config "rust.json", json parse error, Message { msg: "invalid type: sequence, expected a string", location: Some(Location { line: 2, column: 13 }) }', bin/ssserver.rs:140:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ cat rust.json
{
  "server": ["::0","0.0.0.0"],
  "server_port": 2333,
  "password": "passwd",
  "method": "aes-256-gcm",
  "mode": "tcp_and_udp"
}
```

以及 ss-libev 这里有详细的文档 https://github.com/shadowsocks/shadowsocks-libev/tree/master/doc
ss-rust 既然不能完全沿用 ss-libev 的配置，是不是该完善一下文档呢？

**Comment by database64128** [comment]
Just go with `"server": "::"`.

**Comment by jxcn** [comment]
> Just go with `"server": "::"`.

```
$ ssserver -c rust.json -v
2021-03-04T18:06:21.591100930+08:00 INFO  [51768:140117096127360] [ssserver] shadowsocks 1.9.1
2021-03-04T18:06:21.594597657+08:00 DEBUG [51768:140117096127360] [shadowsocks::net::tcp] 0.0.0.0:2333 may have already been occupied, retry with IPV6_V6ONLY
thread 'main' panicked at 'aborted with server exited unexpectly', bin/ssserver.rs:306:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ cat rust.json 
{
  "server": "::",
  "server_port": 2333,
  "password": "passwd",
  "method": "aes-256-gcm",
  "mode": "tcp_and_udp"
}
```

**Comment by database64128** [comment]
You have other applications that listen on `0.0.0.0:2333/tcp`. Check with `ss -tln`.

**Comment by jxcn** [comment]
> You have other applications that listen on `0.0.0.0:2333/tcp`. Check with `ss -tln`.

My mistake.

所以文档是不是该完善一下呢？

**Comment by zonyitoo** [comment]
What do you mean?

**Comment by DuckSoft** [comment]
请您运行 `ss -tln` 看看。

**Comment by jxcn** [comment]
> Just run `ss -tlnp` and you will see why.

然而从外面连 IPv4 过来就会报 `Connection refused`
```
State          Recv-Q         Send-Q                  Local Address:Port                    Peer Address:Port         Process                                   
LISTEN         0              1024                                *:2333                               *:*
```

**Comment by jxcn** [comment]
> ```
> *:2333
> ```
> 
> It is listening on both ipv4 and ipv6.

所以为什么 `"server": "::"` 客户端 IPv4 连会报 `Connection refused`
`"server": "0.0.0.0"` 就可以通过 IPv4 正常连接呢？

**Comment by zonyitoo** [comment]
If so, it may indicate that your system haven't enabled dual-stack ipv6 by default?

**Comment by zonyitoo** [comment]
If you are still interested in finding the root cause of this issue, you could try to run `strace` on `obfs-server` with the following environment variables set:

- `SS_REMOTE_HOST="::"`
- `SS_REMOTE_PORT=2333`
- `SS_LOCAL_HOST="::"`
- `SS_LOCAL_PORT=64332`
- `SS_PLUGIN_OPTIONS="fast-open;obfs=http"`

and see what exactly address it was trying to listen, and whether it sets `IPV6_V6ONLY` to `1`.

**Comment by jxcn** [comment]
> ```shell
> export SS_REMOTE_HOST="::"
> export SS_REMOTE_PORT=2333
> export SS_LOCAL_HOST="::"
> export SS_LOCAL_PORT=64332
> export SS_PLUGIN_OPTIONS="fast-open;obfs=http"
> strace obfs-server
> ```
> 
> You may see something like these
> 
> ```
> ...
> socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP) = 5
> setsockopt(5, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
> setsockopt(5, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
> setsockopt(5, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
> ...
> bind(5, {sa_family=AF_INET6, sin6_port=htons(2333), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::", &sin6_addr), sin6_scope_id=0}, 28) = 0
> listen(5, 1024)                         = 0
> setsockopt(5, SOL_TCP, TCP_FASTOPEN, [5], 4) = 0
> ...
> ```
> 
> It is obvious that `obfs-server` set `IPV6_V6ONLY` when `SS_REMOTE_HOST` was `::`, that's why you cannot connect it with IPV4 clients.
> 
> I don't know why it behaved like that. Was it working as expected? cc @madeye

打印出来非常多内容 需要哪些？

**Comment by zonyitoo** [comment]
I have already done the test.

**Comment by GF-Huang** [comment]
How can I enable dual mode (IPv4 and IPv6) on `loopback`, rather than `any` (`::`) ?

I had try this: `"server": ["127.0.0.1", "::1"]`, not work.
```
> ssserver.exe -c config.json
loading config "config.json", json parse error, Error { inner: ErrorInner { content: Code(ExpectedString), position: Some(Position { line: 3, column: 22 }) } }
```

I had try this: `"server": "::1"`, but only works for IPv6, reject the IPv4 connections.

**Comment by zonyitoo** [comment]
Start 2 server instances with the extended configuration format:

```json
{
    "servers": [
        { "address": "127.0.0.1", ... },
        { "address": "::1", ... },
    ]
}
```

**Comment by GF-Huang** [comment]
This is extremely inconvenient.
