### ISSUE TITLE
shadowsocks-rust的优势是什么

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-rust#448]
在同一台VPS部署了shadowsocks-rust,和shadowsocks-libev。发现shadowsocks-rust在速度、时延上并没有比shadowsocks-libev有提升，应该比libev还稍微差一些。那么开发rust主要原因是为何？针对哪些特殊场景吗？如需要支持多用户？

**Comment by zonyitoo** [comment]
Our tests shows rust have significant speed advantage than libev. How did you test?

**Comment by tianlichunhong** [comment]
My test is non-professional. It is in a network environment with a packet loss rate of 30%, and 250ms delay from the United States to China. A simple test failed to find that rust has a better experience. Such as network speed and delay. And when using aes-128-gcm without v2ray-plugin, it was quickly detected by GFW after several speedtest.net, and the port was block by GFW. I have used libev for several years and this situation has never happened before.

**Comment by zonyitoo** [comment]
I feel sorry about it.

If you want to make a performance test, just run both `sslocal` and `ssserver` on your own computer.

**Comment by om2mo** [comment]
支持ACL

**Comment by zonyitoo** [comment]
Since this is not a resolvable issue, I am going to close this.
