### ISSUE TITLE
shadowsocks server转发到server本机nginx

### ISSUE THREAD

**Issue by xiedeacc** [shadowsocks/shadowsocks-rust#453]
>Browser[SwitchyOmega] -> shadowsocks-client --> shadowsocks-server[Self-built server or shared by others]  --> nginx

注意nginx和shadowsocks-server部署在同一台机器上

**Comment by zonyitoo** [comment]
So? What problem did you encountered?

**Comment by xiedeacc** [comment]
sorry, it's my dns problem
