### ISSUE TITLE
[queston][[feature request?] MIPS64 support

### ISSUE THREAD

**Issue by huangya90** [shadowsocks/shadowsocks-rust#467]
Hi,

I saw there are two versions of MIPS shadowsocks-rust implementation. There are mips version and mipsel version. 
Is there any plan to support MIPS64? Or can I  just use mips version？ Thank you very much!

**Comment by zonyitoo** [comment]
You can compile it by yourself. You can open another issue if you found any incompatible in MIPS64 platform.
