### ISSUE TITLE
Local HTTP only works in `locals` not in `local`

### ISSUE THREAD

**Issue by jasonhancn** [shadowsocks/shadowsocks-rust#468]
I‘m using sslocal version 1.10.0.

when I configure local address and port at the root level, the command line parameter "--protocol http" dose not take effect.

```json
    "local_address": "127.0.0.1",
    "local_port": 8118
```

when set address/port and protocol in `locals`, it works

```json
    "locals": [
        {
            "protocol": "http",
            "local_address": "127.0.0.1",
            "local_port": 8118
        }
    ]
```

**Comment by zonyitoo** [comment]
Yes. https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.10.0 Please read Release Node carefully.

The command line argument `--protocol` is for the instance that created by command line `--local-addr`. So it is correct that only your second configuration works.
