### ISSUE TITLE
CryptoStream can be used in trojan?

### ISSUE THREAD

**Issue by Xx0101** [shadowsocks/shadowsocks-rust#470]
I want to use it in trojan-r

**Comment by zonyitoo** [comment]
What problem did you encountered?

**Comment by Xx0101** [comment]
> What problem did you encountered?

I want use it to crypto stream.server is trojan-go，but crypto error.

**Comment by zonyitoo** [comment]
What can I do for help?

**Comment by Xx0101** [comment]
> What can I do for help?

https://github.com/Xx0101/rust-leaf

**Comment by Xx0101** [comment]
> What can I do for help?

https://github.com/Xx0101/rust-leaf
this is my project.
I want to add aead crypto on trojan. Can you help me see what went wrong.
trojan-go is also in the directory

**Comment by zonyitoo** [comment]
Does trojan support shadowsocks protocol?

**Comment by zonyitoo** [comment]
I couldn't find any code that references `CryptoStream`

**Comment by Xx0101** [comment]
> I couldn't find any code that references `CryptoStream`

references Chipheldn't find any code that references `CryptoStream`

References the `Cipher` only in leaf/proxy/trojan/stream.rs.  Did I misuse it. And,the server supports shadowssocks protocol.

**Comment by zonyitoo** [comment]
Did you run KDF on your `key`?

**Comment by Xx0101** [comment]
> Did you run KDF on your `key`?

no, I use openssl_bytes_to_key

**Comment by zonyitoo** [comment]
It should work. Hmm, I have no idea. Could you just try to run the `sslocal` in this project and try if it works with your server?

**Comment by zonyitoo** [comment]
1. If it works, then there must be something wrong in your protocol implementation.
2. If it doesn't, then your server may have compatible issue with Rust's implementation, then we can take a deep look into this.
