### ISSUE TITLE
public ip in config raise an error

### ISSUE THREAD

**Issue by Lix1993** [shadowsocks/shadowsocks-rust#474]
2021-04-01T11:35:34.639598682+08:00 INFO  shadowsocks 1.10.2
2021-04-01T11:35:34.640114893+08:00 ERROR servers exited with error: Cannot assign requested address (os error 99)
thread 'main' panicked at 'aborted with server exited unexpectly', bin/ssserver.rs:299:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by Lix1993** [comment]
when change ip to 0.0.0.0 it works

**Comment by zonyitoo** [comment]
This error indicates that `bind()` returns errno `EADDRNOTAVAIL`.

Just double check if you have set the correct address for server.

**Comment by Lix1993** [comment]
I confirm ip is correct.

On a bandwagonhost vps it works, but on tencent clount it failed.

**Comment by zonyitoo** [comment]
Did you tried with other implementations, like libev or go2?

The errno `EADDRNOTAVAIL` indicates that the IP you want to `bind()` is not a local IP.

**Comment by zonyitoo** [comment]
BTW, just for check. You didn't set the `local_address` and `local_port` in your configuration, right?

**Comment by Lix1993** [comment]
thanks

ifconfig shows no network interface with public ip, so i have to use 10.0.4.13 instead.



```
ubuntu@VM-4-13-ubuntu:~$ ifconfig 
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.4.13  netmask 255.255.252.0  broadcast 10.0.7.255
        inet6 fe80::5054:ff:feca:220f  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:ca:22:0f  txqueuelen 1000  (Ethernet)
        RX packets 5719548  bytes 8249828070 (8.2 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 494213  bytes 536014078 (536.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1399  bytes 119805 (119.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1399  bytes 119805 (119.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


```

**Comment by Lix1993** [comment]
thanks for your help
