### ISSUE TITLE
 rc4 is not a supported method

### ISSUE THREAD

**Issue by userbl** [shadowsocks/shadowsocks-rust#475]
thread 'main' panicked at 'loading config "config.json", unsupported method, `rc4` is not a supported method', bin/sslocal.rs:197:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

config.json
     {"local_address":"192.168.9.10","local_port":1081,"servers": 
     [{"address":"58.129.457.163","method":"rc4","password":"******","port":45721,"timeout":300}]}

**Comment by zonyitoo** [comment]
Yes. It is deprecated.

**Comment by userbl** [comment]
Thank you very much !
