### ISSUE TITLE
[Feature Request] Accept multiple passwords on a single port

### ISSUE THREAD

**Issue by database64128** [shadowsocks/shadowsocks-rust#489]
Reference implementations

- https://github.com/Jigsaw-Code/outline-ss-server
- https://github.com/Qv2ray/mmp-go

Possible config format

``` jsonc
{
    "servers": [
        {
            "server": "::",
            "server_port": 12345,
            "method": "aes-256-gcm",
            "passwords": {
                "0": "144537e6-08f4-4110-a7f4-aba6da8be7f2", // When reloading, identify individual passwords with the number (0 in this case).
                "1": "33ae69d4-6bd6-41ec-b6b9-05f0412e7171"
            },
            "remarks": "Service A",
            "id": "5d91abc7-3ee7-41c9-a9e8-49a7e84450c7" // Used to identify servers when reloading.
        },
        {
            "server": "example.com",
            "server_port": 54321,
            "method": "chacha20-ietf-poly1305",
            "password": "example",
            "remarks": "Service B",
            "id": "9185279e-25c2-4438-913a-dfe3d01f9bb4" // Used to identify servers when reloading.
        }
    ]
}
```

**Comment by anquan123** [comment]
This is a very useful feature! Single port multi-user support can be realized!  The multi-port and multi-users of ss service providers seem to be more likely to be blocked than the single-ip single-port of individual users! It should be that GFW will detect the number of ports open by the IP. Once too many ports are opened, it will be suspected of being a proxy IP!

**Comment by zonyitoo** [comment]
Ah.. really? Did you have any references to support that?

**Comment by pyy** [comment]
Will in this way it save memory usage on the remote server? compare to multiple instance on different port.

**Comment by zonyitoo** [comment]
It will, but shouldn’t be significant.

**Comment by lzm0** [comment]
Would like to see this feature to be supported

**Comment by kallydev** [comment]
> Would like to see this feature to be supported

Since shadowsocks protocol doesn't take into account multi-user authentication, I recommend implementing it in SIP 003 plugin.

**Comment by fortuna** [comment]
I have a discussion on the optimizations we did for Outline at https://github.com/shadowsocks/shadowsocks-org/issues/130

In practice, the trial decryption is not an issue at all.

**Comment by database64128** [comment]
Now that we have Shadowsocks 2022 Extensible Identity Headers for native multi-user support (although shadowsocks-rust hasn't implemented it yet), I'm closing this issue.
