### ISSUE TITLE
[Feature Request] Add UDP relate options for `ssmanager`

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-rust#494]
Add `--udp-timeout` and `--udp-max-associations` options for `ssmanager`

Refer: https://github.com/shadowsocks/shadowsocks-rust/discussions/493

**Comment by zonyitoo** [comment]
Please test with the latest commit.

**Comment by pexcn** [comment]
> Please test with the latest commit.

可以提供一下编译好的 linux amd64 的二进制吗？
我这边用 GitHub Actions 编译 (docker build ...) 不知道出了什么问题，每次都要一个多小时。

另外提个小建议，希望本项目能支持 https://github.com/actions/upload-artifact, 这样就方便下载二进制进行测试了 😄

**Comment by zonyitoo** [comment]
Just run:

```
cross build --release --target "aarch64-unknown-linux-musl"
```

Actions for normal pushes are not built with optimization, just for unit tests.

**Comment by pexcn** [comment]
加了 `--udp-timeout 300 --udp-max-associations 512` 选项，在日志中体现出来了👌🏼
![image](https://user-images.githubusercontent.com/4590439/114302424-8bed8500-9afb-11eb-9bb1-56e3683a6a69.png)

> Actions for normal pushes are not built with optimization, just for unit tests.

单元测试通过以后，再把二进制放到  artifacts 里不是更好吗？因为不是用于正式环境的，只是当作测试版。
例如 shadowsocks-android 也有类似的做法：https://github.com/shadowsocks/shadowsocks-android/blob/master/.circleci/config.yml#L24
