### ISSUE TITLE
[Feature Request] Multiple Interfaces Support for ssmanager and ssserver

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-rust#502]
This suggestion is based on my production environment with shadowsocks-libev.

### [Environment]

Ubuntu 18.04
shadowsocks-manager 0.36.69
shadowsocks-rust

Multiple interfaces on the server bound with IP1, IP2, and IP3

### [Expected Behavior]

Start shadowsocks-rust ssmanager on IP1, IP2, and IP3 with the "-b" option.

Traffics that come from IP1 will be using IP1 as the outgoing interface.

Traffics that come from IP2 will be using IP2 as the outgoing interface.

Traffics that come from IP3 will be using IP3 as the outgoing interface.

### [What Do I See Instead]

I don't think ssmanager allows you to start on a certain interface. Instead, it only allows you to listen on 0.0.0.0, so basically, it is not possible to start ssmanager instance on different interfaces for different purposes.

And also, I don't think ssmanager can use "-i" or "-b" and pass the configuration to ssserver.

### [Usage Background]

I need to do some optimization for each interface user. I need to configure IP1 to access Netflix, IP2 to use public DNS, and IP3 for another certain group of people. Each configuration can allow me to control with shadowsocks-manager.

Previously I opened an issue for shadowsocks-libev [here](https://github.com/shadowsocks/shadowsocks-libev/issues/2738). It was a $200 question but successfully implemented. Please notice shadowsocks-libev [uses "-i" to route the traffic](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/shadowsocks-libev.asciidoc).

In [shadowsocks-rust v1.8.4](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.8.4), it fixed a problem with [multiple interface/IP usage scenario](https://github.com/shadowsocks/shadowsocks-rust/issues/26), but I think it's not working for ssmanager.

### [What Do I Propose]

1. Add "-i" function to shadowsocks-rust ssmanager to route the traffic, and pass to ssserver
2. Add "-s" function to shadowsocks-rust ssmanager to specify the bind-address, and pass to ssserver.

**Comment by zonyitoo** [comment]
1. `ssserver` has a `--outbound-bind-interface`, which works similar to `-i` in shadowsocks-libev
2. `ssserver` already supported that.

So the only thing I have to do is let `ssmanager` accepts `--outbound-bind-interface` and `--server-addr` and passes them to the internal server instances.

**Comment by zonyitoo** [comment]
Basically I don't have a lot of things to do. If you still want the command line argument for specifying the `server_host`, I can add it right now.

**Comment by RebelliousWhiz** [comment]
> Basically I don't have a lot of things to do. If you still want the command line argument for specifying the `server_host`, I can add it right now.

That would be awesome, thank you very much for that!

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/49b7004d7565de98a24b49657443b19c03365a8f/bin/ssmanager.rs#L52

It already exists. So nothing have to be done.

**Comment by RebelliousWhiz** [comment]
OK, I guess I will just test it. Sorry for the trouble, last time I tested the shadowsocks-rust was definitely way before 10 days ago.

I will close the issue for now. If I have any question, I will open again.

Thank you very much for taking your time to evaluate this issue!
