### ISSUE TITLE
配置文件不起作用了么？

### ISSUE THREAD

**Issue by qcxiang** [shadowsocks/shadowsocks-rust#504]
error: The following required arguments were not provided:
    --encrypt-method <ENCRYPT_METHOD>
    --password <PASSWORD>
    --server-addr <SERVER_ADDR>

配置文件“shadowsocks.json”里已经配置了method、password、server，为啥程序启动的时候报错，要通过命令行传参启动。

**Comment by DuckSoft** [comment]
> 为啥程序启动的时候报错

你是怎么启动的程序？请提供具体的命令及参数。

> 配置文件“shadowsocks.json”里已经配置了method、password、server

怎么配置的？请去除敏感信息之后贴一下具体用的文件内容。

> 配置文件不起作用了么？

XY 问题，又称过早得出结论。

**Comment by qcxiang** [comment]
之前一直这么用，最近更新到新版本之后就报这个错误了。
**启动程序：**
**ssserver --no-delay -U --config /etc/shadowsocks.json**
error: The following required arguments were not provided:
    --encrypt-method <ENCRYPT_METHOD>
    --password <PASSWORD>
    --server-addr <SERVER_ADDR>

USAGE:
    ssserver --config <CONFIG> --encrypt-method <ENCRYPT_METHOD> --password <PASSWORD> --server-addr <SERVER_ADDR> -U --tcp-no-delay

For more information try --help

**配置文件内容**
/etc/shadowsocks.json
{
    "server":"xxxx",
    "server_port":33060,
    "password":"xxxx",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":true
}

**Comment by database64128** [comment]
@qcxiang Just add the following fields to your config, and start the server with `ssserver -c /etc/shadowsocks.json`.

```jsonc
    "mode": "tcp_and_udp",
    "no_delay": true,
```

**Comment by database64128** [comment]
I would also recommend dropping `timeout` and `fast_open`, since apparently you don't quite understand what you're doing.

**Comment by qcxiang** [comment]
> @qcxiang Just add the following fields to your config, and start the server with `ssserver -c /etc/shadowsocks.json`.
> 
> ```js
>     "mode": "tcp_and_udp",
>     "no_delay": true,
> ```


thank you! it works!
