### ISSUE TITLE
What does the "unknown" stand for?

### ISSUE THREAD

**Issue by SekiBetu** [shadowsocks/shadowsocks-rust#509]
![image](https://user-images.githubusercontent.com/38283893/116892208-2ad05180-ac62-11eb-8117-aadb0e7c2a80.png)

**Comment by DuckSoft** [comment]
It's Rust toolchain name.

```console
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-2021-03-24-x86_64-unknown-linux-gnu
nightly-aarch64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
1.24.1-x86_64-unknown-linux-gnu
```

**Comment by zonyitoo** [comment]
This is so called **target triple**s.

https://doc.rust-lang.org/nightly/rustc/platform-support.html

```
ARCH-  VENDOR- OS
```

For GNU/Linux OSes, they usually don't have a specific vendor, so it is **unknown**.

**Comment by klaaktu** [comment]
Hi, about the target:
What's difference between `gnu` and `musl`? Should I use `gnu` if `uname -a` says "GNU/Linux"?
p.s. ubnt er-x, MT7621

**Comment by zonyitoo** [comment]
GNU means GNU toolchains, which will dynamically link to `glibc`. MUSL means statically linked to `musl`.
