### ISSUE TITLE
是否可以把local-dns做一个optional的选项

### ISSUE THREAD

**Issue by mokitoo** [shadowsocks/shadowsocks-rust#511]
目前看起来local-dns好像是必选的，但是它的原理好像是local dns把域名发给远端请求remote dns , 返回的ip被local dns缓存，下一次就不需要重复请求远端dns了，不知道这么理解原理对不对。

如果是这样的话，那么远端的代理始终看不到代理的域名，不知道有什么好的解决方案呢？

**Comment by zonyitoo** [comment]
`local-dns` is always an optional feature.

**Comment by mokitoo** [comment]
> `local-dns` is always an optional feature.

如果配置文件不写local-dns这块的话，那么会把需要代理的域名直接发给远程的proxy去解析对嘛？

**Comment by zonyitoo** [comment]
The `local_dns_*` fields in configuration file are for setting the `local-dns` server. It doesn't related to whether the domain names are sent to remote or not. They are just not related.

**Comment by zonyitoo** [comment]
Android. cc @madeye @Mygod
