### ISSUE TITLE
rust相比于libev有什么优缺点呀？

### ISSUE THREAD

**Issue by wind0ta** [shadowsocks/shadowsocks-rust#519]
rust相比于libev有什么优缺点呀？

**Comment by zonyitoo** [comment]
1. Local: Support multiple remote servers and choose them by balancer
2. Local: Support multiple inbound ports with various protocols, including SOCKS5, SOCKS4/4a, HTTP, ...
3. Servers are running in multi-threads
4. Better performances

**Comment by zonyitoo** [comment]
Ref https://github.com/shadowsocks/shadowsocks-rust/issues/448 .
