### ISSUE TITLE
Donate this code into shadowsocks org on github.com/shadowsocks

### ISSUE THREAD

**Issue by netroby** [shadowsocks/shadowsocks-rust#53]
Donate this code into shadowsocks org on github.com/shadowsocks?

To gains more users and improve development. should join to shadowsocks org.

**Comment by zonyitoo** [comment]
How to do that?

**Comment by netroby** [comment]
contact one of the team member. like @clowwindy

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zonyitoo** [comment]
Already transferred.
