### ISSUE TITLE
[Feature proposal] Load balancer Round Robin

### ISSUE THREAD

**Issue by pyy** [shadowsocks/shadowsocks-rust#534]
May I ask why not add round robin optional feature to the load balancer? Thank you.
Advantage: spread bandwidth from local to multiple remote server, in order to protect remote servers.

**Comment by zonyitoo** [comment]
There are several disadvantages about using round-robin balancer in a pass firewall situation:

1. For most use cases, people won't use multiple server instances hosted by one service provider. So there is no need to "spread bandwidth".
2. If your servers are provided by different service providers, then connections for one website will be proxied from different services. For instance, accessing "youtube.com" and all of its resources are retrived from all over the world, US, JP, ... For websites that provide different services based on your location will be messed up.
3. Spread connections from all over the world will make your connection very unstable, which is a problem that unresolvable physically. That's a very bad experience.

On the other hand, why do you think round-robin could "protect" your remote servers?

**Comment by pyy** [comment]
Good points. Thanks for your reply.


1.
 > why do you think round-robin could "protect" your remote servers?

If long time connecting with same IP and same port, will the remote server be detected by this unusually connecting? (I just think, without test).  This is the main concern from myself.

2. It's true that one website be proxied from different IPs might get problems. From my test, I put nginx (stream load balance) in local part, youtube.com shows CAPTCHA, but after verifying successfully, youtube.com works well, because of cookies in the browser I think.

3. If we have 20 servers, for example, we can use the existing score system in ss-rust to get best 5 servers and then make round-robin for theese 5 servers, to improve the unreliable round-robin.

**Comment by zonyitoo** [comment]
> If long time connecting with same IP and same port, will the remote server be detected by this unusually connecting?

No. There is no evidence about this could become a feature for detecting. Actually there are evidences about active probing, which is that someone will try to replay your data flows to your server's port and detecting it based on its behavior.

Long time ago, the balancer is a round-robin balancer. And trust me, its experience is really bad when you have servers around the world.

Choosing the best server and use it all the way will help to improve the stablity of connections. If you have some servers, for example, the best 5 servers, have nearly the same connection quality, then the score of them will become very similar. In practice, servers that have very similar scores will trigger switching constantly. In this case, it should work just like "spreading bandwidth" through these servers, but without the flaws of round-robin.

**Comment by pyy** [comment]
thanks for your comments.
