### ISSUE TITLE
Enable TCP KeepAlive by default

### ISSUE THREAD

**Issue by zonyitoo** [shadowsocks/shadowsocks-rust#546]
ref #490 

TCP Keep Alive is useful for purging dead connections. Since many users run shadowsocks with mobile connection, there should be higher chance to leave dead connections on servers.

Further more, Go already have set 15 seconds keep alive timeout on all TCP connections. (Go's source code can prove that: [net/tcpsock_posix.go:accept](https://golang.org/src/net/tcpsock_posix.go). And here is the issue https://github.com/golang/go/issues/31510 that introduced this feature into the standard `net` library.)

`SO_KEEPALIVE` is not enabled by default for most operating systems.

Introducing this feature shouldn't break anything. If you have encountered anything related to this, please comment.

Adding a new configuration field for customizing the keep alive timeout

```json
{
    "keep_alive": 15
}
```

**Comment by om2mo** [comment]
15秒可能消耗过多的电量在移动平台设备，如何在命令行中配置它？

**Comment by zonyitoo** [comment]
Try with this commit and specify keep alive timeouts with command line options like `--tcp-keep-alive 300`.

**Comment by om2mo** [comment]
➜  ~ sslocal -U --protocol redir  --tcp-fast-open --tcp-no-delay --tcp-keep-alive 300 -s server -m aes-256-gcm -k  -b 0.0.0.0:12345
error: Found argument '--tcp-keep-alive' which wasn't expected, or isn't valid in this context
        Did you mean --tcp-redir?

**Comment by zonyitoo** [comment]
You should either compile from the latest master branch, or download the nightly build of v1.11.2.

**Comment by zonyitoo** [comment]
@madeye @Mygod Consider adding `--tcp-keep-alive` or `keep_alive` configuration if shadowsocks-android upgrades the underlying shadowsocks-rust, if this related to battery consumption.

**Comment by Mygod** [comment]
According to [this](https://stackoverflow.com/a/30904117/2245107), Android will not respect TCP keep alive settings when device goes to sleep.

**Comment by zonyitoo** [comment]
So, @om2mo your assumption doesn't exists. What's your mobile platform?

**Comment by zonyitoo** [comment]
But on the other hand, what if system is not going to sleep? Would this increase battery consumption while system is awake?

**Comment by Mygod** [comment]
Setting it to 28 minutes as default should alleviate he problem.

**Comment by zonyitoo** [comment]
Why 28 minutes?

**Comment by Mygod** [comment]
It is the timeout for GMS heartbeat on mobile network.
