### ISSUE TITLE
Is there an iOS client with ipv6 support?

### ISSUE THREAD

**Issue by itskeKs** [shadowsocks/shadowsocks-rust#550]
Hey there,

might be a long shot but is there an opensource ios client with ipv6 support for iOS somewhere? Would be great if someone can help me out. i am stuck with nekit atm but the project is abandoned.

Any help appreciated. Thanks in advance.

**Comment by zonyitoo** [comment]
I don't know, mate. This project is just contains low level services.

**Comment by itskeKs** [comment]
any idea where to look or to ask? 😅

**Comment by NetHeritage** [comment]
shadowrocket

**Comment by linuxbunter213** [comment]
No check IOS projects
