### ISSUE TITLE
不监听udp的端口

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#551]
测试udp的时候不通，排查到服务端没有监听udp端口
启动命令
```Shell
ssmanager \
--manager-address /tmp/ss-manager.socket \
--daemonize-pid /run/ss-manager.pid \
--daemonize
```
发送命令
```Shell
add :{"server_port":1234,"password":"abcd","method":"aes-128-gcm","mode":"tcp_and_udp"}  
```
结果发现只监听tcp的端口没有udp的端口监听

**Comment by zonyitoo** [comment]
I don't think so. I tried it locally and it listens to port 1234 with both TCP and UDP.

**Comment by yiguihai** [comment]
> I don't think so. I tried it locally and it listens to port 1234 with both TCP and UDP.
> 
> BTW, you shouldn't add a space after `add`, in your example command. You should send
> 
> ```
> add: {"server_port":1234,"password":"abcd","method":"aes-128-gcm","mode":"tcp_and_udp"}
> ```

亲自演示
![IMG_20210613_082626](https://user-images.githubusercontent.com/22967964/121791860-2f086b00-cc21-11eb-9929-b6de19883a2b.jpg)

**Comment by zonyitoo** [comment]
Well, in your case, it doesn't even listen to the TCP port.

What did you see in `ssmanager`'s log?

**Comment by yiguihai** [comment]
> Well, in your case, it didn't even listen to the TCP port.
> 
> What did you see in `ssmanager`'s log?

只有这些
![IMG_20210613_085307](https://user-images.githubusercontent.com/22967964/121792233-ebaffb80-cc24-11eb-8a68-bdeca0632086.jpg)

**Comment by zonyitoo** [comment]
Did you noticed that your command have missed the `"mode": "tcp_and_udp"`:

![Uploading image.png…]()

**Comment by yiguihai** [comment]
> Did you noticed that your command have missed the `"mode": "tcp_and_udp"`:
> 
> ![image](https://user-images.githubusercontent.com/1067951/121792254-26199880-cc25-11eb-8d22-c704ab8ccb7e.png)

加入后可以了，tcp_and_udp不是默认值的吗？

**Comment by zonyitoo** [comment]
It was never a default value.

Add `-U` to command line arguments to apply it to all servers as default.
