### ISSUE TITLE
shadowsocks-rust timeout every 15 second

### ISSUE THREAD

**Issue by pyy** [shadowsocks/shadowsocks-rust#554]
Hello,

I'm using VNC over Shadowsocks-rust tunnel mode, but the connection disconect every ca. 15 second. 
I have tried setting `"timeout": 7200` in both local and server part, it doesn't work. Latest Shadowsocks-Rust version also have this problem.

If I use SSH port forward or shadowsocks-libev tunnel mode, there is no this problem.

Someone have similar problem? Any clue? Thank you.

**Comment by zonyitoo** [comment]
No idea. The only thing related to 15 seconds is the TCP keep alive socket option.

You may try to add a `"keep_alive": 7200` to the configuration file and see if there is anything changes.

Further more, you can add `-vvv` to the command line options and see what log does it output before disconnection.

**Comment by zonyitoo** [comment]
I tried locally with this configuration

```
VNCViewer -> sslocal (tunnel) -> ssserver -> VNCServer (macOS)
```

I was playing around about 15 minutes and everything works fine. `sslocal` and `ssserver` starts with default configurations:

```
$ sslocal -b '127.0.0.1:9000' -s '127.0.0.1:8388' -k 'aaa' -m 'aes-128-gcm' --protocol tunnel --forward-addr $VNC_SERVER_ADDR
$ ssserver -s 127.0.0.1:8388 -k 'aaa' -m 'aes-128-gcm'
```

**Comment by pyy** [comment]
Thanks for your reply. 
1. 
It looks `"timeout": 7200` has no effect. Only `"keep_alive": 7200` solves this problem.
And important is: `"keep_alive": 7200` must put inside `"locals": []` in local config file, not in `"servers": []` in local config file.

Below works:


```
{
    "locals": [
        {
            "local_address": "127.0.0.1",
            "local_port": xxxx,
            "keep_alive": 7200,    <-- must in locals part.

        },
        {
            "local_address": "127.0.0.1",
            "local_port": xxxx,
            "protocol": "tunnel",
            "forward_address": "x.x.x.x",
            "forward_port": xxxx
        }
    ],
    "servers": [
        {
            "server": "a.b.c.d",
    	    "server_port": xxxx,
    	    "password": "password",
    	    "method": "aes-256-gcm",
            "keep_alive": 7200,    <-- wrong.
        }

    ]

}

```

May I ask is `"timeout": 7200` only for remote server part, the timeout setting for connecting target website?

2.  -vv output from sslocal:
```
2021-06-16T22:05:22.739031+02:00 TRACE [8781:123145604231168] 
[shadowsocks::relay::tcprelay::proxy_stream::client] connected tcp remote 
x.x.x.x:xxxx (outbound: x.x.x.x:xxxx) with ConnectOpts { bind_local_addr: 
None, bind_interface: None, tcp: TcpSocketOpts { send_buffer_size: None, 
recv_buffer_size: None, nodelay: false, fastopen: false, keepalive: Some(15s) } }
```
notice the last part `keepalive: Some(15s)`, still is 15s, but I set it 7200s in the configuration. Is there something wrong in the program?

Thanks again.

**Comment by zonyitoo** [comment]
> And important is: `"keep_alive": 7200` must put inside `"locals": []` in local config file, not in `"servers": []` in local config file.

No. `"keep_alive"` must be in the root of the configuration file like this:

```json
{
    "keep_alive": 7200,
    "locals": [],
    "servers": []
}
```

> notice the last part `keepalive: Some(15s)`, still is 15s

Yes, it is obvious that you didn't changed the TCP keep alive setting.

> Only `"keep_alive": 7200` solves this problem.

Since you have put in the wrong place, the `sslocal` is still running with the default settings. If you problem solved, then it can be sured that it is a networking issue.

> May I ask is `"timeout": 7200` only for remote server part, the timeout setting for connecting target website?

Yes, `timeout` is for handshaking and connecting.

**Comment by pyy** [comment]
Hello zonyitoo,

thanks again for your correction.

1. You are right, that `"keep_alive"` must be in the root of the configuration file. And then `-vv` will show 
```
[shadowsocks::relay::tcprelay::proxy_stream::client] connected tcp remote ....  keepalive: Some(7200s) } }
```

2.  but, but, the connection still discount every 20-75s randomly. 
Below is the config of local part:
```
{
    "locals": [
        {
            "local_address": "127.0.0.1",
            "local_port": xxx,
        },
        {
            "local_address": "x.x.x.x",
            "local_port": xxx,
            "protocol": "tunnel",
            "forward_address": "x.x.x.",
            "forward_port": xxx
        }
    ],
    "servers": [
        {
		"server": "x.x.x.x",
    		"server_port": xxx,
    		"password": "password",
    		"method": "aes-256-gcm"
        }

    ],
"keep_alive": 7200,
}
```

Server part:
```
{
    "server": "x.x.x.x",
    "server_port": xxx,
    "method": "aes-256-gcm",
    "password": "password",
    "timeout": 7200,
    "keep_alive": 7200
}

```

May I ask my config is correct? Thank you.
(If I use ssh forward port as tunnel, there is not this problem, so perhaps it's not the VNC server/client problem.)

**Comment by pyy** [comment]
Finally, find where is the problem!!

I use systemd in server part to control shadowsocks-rust. and I set `type=forking`, which make the systemd cannot detect succefully the running of shadowsocks-rust, it just restart again and again. When I use it in local part, the proxy works well in the browser, so I didn't realize the systemd configuration is wrong.

`type=forking`:
```
Jun 12 06:35:03 localhost systemd[1]: Starting Daemon to start shadowsocks-rust-server...
Jun 12 06:35:03 localhost ssserver[17482]: INFO  shadowsocks 1.11.1
Jun 12 06:35:03 localhost ssserver[17482]: INFO  shadowsocks tcp server listening on x.x.x.x:xxx, inbound address x.x.x.x:xxx
Jun 12 06:36:34 localhost systemd[1]: shadowsocks-rust-server.service: Start operation timed out. Terminating.
Jun 12 06:36:34 localhost ssserver[17482]: INFO  received SIGTERM, exiting
Jun 12 06:36:34 localhost systemd[1]: Failed to start Daemon to start shadowsocks-rust-server.
Jun 12 06:36:34 localhost systemd[1]: shadowsocks-rust-server.service: Unit entered failed state.
Jun 12 06:36:34 localhost systemd[1]: shadowsocks-rust-server.service: Failed with result 'timeout'.
Jun 12 06:36:34 localhost systemd[1]: shadowsocks-rust-server.service: Service RestartSec=100ms expired, scheduling restart.
Jun 12 06:36:34 localhost systemd[1]: Stopped Daemon to start shadowsocks-rust-server.
Jun 12 06:36:34 localhost systemd[1]: Starting Daemon to start shadowsocks-rust-server...
Jun 12 06:36:34 localhost ssserver[18394]: INFO  shadowsocks 1.11.1
Jun 12 06:36:34 localhost ssserver[18394]: INFO  shadowsocks tcp server listening on x.x.x.x:xxx, inbound address x.x.x.x:xxx
Jun 12 06:38:04 localhost systemd[1]: shadowsocks-rust-server.service: Start operation timed out. Terminating.
Jun 12 06:38:04 localhost ssserver[18394]: INFO  received SIGTERM, exiting
Jun 12 06:38:04 localhost systemd[1]: Failed to start Daemon to start shadowsocks-rust-server.
Jun 12 06:38:04 localhost systemd[1]: shadowsocks-rust-server.service: Unit entered failed state.
Jun 12 06:38:04 localhost systemd[1]: shadowsocks-rust-server.service: Failed with result 'timeout'.
Jun 12 06:38:04 localhost systemd[1]: shadowsocks-rust-server.service: Service RestartSec=100ms expired, scheduling restart.
Jun 12 06:38:04 localhost systemd[1]: Stopped Daemon to start shadowsocks-rust-server.
Jun 12 06:38:04 localhost systemd[1]: Starting Daemon to start shadowsocks-rust-server...
Jun 12 06:38:04 localhost ssserver[19305]: INFO  shadowsocks 1.11.1
Jun 12 06:38:04 localhost ssserver[19305]: INFO  shadowsocks tcp server listening on x.x.x.x:xxx, inbound address x.x.x.x:xxx
Jun 12 06:39:35 localhost systemd[1]: shadowsocks-rust-server.service: Start operation timed out. Terminating.
Jun 12 06:39:35 localhost ssserver[19305]: INFO  received SIGTERM, exiting
Jun 12 06:39:35 localhost systemd[1]: Failed to start Daemon to start shadowsocks-rust-server.
Jun 12 06:39:35 localhost systemd[1]: shadowsocks-rust-server.service: Unit entered failed state.
Jun 12 06:39:35 localhost systemd[1]: shadowsocks-rust-server.service: Failed with result 'timeout'.
Jun 12 06:39:35 localhost systemd[1]: shadowsocks-rust-server.service: Service RestartSec=100ms expired, scheduling restart.
Jun 12 06:39:35 localhost systemd[1]: Stopped Daemon to start shadowsocks-rust-server.
Jun 12 06:39:35 localhost systemd[1]: Starting Daemon to start shadowsocks-rust-server...
Jun 12 06:39:35 localhost ssserver[20265]: INFO  shadowsocks 1.11.1
```

It should be `type=simple`, then everything works well.
After correction, the full systemd configuration is here:
```
[Unit]
Description=Daemon to start shadowsocks-rust-server
Wants=network-online.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/ssserver --log-without-time -c /etc/shadowsocks-rust/config.json
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by zonyitoo** [comment]
Glad to hear that.

**Comment by linuxbunter213** [comment]
Had the same problem on a god finger check port 52 for cookies
