### ISSUE TITLE
In a Particular Case, ssmanager Is Not Closing UDP Ports When ssmgr Asks So

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-rust#557]
I had a crazy busy day. So please forgive me for not writing this issue properly as the way I used to...

I have both TCP and UDP enabled for the ssmanager server. I use shadowsocks-manager to control my client accounts. Today, one of my clients used up his data, and then I added the data for him through shadowsocks-manager GUI.

However, the port was not able to be connected correctly, so I checked the log.

I noticed the port was in use which is weird:

```
journalctl -u eno0manager -f
Jun 26 17:40:10 theeden-us-tc-1 ssmanager[867]: 2021-06-26T17:40:10.816649106+08:00 ERROR servers exited with error: Address already in use (os error 98)
```

Then I checked the ports, and it appears the UDP was still open:

```
sudo  netstat -tupl | grep 15xxx
udp   2144768      0 eno1:15xxx   0.0.0.0:*
```

Then I stopped and restarted ssmanager and ssmgr. Then the ports were opened correctly.

```
sudo  netstat -tupl | grep 15xxx
tcp        0      0 eno1:15xxx   0.0.0.0:*               LISTEN      4698/ssmanager
udp        0      0 eno1:15xxx   0.0.0.0:*                           4698/ssmanager
```

Therefore I here make a bold assumption (大胆假设😂) that when ssmgr asks the ssmanager to stop a port, ssmanager does not close UDP as expected.

**Comment by zonyitoo** [comment]
I tested locally by repeatedly sending `add: {"server_port": 1080,"password":"aaa","mode":"tcp_and_udp"}` to the `ssmanager` and the server `1080` could be able to restart normally.

But one interesting thing is, in your first `netstat`'s output, the program column was missing.

**Comment by RebelliousWhiz** [comment]
I have done a bit more tests. This issue might need help from @gyteng also.

In shadowsocks-webgui, if I only delete then add the port, shadowsocks-rust is working perfectly fine. Both TCP and UDP close and open correctly. But if I set webgui as below and use data over the limit, shadowsocks-rust will close the UDP and open UDP again, which is weird:

![image](https://user-images.githubusercontent.com/15100865/123572872-7ab13c00-d7ff-11eb-8d7b-8bf5a760f681.png)
![image](https://user-images.githubusercontent.com/15100865/123572883-7e44c300-d7ff-11eb-9a99-4d08b20bd92d.png)

ssmgr log (Information below was for testing purposes only, server deleted after the test)x:

```
## I added port 17279 here

Jun 28 10:43:43 eno1 ssmgr[18999]: [2021-06-28T10:43:43.330] [INFO] system - { command: 'add', port: 17279, password: '2730792459' }
Jun 28 10:43:43 eno1 ssmgr[18999]: [2021-06-28T10:43:43.781] [INFO] system - { command: 'version' }
Jun 28 10:43:50 eno1 ssmgr[18999]: [2021-06-28T10:43:50.911] [INFO] system - { command: 'list' }
Jun 28 10:44:00 eno1 ssmgr[18999]: [2021-06-28T10:44:00.002] [INFO] system - Receive flow from shadowsocks: (libev)
Jun 28 10:44:00 eno1 ssmgr[18999]: {}
Jun 28 10:44:00 eno1 ssmgr[18999]: [2021-06-28T10:44:00.033] [INFO] system - { command: 'flow', options: { clear: true } }
Jun 28 10:44:28 eno1 ssmgr[18999]: [2021-06-28T10:44:28.863] [INFO] system - { command: 'list' }

## I used up the data here. Fun fact: one fast.com speed test costs over 150M of data.

Jun 28 10:45:00 eno1 ssmgr[18999]: [2021-06-28T10:45:00.002] [INFO] system - Receive flow from shadowsocks: (libev)
Jun 28 10:45:00 eno1 ssmgr[18999]: {
Jun 28 10:45:00 eno1 ssmgr[18999]:   "17279": 153305804
Jun 28 10:45:00 eno1 ssmgr[18999]: }
Jun 28 10:45:00 eno1 ssmgr[18999]: [2021-06-28T10:45:00.406] [INFO] system - { command: 'flow', options: { clear: true } }
Jun 28 10:45:01 eno1 ssmgr[18999]: [2021-06-28T10:45:01.046] [INFO] system - { command: 'version' }
Jun 28 10:45:04 eno1 ssmgr[18999]: [2021-06-28T10:45:04.408] [INFO] system - { command: 'list' }
Jun 28 10:45:08 eno1 ssmgr[18999]: [2021-06-28T10:45:08.266] [INFO] system - { command: 'del', port: 17279 }
Jun 28 10:45:40 eno1 ssmgr[18999]: [2021-06-28T10:45:40.429] [INFO] system - { command: 'list' }
```

shadowsocks-rust log:

```
## I started the server here and tested :

Jun 28 10:44:00 eno1 ssmanager[8872]: 2021-06-28T10:44:00.003751731+08:00 INFO  shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
Jun 28 10:44:00 eno1 ssmanager[8872]: 2021-06-28T10:44:00.003824228+08:00 INFO  shadowsocks udp server listening on 192.168.110.100:17279

## I don't think in v1.11.1 I am able to get debug log from shadowsocks-rust ssmanager, and I am bad at compile... Waiting for v1.11.2 release..
```

netstat log:

```
root@eno1:~# netstat -tupl | grep 17279
udp        0      0 theeden-hk-2:17279      0.0.0.0:*                           8872/ssmanager
```

In this case only, when I select unlimited data in webgui and use up all the data, shadowsocks-rust will have this UDP port open.

Then I add more data in webgui. Here is what I have:

![image](https://user-images.githubusercontent.com/15100865/123573952-8b62b180-d801-11eb-928e-ab45fb898345.png)

ssmgr log:

```
Jun 28 10:48:27 theeden-hk-2 ssmgr[18999]: [2021-06-28T10:48:27.730] [INFO] system - { command: 'list' }
Jun 28 10:48:34 theeden-hk-2 ssmgr[18999]: [2021-06-28T10:48:34.110] [INFO] system - { command: 'add', port: 17279, password: '2730792459' }
```

shadowsocks-rust log:

```
Jun 28 10:48:34 theeden-hk-2 ssmanager[8872]: 2021-06-28T10:48:34.112262451+08:00 INFO  shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
Jun 28 10:48:34 theeden-hk-2 ssmanager[8872]: 2021-06-28T10:48:34.112325105+08:00 ERROR servers exited with error: Address already in use (os error 98)
```

Netstat log:

```
root@eno1:~# netstat -tupl | grep 17279
udp        0      0 eno1:17279      0.0.0.0:*                           8872/ssmanager
```

I think it might be a little difficult here to determine what's really going on since I don't have shadowsocks-rust debug log...

**Comment by zonyitoo** [comment]
> I think it might be a little difficult here to determine what's really going on since I don't have shadowsocks-rust debug log...

Just start `ssmanager` with `-vvv` command line argument.

**Comment by RebelliousWhiz** [comment]
OK, I will do more tests and let you know.

**Comment by zonyitoo** [comment]
> But if I set webgui as below and use data over the limit, shadowsocks-rust will close the UDP and open UDP again, which is weird:

What exactly command that `webgui` sends to `ssmanager` when it detected data quota excceeded?

**Comment by RebelliousWhiz** [comment]
I got nothing useful from webgui debug log....

Logs before ssmgr receive "delete"

```
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.001] [INFO] system - [1] cron: CheckServerStatus, [180]
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.002] [INFO] system - [1] cron: CheckPaypalOrder, [60]
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.002] [INFO] system - [1] cron: SaveFlow, [60]
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.004] [INFO] system - [1] cron: Generate5minFlow, [300]
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.004] [INFO] system - [1] cron: CheckAlipayOrder, [60]
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.004] [INFO] alipay - check alipay order
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.015] [INFO] flowSaver - Generate 5min flow, length: 10
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.015] [INFO] flowSaver - insert generate flow from 0 to 50
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.060] [INFO] flowSaver - [server: 8] insert 6 flow
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.377] [INFO] flowSaver - [server: 9] insert 2 flow
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.419] [INFO] flowSaver - [server: 11] insert 1 flow
Jun 28 10:45:00 eno1 ssmgr[28560]: [2021-06-28T10:45:00.759] [INFO] flowSaver - [server: 14] insert 3 flow
```

Others are just http logs and queue logs like:

```
Jun 28 10:45:01 eno1 ssmgr[28560]: [2021-06-28T10:45:01.430] [WARN] express - [my.web] [my.ip] GET 304 9ms /serviceworker.js
Jun 28 10:45:10 eno1 ssmgr[28560]: [2021-06-28T10:45:10.813] [INFO] account - Add [35] elements to queue
Jun 28 10:45:22 eno1 ssmgr[28560]: [2021-06-28T10:45:22.637] [INFO] account - Add [35] elements to queue
Jun 28 10:45:28 eno1 ssmgr[28560]: [2021-06-28T10:45:28.620] [WARN] express - [my.web] [my.ip] GET 304 7ms /admin/account/116
Jun 28 10:45:28 eno1 ssmgr[28560]: [2021-06-28T10:45:28.759] [WARN] express - [my.web] [my.ip] GET 304 11ms /libs/style.css
Jun 28 10:45:28 eno1 ssmgr[28560]: [2021-06-28T10:45:28.760] [WARN] express - [my.web] [my.ip] GET 304 12ms /libs/angular-material.min.css
Jun 28 10:45:28 eno1 ssmgr[28560]: [2021-06-28T10:45:28.760] [WARN] express - [my.web] [my.ip] GET 304 10ms /libs/bundle.js
```

**Comment by zonyitoo** [comment]
Just start `ssmanager` with `-vvv`, and you will see the commands it receives from `ssmgr`.

**Comment by RebelliousWhiz** [comment]
I started `ssmanager` with `-vvv`. Didn't see any log related to ssmgr, only TCP/UDP open or close.

I restarted ssmanager, then did the same thing: set up 50MB data limit, ran our of quota, TCP port closed, UDP remains. The test port is the same: 17279

Please check the logs here: https://codeshare.io/N33er8 (will expire in 24 hours)

Line 215 and 216 shows:

```
Jun 28 13:47:33 eno1 ssmanager[23383]: 2021-06-28T13:47:33.637106520+08:00 INFO  [23383:140434858149632] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
Jun 28 13:47:33 eno1 ssmanager[23383]: 2021-06-28T13:47:33.637177406+08:00 INFO  [23383:140434858149632] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 192.168.110.100:17279
```
And that's all I get from the log about port 17279.

In two mins, TCP port 17279 was closed. However, I didn't see any log about the port closing.

**Comment by zonyitoo** [comment]
I couldn't see `17279` in your logs but only `17777`.

BTW, did you start servers from configuration file instead of `add` command? I couldn't see

https://github.com/shadowsocks/shadowsocks-rust/blob/6490e34ec680138455e1e8441fdd3e1453c88d6d/crates/shadowsocks-service/src/manager/server.rs#L134

in your logs. So it didn't receive any commands from any manager clients.

Does something still listening on UDP `17777` after your test?

**Comment by RebelliousWhiz** [comment]
zonyitoo, codeshare.io search is stupid. Please check the line 215 and 216 directly, you will see 17279.

17777 is another port pre-configured that's in use, not in the scope of the problem.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/actions/runs/972402299

But still, there is no command logs. Could you download this nightly builds and see if you can see `received ... from ...`?

**Comment by RebelliousWhiz** [comment]
No problem zonyitoo. I will test it soon with the nightly build. 上班摸鱼 is bad after all... 下班摸鱼 is ok...

**Comment by RebelliousWhiz** [comment]
Tested with v1.11.2 nightly build. The log looks fine. This time I set 17279 pre-configured, and start ssmanager and ssmgr:

```
journalctl -u ssmanager -f --since 15:30 | grep 17279

## Server start

Jun 28 15:30:51 eno1 ssmanager[26361]: 2021-06-28T15:30:51.124679786+08:00 TRACE [26361:140711628792464] [shadowsocks_service::manager::server] received Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None }) from SocketAddr(127.0.0.1:14610)
Jun 28 15:30:51 eno1 ssmanager[26361]: 2021-06-28T15:30:51.124927273+08:00 INFO  [26361:140711626664736] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
Jun 28 15:30:51 eno1 ssmanager[26361]: 2021-06-28T15:30:51.124974832+08:00 INFO  [26361:140711626664736] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 192.168.110.100:17279

## Data used up

Jun 28 15:32:20 eno1 ssmanager[26361]: 2021-06-28T15:32:20.282246447+08:00 TRACE [26361:140711628792464] [shadowsocks_service::manager::server] received Remove(RemoveRequest { server_port: 17279 }) from SocketAddr(127.0.0.1:14610)

## Add data

Jun 28 15:33:33 eno1 ssmanager[26361]: 2021-06-28T15:33:33.031846712+08:00 TRACE [26361:140711628792464] [shadowsocks_service::manager::server] received Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None }) from SocketAddr(127.0.0.1:14610)
Jun 28 15:33:33 eno1 ssmanager[26361]: 2021-06-28T15:33:33.032023853+08:00 INFO  [26361:140711628774176] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
```

Didn't see the UDP log, so I checked again

```
journalctl -u ssmanager --since 15:33
Jun 28 15:33:33 eno1 ssmanager[26361]: 2021-06-28T15:33:33.031846712+08:00 TRACE [26361:140711628792464] [shadowsocks_service::manager::server] received Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None }) from SocketAddr(127.0.0.1:14610)
Jun 28 15:33:33 eno1 ssmanager[26361]: 2021-06-28T15:33:33.032023853+08:00 INFO  [26361:140711628774176] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279
Jun 28 15:33:33 eno1 ssmanager[26361]: 2021-06-28T15:33:33.032086796+08:00 ERROR [26361:140711628774176] [shadowsocks_service::server::server] servers exited with error: Address in use (os error 98)
```

Netstat:

```
root@eno1:~$ sudo netstat -tupl | grep 17279
udp        0      0 theeden-hk-2:17279      0.0.0.0:*                           26361/ssmanager
```

The weird thing is if you just delete then add the port, it works fine.

```
root@eno1:~$ journalctl -u ssmanager -f | grep 17279

## Add test

Jun 28 15:50:30 eno1 ssmanager[26730]: 2021-06-28T15:50:30.710184574+08:00 TRACE [26730:139640770925200] [shadowsocks_service::manager::server] received Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None }) from SocketAddr(127.0.0.1:14610)
Jun 28 15:50:30 eno1 ssmanager[26730]: 2021-06-28T15:50:30.710422965+08:00 INFO  [26730:139640770906912] [shadowsocks_service::server::tcprelay] shadowsocks tcp server listening on 192.168.110.100:17279, inbound address 192.168.110.100:17279

## Delete test
Jun 28 15:50:30 eno1 ssmanager[26730]: 2021-06-28T15:50:30.710484379+08:00 INFO  [26730:139640770906912] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 192.168.110.100:17279
Jun 28 15:50:55 eno1 ssmanager[26730]: 2021-06-28T15:50:55.023277816+08:00 TRACE [26730:139640770925200] [shadowsocks_service::manager::server] received Remove(RemoveRequest { server_port: 17279 }) from SocketAddr(127.0.0.1:14610)
```

`netstat -tupl | grep 17279`  shows nothing.

But please notice, when you are testing, you are sending `add: {"server_port": 1080,"password":"aaa","mode":"tcp_and_udp"}`, but in this case ssmgr is sending `Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None })`. However, the remove command `Remove(RemoveRequest { server_port: 17279 })` is the same (or I didn't notice the difference?)

And also, `shadowsocks-manager` is not using `ssmgr` to control `mode`, if I want to use `tcp_and_udp`, I need to start it with `ssmanager`.

**Comment by zonyitoo** [comment]
> But please notice, when you are testing, you are sending `add: {"server_port": 1080,"password":"aaa","mode":"tcp_and_udp"}`, but in this case ssmgr is sending `Add(ServerConfig { server_port: 17279, password: "2730792459", method: None, no_delay: None, plugin: None, plugin_opts: None, mode: None })`.

Well yes, but it won't have any differences in this case.

> However, the remove command `Remove(RemoveRequest { server_port: 17279 })` is the same (or I didn't notice the difference?)

Yes, it is the same, that's the strange part. I tried locally by sending `add` and `remove` repeatedly but still couldn't reproduce. Very anonying.

**Comment by zonyitoo** [comment]
Is there any chance that there is a future leak inside UDP association manager? Hmm, if that's true, it will be the cause of this issue.

**Comment by zonyitoo** [comment]
Please check this commit and verify with the nightly build.

THANK YOU for helping me finding this severe bug.

**Comment by RebelliousWhiz** [comment]
Problem confirm solved! Now UDP can be closed accordingly as expected!

Thank you zonyitoo, I am glad to be of help!
