### ISSUE TITLE
Reverse proxy?

### ISSUE THREAD

**Issue by riaqn** [shadowsocks/shadowsocks-rust#558]
Would it be possible to add reverse proxy to shadowsocks? This would be useful for people who use shadowsocks to torrent in countries of strict copyright laws.

Currently I'm using SSH reverse proxy which works fine, but I imagine shadowsocks with its new crypto algorithms could be lighter on my CPU.

**Comment by zonyitoo** [comment]
Just run `sslocal` with `--protocol tunnel`.

**Comment by riaqn** [comment]
Thanks! closing

**Comment by riaqn** [comment]
Reopening because I think what `ss-tunnel` achieves is not what I want.
What I want is to have ss server listen on a port, and forward all incoming connections to ss client, who then forward the connections to a specified address and port.

**Comment by zonyitoo** [comment]
A ssserver forwards connections to ssclient? I couldn’t understand what exactly you want. Could you elaborate your idea precisely?

**Comment by database64128** [comment]
I think https://github.com/fatedier/frp is what you want.

**Comment by riaqn** [comment]
@database64128 thanks - but it seems like frp still uses the usual TLS encryption which might be slower than the default of shadowsocks?
