### ISSUE TITLE
能否添加ffi支持

### ISSUE THREAD

**Issue by zhaowq32** [shadowsocks/shadowsocks-rust#559]
使用cbindgen导出C头文件中只有宏定义，没有具体的函数实现，能够添加对ffi的支持？

**Comment by zonyitoo** [comment]
Could you elaborate what exactly you want to do?

**Comment by zhaowq32** [comment]
I want shadowsocks to be called by C++ applications as a static library.

**Comment by zonyitoo** [comment]
How to call async functions from c++?

**Comment by zhaowq32** [comment]
I don't know enough about rust. Maybe need a wrapper.

**Comment by zonyitoo** [comment]
I don’t think so. It would be very complicated when crossing language boundary.

I would recommend to run as a subprocess and then communicate with pipes if you really wants to call it from c++

**Comment by zhaowq32** [comment]
```
//config is the configuration information in json format, obtained from c++
fn start(config: String) {
    // parse config
    runtime.block_on(async move {
        let abort_signal = monitor::create_signal_monitor();
        let server = run_local(config);

        tokio::pin!(abort_signal);
        tokio::pin!(server);

        match future::select(server, abort_signal).await {
            // Server future resolved without an error. This should never happen.
            Either::Left((Ok(..), ..)) => panic!("server exited unexpectly"),
            // Server future resolved with error, which are listener errors in most cases
            Either::Left((Err(err), ..)) => panic!("aborted with {}", err),
            // The abort signal future resolved. Means we should just exit.
            Either::Right(_) => (),
        }
    });
}
```

**Comment by zonyitoo** [comment]
Aha, that’s a good idea. Then you can just add this `fn start` in your project and expose it as FFI.

**Comment by zhaowq32** [comment]
Thank you for your help.

**Comment by cielpy** [comment]
> Is this feasible?
> 
> ```
> //config is the configuration information in json format, obtained from c++
> fn start(config: String) {
>     // parse config
>     runtime.block_on(async move {
>         let abort_signal = monitor::create_signal_monitor();
>         let server = run_local(config);
> 
>         tokio::pin!(abort_signal);
>         tokio::pin!(server);
> 
>         match future::select(server, abort_signal).await {
>             // Server future resolved without an error. This should never happen.
>             Either::Left((Ok(..), ..)) => panic!("server exited unexpectly"),
>             // Server future resolved with error, which are listener errors in most cases
>             Either::Left((Err(err), ..)) => panic!("aborted with {}", err),
>             // The abort signal future resolved. Means we should just exit.
>             Either::Right(_) => (),
>         }
>     });
> }
> ```

I have a use case like yours, could you share the code? I'm not familiar with Rust :(
