### ISSUE TITLE
provide shadowsocks-rust docker image?

### ISSUE THREAD

**Issue by woodgear** [shadowsocks/shadowsocks-rust#570]

**Comment by zonyitoo** [comment]
What do you need inside that docker image?

**Comment by kallydev** [comment]
> What do you need inside that docker image?

For those familiar with Docker, this will make it easier than `systemd` to install, uninstall, update, and auto restart.

Feel free to assign this issue to me if we need it. I can help implement an auto build and release process for `multi-arch` Docker images based on `GitHub Actions`.

**Comment by zonyitoo** [comment]
Excellent. Also Github also have provided a Docker hub for uploading.
