### ISSUE TITLE
[Feature Request] Add Unix Domain Socket support

### ISSUE THREAD

**Issue by gubiao** [shadowsocks/shadowsocks-rust#576]
Is it possible to add Unix Domain Socket support?
I use Cloudflare CDN + Nginx(TLS) + Shadowsocks-rust + v2ray-plugin (websocket).
Nginx proxy my website and ss+v2ray-plugin at the same time.
It would be great if shadowsocks-rust could add UDS support.
Many people told me that UDS is faster than a local loopback connection. I also found this:
https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance

**Comment by zonyitoo** [comment]
Where to add UDS support? Could you describe your request more precisely?

**Comment by gubiao** [comment]
> Where to add UDS support? Could you describe your request more precisely?

Add UDS support to the ssserver program.

My current Nginx configuration:
...
upstream myssserver {
        server 127.0.0.1:8000;
        keepalive 32;
        keepalive_requests 2000;
        keepalive_time 7d;
        keepalive_timeout 7d;
    }
...
location /haha {
            proxy_pass http://myssserver;
            proxy_socket_keepalive on;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_next_upstream off;
            proxy_redirect off;
            proxy_connect_timeout 5s;
            proxy_send_timeout 7d;
            proxy_read_timeout 7d;
            proxy_buffering off;
            proxy_request_buffering off;
            keepalive_requests 2000;
            keepalive_time 7d;
            keepalive_timeout 7d;
        }
...

If ssserver can provide UDS support, then Nginx can communicate with ssserver through UDS:
    upstream myssserver {
        server unix:/myssserver.socks;
        ....
    }

Communicating through the TCP connection of the network loopback address will result in a large number of 127.0.0.1->127.0.0.1 TCP connections in the operating system.

**Comment by zonyitoo** [comment]
It is impossible. Because the data flow is:

```
CLIENT -> nginx -> v2ray-plugin -> ssserver -> REMOTE
```

It doesn't matter whether `ssserver` support UDS or not, because it is communicating with `v2ray-plugin`.

You have to make `v2ray-plugin` support UDS to fulfill your goal.

**Comment by gubiao** [comment]
> ```
> CLIENT -> nginx -> v2ray-plugin -> ssserver -> REMOTE
> ```
> 
Thank you for your clarification, I have always thought that the request processing flow is:
CLIENT -> nginx -> ssserver -> v2ray-plugin -> REMOTE
