### ISSUE TITLE
使用kcptun插件退出了

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#585]
启动没几秒就自动退出了，关闭kcptun插件后就正常。
这是我的客户端配置
```json
{
    "locals": [
        {
            "protocol": "redir",
            "mode": "tcp_and_udp",
            "tcp_redir": "tproxy",
            "udp_redir": "tproxy",
            "local_address": "127.0.0.1",
            "local_port": 60080,
            "local_udp_address": "127.0.0.1",
            "local_udp_port": 60080
        },
        {
            "protocol": "dns",
            "local_address": "0.0.0.0",
            "local_port": 60053,
            "local_dns_address": "127.0.0.1",
            "local_dns_port": 53,
            "remote_dns_address": "1.1.1.1",
            "remote_dns_port": 53
        }
    ],
    "servers": [
        {
            "disabled": false,
            "address": "172.245.8.20",
            "port": 33277,
            "mode": "tcp_and_udp",
            "method": "none",
            "password": "admin",
            "plugin": "",
            "plugin_opts": "",
            "timeout": 7200,
            "tcp_weight": 0.1,
            "udp_weight": 1.0,
        },
        {
            "disabled": true,
            "address": "172.245.8.20",
            "port": 67,
            "mode": "tcp_and_udp",
            "method": "none",
            "password": "admin",
            "plugin": "kcptun-plugin",
            "plugin_opts": "mode=fast;dscp=46;crypt=none;parityshard=1;rcvwnd=2048;key=admin;sndwnd=2048;mtu=1400;datashard=10;nocomp",
            "timeout": 7200,
            "tcp_weight": 1.0,
            "udp_weight": 0.1,
        },
        {
            "disabled": false,
            "address": "1.0.0.0",
            "port": 80,
            "mode": "tcp_and_udp",
            "method": "none",
            "password": "N2QxZmYwMWYtOGY1",
            "plugin": "v2ray-plugin",
            "plugin_opts": "path=e6a6c65465fb19dc2378fafc7d18199463554c33;host=mikutap.ml",
            "timeout": 7200,
            "tcp_weight": 1.0,
            "udp_weight": 0.1,
        },
    ],
    "udp_timeout": 300,
    "udp_max_associations": 512,
    "dns": "cloudflare",
    "mode": "tcp_and_udp",
    "no_delay": false,
    "keep_alive": 15,
    "nofile": 10240,
    "ipv6_first": false
}
```
出错信息
```Bash
root@OpenWrt:~# sslocal -v --log-without-time --acl /tmp/bypass-china.acl --config /tmp/ss.json
INFO  [23307:3069841408] [sslocal] shadowsocks 1.11.3
DEBUG [23307:3069841408] [shadowsocks::plugin] started plugin "kcptun-plugin" on 127.0.0.1:45371 <-> 172.245.8.20:67 (23310)
DEBUG [23307:3069841408] [shadowsocks::plugin] started plugin "v2ray-plugin" on 127.0.0.1:43051 <-> 1.0.0.0:80 (23311)
2021/08/03 12:29:58 version: 20210803
2021/08/03 12:29:58 initiating key derivation
2021/08/03 12:29:58 listen udp 172.245.8.20:67: bind: cannot assign requested address
github.com/xtaci/kcp-go.ListenWithOptions
        /home/runner/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.20+incompatible/sess.go:974
main.main.func1
        /home/runner/go/pkg/mod/github.com/shadowsocks/kcptun@v0.0.0-20201019020523-ad6f28038b21/server/main.go:454
github.com/urfave/cli.HandleAction
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
github.com/urfave/cli.(*App).Run
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286
main.main
        /home/runner/go/pkg/mod/github.com/shadowsocks/kcptun@v0.0.0-20201019020523-ad6f28038b21/server/main.go:509
runtime.main
        /tmp/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:225
runtime.goexit
        /tmp/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm.s:841
2021/08/03 12:29:58 V2Ray 4.41.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.6 linux/arm)
2021/08/03 12:29:58 A unified platform for anti-censorship.
2021/08/03 12:29:58 [Warning] V2Ray 4.41.0 started
2021/08/03 12:29:58 127.0.0.1:52008 accepted tcp:127.0.0.1:0
DEBUG [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] failed to check TCP server 172.245.8.20:67, error: Connection refused (os error 111)
2021/08/03 12:29:59 127.0.0.1:48294 accepted tcp:127.0.0.1:0
INFO  [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] chose best TCP server 1.0.0.0:80
INFO  [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] chose best UDP server 172.245.8.20:33277
DEBUG [23307:3069841408] [shadowsocks::plugin] terminating plugin process None, local_addr: 127.0.0.1:45371
ERROR [23307:3069841408] [shadowsocks_service::local] plugin exited with status: exit status: 255
DEBUG [23307:3069841408] [shadowsocks::plugin] terminating plugin process Some(23311), local_addr: 127.0.0.1:43051
DEBUG [23307:3069841408] [shadowsocks::plugin] plugin process 23311 is terminated gracefully with status: ExitStatus(ExitStatus(0))
server exited unexpectly
root@OpenWrt:~#
```

**Comment by yiguihai** [comment]
换别的端口也一样退出已确定不是我的配置问题

**Comment by zonyitoo** [comment]
This is not related to this project, please open an issue to your kcptun plugin.

**Comment by yiguihai** [comment]
> 启动没几秒就自动退出了，关闭kcptun插件后就正常。
> 这是我的客户端配置
> 
> ```json
> {
>     "locals": [
>         {
>             "protocol": "redir",
>             "mode": "tcp_and_udp",
>             "tcp_redir": "tproxy",
>             "udp_redir": "tproxy",
>             "local_address": "127.0.0.1",
>             "local_port": 60080,
>             "local_udp_address": "127.0.0.1",
>             "local_udp_port": 60080
>         },
>         {
>             "protocol": "dns",
>             "local_address": "0.0.0.0",
>             "local_port": 60053,
>             "local_dns_address": "127.0.0.1",
>             "local_dns_port": 53,
>             "remote_dns_address": "1.1.1.1",
>             "remote_dns_port": 53
>         }
>     ],
>     "servers": [
>         {
>             "disabled": false,
>             "address": "172.245.8.20",
>             "port": 33277,
>             "mode": "tcp_and_udp",
>             "method": "none",
>             "password": "admin",
>             "plugin": "",
>             "plugin_opts": "",
>             "timeout": 7200,
>             "tcp_weight": 0.1,
>             "udp_weight": 1.0,
>         },
>         {
>             "disabled": true,
>             "address": "172.245.8.20",
>             "port": 67,
>             "mode": "tcp_and_udp",
>             "method": "none",
>             "password": "admin",
>             "plugin": "kcptun-plugin",
>             "plugin_opts": "mode=fast;dscp=46;crypt=none;parityshard=1;rcvwnd=2048;key=admin;sndwnd=2048;mtu=1400;datashard=10;nocomp",
>             "timeout": 7200,
>             "tcp_weight": 1.0,
>             "udp_weight": 0.1,
>         },
>         {
>             "disabled": false,
>             "address": "1.0.0.0",
>             "port": 80,
>             "mode": "tcp_and_udp",
>             "method": "none",
>             "password": "N2QxZmYwMWYtOGY1",
>             "plugin": "v2ray-plugin",
>             "plugin_opts": "path=e6a6c65465fb19dc2378fafc7d18199463554c33;host=mikutap.ml",
>             "timeout": 7200,
>             "tcp_weight": 1.0,
>             "udp_weight": 0.1,
>         },
>     ],
>     "udp_timeout": 300,
>     "udp_max_associations": 512,
>     "dns": "cloudflare",
>     "mode": "tcp_and_udp",
>     "no_delay": false,
>     "keep_alive": 15,
>     "nofile": 10240,
>     "ipv6_first": false
> }
> ```
> 
> 出错信息
> 
> ```shell
> root@OpenWrt:~# sslocal -v --log-without-time --acl /tmp/bypass-china.acl --config /tmp/ss.json
> INFO  [23307:3069841408] [sslocal] shadowsocks 1.11.3
> DEBUG [23307:3069841408] [shadowsocks::plugin] started plugin "kcptun-plugin" on 127.0.0.1:45371 <-> 172.245.8.20:67 (23310)
> DEBUG [23307:3069841408] [shadowsocks::plugin] started plugin "v2ray-plugin" on 127.0.0.1:43051 <-> 1.0.0.0:80 (23311)
> 2021/08/03 12:29:58 version: 20210803
> 2021/08/03 12:29:58 initiating key derivation
> 2021/08/03 12:29:58 listen udp 172.245.8.20:67: bind: cannot assign requested address
> github.com/xtaci/kcp-go.ListenWithOptions
>         /home/runner/go/pkg/mod/github.com/xtaci/kcp-go@v5.4.20+incompatible/sess.go:974
> main.main.func1
>         /home/runner/go/pkg/mod/github.com/shadowsocks/kcptun@v0.0.0-20201019020523-ad6f28038b21/server/main.go:454
> github.com/urfave/cli.HandleAction
>         /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524
> github.com/urfave/cli.(*App).Run
>         /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:286
> main.main
>         /home/runner/go/pkg/mod/github.com/shadowsocks/kcptun@v0.0.0-20201019020523-ad6f28038b21/server/main.go:509
> runtime.main
>         /tmp/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64/staging_dir/hostpkg/lib/go-cross/src/runtime/proc.go:225
> runtime.goexit
>         /tmp/openwrt-sdk-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64/staging_dir/hostpkg/lib/go-cross/src/runtime/asm_arm.s:841
> 2021/08/03 12:29:58 V2Ray 4.41.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.6 linux/arm)
> 2021/08/03 12:29:58 A unified platform for anti-censorship.
> 2021/08/03 12:29:58 [Warning] V2Ray 4.41.0 started
> 2021/08/03 12:29:58 127.0.0.1:52008 accepted tcp:127.0.0.1:0
> DEBUG [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] failed to check TCP server 172.245.8.20:67, error: Connection refused (os error 111)
> 2021/08/03 12:29:59 127.0.0.1:48294 accepted tcp:127.0.0.1:0
> INFO  [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] chose best TCP server 1.0.0.0:80
> INFO  [23307:3069841408] [shadowsocks_service::local::loadbalancing::ping_balancer] chose best UDP server 172.245.8.20:33277
> DEBUG [23307:3069841408] [shadowsocks::plugin] terminating plugin process None, local_addr: 127.0.0.1:45371
> ERROR [23307:3069841408] [shadowsocks_service::local] plugin exited with status: exit status: 255
> DEBUG [23307:3069841408] [shadowsocks::plugin] terminating plugin process Some(23311), local_addr: 127.0.0.1:43051
> DEBUG [23307:3069841408] [shadowsocks::plugin] plugin process 23311 is terminated gracefully with status: ExitStatus(ExitStatus(0))
> server exited unexpectly
> root@OpenWrt:~#
> ``` 
@madeye
