### ISSUE TITLE
ERROR failed to daemonize, unable to lock pid file

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#587]
做成脚本后启动后是不是的出现这个提示
```Bash
ERROR failed to daemonize, unable to lock pid file
INFO  shadowsocks 1.11.3
2021/08/05 13:23:26 version: 20210804
2021/08/05 13:23:26 initiating key derivation
2021/08/05 13:23:26 listening on: 127.0.0.1:37049
2021/08/05 13:23:26 nodelay parameters: 0 30 2 1
2021/08/05 13:23:26 sndwnd: 2048 rcvwnd: 2048
2021/08/05 13:23:26 compression: false
2021/08/05 13:23:26 mtu: 1400
2021/08/05 13:23:26 datashard: 10 parityshard: 1
2021/08/05 13:23:26 acknodelay: false
2021/08/05 13:23:26 dscp: 46
2021/08/05 13:23:26 sockbuf: 4194304
2021/08/05 13:23:26 keepalive: 10
2021/08/05 13:23:26 conn: 1
2021/08/05 13:23:26 autoexpire: 10
2021/08/05 13:23:26 scavengettl: 600
2021/08/05 13:23:26 snmplog:
2021/08/05 13:23:26 snmpperiod: 60
2021/08/05 13:23:26 quiet: false
2021/08/05 13:23:26 vpn: false
2021/08/05 13:23:26 connection: 0.0.0.0:58336 -> 172.245.8.20:67
^CINFO  received SIGINT, exiting
```
报错后程序没有退出还在前台运行
导致后面的命令被没有被执行

**Comment by zonyitoo** [comment]
```
ERROR failed to daemonize, unable to lock pid file
```

The error is very clear. The pid file was locked by someone else or your problem didn't have enough privilege to lock the file.

**Comment by yiguihai** [comment]
> ```
> ERROR failed to daemonize, unable to lock pid file
> ```
> 
> The error is very clear. The pid file was locked by someone else or your problem didn't have enough privilege to lock the file.

我用的也是root权限
这个错误频繁出现在重启脚本也就是关闭sslocal再开启的时候
我在关闭脚本时的就读了一下如果这个文件，这也影响的话我无话可说了
```Bash
read sspid </tmp/ss.pid
```
其它的都是由sslocal自己读写，太玄学了跟抽奖一样

**Comment by zonyitoo** [comment]
Did your restart script wait until the existing `sslocal` process have exited and then start a new one?

The `daemonize` crate will [lock the pid file with `flock`](https://github.com/knsd/daemonize/blob/f7be28efa1b4a70e43bb37b5f4ff4d664992edca/daemonize/src/lib.rs#L518-L521) after creating new forks, which is for ensuring singleton.

You may try to add a `sleep 2` after `kill` and see if it fixes your problem.

**Comment by yiguihai** [comment]
> Did your restart script wait until the existing `sslocal` process have exited and then start a new one?
> 
> The `daemonize` crate will [lock the pid file with `flock`](https://github.com/knsd/daemonize/blob/f7be28efa1b4a70e43bb37b5f4ff4d664992edca/daemonize/src/lib.rs#L518-L521) after creating new forks, which is for ensuring singleton.
> 
> You may try to add a `sleep 2` after `kill` and see if it fixes your problem.

循环测试执行了一百次没有报错这也算不是办法的办法吧。好像用wait等待也可以

**Comment by zonyitoo** [comment]
`sleep 2` is commonly used in production environment, which is a effective solution used by many operators.
