### ISSUE TITLE
[Feature] Username and password authentication for sock5

### ISSUE THREAD

**Issue by driftluo** [shadowsocks/shadowsocks-rust#589]
Here is a simple implementation:

https://github.com/driftluo/shadowsocks-rust/tree/add-username-password-authentication

The problem now is that it is really not good to set these two parameters in from the config, so the implementation is getting them through environment variables, any better ideas, please? And is there any interest in merging such a modification?

**Comment by driftluo** [comment]
I did not find a suitable place to put these two values in the config of shadowsocks

**Comment by zonyitoo** [comment]
shadowsocks' `sslocal` must be running inside a trusted local environment, which is unnecessary to have authentication in this environment.

**Comment by database64128** [comment]
Personally I don't need this feature. But I think it's something nice to have. Some users might want it in scenarios like office LAN.

**Comment by alaz** [comment]
I agree that it would be nice to have [RFC 1929](https://www.rfc-editor.org/rfc/rfc1929) supported. People may have some use cases where this is required.

**Comment by zonyitoo** [comment]
It is already supported in recent releases.

**Comment by alaz** [comment]
My bad, I missed it yesterday. Just found [the config](https://github.com/shadowsocks/shadowsocks-rust?tab=readme-ov-file#socks5-authentication-configuration) in the README. Thank you
