### ISSUE TITLE
cargo install is too clumsy, and sometimes fail because the `openssl-devel` 

### ISSUE THREAD

**Issue by cssivision** [shadowsocks/shadowsocks-rust#59]
i think we should produce a static linked binary, so that we are ready to distribute it to `all` linux distributions.

Is it necessary?  i think i can produce PR to do this. @zonyitoo

**Comment by zonyitoo** [comment]
Is it possible to make **one** static linked library for **all** linux destribution??

**Comment by cssivision** [comment]
yes, though the process is verbose..., especially build openssl as a static linked library. suggest you use this https://github.com/emk/rust-musl-builder, and be carefully of the openssl issues https://github.com/emk/rust-musl-builder/issues/21, i think i can produce a pr to do this.

**Comment by zonyitoo** [comment]
Sure. But you have to keep the original build process, which will uses the system-wide openssl and libsodium.

**Comment by cssivision** [comment]
i think i can fix this.

**Comment by TheWaWaR** [comment]
We could learn from `rustup` how to do static link openssl : https://github.com/rust-lang-nursery/rustup.rs/blob/master/ci/run-docker.sh#L166-L193

I tested in [my project](https://github.com/TheWaWaR/simple-http-server/blob/master/.ci/build-linux-static.sh), works well.

**Comment by cssivision** [comment]
successfully build a static linked binary, the difficulty is building libsodium as a static linked library.

it's seems that crate `sodiumoxide` has a bug for build a static library, the env variable `SODIUM_LIB_DIR ` is alway wrong. 

i hardcode the static linked library path to bypass this problem.  i will also fire a pr to `sodiumoxide`.

<img width="531" alt="screen shot 2017-07-25 at 21 11 15" src="https://user-images.githubusercontent.com/8855275/28574005-2ee3b2de-717f-11e7-857d-562e1b080411.png">

**Comment by cssivision** [comment]
i build everything from scratch, it has nothing to do with `sodiumoxide`. i make a mistake in the env variable the first time, and `cargo` cache the result for me, when i built without cache, i works fine. i don't know whether this is a bug in cargo.

**Comment by zonyitoo** [comment]
Merged. Closing this issue.

**Comment by zonyitoo** [comment]
I have added a helper script: https://github.com/shadowsocks/shadowsocks-rust/blob/master/build/build-release . Please help to check if it works in your environment. @cssivision

**Comment by cssivision** [comment]
yes, it works well in my centos 7 server.
