### ISSUE TITLE
Linux Service Support

### ISSUE THREAD

**Issue by Prajwal-Koirala** [shadowsocks/shadowsocks-rust#592]
Hello,
Let me begin by stating that this is far superior to the `C` version of shadowsocks; however, the present issue I am having with this is the service in Linux; I was wondering if I would have to manually construct the service file or if there is anything else I am overlooking.

**Comment by DuckSoft** [comment]
You may find systemd service files here: https://github.com/shadowsocks/shadowsocks-rust/tree/master/debian
Or it's always fine to compose one yourself.

**Comment by zonyitoo** [comment]
You can make a systemd service file as @DuckSoft suggested. Or you can use other famous process managers, like supervisor, initd, procd on OpenWRT...

Or maybe you can just add `--daemonize` into command line arguments.
