### ISSUE TITLE
Please allow to  get current connected client IP.

### ISSUE THREAD

**Issue by videni** [shadowsocks/shadowsocks-rust#612]
we can get the IP by `ss` command,   however,  let's assume we got 1000 users,  then we need to run `ss` command 1000 times within a few seconds, our CPU would burn  quickly. Can add another API to get current connected IP? so we can  simply request it from ssmanager directly.  any idea please? I'm happy to add it if you guys like.

**Comment by zonyitoo** [comment]
I couldn't understand what's the API for? Why would you need the current connected IP? Could you make a detailed example?

**Comment by videni** [comment]
# Case 1
we need to know if an ss account is used by lots users,so we can disable it. 

# Case 2

we can use this info to decide current online devices, though not 100% sure, but enough for our case.

**Comment by zonyitoo** [comment]
I don’t think `ssserver` has data usage statistic by users feature.

**Comment by videni** [comment]
yes, so I suggest to add a new API, like the ping API.

**Comment by zonyitoo** [comment]
1. `ssserver` is designed as a single server instance.
2. `ssmanager` is designed for running multiple server instances and it comes with various APIs, including a `ping` API that can get all data usage statistics for each instances.

**Comment by videni** [comment]
except current connected IP if I am right.

**Comment by zonyitoo** [comment]
What is “current connected IP”?

**Comment by videni** [comment]
something like this, I think
```
pub struct FlowStat {
    tx: FlowCounter,
    rx: FlowCounter,
    client_ip: Option<std::net::SocketAddr>,
}
```

Then we can query the connected client IP using the Ping command. I personally don't like the way [Anankke/shadowsocks-mod](https://github.com/Anankke/shadowsocks-mod/)  used to handle client ip, which extends the python version shadowsocks by copying all source code into its lib.  some obstacles must exist, so the author has to do this way.

**Comment by videni** [comment]
It seems saving client_addr into FlowStat is not a good idea, because a ss port might be used by serveral users at the same time.

**Comment by zonyitoo** [comment]
`ssmanager` should already be a good idea about how to manage multiple users.

**Comment by videni** [comment]
@zonyitoo ,  indeed, we can manage multiple users, but we can't get IP of a client(such as android client)  on ssmanager.

**Comment by zonyitoo** [comment]
Why would you care about client's IP? If a user exceeded data quota, then just disable that port completely.

**Comment by videni** [comment]
our user may expose their account publicly but  quota not exceed. please check the use case I list above please.

**Comment by zonyitoo** [comment]
I don't think it is easy to add client IP level data flow statistic in the code. Do you have a solution that doesn't envolve too much modifications?

**Comment by kallydev** [comment]
> Why would you care about client's IP? If a user exceeded data quota, then just disable that port completely.

I guess he might want to get the client IP and write it to database for analyzing abuse of multiple shared accounts, crawler accounts, etc.

**Comment by dev4u** [comment]
这种功能，更多是应用在机场服务的场景上。但是ss因为某些原因，通常需要套一层tls的插件。所以ss能读取的客户端ip就是本地ip，是无意义于做其他业务的。

**Comment by videni** [comment]
@zonyitoo , no need to record  data flow stats of every client IP, we just need to get the client IP that connected to a `ssserver`, so the FlowStat still keep it is.

**Comment by videni** [comment]
@ dev4u , I don't understand what is wrong with tls plugin.

1. ssserver is used behind a proxy and the proxy doesn't forward its client IP.   (this is handled by us)
2. the user client  connects our ssserver using a proxy and the proxy doesn't forward its client IP, we can't get reall ip of client. (Nothing we can do)

both  can happen, as I said, we need a mostly likely answer, not 100% sure,

**Comment by zonyitoo** [comment]
If you are using plugin, then the client IP that `ssserver` receives is the plugin's local IP, for most cases is `127.0.0.1`.

**Comment by kallydev** [comment]
@videni I have an idea, HAProxy supports [port range reverse proxy](https://www.haproxy.com/documentation/hapee/latest/configuration/binds/syntax/) and [log forwarding](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#3.10). This solution may help you to implement it without modifying shadowsocks-rust.

**Comment by zonyitoo** [comment]
I would personally suggest you to do that in the top level of your servers. A reverse proxy that @kallydev suggested should be a good solution.

**Comment by videni** [comment]
@kallydev  @zonyitoo ,  thanks,  HAProxy may works, but the tech stack is a little complex, because we need to a dedicated proxy server(HAProxy) ,  also need to add flow control to HAProxy itself. The [https://github.com/cbeuw/Cloak](https://github.com/cbeuw/Cloak) might be a good alternative.  if we use this plugin, then 

1.  Handle PROXY, FLOW-CONTROL, user  management in this plugin natively， simpler infrastructure.
```
CLIENT -> [Cloak PLUGIN -> ssservers ] -> TARGET
```
1. No need to use ssmanager anymore, because Cloak handles multiple users internally.
2. We can control flow in this plugin easily.

This is preferred way, but this plugin also need  client side change, currently, it seems not too many clients embeded the cloak client plugin, it is hard to let our user to do this job.

**Comment by videni** [comment]
closed,  as it is best to  implement at a  proxy,  thanks again to help me out.

**Comment by kallydev** [comment]
@videni I have written a simple shadowsocks gateway framework. It doesn't currently support UDP forwarding, I plan to support it at a later date.

https://github.com/kallydev/shadowsocks-gateway

**Comment by videni** [comment]
@kallydev  good to know, can you share me some ideas you design the gateway? 

execept TCP, UDP traffic relay, how to deploy it?

## Option 1. A dedicated server to deploy  before all ss-server nodes?

 A central place to relay all traffic,  the proxy server traffic will be the total of all ss-nodes being proxied. 

## Option 2.  Deploy it alongside with  per ss-server node? 

Any ss-server node serves traffic directly,  no single  bottleneck.  we would purchase VMs from cloud providers, the traffic  of each VM is costly, so I prefer this way.   If this way we may have this flow

```
Client  -> Gateway -> [Plugin] -> ss-server -> Target
```
the `Gateway -> [Plugin] -> ss-server `  part is on the same VM.  I am not sure what the performance will be. I am implementing a Rust version, we'll see it soon.

**Comment by kallydev** [comment]
@videni I think Option B is the best. Option A's gateway will carry all the traffic. if it is down, then all sservers will be unavailable. If you choose option B, you can deploy the gateway to 0.0.0.0 and the sserver to 127.0.0.1, you just need to enable the `SO_REUSEADDR` option for the socket.

You seem to be concerned about the performance of the gateway, I suggest you add `TFO` and `zero-copy` support to it, they can reduce latency as well as improve performance for it. [HAProxy](http://www.haproxy.org/) is a good reference.

**Comment by kallydev** [comment]
If I remember correctly, the original ssserver will only return data if the password is correct. So even though the gateway works at layer 4, it can still tell if the password is correct by watching if the ssserver response to the connection.

**Comment by videni** [comment]
@kallydev  thanks you so much, these clues are very useful for me.
