### ISSUE TITLE
Crate `bloomfilter` v1.0.7 breaks the build.

### ISSUE THREAD

**Issue by spacemeowx2** [shadowsocks/shadowsocks-rust#615]
Today I encountered a compilation error while compiling a crate that depends on shadowsocks (without Cargo.lock). Then I found out that the `bloomfilter` dependency had introduced breaking change in a minor release yesterday.

```
error[E0599]: no function or associated item named `new_for_fp_rate` found for struct `Bloom<_>` in the current scope
  --> /Users/space/.cargo/registry/src/github.com-1ecc6299db9ec823/shadowsocks-1.11.1/src/context.rs:54:24
   |
54 |                 Bloom::new_for_fp_rate(item_count, fp_p),
   |                        ^^^^^^^^^^^^^^^ function or associated item not found in `Bloom<_>`
```

https://github.com/shadowsocks/shadowsocks-rust/blob/ca85b6a65be821c66554f23ebb8dc04224a27861/crates/shadowsocks/src/context.rs#L53-L54

Related issue: https://github.com/jedisct1/rust-bloom-filter/issues/29

**Comment by IceCodeNew** [comment]
Duplicated with #614
