### ISSUE TITLE
tun udp tcp_and_udp cause tun's self.udp panicked

### ISSUE THREAD

**Issue by iamwwc** [shadowsocks/shadowsocks-rust#616]
Here are my vscode launch.json used for debugging
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'sslocal'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=sslocal",
                    "--package=shadowsocks-rust"
                ],
                "filter": {
                    "name": "sslocal",
                    "kind": "bin"
                }
            },
            "env": {
                "RUST_BACKTRACE": "1"
            },
            // ip tuntap add mode tun tun0
            // ifconfig tun0 inet 10.255.0.1 netmask 255.255.255.0 up
            // --outbound-bind-interface lo0 --tun-interface-name tun0
            "args": ["--config", "${workspaceFolder}/examples/config.json", "--protocol", "tun", "--tun-interface-name", "tun0", "--outbound-bind-interface", "eth0", "-v"],
            "cwd": "${workspaceFolder}"
        },
    ]
}
```

It works until I have rebased your master codes. It's seems https://github.com/shadowsocks/shadowsocks-rust/commit/288180f465163aaf7d5ba81ee965882fb1531381#diff-2d7d2001059d7fca7a161eff75d70d02dd32a1b5c26dfaa5824b99017ee3197aR143 control UDP but I don't know how to pass `mode: "tcp_and_udp"` from cli arguments, and finally cause unwrap panicked at https://github.com/shadowsocks/shadowsocks-rust/commit/288180f465163aaf7d5ba81ee965882fb1531381#diff-2d7d2001059d7fca7a161eff75d70d02dd32a1b5c26dfaa5824b99017ee3197aR204

And I have try use `config_ext.json`, But there is not configuration field to set `tun-interface-name` from config file, It only can be set by cli args `--tun-interface-name` https://github.com/shadowsocks/shadowsocks-rust/blob/288180f465163aaf7d5ba81ee965882fb1531381/bin/sslocal.rs#L176

It's deadlocked now

Here are error messages.
```
INFO  [3445:140737350429184] [shadowsocks_service::local::tun] shadowsocks tun device tun0, address 10.255.0.1, netmask 255.255.255.0, mtu 1500, mode TcpOnly
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/codes/shadowsocks-rust/crates/shadowsocks-service/src/local/tun/mod.rs:204:44
```

There are lacking detail config about how to use tun and other functions. In order to debugging shadowsocks tun, I have to write a `Debug-instruction.md`, some of instruction may be wrong, spent a lot of time to debug

**Comment by zonyitoo** [comment]
Check the [Configuration](https://github.com/shadowsocks/shadowsocks-rust#configuration) section in README.md about how to set `tun_interface_name` other related arguments.

```
INFO  [3445:140737350429184] [shadowsocks_service::local::tun] shadowsocks tun device tun0, address 10.255.0.1, netmask 255.255.255.0, mtu 1500, mode TcpOnly
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/codes/shadowsocks-rust/crates/shadowsocks-service/src/local/tun/mod.rs:204:44
```

This panic is a bug. I am going to fix it.
