### ISSUE TITLE
使用安卓客户端连接时，vps的ss进程会被强制终止

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-rust#62]
服务端系统：Debian 8
ss-rust版本：1.6.1

使用的加密：aes-256-gcm

桌面系统：win7sp1 64
桌面客户端版本：shadowsocks-windows 4.0.5

安卓系统：Android 5.1.1
安卓客户端版本：影梭 4.2.3

具体出现的问题：
在使用win客户端连接使用时，能正常使用
使用安卓客户端连接使用时，可能会在1～5分钟之内断开连接，登录vps检查ss进程时，发现ss进程已经消失

补充错误日志：
![t3 6 2l9u4 jesbsgl2 e01](https://user-images.githubusercontent.com/10991795/29748512-dbacd6c8-8b4a-11e7-84ec-dfdc6b6c956e.png)
打码部分为我的ip

8.28补充：我关闭了服务端的udp转发，然后安卓客户端连接就不再出现上述现象了

**Comment by cssivision** [comment]
this kind of errors  is caused is mainly by wrong encryption method or wrong password, maybe need a nice `error handler`(for example, print the log) instead of panic.

**Comment by zonyitoo** [comment]
The last log

> Invalid Address type 243

indicates that server failed to decode that UDP packet properly.

I should fix this, it should not panic.

**Comment by zonyitoo** [comment]
@Aniark Please try the latest commit in master branch. It shouldn't crash.

**Comment by Aniark** [comment]
@zonyitoo  抱歉，鄙人才粗学浅，并不会编译git。我只会解压使用release里的已经编译的文件

by the way，安卓影梭客户端昨天更新到4.2.4，使用该版本后也没有出现上述问题

**Comment by zonyitoo** [comment]
@Aniark Check this out.

[shadowsocks-1.6.1-release.x86_64-unknown-linux-musl.tar.gz](https://github.com/shadowsocks/shadowsocks-rust/files/1262131/shadowsocks-1.6.1-release.x86_64-unknown-linux-musl.tar.gz)

**Comment by cssivision** [comment]
wrong link, should be https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.6.1/shadowsocks-1.6.1-release.x86_64-unknown-linux-musl.tar.gz

**Comment by zonyitoo** [comment]
Hmm, Nope. The file I just uploaded is the latest build. @Aniark you should just download my link.

**Comment by Aniark** [comment]
@zonyitoo  链接点进去，是404 not found

**Comment by zonyitoo** [comment]
... fuc*, I will upload it again tonight.

**Comment by Aniark** [comment]
@zonyitoo 尝试过cargo build和docker build，最后因为报错太多和各种bug停止。我并非专业的程序员，没有专业的知识解决bug。我还是等待你的upload吧

**Comment by zonyitoo** [comment]
[shadowsocks-1.6.2-release.x86_64-unknown-linux-musl.tar.gz](https://github.com/shadowsocks/shadowsocks-rust/files/1263810/shadowsocks-1.6.2-release.x86_64-unknown-linux-musl.tar.gz)

@Aniark Check this out.

**Comment by Aniark** [comment]
@zonyitoo 测试了影梭4.2.3 & 4.2.4，均不再出现上述问题

**Comment by zonyitoo** [comment]
Thanks alot! This fix will be released in 1.6.2.
