### ISSUE TITLE
Load Balancer should respect individual "mode" setting for each server

### ISSUE THREAD

**Issue by bjin** [shadowsocks/shadowsocks-rust#620]
Shadowsocks with "SIP003" plugins supports only TCP connections, so it's common to setup a shadowsocks server, with TCP+SIP003 plugin listening on `PORT1`, and UDP on (possibly another) port `PORT2`.

I tried to set up `shadowsocks-rust` with multiple remote server configuration (see below), it somehow works but the load balancer keeps probing closed ports (`SERVER1:PORT2`, `SERVER2:PORT2` and `SERVER3:PORT1`), generating a lot of unnecessary traffics. 

It turns out that individual `mode` settings in `servers` config are ignored in load balancer.

```
{
    "servers": [
        {
            "server": "SERVER1",
            "server_port": PORT1,
            "password": "...",
            "method": "...",
            "plugin":"v2ray-plugin",
            "plugin_opts":"...",
	    "mode": "tcp_only"
        },
        {
            "server": "SERVER2",
            "server_port": PORT1,
            "password": "...",
            "method": "...",
            "plugin":"v2ray-plugin",
            "plugin_opts":"...",
	    "mode": "tcp_only"
        },
        {
            "server": "SERVER3",
            "server_port": PORT2,
            "password": "...",
            "method": "...",
	    "mode": "udp_only"
        }
    ],
    "mode": "tcp_and_udp"
}
```

Also, setting `tcp_weight` or `udp_weight` to `0.0` doesn't fix the issue.

**Comment by zonyitoo** [comment]
Yes, `sslocal` won't use the `mode` in the server's section.

If you set `"mode": "tcp_and_udp"` in the global scope, which indicates that the local server serves TCP & UDP for clients, so the servers must also be able to handle TCP & UDP, too.

**Comment by bjin** [comment]
Thanks for your quick fix. Please check [my comment](https://github.com/shadowsocks/shadowsocks-rust/commit/0b01621e2f9755876338d39b6b4c2de81a1fed9d#r56046766) to the commit above.
