### ISSUE TITLE
[Snap][Service]Service in snap can not work, because there is no default path of config file

### ISSUE THREAD

**Issue by yangyankui** [shadowsocks/shadowsocks-rust#621]
there is no default path of config file, 
therefore i can not use
`snap start shadowsocks-rust.ssserver-daemon`

debian 10, 
snap,
shadowsocks-rust  edge v1.11.2.r34.gf717984

**Comment by kallydev** [comment]
You can use arguments as a temporary solution. Ref #617.

```bash
shadowsocks-rust.ssserver -s "0.0.0.0:8388" -m "aes-256-gcm" -k "********"
```

**Comment by yangyankui** [comment]
Thank you!
Now, I am using
`shadowsocks-rust.ssserver -c config.json`
Is there any plan to support the default path?
Hope to add the function of the default path of config file.

**Comment by kallydev** [comment]
> Is there any plan to support the default path?
> Hope to add the function of the default path of config file.

Unfortunately, I don't have a build environment available for snap.

If you keep this issues open, other collaborators may be able to fix it.

**Comment by yangyankui** [comment]
Ok, Thank you!

**Comment by zonyitoo** [comment]
@DuckSoft

**Comment by kallydev** [comment]
I recommend to set the default path to `~/.config/shadowsocks-rust`.

**Comment by yangyankui** [comment]
shadowsocks-libev default path is `/etc/shadowsocks-libev/config.json`

**Comment by zonyitoo** [comment]
Why snap's daemon couldn't start with command line arguments?

**Comment by kallydev** [comment]
> shadowsocks-libev default path is `/etc/shadowsocks-libev/config.json`

The snap default is to allow the application to access only the path under `$HOME`, unless the application is installed using the `--classic` parameter.

**Comment by orisson003** [comment]
Same problem here. It seems snap version can't automatically read configure file via a default or designated path as in Shadowsocks-libev. Neither can it pass parameters to its daemon service when invoking systemctl. Both of these methods are not currently working in the snap store version.

**Comment by zonyitoo** [comment]
It should already supported in the latest version: https://github.com/shadowsocks/shadowsocks-rust/blob/1eff9b188341c5d829b956b467de90e4aba2c660/bin/common/config.rs#L7-L44

**Comment by kallydev** [comment]
The issue still exists with channels like stable and edge, but I can't see the snapcraft build logs. If edge is the latest image, then this issue may still be unresolved.

```bash
kallydev@ubuntu:~$ sudo snap install shadowsocks-rust --edge
shadowsocks-rust (edge) v1.12.2.r12.g1eff9b1 from DuckSoft installed
kallydev@ubuntu:~$ shadowsocks-rust.ssserver --version
shadowsocks 1.12.3
kallydev@ubuntu:~$ cat .config/shadowsocks-rust/config.json 
{
    "server": "127.0.0.1",
    "server_port": 8388,
    "password": "password",
    "method": "aes-256-gcm"
}
kallydev@ubuntu:~$ shadowsocks-rust.ssserver 
missing proxy servers, consider specifying it by --server-addr, --encrypt-method, --password command line option, or configuration file, check more details in https://shadowsocks.org/en/config/quick-guide.html
USAGE:
    ssserver [FLAGS] [OPTIONS]
```

**Comment by zonyitoo** [comment]
Please try again with the global configuration path `/etc/shadowsocks-rust/configuration.json`

**Comment by kallydev** [comment]
> Please try again with the global configuration path `/etc/shadowsocks-rust/config.json`

```
kallydev@ubuntu:~$ sudo vim /etc/shadowsocks-rust/config.json
kallydev@ubuntu:~$ shadowsocks-rust.ssserver
missing proxy servers, consider specifying it by --server-addr, --encrypt-method, --password command line option, or configuration file, check more details in https://shadowsocks.org/en/config/quick-guide.html
USAGE:
    ssserver [FLAGS] [OPTIONS]
```

This should be because the image does not have permission to read these configuration files.

```bash
kallydev@ubuntu:~$ shadowsocks-rust.ssserver -c .config/shadowsocks-rust/config.json 
loading config ".config/shadowsocks-rust/config.json", error while reading file, Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
kallydev@ubuntu:~$ shadowsocks-rust.ssserver -c /etc/
Display all 230 possibilities? (y or n)
kallydev@ubuntu:~$ shadowsocks-rust.ssserver -c /etc/shadowsocks-rust/config.json 
loading config "/etc/shadowsocks-rust/config.json", error while reading file, Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

~~I don't understand why snap's `home` permissions can't access `$HOME/.config/shadowsocks-rust/config.json`, but it can access `$HOME/config.json`.~~

Ref [https://snapcraft.io/docs/home-interface](https://snapcraft.io/docs/home-interface), only "non-hidden files" can be accessed.

> The home interface allows access to non-hidden files owned by the user in the user’s home ($HOME) directory where a user normally stores their personal files and documents.

```
kallydev@ubuntu:~$ shadowsocks-rust.ssserver -c ~/config.json 
2021-11-25T17:37:52.484976149-08:00 INFO  shadowsocks server 1.12.3 build 2021-11-25T16:55:04.297088322+00:00
2021-11-25T17:37:52.486770036-08:00 INFO  shadowsocks tcp server listening on 127.0.0.1:8388, inbound address 127.0.0.1:8388
```

**Comment by yangyankui** [comment]
It's OK.
shadowsock-rust v1.12.2.r12.g1eff9b1  edge
config.json :
{
    "address": "0.0.0.0",
    "port": 8388,
    "password": "password",
    "method": "chacha20-ietf-poly1305"
}
`root@localhost:~#snap install shadowsocks-rust --edge`
`root@localhost:~#cp config.json /var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json`
`root@localhost:~#snap start --enable shadowsocks-rust.ssserver-daemon`

**Comment by kallydev** [comment]
We can completely resolve the `$HOME/.config/shadowsocks-rust` permissions issue using https://snapcraft.io/docs/personal-files-interface, but this needs to be done via https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks.

So, I just reviewed the qv2ray's solution, then replaced `$HOME/.config/shadowsocks-rust/config.json` with `$HOME/snap/shadowsocks-rust/current/.config/shadowsocks-rust/config.json`, which successfully bypasses the issue.

```bash
kallydev@ubuntu:~$ shadowsocks-rust.ssserver -c ./snap/shadowsocks-rust/current/.config/shadowsocks-rust/config.json 
2021-11-25T18:08:11.951115534-08:00 INFO  shadowsocks server 1.12.3 build 2021-11-25T16:55:04.297088322+00:00
2021-11-25T18:08:11.952194068-08:00 INFO  shadowsocks tcp server listening on 127.0.0.1:8388, inbound address 127.0.0.1:8388
```
