### ISSUE TITLE
Google detects my ip

### ISSUE THREAD

**Issue by thegreathir** [shadowsocks/shadowsocks-rust#622]
Hi, I rent my individual server in Netherlands and I set up a shadowsocks-rust server on it. I also use sslocal and shadowsocks-android as client. After one month my ip is leaked and google sites are not available because sanctions. What did I wrong?

**Comment by kallydev** [comment]
Why do you think this is related to shadowocks? This is more likely to be caused by the IP reputation of your proxy server.

**Comment by zonyitoo** [comment]
I don't know. There are too many variables that would lead to this result.

**Comment by thegreathir** [comment]
Is there any advice to prevent Google to know my IP location?

**Comment by zonyitoo** [comment]
Maybe establish channel through a proxy chain?

**Comment by kallydev** [comment]
I see what you mean now. Google doesn't just get your location based on IP, it occasionally ignores IP and chooses to determine your location based on your account activity history.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/36319157/132848947-32532533-e201-427c-a2ac-6396063c2b45.png">

If you have installed Google framework, it can also get your location via GPS and your system timezone setting. I suggest you use FireFox to access the web version of google, and install [AdGuard](https://adguard.com/) and [Duckduckgo Privacy Essentials](https://duckduckgo.com/app) plugins to filter Google's trackers.

This won't solve the problem completely, but it will reduce the probability of Google getting your real IP through cross-site tracking script.

**Comment by thegreathir** [comment]
Thank you all for your suggestions,
Proxy chain is working and I put my shadowsocks server behind TOR. It's a bit slow but it seems there is no better solution...

**Comment by zonyitoo** [comment]
Reopen if you have other questions.
