### ISSUE TITLE
怎么在后台运行

### ISSUE THREAD

**Issue by coolicer** [shadowsocks/shadowsocks-rust#63]
直接下载了编译后的版本，ssserver -c ss.json 
是不是可以加个--daemon

**Comment by zonyitoo** [comment]
这不是这一个binary需要解决的问题。可解决的方法太多了
1. Supervisor
2. Systemd
3. Launchd
4. ...

**Comment by cssivision** [comment]
Systemd

**Comment by zonyitoo** [comment]
Ps. 如果用的是终端，你还可以直接

```bash
ssserver -c ss.json &
```

**Comment by coolicer** [comment]
我用supervor了

**Comment by coolicer** [comment]
@zonyitoo 顺便问问chacha20为什么不能用

**Comment by zonyitoo** [comment]
Ref: #61 由于一个sodium的库有问题导致的。

**Comment by coolicer** [comment]
怎么解决？
@zonyitoo

**Comment by zonyitoo** [comment]
暂无法解决，sodiumoxide的作者似乎已经弃坑。我可能考虑换一个libsodium的库，或者直接用我自己的那个库。

**Comment by zonyitoo** [comment]
@coolicer 刚更新成我自己的库，你pull一下试试看看能不能正常使用？

**Comment by zonyitoo** [comment]
可以直接下载这个 [shadowsocks-1.6.2-release.x86_64-unknown-linux-musl.tar.gz](https://github.com/shadowsocks/shadowsocks-rust/files/1263810/shadowsocks-1.6.2-release.x86_64-unknown-linux-musl.tar.gz) 来测试

**Comment by coolicer** [comment]
@zonyitoo dalao，哪种加密比较好用啊，现在还在用rc4-md5

**Comment by zonyitoo** [comment]
aes-256-gcm

**Comment by coolicer** [comment]
@zonyitoo 你的chacha20-ietf就是这个chacha20-ietf-poly1305吗？

**Comment by zonyitoo** [comment]
不是。既然名字是不同的，那么必然用的不是同一套算法。shadowsocks.org里并没有要求各实现需要支持`chacha20-ietf-poly1305`

**Comment by coolicer** [comment]
谢谢大佬

**Comment by zonyitoo** [comment]
`chacha20-ietf-poly1305` 原来早就支持，忘记了。

是的，cpuinfo里有aes就是支持aes-ni.
