### ISSUE TITLE
[Bug] `sslocal` cannot daemonize when a plugin is specified via config file

### ISSUE THREAD

**Issue by spyophobia** [shadowsocks/shadowsocks-rust#640]
## Bug description
`sslocal` cannot daemonize using the `-d` or `--daemonize` flag when the config file specifies a plugin.

I am not **entirely** sure that this is 100% the real issue here, but I have tested on two different OSes (RHEL8 & Arch) and observed the same behavior, so let's just say I am reasonably confident.

## To replicate
Here I will use [simple-tls](https://github.com/IrineSistiana/simple-tls) as an example, but the choice of plugin seems irrelevant.
On a Linux x64 machine:
1. Get required binaries - sslocal v1.11.2 (latest stable at the time of writing), [simple-tls](https://github.com/IrineSistiana/simple-tls/releases) or any other plugin
2. Get the config files: [configs.zip](https://github.com/shadowsocks/shadowsocks-rust/files/7296197/configs.zip)
3. Verify that when `-d` is not used, `sslocal` runs correctly
```bash
# Both should run fine
sslocal -v -c ss.json
sslocal -v -c ss-plugin.json # you might have to edit plugin path
```
4. Verify that when `-d` is used without a plugin, `sslocal` daemonizes correctly
```bash
sslocal -v -c ss.json -d --daemonize-pid ss.pid
ps aux | grep sslocal # expect sslocal is running
```
5. Verify that when `-d` is used with a plugin, `sslocal` no longer daemonizes
```bash
sslocal -v -c ss-plugin.json -d --daemonize-pid ss-plugin.pid
ps aux | grep sslocal # expect no sslocal process
```

## Environment & versions
```bash
uname -msr
Linux 4.18.0-305.19.1.el8_4.x86_64 x86_64

sslocal --version
shadowsocks 1.11.2

whoami
root
```

**Comment by zonyitoo** [comment]
Couldn't reproduce with 1.12.0-alpha.8 and `v2ray-plugin`.

What did you see in logs when starting `sslocal` with plugins and daemonizing it?

**Comment by spyophobia** [comment]
Previously I had tried two plugins. I just tried using v2ray a moment ago and daemonizing also failed. This is on v1.11.2.

When daemonizing `sslocal` with plugin:
- there were no logs whatsoever on the terminal when daemonizing fails
- the exit code is 0
- pid file is created
- there is no indication to whether the daemon is running or not without using `ps aux | grep sslocal`.

### Things I tried/checked
- test on RHEL & Arch, same result
- SELinux off (`setenforce 0`)
- running as root & non-root

An interesting observation: when daemonizing as non-root **with or without** a plugin, the pid file is created but is left empty. There shouldn't be a problem with file permissions as all this is happening in my home directory. Not sure how this may be related to this issue but FYI.

<hr>

I will try the latest git version and report back if you so desire.

**Comment by spyophobia** [comment]
Also can you please share your working config file? Just to rule out the possibility of some unknown config conflicts.

**Comment by spyophobia** [comment]
```bash
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            31Gi       5.8Gi       8.8Gi       2.5Gi        16Gi        22Gi
Swap:           31Gi          0B        31Gi
```

**Comment by spyophobia** [comment]
Okay, it seems like I have actually discovered two closely related but different issues here.

The first one is exactly as you stated: if `"plugin"` field contains a relative path, daemonizing will fail.

The second one is the same problem but with `"plugin_opts"`. If the plugin requires passing in a path to a config file using this field (e.g. [Cloak](https://github.com/cbeuw/Cloak/wiki/Underlying-proxy-configuration-guides#plugin-mode)) and we use a relative path, daemonizing will also fail.

Commit 862a8a7 did fix the first issue, but not the second one. I assume you reverted the change due to backward compatibility concerns?

I think the greater problem here is the difference in behavior between "daemon mode" and "non-daemon mode". The same config file can work in one mode but fail in another, which is unexpected and hard to diagnose.

**Comment by zonyitoo** [comment]
> I assume you reverted the change due to backward compatibility concerns?

Nope. It doens't fix the first issue at all.

You could try to apply that commit locally and see if that fixes your issue?

**Comment by spyophobia** [comment]
Yes it did. Just tested with `v2ray` and `cloak`, solved both issues (now both `"plugin"` and `"plugin_opts"` can use relative paths).

Would you like a PR?

**Comment by spyophobia** [comment]
By the way, you may wish to include a compatibility note on this in the next release, as I am concerned that this "fix" could break some people's configs.

In the original implementation, since `Daemonize::working_directory` was not called, the working directory defaults to `/`. So if someone has a plugin with path `/opt/ss-plugins/my-plugin`, but has set the `"plugin"` field in their config file as `opt/ss-plugins/my-plugin`, this change will break their config.

Admittedly, a path like this would be considered an "erroneous" config. Nevertheless this change breaks bug-compatibility so I think it's worth a mention.
