### ISSUE TITLE
How to view logs when run with docker?

### ISSUE THREAD

**Issue by itsalongstory** [shadowsocks/shadowsocks-rust#647]
```
docker run --name ssserver-rust \
  --restart always \
  -p 666:8388/tcp \
  -p 666:8388/udp \
  -v ~/ss-server.json:/etc/shadowsocks-rust/config.json \
  -dit ghcr.io/shadowsocks/ssserver-rust:latest
```

Where to view log files？

**Comment by dev4u** [comment]
log-config: log4rs configuration file

指定参数传入，配置文件参考项目中log4rs.yaml。

**Comment by zonyitoo** [comment]
Logs are printed to `stderr` by default.

Or use `--log-config` to redirect logs to files.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/9cba0ba85b9bbdee98270b082f728b3d9eb419fe/Dockerfile#L54

The default `ENTRYPOINT` doesn't have this parameter, you can run it manually.
