### ISSUE TITLE
Adding new users

### ISSUE THREAD

**Issue by digeratus** [shadowsocks/shadowsocks-rust#66]
Is it possible to add new users while running or does it require a reboot? In other words, once the configuration file has been edited what does it take to take effect.

Also, is there a way to do it via an API?
https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users

Thanks

**Comment by zonyitoo** [comment]
1. It requires reboot after editing the configuration file.
2. Sure, it is quite easy to support it like [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c)

But I don't have enough time to implement this recently, too busy :(
**Any PRs are welcome!!**

Here is some hints for implementing manage APIs:

1. Stores different users' configuration in different files `.shadowsocks_${port}.conf` https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L101
2. Spawn/Kill a shadowsocks' instance after modified the configuration files https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/manager.c#L472-L515
3. Implement manage protocol https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users#protocol

**Comment by digeratus** [comment]
Great. Thanks

**Comment by digeratus** [comment]
I'm quite new to shadowsocks so please forgive my ignorance here, but when creating a password for the configuration file, is that arbitrary? Any password would do or it is it a system assigned password that gets created running some utility or command I'm not aware of within shadowsocks?

Thanks again.

**Comment by zonyitoo** [comment]
If I understand you correctly,  what you are asking is about how to generate a new password?

> Any password would do

Yes, you can use any password you want.

> gets created running some utility or command

Well, you can create by writing a simple program to generate a completely random string, or use other existing program, for instance:

```
$ openssl rand -base64 32
```

That would give you a random generated string, and you can use it as password.
