### ISSUE TITLE
Possible snap installation issue.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [shadowsocks/shadowsocks-rust#663]
```
root@raspberrypi:/snap/bin# ./shadowsocks-rust.ssserver
/snap/shadowsocks-rust/110/snap/command-chain/snapcraft-runner: 5: exec: /snap/shadowsocks-rust/110/bin/ssserver: Exec format error
```

On ubuntu it seems to work fine but on raspberry pi it gives this error.

**Comment by zonyitoo** [comment]
rpi requires aarch64 binaries.

**Comment by Prajwal-Koirala** [comment]
Shouldn't snap handle that automatically?
Last time I did this, snap did it automatically.

**Comment by zonyitoo** [comment]
It should.

I just upgraded to v1.12.0-alpha.10 on snap, please try again and see if it fixes your issue.

**Comment by Prajwal-Koirala** [comment]
```
 /snap/bin/shadowsocks-rust.ssserver -c /var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json
/snap/shadowsocks-rust/127/snap/command-chain/snapcraft-runner: 5: exec: /snap/shadowsocks-rust/127/bin/ssserver: Exec format error
```

**Comment by Prajwal-Koirala** [comment]
Still not working.

**Comment by zonyitoo** [comment]
I can't help further because I don't have a RPi. You may try to install it manually from Release builds. https://github.com/shadowsocks/shadowsocks-rust/releases

**Comment by 18o** [comment]
the same error occur on Debian arm64, it's because the snap download the x86_64 binary files on arm64 platform by running `snap install shadowsocks-rust`, i'm quite sure about this because i copy that binary file to a x86_64 Debian and it works.

**Comment by Prajwal-Koirala** [comment]
```
root@raspberrypi:/snap/bin# file -Lb  ./shadowsocks-rust.ssserver | cut -d, -f2
 ARM
root@raspberrypi:/snap/bin# uname -a
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
```

**Comment by Prajwal-Koirala** [comment]
> I can't help further because I don't have a RPi. You may try to install it manually from Release builds. https://github.com/shadowsocks/shadowsocks-rust/releases

Hey,
Can u please explain the different releases, I don't understand it.

This is the only part i don't understand this part.
```
aarch64-unknown-linux-gnu
aarch64-unknown-linux-musl
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
i686-unknown-linux-musl
mips-unknown-linux-gnu
mips-unknown-linux-musl
mipsel-unknown-linux-musl
x86_64-apple-darwin
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl
```

**Comment by zonyitoo** [comment]
What architecture is your RPi’s CPU? If you don’t know about it, check the official document of RPi
.

**Comment by zonyitoo** [comment]
> root@raspberrypi:/snap/bin# file -Lb shadowsocks-rust.ssserver
> ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, Go BuildID=yNI-EPJhBV_TYbOa3Nar/6vMqPK2BmTMJ1LlG1ZP2/8dzdhZ81ahVvXx3n8lrb/3WHXTQ5oUNtPf-jj-FN4, BuildID[sha1]=8c23efe5d46db11d967812ec108c9145fa2e57e3, stripped
> root@raspberrypi:/snap/bin# uname -a
> Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux

It seems that snap thought you were running on a 32-bits armv7 device.

**Comment by Prajwal-Koirala** [comment]
Can I force snap to install 64 bit version of the app?

**Comment by Prajwal-Koirala** [comment]
> What architecture is your RPi’s CPU? If you don’t know about it, check the official document of RPi .

64 bit.

**Comment by Prajwal-Koirala** [comment]
> > root@raspberrypi:/snap/bin# file -Lb shadowsocks-rust.ssserver
> > ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, Go BuildID=yNI-EPJhBV_TYbOa3Nar/6vMqPK2BmTMJ1LlG1ZP2/8dzdhZ81ahVvXx3n8lrb/3WHXTQ5oUNtPf-jj-FN4, BuildID[sha1]=8c23efe5d46db11d967812ec108c9145fa2e57e3, stripped
> > root@raspberrypi:/snap/bin# uname -a
> > Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
> 
> It seems that snap thought you were running on a 32-bits armv7 device.

Is there a local snap config, that tells snap what arch to use?
if so than can i edit the config and than snap will install the 64 bit version of the app instead of the 32 bit version.

**Comment by zonyitoo** [comment]
```
root@raspberrypi:/snap/bin# uname -a
Linux raspberrypi 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
```

You are running on a armv7 CPU, which is a 32-bit processor.

**Comment by zonyitoo** [comment]
Try to install `arm-unknown-linux-musleabihf` if it works.

**Comment by 18o** [comment]
does the snap package uploaded manually ? i just confused why x86_64 binary was download on arm platform when run snap install

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/master/snap/snapcraft.yaml

**Comment by Prajwal-Koirala** [comment]
Hey,
Can you turn the repo into a PPA? 
This would make installation easier for new users and more people would use this.

**Comment by zonyitoo** [comment]
I have no spare time to maintain too many of them.

**Comment by Prajwal-Koirala** [comment]
> I have no spare time to maintain too many of them.

Hey,
I had this one question since about 2018, and I never really got a straight forward answer to it.

Why isn't there a single unified experience to shadowsocks?

There are a lot of useless repo on this org, things that have been depreciated for years haven't been archived, and still people open issues and stuff.

Are there any plans for a single unified experience like WireGuard?

For example, you guys are planing on using rust on server side, so depreciate the go version and other things.

We all really want a single version of server side and a single version of it on client side and there are so many versions of things it's hard for the end user to keep track of.

**Comment by zonyitoo** [comment]
Well, because shadowsocks is a open source project. All projects in this org are contributed by ones that are passionate on improving shadowsocks.

We haven't planned on using the rust version on server side. Or we should say, there is no "we". The organization only defines the protocol. Using which implementation is decided by yourself, you can also make your own implementation.

**Comment by GF-Huang** [comment]
Same issue, someone solved it?

**Comment by zonyitoo** [comment]
You may try to add `--arch arm64` when installing from `snap`.

**Comment by GF-Huang** [comment]
> You may try to add `--arch arm64` when installing from `snap`.
```
(base) pi@raspberrypi:~ $ sudo snap install shadowsocks-rust --arch arm64
error: unknown flag `arch'
```

```
(base) pi@raspberrypi:~ $ snap version 
snap    2.58.2
snapd   2.58.2
series  16
debian  11
kernel  5.15.32-v8+
```

**Comment by skullcrossbones** [comment]
root@instance:~# sudo snap install shadowsocks-rust -- aarch64
error: store.SnapNotFound with 2 snaps

root@instance-~# sudo snap install shadowsocks-rust -- arm64
error: store.SnapNotFound with 2 snaps


root@instance:~# snap --version
snap    2.59.1
snapd   2.59.1
series  16
ubuntu  22.04
kernel  5.15.0-1034-oracle
