### ISSUE TITLE
Dealing with unicode domains in ACL

### ISSUE THREAD

**Issue by spyophobia** [shadowsocks/shadowsocks-rust#669]
Continues discussion under 4500d46

**Comment by Y0ba** [comment]
Also in your particular example all three rules can be replaced with this:
```
# .中国
||xn--fiqs8s
# .公司
||xn--55qx5d
# .网络
||xn--io0a7i
```

**Comment by spyophobia** [comment]
> Because dns in general doesn't work with unicode domains. It's possible to do it in opposite way - convert everything to unicode and then do match, but I not sure if it worth it.

Okay I can respect this opinion. Also after a bit of research I found the standard for this (rfc3492) so I guess yeah you're correct.

However I am more concerned with backward compatibility. Many ACLs exist that are not properly encoded considering this isn't exactly a well-known standard. Also many users simply pull existing ACLs from others' repositories instead of writing their own, which means they rely on the upstream to fix their lists to prevent annoying breakages.

For this reason I suggest that we at minimum introduce an extensive deprecation period for unencoded Unicode domains.  Again, if we cannot match against unicode patterns, at least don't let one bad line fail the entire parse (unless there are any associated safety concerns).

**Comment by Y0ba** [comment]
Okay, here is what I think is the best option here:
1) Enable unicode support and explicitly convert all domains to unicode (ind converter is smart and don't convert ascii domains so there won't be a performance impact)/
2) Detect `asd$` and `(^|\.)xyz$` (also `(?:^|\.)xyz$`) patterns and automatically replace them with `|asd` and `||xyz`.

That way we will get both high speed (speed of `|xyz` and `||xyz` is unaffected by unicode) and  backward compatibility. It will be even faster since 99% of regex rules are exactly these two patterns.

**Comment by spyophobia** [comment]
I'm not very familiar with IDNs at all (or for that matter, the inner workings of ACL; I simply noticed a breakage in my ACL after update lol). So I will defer to your opinion on the specific implementation.

**Comment by Y0ba** [comment]
Well, unicode conversion was introduced not because of some some principle, but simply because unicode regexes are slower and take more memory. If this slowdown can be mitigated for most of regexes, then there is no point to not support idns.

**Comment by zonyitoo** [comment]
What error did you got? Could you provide an ACL file that fail to parse? @spyophobia

**Comment by dev4u** [comment]
https://github.com/shadowsocks/shadowsocks-rust/pull/627#issuecomment-922320750
@zonyitoo 可能跟我之前的情况一样，网络上的acl文件，会预处理不了类似`(^|\.)boxun.+\.azurewebsites\.net`的规则。

**Comment by zonyitoo** [comment]
It works perfectly on my laptop.

**Comment by zonyitoo** [comment]
For errors that mentioned in https://github.com/shadowsocks/shadowsocks-rust/pull/627#issuecomment-922320750 , we should enable the `allow_invalid_utf8` option: https://github.com/rust-lang/regex/blob/238b7759ad913c3e3d49cf30a84267eb6b89e9dd/regex-syntax/src/parser.rs#L146-L157

**Comment by zonyitoo** [comment]
> Okay, here what I think is the best option here:
> 
> 1. Enable unicode support and explicitly convert all domains to unicode (idn converter is smart and don't convert ascii domains so there won't be a performance impact).
> 2. Detect `^asd$` and `(^|\.)xyz$` (also `(?:^|\.)xyz$`) patterns and automatically replace them with `|asd` and `||xyz`.
> 
> That way we will get both high speed (speed of `|xyz` and `||xyz` is unaffected by unicode) and backward compatibility. It will be even faster since 99% of regex rules are exactly these two patterns.

Patterns:

1. `||` equivalent:

```regex
^(\(\^\|\\\.\)|\\\.)?([a-zA-Z0-9-]+(\\\.)?)+\$?$
```

2. `|` equivalent

```regex
^\^([a-zA-Z0-9-]+(\\\.)?)+\$?$
```

**Comment by Y0ba** [comment]
> `[a-zA-Z0-9-]`

Just use `[\w-]`. It will also include all Unicode alphabetic characters.

> `^(\(\^\|\\\.\)|\\\.)?([a-zA-Z0-9-]+(\\\.)?)+\$?$`

First, it will not match patterns with non-capturing group `(?:^|\.)xyz$`. Second it's also will be faster to use non-capturing groups inside regex itself. And third, I don't think making last `$` optional is a good idea.

Something like `^(?:\((?:\?\:)?\^\|\\\.\)|\\\.)?(?:[\w-]+(?:\\\.)?)+\$$` probably will be better.

And `^\^(?:[\w-]+(?:\\\.)?)+\$$` for `|` equivalent.

**Comment by zonyitoo** [comment]
1. `||` equivalent

```
^(?:\((?:\?:)?\^\|\\\.\)|(?:\^\.\+)?\\\.)?((?:[\w-]+(?:\\\.)?)+)\$$
```

2. `|` equivalent

```
^\^((?:[\w-]+(?:\\\.)?)+)\$$
```

One online ACL rule won't add the tailing `$` in rules. But you are right, it is possible that it just want to match a word in the URL.

**Comment by zonyitoo** [comment]
Ok, this is definitely a wrong ACL. Client won't send a unicode domain to socks5 server:

```
$ curl 'https://人.中国' --socks5-hostname 127.0.0.1:1300 -v
*   Trying 127.0.0.1:1300...
* SOCKS5 connect to xn--gmq.xn--fiqs8s:443 (remotely resolved)
```

Samething you can find in Chrome when you are trying to access a website with IDN.

**Comment by spyophobia** [comment]
Okay good to know. I'll go submit a PR in that repo then.

**Comment by zonyitoo** [comment]
The latest commit will skip rules that containing non-ASCII characters.
