### ISSUE TITLE
Is shadowsocks compatible with SOCKS?

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-rust#675]
That is, MacOS has an option to put your SOCKS proxy. Can I replace it with a Shadowsocks proxy, or would I need the specific client?

**Comment by zonyitoo** [comment]
Yes.

**Comment by DUOLabs333** [comment]
Really, I tried it right now, and it didn't work. Does it need a username or can you leave it blank?

**Comment by DUOLabs333** [comment]
I tried to `curl` `cloudflare`, but got `dns resolve www.cloudflare.com:443 error: No connections available`

**Comment by zonyitoo** [comment]
1. No username.
2. `curl` doesn't read the system configrated proxy setting.
3. `Too many open files`, you could raise fd limit with `ulimit` or `-n 10240` or `"nofile": 10240` in configuration file.
