### ISSUE TITLE
"ERROR accept failed with error: Too many open files (os error 24)"

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-rust#676]
I'm trying to run this with the server.json
```
{
    "server": "0.0.0.0",
    "server_port": 8888,
    "password": "mypassword",
    "method": "aes-256-gcm",
    "dns": "google",
}
 ```
and client.json
```
{
    "server": "192.168.1.51",
    "server_port": 8888,
    "password": "mypassword",
    "method": "aes-256-gcm",
    "local_address": "127.0.0.1",
    "local_port": 1080,
}
```
When using with `curl` it works fine, but trying to use it as my actual proxy fails with `ERROR accept failed with error: Too many open files (os error 24)`

**Comment by zonyitoo** [comment]
Error is as it said. You may try to run with `-n 10240` or `"nofile": 10240` in configuration file.

**Comment by DUOLabs333** [comment]
The problem still exists.

**Comment by zonyitoo** [comment]
Put it in the configuration that you see this error. If you saw the error on the server side, then put it in the server's configuration.

**Comment by DUOLabs333** [comment]
I saw it on the client side, so absolutely nothing happens, nothing loads and using curl through the proxy fails if I put the option in the client.json

**Comment by DUOLabs333** [comment]
Now there's `OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.cloudflare.com:443` if I use `curl`.

**Comment by zonyitoo** [comment]
```bash
curl 'https://www.cloudflare.com' --socks5-hostname YOUR_PROXY:PORT
```

**Comment by DUOLabs333** [comment]
Sorry, meant to say that ` curl -x socks5h://127.0.0.1:1080 -sSL4 https://www.cloudflare.com` succeeds if the system isn't configured to use the proxy, but if it is, it stops working. This implies that the browser is preventing anything else from working.

**Comment by zonyitoo** [comment]
If you tells `curl` to use `socks5h://127.0.0.1:1080`, then it is unrelated what's in the system's configuration.

This is not a common shadowsocks' issue, try to figure it out in your own environment.

**Comment by zonyitoo** [comment]
I am using macOS, too. Everything works fine.

**Comment by DUOLabs333** [comment]
Could you tell me your setup, to see if mine differs?

**Comment by zonyitoo** [comment]
There is no setup. Just configure and it works. No special setting.

**Comment by DUOLabs333** [comment]
From the logs, everything seems to be working fine, so this is very confusing.

**Comment by DUOLabs333** [comment]
Found the reason: for some reason, the client won't work if it's running locally. It also has to be running on the remote server -- don't know why.

**Comment by DUOLabs333** [comment]
One last problem -- I have a DNS running locally on my server, so I specify `"dns":"127.0.0.01"`. It didn't work for some reason.

**Comment by zonyitoo** [comment]
Is your DNS resolver listening on port `53`?

**Comment by DUOLabs333** [comment]
Yes: `0.0.0.0:53`

**Comment by zonyitoo** [comment]
Ports < 1024 on macOS are privileged ports, you have to start it with launchd. Also, macOS have its own DNS cache server listening on `53`.

Learn more about macOS before making your own modifications.

**Comment by DUOLabs333** [comment]
The server is on a Linux server, the DNS is also on the Linux server.

**Comment by zonyitoo** [comment]
What do you expect when configuring `"dns":"127.0.0.01"`?

**Comment by DUOLabs333** [comment]
Since both the server and client are on the server, when the Macbook sends a request to the client, it will resolve the hostname at `127.0.0.1:53`, `127.0.0.1` relative to the client.

**Comment by zonyitoo** [comment]
It should work already. DNS queries should have sent to 127.0.0.1:53

**Comment by DUOLabs333** [comment]
I checked, all I get is DNS errors.

**Comment by zonyitoo** [comment]
Quite uncommon behavior. You should do more debugging on your environment. First of all, try to `dig` your own DNS server and see if it works well.

**Comment by DUOLabs333** [comment]
Oh, right, now I remember why. I only set it to go to the public IP, not on localhost (it interfered with dnsmasq).

**Comment by DUOLabs333** [comment]
Not sure why it didn't work through the hostname though. Does shadowsocks not support that?

**Comment by zonyitoo** [comment]
What do you mean host name?

**Comment by DUOLabs333** [comment]
On my LAN, my DNS is reachable with `hostname.local`. Can shadowhosts reach that?

**Comment by DUOLabs333** [comment]
And it's weird why `0.0.0.0` doesn't work. Is it because it's not an actual IP address?

**Comment by zonyitoo** [comment]
> On my LAN, my DNS is reachable with `hostname.local`. Can shadowhosts reach that?

That’s because your macOS has a `hostname.local` configured in the local DNS server.

The ssserver is running on the server itself, it is quite abnormal to not doing that with hostname instead of 127.0.0.1

**Comment by DUOLabs333** [comment]
My server and my MacOS are on the same LAN.

**Comment by zonyitoo** [comment]
`hostname.local` is a name, it have to be resolved to IP address by a DNS resolver, which is your macOS's local DNS resolver or the DNS resolver running on LAN.



> And it's weird why `0.0.0.0` doesn't work. Is it because it's not an actual IP address?

What's that mean? `"dns": "0.0.0.0"`?

**Comment by DUOLabs333** [comment]
0.0.0.0 mean all IPv4 addresses on the computer: 127.0.0.1, and if that doesn't resolve, your public IP.

**Comment by dev4u** [comment]
这兄弟， 我怎么感觉你还没搞明白你想干嘛。直白的说，ss的相关文档真的不算丰富，你没什么基础的话，不如先多搜一下网上的资源、多研究一下现有的文档，或许比现在把issue当聊天工具用，要强不止百倍噢。

**Comment by DUOLabs333** [comment]
Ok, got it. Thanks for your help anyway.
