### ISSUE TITLE
The dns protocol doesn't take 53 as the default port

### ISSUE THREAD

**Issue by Tigerfyj** [shadowsocks/shadowsocks-rust#683]
I compiled sslocal and ssserver with the flags: `--release --features "local-http-rustls,local-dns,local-redir,local-socks4,local-tunnel,multi-thre[0/1]logging,trust-dns,local,local-http"`.
The git branch  is "54e834a", `git status` shows `v1.12.1`.

How to reproduce:
```
$ sslocal --protocol dns -b "127.0.0.1:5555" -s "127.0.0.1:6666" -m "aes-256-gcm" -k "hello-kitty"   --remote-dns-addr "8.8.8.8" --local-dns-addr "1.1.1.1" -v
```

I got the message on the server side:
```
 [shadowsocks_service::server::tcprelay] tcp tunnel 127.0.0.1:36358 -> 8.8.8.8:80 connect failed, error: Connection timed out (os error 110)
```

The v1.11.x doesn't have this issue.

**Comment by zonyitoo** [comment]
I don't think so. The `--remote-dns-addr` is an `Address`, which will have default port `80` all the time.

**Comment by dev4u** [comment]
> I don't think so. The `--remote-dns-addr` is an `Address`, which has default port `80` all the time.
> 
平心而论，这样取dns的默认端口，合情但不见得合理噢。
