### ISSUE TITLE
搞不懂snap安装的ss-rust默认配置文件在哪？

### ISSUE THREAD

**Issue by tooiiby** [shadowsocks/shadowsocks-rust#688]
shadowsocks-libev用/var/snap/shadowsocks-libev/common/etc/shadowsocks-libev/config.json启动成功，shadowsocks-rust用/var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json报错启动失败。

**Comment by zonyitoo** [comment]
@DuckSoft

**Comment by kda2011** [comment]
Maybe an newbie install script help? Issue #692

**Comment by tooiiby** [comment]
> 也许新手安装脚本有帮助？问题#692

感谢您的回复，但让我苦恼的并不是安装问题。而是ss-rust并不能像ss-libev一样直接读取/var/snap/shadowsocks-libev/common/etc/shadowsocks-libev/config.json里面的配置文件，我的问题跟＃691其实是一样。希望ss-rust也能读取/var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json中的配置

**Comment by kda2000** [comment]
你既没有发配置文件，也没有发报错信息。很难诊断。
1.也许是配置文件json语法问题？两个版本的json容错设计可能不一样？
2.权限问题？打包者可能不熟悉snap？

个人觉得按#692的方法解压安装，比snap更轻量方便。
没必要用snap这个臃肿不成熟的软件发行平台，而且主要开发者zonyitoo也说了他不熟悉snap。#691。
开发者甚至还说了不希望这个软件对新手太简单易用，#692，震惊。
你可以考虑停留在libev版本或选用其他版本实现。
