### ISSUE TITLE
Is it necessary to run slocal on the server side?

### ISSUE THREAD

**Issue by digeratus** [shadowsocks/shadowsocks-rust#69]
There’s sslocal and ssserver. Is sslocal just a client and the other a server?

I’m asking because I’d like to start the server side and don’t know if I need to start both or just ssserver.

Thanks

**Comment by zonyitoo** [comment]
`sslocal` runs in your local system, and `ssserver` runs in remote server.

**Comment by zonyitoo** [comment]
```
YourBrowser -> sslocal -> [INTERNET] -> ssserver -> [INTERNET] -> RemoteServer
|                     |               |           |
| Your Local System   |               | Proxy     |
| Your computer       |               | Server    |
+---------------------+               +-----------+
```

**Comment by zonyitoo** [comment]
Close for inactivity.
