### ISSUE TITLE
Logging level not configrable in config file

### ISSUE THREAD

**Issue by sstpe** [shadowsocks/shadowsocks-rust#691]
I'd like to have `ssserver` be in verbose logging mode on my shadowsocks-rust deployment via snap. However, snap doesn't make it easy to pass command-line arguments to its services. I use a config file instead.

The problem is, there doesn't seem to be a way, documented or otherwise, to set the logging level to verbose in the config file, despite being able to set just about everything else. This strikes me as unintentional.

**Comment by dev4u** [comment]
试试-vv 或者 -vvv

**Comment by zonyitoo** [comment]
Is there a way to run the `ssserver` binary directly instead of running via `snapctl`?

**Comment by sstpe** [comment]
> Is there a way to run the `ssserver` binary directly instead of running via `snapctl`?

There absolutely is -- `shadowsocks-rust.ssserver`, however there doesn't seem to be a way to configure snap to automatically start ssserver with arguments passed to the binary.

It's possible I'm missing a way to alter the `ssserver-daemon` that snap is using. However, if I were to find a way to do that, it would still strike me as a hacky workaround, and would probably be reverted by snap during the next refresh.

As far as I'm aware after much trial and error, the only way I'm able to configure ssserver when it is started by snap is through the config file (found only in the default location inside of `/var/snap/shadowsocks-rust/common/etc/shadowsocks-rust/config.json`, as I can't change that either).

**Comment by zonyitoo** [comment]
I am not so familiar with snap. Could you help to fix #621 ?

BTW, the verbose level command line option is just for debugging. So if you are trying to debug, just run it directly instead of starting with snap's daemon.

**Comment by zonyitoo** [comment]
> This issue still stands because logging level is still not configurable via the config file. An alternative solution could be providing configuration settable by `snap set shadowsocks-rust verbose=true`.

Maybe we could make a wrapper script that reads variables from `snap get` and then pass it to `sslocal`, `ssserver` command line arguments. @DuckSoft what do you think?

**Comment by sstpe** [comment]
> I am not so familiar with snap. Could you help to fix #621 ?

I'm not sure I'm able to at the moment, as I'm newly learning about snap for shadowsocks, but I can take a look at how `shadowsocks-libev` manages to read its configuration file at `/var/snap/shadowsocks-libev/common/etc/shadowsocks-libev/config.json`

> BTW, the verbose level command line option is just for debugging. So if you are trying to debug, just run it directly instead of starting with snap's daemon.

At this stage for me, it's helpful to see every connection `ssserver` is receiving from a client. The default log level doesn't log that. A workaround I was using was `tcpdump` but that's unwieldy compared to simply being able to enable verbose logging.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/365465811113ed5018ee4c8d5b078b41095387fc/src/utils.c#L537

**Comment by zonyitoo** [comment]
I don't know if snap allows you to start programs with environment variables: `SS_LOG_VERBOSE_LEVEL`, `SS_LOG_WITHOUT_TIME`. If it is true, then this commit should fix this issue.

**Comment by sstpe** [comment]
Thank you @zonyitoo! All the blockers on my use case are now resolved. Much appreciated!
