### ISSUE TITLE
Showcase : Newbie friendly install script

### ISSUE THREAD

**Issue by kda2011** [shadowsocks/shadowsocks-rust#692]
Maybe add this to homepage? I write some reasons below: really newbie-friendly, mainly extract & run! no root required, no need to install some heavy package like:snap, docker, cargo. Also reasons not to doing so: It's not auto-update.

This install script was tested on Oracle Linux Server 8.5 aarch64, bash 4.4.20.

安装步骤（以aarch64 v1.12.2为例）：
所有文件将安装至$HOME/ss，安装完毕之后，使用ss/start.sh运行，使用cat ss/log_ss查看日志，使用vi ss/config.json修改配置。

cd
mkdir ss
cd ss
curl -OL https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.12.2/shadowsocks-v1.12.2.aarch64-unknown-linux-musl.tar.xz
tar xf shadowsocks-v1.12.2.aarch64-unknown-linux-musl.tar.xz
echo '
{
"server":"::",
"server_port":3389,
"password":"YOUR-PASSWORD",
"method":"aes-256-gcm",
"dns":"1.1.1.1"
}
' > config.json
echo '
cd "$HOME/ss"
pkill ssserver
rm -f log_ss
nohup ./ssserver -c config.json > log_ss 2>&1 &
' > start.sh
chmod +x start.sh
cd

**Comment by zonyitoo** [comment]
I don't want to make it too easy for newbies, for some known reason.

**Comment by kda2011** [comment]
> I don't want to make it too easy for newbies, for some known reason.

Thanks your great contribution in shadowsocks-rust.👏
However, your decision making people sad. 🙁
Hope you change your mind one day , maybe.👍
