### ISSUE TITLE
Two-way proxy?

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-rust#693]
Currently, if you start a service on a server, you can access it in the client. However, if you start a service on the client, you can't access it on the server. Is there a way to make it happen?

**Comment by zonyitoo** [comment]
I don't really understand what your problem is. Are you talking about how to access a server running behind NAT?

**Comment by DUOLabs333** [comment]
I mean any service running on the localhost on the client should be
reachable by the server.

**Comment by zonyitoo** [comment]
This is not how shadowsocks, or SOCKS5 protocol was designed. The most suitable and relevent solution is the `BIND` command in SOCKS5, but unfortunately, shadowsocks' protocol missed that part.

**Comment by DUOLabs333** [comment]
Ah, I see. Regarding the second part, I meant that if the client is already connected to server, to reverse the connection. But it seems it's not possible.
