### ISSUE TITLE
Suggest: Build one single bundled binary

### ISSUE THREAD

**Issue by kda2000** [shadowsocks/shadowsocks-rust#698]
For proxy tools, source code that are required by client **is** also required by server, in theory.
sslocal, ssserver, ssmanager shares a lot of common source code.
Static-link build them apart is wasting storage space.As of ssurl, it's something 'one line code'.
I suggest build them into one single binary file, with switch flag, like --local, --server, --manager, --encode, --decode.

**Comment by zonyitoo** [comment]
I don't think this is necessary, because you won't run a client and a server in the same machine, for most cases. The `ssurl` is just a convenient tool, which can always be ignored.

**Comment by kda2000** [comment]
Running ss-local in client, is actually running an local socks5 **server**, and an shadowsocks **client**,in same machine.

Running an tunnel shadowsocks in server , there maybe something similar like this?

Learned from go-shadowsocks2, v2ray-core.

**Comment by zonyitoo** [comment]
Do make it wrong. The term "server" refer to the shadowsocks server (or remote), and "client" refer to the shadowsocks client (or local). The local socks5 server is a feature in the local client.

**Comment by kda2000** [comment]
Maybe you're right, it is unnecessary. People won't run a client and a server in the same machine, like tunnel , **for most cases**.

But they do share a lot common source code, like base shadowsocks-encrypt, ACL.

Hold this issue open for more discussion from different people?

**Comment by database64128** [comment]
I second this proposal.

> because you won't run a client and a server in the same machine

I actually do run sslocal and ssserver at the same time on half of my shadowsocks-rust deployments.

**Comment by database64128** [comment]
> I suggest build them into one single binary file, with switch flag, like --local, --server, --manager, --encode, --decode.

We can use commands to separate different modes:

```bash
$ ss-rust client -c /etc/shadowsocks-rust/client.jsonc
$ ss-rust server -c /etc/shadowsocks-rust/server.jsonc
$ ss-rust manager -xxx
$ ss-rust url -xxx
```

**Comment by spyophobia** [comment]
Does this change increase the amount of RAM required for compilation? Previously on memory-constrained machines I've always used the "compile binaries one at a time with `--bin` flag" trick to reduce memory usage. I suppose this trick would no longer work now?

**Comment by zonyitoo** [comment]
Compile with `--bin` is still working, because the new binary will only be compiled with name `ssservice`.
