### ISSUE TITLE
Suggest: Default config path & Log level

### ISSUE THREAD

**Issue by kda2000** [shadowsocks/shadowsocks-rust#700]
Recent commit made some new change, I have some suggestion about them:
1. Add 'working directory', 'executable location' to Default config path.
2. Put log level setting in config.json like nginx, httpd. Furthermore, make this as SIP standard?
PS: I don't know if there is any SIP standard for config.json. As far as I know , ss-rust using some different keyword from libev, for port as server_port.
3. Print loaded config path, log level setting to stdout during startup, for better user-understanding ,before they post any new issue about config.

**Comment by database64128** [comment]
> Add 'working directory', 'executable location' to Default config path.

Working directory can be defined in a systemd unit file. A running process can easily detect its binary location.

**Comment by zonyitoo** [comment]
> Add 'working directory', 'executable location' to Default config path.

What's that for? Why would binary needs to know where itself was located?

> Put log level setting in config.json like nginx, httpd. Furthermore, make this as SIP standard?

Logging level is only for binaries. But the config.json is parsed in the shadowsocks-service library, which doesn't care about logging. I would still keep the logging level option in command line and environment variables.

> PS: I don't know if there is any SIP standard for config.json. As far as I know , ss-rust using some different keyword from libev, for port as server_port.

https://shadowsocks.org/en/config/quick-guide.html

No, there is only `server_port`.

> Print loaded config path, log level setting to stdout during startup, for better user-understanding ,before they post any new issue about config.

No. If the process is running in the sandbox, then the path of configuration file is not the actual path in the host. I don't think it would help and also adding complication in the current code.

**Comment by kda2000** [comment]
> > Add '**working directory**', '_executable location_' to Default config path.
> 
> Working directory can be defined in a systemd unit file. A running process can easily detect its binary location. 
>
> What's that for? Why would binary needs to know where itself was located?
> 

For tarball/extract installation, it make an quick cli start using './ssserver' instead of './ssserver -c config.json'. Binary doesn't need to know itself location, something like reading 'config.json' directly, may do the same job.

> > Put log level setting in config.json like nginx, httpd. Furthermore, make this as SIP standard?
> 
> Logging level is only for binaries. But the config.json is parsed in the shadowsocks-service library, which doesn't care about logging. I would still keep the logging level option in command line and environment variables.
> 
> > PS: I don't know if there is any SIP standard for config.json. As far as I know , ss-rust using some different keyword from libev, for port as server_port.
> 
> https://shadowsocks.org/en/config/quick-guide.html
> 
> No, there is only `server_port`.
> 

About keyword 'server_port', it maybe my mistake.
About Log Level setting, that's up to you, it can be a big change.
Program like Apache HTTPd, NGINX do read log setting in config file. They do have something  about master, slave, core, service, etc.

> > Print loaded config path, log level setting to stdout during startup, for better user-understanding ,before they post any new issue about config.
> 
> No. If the process is running in the sandbox, then the path of configuration file is not the actual path in the host. I don't think it would help and also adding complication in the current code.

If some newbie create two config file in both default location. Things can be wired.
Some example again : PHP will let user know which php.ini it loaded, even in docker as a virtual-path?

**Comment by zonyitoo** [comment]
Apart from the logging level in the configuration requrest, all the others are supported in the latest branch.
