### ISSUE TITLE
Connection to `sslocal` fails after a while on SagerNet

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-rust#704]
I connect to the SOCKS proxy created by shadowsocks through `SagerNet` (this happens on any version, though I'm focusing on the latest ve3stion available through F-droid). This works for a while, though after a while, it will fail -- trying to connect to a `0.0.0.0:$PORT` or `127.0.0.1.nip.io:$PORT` will fail with "Connection refused". To fix it, I either have to reinstall the app or get a new version. Later versions (available on GitHub) last much longer before failing (1-3 days) than the F-droid version (<1 day).

**Comment by kda2000** [comment]
Post your servr-side shadowsock-rust version.

0.0.0.0 is for LISTEN, not for CONNECT.

It maybe an client-side problem, try Shadowsocks by Max Lv(android) or Potatso Lite(iOS).

**Comment by zonyitoo** [comment]
It is impossible to use `0.0.0.0:$PORT` for connection.

Please provide more detail about how to reproduce your problem.

**Comment by DUOLabs333** [comment]
1. Run a service on the server with `127.0.0.1:$PORT`. 
2. Set up `ssserver` and `sslocal`, exposing `sslocal`. 
3. Connect to `sslocal` with the `SOCKS` option in `SagerNet`
4. You can connect  to the original service with `0.0.0.0:$PORT`.

**Comment by zonyitoo** [comment]
Is your `sslocal` listening on `127.0.0.1:$PORT`?

Are you setup your clients to connect `sslocal` with address `0.0.0.0:$PORT`?

**Comment by DUOLabs333** [comment]
`sslocal` is running on `0.0.0.0:2015`, and I can connect with `<IP>:2015`

**Comment by zonyitoo** [comment]
Then everything is normal. 

Did you see any error logs?

**Comment by DUOLabs333** [comment]
Phone: `2021-11-30T08:09:53.471856236-05:00 DEBUG [5172:281473149808224] [shadowsocks_service::local::utils] established tcp tunnel 192.168.1.90:44860 <-> 151.101.2.137:443 through sever 127.0.0.1:2014 (outbound: 127.0.0.1:2014)`

Laptop: `2021-11-30T08:09:38.469108874-05:00 DEBUG [5172:281473145605728] [shadowsocks_service::local::socks::server::socks5::tcprelay] CONNECT update.googleapis.com:443`

**Comment by zonyitoo** [comment]
Where did you see "Connection refused"?

**Comment by DUOLabs333** [comment]
When I'm trying to connect to one of my local services on `127.0.0.1.nip.io:2001`

**Comment by zonyitoo** [comment]
What was listening on `127.0.0.1.nip.io:2001`

**Comment by zonyitoo** [comment]
```
Client (SagerNet) -> <ip>:2015 (sslocal) -> 127.0.0.1:$PORT (ssserver) -> 127.0.0.1.nip.io:2001
```

Is that correct?

**Comment by DUOLabs333** [comment]
A service on the server is on `localhost:2001`. `127.0.0.1.nip.io` just resolves to `localhost`.

**Comment by DUOLabs333** [comment]
Yes

**Comment by zonyitoo** [comment]
So where did you see "Connection refused"? On which part? 1 or 2 or 3 or 4?

**Comment by DUOLabs333** [comment]
The last part, when connecting to `127.0.0.1.nip.io:2001`

**Comment by zonyitoo** [comment]
Run `ssserver` with `-vvv` and see what exactly IP "127.0.0.1.nip.io" was resolved when reproduced.

**Comment by DUOLabs333** [comment]
It resolves to 127.0.0.1, but the problem is that the ports are not forwarded -- port 2001 on the server is not forwarded to port 2001 on my phone

**Comment by DUOLabs333** [comment]
With `curl`, it works fine.

**Comment by zonyitoo** [comment]
What do you mean “forward to phone”?

**Comment by zonyitoo** [comment]
You want to access to a server that running on the same machine with `ssserver` which listening on `127.0.0.1`, am I correct?

Did you check the `ssserver`'s log that it receives the request and then connected to your server?

**Comment by zonyitoo** [comment]
Answer my question please. Did you see the log?

**Comment by zonyitoo** [comment]
Then you should open an issue to SagerNet. I don't think there is anything related to shadowsocks-rust.

**Comment by DUOLabs333** [comment]
I did, they soon closed off issues though. I will note that this port forwarding only works on `SagerNet`, v2rayNG doesn't work at all, neither does Shadowsocks FOSS.

**Comment by zonyitoo** [comment]
Since `sslocal` and `ssserver` have already established the tunnel, I don't think there are anything I can help further.

You should look deep into your configuration and figure out what exactly the problem is. Feel free to reopen the issue if you have found the exact problem in shadowsocks-rust.

**Comment by DUOLabs333** [comment]
Does `ssserver`/`sslocal` have a rate limit or automatically block clients?

**Comment by zonyitoo** [comment]
No.

**Comment by DUOLabs333** [comment]
My configuration is fairly simple:

`ssserver`:
```
{
    "server": "127.0.0.1",
    "server_port": 2014,
    "password": "*******",
    "method": "aes-256-gcm",
    "mode": "tcp_and_udp",
    "dns": "127.0.0.1",
}
```

`sslocal`:
```
{
    "server": "127.0.0.1",
    "server_port": 2014,
    "password": "gq8jhYmrvyBzxumN",
    "method": "aes-256-gcm",
    "local_address": "0.0.0.0",
    "local_port": 2015,
    "mode": "tcp_and_udp",
    "nofile": 1024
}
```

**Comment by DUOLabs333** [comment]
My configuration is fairly simple:

`ssserver`:
```
{
    "server": "127.0.0.1",
    "server_port": 2014,
    "password": "*******",
    "method": "aes-256-gcm",
    "mode": "tcp_and_udp",
    "dns": "127.0.0.1",
}
```

`sslocal`:
```
{
    "server": "127.0.0.1",
    "server_port": 2014,
    "password": "********",
    "method": "aes-256-gcm",
    "local_address": "0.0.0.0",
    "local_port": 2015,
    "mode": "tcp_and_udp",
    "nofile": 1024
}
```

**Comment by zonyitoo** [comment]
I don't think there are anything to do with shadowsocks' configuration, since the tunnel have already been established, and you didn't see any ERROR logs in both `sslocal` and `ssserver`.

I can't do anything for you before you find any solid evidences about which part of shadowsocks-rust is broken or blocking your connections. Post logs or configuration or anything useful for debugging.

**Comment by DUOLabs333** [comment]
The interesting thing is that it works as expected with `curl` on Termux, so it's probably a thing with the SOCKS client I'm using.

**Comment by zonyitoo** [comment]
Now it is more likely that the problem was caused by some misconfiguration in SagerNet?

**Comment by DUOLabs333** [comment]
I reinstalled it, didn't change any settings, I'll see what happens.

**Comment by kda2000** [comment]
> I want to access the localhost of a remote server on the localhost of the phone.

终于搞懂你什么意思了，建议问问题直接一点，不要发无关的东西。虽然这个问题和shadowsocks-rust无关，我还是解答一下吧…

如果你要访问服务器的本地资源，没有必要搭建自定义DNS服务器。
你可以直接在客户端访问服务器的局域网IP，比如192.168.1.xxx，10.0.0.xxx。

![0E0DB358-E4A0-4501-AA7D-29B894D43B98](https://user-images.githubusercontent.com/95015672/144150977-07bb5799-07b5-4782-8cd6-7657e6148dd5.jpeg)


Tested on
Server: shadowsocks-rust
Client: Potatso Lite

**Comment by DUOLabs333** [comment]
Yes, but I would have to change it every time the IP address gets changed.

**Comment by DUOLabs333** [comment]
Also, all I get is `ERR_EMPTY_RESPONSE`

**Comment by DUOLabs333** [comment]
@zonyitoo It finally broke today.

**Comment by zonyitoo** [comment]
Provide useful details.

**Comment by DUOLabs333** [comment]
SagerNet just fails -- I can turn it on and ping `sslocal`, but trying to access `0.0.0.0:2001` fails where it worked before.

**Comment by kda2000** [comment]
I can confirm it's not an shadowsocks-rust bug, further discussion should move to SagerNet.

0.0.0.0 is not for CONNECT...
