### ISSUE TITLE
Address types 0x05, 0x43, 0x47 not supported

### ISSUE THREAD

**Issue by wilem82** [shadowsocks/shadowsocks-rust#705]
When I run it like that:

     ssserver -U -v -m none -b x.x.x.x -s x.x.x.x:8388

And then configure

- Firefox to use x.x.x.x:8388 as the socks5 proxy, `ssserver` logs "handshake failed, ... address type 0x5 not supported" and Firefox times out on trying to open anything
- Windows to use x.x.x.x:8388 and try with Edge, `ssserver` logs "handshake failed, ... address type 0x43 not supported" (on a rare occasion 0x43 turns into 0x47) and Edge times out on trying to open anything

I've checked Socks5's rfc and such address types simpyl don't exist. What could be wrong here please?

**Comment by KexyBiscuit** [comment]
`ssserver` doesn't provide SOCKS5 service, but [Shadowsocks](https://shadowsocks.org/) service only. You have to use `ssclient` or other compatible clients for connecting.

**Comment by zonyitoo** [comment]
You are trying to use `ssserver` as a socks5 server, which is completely wrong. `sslocal` is a socks5 server not `ssserver`.

**Comment by kda2000** [comment]
Run ssserver on SERVER,
Run sslocal on CLIENT.
sslocal host an local socks5 server, to translate between shadowocks and socks5.
