### ISSUE TITLE
run as server side in linux arm64 CPU 100%

### ISSUE THREAD

**Issue by cxjava** [shadowsocks/shadowsocks-rust#719]
when I run as server side in linux arm64(oracle cloud), the CPU is 100%.

command:
```shell
ssserver -s "[::]:8388" -m "aes-256-gcm" -k "hello-kitty" 
```
I have try those binary:

-  shadowsocks-v1.12.4.arm-unknown-linux-musleabi.tar.xz
- shadowsocks-v1.12.4.arm-unknown-linux-musleabihf.tar.xz

don't have log

**Comment by kda2000** [comment]
arm64 = aarch64
Try this:
https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.12.4/shadowsocks-v1.12.4.aarch64-unknown-linux-musl.tar.xz

Furthermore, consider your server's performance.

**Comment by zonyitoo** [comment]
`arm` is not for arm64 (aarch64). Use the `aarch64` packages.

**Comment by cxjava** [comment]
> arm64 = aarch64 Try this: https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.12.4/shadowsocks-v1.12.4.aarch64-unknown-linux-musl.tar.xz
> 
> Furthermore, consider your server's performance.
> 
> PS: I use Oracle Cloud too, it works well.

@kda2000  @zonyitoo Ok Thank you!
