### ISSUE TITLE
[snap] No such file or directory (os error 2)

### ISSUE THREAD

**Issue by yongri0** [shadowsocks/shadowsocks-rust#726]
install by snap
ubuntu 20.04
root user
config file  /etc/shadowsocks-rust/config.json

- ` shadowsocks-rust.ssserver -c /etc/shadowsocks-rust/config.json`

return 
- ` loading config "/etc/shadowsocks-rust/config.json", No such file or directory (os error 2)`

but input below can use
- ` shadowsocks-rust.ssserver -s <xxx.xxx.xxx.xxx>:<xxxx> -k <xxxxxxx> -m aes-256-gcm -d start`

please teach me ，thx

**Comment by zonyitoo** [comment]
What do you expect?

**Comment by yongri0** [comment]
> What do you expect?

`shadowsocks-rust.ssserver -c /etc/shadowsocks-rust/config.json`
i can't use config file, why?

**Comment by zonyitoo** [comment]
Try to put the file in `/var/snap/shadowsocks/common/etc/shadowsocks-rust/config.json`

**Comment by zonyitoo** [comment]
Close due to inactive.
