### ISSUE TITLE
[Suggestion] Replay-attack-detect enabled by default

### ISSUE THREAD

**Issue by sstpe** [shadowsocks/shadowsocks-rust#729]
Looking at [Cargo.toml](https://github.com/shadowsocks/shadowsocks-rust/blob/93f0fb7fa9e3d5a421616bf1da3d649e3f1c4b17/Cargo.toml#L53-L66), it seems like replay attack detection is not enabled by default. Is that correct?

Also, when I run `sslocal` and `ssserver` built with `cargo build --features "replay-attack-detect"`, I see in the trace `security: SecurityConfig { replay_attack: SecurityReplayAttackConfig { policy: Ignore } }`. That's no different to what I see in the trace when I build without `replay-attack-detect`.

It's possible I'm misunderstanding, but it seems to me that by default there is no replay attack detection, and when `--features "replay-attack-detect"` is specified, the policy is unchanged (still ignoring replays). Am I correct?

If so, my suggestion is to enable replay attack detection, and enable it by default.

Thanks!

**Comment by database64128** [comment]
The current Shadowsocks protocol lacks a timestamp in its header. And you can't tell whether a message is client-to-server or server-to-client, since both types of message is encrypted with a session key derived from the same master key. Therefore, it's not possible to properly implement replay protection without changing the protocol. See https://github.com/shadowsocks/shadowsocks-rust/pull/556#issuecomment-929180796.

**Comment by sstpe** [comment]
Thanks so much for pointing me to that discussion. It's a surprising
conclusion given the recommendations I thought I remembered from the
academic community. Maybe I'll have more questions, so I'll leave this
issue open for now, but I'll be away for a couple days.

Thanks again!

**Comment by sstpe** [comment]
Okay, after reading that discussion and some related ones, I noticed that there wasn't really a lot of consensus from the community at large about how to handle this, despite the issue having gone quiet for a while. I'm sure I may have missed a thread or two, but I read through https://github.com/net4people/bbs/issues/58 (which still recommends nonce and timing-based replay attack prevention), https://github.com/shadowsocks/shadowsocks-org/issues/183, the thread you sent, plus some discussions here and there.

Is Outline still using a replay filter? Is there consensus and/or recent work to refine the protocol I've missed?

Is it fair to say that we're still not sure the best ways to mitigate the theoretical replay attacks, but right now we're doing well enough, so for now it's a non-issue?

Thank you for your insight.

By the way, mostly out of curiosity, does that mean that https://github.com/shadowsocks/shadowsocks-windows/issues/3118 is not an issue any more?

**Comment by zonyitoo** [comment]
> Is Outline still using a replay filter? Is there consensus and/or recent work to refine the protocol I've missed?

Outline only have replay filter for TCP relays.

To make a conclusion, the community have found that the bloom filter based replay filter doesn't help to prevent probing from attackers. On the other hand, shadowsocks is a "fast tunnel proxy", so replay detection should be handled by upper level protocols, for example, TLS.

**Comment by sstpe** [comment]
> To make a conclusion, the community have found that the bloom filter based replay filter doesn't help to prevent probing from attackers. On the other hand, shadowsocks is a "fast tunnel proxy", so replay detection should be handled by upper level protocols, for example, TLS.

So, the suggested replay attack mitigation is using shadowsocks-over-TLS? Or are you saying that because most shadowsocks traffic is going to be TLS-over-shadowsocks, replay detection is already handled sufficiently?

Does this mean that the only mitigations we have now compared to when [How China Detects and Blocks Shadowsocks](https://gfw.report/publications/imc20/data/paper/shadowsocks.pdf#page=9) was released are:
- Consistent server reaction to probes (see page 9), since shadowsocks-libev v3.3.1 and outline v1.0.7
- Always using AEAD ciphers

Is that correct?

Thanks!

**Comment by zonyitoo** [comment]
You don't need to add any obfuscation on shadowsocks, because nearly all your application requests are using TLS. If the attacker replays your data stream, then the TLS request must be rejected by the target servers.

**Comment by sstpe** [comment]
Makes sense. Is my understanding correct that AEAD ciphers and consistent server reactions to probes have been good enough? Were there other developments I'm not thinking of? Just want to make sure I understand :)

**Comment by zonyitoo** [comment]
The community has some ideas about how to improve the protocol, but currently there is nothing making progress.
