### ISSUE TITLE
[::1]:1081 and 127.0.0.1:1081 on one client

### ISSUE THREAD

**Issue by BigmenPixel0** [shadowsocks/shadowsocks-rust#732]
Is it possible on one client to run the proxy on `[::1]:1081` and `127.0.0.1:1081`?

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust#configuration

Configure 2 clients with `locals`.

**Comment by BigmenPixel0** [comment]
> https://github.com/shadowsocks/shadowsocks-rust#configuration
> 
> Configure 2 clients with `locals`.

Maybe it will be more convenient if, when you specify [::1], shadowsocks will listen to 127.0.0.1 as well, as is done [here](https://github.com/shadowsocks/shadowsocks-rust/blob/77bc0fc7ec094bfb541f06f5661693f53011d1eb/README.md?plain=1#L488)?

**Comment by database64128** [comment]
@BigmenPixel0 You can't make one socket listen on `::1` and `127.0.0.1` at the same time. The `IPV6_V6ONLY` socket option only works if you listen on `::`.

**Comment by zonyitoo** [comment]
> > [shadowsocks/shadowsocks-rust#configuration](https://github.com/shadowsocks/shadowsocks-rust#configuration)
> > Configure 2 clients with `locals`.
> 
> Maybe it will be more convenient if, when you specify [::1], shadowsocks will listen to 127.0.0.1 as well, as is done [here](https://github.com/shadowsocks/shadowsocks-rust/blob/77bc0fc7ec094bfb541f06f5661693f53011d1eb/README.md?plain=1#L488)?

It is impossible for socket APIs. I can only make it possible by creating two individual listeners listening on `::1` and `127.0.0.1`, which is exactly the same as specifying 2 local instances in `locals`.

Why do you think that specifying 2 individual locals in configuration is inconvenient?

**Comment by BigmenPixel0** [comment]
> Why do you think that specifying 2 individual locals in configuration is inconvenient?

I couldn't do it, but this is of course my problem. I can probably solve this, so consider that the problem is solved then.
