### ISSUE TITLE
proposal(deploy): support k8s cloud native deployment

### ISSUE THREAD

**Issue by longkai** [shadowsocks/shadowsocks-rust#739]
I've been deploying shadowsocks in Kubernetes with a cloud provider or bare metal node for a while, and its deployment experience is really fine.

What's more, we can leverage k8s Service to expose traffic outside, like `LoadBalancer` or `NodePort` which gains more fine-grained compare with fixed host and port.

For a more interesting use case, we can use a Ingress(Istio, nginx, etc.) which routes the matched traffic to shadowsocks along with real web service.

I've written a helm chart with necessary values that user can modify(method, password, etd.), then `helm install` all the stuff into k8s with one click.

Or just generate the raw yaml then `kubectl apply -f shadowsocks.yaml`.

Since the cloud native is more popular, if you think this k8s deployment is fine, I would be happy send a PR.

Thank you for your nice work.

**Comment by kallydev** [comment]
This usage is very cool, I am very interested in it.

**Comment by longkai** [comment]
> This usage is very cool, I'm very interested in it.
> 
> Is it based on the Docker image we provide at GitHub Packages?

Yes.
