### ISSUE TITLE
Question on static-build linked

### ISSUE THREAD

**Issue by digeratus** [shadowsocks/shadowsocks-rust#74]
Hi YT,

I managed to build from source v1.6.5 on Ubuntu with success connecting to client and everything. Took me a long time mainly because I need to have all the Ubuntu tools to build from source and OpenSSL is a paying to install, but I figured it out.  After all that and after reading the code I can see that it’s safe, nothing suspicious. Which makes me think that for the next server I might just use the static-linked build and avoid having to deal with Ubuntu development tools.

With that in mind, if I take the latest version from here:
https://github.com/shadowsocks/shadowsocks-rust/releases

and unpack it in a linux x86 server, can I just run ssserver without having to “build” anything? In other words, just run it as a binary with the config.json file? sssever -c config.json and have it run?

Also, what’s the difference between these two gz files?
shadowsocks-v1.6.5-release.x86_64-unknown-linux-musl.tar.gz 7.3 MB
shadowsocks-v1.6.5-release.x86_64-unknown-linux-musl.tar.xz 9.66 MB

Thanks again for all the help. By the way, do you have a Telegram group or something other besides github issues to communicate with you? For example, this is not an issue, more of a question probably better handled somewhere else. I could help with the documentation for others who want to do the same. Hardly any good documentation on shadowsocks in general, most of it in Chinese.

**Comment by zonyitoo** [comment]
> and unpack it in a linux x86 server, can I just run ssserver without having to “build” anything? In other words, just run it as a binary with the config.json file? sssever -c config.json and have it run?

If your server is running with a x86_64 Linux system, then you can just run it out of box.

> Also, what’s the difference between these two gz files?
> shadowsocks-v1.6.5-release.x86_64-unknown-linux-musl.tar.gz 7.3 MB
> shadowsocks-v1.6.5-release.x86_64-unknown-linux-musl.tar.xz 9.66 MB

The only difference between these two files is: The first one is compressed by `gzip` and the second one is by `xz`.

I am appreciate with your passion. But I don't have any telegram groups.

**Comment by zonyitoo** [comment]
Close for inactivity.
