### ISSUE TITLE
Want to support s390x architecture

### ISSUE THREAD

**Issue by fengguowudi** [shadowsocks/shadowsocks-rust#740]
My server is s390x's cpu architecture, and the current release doesn't have a version that my machine can use.

**Comment by zonyitoo** [comment]
https://github.com/rust-embedded/cross

There is no way to build it with `cross`. Feel free to make a PR if you know how to cross compile it.

**Comment by zonyitoo** [comment]
This action may be a solution: https://github.com/marketplace/actions/run-on-architecture
