### ISSUE TITLE
希望能接收信号以重载配置

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-rust#748]
举个例子：
我启动 ssserver 的时候加载了插件，我的启动命令是
```sh
ssserver \
  --server-addr 0.0.0.0:1 \
  --password password \
  --encrypt-method chacha20-ietf-poly1305 \
  --timeout 3600 \
  --udp-timeout 300 \
  --udp-max-associations 1024 \
  --nofile 1048576 \
  --tcp-keep-alive 300 \
  --tcp-fast-open \
  --tcp-no-delay \
  -U \
  --plugin "xray-plugin" \
  --plugin-opts "server;tls;fast-open;mode=grpc;host=xxx.domain.com"
```
这个插件加载了 SSL 证书，假设是免费的证书，有效期只有 3 个月，虽然我设置了 acme.sh 自动续期证书，但是要重启 ssserver 的进程才能让证书生效。

所以想问下 ssserver 能否增加接收某个信号来重启自身进程这个功能？就像 `kill -SIGUSR1 <pid of ssserver>`

**Comment by zonyitoo** [comment]
I am using process managers to fulfull the exact same goal. OpenWRT: procd, Linux: systemd.

**Comment by pexcn** [comment]
请问 docker 有类似的功能吗？:grinning:

**Comment by zonyitoo** [comment]
Well, you can always package any process managers you flavored in Dockerfile.

**Comment by pexcn** [comment]
> Well, you can always package any process managers you flavored in Dockerfile.

意思是把 systemd 也打包进容器吗？好像有点大...

**Comment by zonyitoo** [comment]
How about [supervisord](http://supervisord.org/), which should be relatively smaller.

**Comment by zonyitoo** [comment]
Oh BTW, since you have set a crontab to call `acme.sh`, why not just kill the `ssserver` process and restart it after calling `acme.sh`?

**Comment by pexcn** [comment]
> Oh BTW, since you have set a crontab to call `acme.sh`, why not just kill the `ssserver` process and restart it after calling `acme.sh`?

acme.sh 的 docker 镜像是[这里](https://hub.docker.com/r/neilpang/acme.sh)提供的，它应该是自带了一个 Cron 来自动更新证书的，不是我自己设置的。

**Comment by pexcn** [comment]
目前打算使用 Systemd 定时器来定时重启 docker 容器来解决此问题了😀

**Comment by pexcn** [comment]
@zonyitoo 请问 ssservice 能否增加类似于 `nginx -s reload` 的功能？
因为根据 acme.sh 的[文档](https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers#2-deploy-certs-from-a-container-to-another-container)，可以通过配置 `DEPLOY_DOCKER_CONTAINER_RELOAD_CMD` 来达到更加优雅地重载证书

**Comment by zonyitoo** [comment]
What behavior do you expect for this `reload` feature?

**Comment by pexcn** [comment]
> What behavior do you expect for this `reload` feature?

发送 SIGUSR1 信号来重启 SS 本身和插件
发送 SIGUSR2 信号来重启插件
如果可以的话，并希望信号能传递到插件里面

**Comment by pexcn** [comment]
已通过 [restart-container.sh](https://github.com/pexcn/docker-images/blob/77addca1fe33d2eb022660894c1cba63f7b773d5/utils/acme.sh/restart-container.sh) 解决了
