### ISSUE TITLE
Build failing even with nightly

### ISSUE THREAD

**Issue by rimthekid** [shadowsocks/shadowsocks-rust#754]
error[E0635]: unknown feature `llvm_asm`
 --> /Users/farbod/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto2-0.1.2/src/lib.rs:2:21
  |
2 | #![feature(stdsimd, llvm_asm)]
  |                     ^^^^^^^^

   Compiling instant v0.1.12
For more information about this error, try `rustc --explain E0635`.
error: could not compile `crypto2` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `shadowsocks-rust v1.12.5`, intermediate artifacts can be found at `/var/folders/0_/pfgn12_s7tq6pl3hvgk9rd7h0000gn/T/cargo-installlwbxl3`

Caused by:
  build failed

I checked with two seperate pc's and still having this error using rustc 1.60.0-nightly (bfe156467 2022-01-22)

**Comment by dev4u** [comment]
#749

**Comment by zonyitoo** [comment]
If you are using the latest nightly, you will have to build with the latest master branch.
