### ISSUE TITLE
loading config "config", `protocol` invalid, unrecognized protocol dns

### ISSUE THREAD

**Issue by PHCSJC** [shadowsocks/shadowsocks-rust#759]
I want config and run local dns, bug get error.

./sslocal -c config

system: debian 10 amd64
version: shadowsocks 1.13.1

This is config:
{      
"local_address": "127.0.0.1",
    "local_port": 1080,
    "locals": [
        
	{
            "protocol": "dns",
            "local_address": "127.0.0.1",
            "local_port": 5353,
            "local_dns_address": "223.5.5.5",
            "local_dns_port": 53,
            "remote_dns_address": "8.8.8.8",
            "remote_dns_port": 53
        }

			],
	"servers": [
        {

            "address": "*.*.*.*",
            "port": 444,
            "method": "aes-256-gcm",
            "password": "*********"
		}
				]

}

**Comment by zonyitoo** [comment]
You have to build with `--features "local-dns"` to use `dns` protocol.
