### ISSUE TITLE
Can't build with --locked

### ISSUE THREAD

**Issue by BigmenPixel0** [shadowsocks/shadowsocks-rust#760]
If I run `cargo fetch` with `--locked` I get an error:

```
error: the lock file /tmp/makepkg/shadowsocks-rust/src/shadowsocks-rust-1.13.1/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
 ```
 
shadowsocks-rust version 1.13.1

**Comment by database64128** [comment]
Looks like you are the maintainer of the [`shadowsocks-rust` AUR package](https://aur.archlinux.org/packages/shadowsocks-rust). I have a few questions and suggestions on your `PKGBUILD`:

1. `arch` should not be `any`. You should explicitly list all supported architectures.
2. Why are `openssl` and `libsodium` listed as dependencies? They are not required by `shadowsocks-rust`.
3. Why explicitly disable LTO? Building shadowsocks-rust with LTO won't break. Actually LTO is explicitly enabled in `Cargo.toml` to improve performance for release builds.
4. Why add `-rust` suffix to `sslocal`, `ssserver`, and `ssurl`? Also, now that we have `ssservice`, you can simply create `sslocal`, `ssserver`, `ssmanager` as symlinks to `ssservice`. And these symlinks won't work if you name them with the `-rust` suffix. If @zonyitoo is willing to integrate `ssurl` into `ssservice`, then we can use a single binary for everything.
5. I don't think running tests when building the package is a good idea.
6. I don't think it's necessary to have a separate `fetch` run in `prepare()`.

**Comment by database64128** [comment]
Looking at Rust packages in the official repos, some of them skipped the `fetch` step, some omitted the tests, some have neither and some have both like your package does. Realistically, I don't think anyone installing the `shadowsocks-rust` package is interested in running the tests.

As for the LTO situation, I was wrong. You made the right call to explicitly disable LTO. Please also consider open an issue at https://github.com/briansmith/ring and attach the failed build logs.

**Comment by zonyitoo** [comment]
I just updated `Cargo.lock`.

> If @zonyitoo is willing to integrate ssurl into ssservice, then we can use a single binary for everything.

Well, the `ssurl` is not a required component. It is totally Ok to omit the `ssurl` binary in the `PKGBUILD`.

**Comment by zonyitoo** [comment]
> *3. I tried to compile with LTO, it didn’t work for me, so this is my problem? ([log](https://bin.snopyta.org/?9c897203667e9b59#42HT74dj4V59qzHhLVYAPnTZikvdBseL2d8ERpvtHK2E))

That was interesting! How to reproduce that? @BigmenPixel0

**Comment by BigmenPixel0** [comment]
> > *3. I tried to compile with LTO, it didn’t work for me, so this is my problem? ([log](https://bin.snopyta.org/?9c897203667e9b59#42HT74dj4V59qzHhLVYAPnTZikvdBseL2d8ERpvtHK2E))
> 
> That was interesting! How to reproduce that? @BigmenPixel0

Try building the `shadowsocks-rust` package from the AUR, but with the lto option enabled.

**Comment by database64128** [comment]
> That was interesting! How to reproduce that?

It’s not really related to this project, but if you are curious, Arch Linux’s build system can be configured to enable LTO by including `lto` in `OPTIONS` in `/etc/makepkg.conf`. It probably has nothing to do with Rust’s LTO.

**Comment by BigmenPixel0** [comment]
> As for the LTO situation, I was wrong. You made the right call to explicitly disable LTO. Please also consider open an issue at https://github.com/briansmith/ring and attach the failed build logs.

Already [exist](https://github.com/briansmith/ring/issues/1444).

**Comment by BigmenPixel0** [comment]
Problem solved, I'm closing the issue.

**Comment by BigmenPixel0** [comment]
The problem recurred in 1.14.1.

**Comment by zonyitoo** [comment]
What problem exactly?

**Comment by BigmenPixel0** [comment]
> What problem exactly?

```
error: the lock file /var/cache/makepkg/shadowsocks-rust/src/shadowsocks-rust-1.14.1/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

**Comment by zonyitoo** [comment]
Well, this is because the tag v1.14.1 was tagged on the wrong commit.

**Comment by zonyitoo** [comment]
Retagged. Please retry.

**Comment by BigmenPixel0** [comment]
> Retagged. Please retry.

It works, thanks.
