### ISSUE TITLE
[Bug] sslocal v1.13.0 onward crashing on Windows (x86_64-pc-windows-gnu)

### ISSUE THREAD

**Issue by sstpe** [shadowsocks/shadowsocks-rust#768]
Since v1.13.0, `sslocal` crashes on startup on Windows (`x86_64-pc-windows-gnu`).
Interestingly, `x86_64-pc-windows-msvc` seems to be fine.

As an example, using a minimal `sslocal` configuration of:
```
{
    "server":"ip-hidden",
    "server_port":52422,
    "local_port":12345,
    "password":"testpassword",
    "method":"chacha20-ietf-poly1305"
}
```
and running `.\sslocal.exe -c config.json -vvv` from a Windows machine yields:
```
TRACE [6084:8224] [shadowsocks_rust::service::local] Config { log: LogConfig { level: 3, format: LogFormatConfig { without_time: false }, config_path: None }, runtime: RuntimeConfig { worker_count: None, mode: MultiThread } }
```
The program exits there with no other output. Windows Event Viewer contains a log of the program crash, but no helpful information in the log, as far as I can tell.

This has been tested on `v1.13.0`, `v1.13.1`, and `v1.13.2` all downloaded from the Release page.

**Comment by zonyitoo** [comment]
> Windows Event Viewer contains a log of the program crash, but no helpful information in the log, as far as I can tell.

So the program actually crashed? Could you get the stack backtrace?

**Comment by zonyitoo** [comment]
Hmm, it couldn't reproduce in v1.12.x?

**Comment by sstpe** [comment]
Correct. Just re-tested v1.12.5. No issues.

**Comment by zonyitoo** [comment]
Try again with `aes-128-gcm` and see if it works.

**Comment by sstpe** [comment]
Just tried, but same issue.

**Comment by zonyitoo** [comment]
I don't have any Windows devices. :( I would need to find a way to reproduce it and see what exactly was happening.

Do you have any debug tools like GDB to help getting the actual stack backtrace or any useful information about where did it crashed?

**Comment by sstpe** [comment]
It seems to be something in the key generation from the password. The password looks right in the debugger, but the main thread overruns its stack inside this call:
https://github.com/shadowsocks/shadowsocks-rust/blob/5ffab23b72088220231bcc27d99e0a8e87080c35/crates/shadowsocks/src/config.rs#L188

`password.as_bytes()` and `enc_key` both look right in the debugger, as far as I can tell, so it seems to be the library code.

I tried modifying the size of my password to see if it was off-by-one error in the library, but it didn't help.

**Comment by sstpe** [comment]
Just noticed the most recent commit. I hoped https://github.com/shadowsocks/shadowsocks-crypto/commit/0185e54128a48c610521b50d854f5afb1ca58e42 would fix this, but it didn't. Same crash in the same place.

For reference, the crash takes place in this loop:
https://github.com/shadowsocks/shadowsocks-crypto/blob/0185e54128a48c610521b50d854f5afb1ca58e42/src/v1/cipher.rs#L153-L167
Specifically, the second iteration of the loop. `offset` is 16, `key_len` is 32, and it dies during `m.finalize()` on that iteration.

**Comment by zonyitoo** [comment]
I suspect that the `md5-asm` crate has bug on x86_64-pc-windows-gnu target.

**Comment by zonyitoo** [comment]
@sstpe Please try to compile with gnu toolchain with:

1. Compile it without setting any feature flags (or `RUSTFLAGS`)
2. Compile it with `RUSTFLAGS="-C target-cpu=native"`
3. Compile with shadowsocks-crypto on the master branch
    https://github.com/shadowsocks/shadowsocks-rust/blob/5ffab23b72088220231bcc27d99e0a8e87080c35/crates/shadowsocks/Cargo.toml#L76
    Replace this line to
    ```
    shadowsocks-crypto = { git = "https://github.com/shadowsocks/shadowsocks-crypto.git", features = ["ring"] }
    ```

Check if any of these methods could fix this issue.

**Comment by sstpe** [comment]
1. I think is the default way of building? Just `cargo build --bin sslocal` will do this, right? In that case, no effect
2. No effect
3. This has an effect: it will run until a request is made to the `sslocal` server. Then it will fail inside the creation of a new `EncryptedWriter` here:
https://github.com/shadowsocks/shadowsocks-rust/blob/5ffab23b72088220231bcc27d99e0a8e87080c35/crates/shadowsocks/src/relay/tcprelay/crypto_io.rs#L78
Specifically failing here:
https://github.com/shadowsocks/shadowsocks-rust/blob/5ffab23b72088220231bcc27d99e0a8e87080c35/crates/shadowsocks/src/relay/tcprelay/aead.rs#L311
Which fails here:
https://github.com/shadowsocks/shadowsocks-crypto/blob/724d2914238bf70630222478413c12ff50e80205/src/v1/cipher.rs#L296
Which dies in the HKDF library. In the debugger, the salt looks right in the library code, but it dies anyway somewhere in that call. Seems like library code again.
The final TRACE message emitted is that it generated the AEAD cipher salt.

**Comment by zonyitoo** [comment]
Thanks for very helpful information!

Then we can make a conclusion that `md5-asm` and `sha1-asm` is not working properly on x86_64-pc-windows-gnu.

**Comment by zonyitoo** [comment]
Please do method 3 again, which have disabled both `md5-asm` and `sha1-asm` for x86_64-pc-windows-gnu. If everything works fine, I will make a new release.
