### ISSUE TITLE
[Question] 使用 Rust 语言实现的加密库

### ISSUE THREAD

**Issue by LuoZijun** [shadowsocks/shadowsocks-rust#77]
请问使用 [DaGenix/rust-crypto](https://github.com/DaGenix/rust-crypto) 这个rust语言实现的加密库
能满足当前项目的需要吗？

这样似乎就可以直接 `cargo build` 而不需要 `brew install libsodium openssl` 了。

**Comment by zonyitoo** [comment]
```
Latest commit cc1a5fd  on 7 Sep 2016
```

So, the answer is: no.

**Comment by wongsyrone** [comment]
加密库和一般库不一样，我不认为用一个未经过专家审核过的rust原生库会有更多的优点。另外libsodium已经集成到了php里面。

**Comment by LuoZijun** [comment]
那是否可以把对 libsodium 的依赖编译写进 类似 build.rs 里面？这样可以减少安装流程。

**Comment by zonyitoo** [comment]
Please read README carefully:

> NOTE: If you haven't installed the correct version of libsodium in your system, you can set a environment variable SODIUM_BUILD_STATIC=yes to let libsodium-ffi to build libsodium from source, which requires you to have build tools (including GCC, libtools, etc.) installed.

**Comment by LuoZijun** [comment]
@zonyitoo sry，my mistake。
