### ISSUE TITLE
my ssserver version 1.13.2 was hijacked???

### ISSUE THREAD

**Issue by NeoGeoSNK** [shadowsocks/shadowsocks-rust#770]
The binary was compiled from cargo latest nightly build:

cargo +nightly install --force shadowsocks-rust

Now I see a lot of smtp egress traffic, which send too many spam mails to several address.

netstat -cnatp:

> tcp        0      1  myserver:33478     target_victim:25         SYN_SENT    479/ssserver 

My question is how ssserver able to send smtp request? Where is the configuration? How can I fix this issue?

Thanks

**Comment by zonyitoo** [comment]
`ssserver` itself won't send any stmp email requests. Maybe there is a client making stmp email requests with shadowsocks protocol to your `ssserver`'s listen port. I don't think there is anything related to this project.
