### ISSUE TITLE
Is there any possibility of compiling the ss-local as a wasm and use it inside the browser to connect to an ss-server?

### ISSUE THREAD

**Issue by miniyarov** [shadowsocks/shadowsocks-rust#778]
I am working on a browser extension to connect to my remote server and wonder if I can use ss-local inside the browser instead of relying on socks5.

**Comment by zonyitoo** [comment]
Maybe. You could give a try.

**Comment by 18o** [comment]
I think it couldn't work inside browser because no TCP or UDP support in browser. Also you need consider if Tokio can work in browser as it's based on mio which using epoll/iocp/kqueue .

**Comment by miniyarov** [comment]
There are some ways to use websockets as a TCP stream transport but still not much information on it I've found

**Comment by erikziyunchi** [comment]
Do you have any updates on this? Were you able to compile it into WASM?

**Comment by zonyitoo** [comment]
https://stackoverflow.com/questions/77402053/can-tokioruntime-be-used-in-wasm

Unfortunately yes.
