### ISSUE TITLE
Is UDP forward/relay supported?

### ISSUE THREAD

**Issue by digeratus** [shadowsocks/shadowsocks-rust#78]
Didn’t see this in the features. Just want to make sure.

**Comment by zonyitoo** [comment]
Yes, it is supported. But I have never tested it yet.

Please try to enable it by adding `"enable_udp": true` in configuration file or `-u` via command line.

Please send feedback if you have encountered any problems when using UDP relay. :)

**Comment by digeratus** [comment]
I'm trying to test it but don't know what I should be looking at. What is the benefit of having UDP forwarding?

**Comment by zonyitoo** [comment]
Some applications transfer data in UDP datagrams, such as games.

**Comment by zonyitoo** [comment]
Close because of inactivity.
