### ISSUE TITLE
[Compile] error E0308

### ISSUE THREAD

**Issue by xiashali** [shadowsocks/shadowsocks-rust#780]
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.61.0-nightly (03918badd 2022-03-07)

```
error[E0308]: mismatched types
  --> /home/algae/.cargo/registry/src/mirrors4.tuna.tsinghua.edu.cn-7180e12c232a1251/shadowsocks-service-1.14.0/src/dns/mod.rs:44:75
   |
44 |         DnsConfig::TrustDns(dns) => match DnsResolver::trust_dns_resolver(dns, ipv6_first).await {
   |                                                                           ^^^ expected struct `trust_dns_resolver::config::ResolverConfig`, found struct `ResolverConfig`
   |
   = note: perhaps two different versions of crate `trust_dns_resolver` are being used?

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `shadowsocks-rust v1.14.0 (registry `tuna`)`, intermediate artifacts can be found at `/tmp/cargo-installJM0i9n`
```

**Comment by zonyitoo** [comment]
Can you reproduce it with the `master` branch?

**Comment by gnattu** [comment]
I can confirm latest master (before 1.14.1 commit) fixed this. 

Using `stable-aarch64-unknown-linux-gnu updated - rustc 1.59.0 (9d1b2106e 2022-02-23)`

**Comment by zonyitoo** [comment]
The master was always compilable because there is no CI error on https://github.com/shadowsocks/shadowsocks-rust/actions

**Comment by zonyitoo** [comment]
It only happens when building from `crates.io`. I am trying to upgrade the edition of shadowsocks and shadowsocks-service to 2021 and see if it can fix this issue.

**Comment by gnattu** [comment]
This error happens to me when I was using `cargo install` to build it from create.

**Comment by xiashali** [comment]
`cargo install` shows two different `trust-dns-resolver` versions
 ```
Compiling trust-dns-resolver v0.20.4
Compiling shadowsocks v1.13.2
Compiling trust-dns-resolver v0.21.1
```

**Comment by zonyitoo** [comment]
That should be the root cause. Who is depending on `trust-dns-resolver v0.20.4`!

**Comment by gnattu** [comment]
The latest creates using `shadowsocks-service 1.41.1` is buildable for me.

**Comment by zonyitoo** [comment]
So there must be a bug with edition 2018.  Now shadowsocks-rust 1.41.1 is released to crates.io.
