### ISSUE TITLE
at most how many servers can I add in the config file

### ISSUE THREAD

**Issue by shawokou123** [shadowsocks/shadowsocks-rust#783]
in the documentation：
“ In shadowsocks-rust, we also have an extended configuration file format, which is able to define more than one server. ”

I have a question：

So at most how many servers can I add in the config file

**Comment by zonyitoo** [comment]
No one have tested it before. The balancer process will get slower to find the best server.

**Comment by shawokou123** [comment]
Thanks

 This is the best shadowsocks version I've ever used. In particular, on
Android, I use it in a termux environment.

ty ***@***.***> 于 2022年3月11日周五 16:53写道：
