### ISSUE TITLE
tcp redir of sslocal does not work with tproxy

### ISSUE THREAD

**Issue by 020794** [shadowsocks/shadowsocks-rust#784]
It seemed tcp redir sticked to "redirect" even though it was set to "tproxy" in the config.

command:
sslocal -c config.json

config.json:
{
  "server": "xxx.xxx",
  "server_port": 80, 
  "password": "1234567",
  "local_address": "0.0.0.0",
  "local_port": 1080,
  "tcp_redir": "tproxy",
  "protocol": "redir",
  "mode": "tcp_and_udp",
  "method": "aes-256-gcm",
  "plugin": "xray-plugin",
  "plugin_opts": "tls;host=xxx.xxx"
}

output:
2022-03-12T01:53:20.974451307+08:00 INFO  shadowsocks local 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
2022/03/12 01:53:20 Xray 1.5.3 (Xray, Penetrates Everything.) Custom (go1.17.6 linux/amd64)
2022/03/12 01:53:20 A unified platform for anti-censorship.
2022-03-12T01:53:20.980676805+08:00 INFO  shadowsocks TCP redirect (redirect) listening on 0.0.0.0:1080
2022-03-12T01:53:20.980761004+08:00 INFO  shadowsocks UDP redirect (tproxy) listening on 0.0.0.0:1080
2022/03/12 01:53:20 [Warning] core: Xray 1.5.3 started
2022/03/12 01:53:20 127.0.0.1:39502 accepted tcp:127.0.0.1:0
2022/03/12 01:53:21 127.0.0.1:39504 accepted tcp:127.0.0.1:0

**Comment by zonyitoo** [comment]
```json
{
    "locals": [
        {
            "local_address": "0.0.0.0",
            "local_port": 1080,
            "tcp_redir": "tproxy",
            "protocol": "redir"
        }
    ],
    "server": "xxx.xxx",
    "server_port": 80,
    "password": "1234567",
    "mode": "tcp_and_udp",
    "method": "aes-256-gcm",
    "plugin": "xray-plugin",
    "plugin_opts": "tls;host=xxx.xxx"
}
```

Extended configuration key is only working in `locals` and `servers`. Read the documentation carefully. https://github.com/shadowsocks/shadowsocks-rust/blob/master/README.md#configuration

**Comment by 020794** [comment]
> servers



> ```json
> {
>     "locals": [
>         {
>             "local_address": "0.0.0.0",
>             "local_port": 1080,
>             "tcp_redir": "tproxy",
>             "protocol": "redir"
>         }
>     ],
>     "server": "xxx.xxx",
>     "server_port": 80,
>     "password": "1234567",
>     "mode": "tcp_and_udp",
>     "method": "aes-256-gcm",
>     "plugin": "xray-plugin",
>     "plugin_opts": "tls;host=xxx.xxx"
> }
> ```
> 
> Extended configuration key is only working in `locals` and `servers`. Read the documentation carefully. https://github.com/shadowsocks/shadowsocks-rust/blob/master/README.md#configuration

my bad
