### ISSUE TITLE
ShadowSocks with Wireguard

### ISSUE THREAD

**Issue by airled** [shadowsocks/shadowsocks-rust#785]
Hi. WireGuard is not working via shadowsocks-rust 1.14.1.
Server config:
```json
{
  "server": "0.0.0.0",
  "server_port": 14000,
  "password": "pass",
  "timeout": 300,
  "method": "chacha20-ietf-poly1305",
  "mode": "tcp_and_udp"
}
```

client config:
```json
{
  "server": "server_ip",
  "server_port": 14000,
  "local_address": "0.0.0.0",
  "local_port": 5634,
  "password": "pass",
  "timeout": 300,
  "method": "chacha20-ietf-poly1305",
  "mode": "tcp_and_udp",
  "tunnel_address": "127.0.0.1:51820"
}
```

Wireguard config:
```
...
[Peer]
PublicKey = key
Endpoint = 127.0.0.1:5634
AllowedIPs = 0.0.0.0/0
```

When I up my wireguard interface, shadowsocks logs this error:
```
2022-03-12T13:47:52.408991642+06:00 INFO  shadowsocks local 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
2022-03-12T13:47:52.410106942+06:00 INFO  shadowsocks socks TCP listening on 0.0.0.0:5634
2022-03-12T13:47:52.410254412+06:00 INFO  shadowsocks socks5 UDP listening on 0.0.0.0:5634
2022-03-12T13:49:04.986322022+06:00 ERROR received invalid UDP associate packet: b"\x01\x00\x00\x00e\xd9a\...
```
Are my configs incorrect? Or is there a way to fix it?

**Comment by zonyitoo** [comment]
The `sslocal` is running in socks5 mode, so it is of course reporting errors when you are trying to send WireGuard UDP packets to it.

**Comment by database64128** [comment]
Use tunnel mode instead of SOCKS5.

**Comment by airled** [comment]
I add
```
"protocol": "tunnel"
```
to shadowsocks config, but now it forces me to specify forward-addr parameter. Can you please provide me what exactly should I use here to tunnel wireguard traffic?

**Comment by zonyitoo** [comment]
The forward address is the target address that specifies the "tunnel"'s endpoint. In this case, set forward address to your WireGuard server's address.

**Comment by airled** [comment]
Thank you for your help, but no luck. WireGuard is not working. No shadowsocks log either.

**Comment by zonyitoo** [comment]
What did you see? Try to add `-v` when starting `sslocal` and `ssserver`.

**Comment by airled** [comment]
`./ssserver --server-addr '0.0.0.0:14000' --encrypt-method 'chacha20-ietf-poly1305' -k 'pass' -u -v`
```
2022-03-12T09:52:20.779371491+01:00 INFO  [27707:139991275227520] [shadowsocks_rust::service::server] shadowsocks server 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
2022-03-12T09:52:20.781948930+01:00 INFO  [27707:139991275227520] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 0.0.0.0:14000
```

`./sslocal --local-addr '0.0.0.0:5634' --server-addr 'ip:14000' --encrypt-method 'chacha20-ietf-poly1305' -k 'pass' --protocol 'tunnel' -u -f 'ip' -v`
```
2022-03-12T14:52:35.231772575+06:00 INFO  [8292:139683997137408] [shadowsocks_rust::service::local] shadowsocks local 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
2022-03-12T14:52:35.233169122+06:00 INFO  [8292:139683997137408] [shadowsocks_service::local::tunnel::udprelay] shadowsocks UDP tunnel listening on 0.0.0.0:5634
2022-03-12T14:52:49.502851883+06:00 DEBUG [8292:139683997137408] [shadowsocks_service::local::tunnel::udprelay] created udp association for 127.0.0.1:52863
2022-03-12T14:52:49.567744566+06:00 DEBUG [8292:139683997132352] [shadowsocks::dns_resolver::resolver] auto-reload /etc/resolv.conf
```

That's all. No wireguard traffic.

**Comment by zonyitoo** [comment]
```
2022-03-12T14:52:49.502851883+06:00 DEBUG [8292:139683997137408] [shadowsocks_service::local::tunnel::udprelay] created udp association for 127.0.0.1:52863
```

It had already created an association for your wireguard client.

The `-f` is `ip:port`, which is your Wireguard server's ip:port (address).

**Comment by airled** [comment]
`./sslocal --local-addr '0.0.0.0:5634' --server-addr 'ip:14000' --encrypt-method 'chacha20-ietf-poly1305' -k 'pass' --protocol 'tunnel' -u -f 'ip:51820' -v`

```
2022-03-12T15:05:58.296755016+06:00 INFO  [9719:140588295617024] [shadowsocks_rust::service::local] shadowsocks local 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
2022-03-12T15:05:58.301582638+06:00 INFO  [9719:140588295617024] [shadowsocks_service::local::tunnel::udprelay] shadowsocks UDP tunnel listening on 0.0.0.0:5634
2022-03-12T15:06:03.503786903+06:00 DEBUG [9719:140588295617024] [shadowsocks_service::local::tunnel::udprelay] created udp association for 127.0.0.1:40035
2022-03-12T15:06:04.319058997+06:00 DEBUG [9719:140588293510720] [shadowsocks::dns_resolver::resolver] auto-reload /etc/resolv.conf
```

Still no traffic.

**Comment by zonyitoo** [comment]
You won't see any traffic from logs. Does `ssserver` show `created udp association` log?

**Comment by airled** [comment]
No, only initialization entries.

**Comment by zonyitoo** [comment]
So I think `sslocal` couldn't send any UDP packets to `ip:14000`, or `ssserver` couldn't receive any packets from `sslocal`.

You may try to run both `sslocal` and `sserver` locally in the same environment and add `-vvv` on both `sslocal` and `ssserver` and see what exactly happening.

**Comment by database64128** [comment]
Note that the forward address is relative to the Shadowsocks server. That is, if you run your `ssserver` on the same machine as your WireGuard server, you can use `-f [::1]:port`.

**Comment by airled** [comment]
> So I think `sslocal` couldn't send any UDP packets to `ip:14000`, or `ssserver` couldn't receive any packets from `sslocal`.
> 
> You may try to run both `sslocal` and `sserver` locally in the same environment and add `-vvv` on both `sslocal` and `ssserver` and see what exactly happening.

I run both ssserver and sslocal on my local machine. When I up wg interface I see association entries in both logs. Are you sure, that my run commands for ssserver and sslocal are correct? I'm pretty sure that udp traffic is not blocked since wireguard works absolutely fine without shadowsocks .

**Comment by zonyitoo** [comment]
If sslocal and ssserver are both running on the same machine, try to set `—server-addr 127.0.0.1:14000`.

I don’t have much ideas about why your ssserver didn’t receive any packets from sslocal.

**Comment by airled** [comment]
Well, thank you for trying to help. Seems like I should try to find another solution.

**Comment by database64128** [comment]
Did you lower your WireGuard tunnel's MTU? The default 1420 assumes using IPv6 with a PMTU of 1500. When encapsulating WireGuard packets into Shadowsocks, the final Shadowsocks packet may exceed your on-path MTU and get silently dropped by routers.

You are using ChaCha20-Poly1305, which introduces overhead of a 32-byte salt and a 16-byte tag. The SOCKS address header should be 1+4+2 bytes long for IPv4 targets and 1+16+2 bytes long for IPv6 targets. Therefore, you should lower your WireGuard tunnel MTU to 1420-32-(1+16+2)-16=1353.

**Comment by airled** [comment]
> Did you lower your WireGuard tunnel's MTU? The default 1420 assumes using IPv6 with a PMTU of 1500. When encapsulating WireGuard packets into Shadowsocks, the final Shadowsocks packet may exceed your on-path MTU and get silently dropped by routers.
> 
> You are using ChaCha20-Poly1305, which introduces overhead of a 32-byte salt and a 16-byte tag. The SOCKS address header should be 1+4+2 bytes long for IPv4 targets and 1+16+2 bytes long for IPv6 targets. Therefore, you should lower your WireGuard tunnel MTU to 1420-32-(1+16+2)-16=1353.

Thank you, I set wg MTU to 1200 but still no luck.

**Comment by zonyitoo** [comment]
I don't think there are any obvious obstacles to use shadowsocks' tunnel to relay WireGuard's UDP packets.

An idea come up to my mind: Maybe the packet sent from `sslocal` is routed back to WireGuard's tun interface, which is why it cannot reached to `ssserver`? I don't know. You could try to run the `sslocal` on another machine and see if it works.

**Comment by database64128** [comment]
On another note, you should not set the tunnel MTU anywhere below 1280. 1280 is the minimum MTU of IPv6.

**Comment by airled** [comment]
@zonyitoo @database64128 Something changed. I disabled automatic wireguard routing with `Table = off` in wg config. Now ssserver see association but raise this error:
```

**Comment by zonyitoo** [comment]
> @zonyitoo @database64128 Something changed. I disabled automatic wireguard routing with `Table = off` in wg config. Now ssserver see association but raise this error:
> 
> ```
> 2022-03-12T18:24:42.853568343+01:00 INFO  [23061:139631187380608] [shadowsocks_rust::service::server] shadowsocks server 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
> 2022-03-12T18:24:42.855348318+01:00 INFO  [23061:139631187380608] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 0.0.0.0:14000
> 2022-03-12T18:25:10.750847648+01:00 DEBUG [23061:139631187380608] [shadowsocks_service::server::udprelay] created udp association for 188.232.116.227:52075
> 2022-03-12T18:25:10.751594327+01:00 ERROR [23061:139631187380608] [shadowsocks_service::server::udprelay] udp server recv_from failed with error: invalid tag-in
> ```
> 
> Any ideas?

This is a crypto error, which means that the `ssserver` failed to decrypt the received packet.

Do `sslocal` and `ssserver` share the same `method` and `password`?

Or maybe it is packet too large to fit in an UDP frame? Did you set the maximum UDP packet size in WG?

**Comment by airled** [comment]
> > @zonyitoo @database64128 Something changed. I disabled automatic wireguard routing with `Table = off` in wg config. Now ssserver see association but raise this error:
> > ```
> > 2022-03-12T18:24:42.853568343+01:00 INFO  [23061:139631187380608] [shadowsocks_rust::service::server] shadowsocks server 1.14.1 build 2022-03-08T08:30:30.667857105+00:00
> > 2022-03-12T18:24:42.855348318+01:00 INFO  [23061:139631187380608] [shadowsocks_service::server::udprelay] shadowsocks udp server listening on 0.0.0.0:14000
> > 2022-03-12T18:25:10.750847648+01:00 DEBUG [23061:139631187380608] [shadowsocks_service::server::udprelay] created udp association for 188.232.116.227:52075
> > 2022-03-12T18:25:10.751594327+01:00 ERROR [23061:139631187380608] [shadowsocks_service::server::udprelay] udp server recv_from failed with error: invalid tag-in
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any ideas?
> 
> This is a crypto error, which means that the `ssserver` failed to decrypt the received packet.
> 
> Do `sslocal` and `ssserver` share the same `method` and `password`?
> 
> Or maybe it is packet too large to fit in an UDP frame? Did you set the maximum UDP packet size in WG?

Yeap, the password and the encryption method and the same. Not sure abount udp packet size. If you mean MTU then I set 1300 in wireguard config. Still doesn't work.

**Comment by Theo-Silfa** [comment]
Hey guys. I'm trying to do almost the same thing here but it seems that ssserver forwards udp traffic only one direction.
I do `nc -u -l <tunneled-port>` on the server and `nc -u localhost <sslocal-local-port>` on the client. Typing smth in to the client will show the data on the server but the reverse doesn't work. Tried the same thing with tcp and everything worked. Same behaviour is observed in libev implementation.
Is it a bug or expected behaviour? 😕

**Comment by zonyitoo** [comment]
Just simply use `dig xxxxxxx` and you can verify whether the UDP association works as expected.

**Comment by drew1kun** [comment]
> It works now without automatic wg routing. `-f` value was incorrect. It was as `ip:14000` but should be `ip:51820`. I can now route my wg traffic via shadowsocks tunnel. But also I should investigate now how to forward all my traffic again via wg, not only custom routes.

Hi @airled, I am trying the same thing but without any luck. Could you please show client config and the command how do you run it? Thank you.

**Comment by drew1kun** [comment]
My setup:

SS server config:
```json
{
  "servers": [
    {
      "mode":"tcp_and_udp",
      "server":"0.0.0.0",
      "server_port":8388,
      "fast_open":false,
      "timeout":300,
      "method":"aes-256-gcm",
      "password":"PASS"
    }
  ]
}
```

SS Client Config `~/shadowsocks-rust-wg-tunnel.json` (in accordance with [documentation](https://github.com/shadowsocks/shadowsocks-rust/blob/master/README.md)):
```json
{
    "mode":"udp_only",
    "protocol":"tunnel",
    "server":"<ss_server_ip>",
    "server_port":8388,
    "local_address":"127.0.0.1",
    "local_port":51821,
    "password":"PASS",
    "method":"aes-256-gcm"
    "forward_address":"<wireguard_ip>"
    "forward_port":"<wireguard_port_51820>",
}
```
Running client with:
```
sslocal -c ~/shadowsocks-rust-wg-tunnel.json
config integrity check failed, missing `forward_addr` in configuration
```
What am I doing wrong?
Should I remove `"protocol":"tunnel",` and use `"tunnel_address": "127.0.0.1:51820"`?
Or should it be `"tunnel_address": "<wireguard_ip>:51820"` instead?
Please help.

**Comment by drew1kun** [comment]
Well, I managed it to work setting `MTU = 1384` on client wireguard config and running ss client this way:
```
sslocal --local-addr '127.0.0.1:51821' --server-addr '<ss_server_IP>:8388' --encrypt-method 'aes-256-gcm' -k 'SS_PASS' --protocol 'tunnel' -u -f '<wireguard_server_IP>:51820' -v
```
But how do I translate this into config? With `"protocol":"tunnel",` set in `~/shadowsocks-rust-wg-tunnel.json` still receiving the error mentioned above. Any ideas?

**Comment by drew1kun** [comment]
Posting here update for information purposes. The working config looks like this:
```json
{
    "server":"<ss_server_IP>",
    "server_port":8388,
    "password":"SS_PASS",
    "method":"aes-256-gcm",
    "locals": [
        {
            "mode":"udp_only",
            "protocol":"tunnel",
            "forward_address":"<wireguard_IP>",
            "forward_port":"<wireguard_port_51820>",
            "local_address":"127.0.0.1",
            "local_port":51821
        }
    ]
}
```
WG config:
```
[Interface]
PrivateKey = PRIV_KEY
ListenPort = 51820
Address = 10.0.9.10/24
DNS = 1.1.1.1, search.domain
MTU = 1384

[Peer]
PublicKey = PUB_KEY
PresharedKey = PRESHARED_KEY
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = localhost:51821
PersistentKeepalive = 25
```

The only thing is that wireguard connection now looks somewhat unstable. I set up `MTU = 1384` . But it seems it does not work sometimes. I run `pings 8.8.8.8` and `ping 192.168.10.10`(host within the VPN network), in order to see if Wireguard over Shadowsocks works after I press connect on wireguard UI. Sometimes I need to disconnect and connect again, in order to see the pings... It is kind of a lottery instead of stable connection. @database64128 could that be related to the MTU number I use, and how do I find out the recommended value? Maybe someone could suggest any other configuration in order to maximize stability of WG tunneling over SS? Thank you.

**Comment by database64128** [comment]
@drew1kun `aes-256-gcm` has the same amount of overhead as `chacha20-poly1305`, so you can just follow the recommendation in https://github.com/shadowsocks/shadowsocks-rust/issues/785#issuecomment-1065854775.

You might also be interested in this project of mine: https://github.com/database64128/swgp-go. The zero-overhead mode can be used to proxy WireGuard traffic without affecting the tunnel MTU.

**Comment by Bromelioideae** [comment]
> Posting here update for information purposes. The working config looks like this:
> 
> ```json
> {
>     "server":"<ss_server_IP>",
>     "server_port":8388,
>     "password":"SS_PASS",
>     "method":"aes-256-gcm",
>     "locals": [
>         {
>             "mode":"udp_only",
>             "protocol":"tunnel",
>             "forward_address":"<wireguard_IP>",
>             "forward_port":"<wireguard_port_51820>",
>             "local_address":"127.0.0.1",
>             "local_port":51821
>         }
>     ]
> }
> ```
> 
> WG config:
> 
> ```haproxy-config
> [Interface]
> PrivateKey = PRIV_KEY
> ListenPort = 51820
> Address = 10.0.9.10/24
> DNS = 1.1.1.1, search.domain
> MTU = 1384
> 
> [Peer]
> PublicKey = PUB_KEY
> PresharedKey = PRESHARED_KEY
> AllowedIPs = 0.0.0.0/0, ::/0
> Endpoint = localhost:51821
> PersistentKeepalive = 25
> ```

Thank you, thank you, thank you! I was finally able to get this config working after hours of tinkering. I initially got it to work a few hours ago but after restarting the server to confirm everything was okay, nothing was. My wireguard was slow, the regular shadowsocks connection was slow and the tunnel didn't work any at all. If I wasn't fully conscious I would have thought I dreamt it. Instead of going back to the basics I was searching for irrelevant solutions as I knew the connections were stable before and I had seen the tunnel in operation. The base issue turned out to be that both my unbound dns server and another instance of shadowsocks were both disabled, not quite sure how that happened but those were the causes of my slow regular ss and my regular wireguard,

After resolving those issues the regular connections became stable again so I went back to trying the tunnel. I am currently using Windows so I defaulted to using the Windows gui app. That works fine for ss and cloak+ss but each time I edited the config to add the locals tunnel section it would remove the section on closing the app. I went down the rabbit hole and had to follow the config from a commercial VPN vendor to realise that I had to use the command line app. So I downloaded the windows "msvc" version and tried that and it worked without issue . 

Then I started having the issues mentioned before so after getting the connections stable and another long round of searching without touching the config that I knew to work I realised that I was trying to force cloak and another unobfuscated server to live on the same port 443. Despite configuring the cloaked server to only use UDP, I the ss client seemed to prefer to connect to the cloak server on TCP 443 when connecting even though a ss server on UDP 443 was available. As a test I disable the cloak server on TCP 443 and I am now using the tunnel. 

I hope I will never have the real NEED to use this solution but I hope your work on this and my little clarifiers will assist those who do. My next steps are to try and get the tunnel obfuscated with cloak. In the meantime I need to figure how to run the command line app automatically on windows boot and how to create a shortcut or something that launches the app and puts it in the background while still available to shutdown.

**Comment by hiiamboris** [comment]
@drew1kun have you found a solution for the lottery behavior? For me it has like 5-10% to connect successfully.

**Comment by drew1kun** [comment]
@hiiamboris unfortunately, the only solution I have found so far is to use shadowsocks-libev instead.

**Comment by hiiamboris** [comment]
Which on Windows isn't an option because doesn't support tunnels or any custom config :/

**Comment by zonyitoo** [comment]
> @hiiamboris unfortunately, the only solution I have found so far is to use shadowsocks-libev instead.

What's the actual problem you have found at that time exactly?

**Comment by anthonyma94** [comment]
Apologies for necro-ing this post, but I'm having issues with connecting Wireguard on Windows through Shadowsocks.

SS Server
```json
{
        "server": "0.0.0.0",
        "server_port": 21638,
        "password": "pass",
        "timeout": 300,
        "method": "aes-256-gcm",
        "mode": "tcp_and_udp"
}
```
WG Server
```ini
[Interface]
Address = 10.66.66.1/24
ListenPort = 60820
PrivateKey = private

[Peer]
PublicKey = public
AllowedIPs = 10.66.66.3/32
PersistentKeepalive = 30
```
SS Client
```json
{
	"server": "server_IP",
	"server_port": 21638,
	"password": "pass",
	"method": "aes-256-gcm",
	"locals": [
		{
			"mode": "udp_only",
			"protocol": "tunnel",
			"forward_address": "server_IP",
			"forward_port": 60820,
			"local_address": "127.0.0.1",
			"local_port": 1080
                }
	]
}
```
WG Client
```ini
[Interface]
PrivateKey = private
Address = 10.66.66.3/24
DNS = 1.1.1.1
MTU = 1353

[Peer]
PublicKey = public
AllowedIPs = 0.0.0.0/0
Endpoint = 127.0.0.1:1080
```

Running `sslocal -c config.json -v` shows a udp association every time WG is activated. `ssserver -c config.json -v` however doesn't show it receiving a connection (not sure if it would given it's UDP).

sslocal
```
2025-01-02T12:51:43.0631887-05:00  INFO main ThreadId(01) shadowsocks_rust::service::local: shadowsocks local 1.22.0 build 2025-01-02T14:54:14.474672314+00:00
2025-01-02T12:51:43.0639296-05:00  WARN main ThreadId(01) shadowsocks_service::local::loadbalancing::ping_balancer: no valid UDP server serving for UDP clients, consider disable UDP with "mode": "tcp_only", currently chose server_IP:21638
2025-01-02T12:51:43.0658431-05:00  INFO tokio-runtime-worker ThreadId(13) shadowsocks_service::local::tunnel::udprelay: shadowsocks UDP tunnel listening on 127.0.0.1:1080
2025-01-02T12:51:47.088844-05:00 DEBUG tokio-runtime-worker ThreadId(04) shadowsocks_service::local::net::udp::association: created udp association for 127.0.0.1:57790
```

ssserver
```
2025-01-02T17:56:53.783667783Z DEBUG main ThreadId(01) shadowsocks_rust::sys: rlimit NOFILE adjusted rlimit { rlim_cur: 1048576, rlim_max: 1048576 }
2025-01-02T17:56:53.783718573Z  INFO main ThreadId(01) shadowsocks_rust::service::server: shadowsocks server 1.22.0 build 2025-01-02T14:53:49.390696600+00:00
2025-01-02T17:56:53.784433608Z  INFO tokio-runtime-worker ThreadId(02) shadowsocks_service::server::tcprelay: shadowsocks tcp server listening on 0.0.0.0:21638, inbound address 0.0.0.0:21638
2025-01-02T17:56:53.784555262Z  INFO tokio-runtime-worker ThreadId(02) shadowsocks_service::server::udprelay: shadowsocks udp server listening on 0.0.0.0:21638, inbound address 0.0.0.0:21638
```

Any help is greatly appreciated!

**Comment by Maahdima** [comment]
> Apologies for necro-ing this post, but I'm having issues with connecting Wireguard on Windows through Shadowsocks.
> 
> SS Server
> 
> {
>         "server": "0.0.0.0",
>         "server_port": 21638,
>         "password": "pass",
>         "timeout": 300,
>         "method": "aes-256-gcm",
>         "mode": "tcp_and_udp"
> }
> WG Server
> 
> [Interface]
> Address = 10.66.66.1/24
> ListenPort = 60820
> PrivateKey = private
> 
> [Peer]
> PublicKey = public
> AllowedIPs = 10.66.66.3/32
> PersistentKeepalive = 30
> SS Client
> 
> {
> 	"server": "server_IP",
> 	"server_port": 21638,
> 	"password": "pass",
> 	"method": "aes-256-gcm",
> 	"locals": [
> 		{
> 			"mode": "udp_only",
> 			"protocol": "tunnel",
> 			"forward_address": "server_IP",
> 			"forward_port": 60820,
> 			"local_address": "127.0.0.1",
> 			"local_port": 1080
>                 }
> 	]
> }
> WG Client
> 
> [Interface]
> PrivateKey = private
> Address = 10.66.66.3/24
> DNS = 1.1.1.1
> MTU = 1353
> 
> [Peer]
> PublicKey = public
> AllowedIPs = 0.0.0.0/0
> Endpoint = 127.0.0.1:1080
> Running `sslocal -c config.json -v` shows a udp association every time WG is activated. `ssserver -c config.json -v` however doesn't show it receiving a connection (not sure if it would given it's UDP).
> 
> sslocal
> 
> ```
> 2025-01-02T12:51:43.0631887-05:00  INFO main ThreadId(01) shadowsocks_rust::service::local: shadowsocks local 1.22.0 build 2025-01-02T14:54:14.474672314+00:00
> 2025-01-02T12:51:43.0639296-05:00  WARN main ThreadId(01) shadowsocks_service::local::loadbalancing::ping_balancer: no valid UDP server serving for UDP clients, consider disable UDP with "mode": "tcp_only", currently chose server_IP:21638
> 2025-01-02T12:51:43.0658431-05:00  INFO tokio-runtime-worker ThreadId(13) shadowsocks_service::local::tunnel::udprelay: shadowsocks UDP tunnel listening on 127.0.0.1:1080
> 2025-01-02T12:51:47.088844-05:00 DEBUG tokio-runtime-worker ThreadId(04) shadowsocks_service::local::net::udp::association: created udp association for 127.0.0.1:57790
> ```
> 
> ssserver
> 
> ```
> 2025-01-02T17:56:53.783667783Z DEBUG main ThreadId(01) shadowsocks_rust::sys: rlimit NOFILE adjusted rlimit { rlim_cur: 1048576, rlim_max: 1048576 }
> 2025-01-02T17:56:53.783718573Z  INFO main ThreadId(01) shadowsocks_rust::service::server: shadowsocks server 1.22.0 build 2025-01-02T14:53:49.390696600+00:00
> 2025-01-02T17:56:53.784433608Z  INFO tokio-runtime-worker ThreadId(02) shadowsocks_service::server::tcprelay: shadowsocks tcp server listening on 0.0.0.0:21638, inbound address 0.0.0.0:21638
> 2025-01-02T17:56:53.784555262Z  INFO tokio-runtime-worker ThreadId(02) shadowsocks_service::server::udprelay: shadowsocks udp server listening on 0.0.0.0:21638, inbound address 0.0.0.0:21638
> ```
> 
> Any help is greatly appreciated!

Any solution for the problem?
Ive got this too.
Thanks.

**Comment by hiiamboris** [comment]
Try [sing-box](https://sing-box.sagernet.org/configuration/) instead as it is tailored to creating complex tunnels.

**Comment by temach** [comment]
Here is my working configuration to tunnel/obfuscate wireguard via shadowsocks.

It works as follows:
```
curl foo.com (on client) 
|
V
wireproxy (on client, so only traffic on one port is wireguarded hence exclusion rules for sslocal are NOT necessary)
|
V
sslocal (on client) 
|
V
ssserver (on remote) 
|
V
wireguard (on remote)
|
V
foo.com (whatever other remote server)
```


wireguard (on same VM as shadowsocks server, with https://github.com/wg-easy/wg-easy) docker-compose.yaml:
```yaml
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=example.org
      - PASSWORD=MY_PASS
      - WG_PORT=51820

    image: ghcr.io/wg-easy/wg-easy:13
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

shadowsocks remote server config.json:
```json
{
	"servers": [
		{
			"server":"0.0.0.0",
			"server_port":8388,
			"password":"PASSWORD",
			"method":"aes-256-gcm",
			"mode": "tcp_and_udp"
		}
	]
}
```
shadowsocks remote server docker-compose.yaml:
```yaml
services:
  ssserver-rust:
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    container_name: ssserver-rust
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    command: "ssserver --log-without-time -a nobody -vvv -c /etc/shadowsocks-rust/config.json"
    volumes:
      - ./config.json:/etc/shadowsocks-rust/config.json
```



The sslocal (forward_address configures how to reach wireguard udp endpoint) config.json:
```json
{
	"servers": [
		{
			"server":"188.212.100.100",
			"server_port":8388,
			"password":"PASSWORD",
			"method":"aes-256-gcm"
		}
	],
	"locals": [
		{
			"mode":"tcp_and_udp",
			"protocol":"tunnel",
			"local_address":"127.0.0.1",
			"local_port":8388,
			"forward_address":"188.212.100.100",
			"forward_port":51820
		}
	]
}
```



The wireguard client that routes traffic into sslocal:
```ini
[Interface]
PrivateKey = ZZZZZZZ
Address = 10.8.0.9/24
DNS = 1.1.1.1
MTU = 1350

[Peer]
PublicKey = YYYYYYYY
PresharedKey = XXXXXXX
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 127.0.0.1:8388
```

Wireproxy (https://github.com/pufferffish/wireproxy ) accepts HTTP on port 8080 and sends out wireguard UDP packets (into sslocal thanks to Endpoint = 127.0.0.8388):
```ini
WGConfig = ./wireguard.conf

[http]
BindAddress = 127.0.0.1:8080
```

Optinally get a browser extension to direct traffic info wireproxy e.g. FoxyProxy for firefox.
Note that MTU must be set for wireguard.
And if now using wireproxy you need to exclude server from AllowedIPs, otherwise traffic from sslocal will loop back into wg0 interface, instead of reaching the remote

**Comment by PedroBuffon** [comment]
I'm on windows 11, can't seem to work with your config @temach, tried everything, even with wgproxy can't make wireguard connect to my home server.
My server shadow config:
```json
{
    "server":"0.0.0.0",
    "server_port": 8388,
    "password": "redacted",
    "method": "aes-256-gcm",
    "mode":"tcp_and_udp"
}
```
My cliente config:
```json
{
	"servers": [
		{
			"server":"redacted",
			"server_port":8388,
			"password":"redacted",
			"method":"aes-256-gcm"
		}
	],
    "locals": [
        {
            "mode": "tcp_and_udp",
            "protocol": "tunnel",
            "local_address": "127.0.0.1",
            "local_port": 8388,
            "forward_address": "redacted",
            "forward_port": 51820
        }
    ]
}
```
My wireguard config:
```
[Interface]
PrivateKey = redacted
Address = 192.168.2.4/32, 2804:10fc:200:e102::4/64
DNS = 1.1.1.1, 8.8.8.8
MTU = 1420

[Peer]
PublicKey = redacted
PresharedKey = redacted
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1, ::/1, 8000::/1
Endpoint = 127.0.0.1:8388
```
My wireguard server is my mikrotik running on 10.84.181.1

Chaging MTU doesn't do anything, the logs from the server too don't say anything, i only seem to be getting the sent packets on my wireguard client.
If i try only proxy and set it on firefox it works, but tunnel mode doesn't. Any help? if more info is necessary just tell me.

**Comment by database64128** [comment]
@PedroBuffon Have you tried https://github.com/database64128/swgp-go#routing-loop-prevention? With newer versions of swgp-go, it can take care of this for you if you set `"proxyAutoPickInterface": true`.

**Comment by temach** [comment]
@PedroBuffon I have only tried that config on linux, theoretically it might work on windows. Unfortunately I do not remember the details that well.
