### ISSUE TITLE
【Help】 If it is other encryption methods,how do I configure?

### ISSUE THREAD

**Issue by shawokou123** [shadowsocks/shadowsocks-rust#787]
If it is other encryption methods, such as rc4-md5, how do I configure.

For example, I can't use the following configuration：

{
            "address": "1.1.1.1",
            "port": 0000,
            "password": "passwrd",
            "method": "rc4-md5",
            "remarks": "new server"
        },

**Comment by zonyitoo** [comment]
`rc4-md5` is a stream cipher. [Stream ciphers](https://en.wikipedia.org/wiki/Stream_cipher) are completely broken and will be removed soon. New users must use [AEAD ciphers](https://shadowsocks.org/en/wiki/AEAD-Ciphers).

https://shadowsocks.org/en/wiki/Stream-Ciphers.html
