### ISSUE TITLE
Connection refused (os error 111)

### ISSUE THREAD

**Issue by L11R** [shadowsocks/shadowsocks-rust#789]
`ssservice[957]: ERROR tcp tunnel 127.0.0.1:57472 -> 127.0.0.1:5001 connect failed, error: Connection refused (os error 111)`
I am getting tons of this error. Cannot understand what is wrong. It seems to cause slow download speed and long handshakes. My config:
```json
{
  "server": "ip",
  "server_port": 443,
  "password": "pass",
  "method": "chacha20-ietf-poly1305",
  "fast_open": true,
  "reuse_port": true,
  "timeout": 7200,
  "nofile": 10240,
  "udp_timeout": 300,
  "udp_max_associations": 512,
  "plugin": "v2ray-plugin",
  "plugin_opts": "server;tls;host=mydomain.me;cert=fullchain.pem;key=privkey.pem"
}
```

**Comment by zonyitoo** [comment]
```
ssservice[957]: ERROR tcp tunnel 127.0.0.1:57472 -> 127.0.0.1:5001 connect failed, error: Connection refused (os error 111)
```

Well, it just means that the `ssserver` service failed to connect to `127.0.0.1:5001`.

**Comment by L11R** [comment]
> Well, it just means that the ssserver service failed to connect to 127.0.0.1:5001.
Hm, okay, but why it tries?

**Comment by zonyitoo** [comment]
It can only be your local client sent a request to the server with target address `127.0.0.1:5001`.

**Comment by L11R** [comment]
@zonyitoo thanks for the help, after reboot it seems to be okay, closing.
