### ISSUE TITLE
Warning: app/dispatcher: default route for tcp:127.0.0.1:0

### ISSUE THREAD

**Issue by alienzj** [shadowsocks/shadowsocks-rust#794]
Client config:
![image](https://user-images.githubusercontent.com/8847420/160059484-796f28ac-4b6a-414d-9894-3e631ef69774.png)

Server config:
![image](https://user-images.githubusercontent.com/8847420/160059516-66051402-9615-484f-97d9-49ec1665ed52.png)

Log:
![image](https://user-images.githubusercontent.com/8847420/160060009-dc31e7c8-b27c-403c-ac0c-5a13dcb50a2e.png)

**Comment by alienzj** [comment]
Dear shadowsocks developer, can you help me to figure out the problem why I can't connect to my ss server ?

**Comment by zonyitoo** [comment]
The `v2ray-plugin` just close the connection directly. I don't think this is related to shadowsocks.

**Comment by alienzj** [comment]
Thanks. Do you have any suggestion for plugin choice ?

**Comment by zonyitoo** [comment]
No. But `v2ray-plugin` should work fine in this case. You should double check the `plugin_opts` and see what exactly it was happening.

**Comment by dev4u** [comment]
服务端怎么可能设置loopback地址呢！不会是过来搞事的吧？

**Comment by alienzj** [comment]
> 服务端怎么可能设置loopback地址呢！不会是过来搞事的吧？

I modified the server IP to `::` and found that SS couldn't connect.  After updating the rule of iptables, the issue was solved.
It turned out that the server firewall blocked the port connection.

Thanks both.
