### ISSUE TITLE
how to connect to shadowsocks sever via other HTTP proxy server?

### ISSUE THREAD

**Issue by EDK-Rise** [shadowsocks/shadowsocks-rust#796]
i want to connect to shadow socks via HTTP proxy server with auth. i am using windows 10.
Client ---> http proxy server with auth ---> shadowsocks server

**Comment by zonyitoo** [comment]
What did you do and what problem have you encountered?

**Comment by EDK-Rise** [comment]
in my country i only access specific ip's or websites.  and i  access http proxy server that could access more ip's like provided shadowsocks servers. without http proxy server i can't access provided shadowsocks servers.

**Comment by zonyitoo** [comment]
If I understand it correctly, you want to start `sslocal` as a HTTP proxy server? Read the configuration section: https://github.com/shadowsocks/shadowsocks-rust#configuration about `"protocol": "http"`.

**Comment by EDK-Rise** [comment]
no,. i need connect to shadowsocks server over the http server.

**Comment by zonyitoo** [comment]
So you already have a HTTP proxy server, and you want to connect to the shadowsocks server via this HTTP proxy server. There are many ways to fulfill this goal:

1. Run a `sslocal` on a Router, and proxy everything you want via route strategy through `sslocal`.
2. Write a shadowsocks SIP003 plugin, `Client -> [sslocal -> PluginClient] -> HTTP Proxy Server -> [PluginServer -> ssserver]`
3. Change HTTP Proxy Server's target address to be SOCKS5, and then start `sslocal` as a SOCKS5 server, `Client -> HTTP Proxy Server -> sslocal -> ssserver`.

**Comment by EDK-Rise** [comment]
i haven't access HTTP server and shadowsock server for configuration and also i have simple combined adsl/router modem so i can't run any program.

**Comment by zonyitoo** [comment]
The key is to let the HTTP proxy server sends data from `sslocal` to `ssserver`.

So you can make a Plugin, which receives all data sent from `sslocal`, and then use `CONNECT` to relay them to HTTP proxy server targeting to `ssserver`'s IP.

It should work.

**Comment by dev4u** [comment]
> Could you please provide more details and references how one can implement such solution

https://shadowsocks.org/guide/sip003.html

**Comment by verbal666** [comment]
Thread is old.
Meanwhile i approached SS, and found the same problem, also nowdays. SS has not an HTTP(S) passthrough 🤷‍♀️
The only way is to install a transparent proxy / proxifier (redsocks, ts-warp, squid as transparent etc...), but Proxy Admins can catch the ip of destination in 1st level form (1.2.3.4) and not a domain name (my.domain.com with a reverse proxy). In some cases (mine) a CONNECT 1.2.3.4 is denied and notified as "possible data leak" 🤷‍♀️
