### ISSUE TITLE
构建ios平台的库时出现错误

### ISSUE THREAD

**Issue by Yewenyu** [shadowsocks/shadowsocks-rust#797]
你好，请问怎么解决下面的错误

cargo lipo --release
[INFO  cargo_lipo::meta] Will build universal library for ["ss_client_c"]
[INFO  cargo_lipo::lipo] Building "ss_client_c" for "aarch64-apple-ios"
   Compiling serde_derive v1.0.136
   Compiling tokio-macros v1.7.0
   Compiling futures-macro v0.3.21
   Compiling thiserror-impl v1.0.30
   Compiling pin-project-internal v1.0.10
   Compiling async-trait v0.1.52
   Compiling enum-as-inner v0.3.3
   Compiling derivative v2.2.0
   Compiling pest_derive v2.1.0
   Compiling sha1 v0.10.1
error[E0433]: failed to resolve: could not find `__detect_target_features` in `$crate`
 --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/sha1-0.10.1/src/compress/aarch64.rs:8:1
  |
8 | cpufeatures::new!(sha1_hwcap, "sha2");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `__detect_target_features` in `$crate`
  |
  = note: this error originates in the macro `cpufeatures::new` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `sha1` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
[ERROR cargo_lipo] Failed to build "ss_client_c" for "aarch64-apple-ios": Executing "/Users/xiewenyu/.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo" "--color" "auto" "build" "-p" "ss_client_c" "--target" "aarch64-apple-ios" "--release" "--lib" finished with error status: exit status: 101

cargo.toml

[package]
name = "ss_client_c"
version = "0.1.0"
edition = "2021"

[lib]
name = "ss_client_c"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
shadowsocks-rust = { path = "..",features = ["local-tunnel","stream-cipher"]}

**Comment by zonyitoo** [comment]
It looks like https://github.com/RustCrypto/utils/tree/master/cpufeatures fails to compile on iOS.

**Comment by Yewenyu** [comment]
> It looks like https://github.com/RustCrypto/utils/tree/master/cpufeatures fails to compile on iOS.

I'm sorry. I can't figure out how to fix it.
I guess I need to make changes here?

[target.'cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
shadowsocks-crypto = { version = "0.3.3", features = [] } in crates/shadowsocks/Cargo.toml

**Comment by zonyitoo** [comment]
https://github.com/RustCrypto/hashes/tree/master/sha1

Try to compile this crate independently. If you can see the same error, open an issue right there.

**Comment by Yewenyu** [comment]
> 
It compiles without errors

cargo build --target aarch64-apple-ios --release
   Compiling version_check v0.9.4
   Compiling typenum v1.15.0
   Compiling blobby v0.3.1
   Compiling cpufeatures v0.2.2
   Compiling cfg-if v1.0.0
   Compiling generic-array v0.14.5
   Compiling crypto-common v0.1.3
   Compiling block-buffer v0.10.2
   Compiling digest v0.10.3
   Compiling sha1 v0.10.1 (/Users/xiewenyu/Desktop/rust-project/hashes-master/sha1)
    Finished release [optimized] target(s) in 5.41s

**Comment by zonyitoo** [comment]
Alright then, I suspect that it is related to the cargo's feature resolver. The `asm` feature was enabled unexpectly.

Does the `shadowsocks-rust` in local path `..` use `edition = "2021"`?

Could you compile `shadowsocks-rust` or `shadowsocks-service` independently?

**Comment by Yewenyu** [comment]
> Alright then, I suspect that it is related to the cargo's feature resolver. The `asm` feature was enabled unexpectly.
> 
> Does the `shadowsocks-rust` in local path `..` use `edition = "2021"`?
> 
> Could you compile `shadowsocks-rust` or `shadowsocks-service` independently?

Compile error

cargo build --target aarch64-apple-ios --features "local-tun local-redir armv8 neon"


   Compiling serde_derive v1.0.136
   Compiling tokio-macros v1.7.0
   Compiling futures-macro v0.3.21
   Compiling thiserror-impl v1.0.30
   Compiling digest v0.10.3
   Compiling polyval v0.5.3
   Compiling pin-project-internal v1.0.10
   Compiling poly1305 v0.7.2
error[E0433]: failed to resolve: could not find `__detect_target_features` in `$crate`
  --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/polyval-0.5.3/src/backend/autodetect.rs:15:1
   |
15 | cpufeatures::new!(mul_intrinsics, "aes"); // `aes` implies PMULL
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `__detect_target_features` in `$crate`
   |
   = note: this error originates in the macro `cpufeatures::new` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/polyval-0.5.3/src/lib.rs:80:5
   |
80 |     feature(stdsimd, aarch64_target_feature)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0433, E0554.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `polyval` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Yewenyu** [comment]
> ```
> error[E0554]: #![feature] may not be used on the stable release channel
> ```
> 
> You have to use nightly if you want to enable `armv8 neon`.

Now I've changed to nightly.

rustup default nightly-2022-03-23

When I use ’cargo build --features "local-tun local-redir armv8 neon"‘ to build, it is  successed.
But when select ios target, it is failed.

cargo build --target aarch64-apple-ios --features "local-tun local-redir armv8 neon"
   Compiling digest v0.10.3
   Compiling polyval v0.5.3
   Compiling ctr v0.8.0
   Compiling poly1305 v0.7.2
   Compiling chacha20 v0.8.1
   Compiling serde v1.0.136
   Compiling futures-util v0.3.21
   Compiling elliptic-curve v0.11.12
   Compiling thiserror v1.0.30
   Compiling pin-project v1.0.10
error: the target features fp, neon must all be either enabled or disabled together
    |
    = help: add the missing features in a `target_feature` attribute

error: the target features fp, neon must all be either enabled or disabled together
     |
     = help: add the missing features in a `target_feature` attribute

error: could not compile `polyval` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by zonyitoo** [comment]
Switch to nightly-2022-03-09  . The recent released versions of nightly have known bugs.

**Comment by Yewenyu** [comment]
> Switch to nightly-2022-03-09 . The recent released versions of nightly have known bugs.

I've switched to nightly-2022-03-09, and it has a new error.

cargo build --target aarch64-apple-ios --features "local"
   Compiling shadowsocks-service v1.13.5 (/Users/xiewenyu/Desktop/rust-project/shadowsocks-rust/crates/shadowsocks-service)
   Compiling shadowsocks-rust v1.13.5 (/Users/xiewenyu/Desktop/rust-project/shadowsocks-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 19.23s
xiewenyudeMBP:shadowsocks-rust xiewenyu$ cargo build --target aarch64-apple-ios --features "local-tun local-redir armv8 neon"
   Compiling smoltcp v0.8.0
   Compiling shadowsocks v1.13.2 (/Users/xiewenyu/Desktop/rust-project/shadowsocks-rust/crates/shadowsocks)
error[E0425]: cannot find value `BIOCSETIF` in this scope
  --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:79:29
   |
79 |         try_ioctl!(self.fd, BIOCSETIF, &mut self.ifreq);
   |                             ^^^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use crate::phy::sys::bpf::libc::BIOCSETIF;
   |
1  | use libc::BIOCSETIF;
   |

error[E0425]: cannot find value `BIOCIMMEDIATE` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:107:29
    |
107 |         try_ioctl!(self.fd, BIOCIMMEDIATE, &mut bufsize as *mut libc::c_int);
    |                             ^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use crate::phy::sys::bpf::libc::BIOCIMMEDIATE;
    |
1   | use libc::BIOCIMMEDIATE;
    |

error[E0425]: cannot find value `BIOCGBLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:108:29
    |
108 |         try_ioctl!(self.fd, BIOCGBLEN, &mut bufsize as *mut libc::c_int);
    |                             ^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use crate::phy::sys::bpf::libc::BIOCGBLEN;
    |
1   | use libc::BIOCGBLEN;
    |

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:121:35
    |
121 |             if len == -1 || len < BPF_HDRLEN as isize {
    |                                   ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:129:25
    |
129 |                 &buffer[BPF_HDRLEN] as *const u8 as *const libc::c_void,
    |                         ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:130:23
    |
130 |                 len - BPF_HDRLEN,
    |                       ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `smoltcp` due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed.


But I just use "local" feature, it builded success.
cargo build --target aarch64-apple-ios --features "local"

And then I failed with:
cargo build --target aarch64-apple-ios --features "local-tun"

cargo build --target aarch64-apple-ios --features "local-tun"
   Compiling smoltcp v0.8.0
error[E0425]: cannot find value `BIOCSETIF` in this scope
  --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:79:29
   |
79 |         try_ioctl!(self.fd, BIOCSETIF, &mut self.ifreq);
   |                             ^^^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use crate::phy::sys::bpf::libc::BIOCSETIF;
   |
1  | use libc::BIOCSETIF;
   |

error[E0425]: cannot find value `BIOCIMMEDIATE` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:107:29
    |
107 |         try_ioctl!(self.fd, BIOCIMMEDIATE, &mut bufsize as *mut libc::c_int);
    |                             ^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use crate::phy::sys::bpf::libc::BIOCIMMEDIATE;
    |
1   | use libc::BIOCIMMEDIATE;
    |

error[E0425]: cannot find value `BIOCGBLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:108:29
    |
108 |         try_ioctl!(self.fd, BIOCGBLEN, &mut bufsize as *mut libc::c_int);
    |                             ^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use crate::phy::sys::bpf::libc::BIOCGBLEN;
    |
1   | use libc::BIOCGBLEN;
    |

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:121:35
    |
121 |             if len == -1 || len < BPF_HDRLEN as isize {
    |                                   ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:129:25
    |
129 |                 &buffer[BPF_HDRLEN] as *const u8 as *const libc::c_void,
    |                         ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `BPF_HDRLEN` in this scope
   --> /Users/xiewenyu/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.0/src/phy/sys/bpf.rs:130:23
    |
130 |                 len - BPF_HDRLEN,
    |                       ^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `smoltcp` due to 6 previous errors

**Comment by zonyitoo** [comment]
Remove that `local-tun` temporary.

**Comment by Yewenyu** [comment]
> Remove that `local-tun` temporary.

Ok, actually I just need `local`, thank you very much.
