### ISSUE TITLE
Question: shadowsocks-rust vs shadowsocks-libev in terms of features?

### ISSUE THREAD

**Issue by brianwoo** [shadowsocks/shadowsocks-rust#801]
Hi devs, I am new to shadowsocks and I am trying to see which is the best version to install.  From what I have found, the most popular versions are shadowsocks-rust, shadowsocks-libev and the outline-ss-server, among other variations.  Is shadowsocks-libev still being actively developed and rust is considered the most up to date?  Are the enhancements added to libev by the Outline team ported to the rust version?  Thanks.

**Comment by zonyitoo** [comment]
You are free to add any new features with PR.
