### ISSUE TITLE
建议tcp转发可以加大等待时间的长度

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#804]
https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/local/utils.rs#L52
最近一段时间，发现ss经常发生只有上行请求，没有下行响应的情况。
上述位置的代码，加大等待的超时长度，故障现象有所好转。
我在测的修改后方案是：5秒至10秒的随机时间长度。
如果不是错觉，希望能优化这个时间长度。

**Comment by zonyitoo** [comment]
What? This timeout is for waiting the first data packet to be sent with the handshake header. It is impossible to set it to 10 seconds. What problem did you want to solve actually?

**Comment by dev4u** [comment]
最近我用tg，经常遇到有上行请求，但没收到下行响应。修改这个时间长度后，tg响应速度虽然有点慢，但是至少响应是能收到的。

**Comment by zonyitoo** [comment]
This is completely irrevelent. This timeout is for server-hello protocols only. You are looking to a wrong place.

**Comment by dev4u** [comment]
噢，原来是错觉，那我再另找原因。
