### ISSUE TITLE
does shadowsocks-rust support ipv6?

### ISSUE THREAD

**Issue by xiedeacc** [shadowsocks/shadowsocks-rust#808]
at title, I notice all ipv6 connection was not transfer to my remote server, if shadowsocks-rust support ipv6, how to config local and server, thanks

**Comment by zonyitoo** [comment]
Of course it supports IPv6. I can help further because you didn’t provide more information.

**Comment by youkechat** [comment]
I found my openwrt never proxy IPV6 trafic, for some reason, my pc ipv6 addr must  to be obtained by ralay mode. but I don't think this it's a problem, pc network trafic will pass openwrt lan interface anyway, so I think shadowsocks should transfer these ipv6 trafic to my remote host, but it doesn't, should I add a iptable rule to make all ipv6 trafic to shadowsokcs-rust ?

**Comment by youkechat** [comment]
> Of course it supports IPv6. I can help further because you didn’t provide enough information.

can U reopen this issue?
