### ISSUE TITLE
服务模式没有跟随配置文件

### ISSUE THREAD

**Issue by yiguihai11** [shadowsocks/shadowsocks-rust#810]
![IMG_20220418_104955](https://user-images.githubusercontent.com/103910817/163746703-73327485-05ff-4f55-9730-ec9bba200fd5.jpg)
我在配置文件中设置了```mode: "tcp_and_udp"```但是命令行启动的时候没有加-U依然是tcp_only如上图  
如果不是有意为之还请修复一下

**Comment by zonyitoo** [comment]
Your local instance is created from command line options, so all the arguments have to be provided.

The `mode` in the configuration file is only for locals and servers instances.

**Comment by yiguihai11** [comment]
> Your local instance is created from command line options, so all the arguments have to be provided.
> 
> The `mode` in the configuration file is only for locals and servers instances.

还有一个问题就是使用ssmanager的API添加用户时如何使用acl文件？我在启动ssmanager时命令行参数配置了acl文件，添加一个用户端口后acl访问规则没有生效

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/66dc357ebfccc2eab977d2720a9e6a0ef55f09d5/crates/shadowsocks-service/src/manager/server.rs#L228-L230

I don't think so, it should work.

Are you using standalone mode? It doesn't work in standalone mode.

**Comment by yiguihai11** [comment]
> 

对就是standalone独立模式启动的，然后添加的用户访问一些被acl屏蔽的ip或域名不起作用

**Comment by zonyitoo** [comment]
Yes it is expected. Because I don't know the exact path of ACL file in the library.

**Comment by yiguihai11** [comment]
> 

能不能在api参数中添加一个acl参数用来指定acl文件位置呢

**Comment by zonyitoo** [comment]
Any PRs are welcome. Currently I am working on another project.

**Comment by yiguihai11** [comment]
> 

我不会rustʘᴗʘ
