### ISSUE TITLE
Is it possible to run sslocal as a plain-old SOCKS5 server?

### ISSUE THREAD

**Issue by flavorgold1** [shadowsocks/shadowsocks-rust#818]
If not, would it be a lot of work to enable such a feature?
I know that this isn't the purpose of this software, but, I think it sort of helps us make more "multipurpose" use of it.
I can't find other decent, well-supported SOCKS5 servers like this one.

**Comment by zonyitoo** [comment]
Set a ACL file to "bypass" all requests, then it will become a pure SOCKS5 server.

**Comment by flavorgold1** [comment]
`./sslocal --config ./config.json --acl ./acl.json`
`config.json`:
```
{
    "locals": [
        {
            "local_address":"::",
            "local_port":6000,
            "mode":"tcp_and_udp",
            "socks5_auth_config_path":"/path/to/auth.json"
        }
    ]
}
```
`acl.json`:
```
[bypass_all]
```
`auth.json`:
```
{
    "password": {
        "users": [
            {
                "user_name": "socks_user_id",
                "password": "socks_password"
            }
        ]
    }
}
```
Result:
```
missing proxy servers, consider specifying it by --server-addr, --encrypt-method, --password command line option, or --server-url command line option, or configuration file, check more details in https://shadowsocks.org/en/config/quick-guide.html
```

What am I doing wrong here?
Sorry and Thank You.

**Comment by zonyitoo** [comment]
Just give a random server config, `server`, `server_port`, `method`, `password`

**Comment by flavorgold1** [comment]
> Just give a random server config, `server`, `server_port`, `method`, `password`

Wow. That worked. Do I have to care about whether this sslocal keeps trying to connect to that dummy shadowsocks server? I set it to 127.0.0.1 with some random port number. Or, does sslocal only try to establish a connection when it needs to?

**Comment by zonyitoo** [comment]
Yes, it will connect only when it needs to.
