### ISSUE TITLE
plugin在安卓的ss支持吗？

### ISSUE THREAD

**Issue by coolicer** [shadowsocks/shadowsocks-rust#82]
我看客户端可以加这个 --plugin "obfs-local" --plugin-opts "obfs=tls"，我不太清楚怎么用

**Comment by zonyitoo** [comment]
不清楚你使用的是什么Android客户端，请咨询该客户端的开发者。

**Comment by coolicer** [comment]
@zonyitoo 就是shadowsocks for android

**Comment by zonyitoo** [comment]
相信是这个吧 https://github.com/shadowsocks/shadowsocks-android ，请到此项目咨询。我没有使用过并不清楚。

**Comment by ContactFront** [comment]
@coolicer Android 客户端支持 simple-obfs. 需要另外安装插件
 https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.obfs_local

**Comment by coolicer** [comment]
@ContactFront 好的

**Comment by zonyitoo** [comment]
Close because of inactivity.
