### ISSUE TITLE
UDP over TCP protocol support

### ISSUE THREAD

**Issue by aire1** [shadowsocks/shadowsocks-rust#834]
can you add UDP over TCP protocol?
example: https://github.com/SagerNet/UoT
or it can add only to v2ray-plugin?

**Comment by zonyitoo** [comment]
You can run it as a plug-in.

**Comment by database64128** [comment]
SagerNet/UoT uses a special target address for UoT traffic, which is non-standard behavior. You really shouldn't expect such things from a reference implementation like shadowsocks-rust.

Besides, there probably isn't a compelling reason for you to use UoT. In my opinion, most users of UoT don't actually need UoT. They just like the concept of UoT for some strange reason.

**Comment by dev4u** [comment]
setup a UDP fallback profile to enable UDP forwarding
