### ISSUE TITLE
可以调整ssserver日志级别吗？

### ISSUE THREAD

**Issue by qwerttvv** [shadowsocks/shadowsocks-rust#837]
最近总有扫我的，每天日志100m……

来回来去冒出来4个IP了，目前我还没有准备拉黑名单，对我唯一影响就是日志太大了，本来我有个脚本一周删一次日志，我感觉现在是不是一天删一次了

或者看看有没有办法调整ssserver的日志输出级别，把警告一类的，就忽略了吧？

**Comment by AaronChen0** [comment]
Use `--log-config log4rs.yaml`, 

Reference:
https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/log4rs.yaml
https://crates.io/crates/log4rs

**Comment by zonyitoo** [comment]
Yes, use `--log-config` as @AaronChen0 said.
