### ISSUE TITLE
Is shadowsocks-rust going to support shadowsocksR? especially the protocol supporting, e.g. auth_aes128_sha1, auth_aes128_md5, etc.

### ISSUE THREAD

**Issue by breakapphub** [shadowsocks/shadowsocks-rust#846]
Is shadowsocks-rust going to support shadowsocksR? especially the protocol supporting, e.g. auth_aes128_sha1, auth_aes128_md5, etc.
Are there any other projects written in rust support shaodowsR?

**Comment by zonyitoo** [comment]
never.
