### ISSUE TITLE
Does sslocal support shadowsocks 2022? 

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-rust#847]
I use the version v1.15.0-alpha.4, but it log said does not support "2022-blake3-aes-256-gcm" method. On server side, ssserver work fine. Can somebody tell me how to do? Thank you!

**Comment by database64128** [comment]
Are you sure you are using the right version of sslocal? sslocal prints version info and build time on startup, please double check.

**Comment by tianlichunhong** [comment]
> Are you sure you are using the right version of sslocal? sslocal prints version info and build time on startup, please double check.

Thank you very much for you reply! Yes, I used command ssloal --version , show the version is 1.15.0-alpha.4. Log show that unsupported,   "2022-blake3-aes-256-gcm" is not a supported method.

**Comment by tianlichunhong** [comment]
> Are you sure you are using the right version of sslocal? sslocal prints version info and build time on startup, please double check.

Thank you for your reply!  And very sorry,  yes, it my mistake. It work fine.
