### ISSUE TITLE
manager support?

### ISSUE THREAD

**Issue by Willian-Zhang** [shadowsocks/shadowsocks-rust#85]
https://github.com/shadowsocks/shadowsocks-manager

**Comment by zonyitoo** [comment]
Not supported yet. Any PRs are welcome.

**Comment by zonyitoo** [comment]
Already done. Supported `add`, `remove`, `list` and `ping` commands as [Manage Multiple Users](https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users) defined.
