### ISSUE TITLE
Shadowsocks insecurely cracked; Use random salt to each connection

### ISSUE THREAD

**Issue by blurfish** [shadowsocks/shadowsocks-rust#854]
https://github.com/snail007/shadowtunnel/issues/17

Q1. Why Shadowsocks are not encrypting destination address|port when requesting question to ss server??
Q2. Instead of actually using the shared secret, the first connection ask for the random salt, and use {salt+password} as a new password. Rotate this password for every 10 minutes or so.
Q3. What is your thought on this? Do you still believe shadowsocks is secure?

**Comment by dev4u** [comment]
你不会是来搞笑的吧？

**Comment by zonyitoo** [comment]
> Q1. Why Shadowsocks are not encrypting destination address|port when requesting question to ss server??

Why do you think the destination address is not encrypted in shadowsocks protocol?

> Q2. Instead of actually using the shared secret, the first connection ask for the random salt, and use {salt+password} as a new password. Rotate this password for every 10 minutes or so.

Why is this useful for increasing security level?

> Q3. What is your thought on this? Do you still believe shadowsocks is secure?

I don't see anything in https://github.com/snail007/shadowtunnel/issues/17 is related to shadowsocks, except it has a "shadow" in its name.
