### ISSUE TITLE
 failed to fetch `https://github.com/rust-lang/crates.io-index` ? 

### ISSUE THREAD

**Issue by chenyangguang** [shadowsocks/shadowsocks-rust#86]
➜  libsodium-stable  `cargo install shadowsocks-rust   `  
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

使用 cargo 安装时拉不下来？　
To learn more, run the command again with --verbose.
➜  libsodium-stable  `cargo install shadowsocks-rust --verbose`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [16/-17] The SSL certificate is invalid

**Comment by zonyitoo** [comment]
你被墙了。加Proxy。

**Comment by chenyangguang** [comment]
＠zonyitoo 就是要翻，才搞这个啊．关键现在加Proxy没用呢．

**Comment by zonyitoo** [comment]
这是已知问题，原因就是你访问不了`https://github.com/rust-lang/crates.io-index`，这是github的地址。翻墙就可以了。

**Comment by zonyitoo** [comment]
你是什么系统？

**Comment by chenyangguang** [comment]
ubuntu16.04

**Comment by zonyitoo** [comment]
直接下载静态链接的binary吧https://github.com/shadowsocks/shadowsocks-rust/releases

**Comment by zonyitoo** [comment]
This is a network problem. Closing issue.
