### ISSUE TITLE
[Question] How do I read shadowsocks network traffic stat info on Windows platform?

### ISSUE THREAD

**Issue by xinlake** [shadowsocks/shadowsocks-rust#860]

**Comment by zonyitoo** [comment]
https://www.howtogeek.com/427344/how-to-see-the-applications-using-your-network-on-windows-10/

**Comment by xinlake** [comment]
> https://www.howtogeek.com/427344/how-to-see-the-applications-using-your-network-on-windows-10/

Sorry, I need to show the shadowsocks network traffic info on my app. Do shadowsocks provide any API to read stat info?

**Comment by zonyitoo** [comment]
No. You can make a proxy thread in your application and do the statistics in the proxy.

```
[PROXY] ----> sslocal -> ssserver -> ...
```

**Comment by xinlake** [comment]
> No. You can make a proxy thread in your application and do the statistics in the proxy.
> 
> ```
> [PROXY] ----> sslocal -> ssserver -> ...
> ```
> 
> The `[PROXY]` should be very simple, because it only needs 1 TCP Listener socket and 1 UDP socket, and just copy everything it reads from the clients and sslocal to the otherside. It should only contains less then 200 lines of code.

Simple, although this solution is a bit inefficient, Thank you.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/e84e76a6821abdf75b5ba393d405b42d07d2dcdd/crates/shadowsocks-service/src/local/mod.rs#L416-L457

I just remember there is a stat task in `sslocal`, which will report statistics to a specific UDS address. Maybe we can make it report to a TCP / UDP port.

**Comment by xinlake** [comment]
Does the `local-flow-stat` feature only supported on Android? 

[My app](https://github.com/xinlake/privch) is a Flutter cross-platform shadowsocks (other protocols may be supported in the future) client application, it currently runs on Android, Windows. The network traffic stat showing is supported on Android (get process network stat info via system API).

The hard part for me is getting traffic statistics on Windows. I searched for **win32 API** and it needs to be obtained by a network monitor, seems the system cannot directly support it. **CLR** is a feasible way but my app is a native app on the Windows platform, so the overhead may be high. Then **shadowsocks**, if it provided its traffic statistic information on Windows system then this could be a good solution to my app.

**Comment by dev4u** [comment]
https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/bg/TrafficMonitor.kt
可以看看怎么读取

**Comment by xinlake** [comment]
> https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/bg/TrafficMonitor.kt 可以看看怎么读取

我 App 的流量图功能在 Android 端已经支持了（通过 `TrafficStats.getUidTxBytes(applicationUid)` 可以得到），需要在 Windows 端也支持同样的功能，目前在评估各种方案，想了解 Shadowsocks Windows 版本有没流量统计信息接口

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/e84e76a6821abdf75b5ba393d405b42d07d2dcdd/crates/shadowsocks-service/src/local/mod.rs#L429

`local-flow-stat` can support reporting to a specific TCP port. Maybe you can start a TCP listener listening to `127.0.0.1:?` and then pass it to `--local-stat-***`

**Comment by xinlake** [comment]
> https://github.com/shadowsocks/shadowsocks-rust/blob/e84e76a6821abdf75b5ba393d405b42d07d2dcdd/crates/shadowsocks-service/src/local/mod.rs#L429
> 
> `local-flow-stat` can support reporting to a specific TCP port. Maybe you can start a TCP listener listening on `127.0.0.1:?` and then pass it to `--local-stat-***`

Sorry for my late, does it work on **Windows System**?

**Comment by zonyitoo** [comment]
Of course.

**Comment by xinlake** [comment]
> 

OK, Thank you very much
