### ISSUE TITLE
The ACL rules are not loaded from config file

### ISSUE THREAD

**Issue by fowagon** [shadowsocks/shadowsocks-rust#861]
https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.14.3

`shadowsocks.exe --config soadow.json`

`shadow.json` has `"acl":"acl.txt",` line.

It is not loaded at all.

Only `shadowsocks.exe --config soadow.json --acl acl.txt` works.

Please make ACL loaded from config file.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.15.0-alpha.5

It only works since v1.15.0-alpha.5.
