### ISSUE TITLE
[Enhancement] 多服务端时SIP003插件是否可以优化成只有一个进程常驻？

### ISSUE THREAD

**Issue by missdeer** [shadowsocks/shadowsocks-rust#866]
当前选中的服务端对应的插件进程可以常驻，其他服务端对应的插件进程只有在用到的时候再启动，不用了就关掉，是否可以这样？

**Comment by zonyitoo** [comment]
No. Because the PingBalancer will continously ping servers even if they are not chosen.

**Comment by missdeer** [comment]
理解。不过我有几十个server，于是就一直常驻着几十个插件进程，看着不大舒服，有没有其他改进方案？

**Comment by zonyitoo** [comment]
I don't think so. Each server must have 1 plugin process for handling data flows.

Linux should be ok to handle tens of processes.
