### ISSUE TITLE
新加密方式报错

### ISSUE THREAD

**Issue by yadex** [shadowsocks/shadowsocks-rust#868]
![maim20220615-113712](https://user-images.githubusercontent.com/20081672/173731822-7edfa57f-a14d-4355-9973-b1ab08e20109.png)

**Comment by SevendaysZzzz** [comment]
这个问题解决了吗？

**Comment by yadex** [comment]
没有解决，用了老的

**Comment by iKirby** [comment]
新的加密方式要求使用固定长度的 Key，参见 https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-1-shadowsocks-2022-edition.md#21-psk

**Comment by yadex** [comment]
原来这样，没仔细看文档

**Comment by SevendaysZzzz** [comment]
好吧，看来不用重开了
