### ISSUE TITLE
Method chacha20-ietf-poly1305 not supported in shadowsocks-rust?

### ISSUE THREAD

**Issue by chenyangguang** [shadowsocks/shadowsocks-rust#87]
➜  ~ ssserver
INFO: loading config from config.json
2017-11-30 21:53:48 ERROR    method chacha20-ietf-poly1305 not supported

But My method only support for chacha20-ietf-poly1305, how to fix it ?

**Comment by zonyitoo** [comment]
I use `chacha20-ietf-poly1305` every day.

How to reproduce your issue?

**Comment by chenyangguang** [comment]
我也不知道怎么重现。我就是按照shadowsocks-rust的方法去做的。前面go-shadowsocks2, 和 ss-qt5都试过了，都没法用。开启服务之后，隔一段时间之后报超时了。而且我这里 public ip 地址一直都是变的呀。现在一步步按照 shadowsocks-rust 的方法来，安装好必要的那些依赖之后，开始 ssserver 就说是 method chacha20-ietf-poly1305的加密方法并不支持。。。

**Comment by zonyitoo** [comment]
安装的方式，运行的命令和参数，错误的完整输出，配置文件的内容。既然你现在是一直都不能用的，那自然可以重现

**Comment by chenyangguang** [comment]
使用 binary 方式安装
```

tar -xvf shadowsocks-rust-1.6.10.tar.gz
cd build
./build-release
```

配置文件写入 config.json, 加密方法 method chacha20-ietf-poly1305, 和移动端的配置一样的。
用
`ssserver -c config.json `
命令启动时, 报我不支持chacha20-ietf-poly1305方法

```
➜  shadowsocks-rust-1.6.10 ssserver -c ~/config.json 
INFO: loading config from /home/v/config.json
2017-12-03 10:50:03 ERROR    method chacha20-ietf-poly1305 not supported
```

```bash
➜  shadowsocks-rust-1.6.10 cargo run --bin ssserver -- -c config.json
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

To learn more, run the command again with --verbose.
```

两种方法我都试了，

**Comment by zonyitoo** [comment]
(2) 是你无法正常访问到 `https://github.com/rust-lang/crates.io-index`，网络问题，不讨论。

Binary方法，不用去`cd build`. 解压出来的就是可执行文件。

`config.json` 的内容是怎样的？除了 server ip 和密码，其它部分复制出来看一下。不使用config文件，直接命令行传参呢？

另外

```
2017-12-03 10:50:03 ERROR    method chacha20-ietf-poly1305 not supported
```

这不是我这个项目的日志的输出格式，请先确认`ssserver`确实是此项目的Binary。

**Comment by chenyangguang** [comment]
```
➜  tree -L 1
.
├── appveyor.yml
├── build
├── Cargo.lock
├── Cargo.toml
├── configs
├── debian
├── examples
├── LICENSE
├── Makefile
├── README.md
├── rustfmt.toml
├── src
└── tests
并没有直接看见执行文件，是 src/bin里面的执行命令么， rust我不太熟

➜   which ssserver
/usr/local/bin/ssserver

```

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.6.10/shadowsocks-v1.6.10-release.x86_64-unknown-linux-musl.tar.xz

下载，解压

**Comment by chenyangguang** [comment]
我使用go-shadowsocks2版本去了

**Comment by zonyitoo** [comment]
1. 解压之后不需要做任何的操作，直接 `./ssserver` 就可以了。你直接下载了源码，不是下载可执行文件。
2. 看你的输出日志，`/usr/local/bin/ssserver` 的绝对不是此项目的可执行文件，比较像是 Python 版
3. 可执行文件与Rust无关。

Closing issue.
