### ISSUE TITLE
too slow or not response after connected seconds

### ISSUE THREAD

**Issue by chuoke** [shadowsocks/shadowsocks-rust#873]
When connected, the request can respond normally, after a few more requests, slow down or even no response.

I don't know what happened. It had been working fine. All of a sudden, something went wrong. I changed the configuration. It didn't work.

Is anyone else in the same situation?

**Comment by zonyitoo** [comment]
> after a few more requests

So the "requests" open new tcp channels or reuse the same tcp channel?

**Comment by chuoke** [comment]
> So the "requests" open new tcp channels or reuse the same tcp channel?

Yes, but I'm not sure. I think I got replay attach.
