### ISSUE TITLE
aead 现在还安全么？

### ISSUE THREAD

**Issue by 18o** [shadowsocks/shadowsocks-rust#875]
上半年两台vps被GFW屏蔽了，都是因为用ss-rust，aes-256-gcm加密的.

想问下现在aead还安全么？ 如果不安全，那ss-rust有什么可用做的能够变安全呢？

**Comment by zonyitoo** [comment]
So far, I think shadowsocks AEAD is still secured with "correct" implementations. Some of the client implementations, especially those closed sourced, send handshake headers and data in different packets may increase the risk of the servers to be detected.

This is not a technical issue. Use Discussions instead.
