### ISSUE TITLE
请升级 依赖 `ring` 的版本

### ISSUE THREAD

**Issue by LuoZijun** [shadowsocks/shadowsocks-rust#90]
当前 master 分支，在使用 nightly 版本的 rust 编译时会出现 `模块文件依赖错误` .

这个问题是 [briansmith/ring](https://github.com/briansmith/ring) 这个依赖引起的，相关问题跟踪:

https://github.com/briansmith/ring/issues/607
https://github.com/briansmith/ring/issues/609
https://github.com/briansmith/ring/issues/598

鉴于此，请切换 `ring` 至 `0.13` 或者更高的版本，谢谢。

**Comment by zonyitoo** [comment]
Ring目前在crates.io上只发布到0.12.1

https://crates.io/crates/ring

**Comment by luckypoem** [comment]
@zonyitoo 
我在这里https://github.com/changlan/kytan/issues/23 ，也遇到这个 ring v0.12.1的问题，怎么解决？
感谢你的答复

**Comment by LuoZijun** [comment]
@luckypoem 以 `稳定版` 编译，或者修改 `ring` 的版本至 `0.13` 。

也可以手动去 `cargo` 的 `registry` 目录修复下 `ring` 。

**Comment by briansmith** [comment]
See https://twitter.com/BRIAN_____/status/955339612381093888.
