### ISSUE TITLE
Cipher aes-256-cfb is not available

### ISSUE THREAD

**Issue by artenax** [shadowsocks/shadowsocks-rust#914]
I understand it is outdated, but it is still found in Telegram channels about shadowsocks. And shadowsocks is not only used in China, where strong encryption is needed. Can you take care of other users too?
Fortunately, shadowsocks-libev supports them, but I can't make a build for Windows.

Also, many ss:// protocols are not supported. I have to decode base64 and make up a command line myself.

**Comment by zonyitoo** [comment]
1. You can always enable it with `stream-ciphers` feature
2. It is not about “strong encryption” but easy to be detected.
3. There is only one ss:// protocol standard, which is SIP002. SIP002 is fully supported by this project.

**Comment by artenax** [comment]
> You can always enable them with stream-ciphers feature

Do you mean when compiling? Thanks. I will explore it.
