### ISSUE TITLE
有没有ubuntu上的客户端图形程序？

### ISSUE THREAD

**Issue by jearton** [shadowsocks/shadowsocks-rust#919]

**Comment by artenax** [comment]
Yes, for example shadowsocks-qt5 https://github.com/shadowsocks/shadowsocks-qt5/releases
Unlike shadowsocks-rust, shadowsocks-qt5 also supports old ciphers, all ss:// URL's, has a graphical interface, profiles, latency test.

**Comment by artenax** [comment]
There are also shadowsocks-electron https://github.com/nojsja/shadowsocks-electron/releases
But keep in mind that electron contains a chromium browser, i.e. the application is quite heavy.
