### ISSUE TITLE
能再次提供shadowsocks-rust v0.9.14版吗？

### ISSUE THREAD

**Issue by luckypoem** [shadowsocks/shadowsocks-rust#92]
hi.
能再次提供shadowsocks-rust v0.9.14版吗？
我克隆你的新版，编译遇错。
以前克隆你的v0.9.14版，可以成功安装shadowsocks-rust。

**Comment by zonyitoo** [comment]
0.9.x版本已经很久很久之前的了。
master分支，编译遇到什么问题？

**Comment by luckypoem** [comment]
root@RegalMusty-VM:~/shadowsocks-rust# cargo build --release
   Compiling build_const v0.2.0
   Compiling adler32 v1.0.2
   Compiling vec_map v0.8.0
   Compiling matches v0.1.6
   Compiling pkg-config v0.3.9
   Compiling unicode-normalization v0.1.5
   Compiling scopeguard v0.3.3
   Compiling openssl v0.9.23
   Compiling typenum v1.9.0
   Compiling arrayref v0.3.4
   Compiling dtoa v0.4.2
   Compiling serde v1.0.27
error: Could not compile `serde`.

To learn more, run the command again with --verbose.
root@RegalMusty-VM:~/shadowsocks-rust#

如何解决？谢谢回复

**Comment by zonyitoo** [comment]
这个错误太奇怪了。提供一下

```
rustc --version
```

我怀疑是你的机器内存太少了，编译不了。

你的是Linux系统么，去[这里](https://github.com/shadowsocks/shadowsocks-rust/releases)下载`shadowsocks-v1.6.10-release.x86_64-unknown-linux-musl.tar.xz`直接运行试试看

**Comment by luckypoem** [comment]
我下载了shadowsocks-v1.6.10-release.x86_64-unknown-linux-musl.tar.xz
解压后，运行./ssserver -c config-for-ss-rust.json
然后在本地机器可以正常翻墙。

**Comment by luckypoem** [comment]
root@RegalMusty-VM:~# rustc --version
rustc 1.23.0 (766bd11c8 2018-01-01)
root@RegalMusty-VM:~#

**Comment by zonyitoo** [comment]
那之后就直接使用这些预编译的Binary吧。你使用的这一台VM，内存分配太少了，无法正常编译。

**Comment by luckypoem** [comment]
root@RegalMusty-VM:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            512         374           0          34         137           6
Swap:             0           0           0
root@RegalMusty-VM:~# 

有可能是内存分配太少了，无法正常编译。

**Comment by zonyitoo** [comment]
So, problem solved?

**Comment by luckypoem** [comment]
yes.tks

**Comment by luckypoem** [comment]
我重启了linux vps.这次有足够的内存，但还是编译失败，不知为何？

root@RegalMusty-VM:~/shadowsocks-rust# cargo build --release
   Compiling libc v0.2.35
   Compiling serde v1.0.27
   Compiling checked_int_cast v1.0.0
   Compiling termcolor v0.3.3
   Compiling xattr v0.1.11
   Compiling iovec v0.1.1
   Compiling atty v0.2.6
   Compiling subprocess v0.1.12
   Compiling time v0.1.39
   Compiling memchr v2.0.1
   Compiling num_cpus v1.8.0
   Compiling rand v0.3.20
   Compiling rand v0.4.2
   Compiling rayon-core v1.3.0
   Compiling unicode-bidi v0.3.4
   Compiling coco v0.1.1
   Compiling unreachable v1.0.0
   Compiling filetime v0.1.14
   Compiling net2 v0.2.31
   Compiling log v0.4.1
   Compiling bzip2-sys v0.1.6
   Compiling miniz-sys v0.1.10
   Compiling miniz_oxide_c_api v0.1.1
   Compiling crc v1.7.0
   Compiling foreign-types v0.3.2
   Compiling miniz_oxide v0.1.1
   Compiling block-buffer v0.3.3
   Compiling num-integer v0.1.35
   Compiling serde_json v1.0.9
   Compiling openssl-sys v0.9.23
   Compiling base64 v0.9.0
   Compiling typenum v1.9.0
   Compiling qrcode v0.5.0
   Compiling textwrap v0.9.0
   Compiling bytes v0.4.5
   Compiling msdos_time v0.1.5
   Compiling aho-corasick v0.6.4
   Compiling futures-cpupool v0.1.8
   Compiling idna v0.1.4
   Compiling thread_local v0.3.5
   Compiling tar v0.4.14
   Compiling log v0.3.9
   Compiling num-iter v0.1.34
   Compiling clap v2.29.0
error: Could not compile `clap`.

To learn more, run the command again with --verbose.
root@RegalMusty-VM:~/shadowsocks-rust# free -m
              total        used        free      shared  buff/cache   available
Mem:            512         146         350           7          15         297
Swap:             0           0           0
root@RegalMusty-VM:~/shadowsocks-rust#

**Comment by zonyitoo** [comment]
512M内存？肯定编不过的哈。我的512的也编不了。至少1G以上的内存才能编。

**Comment by luckypoem** [comment]
hi.我搞了个1 gb的vps:
root@yms:~/shadowsocks-rust# free -m
             total       used       free     shared    buffers     cached
Mem:           997        702        294          3         11        572
-/+ buffers/cache:        118        878
Swap:         1903          1       1902
root@yms:~/shadowsocks-rust#

但是依然遇错：
root@yms:~/shadowsocks-rust# cargo build --release
显示：
...
Compiling libsodium-ffi v0.1.11
error: failed to run custom build command for `libsodium-ffi v0.1.11`
process didn't exit successfully: `/root/shadowsocks-rust/target/release/build/libsodium-ffi-4014b9b0ded51fb0/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rerun-if-env-changed=SODIUM_BUILD_STATIC
--- stderr
thread 'main' panicked at 'Missing libsodium library in your system, try to use SODIUM_BUILD_STATIC=yes to build it from source', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libsodium-ffi-0.1.11/build.rs:41:23
note: Run with `RUST_BACKTRACE=1` for a backtrace.
root@yms:~/shadowsocks-rust#

怎么解决？谢谢你

**Comment by luckypoem** [comment]
不知怎么回事，出现了划线。不会去掉划线，楼主帮忙去掉一下。

**Comment by luckypoem** [comment]
哦，先编译libsodium就可以了：
wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
tar zxvf libsodium-1.0.16.tar.gz
cd libsodium-1.0.16
./configure
make
make install
ldconfig

**Comment by zonyitoo** [comment]
```
Missing libsodium library in your system, try to use SODIUM_BUILD_STATIC=yes to build it from source
```
