### ISSUE TITLE
sslocal rejects config file

### ISSUE THREAD

**Issue by bigli0n** [shadowsocks/shadowsocks-rust#930]
Have been using shadowsocks-libev for years, and I guess the config file format is different for the rust port? When I try to use my config.json file (systemd service, sslocal running with the -c option, I get these errors:

`server`, `server_port`, `method`, `password` must be provided together

What is the _correct_ way to set this file up. Does anyone have a working configuration? The examples provided aren't very clear on this. All of these values are in the file as per the shadowsocks format, as far as I know and it's working on the server

**Comment by zonyitoo** [comment]
You should at least post your configuration file for reproducing.

**Comment by bigli0n** [comment]
It ended up being a small typo, I recreated the file and it works flawlessly, thanks. Closing issue
