### ISSUE TITLE
Permissions to run ss-local in Tun mode

### ISSUE THREAD

**Issue by bigli0n** [shadowsocks/shadowsocks-rust#933]
What permissions are required to run ss-local in tun mode on a debian-based system, as a user other than root? I get "permission denied" when I try it either from the command line or via a systemd service. Doing this with tun2socks and scripts works but it's clunky and I'd rather just use ss-local. I've tried granting various capabilities with CapabilityBoundingSet= but nothing seems to work, same for setcap

**Comment by zonyitoo** [comment]
You may try to run with `strace` and see which syscall returns `EPERM`.

**Comment by bigli0n** [comment]
I have found the issue: running sslocal in tun mode is very insecure. After granting CAP_NET_ADMIN to sslocal binary, I was able to get it working via CLI, but running it as a systemd service with even light sandboxing fails. I think this is a huge problem. I can run sslocal in proxy mode with many of the sandboxing options enabled, with no issues, and then combine it with tun2socks and a little routing via script, all with minimal privileges and system access. But in tun mode sslocal requires access to huge swaths of the filesystem and kernel which is unacceptable. Why does sslocal need access to kernel logs and tunables, or control groups? Why is the ability to escalate privileges necessary, when I have already allowed it everything it should need? OpenVpn can run with most of the below options enabled but shadowsocks in tun mode fails and that is concerning considering it's intended purpose makes it, and thus anyone using it, a target of some very technically sophisticated state-actors. Below are some of the sandboxing options provided by systemd, which _should_ be used whenever possible. 

[Service]
Type=
User=
Group=
WorkingDirectory=
ProtectControlGroups=
ProtectKernelTunables=
ProtectKernelLogs=
ProtectSystem=
ProtectHome=
ProtectKernelModules=
ProtectProc=
ProtectHostname=
LockPersonality=
MemoryDenyWriteExecute=
RestrictNamespaces=
RestrictSUIDSGID=
NoNewPrivileges=
PrivateTmp=
PrivateIPC=
PrivateDevices=

**Comment by database64128** [comment]
I always find it baffling and a little bit hilarious when someone with little knowledge of security or what they are doing makes wild claims about something they clearly don't understand. Well, good luck with your security theater I guess.

**Comment by bigli0n** [comment]
Did I say I was an expert? Nope. I am simply asking why this program needs access to this stuff. If I am so ignorant, please enlighten me as to where I'm wrong. Hopefully I _am_  misunderstanding what's going on here but it seems pretty simple to me. So please explain this instead of just insulting me, because I am willing to listen database64128. That's how we learn

**Comment by bigli0n** [comment]
I see. It's just us ignorant plebian users that think alpha release software downloaded from the internet shouldn't run with root privileges. The real security experts such as yourself run everything as root with full access to their systems because it's fun, and I guess I'm hallucinating when I get error messages such as "operation not permitted" when trying to launch a binary that has any kind of restriction placed on it by the init system

**Comment by zonyitoo** [comment]
https://www.kernel.org/doc/Documentation/networking/tuntap.txt

You could read the document first. `CAP_NET_ADMIN` is mandatory for opening `/dev/net/tun`.

You don't need to run with `root` user, but any users that have `CAP_NET_ADMIN`.

https://unix.stackexchange.com/questions/557306/how-to-allow-non-root-user-to-create-tun-devices

**Comment by zonyitoo** [comment]
Actually you can just do it in systemd:

```
[Service]
CapabilityBoundingSet=CAP_NET_ADMIN
AmbientCapabilities=CAP_NET_ADMIN
```

**Comment by database64128** [comment]
> It also make me curious that how other applications, like OpenVPN or Tor, create tun devices without `CAP_NET_ADMIN`?

They do need `CAP_NET_ADMIN`. Here's the content of `/usr/lib/systemd/system/openvpn-client@.service`:

```service
[Unit]
Description=OpenVPN tunnel for %I
After=syslog.target network-online.target
Wants=network-online.target
Documentation=man:openvpn(8)
Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO

[Service]
Type=notify
PrivateTmp=true
WorkingDirectory=/etc/openvpn/client
ExecStart=/usr/bin/openvpn --suppress-timestamps --nobind --config %i.conf
User=openvpn
Group=network
AmbientCapabilities=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE
LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
ProtectSystem=true
ProtectHome=true
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by zonyitoo** [comment]
I think problem is solved.
