### ISSUE TITLE
High memory usage after short bursts of DNS queries

### ISSUE THREAD

**Issue by dmi-dmi-dmi** [shadowsocks/shadowsocks-rust#939]
I noticed that `sslocal` (ver. 1.14.3) memory usage goes up when there is a burst of DNS traffic. I guess using additional memory is somewhat normal.

The problem is that it never goes down. 

For example, when I start sslocal it consumes about 5mb RAM and it continues to use around that amount when I do my usual web-surfing. Now, when there is a spike in DNS traffic sslocal will start consuming more and more memory which won't be released back even after hours of idling.

An easy way (for me at least) to check this is to open a dozen of tabs with [https://browserleaks.com/dns](https://browserleaks.com/dns). Said page tries to resolve 100 randomly generated domain names - hence generating DNS traffic. After toying with this page for 5-10 minutes I can see that sslocal consumes 700mb - 800mb of RAM which goes down to 500mb-600mb in a few minutes but it never goes back to the range of  10mb-15mb which I see with normal usage.

sslocal is started with this command
```
/usr/bin/sslocal --udp-timeout 60 -c /etc/shadowsocks/rust/config.json 
```

Following config is used
```
> cat /etc/shadowsocks/rust/config.json 
{
    "server": "...",
    "server_port": ...,
    "password": "...",
    "method": "chacha20-ietf-poly1305",
    "locals": [
    	{
		"local_address": "127.0.0.1",
		"local_port": 1082,
		"mode": "tcp_and_udp"
	},
	{
		"protocol": "http",
		"local_address": "127.0.0.1",
		"local_port": 1080
	}
    ],
    "mode": "tcp_and_udp"
}
```

**Comment by zonyitoo** [comment]
It should related to the memory allocator of Rust, which won't return allocated memory to system immediately after they are freed. You could also limits the amount of UDP associations via `--udp-max-associations`.

**Comment by database64128** [comment]
This is just how the default glibc allocator behaves. You can try [other allocators](https://github.com/shadowsocks/shadowsocks-rust#memory-allocators) by building with, for example, `--features jemalloc`.

**Comment by dmi-dmi-dmi** [comment]
> won't return allocated memory to system immediately after they are freed

but will it return later? I mean if it does return memory to the OS at a later stage then I would prefer to stick with the default allocator, I guess. I am not really constrained with memory nor I have conducted extensive testing with waiting significant amount of time.

> You can try [other allocators](https://github.com/shadowsocks/shadowsocks-rust#memory-allocators) by building with, for example

Which allocator would you recommend to try out?

**Comment by zonyitoo** [comment]
I don’t know. Previous tests shows that it won’t return to system even after half an hour.

**Comment by database64128** [comment]
> Which allocator would you recommend to try out?

I think `jemalloc` is a lot more active in returning memory to system.

**Comment by dmi-dmi-dmi** [comment]
Quick test shows that `snmalloc` and `jemalloc` seem to be better in terms of returning memory. Yet memory usage with them grows anyway but at a much slower rate.

I think for simplicity I will stick to the distro supplied version of `shadowsocks-rust` and just add `MemoryMax` constraint for `sslocal` in the systemd service file so it is restarted.
