### ISSUE TITLE
can't stat 'target/debug/sslocal': No such file or directory

### ISSUE THREAD

**Issue by e2ge** [shadowsocks/shadowsocks-rust#94]
when I used "cargo build --release" to compile ss-rust in docker alpine, 
after "make install",  a error appeared:

"can't stat 'target/debug/sslocal': No such file or directory"

it seems that "make install" doesn't find the "target/release/" folder
Replacing to"cargo install --root /usr/local" can solve this error.

**Comment by zonyitoo** [comment]
Hmm, `Makefile` is just for generating `.deb` package.

```
cargo install --root /usr/local
```

is recommended.

**Comment by e2ge** [comment]
Thanks. I followed the README.md to find this error.
You should change the README.md to "make install TARGET=release", because build command is "cargo build --release"

**Comment by zonyitoo** [comment]
Good point.
