### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by maximilize** [shadowsocks/shadowsocks-rust#947]
I would love to know a little more about the status of this project. Is it still under active development? I can see that the last stable release is from April this year, and the next alpha is stuck since July.
Are there any release plans or so?

**Comment by zonyitoo** [comment]
The latest Alpha versions are for the new 2022 protocol, which is still require more comments by users to use in their environment.

The next stable release may be published at the end of the year.

> Is it still under active development?

No. It would keep stable for a long time.
