### ISSUE TITLE
Syntax error on MIPS router

### ISSUE THREAD

**Issue by Yejia995** [shadowsocks/shadowsocks-rust#954]
I tried to run ssserver on my router, which is mips,
the process terminates with an error message:
`./ssserver: line 1: syntax error: unexpected "("`
I tried both the musl build and gnu build, but got the same error message.
It might be a shell issue,
and the shell on router is ash.
I think there's no mistake in the config:
```
{
    "server": "0.0.0.0",
    "server_port": 8388,
    "password": "123456",
    "method": "aes-256-gcm",
    "mode": "tcp_and_udp"
}
```
Is there anything I need to fix?
or is is possible to run ssserver on mips router?

**Comment by zonyitoo** [comment]
1. You may try to use mips and mipsel and see if anything changed.
2. Cross compile one by yourself.

**Comment by database64128** [comment]
> the process terminates with an error message:

This message was from your shell, not from `ssserver`. It looks like you were trying to run some kind of script, but there were syntax errors. This has nothing to do with shadowsocks-rust.

**Comment by Yejia995** [comment]
The script is just `./server -c config.json`. 
While after changing from mips to mipsel rust, there's no error message like `./ssserver: line 1: syntax error: unexpected "("`, but sadly it just stop running with no output:
```
root@router:/etc/ssserver# ./ssserver -c config.json
root@router:/etc/ssserver# 
```

**Comment by zonyitoo** [comment]
Then you will have to compile it yourself. The prebuilt binaries couldn't run on your CPU.

**Comment by Yejia995** [comment]
> Then you will have to compile it yourself. The prebuilt binaries couldn't run on your CPU.

OK, I'll try to compile one. Thank you so much!
