### ISSUE TITLE
Use X-Forwarded-For header for IP addresses

### ISSUE THREAD

**Issue by Venem** [shadowsocks/shadowsocks-rust#957]
For those of us that run Shadowsocks behind a reverse proxy, all connections look as if they're coming from the same place: the proxy.

Would it be possible to use the X-Forwarded-For header in Shadowsocks? This would mean that connection attempts can be monitored with fail2ban and brute-force attacks could be mitigated.

**Comment by zonyitoo** [comment]
shadowsocks runs on Transport Layer, which are TCP, UDP, ... So you can always put anything on the Application Layer, such as HTTP.
