### ISSUE TITLE
请教ipv6的tcp流量如何通过ip6tables转发到代理端口的？

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-rust#967]
据说IPv6是不支持REDIRECT的，我设置shadowsocks-rust的客户端，如下：
		{
			"local_address":"::",
			"protocol": "redir",
			"mode": "tcp_and_udp",
			"local_port":1234
		},
执行显示sslocal的1234端口对于TCP协议启动的是REDIRECT，对UDP协议启动的是TPROXY。
但是IPv6是不支持REDIRECT的（是这样吗？）所以没法通过ip6tables 将TCP流量REDIRECT到1234端口。又因为sslocal的TCP端口是REDIRECT的，设置ip6tables 将TCP流量TPROXY到1234端口，也是不通的。有大侠处理过这样的问题吗？谢谢！

**Comment by zonyitoo** [comment]
1. Use `"tcp_redir": "tproxy"` to switch TCP mode to TPROXY
2. `ip6tables` of course could support IPv6 REDIRECT, refer to this [example configuration](https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/iptables_mixed.sh)

**Comment by tianlichunhong** [comment]
> 1. Use `"tcp_redir": "tproxy"` to switch TCP mode to TPROXY
> 2. `ip6tables` of course could support IPv6 REDIRECT, refer to this [example configuration](https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/iptables_mixed.sh)

机器上同样的一条路由：
ip6tables -t mangle -A PREROUTING -p tcp -m set --match-set gfwlist6 dst -j TPROXY --on-ip ::1 --on-port 1238 --tproxy-mark 2
端口换成xray的"dokodemo-door",的端口,正常使用。换成1.15.0-alpha.9 的sslocal的不通。已经用了"tcp_redir": "tproxy"的参数。就算ip6tables使用redirect，sslocal也换成redirect，也不通。但是IPv4的设置，一切正常。另外ipv6是没有nat的，除非专门设置成nat的方式，所以我想redirect是不可以的。因为redirect是居于表 -t nat的。而tproxy是居于表 -t mangle.

**Comment by zonyitoo** [comment]
I use that script everyday. I can confirm sslocal works for IPv6 with both redirect and tproxy.

**Comment by zonyitoo** [comment]
I just came up with an idea:

You are configuring TPROXY or REDIRECT to `::1`, so did you run `sslocal` with a local instance listening on `::1`?
