### ISSUE TITLE
请问怎么使用obfs插件

### ISSUE THREAD

**Issue by foxconndmd** [shadowsocks/shadowsocks-rust#97]
ssserver -s "[::]:8388" -m "aes-256-gcm" -k "hello-kitty" --plugin "obfs-server" --plugin-opts "obfs=tls"
错误如下：
[2018-03-06][18:10:28.058133615][INFO] ShadowSocks 1.6.12
thread 'main' panicked at 'Failed to start plugin "obfs-server", err: No such file or directory (os error 2)', src/plugin/mod.rs:74:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by foxconndmd** [comment]
解决了，要安装 simple-obfs。

**Comment by hookover** [comment]
怎么安装呢？
