### ISSUE TITLE
It is recommended to use flutter to develop UI, which can support all platforms

### ISSUE THREAD

**Issue by qq805005062** [shadowsocks/shadowsocks-rust#986]
It is recommended to use flutter to develop UI, which can support all platforms
建议使用flutter开发UI，可以支持所有平台
For example: rustdesk project
例如：rustdesk工程
https://github.com/rustdesk/rustdesk.git

**Comment by zonyitoo** [comment]
No relation with this project.

**Comment by qq805005062** [comment]
> No relation with this project.

我知道与本项目无关啊，我是建议你用flutter开发UI，然后可以支持所有平台
I know it has nothing to do with this project, I suggest you use flutter to develop UI, and then you can support all platforms

**Comment by database64128** [comment]
The profile of the developer literally says "**Backend** developer". 😄

And you used the infamous RustDesk as the example, as if Rust code couldn't be written [as shitty as this one](https://news.ycombinator.com/item?id=31456007).
