### ISSUE TITLE
Server started and port is active but no data transfer!

### ISSUE THREAD

**Issue by nDman** [shadowsocks/shadowsocks-rust#989]
Hi,
I have installed shadowsocks-rust by docker and it running but I can't get any data. 
This is my config file:
```
{
    "server":"0.0.0.0",
    "server_port":2767,
    "password":"--------",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
}
```
and these are docker containers:

```
docker run --name sslocal-rust \
  --restart always \
  -p 1080:1080/tcp \
  -v /etc/shadowsocks-rust:/etc/shadowsocks-rust \
  -dit ghcr.io/shadowsocks/sslocal-rust:latest

docker run --name ssserver-rust \
  --restart always \
  -p 2767:2767/tcp \
  -p 2767:2767/udp \
  -v /etc/shadowsocks-rust:/etc/shadowsocks-rust \
  -dit ghcr.io/shadowsocks/ssserver-rust:latest
```
What could be the problem?

I also have a ShadowsockR server running perfectly on port 443.

**Comment by zonyitoo** [comment]
No idea. But the default configuration path should be `/etc/shadowsocks-rust/config.json`: https://github.com/shadowsocks/shadowsocks-rust/blob/eccebfa37f5358b94cafb03d5301982225a6c63f/Dockerfile#L46

**Comment by dev4u** [comment]
No `nameserver` in rust ss doc.

**Comment by zonyitoo** [comment]
> No `nameserver` in rust ss doc.

It doesn’t matter.

**Comment by nDman** [comment]
Ok, I tried ones more to install ss-rust.  This time installed it by [Shadowsocks-rust Docker Image by Teddysun](https://hub.docker.com/r/teddysun/shadowsocks-rust) (it is latest version).

The server is up and port is open but I get this error in **Proxifier** proxy tester:
![2022-11-02_00-38-41](https://user-images.githubusercontent.com/5911295/199341983-1444566d-ff8b-448f-98f9-e19900d867b9.png)

and it makes these lines in docker logs:
```
INFO  received SIGTERM, exiting
INFO  shadowsocks server 1.14.3 build 2022-04-04T17:17:20.738520637+00:00
INFO  shadowsocks tcp server listening on 0.0.0.0:2767, inbound address 0.0.0.0:2767
INFO  shadowsocks udp server listening on 0.0.0.0:2767
WARN  handshake failed, maybe wrong method or key, or under replay attacks. peer: 93.118.172.126:12992, error: invalid tag-in
```

This is server config file:
```
{
    "server":"0.0.0.0",
    "server_port":2767,
    "password":"----------",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "nameserver":"8.8.8.8",
    "mode":"tcp_and_udp",
}
```
and client config:
```
{
    "server": "my_host_ip",
    "server_port": 2767,
    "password": "----------",
    "method": "chacha20-ietf-poly1305",
    "local_address": "127.0.0.1",
    "local_port": 1097,
    "mode":"tcp_and_udp"
}
```
port scanner output:
![2022-11-02_00-44-29](https://user-images.githubusercontent.com/5911295/199343127-d594c219-8dea-4737-925f-61dd0ea5e658.png)

any idea about the problem?

**Comment by zonyitoo** [comment]
> WARN  handshake failed, maybe wrong method or key, or under replay attacks. peer: 93.118.172.126:12992, error: invalid tag-in

Is this ` peer: 93.118.172.126:12992` seems familiar to you? You may add `-vvv` on command line arguments and see what exactly `ssserver` received from clients.
