### ISSUE TITLE
可以集成kcp吗？

### ISSUE THREAD

**Issue by coolicer** [shadowsocks/shadowsocks-rust#99]
搬瓦工开kcp比没开快好几倍，但是kcp是另外安装，有没有可能出一个版本，可以挂上去

**Comment by zonyitoo** [comment]
不需要集成。你可以自己写一个kcp的插件，加进plugin参数就可以了。

**Comment by coolicer** [comment]
就是还要另外部署kcp是吧

**Comment by zonyitoo** [comment]
就跟这个一样

```
$ sslocal -b "127.0.0.1:1080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty" --plugin "obfs-local" --plugin-opts "obfs=tls"
```

把 `obfs-local` 改成 `kcp-local` 什么的就可以了啊。

至于 `kcp-local` 用哪个实现就看你自己选了。[我自己随手写了个](https://github.com/zonyitoo/sskcp-proxy)，没用心写，性能不怎么好。

你说的把kcp单独部署，也是完全没有问题的。灵活组合就好，不需要特意支持。

**Comment by coolicer** [comment]
好的，谢谢
