### ISSUE TITLE
请问编译需要多大内存 

### ISSUE THREAD

**Issue by MedievalSteel** [shadowsocks/shadowsocks-rust#993]
电脑 8GB 内存，用 `````cargo build --features "aead-cipher-extra" -r````` 编译的时候爆内存了，不知在 Releases 里可否直接提供 aead-cipher-extra？

**Comment by zonyitoo** [comment]
I don't think so. These ciphers are not recommended.

BTW, it shouldn't require more than 2GB memories, please double check your configuration.
